### ISSUE TITLE
snowflake-sdk errors on connect

### ISSUE THREAD

**Issue by 0xRapid** [oven-sh/bun#10044]
### What version of Bun is running?

1.1.2

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Use the following code to get the error (you don't need to change any details inside the create connection object).

```
import snowflake from 'snowflake-sdk';

(() => {
    var connection = snowflake.createConnection({
        account: "account",
        username: "user",
        password: "password",
        application: "application"
    });
    connection.connect(
        function(err, conn) {
            if (err) {
                console.error('Unable to connect: ' + err.message);
            }
            else {
                console.log('Successfully connected to Snowflake.');
                // Optional: store the connection ID.
            }
        }
    );
})()
```

### What is the expected behavior?

Connection to be established. 

### What do you see instead?

```
 Unexpected error from calling callback function TypeError: this.constructExponentialBackoffStrategy is not a function. (In 'this.constructExponentialBackoffStrategy()', 'this.constructExponentialBackoffStrategy' is undefined)\n    at prepareRequestOptions (C:\\Users\\User\\WebstormProjects\\bun\\node_modules\\snowflake-sdk\\lib\\http\\base.js:212:20)\n    at <anonymous> (C:\\Users\\User\\WebstormProjects\\bun\\node_modules\\snowflake-sdk\\lib\\http\\base.js:79:54)\n    at sendHttpRequest (C:\\Users\\User\\Web"}
```

### Additional information

The reproduction is pretty easy as you can see, hopefully this can be solved :).

**Comment by Electroid** [comment]
Stepping through the debugger, it looks like the `constructExponentialBackoffStrategy` function is set on the prototype, but it's not saved when the code is imported and run later.

https://github.com/snowflakedb/snowflake-connector-nodejs/blob/ec00a1de570bf3be65c3424478c7882b12f1c9d0/lib/http/node.js#L23

**Comment by 0xRapid** [comment]
If I am searching for that error btw, "is not a function" it seems to have happened a lot here. (Many issues about it, not specifically just in snowflake-sdk)

**Comment by 0xRapid** [comment]
Still happens in 1.1.4

**Comment by 0xRapid** [comment]
Can you add a label "company willing to use bun in production"? @Jarred-Sumner @Electroid 

I have written about it in many places, those issues need to get priority, you can check some of the client-list of snowflake, you will understand libraries like this can not be left out of the equation.

**Comment by khromov** [comment]
Can confirm the same issue here using `snowflake-sdk@1.11.0`. The error we are facing is:

```bash
❌ Import failed 214 |   if (this._connectionConfig.agentClass) {
215 |     mock = {
216 |       agentClass: this._connectionConfig.agentClass
217 |     };
218 |   }
219 |   const backoffStrategy = this.constructExponentialBackoffStrategy();
                                     ^
TypeError: this.constructExponentialBackoffStrategy is not a function. (In 'this.constructExponentialBackoffStrategy()', 'this.constructExponentialBackoffStrategy' is undefined)
      at prepareRequestOptions (/Users/x/Documents/GitHub/project/node_modules/snowflake-sdk/lib/http/base.js:219:32)
      at /Users/x/Documents/GitHub/project/node_modules/snowflake-sdk/lib/http/base.js:38:48
      at sendHttpRequest (/Users/x/Documents/GitHub/project/node_modules/snowflake-sdk/lib/services/sf.js:652:23)
      at /Users/x/Documents/GitHub/project/node_modules/snowflake-sdk/lib/services/sf.js:707:5
      at sendRequest (/Users/x/Documents/GitHub/project/node_modules/snowflake-sdk/lib/services/sf.js:1157:13)
      at /Users/x/Documents/GitHub/project/node_modules/snowflake-sdk/lib/services/sf.js:1159:3
      at /Users/x/Documents/GitHub/project/node_modules/snowflake-sdk/lib/services/sf.js:975:8
      at transitionTo (/Users/x/Documents/GitHub/project/node_modules/snowflake-sdk/lib/services/sf.js:151:20)
      at /Users/x/Documents/GitHub/project/node_modules/snowflake-sdk/lib/services/sf.js:170:5
      at /Users/x/Documents/GitHub/project/node_modules/snowflake-sdk/lib/services/sf.js:927:25

error: script "dev:backfill" exited with code 1
```

The error is triggered when the first `query` is called in this code:

```ts
/* eslint-disable no-console */
import snowflake from 'snowflake-sdk';
import type { Connection } from 'snowflake-sdk';
import getConfig from '../config';
import { SnowflakeArticle } from '../types/SnowflakeArticle';

let connection: Connection | null = null;

export const query = (
  sqlText: string,
  config: any = {},
): Promise<SnowflakeArticle[] | Error> =>
  new Promise((resolve, reject) => {
    if (!connection) {
      connection = snowflake.createConnection(getConfig().snowflake);

      console.log('❄️ Connecting to Snowflake...');

      // eslint-disable-next-line no-unused-vars
      connection.connect((err) => {
        console.log('CONNECTED');
        if (err) {
          console.error(`Unable to connect: ${err.message}`);
          reject(new Error(err.toString()));
        } else {
          console.log(
            `❄️ Initializing Snowflake - successfully connected as id: ${
              connection && connection.getId()
            }`,
          );
        }
      });
    }

    if (config.debug) {
      console.log(`👔 Executing: ${sqlText}`);
    }

    connection.execute({
      sqlText,
      complete(err, stmt, rows) {
        if (err) {
          console.error(
            `Failed to execute statement due to the following error: ${err.message}`,
          );
          reject(err);
        } else {
          // console.log(`❄️ Successfully executed statement: ${stmt.getSqlText()}`);
          resolve(rows as SnowflakeArticle[]);
        }
      },
    });
  });

export function getConnection() {
  return connection;
}

export function disconnect() {
  if (connection && connection.isUp() !== null) {
    console.log('😵 Disconnecting from Snowflake!');
    connection.destroy(() => {
      // do nothing
    });
  } else {
    console.log('✖️ Snowflake was already disconnected!');
  }
}
```

**Comment by 0xRapid** [comment]
Still happens in 1.25. 

Any news on that?
