### ISSUE TITLE
Bun stalls for ages to do the first request with axios for some reason. Node does it instantly.

### ISSUE THREAD

**Issue by touhidurrr** [oven-sh/bun#10082]
### What version of Bun is running?

1.1.9+bb13798d9

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Run in CMD:
```bash
git clone https://github.com/MHNahib/bd-ftp-checker.git
cd bd-ftp-checker
bun install
bun index.js
```

### What is the expected behavior?

With `node index.js` after 5 seconds:
```
  ____  ____    _____ _____ ____     ____ _               _
 | __ )|  _ \  |  ___|_   _|  _ \   / ___| |__   ___  ___| | _____ _ __
 |  _ \| | | | | |_    | | | |_) | | |   | '_ \ / _ \/ __| |/ / _ \ '__|
 | |_) | |_| | |  _|   | | |  __/  | |___| | | |  __/ (__|   <  __/ |
 |____/|____/  |_|     |_| |_|      \____|_| |_|\___|\___|_|\_\___|_|

- M. H. Nahib



❌ : http://old.circleftp.net 500
❌ : http://cds1.discoveryftp.net 500
❌ : http://cds2.discoveryftp.net 500
❌ : http://cds3.discoveryftp.net 500
❌ : http://play.ebox.live 500
❌ : http://dflix.discoveryftp.net 500
❌ : http://sg-cdn.ihub.live:8787/download/games 500
❌ : http://103.120.165.196 500
✅ : http://103.112.63.21 200
✅ : http://abistation.net/ 200
✅ : http://103.103.239.66 200
❌ : http://www.ddnbd.fun 500
❌ : http://crazyctg.com 500
❌ : http://ctgmovies.com 500
✅ : https://uniquenetbd.com 200
✅ : https://inspirebroadband.net 200
❌ : http://file.tajpata.com 500
✅ : https://www.discoverynetbd.com 200
✅ : http://103.17.181.43 200
✅ : https://icctalk.com 200
✅ : https://fiber.colbd.com 200
✅ : https://circlenetworkbd.net 200
✅ : https://deshnetbd.com 200
✅ : http://www.onesky.com.bd 200
✅ : https://www.mazedanetworks.net 200
✅ : https://iccfios.net 200
✅ : http://103.77.252.113 200
✅ : http://www.showtimebd.com 200
✅ : http://162.12.215.254 200
✅ : https://carnival.com.bd 200
✅ : http://skyviewonlineltd.com 200
✅ : https://pastebin.com/VpXpmMjQ 200
✅ : https://icc.com.bd 200
✅ : http://www.uniquedownloadbd.com 200
✅ : http://www.antbd.net 200
✅ : https://www.1netbd.com 200
❌ : http://khulnaflix.net 500
❌ : http://file.khulnaflix.net 500
✅ : https://fnfonline.wixsite.com/fnfonline 200
✅ : https://sunonlinebd.com 200
❌ : http://movies.fnfonlinebd.com 500
✅ : http://amarnetsystem.com 200
✅ : https://sambd.com 200
✅ : https://www.cogentbroadband.net 200
✅ : https://www.dfnbd.net 200
❌ : http://dhakaftp.com/Data 500
❌ : http://dhakaftp.com 500
✅ : https://linktech.net.bd 200
✅ : https://ksnetworkbd.com 200
❌ : http://103.43.148.68 500
❌ : http://220.152.114.214 500
❌ : http://103.203.94.1:8065 500
❌ : http://45.118.247.178:8096 500
❌ : http://45.118.247.178 500
❌ : http://media.dfnbd.net 500
✅ : http://103.237.37.181 200
✅ : https://www.mojaloss.stream 200
❌ : http://103.76.196.90 500
✅ : https://www.antbd.com 200
✅ : https://sunplex.net 200
✅ : http://www.candybd.net 200
✅ : https://planet3communication.com 200
❌ : http://candybd.net/upload/source/movies 500
✅ : http://www.triangle.com.bd 200
✅ : https://www.mcnbd.com 200
✅ : https://ddnbd.com 200
❌ : http://www.freedownloadbd.com 500
❌ : http://103.3.226.208 500
❌ : http://mcbroadbandbd.com 500
❌ : http://ftp.mcnbd.com 500
❌ : http://fs.amrbd.com 500
❌ : http://fs2.amrbd.com 500
✅ : https://sites.google.com/view/mcnbdix 200
❌ : http://come2speed.com 500
❌ : https://www.rangdhanu.live 500
```

### What do you see instead?

With `bun index.js` after 5 seconds:
```
  ____  ____    _____ _____ ____     ____ _               _
 | __ )|  _ \  |  ___|_   _|  _ \   / ___| |__   ___  ___| | _____ _ __
 |  _ \| | | | | |_    | | | |_) | | |   | '_ \ / _ \/ __| |/ / _ \ '__|
 | |_) | |_| | |  _|   | | |  __/  | |___| | | |  __/ (__|   <  __/ |
 |____/|____/  |_|     |_| |_|      \____|_| |_|\___|\___|_|\_\___|_|

- M. H. Nahib



```

### Additional information

I am not sure why Bun is stalling for so long here but it is not supposed to happen.

**Comment by Electroid** [comment]
On macOS, it gets farther but runs into:

```js
2985 |           // remove the content-encoding in order to not confuse downstream operations
2986 |           delete res.headers['content-encoding'];
2987 |           break;
2988 |         case 'br':
2989 |           if (isBrotliSupported) {
2990 |             streams.push(zlib__default["default"].createBrotliDecompress(brotliOptions));
                                ^
error: zlib.createBrotliDecompress is not implemented
      at node:zlib:2269:65
      at handleResponse (/Users/ashcon/Desktop/code/sandbox/bd-ftp-checker/node_modules/axios/dist/node/axios.cjs:2990:26)
      at /Users/ashcon/Desktop/code/sandbox/bd-ftp-checker/node_modules/follow-redirects/index.js:398:5
      at /Users/ashcon/Desktop/code/sandbox/bd-ftp-checker/node_modules/follow-redirects/index.js:91:7
      at node:http:914:115
```

Related: #267

**Comment by touhidurrr** [comment]
> @touhidurrr please run `bun upgrade --canary` and try again

Ok, I just tried canary release `1.1.10-canary.1+c689b2b26` and it looks like the issue has been fixed! It feels like Bun works even faster than Node to run this particular script. Also, I tested under a VPN also and it still feels like it works better than Node.

**Comment by touhidurrr** [comment]
@Jarred-Sumner however, I noticed that some VPN issues remained. First time running ` bunx --bun bd-ftp-checker` under a VPN (Cloudflare Wrap) seemed to get stuck. After turning off VPN and rerunning the command however, it worked instantly. I guess it is a `bun install` issue with `bunx` (running `bun install` alone under a VPN seemed to work fine) ?
