### ISSUE TITLE
Trying to import react native by striping flow types using a runtime plugin

### ISSUE THREAD

**Issue by ceopaludetto** [oven-sh/bun#10083]
### What version of Bun is running?

1.1.2+c8d072c2a

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

I was trying to import `react-native` inside a bun test, so I wrote a plugin to strip flow types from react-native packages, but when I import `react-native` the module get empty.

1. Create the plugin
```ts
// plugin.ts
import type { BunPlugin } from "bun";

import { plugin } from "bun";
import stripTypes from "flow-remove-types";

function stripFlowTypesPlugin(): BunPlugin {
  return {
    name: "strip-flow-types",
    setup: (build) => {
      build.onLoad({ filter: /node_modules\/react-native.*\.jsx?$/ }, async ({ path, loader }) => {
        console.log(`Processing ${path}`);

        const text = await Bun.file(path).text();
        const contents = stripTypes(text).toString();

        return { contents, loader: loader ?? "js" };
      });
    },
  };
}

await plugin(stripFlowTypesPlugin());
```

2. Add into preload section in `bunfig.toml`:
```toml
# bunfig.toml
[test]
preload = ["./plugin.ts"]
```

3. Create a stub test (I'm using dynamic import to avoid errors):
```tsx
// example.spec.tsx
import { describe, expect, it } from "bun:test"

describe("Example", () => {
  it("should", async () => {
    const mod = await import("react-native")
    console.log(mod) // prints -> Module {}
  })
})
```

### What is the expected behavior?

React native should be imported correctly and the modules should be listed

### What do you see instead?

An empty module
<img width="961" alt="Screenshot 2024-04-08 at 16 39 28" src="https://github.com/oven-sh/bun/assets/30508218/7a2623a8-1d6a-40d4-8aff-141fcbee5b66">

### Additional information
When I try to use `require("react-native")` I get this:

```
TypeError: require() async module "/Users/carlos/Documents/Projetos/Javascript/bun-test-react-native/node_modules/react-native/index.js" is unsupported. use "await import()" instead.
```

**Comment by TiBianMod** [comment]
not again the same error, NoNo!!!

is the 4th time this thing is breaking 😢

**Comment by isaachinman** [comment]
Any update or advice on this? React Native is truly terrible to compile with any tool, but I'd love to be able to use Bun.

**Comment by sohenze** [comment]
Any updates?

**Comment by ardeois** [comment]
Still reproducing with Bun 1.2.8

Platform: Darwin 23.6.0 arm64 arm

Even if we load the plugin without any transformation I got the same error.


### Without plugin I get the following error (expected)
```typescript
const mod = await import('@testing-library/react-native');
console.log(mod);
```

```
15 | import typeof ActionSheetIOS from './Libraries/ActionSheetIOS/ActionSheetIOS';
            ^
error: Unexpected typeof
    at {redacted}/node_modules/react-native/index.js:15:8
```

### With plugin (no transformation), I would expect the same error
```javascript
// plugin.ts
import { plugin } from 'bun';

plugin({
    name: 'strip-flow-types',
    setup(build) {
        build.onLoad({ filter: /node_modules\/react-native.*\.jsx?$/ }, async ({ path, loader }) => {
            return { 
                // no transformation at all, simple passthrough
                contents: await Bun.file(path).text(),
                loader: loader ?? 'js' 
            };
        });
    },
});

```

### Actual
I get the following error.
```
22 | var _reactNative = require("react-native");
         ^
TypeError: require() async module "{redacted}/node_modules/react-native/index.js" is unsupported. use "await import()" instead.
      at <anonymous> ({redacted}/node_modules/@testing-library/react-native/build/helpers/accessibility.js:22:5)
 // ...
```

I would expect to have the same `import typeof` error.


@Jarred-Sumner  any advice on plugin `onLoad` that don't seem to load source code the same way as if the plugin was not there?

**Comment by camero2734** [comment]
The plugin works if you just use `fs.readFileSync` instead. I think the issue is that we cannot return a promise in `onLoad` since `react-native` is imported with `require`.

So this works:
```ts
// plugin.ts
import { plugin } from 'bun';
import { readFileSync } from 'node:fs';
// @ts-ignore
import stripTypes from 'flow-remove-types';

plugin({
  name: 'strip-flow-types',
  setup(build) {
    build.onLoad({ filter: /node_modules\/react-native.*\.jsx?$/ }, ({ path, loader, defer, namespace }) => {
      console.log(`Processing file: ${path} with loader: ${loader} and namespace: ${namespace}`);

      const contents = readFileSync(path, 'utf-8');
      const strippedContents = stripTypes(contents).toString();
      return {
        contents: strippedContents,
        loader,
      }
    });
  },
});
```

```ts
// index.test.ts
const mod = await import('@testing-library/react-native');
console.log(mod);
```

Then:
```
bun test --bun --preload=./plugin.ts index.test.ts
```

successfully loads the module:
```ts
Module {
  act: [Function],
  cleanup: [Function: cleanup],
  // ...
}
```

**Comment by jsg2021** [comment]
I'm seeing that any file processed by this plugin (even with `readFileSync` and removing the `async` keyword), the returned module is empty. 

```js
import { readFileSync } from 'node:fs';

import { plugin, type BunPlugin } from 'bun';
// import stripTypes from 'flow-remove-types';

function stripFlowTypesPlugin(): BunPlugin {
	return {
		name: 'strip-flow-types',
		setup(build) {
			build.onLoad(
				// { filter: /(jest|react-native)\/.+\.(js|jsx)$/ },
				{ filter: /.+\.(js|jsx)$/ },
				async ({ path, loader }) => {
					const source = await Bun.file(path).text();
					// const source = readFileSync(path, 'utf-8');
					// Use flow-remove-types to strip the types
					// const contents = stripTypes(source).toString();

					return {
						contents: source,
						loader,
					};
				},
			);
		},
	};
}

// Register the plugin with Bun
plugin(stripFlowTypesPlugin());
```

The straight passthrough is broken, as are stripped flow types :/ 

I've tried forcing the `loader: 'js'`, passing through, ...nothing. All results with an empty modules. The only thing i've gotten to work is the "examples" for onLoad with very short snippets such as:

```
"throw new Error('Please use lodash instead of underscore.')"
```

```
"export default 'simple string';"
```

**Comment by jsg2021** [comment]
@robobun :)

**Comment by robobun** [comment]
Same bug as #19279: source returned from a runtime Bun.plugin onLoad hook that is CommonJS (here react-native's module.exports-based index.js after stripping Flow types) is wrapped as ESM and never evaluated, so import() yields an empty module; the open fix PR #34112 lists both issues and #19279 is where this bug is being consolidated. The separate `require() async module ... is unsupported` error mentioned under additional information is tracked in #30014.

Duplicate of #19279

Please add a 👍 or any extra details over there so it all stays in one place. If this is actually a different problem, say so here and we'll reopen.
