### ISSUE TITLE
bun.exe --bun x @ulixee/cloud start Illegal instruction at address 0x7ff7e0805671

### ISSUE THREAD

**Issue by ducktype** [oven-sh/bun#10117]
### What version of Bun is running?

1.1.3+2615dc742

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

bun.exe --bun x @ulixee/cloud start

### What do you see instead?

  🚚 commander [8/19] Illegal instruction at address 0x7ff7e0805671
???:?:?: 0x7ff7e080590f in ??? (bun.exe)
???:?:?: 0x7ff7dfd3420e in ??? (bun.exe)
???:?:?: 0x7ff7dfc4ed34 in ??? (bun.exe)
???:?:?: 0x7ff7dfc57ff7 in ??? (bun.exe)
???:?:?: 0x7ff7dfe872f4 in ??? (bun.exe)
???:?:?: 0x7ff9e23a257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ff9e324aa57 in ??? (ntdll.dll)

**Comment by kauanlight** [comment]
Managed to solve? Mine is giving this same error but in NEXT and Shadcn

**Comment by ducktype** [comment]
No clue, cleared cache, used canary and old versions...and all versions now show nothing, nothing happens even no more output even simply running bun.exe without args processexplorer and processmonitor show no access to files only windows crash werfault.exe spawning

**Comment by ducktype** [comment]
About bun starting and quitting without any message was about an illegal instruction for my old CPU, windows log in the event log the application crash as [windows - c000001d (Illegal instruction)](https://reverseengineering.stackexchange.com/questions/30809/c000001d-illegal-instruction)
to solve this use the download the "bun baselinewindows build" instead of the standard bun download

**Comment by RiskyMH** [comment]
While I was trying this out, I got a crash lol

```ts
C:\>bun.exe --bun x @ulixee/cloud start
  ⚙️  better-sqlite3 [1/1] prebuild-install warn install LoadLibrary failed: A dynamic link library (DLL) in
============================================================
Bun Canary v1.2.3-canary.37 (1fe2c3b4) Windows x64
Windows v.win11_dt
CPU: sse42 avx avx2 avx512
Args: "node" "C:\Users\<user>\AppData\Local\Temp\bunx-96171257-@ulixee\cloud@latest\node_modules\prebuild-install\bin.js"
Features: Bun.stderr(2) Bun.stdout(2) fetch(2) jsc tsconfig process_dlopen
Builtins: "bun:main" "detect-libc" "node:assert" "node:buffer" "node:crypto" "node:events" "node:fs" "node:http" "node:https" "node:net" "node:os" "node:path" "node:querystring" "node:stream" "node:string_decoder" "node:tls" "node:url" "node:util" "node:util/types" "node:zlib"
Elapsed: 9495ms | User: 609ms | Sys: 328ms
RSS: 0.19GB | Peak: 0.21GB | Commit: 0.24GB | Faults: 51990

panic(main thread): Segmentation fault at address 0x7FFC64189F50
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.2.3/wn21fe2c3bgC3/77//D_CSntdll.dll+97UCSntdll.dll67mvBCSntdll.dllougvBCYKERNEL32.DLL2qsQqmTkrjhHotmplBq1hzpB86uqpCA24//Bg1vijkD

error: Module not found 'C:\Users\<user>\.bun\install\global\node_modules\node-gyp\bin\node-gyp.js'

Bun v1.2.3-canary.37+1fe2c3b42 (Windows x64)

error: install script from "better-sqlite3" exited with 1

```
### crash

Bun v1.2.3-canary ([`1fe2c3b`](<https://github.com/oven-sh/bun/tree/1fe2c3b426f1250b534c9352cbf12bfea0886791>)) on windows x86_64 [RunAsNodeCommand]

Segmentation fault at address 0x7FFC64189F50

- *1 unknown/js code*
- ??? at `0x537df` in ntdll.dll
- ??? at `0xbcdbd` in ntdll.dll
- ??? at `0xbc0e4` in ntdll.dll
- ??? at `0x418ab` in KERNEL32.DLL
- [`Global.zig:120`](<https://github.com/oven-sh/bun/blob/1fe2c3b426f1250b534c9352cbf12bfea0886791/src/Global.zig#L120>): `exit`
- [`javascript.zig:1417`](<https://github.com/oven-sh/bun/blob/1fe2c3b426f1250b534c9352cbf12bfea0886791/src/bun.js/javascript.zig#L1417>): `globalExit`
- [`libuv.zig:604`](<https://github.com/oven-sh/bun/blob/1fe2c3b426f1250b534c9352cbf12bfea0886791/src/deps/libuv.zig#L604>): `subActive`
- [`BunProcess.cpp:2619`](<https://github.com/oven-sh/bun/blob/1fe2c3b426f1250b534c9352cbf12bfea0886791/src/bun.js/bindings/BunProcess.cpp#L2619>): `Bun::Process_functionReallyExit`
- `vmEntryToNative`

Features: process\_dlopen, Bun.stderr, Bun.stdout, fetch, jsc, tsconfig, tsconfig

**Comment by nektro** [comment]
```
❯ ~/src/bun2/build/debug/bun-debug --bun x @ulixee/cloud start
Starting Ulixee Cloud with configuration: {
  maxConcurrentHeroes: 10,
  maxConcurrentHeroesPerBrowser: 10,
  datastoreWaitForCompletion: false,
  heroDataDir: "/var/folders/1f/g5b35_615ds81xl6w9twzksc0000gn/T/.ulixee",
  datastoreStorageDir: "/Users/meghandenny/Library/Application Support/ulixee/datastores",
  argonNotaryId: 1,
}
AddressSanitizer:DEADLYSIGNAL
=================================================================
==83008==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x00016d375a90 sp 0x00016d375a40 T0)
==83008==Hint: pc points to the zero page.
==83008==The signal is caused by a READ memory access.
==83008==Hint: address points to the zero page.
    #0 0x000000000000  (<unknown module>)
    #1 0x00017fdc08c0 in node_register_module_v137+0xb8 (better_sqlite3.node:arm64+0x8c0)
    #2 0x000103a73d00 in node_module_register node.cpp:93
    #3 0x0001998a2ef8 in invocation function for block in dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const+0x1b8 (dyld:arm64+0xfffffffffff56ef8)
    #4 0x0001998df63c  (<unknown module>)
    #5 0x0001998ff588  (<unknown module>)
    #6 0x0001998fc314  (<unknown module>)
    #7 0x0001998fda54  (<unknown module>)
    #8 0x0001998d4b5c  (<unknown module>)
    #9 0x0001998df2dc  (<unknown module>)
    #10 0x0001998a2cb0 in dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const+0xac (dyld:arm64+0xfffffffffff56cb0)
    #11 0x0001998aa66c  (<unknown module>)
    #12 0x0001998a345c in dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&, dyld3::Array<dyld4::Loader const*>&) const+0x130 (dyld:arm64+0xfffffffffff5745c)
    #13 0x0001998a7bec  (<unknown module>)
    #14 0x0001998a3778 in dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const+0x2c8 (dyld:arm64+0xfffffffffff57778)
    #15 0x0001998c7100  (<unknown module>)
    #16 0x0001998bbf58  (<unknown module>)
    #17 0x0001998bba3c  (<unknown module>)
    #18 0x000126c16b0c in dlopen+0x140 (libclang_rt.asan_osx_dynamic.dylib:arm64+0x3eb0c)
    #19 0x000102fd35b4 in Bun::Process_functionDlopen(JSC::JSGlobalObject*, JSC::CallFrame*) BunProcess.cpp:506
    #20 0x000300010034  (<unknown module>)
    #21 0x0001111e9e7c in jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__844_callHelper__dispatch_LowLevelInterpreter64_asm_2527+0x0 (bun-debug:arm64+0x10e76de7c)
    #22 0x000300034160  (<unknown module>)
    #23 0x0001111e88e4 in jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__826_callHelper__dispatch_LowLevelInterpreter64_asm_2527+0x0 (bun-debug:arm64+0x10e76c8e4)
    #24 0x0001111e88e4 in jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__826_callHelper__dispatch_LowLevelInterpreter64_asm_2527+0x0 (bun-debug:arm64+0x10e76c8e4)
    #25 0x0001111e8d18 in jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__829_callHelper__dispatch_LowLevelInterpreter64_asm_2527+0x0 (bun-debug:arm64+0x10e76cd18)
    #26 0x0001111e8d18 in jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__829_callHelper__dispatch_LowLevelInterpreter64_asm_2527+0x0 (bun-debug:arm64+0x10e76cd18)
    #27 0x0001111e8d18 in jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__829_callHelper__dispatch_LowLevelInterpreter64_asm_2527+0x0 (bun-debug:arm64+0x10e76cd18)
    #28 0x0001111e8d18 in jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__829_callHelper__dispatch_LowLevelInterpreter64_asm_2527+0x0 (bun-debug:arm64+0x10e76cd18)
    #29 0x0001111e88e4 in jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__826_callHelper__dispatch_LowLevelInterpreter64_asm_2527+0x0 (bun-debug:arm64+0x10e76c8e4)
    #30 0x0001111e9e7c in jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__844_callHelper__dispatch_LowLevelInterpreter64_asm_2527+0x0 (bun-debug:arm64+0x10e76de7c)
    #31 0x0001111e88e4 in jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__826_callHelper__dispatch_LowLevelInterpreter64_asm_2527+0x0 (bun-debug:arm64+0x10e76c8e4)
    #32 0x0001111e88e4 in jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__826_callHelper__dispatch_LowLevelInterpreter64_asm_2527+0x0 (bun-debug:arm64+0x10e76c8e4)
    #33 0x0001111e9e7c in jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__844_callHelper__dispatch_LowLevelInterpreter64_asm_2527+0x0 (bun-debug:arm64+0x10e76de7c)
    #34 0x0001111e88e4 in jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__826_callHelper__dispatch_LowLevelInterpreter64_asm_2527+0x0 (bun-debug:arm64+0x10e76c8e4)
    #35 0x0001111e88e4 in jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__826_callHelper__dispatch_LowLevelInterpreter64_asm_2527+0x0 (bun-debug:arm64+0x10e76c8e4)
    #36 0x0001111e88e4 in jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__826_callHelper__dispatch_LowLevelInterpreter64_asm_2527+0x0 (bun-debug:arm64+0x10e76c8e4)
    #37 0x0001111e88e4 in jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__826_callHelper__dispatch_LowLevelInterpreter64_asm_2527+0x0 (bun-debug:arm64+0x10e76c8e4)
    #38 0x0001111e9e7c in jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__844_callHelper__dispatch_LowLevelInterpreter64_asm_2527+0x0 (bun-debug:arm64+0x10e76de7c)
    #39 0x0001111e88e4 in jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__826_callHelper__dispatch_LowLevelInterpreter64_asm_2527+0x0 (bun-debug:arm64+0x10e76c8e4)
    #40 0x0001111bf354 in llint_call_javascript+0x4 (bun-debug:arm64+0x10e743354)
    #41 0x00010e2c1c00 in JSC::Interpreter::executeCallImpl(JSC::VM&, JSC::JSObject*, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) Interpreter.cpp:1385
    #42 0x00010e2c2504 in JSC::Interpreter::executeCall(JSC::JSObject*, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) Interpreter.cpp:1400
    #43 0x00010e966ad0 in JSC::call(JSC::JSGlobalObject*, JSC::JSValue, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) CallData.cpp:69
    #44 0x00010e967350 in JSC::profiledCall(JSC::JSGlobalObject*, JSC::ProfilingReason, JSC::JSValue, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) CallData.cpp:90
    #45 0x00010336d844 in Bun::evaluateCommonJSModuleOnce(JSC::VM&, Zig::GlobalObject*, Bun::JSCommonJSModule*, JSC::JSString*, JSC::JSValue) JSCommonJSModule.cpp:213
    #46 0x000103395248 in Bun::createCommonJSModule(Zig::GlobalObject*, JSC::JSString*, ResolvedSource&, bool)::$_0::operator()(JSC::JSGlobalObject*, JSC::Identifier const&, WTF::Vector<JSC::Identifier, 4ul, WTF::CrashOnOverflow, 16ul, WTF::FastMalloc>&, JSC::MarkedVector<JSC::JSValue, 8ul, WTF::RecordOverflow>&) const JSCommonJSModule.cpp:1500
    #47 0x000103394b6c in WTF::Detail::CallableWrapper<Bun::createCommonJSModule(Zig::GlobalObject*, JSC::JSString*, ResolvedSource&, bool)::$_0, void, JSC::JSGlobalObject*, JSC::Identifier, WTF::Vector<JSC::Identifier, 4ul, WTF::CrashOnOverflow, 16ul, WTF::FastMalloc>&, JSC::MarkedVector<JSC::JSValue, 8ul, WTF::RecordOverflow>&>::call(JSC::JSGlobalObject*, JSC::Identifier, WTF::Vector<JSC::Identifier, 4ul, WTF::CrashOnOverflow, 16ul, WTF::FastMalloc>&, JSC::MarkedVector<JSC::JSValue, 8ul, WTF::RecordOverflow>&) Function.h:53
    #48 0x00010edee12c in JSC::moduleLoaderParseModule(JSC::JSGlobalObject*, JSC::CallFrame*) JSModuleLoader.cpp:381
    #49 0x000300010034  (<unknown module>)
    #50 0x0001111e88e4 in jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__826_callHelper__dispatch_LowLevelInterpreter64_asm_2527+0x0 (bun-debug:arm64+0x10e76c8e4)
    #51 0x0001111e88e4 in jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__826_callHelper__dispatch_LowLevelInterpreter64_asm_2527+0x0 (bun-debug:arm64+0x10e76c8e4)
    #52 0x0001111e9e7c in jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__844_callHelper__dispatch_LowLevelInterpreter64_asm_2527+0x0 (bun-debug:arm64+0x10e76de7c)
    #53 0x0001111e9e7c in jsc_llint_commonCallOp__llintOpWithMetadata__llintOpWithReturn__llintOp__commonOp__fn__fn__makeReturn__fn__fn__fn__844_callHelper__dispatch_LowLevelInterpreter64_asm_2527+0x0 (bun-debug:arm64+0x10e76de7c)
    #54 0x0001111bf354 in llint_call_javascript+0x4 (bun-debug:arm64+0x10e743354)
    #55 0x00010e2c1c00 in JSC::Interpreter::executeCallImpl(JSC::VM&, JSC::JSObject*, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) Interpreter.cpp:1385
    #56 0x00010e2c2504 in JSC::Interpreter::executeCall(JSC::JSObject*, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) Interpreter.cpp:1400
    #57 0x00010e966ad0 in JSC::call(JSC::JSGlobalObject*, JSC::JSValue, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) CallData.cpp:69
    #58 0x00010e967350 in JSC::profiledCall(JSC::JSGlobalObject*, JSC::ProfilingReason, JSC::JSValue, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) CallData.cpp:90
    #59 0x00010ede8e20 in JSC::runJSMicrotask(JSC::JSGlobalObject*, WTF::ObjectIdentifierGeneric<JSC::MicrotaskIdentifierType, WTF::ObjectIdentifierThreadSafeAccessTraits<unsigned long long>, unsigned long long>, JSC::JSValue, std::__1::span<JSC::JSValue const, 18446744073709551615ul>) JSMicrotask.cpp:67
    #60 0x00010f519cc8 in JSC::VM::drainMicrotasks() VM.cpp:1347
    #61 0x000104600784 in Zig::GlobalObject::drainMicrotasks() ZigGlobalObject.cpp:2829
    #62 0x000104600a18 in JSC__JSGlobalObject__drainMicrotasks ZigGlobalObject.cpp:2843
    #63 0x000105e3b6b8 in bun.js.event_loop.drainMicrotasksWithGlobal event_loop.zig:131
    #64 0x000105c28ba0 in bun.js.event_loop.tick event_loop.zig:500
    #65 0x000105e2b7c0 in bun.js.event_loop.waitForPromise event_loop.zig:520
    #66 0x000105765524 in bun.js.VirtualMachine.waitForPromise VirtualMachine.zig:909
    #67 0x000106350b44 in bun.js.VirtualMachine.loadEntryPoint VirtualMachine.zig:2287
    #68 0x000105d943bc in bun.js.Run.start bun.js.zig:325
    #69 0x00010569c99c in bun.js.jsc.OpaqueWrap__anon_37088__struct_263624.callback jsc.zig:234
    #70 0x000102be2e8c in JSC__VM__holdAPILock bindings.cpp:4615
    #71 0x000104fe5b8c in bun.js.bindings.VM.VM.holdAPILock VM.zig:35
    #72 0x0001055ccd00 in bun.js.Run.boot bun.js.zig:254
    #73 0x0001055d6558 in cli.run_command.RunCommand.execAsIfNode run_command.zig:1662
    #74 0x0001055f03bc in cli.Command.start cli.zig:867
    #75 0x000104ef33b0 in cli.Cli.start cli.zig:20
    #76 0x000104eef6b4 in main.main main.zig:60
    #77 0x000104eef480 in main start.zig:635
    #78 0x000199886b94 in start+0x17b8 (dyld:arm64+0xfffffffffff3ab94)

==83008==Register values:
 x[0] = 0x000061300012ace8   x[1] = 0x000061300012ace8   x[2] = 0x0000000000000000   x[3] = 0x000061300012acf0  
 x[4] = 0x00006100002141c8   x[5] = 0x0000000000000018   x[6] = 0x000061300012acf1   x[7] = 0x0000000000000001  
 x[8] = 0x0000000000000000   x[9] = 0xea0d078d82ac00c1  x[10] = 0x000000016d3757e0  x[11] = 0x00000c260002559d  
x[12] = 0x00000c260002559d  x[13] = 0x0000000000000000  x[14] = 0x0000000000000000  x[15] = 0x000000016d375000  
x[16] = 0x0000000000000000  x[17] = 0x000000016d375540  x[18] = 0x0000000000000000  x[19] = 0x0000619000144828  
x[20] = 0x000061300012acb8  x[21] = 0x000061300012ace8  x[22] = 0x000061300012c780  x[23] = 0x000061300012acb8  
x[24] = 0x000061300012acd0  x[25] = 0x000000017fdc0330  x[26] = 0x0000000000000010  x[27] = 0x0000000207abef00  
x[28] = 0xfffe000000000002     fp = 0x000000016d375a90     lr = 0x000000017fdc0dbc     sp = 0x000000016d375a40  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (<unknown module>) 
```

**Comment by robobun** [comment]
This is the same problem tracked in #9594: the standard (non-baseline) Windows bun.exe 1.1.x build dying with `Illegal instruction at address ...` during package install on a CPU that lacks the SIMD (SSE4.2/AVX) instructions that build requires, which you confirmed above was fixed by switching to the `-baseline` build. #9594 already contains this exact install-phase crash trace and the maintainer explanation of the CPU requirement, and the identical 1.1.3 report #10294 was already consolidated there, so it will be tracked in #9594. (#9594 is in turn being consolidated into #7179, which is where this will be tracked.)

Duplicate of #9594

Please add a 👍 or any extra details over there so it all stays in one place. If this is actually a different problem, say so here and we'll reopen.
