### ISSUE TITLE
`bun --watch` throwing same module errors multiple times for unknown reasons

### ISSUE THREAD

**Issue by touhidurrr** [oven-sh/bun#10143]
### What version of Bun is running?

1.1.3+2615dc742

### What platform is your computer?
Tested on:
Microsoft Windows NT 10.0.22631.0 x64
Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 unknown (WSL Debian Bookworm)

### What steps can reproduce the bug?

Make the following files:
```ts
// module.ts
throw new Error("Test Error");
export const candy = "Tastes Good";
```
```ts
// a.ts
import { candy } from "./module";
console.log(`a ate candy: ${candy}`);
export const a = "a";
```
```ts
// b.ts
import { candy } from "./module";
console.log(`b ate candy: ${candy}`);
export const b = "b";
```
```ts
// index.ts
import { a } from "./a";
import { b } from "./b";
console.log(a, b);
```

Now run `bun --watch index.ts`.

### What is the expected behavior?

```sh
bun index.ts
1 | throw new Error("Test Error");
          ^
error: Test Error
      at C:\fakepath\Fail Test\module.ts:1:7
```

### What do you see instead?

```sh
bun --watch index.ts
1 | throw new Error("Test Error");
          ^
error: Test Error
      at C:\fakepath\Fail Test\module.ts:1:7
1 | throw new Error("Test Error");
                   ^
error: Test Error
      at module code (C:\fakepath\Fail Test\module.ts:1:16)
```

### Additional information

Same error from but different points in line? Weird.
**Note:** doesn't happen in `bun --hmr`.

**Comment by Dimava** [comment]
Simpler repro (win1.1.3 as well)
```ts
// err.ts
for (const e of [{}]) {
  err
}
```
```sh
bun run --watch .\err.ts
```
```ts
1 | // err.ts
2 | for (const e of [{}]) {
3 |   err
      ^
ReferenceError: Can't find variable: err
      at D:\projects\test\err.ts:3:3
1 | // err.ts
2 | for (const e of [{}]) {
         ^
ReferenceError: Can't find variable: err
      at module code (D:\projects\test\err.ts:2:6)
```

Or even just file with `err` works as well
