### ISSUE TITLE
Bun.file.formData()

### ISSUE THREAD

**Issue by SaltFish001** [oven-sh/bun#10201]
### What version of Bun is running?

1.1.3

### What platform is your computer?

Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

bun_file.test
```
import mime from 'mime';
const test_file_1 = await Bun.file('./tsconfig.json', {
  type: mime.getType('json'),
}).formData();
console.log('test_file_1 >>>', test_file_1);
```

### What is the expected behavior?

![image](https://github.com/oven-sh/bun/assets/42058801/4ca50e42-5b37-488e-881d-050cc00354c5)

**Comment by SaltFish001** [comment]
There are also issues， when i send a file with Chines filename (like ```屏幕截图 2024-04-12 121654.png```) by bun fetch, body use FormData. Will get error like this: 
```
[13:09:48.082] FATAL: Unexpected end of form
    serviceName: "utils"
    err: {
      "type": "Error",
      "message": "Unexpected end of form",
      "stack":
          Error: Unexpected end of form
              at checkEndState (/home/saltfish/Mems/Dummy/service/utilsservice/node_modules/@dkgy/fishbone/node_modules/busboy/lib/types/multipart.js:612:12)
              at Multipart._destroy (/home/saltfish/Mems/Dummy/service/utilsservice/node_modules/@dkgy/fishbone/node_modules/busboy/lib/types/multipart.js:576:13)
              at _destroy (node:internal/streams/destroy:121:10)
              at Multipart.destroy (node:internal/streams/destroy:83:5)
              at Writable.destroy (node:internal/streams/writable:1113:11)
              at Multipart.finish (/home/saltfish/Mems/Dummy/service/utilsservice/node_modules/@dkgy/fishbone/node_modules/hyper-express/src/components/http/Request.js:713:26)
              at Object.onceWrapper (node:events:633:26)
              at Multipart.emit (node:events:530:35)
              at Multipart.emit (node:domain:488:12)
              at SBMH.ssCb (/home/saltfish/Mems/Dummy/service/utilsservice/node_modules/@dkgy/fishbone/node_modules/busboy/lib/types/multipart.js:398:18)
```
This won't happen in Node.js 20.12.0 or English filename.

**Comment by luisvinicius09** [comment]
I'm also having issues with the `Invalid encoding` while trying to read a simple csv file and use the `.formData()` method

**Comment by u007** [comment]
is this still pending?

**Comment by SaltFish001** [comment]
> is this still pending?

Yes

![Image](https://github.com/user-attachments/assets/bc4d6244-8c13-4934-834f-f68aebec40ae)
