### ISSUE TITLE
"Cannot destructure argument" error is hard to understand

### ISSUE THREAD

**Issue by Dimava** [oven-sh/bun#10228]
### What version of Bun is running?

1.1.3+2615dc742

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

```ts
function foo({ a }) {
  return a
}
foo(null)
```

### What is the expected behavior?

Anything that does not say "Right side of assignment". I spent a minute looking for the assignment

Here's what V8 gives:
```ts
Uncaught TypeError: Cannot destructure property 'a' of 'object null' as it is null.
    at foo (<anonymous>:1:16)
    at <anonymous>:4:1
```

### What do you see instead?

```ts
1 | function foo({ a }) {
                        ^
TypeError: Right side of assignment cannot be destructured
      at foo (D:\projects\test\err.ts:1:21)
      at D:\projects\test\err.ts:4:1
```

**Comment by Jarred-Sumner** [comment]
This is a JavaScriptCore bug unfortunately. Would you be able to file an issue on [WebKit's bug tracker](https://bugs.webkit.org/) in the `JavaScriptCore` category?

**Comment by sosukesuzuki** [comment]
https://github.com/WebKit/WebKit/pull/49762 will fix this
