### ISSUE TITLE
Wrong line when shell command fails (ShellError; mjs w/ shebang)

### ISSUE THREAD

**Issue by mnpenner** [oven-sh/bun#10254]
### What version of Bun is running?

1.1.3+2615dc742

### What platform is your computer?

Linux 4.4.0-19041-Microsoft x86_64 x86_64

### What steps can reproduce the bug?

In this script the `^` error pointer is a little off, I have a longer script where the line number is also wrong, but I don't know how to reproduce it in a smaller example.

```js
#!bun
import {$} from 'bun'
import * as posixPath from 'node:path/posix'
import * as localPath from 'node:path'
import * as fs from 'node:fs/promises'

// useless line
const tmpDir = posixPath.relative('/app', '/tmp')
const filename = 'Router.js'
const fullPath = posixPath.join(tmpDir, filename)

console.log('hello 1')
const out1 = await $`echo ${fullPath}`.text()
console.log(out1)
const out2 = await $`false`.text()
console.log('hello 2')
```

The output is:

```txt
❯ ./scripts/build/foo.mjs
hello 1
../tmp/Router.js

10 | const fullPath = posixPath.join(tmpDir, filename)
11 |
12 | console.log('hello 1')
13 | const out1 = await $`echo ${fullPath}`.text()
14 | console.log(out1)
15 | const out2 = await $`false`.text()
                                   ^
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "",
  "stdout": ""
}

      at new ShellError (:12:31)
      at new ShellPromise (:64:31)
      at BunShell (:184:69)
      at /mnt/c/Users/.../scripts/build/foo.mjs:15:20
```

The `^` is pointing to the `x` in `text()`. I don't know where it should point, maybe the `$` or or the `a` in `await` or `t` in `text`, doesn't much matter to me, but the `x` is weird. The column number isn't the point though, the actual line # can be wrong too, which is a bigger problem.

### What is the expected behavior?

Output tells you where the actual error is

### What do you see instead?

Wrong line & column

### Additional information

I'm using an executable file with `.mjs` extension and relying on the shebang (`#!bun`) to execute the file. Not using `bun run` or anything. Not sure if that matters. The error is coming from the shell command (`false`) in the above example.

**Comment by mnpenner** [comment]
It points to the `await` now. Maybe it's centering the `^`. Not sure. Line # is correct. 

```
❯ bun foo.mjs
hello 1
../tmp/Router.js

10 | const fullPath = posixPath.join(tmpDir, filename)
11 |
12 | console.log('hello 1')
13 | const out1 = await $`echo ${fullPath}`.text()
14 | console.log(out1)
15 | const out2 = await $`false`.text()
                    ^
ShellError: Failed with exit code 1
 exitCode: 1,
   stdout: Buffer(0) [],
   stderr: Buffer(0) [],

      at new ShellError (12:16)
      at new ShellPromise (77:16)
      at BunShell (193:35)
      at /tmp/tmp.8VJk33bO0U/foo.mjs:15:20

Bun v1.2.0 (Linux x64)
```

I'm going to close this so no one has to triage it. Might reopen if I can repro the wrong line # issue again.
