### ISSUE TITLE
wasm-simd is not supported in bun

### ISSUE THREAD

**Issue by derekhearst** [oven-sh/bun#10306]
### What version of Bun is running?

1.1.4+fbe2fe0c3

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

https://github.com/derekhearst/wasm-simd-issues
Clone Repo
Bun Install
bun ocr.js tests/test1.jpg -- throws error
node ocr.js tests/test1.jpg -- works

### What is the expected behavior?

Should OCR the image like nodejs does.

### What do you see instead?

`RuntimeError: Aborted(CompileError: WebAssembly.Module doesn't parse at byte 10: wasm-simd is not supported, in function at index 45). Build with -sASSERTIONS for more info.
      at abort (C:\Users\derek\Documents\Projects\node-cli\node_modules\tesseract-wasm\dist\lib.js:558:5228)
      at C:\Users\derek\Documents\Projects\node-cli\node_modules\tesseract-wasm\dist\lib.js:558:6949`

**Comment by derekhearst** [comment]
`
import { simd } from 'wasm-feature-detect';
const hasSIMD = await simd();
console.log(hasSIMD) // returns false
`
Coming from this - https://v8.dev/features/simd

**Comment by datapedd** [comment]
Would love to have this as tensorflow needs it: "bun run ./src/test.ts
SIMD or multi-threading is not supported in this environment."

**Comment by panuchka** [comment]
Would also be needing this to run my game server on bun (physics calculations using wasm)

**Comment by benatkin** [comment]
upstream issue? https://bugs.webkit.org/show_bug.cgi?id=222382

**Comment by benatkin** [comment]
> `import { simd } from 'wasm-feature-detect'; const hasSIMD = await simd(); console.log(hasSIMD) // returns false` Coming from this - https://v8.dev/features/simd

I tried it and got the opposite result!

Installed bun using `curl -fsSL https://bun.sh/install` in a podman container on `fedora:latest`
