### ISSUE TITLE
bun install failed with `v1.1.4` 

### ISSUE THREAD

**Issue by arvinxx** [oven-sh/bun#10368]
### What version of Bun is running?

1.1.4

### What steps can reproduce the bug?

1. git clone https://github.com/lobehub/lobe-chat
2. git checkout branch `build-fail-with-bun/1.1.4`
3. bun install

### What is the expected behavior?

install depends success

### What do you see instead?

install failed. Here is the build on vercel error log:

```
[11:33:16.028] Running build in Washington, D.C., USA (East) – iad1
[11:33:16.179] Cloning github.com/wangzhazha100/lobe-chat (Branch: main, Commit: https://github.com/lobehub/lobe-chat/commit/34677f6691998c51e3a7f0176e33ed4c57e876eb)
[11:33:16.526] Previous build cache not available
[11:33:16.807] Cloning completed: 627.558ms
[11:33:17.270] Running "vercel build"
[11:33:18.012] Vercel CLI 34.1.1
[11:33:19.367] Running "install" command: bun install...
[11:33:19.419] bun install v1.1.4 (fbe2fe0c)
[11:33:19.431] Resolving dependencies
[11:33:30.709] Resolved, downloaded and extracted [8866]
[11:33:30.711] warn: incorrect peer dependency "stylelint@15.11.0"
[11:33:30.711]
[11:33:30.715] warn: incorrect peer dependency "stylelint@15.11.0"
[11:33:30.717]
[11:33:30.718] warn: incorrect peer dependency "stylelint@15.11.0"
[11:33:30.719]
[11:33:30.719] warn: incorrect peer dependency "stylelint@15.11.0"
[11:33:30.719]
[11:33:30.719] warn: incorrect peer dependency "stylelint@15.11.0"
[11:33:30.719]
[11:33:30.720] warn: incorrect peer dependency "stylelint@15.11.0"
[11:33:30.720]
[11:33:30.720] warn: incorrect peer dependency "@octokit/core@5.2.0"
[11:33:30.720]
[11:33:30.720] warn: incorrect peer dependency "stylelint@15.11.0"
[11:33:30.720]
[11:33:30.720] warn: incorrect peer dependency "stylelint@15.11.0"
[11:33:30.721]
[11:33:30.723] warn: incorrect peer dependency "stylelint@15.11.0"
[11:33:30.723]
[11:33:30.723] warn: incorrect peer dependency "stylelint@15.11.0"
[11:33:30.723]
[11:33:30.723] warn: incorrect peer dependency "@octokit/core@5.2.0"
[11:33:30.723]
[11:33:30.724] warn: incorrect peer dependency "@octokit/core@5.2.0"
[11:33:39.655] gyp info it worked if it ends with ok
[11:33:39.657] gyp info using node-gyp@9.4.1
[11:33:39.659] gyp info using node@20.12.2 | linux | x64
[11:33:39.661] gyp info find Python using Python version 3.12.2 found at "/usr/local/bin/python3"
[11:33:39.665] gyp http GET https://nodejs.org/download/release/v20.12.2/node-v20.12.2-headers.tar.gz
[11:33:39.667] gyp http 200 https://nodejs.org/download/release/v20.12.2/node-v20.12.2-headers.tar.gz
[11:33:39.667] gyp http GET https://nodejs.org/download/release/v20.12.2/SHASUMS256.txt
[11:33:39.667] gyp http 200 https://nodejs.org/download/release/v20.12.2/SHASUMS256.txt
[11:33:39.668] gyp info spawn /usr/local/bin/python3
[11:33:39.668] gyp info spawn args [
[11:33:39.668] gyp info spawn args '/vercel/path0/node_modules/node-gyp/gyp/gyp_main.py',
[11:33:39.668] gyp info spawn args 'binding.gyp',
[11:33:39.668] gyp info spawn args '-f',
[11:33:39.668] gyp info spawn args 'make',
[11:33:39.668] gyp info spawn args '-I',
[11:33:39.668] gyp info spawn args '/vercel/path0/node_modules/tree-sitter-yaml/build/config.gypi',
[11:33:39.668] gyp info spawn args '-I',
[11:33:39.668] gyp info spawn args '/vercel/path0/node_modules/node-gyp/addon.gypi',
[11:33:39.668] gyp info spawn args '-I',
[11:33:39.669] gyp info spawn args '/vercel/.cache/node-gyp/20.12.2/include/node/common.gypi',
[11:33:39.669] gyp info spawn args '-Dlibrary=shared_library',
[11:33:39.669] gyp info spawn args '-Dvisibility=default',
[11:33:39.669] gyp info spawn args '-Dnode_root_dir=/vercel/.cache/node-gyp/20.12.2',
[11:33:39.669] gyp info spawn args '-Dnode_gyp_dir=/vercel/path0/node_modules/node-gyp',
[11:33:39.669] gyp info spawn args '-Dnode_lib_file=/vercel/.cache/node-gyp/20.12.2/<(target_arch)/node.lib',
[11:33:39.669] gyp info spawn args '-Dmodule_root_dir=/vercel/path0/node_modules/tree-sitter-yaml',
[11:33:39.669] gyp info spawn args '-Dnode_engine=v8',
[11:33:39.669] gyp info spawn args '--depth=.',
[11:33:39.669] gyp info spawn args '--no-parallel',
[11:33:39.669] gyp info spawn args '--generator-output',
[11:33:39.669] gyp info spawn args 'build',
[11:33:39.669] gyp info spawn args '-Goutput_dir=.'
[11:33:39.669] gyp info spawn args ]
[11:33:39.669] Traceback (most recent call last):
[11:33:39.669] File "/vercel/path0/node_modules/node-gyp/gyp/gyp_main.py", line 42, in
[11:33:39.669] import gyp # noqa: E402
[11:33:39.669] ^^^^^^^^^^
[11:33:39.669] File "/vercel/path0/node_modules/node-gyp/gyp/pylib/gyp/init.py", line 9, in
[11:33:39.669] import gyp.input
[11:33:39.669] File "/vercel/path0/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in
[11:33:39.669] from distutils.version import StrictVersion
[11:33:39.669] ModuleNotFoundError: No module named 'distutils'
[11:33:39.669] gyp ERR! configure error
[11:33:39.669] gyp ERR! stack Error: gyp failed with exit code: 1
[11:33:39.669] gyp ERR! stack at ChildProcess.onCpExit (/vercel/path0/node_modules/node-gyp/lib/configure.js:325:16)
[11:33:39.669] gyp ERR! stack at ChildProcess.emit (node:events:518:28)
[11:33:39.670] gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
[11:33:39.670] gyp ERR! System Linux 5.10.174
[11:33:39.670] gyp ERR! command "/node20/bin/node" "/vercel/path0/node_modules/.bin/node-gyp" "rebuild"
[11:33:39.670] gyp ERR! cwd /vercel/path0/node_modules/tree-sitter-yaml
[11:33:39.670] gyp ERR! node -v v20.12.2
[11:33:39.670] gyp ERR! node-gyp -v v9.4.1
[11:33:39.670] gyp ERR! not ok
[11:33:39.670]
[11:33:39.670] error: install script from "tree-sitter-yaml" exited with 1
[11:33:39.755] Error: Command "bun install" exited with 1
[11:33:43.450]
```

here are some more people reported it:
- https://github.com/lobehub/lobe-chat/issues/2093
- https://github.com/lobehub/lobe-chat/issues/2092

### Additional information

It will pass with node version 18. but failed with node version 20.
it will pass with `1.1.3` , but failed with `1.1.4`

**Comment by dylan-conway** [comment]
This is happening because bun is not respecting the `bundledDependencies` in `npm@9.9.3`. One of those dependencies is an older version of `node-gyp`. It's hoisted, linked to the root `node_modules/.bin`, and used in the install script in `tree-sitter-yaml`.

Instead, bun needs to ignore dependencies that appear in `bundledDependencies` during install. We will work on fixing this soon. As a workaround, you can add `node-gyp@10.1.0` to dev dependencies
