### ISSUE TITLE
hasBeenCalledWith do not show diff

### ISSUE THREAD

**Issue by ValentinJS** [oven-sh/bun#10380]
### What version of Bun is running?

1.1.3+2615dc742

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

Run the following test with `bun test`:

```js
import { expect, mock, test } from 'bun:test';

const mockedFn = mock((args) => args);

const a = { a: { b: { c: { d: 1 } } } };
const b = { a: { b: { c: { d: 2 } } } };

test('mytest', () => {
  mockedFn(a);

  expect(mockedFn).toHaveBeenCalledWith(b);
});
```

### What is the expected behavior?

Expected to see an actual diff of the received vs expected objects, as toEqual / toStrictEqual does

i.e : 

```
bun test repro
bun test v1.1.3 (2615dc74)

src/repro.test.ts:
 6 | const b = { a: { b: { c: { d: 2 } } } };
 7 |
 8 | test('mytest', () => {
 9 |   mockedFn(a);
10 |
11 |   expect(mockedFn).toHaveBeenCalledWith(b);
       ^
error: expect(mockedFn).toHaveBeenCalledWith(b);

  {
    a: {
      b: {
        c: {
+         d: 1,
-         d: 2,
        },
      },
    },
  }

- Expected  - 1
+ Received  + 1

      at /Users/savate/Projects/biggerpicture/src/repro.test.ts:11:3
✗ mytest [5.33ms]

 0 pass
 1 fail
 1 expect() calls
Ran 1 tests across 1 files. [22.00ms]
```

### What do you see instead?

No diff is provided : 

```
bun test repro
bun test v1.1.3 (2615dc74)

src/repro.test.ts:
 6 | const b = { a: { b: { c: { d: 2 } } } };
 7 |
 8 | test('mytest', () => {
 9 |   mockedFn(a);
10 |
11 |   expect(mockedFn).toHaveBeenCalledWith(b);
       ^
error: expect(received).toHaveBeenCalledWith(expected)

Number of calls: 1

      at /Users/savate/Projects/biggerpicture/src/repro.test.ts:11:3
✗ mytest [0.13ms]

 0 pass
 1 fail
 1 expect() calls
Ran 1 tests across 1 files. [16.00ms]
```

### Additional information

This happens with hasBeenCalledWith and all variant such as hasBeenNthCalledWith, hasBeenLastCalledWith...

**Comment by liontariai** [comment]
Can confirm this issue persists in the latest version (bun 1.1.27). Would be great to have this fixed :)

**Comment by francescov1** [comment]
This is making it super tough to write unit tests, still experiencing in `1.1.42`

**Comment by rodhoward** [comment]
As a work around for this issue I've switched to using "lastCalledWith" instead. It is returning a diff as you would hope. Its not quite the same thing but most of the time its kinda what your after anyway.

**Comment by jjjjjjjjjjjjjjjjacob** [comment]
this is returning the response for `toHaveBeenCalledTimes` while testing making it impossible to debug
