### ISSUE TITLE
bun install creates faulty dependency package.json files

### ISSUE THREAD

**Issue by liquidiert** [oven-sh/bun#10454]
### What version of Bun is running?

1.1.4+fbe2fe0c3

### What platform is your computer?

Linux 6.8.0-76060800daily20240311-generic x86_64 x86_64

### What steps can reproduce the bug?

Add a simple package.json file with tailwindcss dependency:
```json
{
  "scripts": {
    "tw:watch": "rm -rf static/CACHE && tailwindcss -i ./static/input.css -o ./static/css/output.css --watch",
    "tw:build": "tailwindcss -i ./static/input.css -o ./static/css/output.css --minify"
  },
  "devDependencies": {
    "tailwindcss": "^3.4.3"
  },
  "dependencies": {}
}
```
run `bun i` and then try to run `bun tw:watch` or `bun --bun tw:watch`

### What is the expected behavior?

bun install should install dependencies correctly and create correct package.json files in node_modules

### What do you see instead?

With `bun tw:watch`:
```text
$ rm -rf static/CACHE && tailwindcss -i ./static/input.css -o ./static/css/output.css --watch
node:internal/modules/package_json_reader:93
        throw error;
        ^

SyntaxError: Error parsing /home/secretone/git_repos/test/src/node_modules/@alloc/quick-lru/package.json: Expected double-quoted property name in JSON at position 714
    at parse (<anonymous>)
    at read (node:internal/modules/package_json_reader:80:16)
    at readPackage (node:internal/modules/package_json_reader:141:10)
    at resolveExports (node:internal/modules/cjs/loader:586:15)
    at Module._findPath (node:internal/modules/cjs/loader:667:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1129:27)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/secretone/git_repos/test/src/node_modules/tailwindcss/lib/lib/expandTailwindAtRules.js:12:58) {
  path: '/home/secretone/git_repos/ff-agent-page/src/node_modules/@alloc/quick-lru/package.json'
}

Node.js v20.12.0
error: script "tw:watch" exited with code 1
```
With `bun --bun tw:watch`:
```text
$ rm -rf static/CACHE && tailwindcss -i ./static/input.css -o ./static/css/output.css --watch
1 | module.exports = require("./binary-extensions.json")
           ^
SyntaxError: Failed to parse JSON
      at /home/secretone/git_repos/test/src/node_modules/binary-extensions/index.js:1:8
      at /home/secretone/git_repos/test/src/node_modules/is-binary-path/index.js:3:7
      at /home/secretone/git_repos/test/src/node_modules/chokidar/lib/nodefs-handler.js:6:7
      at /home/secretone/git_repos/test/src/node_modules/chokidar/index.js:14:7
      at /home/secretone/git_repos/test/src/node_modules/tailwindcss/lib/cli/build/watching.js:12:33
error: script "tw:watch" exited with code 1
```

### Additional information

When I install dependencies via yarn or npm bun run works flawlessly.
Here is a faulty package.json file generated by bun install:
```json
{
    "name": "@alloc/quick-lru",
    "version": "5.2.0",
    "description": "Simple “Least Recently Used” (LRU) cache",
    "license": "MIT",
    "repository": "sindresorhus/quick-lru",
    "funding": "https://github.com/sponsors/sindresorhus",
    "author": {"name": "Sindre Sorhus", "email": "sindresorhus@gmail.com", "url": "https://sindresorhus.com"},
    "engines": {"node": ">=10"},
    "scripts": {"test": "xo && nyc ava && tsd"},
    "files": ["index.js", "index.d.ts"],
    "keywords": ["lru", "quick", "cache", "caching", "least", "recently", "used", "fast", "map", "hash", "buffer"],
    "devDependencies": {"ava": "^2.0.0", "coveralls": "^3.0.3", "nyc": "^15.0.0", "tsd": "^0.11.0", "xo": "^0.26.0"},
}
```
Behind the closing curly brace of devDependencies there is a comma

**Comment by liquidiert** [comment]
Can't be reproduced with newer bun versions
