### ISSUE TITLE
Windows Bun REPL character not visible and crash follows

### ISSUE THREAD

**Issue by jgranduel** [oven-sh/bun#10516]
### What version of Bun is running?

1.1.4

### What platform is your computer?

Platform ServicePack Version      VersionString -------- ----------- -------      -------------  Win32NT             10.0.19045.0 Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

```
>bun repl in windows Terminal
> # can't see any typed characters
> # typing in .help without seeing displays characters and then I can type normaly
>let f = x => x+1 // it can be var a = 1<enter>
481 |                 return SafeInspect(v, this.repl?.writer?.options ?? { colors: ${Bun.enableANSIColors}, showProxy: true });
482 |             }`,
483 |             arguments: [remoteObj],
484 |         });
485 |         ReflectDeleteProperty(GLOBAL, REPL_INTERNALS);
486 |         if (inspected.wasThrown) throw new EvalError(`Failed to inspect object: ${JSONStringify(inspected)}`);
                                             ^
EvalError: Failed to inspect object: {"result":{"type":"object","objectId":"{\"injectedScriptId\":1,\"id\":2}","subtype":"error","className":"SyntaxError","description":"SyntaxError: The only valid numeric escape in strict mode is '\\0'"},"wasThrown":true}
      at C:\Users\<user>\AppData\Local\Temp\bunx-780016501-bun-repl@latest\node_modules\bun-repl\src\repl.ts:486:40
      
>crash !
```

### What is the expected behavior?

type in visible characters as soon as REPL is launched !
no crash !

### What do you see instead?

crash !

### Additional information

PowerShell command doesn't seem to be correct:

```
$([Environment]::OSVersion | ForEach-Object VersionString) $(if ([Environment]::Is64BitOperatingSystem) { "x64" } else { "x86" })
```

Maybe (if on 1 line):

```
[Environment]::OSVersion | select -expand VersionString; $(if ([Environment]::Is64BitOperatingSystem) { "x64" } else { "x86" }
```

**Comment by jgranduel** [comment]
Hi, 

Tested with bunjs-1.1.6 on Windows-10, and everything works with REPL well as far as I have tested. Thanks a lot!
👍

**Comment by jgranduel** [comment]
Hi, 

This issued being still opened, I want to mention that at some point when an import fails, then theprevious behaviour reappears. I am not sure to reproduce in all cases.

In the following example, I failed to import `chalk` for some reasons. (I was using `import chalk from 'chalk'` which happens to work on a different folder so it might not be the point). Then `bun repl` remains broken in my terminal session whatever I do, even simple statements:

```
> bun repl
Welcome to Bun v1.1.6
Type ".help" for more information.
[!] Please note that the REPL implementation is still experimental!
    Don't consider it to be representative of the stability or behavior of Bun overall.
> var a = 10
481 |                 return SafeInspect(v, this.repl?.writer?.options ?? { colors: ${Bun.enableANSIColors}, showProxy: true });
482 |             }`,
483 |             arguments: [remoteObj],
484 |         });
485 |         ReflectDeleteProperty(GLOBAL, REPL_INTERNALS);
486 |         if (inspected.wasThrown) throw new EvalError(`Failed to inspect object: ${JSONStringify(inspected)}`);
                                             ^
EvalError: Failed to inspect object: {"result":{"type":"object","objectId":"{\"injectedScriptId\":1,\"id\":2}","subtype":"error","className":"SyntaxError","description":"SyntaxError: The only valid numeric escape in strict mode is '\\0'"},"wasThrown":true}
      at C:\Users\<user>\AppData\Local\Temp\bunx-780016501-bun-repl@latest\node_modules\bun-repl\src\repl.ts:486:40

**Comment by jgranduel** [comment]
Hi, 

the issue is still present in `bun-1.1.8` :
````
> bun repl
let Welcome to Bun v1.1.18
Type ".help" for more information.
[!] Please note that the REPL implementation is still experimental!
    Don't consider it to be representative of the stability or behavior of Bun overall.
> let a = x => x + 1
481 |                 return SafeInspect(v, this.repl?.writer?.options ?? { colors: ${Bun.enableANSIColors}, showProxy: true });
482 |             }`,
483 |             arguments: [remoteObj],
484 |         });
485 |         ReflectDeleteProperty(GLOBAL, REPL_INTERNALS);
486 |         if (inspected.wasThrown) throw new EvalError(`Failed to inspect object: ${JSONStringify(inspected)}`);
                                             ^
EvalError: Failed to inspect object: {"result":{"type":"object","objectId":"{\"injectedScriptId\":1,\"id\":2}","subtype":"error","className":"SyntaxError","description":"SyntaxError: The only valid numeric escape in strict mode is '\\0'"},"wasThrown":true}
      at C:\Users\<user>\AppData\Local\Temp\bunx-780016501-bun-repl@latest\node_modules\bun-repl\src\repl.ts:486:40


Bun v1.1.18 (Windows x64 baseline)
```
