### ISSUE TITLE
Test failure in `Module._resolveLookupPaths` on Windows

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#10601]
```js
  Error:   [
  +   "/baz/abc"
  -   "/baz"
    ]
  
  - Expected  - 1
  + Received  + 1
  
        at C:\a\bun\bun\test\js\node\module\node-module-module.test.js:116:3
  111 |   expect(require.extensions).toBe(Module._extensions);
  112 | });
  113 | 
  114 | test("Module._resolveLookupPaths", () => {
  115 |   expect(Module._resolveLookupPaths("foo")).toEqual([]);
  116 |   expect(Module._resolveLookupPaths("./bar", { id: "1", filename: "/baz/abc" })).toEqual(["/baz"]);
          ^
  error: expect(received).toEqual(expected)
  
    [
  +   "/baz/abc"
  -   "/baz"
    ]
  
  - Expected  - 1
  + Received  + 1
  
        at C:\a\bun\bun\test\js\node\module\node-module-module.test.js:116:3
  ✗ Module._resolveLookupPaths [5.01ms]
```

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/pull/10620
