### ISSUE TITLE
[ERROR] TTY initialization failed: uv_tty_init returned EINVAL

### ISSUE THREAD

**Issue by long-woo** [oven-sh/bun#10729]
### What version of Bun is running?

1.1.6

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

1. Clone https://github.com/long-woo/nuxt-bun-demo.git
2. Execute `bun i`

### What is the expected behavior?

When I use `pnpm i` everything works fine, the message is as follows:

```sh
pnpm i
Packages: +761
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/[***]/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 809, reused 761, downloaded 0, added 761, done
node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild: Running postinstall script, done in 517ms

> nuxt-app@ postinstall /Users/[***]/nuxt-bun-demo
> nuxt prepare


ℹ Nuxt collects completely anonymous data about usage.                                                       5:26:06 PM
  This will help us improve Nuxt developer experience over time.
  Read more on https://github.com/nuxt/telemetry


❯ Are you interested in participating?
● Yes / ○ No
```

### What do you see instead?

```sh
bun i
bun install v1.1.6 (e58d67b4)

$ nuxt prepare

ℹ Nuxt collects completely anonymous data about usage.                                                       2:24:37 PM
  This will help us improve Nuxt developer experience over time.
  Read more on https://github.com/nuxt/telemetry


 ERROR  TTY initialization failed: uv_tty_init returned EINVAL (invalid argument)                             2:24:37 PM

  at new SystemError (node:internal/errors:250:5)
  at new NodeError (node:internal/errors:361:7)
  at new WriteStream (node:tty:93:11)
  at sD.prompt (node_modules/consola/dist/chunks/prompt.mjs:141:676)
  at confirm (node_modules/consola/dist/chunks/prompt.mjs:251:6)
  at Module.prompt (node_modules/consola/dist/chunks/prompt.mjs:404:18)
  at node_modules/consola/dist/shared/consola.36c0034f.mjs:617:71
  at async ensureUserconsent (node_modules/@nuxt/telemetry/dist/shared/telemetry.023ac76b.mjs:26:20)
  at async setup (node_modules/@nuxt/telemetry/dist/module.mjs:363:74)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2112:17)



 ERROR  TTY initialization failed: uv_tty_init returned EINVAL (invalid argument)                             2:24:37 PM

error: postinstall script from "nuxt-app" exited with 1
```

**Comment by born2ngopi** [comment]
i got same problem with bun version `1.1.7` 

platform i used: `Linux 5.15.146.1-microsoft-standard-WSL2 x86_64`

with error:
```
bun install v1.1.7 (b0b7db5c)

$ nuxt prepare
ℹ Using default Tailwind CSS file                                                                                                        nuxt:tailwindcss 1:43:13 AM

ℹ Nuxt collects completely anonymous data about usage.                                                                                                    1:43:13 AM
  This will help us improve Nuxt developer experience over time.
  Read more on https://github.com/nuxt/telemetry


 ERROR  TTY initialization failed: uv_tty_init returned EINVAL (invalid argument)                                                                          1:43:13 AM

  at new WriteStream (node:tty:93:11)
  at sD.prompt (node_modules/consola/dist/chunks/prompt.mjs:141:676)
  at confirm (node_modules/consola/dist/chunks/prompt.mjs:251:6)
  at Module.prompt (node_modules/consola/dist/chunks/prompt.mjs:404:18)
  at node_modules/consola/dist/shared/consola.36c0034f.mjs:617:71
  at async ensureUserconsent (node_modules/@nuxt/telemetry/dist/shared/telemetry.023ac76b.mjs:26:20)
  at async setup (node_modules/@nuxt/telemetry/dist/module.mjs:363:74)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2141:17)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2439:95)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:3702:7)



 ERROR  TTY initialization failed: uv_tty_init returned EINVAL (invalid argument)                                                                          1:43:13 AM

error: postinstall script from "nuxt-app" exited with 1
```

**Edit:**
i have tried upgrading on version v1.1.8 and still having the same problem

**fix for me**
run `bun update` and run `npx nuxi prepare`

**Comment by BoggerByte** [comment]
I faced the same issue when I tried to install the packages with `bun install` in existing project. Updating with `bun update` and running `nuxt prepare` resolved the issue for me

**Comment by Chuck1sn** [comment]
```shell
bun -v
1.1.8
```

```shell
bunx nuxi@latest init Dylan

✔ Which package manager would you like to use?
bun
◐ Installing dependencies...                                                                                                                    9:25:24 PM
bun install v1.1.8 (89d25807)

$ nuxt prepare

ℹ Nuxt collects completely anonymous data about usage.                                                                                         9:25:43 PM
  This will help us improve Nuxt developer experience over time.
  Read more on https://github.com/nuxt/telemetry


 ERROR  TTY initialization failed: uv_tty_init returned EINVAL (invalid argument)                                                               9:25:43 PM

  at new SystemError (node:internal/errors:259:5)
  at new NodeError (node:internal/errors:370:7)
  at new WriteStream (node:tty:93:11)
  at sD.prompt (node_modules/consola/dist/chunks/prompt.mjs:141:676)
  at confirm (node_modules/consola/dist/chunks/prompt.mjs:251:6)
  at Module.prompt (node_modules/consola/dist/chunks/prompt.mjs:404:18)
  at node_modules/consola/dist/shared/consola.36c0034f.mjs:617:71
  at async ensureUserconsent (node_modules/@nuxt/telemetry/dist/shared/telemetry.023ac76b.mjs:26:20)
  at async setup (node_modules/@nuxt/telemetry/dist/module.mjs:363:74)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2112:17)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2415:95)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:4233:7)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:4331:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2570:19)
  at async Object.run (node_modules/nuxi/dist/chunks/prepare.mjs:53:18)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1648:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1639:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1777:7)



 ERROR  TTY initialization failed: uv_tty_init returned EINVAL (invalid argument)                                                               9:25:43 PM

error: postinstall script from "nuxt-app" exited with 1

 ERROR  Error: Command failed with exit code 1: bun install                                                                                     9:25:43 PM
```

<img width="278" alt="image" src="https://github.com/oven-sh/bun/assets/15964712/e2a5e019-a37d-455d-8fad-39fbd154f5ce">

**Comment by BoggerByte** [comment]
It seems Nuxt is trying to collect optional telemetry data and asks for user permission via the TTY interface, which might cause an internal error. Once a choice is made, this issue won't occur again.

To avoid this, you can manually set your choice by adding `telemetry.enabled=false` to the `~/.nuxtrc` file on Linux (I'm don't know about the location on Mac and Windows).

I also noticed that running `bun postinstall` displays the TTY interface correctly, allowing you to make a choice.

**Comment by chuck1in** [comment]
> It seems like Nuxt is trying to collect optional telemetry data and asks for user permission via the TTY interface, which might cause an internal error. Once a choice is made, this issue won't occur again.
> 
> To avoid this, you can manually set your choice by adding `telemetry.enabled=false` to the `~/.nuxtrc` file on Linux (I don't know about the location on Mac and Windows).
> 
> I also noticed that running `bun postinstall` displays the TTY interface correctly, allowing you to make a choice.

Thanks, I temporarily solved the problem with `bun postinstall`

```shell
# run init and output error info
bunx nuxi@latest init <project-name> 
# ignore error info and cd dir
cd <project-name>
bun postinstall
cd ..
rm -r <project-name>
# run again and get correct info
bunx nuxi@latest init <project-name> 
```
