### ISSUE TITLE
Angular tests crashing 

### ISSUE THREAD

**Issue by johanndev** [oven-sh/bun#10770]
### What version of Bun is running?

1.1.6+e58d67b46

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

1. Create a new angular project:
`bun --bun create @angular@latest ng-bun-test --style css --ssr false`
2. Run tests:
`bun test`

### What is the expected behavior?

Tests are successfully executed.

### What do you see instead?

The execution crashes with: `Need to call TestBed.initTestEnvironment() first`

<details>
<summary>Full log</summary>
```
➜ bun test
bun test v1.1.6 (e58d67b4)

src\app\app.component.spec.ts:
1995 |      * @internal strip this from published d.ts files due to
1996 |      * https://github.com/microsoft/TypeScript/issues/36216
1997 |      */
1998 |     get compiler() {
1999 |         if (this._compiler === null) {
2000 |             throw new Error(`Need to call TestBed.initTestEnvironment() first`);
                         ^
error: Need to call TestBed.initTestEnvironment() first
      at compiler (D:\scratch\ng-bun-test\node_modules\@angular\core\fesm2022\testing.mjs:2000:19)
      at configureTestingModule (D:\scratch\ng-bun-test\node_modules\@angular\core\fesm2022\testing.mjs:1903:9)
      at D:\scratch\ng-bun-test\src\app\app.component.spec.ts:6:11
      at D:\scratch\ng-bun-test\src\app\app.component.spec.ts:5:14
✗ AppComponent > should create the app [2.67ms]
✗ AppComponent > should create the app
1995 |      * @internal strip this from published d.ts files due to
1996 |      * https://github.com/microsoft/TypeScript/issues/36216
1997 |      */
1998 |     get compiler() {
1999 |         if (this._compiler === null) {
2000 |             throw new Error(`Need to call TestBed.initTestEnvironment() first`);
                         ^
error: Need to call TestBed.initTestEnvironment() first
      at compiler (D:\scratch\ng-bun-test\node_modules\@angular\core\fesm2022\testing.mjs:2000:19)
      at configureTestingModule (D:\scratch\ng-bun-test\node_modules\@angular\core\fesm2022\testing.mjs:1903:9)
      at D:\scratch\ng-bun-test\src\app\app.component.spec.ts:6:11
      at D:\scratch\ng-bun-test\src\app\app.component.spec.ts:5:14
✗ AppComponent > should have the 'ng-bun-test' title [3.71ms]
✗ AppComponent > should have the 'ng-bun-test' title
1995 |      * @internal strip this from published d.ts files due to
1996 |      * https://github.com/microsoft/TypeScript/issues/36216
1997 |      */
1998 |     get compiler() {
1999 |         if (this._compiler === null) {
2000 |             throw new Error(`Need to call TestBed.initTestEnvironment() first`);
                         ^
error: Need to call TestBed.initTestEnvironment() first
      at compiler (D:\scratch\ng-bun-test\node_modules\@angular\core\fesm2022\testing.mjs:2000:19)
      at configureTestingModule (D:\scratch\ng-bun-test\node_modules\@angular\core\fesm2022\testing.mjs:1903:9)
      at D:\scratch\ng-bun-test\src\app\app.component.spec.ts:6:11
      at D:\scratch\ng-bun-test\src\app\app.component.spec.ts:5:14
✗ AppComponent > should render title [4.81ms]
✗ AppComponent > should render title

 0 pass
 6 fail
Ran 6 tests across 1 files. [424.00ms]
```
</details>

**Comment by johanndev** [comment]
Addendum: Running the angular test runner via `bun run ng test` works as expected. As the current angular test setup relies on karma, I'm not sure if there is anything that the bun test runner could do.
