### ISSUE TITLE
Improve error message when `async` is missing from function

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#108]
Example:

```js
function x() {
  await Promise.resolve();
}

x();

```

Output: (which is not helpful)
```
error: Expected ";" but found "Promise"
  await Promise.resolve();
        ^
src/index.ts:2:9 23

error: Unexpected .
  await Promise.resolve();
               ^
src/index.ts:2:16 30
```

**Comment by Electroid** [comment]
We made this better.

```js
❯ bun index.js
2 |   await Promise.resolve();
            ^
error: "await" can only be used inside an "async" function
    at index.js:2:9

1 | function x() {
    ^
note: Consider adding the "async" keyword here
   at index.js:1:1

2 |   await Promise.resolve();
                   ^
error: Unexpected .
    at index.js:2:16
```
