### ISSUE TITLE
Installing Plasmo Framework.

### ISSUE THREAD

**Issue by SamHoque** [oven-sh/bun#10801]
### What version of Bun is running?

1.1.7

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

running `bin i`

```
[3.51ms] ".env"
bun install v1.1.7 (b0b7db5c)
  ⚙️  sharp [6/6] sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.5/libvips-8.14.5-win32-x64.tar.br

C:\Users\princ\IdeaProjects\dfm-extention\node_modules\sharp>if not defined npm_config_node_gyp (bun x --silent node-gyp rebuild )  else (node "" rebuild )

104 |   };
105 |
106 |   stream.pipeline(
107 |     fs.createReadStream(tarPath),
108 |     verifyIntegrity(platformAndArch),
109 |     new zlib.BrotliDecompress(),
          ^
error: zlib.BrotliDecompress is not implemented
      at new  (node:zlib:2269:65)
      at extractTarball (C:\Users\princ\IdeaProjects\dfm-extention\node_modules\sharp\install\libvips.js:109:5)
      at C:\Users\princ\IdeaProjects\dfm-extention\node_modules\sharp\install\libvips.js:214:15
      at node:stream:3743:89
      at node:fs:61:45

Bun v1.1.7 (Windows x64)
gyp info it worked if it ends with ok
gyp info using node-gyp@10.1.0
gyp info using node@21.6.0 | win32 | x64
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if the py launcher can be used to find Python 3
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - executable path is ""
gyp ERR! find Python - "" could not be run
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - executable path is ""
gyp ERR! find Python - "" could not be run
gyp ERR! find Python checking if Python is C:\Users\princ\AppData\Local\Programs\Python\Python311\python.exe
gyp ERR! find Python - "C:\Users\princ\AppData\Local\Programs\Python\Python311\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python311\python.exe
gyp ERR! find Python - "C:\Program Files\Python311\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Users\princ\AppData\Local\Programs\Python\Python311-32\python.exe
gyp ERR! find Python - "C:\Users\princ\AppData\Local\Programs\Python\Python311-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python311-32\python.exe
gyp ERR! find Python - "C:\Program Files\Python311-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python311-32\python.exe
gyp ERR! find Python - "C:\Program Files (x86)\Python311-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Users\princ\AppData\Local\Programs\Python\Python310\python.exe
gyp ERR! find Python - "C:\Users\princ\AppData\Local\Programs\Python\Python310\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python310\python.exe
gyp ERR! find Python - "C:\Program Files\Python310\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Users\princ\AppData\Local\Programs\Python\Python310-32\python.exe
gyp ERR! find Python - "C:\Users\princ\AppData\Local\Programs\Python\Python310-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python310-32\python.exe
gyp ERR! find Python - "C:\Program Files\Python310-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python310-32\python.exe
gyp ERR! find Python - "C:\Program Files (x86)\Python310-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Users\princ\AppData\Local\Programs\Python\Python39\python.exe
gyp ERR! find Python - "C:\Users\princ\AppData\Local\Programs\Python\Python39\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python39\python.exe
gyp ERR! find Python - "C:\Program Files\Python39\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Users\princ\AppData\Local\Programs\Python\Python39-32\python.exe
gyp ERR! find Python - "C:\Users\princ\AppData\Local\Programs\Python\Python39-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python39-32\python.exe
gyp ERR! find Python - "C:\Program Files\Python39-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python39-32\python.exe
gyp ERR! find Python - "C:\Program Files (x86)\Python39-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Users\princ\AppData\Local\Programs\Python\Python38\python.exe
gyp ERR! find Python - "C:\Users\princ\AppData\Local\Programs\Python\Python38\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python38\python.exe
gyp ERR! find Python - "C:\Program Files\Python38\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Users\princ\AppData\Local\Programs\Python\Python38-32\python.exe
gyp ERR! find Python - "C:\Users\princ\AppData\Local\Programs\Python\Python38-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files\Python38-32\python.exe
gyp ERR! find Python - "C:\Program Files\Python38-32\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python38-32\python.exe
gyp ERR! find Python - "C:\Program Files (x86)\Python38-32\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack at fail (C:\Users\princ\AppData\Local\Temp\bunx-476061093-node-gyp@latest\node_modules\node-gyp\lib\find-python.js:305:67)
gyp ERR! stack at processTicksAndRejections (:12:39)
gyp ERR! System Windows_NT 10.0.22631
gyp ERR! command "C:\\Users\\princ\\AppData\\Local\\Temp\\bun-node-b0b7db5c0\\node.exe" "C:\\Users\\princ\\AppData\\Local\\Temp\\bunx-476061093-node-gyp@latest\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\princ\IdeaProjects\dfm-extention\node_modules\sharp
gyp ERR! node -v v21.6.0
gyp ERR! node-gyp -v v10.1.0
gyp ERR! not ok

error: install script from "sharp" exited with 1
PS C:\Users\princ\IdeaProjects\dfm-extention> bun i 
[0.00ms] ".env"
bun install v1.1.7 (b0b7db5c)

 8 packages installed [697.00ms]
PS C:\Users\princ\IdeaProjects\dfm-extention> bun dev
$ plasmo dev
32 |     if (loadedModule) {
33 |       const [, loadedPackage] = loadedModule.match(/node_modules[\\/]([^\\/]+)[\\/]/);
34 |       help.push(`- Ensure the version of sharp aligns with the ${loadedPackage} package: "npm ls sharp"`);
35 |     }
36 |   }
37 |   throw new Error(help.join('\n'));
             ^
error:
Something went wrong installing the "sharp" module

Cannot find module "../build/Release/sharp-win32-x64.node" from "C:\Users\princ\IdeaProjects\dfm-extention\node_modules\sharp\lib\sharp.js"

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current win32-x64 runtime: "npm install --platform=win32 --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
      at C:\Users\princ\IdeaProjects\dfm-extention\node_modules\sharp\lib\sharp.js:37:9
      at C:\Users\princ\IdeaProjects\dfm-extention\node_modules\sharp\lib\constructor.js:11:1
      at C:\Users\princ\IdeaProjects\dfm-extention\node_modules\sharp\lib\index.js:6:7

Bun v1.1.7 (Windows x64)
error: script "dev" exited with code 1
PS C:\Users\princ\IdeaProjects\dfm-extention> bun i
[0.00ms] ".env"
bun install v1.1.7 (b0b7db5c)

Checked 680 installs across 725 packages (no changes) [55.00ms]
PS C:\Users\princ\IdeaProjects\dfm-extention> bun i --force
[0.00ms] ".env"
bun install v1.1.7 (b0b7db5c)
  ⚙️  sharp [3/6] sharp: Using cached C:\Users\princ\AppData\Roaming\npm-cache\_libvips\libvips-8.14.5-win32-x64.tar.br
sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies

C:\Users\princ\IdeaProjects\dfm-extention\node_modules\sharp>if not defined npm_config_node_gyp (bun x --silent node-gyp rebuild )  else (node "" rebuild )


sharp: Installation error: zlib.BrotliDecompress is not implemented
gyp info it worked if it ends with ok
gyp info using node-gyp@10.1.0
gyp info using node@21.6.0 | win32 | x64
gyp info find Python using Python version 3.12.3 found at "C:\Users\princ\AppData\Local\Programs\Python\Python312\python.exe"
gyp http GET https://nodejs.org/dist/v21.6.0/node-v21.6.0-headers.tar.gz
gyp http 200 https://nodejs.org/dist/v21.6.0/node-v21.6.0-headers.tar.gz
gyp ERR! error while extracting tarball TAR_ENTRY_ERROR Invalid argument
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: There was a fatal problem while downloading/extracting the tarball
gyp ERR! stack at <anonymous> (C:\Users\princ\AppData\Local\Temp\bunx-476061093-node-gyp@latest\node_modules\node-gyp\lib\install.js:256:20)
gyp ERR! stack at processTicksAndRejections (:12:39)
gyp ERR! System Windows_NT 10.0.22631
gyp ERR! command "C:\\Users\\princ\\AppData\\Local\\Temp\\bun-node-b0b7db5c0\\node.exe" "C:\\Users\\princ\\AppData\\Local\\Temp\\bunx-476061093-node-gyp@latest\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\princ\IdeaProjects\dfm-extention\node_modules\sharp
gyp ERR! node -v v21.6.0
gyp ERR! node-gyp -v v10.1.0
gyp ERR! not ok
```

**Comment by thienandangthanh** [comment]
Because `zlib.BrotliDecompress is not implemented`.

As @Jarred-Sumner stated in https://github.com/oven-sh/bun/issues/7248#issuecomment-2094649081.
> Please follow along in https://github.com/oven-sh/bun/issues/267.
> This issue is being addressed in https://github.com/oven-sh/bun/pull/10722, which will likely ship in Bun v1.1.8 next week.

**Comment by nektro** [comment]
works in canary / the new release once available

<img width="489" alt="image" src="https://github.com/oven-sh/bun/assets/5464072/746279a8-a15d-4598-bc05-b54577e28434">
