### ISSUE TITLE
TypeError: undefined is not an object on object constructor

### ISSUE THREAD

**Issue by tcklpl** [oven-sh/bun#10961]
### What version of Bun is running?

1.1.8-canary.1+159e8bc2a

### What platform is your computer?

Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

I was experimenting transitioning my project from node to bun and I stumbled upon this weird type error:
```bash
➜  server git:(dev) bun src/index.ts
 7 | export class GameServer {
 8 |     private _playerManager = new PlayerManager(this._log.createChildContext('Player Manager'));
 9 |     private _lobbyManager!: LobbyManager;
10 |
11 |     constructor(
12 |         private _configManager: ConfigManager,
                     ^
TypeError: undefined is not an object (near '...}...')
      at new GameServer (/home/tcklpl/projects/war/server/src/game/game_server.ts:12:17)
      at new WarServer (:1:27)
      at /home/tcklpl/projects/war/server/src/index.ts:3:16

Bun v1.1.8-canary.1+159e8bc2a (Linux x64)
```

But the same project works perfectly with ts-node:

```bash
➜  server git:(dev) npx ts-node src/index.ts

        War Server 0.0.1 (Development)
        Source available at https://github.com/tcklpl/war
        Enter help to see the command list.

[20:03:03] [INFO ] War Server >>> Initializing server
[20:03:03] [INFO ] War Server > Config Manager >>> Loading configs
[20:03:03] [INFO ] War Server > Crypt Manager >>> Reading key files
[20:03:03] [INFO ] War Server > Crypt Manager >>> Keys are loaded
[20:03:03] [INFO ] War Server > Game Server >>> Game server started
[20:03:03] [INFO ] War Server > Express Server >>> REST Server listening on localhost:36875
[20:03:03] [INFO ] War Server > Socket Server >>> Socket Server listening on localhost:36876
[20:03:03] [INFO ] War Server >>> Server started successfully in 17ms
^C[20:03:06] [INFO ] War Server >>> Stopping server...
[20:03:06] [INFO ] War Server >>> Server closed
```

And compiles with `tsc` without any errors:
```bash
➜  server git:(dev) npx tsc --build
➜  server git:(dev)
```

This is the most recent commit of my project as I'm writing this issue: [here](https://github.com/tcklpl/war/tree/242ac4c7f73b925184902b25148720e450a9748c/server)

Steps to reproduce:
1. `git clone https://github.com/tcklpl/war.git`
2. `git checkout dev`
3. `git reset --hard 242ac4c`
4. `cd server`
5. `bun i`
6. `bun src/index.ts`

### What is the expected behavior?

For my server to start

### What do you see instead?

```bash
➜  server git:(dev) bun src/index.ts
 7 | export class GameServer {
 8 |     private _playerManager = new PlayerManager(this._log.createChildContext('Player Manager'));
 9 |     private _lobbyManager!: LobbyManager;
10 |
11 |     constructor(
12 |         private _configManager: ConfigManager,
                     ^
TypeError: undefined is not an object (near '...}...')
      at new GameServer (/home/tcklpl/projects/war/server/src/game/game_server.ts:12:17)
      at new WarServer (:1:27)
      at /home/tcklpl/projects/war/server/src/index.ts:3:16

Bun v1.1.8-canary.1+159e8bc2a (Linux x64)
```

### Additional information

The error is thrown inside this constructor:
```ts
import { ConfigManager } from '../config/config_manager';
import { CryptManager } from '../crypt/crypt_manager';
import { PlayerManager } from './player/player_manager';
import { LobbyManager } from './lobby/lobby_manager';
import { Logger } from '../log/logger';

export class GameServer {
    private _playerManager = new PlayerManager(this._log.createChildContext('Player Manager'));
    private _lobbyManager!: LobbyManager;

    constructor(
        private _configManager: ConfigManager,
        private _cryptManager: CryptManager,
        private _log: Logger,
    ) {}

    async initialize() {
        this._log.info('Game server started');
        this._lobbyManager = new LobbyManager(this._configManager, this, this._log.createChildContext('Lobby Manager'));
    }

    async stop() {
        await this._lobbyManager.stop();
    }

    get playerManager() {
        return this._playerManager;
    }

    get lobbyManager() {
        return this._lobbyManager;
    }
}
```

**Comment by DoctorGester** [comment]
Experiencing the same thing:

```ts
export class TransformationContext {
    public readonly diagnostics: ts.Diagnostic[] = [];
    public readonly checker = this.program.getTypeChecker() as TypeCheckerWithEmitResolver;
    public readonly resolver: EmitResolver;
    public readonly precedingStatementsStack: lua.Statement[][] = [];

    public readonly options: CompilerOptions = this.program.getCompilerOptions();
    public readonly luaTarget = this.options.luaTarget ?? LuaTarget.Universal;
    public readonly isModule = ts.isExternalModule(this.sourceFile);
    public readonly isStrict =
        (this.options.alwaysStrict ?? this.options.strict) ||
        (this.isModule && this.options.target !== undefined && this.options.target >= ts.ScriptTarget.ES2015);

    constructor(public program: ts.Program, public sourceFile: ts.SourceFile, private visitorMap: VisitorMap) {
        const originalSourceFile = ts.getParseTreeNode(sourceFile, ts.isSourceFile) ?? sourceFile;
        this.resolver = this.checker.getEmitResolver(originalSourceFile);
    }
}
```

Moving all the member initializers into the constructor fixes the issue.
