### ISSUE TITLE
Bun cannot run archiver module

### ISSUE THREAD

**Issue by LunaFolf** [oven-sh/bun#10986]
### What version of Bun is running?

1.1.7

### What platform is your computer?

Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

> test.ts
```ts
import * as fs from "fs"
import archiver from "archiver"

const output = fs.createWriteStream("./output.zip")
const archive = archiver("zip", { zlib: { level: 9 } })

output.on("close", () => {
  console.log("Zip file created successfully")
})

archive.on("error", (err) => {
  throw err
})

archive.pipe(output)

// Add a test file to the zip
const testFilePath = "./test.txt"
archive.file(testFilePath, { name: "test.txt" })

archive.finalize()
```

All files for a simple test can be found in this gist: https://gist.github.com/LunaFolf/94f8c0a46093028d43d606c54731f857

### What is the expected behavior?

Creation of a `output.zip` file, containing a `test.txt` with the original contents of it's file.

### What do you see instead?

`output.zip` is created, and does contain a `test.txt`, however, the `test.txt` has a file size of zero and can not be extracted due to erroneous data.

Bun fails, with the following error:
```
luna@BEEF:~/projects/10416$ bun ./test.ts
28 |
29 |   beforeFirstCall(this, '_read', function() {
30 |     var source = fn.call(this, options);
31 |     var emit = this.emit.bind(this, 'error');
32 |     source.on('error', emit);
33 |     source.pipe(this);
         ^
TypeError: undefined is not an object
      at node:stream:2087:83
      at /home/luna/projects/10416/node_modules/lazystream/lib/lazystream.js:33:5
      at /home/luna/projects/10416/node_modules/lazystream/lib/lazystream.js:18:5
      at /home/luna/projects/10416/node_modules/lazystream/node_modules/readable-stream/lib/_stream_readable.js:443:5
      at resume_ (/home/luna/projects/10416/node_modules/lazystream/node_modules/readable-stream/lib/_stream_readable.js:790:5)

Bun v1.1.7 (Linux x64)
```

### Additional information

Issue has been previously reported in https://github.com/oven-sh/bun/issues/10416 and is suggested to have been fixed, however this does not seam to be the case.

**Comment by LunaFolf** [comment]
Fixed in v1.1.8! Amazing timing.
