### ISSUE TITLE
Crash using winax from npm

### ISSUE THREAD

**Issue by ironpain** [oven-sh/bun#11007]
### How can we reproduce the crash?

Install from https://www.npmjs.com/package/winax
npm i winax

### JavaScript/TypeScript code that reproduces the crash?

```shell
import {default as wax} from 'winax';
new wax.Object ('ADODB.Connection');
```

### Relevant log output

```shell
var ActiveX = module.exports = require('./build/Release/node_activex.node');
                         ^
TypeError: LoadLibrary failed: Eine DLL-Initialisierungsro
      at D:\workspace\node_space\snippets\node_modules\winax\activex.js:1:22
      at D:\workspace\node_space\snippets\node_modules\winax\index.js:1:8

Bun v1.1.7 (Windows x64)
============================================================
Bun v1.1.7 (b0b7db5c) Windows x64
Args: "C:\Users\ironpain\.bun\bin\bun.exe", ".\src\index.ts"
Features: jsc tsconfig(2) 
Builtins: "bun:main" 
Elapsed: 223ms | User: 0ms | Sys: 31ms
RSS: 110.81MB | Peak: 110.81MB | Commit: 0.16GB | Faults: 27349

panic(main thread): Segmentation fault at address 0x7FFA00272654
oh no: Bun has crashed. This indicates a bug in Bun, not your code
```

### Stack Trace (bun.report)

Bun v1.1.7 ([`b0b7db5`](https://github.com/oven-sh/bun/tree/b0b7db5c060e830801b0273b7ff6e34e3eb5c254)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x7FFF1FA70E18

- *1 unknown/js code*
- ??? at `0x5129c` in ntdll.dll
- ??? at `0x50ff7` in ntdll.dll
- ??? at `0x50c9d` in ntdll.dll
- ??? at `0x17fab` in KERNEL32.DLL
- ??? at `0x1bed8` in ucrtbase.dll
- ??? at `0x1c099` in ucrtbase.dll
- [`Global.zig:123`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/Global.zig#L123): `exitWide`
- [`Global.zig:106`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/Global.zig#L106): `exit`
- [`javascript.zig:907`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/bun.js/javascript.zig#L907): `eventLoop`

**Comment by RiskyMH** [comment]
We've invested a ton of time into making Bun more reliable over the last year. I'm having a really hard time reproducing in latest Bun (can repo in `1.1.8`). If you're still running into this issue, please let me know and I'll re-open this
