### ISSUE TITLE
setEncoding function missing

### ISSUE THREAD

**Issue by Almenon** [oven-sh/bun#11011]
### What version of Bun is running?

Bun v1.1.8

### What platform is your computer?

macOS arm64

### What steps can reproduce the bug?

```javascript
import { PythonShell } from 'python-shell';

PythonShell.runString('x=1+1;print(x)', null).then((messages) => {
  console.log('finished');
});
```

### What is the expected behavior?

2 is shown.

### What do you see instead?
```ts
$ bun example.js
128 |         this.stderrParser = resolve('parse', options.stderrParser || 'text');
129 |         this.terminated = false;
130 |         this.childProcess = (0, child_process_1.spawn)(pythonPath, this.command, options);
131 |         ['stdout', 'stdin', 'stderr'].forEach(function (name) {
132 |             self[name] = self.childProcess[name];
133 |             self.parser && self[name] && self[name].setEncoding(options.encoding || 'utf8');
                                               ^
TypeError: self[name].setEncoding is not a function. (In 'self[name].setEncoding(options.encoding || "utf8")', 'self[name].setEncoding' is undefined)
      at /Users/exkazuu/ghq/github.com/WillBoosterLab/repair-ai/node_modules/python-shell/index.js:133:42
      at forEach (:1:21)
      at new PythonShell (/Users/exkazuu/ghq/github.com/WillBoosterLab/repair-ai/node_modules/python-shell/index.js:131:9)
      at /Users/exkazuu/ghq/github.com/WillBoosterLab/repair-ai/node_modules/python-shell/index.js:252:27
      at new Promise (:1:21)
      at run (/Users/exkazuu/ghq/github.com/WillBoosterLab/repair-ai/node_modules/python-shell/index.js:251:16)
      at /Users/exkazuu/ghq/github.com/WillBoosterLab/repair-ai/example.js:3:1
```
### Additional information

This is a function supported by NodeJS (see https://nodejs.org/api/stream.html#readablesetencodingencoding), so I presume it should be supported by Bun as well.

**Comment by KodeurKubik** [comment]
+1

**Comment by dillonstreator** [comment]
Experiencing the same issue with the [`say`](https://www.npmjs.com/package/say) library
```ts
import say from "say";

say.speak("testing");
```
https://github.com/Marak/say.js/blob/2d83f239356cb013353d2e98bb32cbeec456f60a/platform/base.js#L35-L36
