### ISSUE TITLE
bun build transforms modules.exports.now to exports.now - breaks date-format and log4js packages

### ISSUE THREAD

**Issue by GeoffWilliams** [oven-sh/bun#11175]
### What version of Bun is running?

1.1.8+89d25807f

### What platform is your computer?

Linux 6.1.0-17-amd64 x86_64 unknown

### What steps can reproduce the bug?

When using `bun build` with [date-format](https://www.npmjs.com/package/date-format), `modules.exports` is getting transpiled to `exports` which causes runtime errors.

This testcase demonstrates the error - I was also getting a similar error from [log4js](https://www.npmjs.com/package/log4js
)

**create project**

```shell
bun init
bun add date-format
```

**index.ts**

```typescript
import dateFormat from "date-format";
console.log(dateFormat.asString(new Date().toISOString()));
```

**build**

```shell
bun build --outdir build index.ts --target=bun
```

**run testcase**

```shell
bun ./build/index.js
```

### What is the expected behavior?

Should print the current date to console, no errors. Eg:

```
2024-05-19T03:47:19.008Z
```

### What do you see instead?

Bun reports error because `exports.now` is undefined:

```
40 |     if (typeof format !== "string") {
41 |       date = format;
42 |       format = exports.ISO8601_FORMAT;
43 |     }
44 |     if (!date) {
45 |       date = exports.now();
                  ^
TypeError: exports.now is not a function. (In 'exports.now()', 'exports.now' is undefined)
      at asString (/home/geoff/tmp/expr/testcase/build/index.js:45:14)
      at /home/geoff/tmp/expr/testcase/build/index.js:184:13

Bun v1.1.8 (Linux x64)
```

If we look in the source codes of `date-format` package, we see `module.exports.now()` - bun removed the `module.` qualification which breaks the library:

```javascript
// from node_modules/date-format/lib/index.js
function asString(format, date) {
  if (typeof format !== "string") {
    date = format;
    format = module.exports.ISO8601_FORMAT;
  }
  if (!date) {
    date = module.exports.now();
  }
```

If I edit `build/index.js` and change back to `module.exports.now` the codes works as expected.

### Additional information

I originally found this because log4js was erroring when using `bun build` and `bun build --compile`:

```
914 |     }
915 |     var vDay = addZero(date.getDate());
916 |     var vMonth = addZero(date.getMonth() + 1);
917 |     var vYearLong = addZero(date.getFullYear());
918 |     var vYearShort = addZero(vYearLong.substring(2, 4));
919 |     var vYear = format.indexOf("yyyy") > -1 ? vYearLong : vYearShort;
                      ^
TypeError: undefined is not an object (evaluating 'format.indexOf')
      at asString (/home/geoff/tmp/expr/testcase/build/index.js:919:17)
      at timestampLevelAndCategory (/home/geoff/tmp/expr/testcase/build/index.js:1062:52)
      at colouredLayout (/home/geoff/tmp/expr/testcase/build/index.js:1068:12)
      at /home/geoff/tmp/expr/testcase/build/index.js:1813:31
      at /home/geoff/tmp/expr/testcase/build/index.js:6044:7
      at forEach (:1:21)
      at sendLogEventToAppender (/home/geoff/tmp/expr/testcase/build/index.js:6043:5)
      at forEach (:1:21)
      at sendToListeners (/home/geoff/tmp/expr/testcase/build/index.js:1680:5)
      at send (/home/geoff/tmp/expr/testcase/build/index.js:1731:9)

Bun v1.1.8 (Linux x64)
```

**Workaround**

1. Build with `--external=date-format`
2. `node_modules/date-format` resolvable

Found via: https://github.com/oven-sh/bun/issues/7024

**Comment by robobun** [comment]
## Status: ALREADY FIXED

## Issue Description
The reporter found that `bun build` was incorrectly transforming `module.exports.xxx` references to just `exports.xxx` in the bundled output, which broke the `date-format` package (and by extension `log4js`). Specifically, `module.exports.now()` became `exports.now()` which was undefined at runtime.

## Reproduction Steps Attempted

### Setup
```bash
mkdir -p /tmp/test-11175 && cd /tmp/test-11175
bun init -y
bun add date-format
```

### Test file (index.ts)
```typescript
import dateFormat from "date-format";
console.log(dateFormat.asString(new Date().toISOString()));
```

### Test 1: System bun (v1.3.9) with --target=bun
```bash
bun build --outdir build index.ts --target=bun
bun ./build/index.js
```
**Result:** Successfully outputs date string: `2026-02-19T09:15:58.220Z`

### Test 2: Debug build (current main branch) with --target=bun
```bash
bun-debug build --outdir build index.ts --target=bun
bun-debug ./build/index.js
```
**Result:** Successfully outputs date string: `2026-02-19T09:16:13.259Z`

### Test 3: System bun without --target=bun
```bash
bun build --outdir build index.ts
bun ./build/index.js
```
**Result:** Successfully outputs date string: `2026-02-19T09:16:23.810Z`

## Bundled Output Analysis

The bundled output now correctly preserves `module.exports` references:

```javascript
// Lines from build/index.js showing correct module.exports preservation:
format = module.exports.ISO8601_FORMAT;
date = module.exports.now();
var date = missingValuesDate || module.exports.now();
module.exports.asString = asString;
module.exports.parse = parse;
module.exports.now = now;
module.exports.ISO8601_FORMAT = "yyyy-MM-ddThh:mm:ss.SSS";
```

The original bug reported that these were incorrectly transformed to just `exports.xxx` (without the `module.` prefix), but this is no longer the case.

## Conclusion
The bug was reported against Bun v1.1.8 and has been fixed in the current version (v1.3.9 / current main branch). The bundler now correctly preserves `module.exports` references in CJS modules rather than incorrectly shortening them to `exports`.
---
*This is an automated comment.*
