### ISSUE TITLE
Implement node:v8 setFlagsFromString

### ISSUE THREAD

**Issue by roderik** [oven-sh/bun#11264]
### What is the problem this feature would solve?

I'm trying to run a nestjs application which uses the Pulumi automation api, it appears to use setFlagsFromString which is currently not implemented

```
NotImplementedError: node:v8 setFlagsFromString is not yet implemented in Bun.
 code: "ERR_NOT_IMPLEMENTED"

      at new NotImplementedError (internal:shared:19:14)
      at internal:shared:2:35
      at node:v8:2:23
      at node:v8:30:33
      at /Users/roderik/Development/btp/node_modules/@pulumi/pulumi/runtime/closure/v8.js:135:12
      at anonymous (native:1:1)
      at /Users/roderik/Development/btp/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:393:29
      at anonymous (native:1:1)
      at /Users/roderik/Development/btp/node_modules/@pulumi/pulumi/runtime/closure/serializeClosure.js:122:14
      at anonymous (native:1:1)
      at /Users/roderik/Development/btp/node_modules/@pulumi/pulumi/runtime/index.js:30:31
      at anonymous (native:1:1)
      at /Users/roderik/Development/btp/node_modules/@pulumi/pulumi/index.js:48:18
      at anonymous (native:1:1)
      at /Users/roderik/Development/btp/node_modules/@pulumi/aws/appconfig/index.js:8:1

Bun v1.1.9 (macOS arm64)
```

### What is the feature you are proposing to solve the problem?

Not a clue what it does, but it would make this error go away

### What alternatives have you considered?

Sticking to node 🤷🏻

**Comment by Electroid** [comment]
It looks like that package also depends on supporting the Chrome DevTools Protocol (it calls the inspector)

That is a more complicated project, we do want to do this eventually, but unfortunately this won't be a quick fix.

**Comment by Karakatiza666** [comment]
Just had the same error because setFlagsFromString was referenced in Pulumi (which is used in [sst](https://sst.dev) )

**Comment by ritikkumar112411** [comment]
It has 2 possibilities:
1. try to check node, sst, bun are successfully installed in your wsl 
2. try running npx sst dev instead of bun sst dev 
If still gives same error please comment back I will resolve that for sure

**Comment by zvictor** [comment]
For anyone struggling with `setFlagsFromString is not yet implemented in Bun`:

**You MUST have `node` installed and in your `PATH`** regardless of you running `bunx sst` instead of `npx sst` or not.

I can guarantee  you that, because I run my projects in [nix isolated environments](https://mtlynch.io/notes/nix-dev-environment/) and enabling `node` solves the issue for me.

Failing `shell.nix`:
```nix
{ pkgs ? import <nixpkgs> {} }:

pkgs.mkShell {
  nativeBuildInputs = with pkgs.buildPackages; [
    # corepack_latest
    # nodePackages_latest.nodejs
    bun
  ];
}
```

Working `shell.nix`:
```nix
{ pkgs ? import <nixpkgs> {} }:

pkgs.mkShell {
  nativeBuildInputs = with pkgs.buildPackages; [
    # corepack_latest
    nodePackages_latest.nodejs
    bun
  ];
}
```
