### ISSUE TITLE
Bun doesn't work with @discordjs/voice

### ISSUE THREAD

**Issue by SkyLissh** [oven-sh/bun#11313]
### What version of Bun is running?

1.1.9

### What platform is your computer?

Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Create a basic example of a bot that needs to reproduce an audio file in a voice channel, install the following libs:

- discordjs
- @discordjs/voice
- @discordjs/opus
- libsodium-wrappers
- ffmpeg-static

You can use the following code:

```ts
const channel = interaction.channel;
    if (!channel || !channel.isVoiceBased()) return;

    const connectionChannel = joinVoiceChannel({
      channelId: channel.id,
      guildId: (channel as VoiceBasedChannel).guild.id,
      adapterCreator: (channel as VoiceBasedChannel).guild.voiceAdapterCreator,
    });

    connectionChannel.on(VoiceConnectionStatus.Signalling, () => {
      console.log("Connecting...");
    });
    connectionChannel.on(VoiceConnectionStatus.Ready, () => {
      console.log("Player ready");
    }); 

    const speechFile = path.resolve(process.cwd(), "speech.mp3");

    const connection = getVoiceConnection(interaction.guildId!);
    if (!connection) return;

    const resource = createAudioResource(speechFile, {
      metadata: { title: "test" },
    });
    const player = createAudioPlayer();

    player.on(AudioPlayerStatus.Idle, () => {
      console.log("Idle");
    });
    player.on(AudioPlayerStatus.Buffering, () => {
      console.log("Buffering");
    });
    player.on(AudioPlayerStatus.Playing, () => {
      console.log("Playing");
    });
    player.on("stateChange", (oldState, newState) => {
      console.log(
        `Audio player transitioned from ${oldState.status} to ${newState.status}`
      );
    });
    player.on("error", (error) => {
      console.error("Error:", error.message);
    });

    connection.subscribe(player);
    player.play(resource);
```

### What is the expected behavior?

That when the code is executed the bot plays successfully an audio in the voice channel of discord

### What do you see instead?

When running the previous code the bot will get stuck in the `Buffering` state and never change to `Playing` state, this exact code was tested also on Node 20.13.1 and it works as expected.

### Additional information

I think this may be related to the @discordjs/opus library, when running the following code

```ts
import { OpusEncoder } from "@discordjs/opus"

console.log(OpusEncoder);
```

It throws the following error:

`error: Cannot find module "node_modules/@discordjs/opus/prebuild/node-v115-napi-v3-linux-x64-glibc-2.29/opus.node" from "node_modules/@discordjs/opus/lib/index."`

This code also was tested on MacOS Darwin 23.3.0 arm64, and the previous error doesn't show up, but the stuck in `Buffering` state remains.

**Comment by Svapnil** [comment]
Just ran into this same issue aswell while using Bun for voice

**Comment by vladfrangu** [comment]
Did you add `@discordjs/voice` as a trustedDependency? We have a postinstall script that actually downloads a prebuilt opus binding or compiles one for your system

**Comment by SkyLissh** [comment]
No I didn't think that I have to add `@discordjs/voice` to trusted deps because the `@discordjs/opus` is already in the default truested deps in bun

**Comment by zupanibla** [comment]
It works in deno.

**Comment by Wiibleyde** [comment]
Any new on this ? the discord-voip lib has a bug for the same reason :
```
TimeoutNegativeWarning: -29 is a negative number.
Timeout duration was set to 1.
      at prepareNextAudioFrame (/home/wiibleyde/Documents/Perso/Eve/node_modules/discord-voip/dist/index.js:128:28)
```

My code work with node but not with bun

**Comment by adil-chbada** [comment]
We're experiencing a similar issue with another package (`kafkajs`) when using Bun. Starting from **Bun v1.2.5**, the package throws an error on startup.

Here's what we've confirmed so far:

- ✅ **Bun v1.2.4** — Works without issues  
- ❌ **Bun v1.2.5 to v1.2.10** — All versions in this range **throw an error** when using `kafkajs`

We're testing on:
- **OS**: Windows 11 Pro (Build 26100)

**Comment by Wiibleyde** [comment]
Just to had a precision, the problem is probably "bigger" I've juste had the same problem with the cron lib : 
```
TimeoutNegativeWarning: -1 is a negative number.
Timeout duration was set to 1.
      at setCronTimeout (/Users/nathan/Documents/Dev/Perso/Eve/node_modules/cron/dist/job.js:155:29)
      at callbackWrapper (/Users/nathan/Documents/Dev/Perso/Eve/node_modules/cron/dist/job.js:178:17)
```

**Comment by Lqm1** [comment]
I'm considering moving my TypeScript Discord bot to Bun.
It mostly works, but I get the following warning:

```
TimeoutNegativeWarning: -8 is a negative number.
Timeout duration was set to 1.
      at prepareNextAudioFrame (D:\Desktop\Projects\example-bot\node_modules\@discordjs\voice\dist\index.mjs:78:28)
```

Is this warning valid? Is the problem caused by discord.js or by Bun?
If I ignore it, will it cause problems in production?
