### ISSUE TITLE
Fix flaky test `child_process-node.test.js`

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#11478]
```js
229 |     );
230 |   });
231 |
232 |   it("should handle killed process", async () => {
233 |     await createChild({ timeout: 1 }, (err, stdout, stderr) => {
234 |       strictEqual(err.killed, true);
                        ^
TypeError: null is not an object (evaluating 'err.killed')
      at /opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-aws-1/bun/bun/test/js/node/child_process/child_process-node.test.js:234:19
      at /opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-aws-1/bun/bun/test/js/node/child_process/child_process-node.test.js:201:17
      at /opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-aws-1/bun/bun/test/js/node/child_process/child_process-node.test.js:199:52
      at exitHandler (node:child_process:69:45)
      at emit (node:events:180:95)
      at #maybeClose (node:child_process:795:27)
      at #handleOnExit (node:child_process:591:31)
✗ ChildProcess spawn bad stdio > should handle killed process [10.36ms]
```

**Comment by sirenkovladd** [comment]
Fixed in https://github.com/oven-sh/bun/pull/11496
