### ISSUE TITLE
Unsupported encoding label "shift_jis"

### ISSUE THREAD

**Issue by sevenc-nanashi** [oven-sh/bun#11564]
### What version of Bun is running?

1.1.12

### What platform is your computer?

Linux 5.15.123.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Run this code:
```js
const bytes = [147, 250, 150, 123, 140, 234];

const decoder = new TextDecoder("shift_jis");
const data = decoder.decode(Uint8Array.from(bytes));
console.log(data);
```

### What is the expected behavior?

It decodes bytes as SHIFT-JIS (and prints `日本語`)

### What do you see instead?

```js
❯ bun __gi_td.js 
1 | const bytes = [147, 250, 150, 123, 140, 234];
2 | 
3 | const decoder = new TextDecoder("shift_jis");
                    ^
TypeError: Unsupported encoding label "shift_jis"
 code: "ERR_INVALID_ARG_TYPE"

      at /home/sevenc7c/utaformatix-ts/__gi_td.js:3:17

Bun v1.1.12 (Linux x64)
[ble: exit 1]
```

### Additional information

It works on other JS runtimes:
```bash
❯ deno run __gi_td.js 
日本語

❯ node __gi_td.js 
日本語

❯ bun __gi_td.js 
1 | const bytes = [147, 250, 150, 123, 140, 234];
2 | 
3 | const decoder = new TextDecoder("shift_jis");
                    ^
TypeError: Unsupported encoding label "shift_jis"
 code: "ERR_INVALID_ARG_TYPE"

      at /home/sevenc7c/utaformatix-ts/__gi_td.js:3:17

Bun v1.1.12 (Linux x64)
[ble: exit 1]
```
![image](https://github.com/oven-sh/bun/assets/59691627/9c5b0390-8127-4a91-a06f-e362a64657e4)

**Comment by kschniedergers** [comment]
running into the same issue
