### ISSUE TITLE
astro / There was an uncaught error in the middle of the stream while rendering

### ISSUE THREAD

**Issue by projaguar** [oven-sh/bun#11602]
### What version of Bun is running?

1.1.12

### What platform is your computer?

MAC. Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

1. create astro project
2. add and config auth-astro 
3. build  -  (bunx --bun astro build)
4. run preview - (bunx --bun astro preview)

### What do you see instead?

```
import { getSession } from 'auth-astro/server';
const session = await getSession(Astro.request);
```
this code make error

error
-----
There was an uncaught error in the middle of the stream while rendering /. 1 | (function (reason) {"use strict";
                        ^
TypeError: ReadableStreamDirectController is now closed
      at onReadableStreamDirectControllerClosed (:1:21)

### Additional information

'bunx --bun astro dev' There is no error with this command. The error message appears only in the distribution version.
pnpm works well

**Comment by AmirHmZz** [comment]
I've faced the same error with the  `bun v1.1.26` and `astro v4.15.4`.

**Comment by eitelkrauss** [comment]
Same error with bun v1.1.29 and astro v4.15.6

**Comment by alf5** [comment]
same error with bun 1.1.30, astro 4.16.5 and @astrojs/node 8.3.4

**Comment by jonaspm** [comment]
same error with
bun 1.1.33
astro 4.16.7

**Comment by leiyangyou** [comment]
error around the following lines in astro/dist/core/app/node.js

```
      destination.on("close", () => {
        reader.cancel().catch((err) => {
          console.error(
            `There was an uncaught error in the middle of the stream while rendering ${destination.req.url}.`,
            err
          );
        });
      });
```

should probably be 
```
      destination.on("close", () => {
       if (!reader.closed) {
        reader.cancel().catch((err) => {
          console.error(
            `There was an uncaught error in the middle of the stream while rendering ${destination.req.url}.`,
            err
          );
        });
      });
    }
```

**Comment by georgzoeller** [comment]
Seeing the same thing, bun, astro4 and 5 (both latest)

**Comment by bkyerv** [comment]
having similar thing in that error (see below) manifests when running build artifacts. when running the dev server I don't see any errors

```
(function (reason) {"use strict";
              ^
TypeError: ReadableStreamDirectController is now closed
```

**Comment by martinklepsch** [comment]
Also experiencing this issue with `bun 1.2.4` and `astro 5.2.0`

**Comment by bkyerv** [comment]
even running using --bun flag still results in this error

**Comment by AsenCME** [comment]
I'm seeing something similar but along the lines of:
```
15:20:23 [ERROR] Stream is already ended
  Stack trace:
    at cork (unknown)
    [...] See full stack trace in the browser, or rerun with --verbose.
15:20:23 [ERROR] [UnhandledRejection] Astro detected an unhandled rejection. Here's the stack trace:
Error: Stream is already ended
    at cork (unknown)
    at write (node:http:1205:18)
    at <anonymous> (/Users/asengeorgiev/Documents/projects/spacebite/site/apps/store/node_modules/astro/dist/vite-plugin-astro-server/response.js:23:9)
    at handle500Response (/Users/asengeorgiev/Documents/projects/spacebite/site/apps/store/node_modules/astro/dist/vite-plugin-astro-server/response.js:17:34)
    at onError (/Users/asengeorgiev/Documents/projects/spacebite/site/apps/store/node_modules/astro/dist/vite-plugin-astro-server/request.js:53:7)
    at <anonymous> (/Users/asengeorgiev/Documents/projects/spacebite/site/apps/store/node_modules/astro/dist/vite-plugin-astro-server/controller.js:67:19)
    at processTicksAndRejections (native:7:39)
  Hint:
    Make sure your promises all have an `await` or a `.catch()` handler.
  Error reference:
    https://docs.astro.build/en/reference/errors/unhandled-rejection/
  Stack trace:
    at cork (unknown)
    [...] See full stack trace in the browser, or rerun with --verbose.
```

Using the `node` and `react` integrations - yes - but this page in particular does not use any react components. The project is run with `bunx --bun astro dev`. If I run it without `bunx --bun ...` it does not throw this error.

Interestingly - this error does not result in termination - the app continues to work.

**Comment by RokoTechnology** [comment]
same issue here causing requests stuck in pending state, switching to node fixed it. wondering if this could be related to server sent events endpoint crashing causing unrelated endpoints to fail?

**Comment by Alipourzadi** [comment]
Same with ```astro 5.8.1``` and ```bun 1.2.15```

**Comment by jonaspm** [comment]
If you upgrade bun to latest version (1.2.23) do you still see the error?

**Comment by litek** [comment]
Looks like an upgrade fixed it for me at least, thanks @jonaspm

**Comment by alf5** [comment]
its fixes it for our astro 4.15.12 project where it used to produce the error/message.
