### ISSUE TITLE
Nuxt floating point error

### ISSUE THREAD

**Issue by raggesilver** [oven-sh/bun#11680]
### How can we reproduce the crash?

Bun crashed while running the Nuxt dev server (`bun --bun nuxt dev`).

[Repo](https://github.com/raggesilver/tasks.app).

**Note:** I'm running Bun canary due to #11303.

### Relevant log output

```shell
Bun Canary v1.1.13-canary.1 (af95bfc7) macOS x64
Args: "node" "/Users/paulo/Projects/tasks_app/node_modules/.bin/nuxt" "dev"
Features: jsc Bun.stdin(36) Bun.stdout(17) dotenv(18) fetch(185) http_server(17) https_server spawn(3)
 transpiler_cache(148) tsconfig_paths(14) tsconfig(39) 
Builtins: "bun:jsc" "bun:main" "detect-libc" "node:assert" "node:async_hooks" "node:buffer" "node:chil
d_process" "node:constants" "node:crypto" "node:dns" "node:events" "node:fs" "node:fs/promises" "node:
http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:process" "no
de:querystring" "node:readline" "node:stream" "node:stream/promises" "node:string_decoder" "node:tls" 
"node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" "node:worker_threads" "ws" "
node:v8" 
Elapsed: 1036511ms | User: 44602ms | Sys: 10037ms
RSS: 0.99GB | Peak: 1.06GB | Commit: 0.02ZB | Faults: 85

panic: Floating point error at address 0x1044D7AF5
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

error: Failed to run "nuxt" due to signal SIGILL
error: script "dev" was terminated by signal SIGILL (Illegal instruction)
[1]    31418 illegal hardware instruction  NODE_TLS_REJECT_UNAUTHORIZED=0 bun dev
```

### Stack Trace (bun.report)

Bun v1.1.13-canary ([`af95bfc`](<https://github.com/oven-sh/bun/tree/af95bfc7b1447d82e211d32fda3a34e5099c09cf>)) on macos x86_64 [RunAsNodeCommand]

Floating point exception at address 0x1044D7AF5

- *2 unknown/js code*
- `src.bun.js.api.bun.dns_resolver.InternalDNS.getaddrinfo`
- `Bun__addrinfo_get`
- `us_socket_context_connect`
- `src.deps.uws.NewSocketHandler`
- `BunObject_callback_connect`
- *1 unknown/js code*
- `llint_entry`
- `llint_entry`

Features: jsc, Bun.stdin, Bun.stdout, dotenv, fetch, http\_server, https\_server, spawn, transpiler\_cache, tsconfig\_paths, tsconfig

**Comment by raggesilver** [comment]
May be related to #11035

**Comment by nektro** [comment]
```
darwin-x64-mini-1 ❯ bun x bun@1.1.13 --bun nuxt dev
Nuxt 3.17.5 with Nitro 2.11.12                                                                                                                     nuxi 4:51:22 PM

 ERROR  OpenSSL BAD_PASSWORD_READ via OPENSSL_internal PEM routines                                                                                     4:51:23 PM
PEM routines via OPENSSL_internal SSL routines

    at <anonymous> (node:http:433:35)
    at fn (node:util:147:14)
    at <anonymous> (node_modules/listhen/dist/index.mjs:613:47)
    at processTicksAndRejections (:12:39) 



 ERROR  OpenSSL BAD_PASSWORD_READ via OPENSSL_internal PEM routines                                                                                     4:51:23 PM
PEM routines via OPENSSL_internal SSL routines

error: "nuxt" exited with code 1
```

and on the latest bun i get a similar error but not the crash detailed above

```
darwin-x64-mini-1 ❯ bun --bun nuxt dev
Nuxt 3.17.5 with Nitro 2.11.12                                                                                                                     nuxi 4:55:11 PM

 ERROR  [uncaughtException] BoringSSL error:09000068:PEM routines:OPENSSL_internal:BAD_PASSWORD_READ                                                    4:55:11 PM

    at serve (unknown)
    at [kRealListen] (node:http:350:41)
    at listen (node:http:327:35)
    at bound listen (internal:promisify:28:22)
    at <anonymous> (node_modules/listhen/dist/index.mjs:613:47)
    at processTicksAndRejections (unknown:7:39)
```

which cpu do you have on your mac?

you can retrieve that information with the following command:

```
❯ sysctl -a | grep machdep.cpu.brand_string
machdep.cpu.brand_string: Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
```
