### ISSUE TITLE
Astro/Starlight doesn't work due to locale issues

### ISSUE THREAD

**Issue by aaronmondal** [oven-sh/bun#11714]
### What version of Bun is running?

1.1.12+43f0913c3

### What platform is your computer?

Linux 6.9.2-gentoo x86_64 unknown

### What steps can reproduce the bug?

As of starlight `v0.24.0` bun no longer works with it. `v0.23.4` worked.

```bash
bun create astro@latest -- --template starlight
cd <path-to-project>
bun install
bun run dev
```

### What is the expected behavior?

No failure.

### What do you see instead?

```
bun run dev
$ astro dev
11:29:46 PM [vite] Error when evaluating SSR module /node_modules/@astrojs/starlight/utils/i18n.ts:
|- AstroUserError: Failed to get locale informations for the 'en' locale.
    at new AstroUserError (/home/xxx/docs/node_modules/astro/dist/core/errors/errors.js:96:9)
    at getLocaleInfo (:99:47)
    at <anonymous> (:5:48)
    at processTicksAndRejections (:12:39)

11:29:46 PM [vite] Error when evaluating SSR module /node_modules/@astrojs/starlight/integrations/shared/localeToLang.ts: failed to import "/node_modules/@astrojs/starlight/u
tils/i18n.ts"
|- AstroUserError: Failed to get locale informations for the 'en' locale.
    at new AstroUserError (/home/xxx/docs/node_modules/astro/dist/core/errors/errors.js:96:9)
    at getLocaleInfo (:99:47)
    at <anonymous> (:5:48)
    at processTicksAndRejections (:12:39)

11:29:46 PM [vite] Error when evaluating SSR module /node_modules/@astrojs/starlight/integrations/expressive-code/translations.ts: failed to import "/node_modules/@astrojs/st
arlight/integrations/shared/localeToLang.ts"
|- AstroUserError: Failed to get locale informations for the 'en' locale.
    at new AstroUserError (/home/xxx/docs/node_modules/astro/dist/core/errors/errors.js:96:9)
    at getLocaleInfo (:99:47)
    at <anonymous> (:5:48)
    at processTicksAndRejections (:12:39)

11:29:46 PM [vite] Error when evaluating SSR module /node_modules/@astrojs/starlight/integrations/expressive-code/index.ts: failed to import "/node_modules/@astrojs/starlight
/integrations/expressive-code/translations.ts"
|- AstroUserError: Failed to get locale informations for the 'en' locale.
    at new AstroUserError (/home/xxx/docs/node_modules/astro/dist/core/errors/errors.js:96:9)
    at getLocaleInfo (:99:47)
    at <anonymous> (:5:48)
    at processTicksAndRejections (:12:39)

11:29:46 PM [vite] Error when evaluating SSR module /node_modules/@astrojs/starlight/index.ts: failed to import "/node_modules/@astrojs/starlight/integrations/expressive-code
/index.ts"
|- AstroUserError: Failed to get locale informations for the 'en' locale.
    at new AstroUserError (/home/xxx/docs/node_modules/astro/dist/core/errors/errors.js:96:9)
    at getLocaleInfo (:99:47)
    at <anonymous> (:5:48)
    at processTicksAndRejections (:12:39)

11:29:46 PM [vite] Error when evaluating SSR module /home/xxx/docs/astro.config.mjs: failed to import "/node_modules/@astrojs/starlight/index.ts"
|- AstroUserError: Failed to get locale informations for the 'en' locale.
    at new AstroUserError (/home/xxx/docs/node_modules/astro/dist/core/errors/errors.js:96:9)
    at getLocaleInfo (:99:47)
    at <anonymous> (:5:48)
    at processTicksAndRejections (:12:39)

[astro] Unable to load your Astro config

[AstroUserError] Failed to get locale informations for the 'en' locale.
  Hint:
    Make sure to provide a valid BCP-47 tags (e.g. en, ar, or zh-CN).
  Stack trace:
    at new AstroUserError (/home/xxx/docs/node_modules/astro/dist/core/errors/errors.js:96:9)
    at <anonymous> (:5:48)
error: script "dev" exited with code 1
```

### Additional information

I assume it's https://github.com/withastro/starlight/commit/ee0cd38a1fae31717fe820e779baeabe693cd67a that broke things. According to the Starlight folks this is an issue in Bun:

- https://github.com/withastro/starlight/issues/1961
- https://github.com/withastro/starlight/issues/1986

**Comment by delucis** [comment]
This should be fixed in `@astrojs/starlight` v0.24.1 — we were unintentionally using a V8-specific internationalisation API and have now addressed that.

Thanks again for reporting.
