### ISSUE TITLE
Creating a new database with bun:sqlite broken when running in wiptest

### ISSUE THREAD

**Issue by larry4000** [oven-sh/bun#1173]
### Version

0.1.10

### Platform

Darwin Larrys-MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?

Try to new a sqlite database inside of a test file, and then run the wiptest runner. Here is an example file index_test.ts:
```
import Database from 'bun:sqlite';
import {test, expect } from 'bun:test';

test('sqlite is broken', () => {
  const db = new Database("test.sqlite");
  expect(1).toBe(1);
});
```
Running this gives:
```
$ bun wiptest
index_test.ts:
1 | import Database from 'bun:sqlite';
2 | import {test, expect } from 'bun:test';
3 | 
4 | test('sqlite is broken', () => {
5 |   const db = new Database("test.sqlite");
                 ^
TypeError: Module is not a constructor (evaluating 'new Database("test.sqlite")')
      at /.../src/index_test.ts:5:13
✗ sqlite is broken


 0 pass
 1 fail
 Ran 1 tests across 1 files [6.00ms]
```

### How often does it reproduce? Is there a required condition?

Always reproduces when run with `wiptest`. `bun:sqlite` working as expected as part of a normal Bun app.

### What is the expected behavior?

Database object should construct successfully.

### What do you see instead?

```
$ bun wiptest
index_test.ts:
1 | import Database from 'bun:sqlite';
2 | import {test, expect } from 'bun:test';
3 | 
4 | test('sqlite is broken', () => {
5 |   const db = new Database("test.sqlite");
                 ^
TypeError: Module is not a constructor (evaluating 'new Database("test.sqlite")')
      at /.../src/index_test.ts:5:13
✗ sqlite is broken


 0 pass
 1 fail
 Ran 1 tests across 1 files [6.00ms]
```

**Comment by larry4000** [comment]
Apologies, I was being a fool!
Should have been
`import {Database} from 'bun:sqlite';`
