### ISSUE TITLE
Huge date problem, makes tests fails whereas in jest they work properly

### ISSUE THREAD

**Issue by Theoreumont** [oven-sh/bun#11782]
### What version of Bun is running?

1.1.12+43f0913c3

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

File 1

```ts
import { calendar_v3 } from "googleapis";
import { format, toZonedTime } from "date-fns-tz";
import { parseISO } from "date-fns";

type Calendar = {
  start: string;
  end: string;
}[];

// Function to extract time zone from ISO string
const getTimeZoneFromISO = (isoString: string): string => {
  const regex = /([+-]\d{2}:\d{2}|Z)$/;
  const match = isoString.match(regex);

  if (match) {
    return match[0] === "Z" ? "UTC" : match[0];
  }

  // Handle case where there is no time zone info in the string
  return "UTC"; // Default to UTC if no time zone is specified
};

// Function to convert ISO string to specified time zone
const convertToTimeZone = (
  isoString: string,
  targetTimeZone: string,
): string => {
  const date = parseISO(isoString);
  const zonedDate = toZonedTime(date, targetTimeZone);
  const formattedDate = format(zonedDate, "yyyy-MM-dd'T'HH:mm:ssXXX", {
    timeZone: targetTimeZone,
  });

  return formattedDate;
};

export const getFreeTimes = ({
  events,
  startDate,
  endDate,
  userDate,
}: {
  events: calendar_v3.Schema$Event[][];
  startDate: string;
  endDate: string;
  userDate: string;
}) => {
  // Remove workingLocation events from the list
  const eventsCleaned = events.map((events) => {
    return events
      .filter((event) => {
        // Exclude events that are working locations
        if (event.eventType === "workingLocation") return false;

        // Check for events that has Recurrency with UNTIL date, and remove them if the UNTIL date is before now
        if (event.recurrence) {
          const untilDate = event.recurrence[0]
            .split(";")
            .find((rec) => rec.includes("UNTIL"));
          if (untilDate) {
            // Looks like : 20230619T215959Z
            const dateFormattedToISO = untilDate
              .split("=")[1]
              .replace(
                /(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})Z/,
                "$1-$2-$3T$4:$5:$6Z",
              );
            console.log("UNTIL date formatted to ISO:", dateFormattedToISO);
            const untilDateValue = new Date(dateFormattedToISO);
            console.log("UNTIL date value:", untilDateValue);
            if (untilDateValue < new Date(startDate)) return false;
          }
        }

        return true;
      })
      .map((event) => {
        // Map to the good day if the event is recurring
        if (event.recurrence) {
          const recurrenceRule = event.recurrence[0];
          const freq = recurrenceRule.match(
            /FREQ=(DAILY|WEEKLY|MONTHLY|YEARLY)/,
          );
          if (freq && freq[1]) {
            const eventStartDate = new Date(event.start?.dateTime!);
            const eventEndDate = new Date(event.end?.dateTime!);
            switch (freq[1]) {
              case "DAILY":
              case "WEEKLY":
              case "MONTHLY":
              case "YEARLY":
                eventStartDate.setFullYear(new Date(startDate).getFullYear());
                eventStartDate.setMonth(new Date(startDate).getMonth());
                eventStartDate.setDate(new Date(startDate).getDate());
                eventEndDate.setFullYear(new Date(startDate).getFullYear());
                eventEndDate.setMonth(new Date(startDate).getMonth());
                eventEndDate.setDate(new Date(startDate).getDate());
                event!.start!.dateTime = eventStartDate.toISOString();
                event.end!.dateTime = eventEndDate.toISOString();
                break;
              default:
                break;
            }
          }
        }
        // Put everthing in the same timezone
        const eventStart = convertToTimeZone(
          event.start?.dateTime!,
          getTimeZoneFromISO(userDate),
        );
        const eventEnd = convertToTimeZone(
          event.end?.dateTime!,
          getTimeZoneFromISO(userDate),
        );
        event.start!.dateTime = eventStart;
        event.end!.dateTime = eventEnd;
        return event;
      })
      .sort((eventA, eventB) => {
        const startA = new Date(eventA.start?.dateTime!);
        const startB = new Date(eventB.start?.dateTime!);
        return (
          startA.getHours() * 60 +
          startA.getMinutes() -
          (startB.getHours() * 60 + startB.getMinutes())
        );
      });
  });

  // console.log("events cleaned", eventsCleaned);

  // Get free time based of start of day until end of day based on the events

  const freeTime = eventsCleaned.map((events) => {
    const busy = events.map((event) => {
      const start = event.start?.dateTime!;
      const end = event.end?.dateTime!;
      return { start, end };
    });

    const available = busy.reduce(
      (acc, slot, index) => {
        if (index === 0) {
          return [
            {
              start: startDate,
              end: slot.start,
            },
          ];
        }

        return [
          ...acc,
          {
            start: busy[index - 1].end,
            end: slot.start,
          },
        ];
      },
      [] as { start: string; end: string }[],
    );

    // Add the last slot
    if (busy.length) {
      available.push({
        start: busy[busy.length - 1].end,
        end: endDate,
      });
    }

    // Filter the available time to remove the one that have a start time after the end time
    const availableFiltered = available.filter((slot) => {
      return new Date(slot.start) < new Date(slot.end);
    });

    return availableFiltered;
  });

  return freeTime;
};
```

File 2

```ts
import { getFreeTimes } from "../free-time";

describe("Calculate free time", () => {
  it("should calculate free time", () => {
    const events = [
      [
        {
          start: {
            date: "2023-01-04",
          },
          end: {
            date: "2023-01-05",
          },
          recurrence: ["RRULE:FREQ=WEEKLY;BYDAY=WE"],
          transparency: "transparent",
          iCalUID: "8o8elu75tthjmhvkbo6cak3in8@google.com",
          eventType: "workingLocation",
        },
        {
          etag: '"3413157673754000"',
          start: {
            dateTime: "2023-11-06T16:55:00+01:00",
            timeZone: "Europe/Paris",
          },
          end: {
            dateTime: "2023-11-06T17:00:00+01:00",
            timeZone: "Europe/Paris",
          },
          recurrence: ["RRULE:FREQ=WEEKLY;WKST=SU;BYDAY=MO,TH,TU,WE"],
          iCalUID: "jhmg15gpdnpdsfrte5shq325cj@google.com",
          sequence: 2,
          eventType: "focusTime",
        },
        {
          id: "35rhgefn1jpkhunm1cq760ph13",
          start: {
            dateTime: "2024-06-12T09:00:00+02:00",
            timeZone: "Europe/Paris",
          },
          end: {
            dateTime: "2024-06-12T12:30:00+02:00",
            timeZone: "Europe/Paris",
          },
          iCalUID: "35rhgefn1jpkhunm1cq760ph13@google.com",
          eventType: "default",
        },
        {
          id: "6a62ik3sm7bqi3a54o682n1vts",
          start: {
            dateTime: "2024-06-12T14:00:00+02:00",
            timeZone: "Europe/Paris",
          },
          end: {
            dateTime: "2024-06-12T14:30:00+02:00",
            timeZone: "Europe/Paris",
          },
          iCalUID: "6a62ik3sm7bqi3a54o682n1vts@google.com",
          eventType: "default",
        },
      ],
      [
        {
          id: "3rlttdets2qpr2djmo0fi3pufo",
          start: {
            dateTime: "2023-06-12T17:00:00+02:00",
            timeZone: "Europe/Paris",
          },
          end: {
            dateTime: "2023-06-12T17:15:00+02:00",
            timeZone: "Europe/Paris",
          },
          recurrence: ["RRULE:FREQ=WEEKLY;BYDAY=FR,MO,TH,TU,WE"],
          iCalUID: "3rlttdets2qpr2djmo0fi3pufo@google.com",
          eventType: "default",
        },
        {
          id: "shdjqv26npnkk1q4g30stfpnpo",
          start: {
            date: "2024-01-31",
          },
          end: {
            date: "2024-02-01",
          },
          recurrence: ["RRULE:FREQ=WEEKLY;BYDAY=WE"],
          iCalUID: "shdjqv26npnkk1q4g30stfpnpo@google.com",
          eventType: "workingLocation",
        },
        {
          id: "54qqss2gslrqu0cgps7kmhsv3l",
          start: {
            dateTime: "2024-06-12T12:00:00+02:00",
            timeZone: "Europe/Lisbon",
          },
          end: {
            dateTime: "2024-06-12T12:30:00+02:00",
            timeZone: "Europe/Lisbon",
          },
          iCalUID: "54qqss2gslrqu0cgps7kmhsv3l@google.com",
          eventType: "default",
        },
        {
          id: "35rhgefn1jpkhunm1cq760ph13",
          start: {
            dateTime: "2024-06-12T09:00:00+02:00",
            timeZone: "Europe/Paris",
          },
          end: {
            dateTime: "2024-06-12T12:30:00+02:00",
            timeZone: "Europe/Paris",
          },
          iCalUID: "35rhgefn1jpkhunm1cq760ph13@google.com",
          eventType: "default",
        },
        {
          id: "4q0i945k3mfrdk7tq1u0aiomif",
          start: {
            dateTime: "2024-06-12T14:00:00+02:00",
            timeZone: "Europe/Paris",
          },
          end: {
            dateTime: "2024-06-12T14:30:00+02:00",
            timeZone: "Europe/Paris",
          },
          iCalUID: "4q0i945k3mfrdk7tq1u0aiomif@google.com",
          eventType: "default",
        },
      ],
    ];

    const userDate = "2024-06-10T11:18:00+02:00";

    const startDate = "2024-06-12T00:00:00+02:00";
    const endDate = "2024-06-13T00:00:00+02:00";

    const freeTime = getFreeTimes({ events, endDate, startDate, userDate });

    const expected = [
      [
        {
          start: "2024-06-12T00:00:00+02:00",
          end: "2024-06-12T09:00:00+02:00",
        },
        {
          start: "2024-06-12T12:30:00+02:00",
          end: "2024-06-12T14:00:00+02:00",
        },
        {
          start: "2024-06-12T14:30:00+02:00",
          end: "2024-06-12T16:55:00+02:00",
        },
        {
          start: "2024-06-12T17:00:00+02:00",
          end: "2024-06-13T00:00:00+02:00",
        },
      ],
      [
        {
          start: "2024-06-12T00:00:00+02:00",
          end: "2024-06-12T09:00:00+02:00",
        },
        {
          start: "2024-06-12T12:30:00+02:00",
          end: "2024-06-12T14:00:00+02:00",
        },
        {
          start: "2024-06-12T14:30:00+02:00",
          end: "2024-06-12T17:00:00+02:00",
        },
        {
          start: "2024-06-12T17:15:00+02:00",
          end: "2024-06-13T00:00:00+02:00",
        },
      ],
    ];

    expect(freeTime).toEqual(expected);
  });

})
```

### What is the expected behavior?

With Jest, it works, every date is for the 2024-06-12, the comparison works properly.

### What do you see instead?

With Bun, the days are delayed by one sometimes, I don't understand why.
It appears that the comparison makes it output 2024-06-11 which is not even possible.
![image](https://github.com/oven-sh/bun/assets/66231672/469317dc-00a2-4d21-9e57-526d32f12902)

**Comment by dylan-conway** [comment]
Hmm, I appear to get the same results for bun and jest.
bun:
```
334 |     expect(freeTime).toEqual(expected);
                           ^
error: expect(received).toEqual(expected)

  [
    [
      {
        end: "2024-06-12T09:00:00+02:00",
        start: "2024-06-12T00:00:00+02:00",
      },
      {
        end: "2024-06-12T14:00:00+02:00",
        start: "2024-06-12T12:30:00+02:00",
      },
      {
-       end: "2024-06-12T16:55:00+02:00",
-       start: "2024-06-12T14:30:00+02:00",
-     },
-     {
        end: "2024-06-13T00:00:00+02:00",
+       start: "2024-06-11T18:00:00+02:00",
-       start: "2024-06-12T17:00:00+02:00",
      }
    ],
    [
      {
        end: "2024-06-12T09:00:00+02:00",
        start: "2024-06-12T00:00:00+02:00",
      },
      {
        end: "2024-06-12T14:00:00+02:00",
        start: "2024-06-12T12:30:00+02:00",
      },
      {
-       end: "2024-06-12T17:00:00+02:00",
-       start: "2024-06-12T14:30:00+02:00",
-     },
-     {
        end: "2024-06-13T00:00:00+02:00",
+       start: "2024-06-11T17:15:00+02:00",
-       start: "2024-06-12T17:15:00+02:00",
      }
    ]
  ]

- Expected  - 10
+ Received  + 2

      at /Users/dylan/code/bun/jest-test/j.test.js:334:22
✗ Calculate free time > should calculate free time [13.56ms]
```
jest:
```
● Calculate free time › should calculate free time

    expect(received).toEqual(expected) // deep equality

    - Expected  - 10
    + Received  +  2

    @@ -7,32 +7,24 @@
          Object {
            "end": "2024-06-12T14:00:00+02:00",
            "start": "2024-06-12T12:30:00+02:00",
          },
          Object {
    -       "end": "2024-06-12T16:55:00+02:00",
    -       "start": "2024-06-12T14:30:00+02:00",
    -     },
    -     Object {
            "end": "2024-06-13T00:00:00+02:00",
    -       "start": "2024-06-12T17:00:00+02:00",
    +       "start": "2024-06-11T17:00:00+02:00",
          },
        ],
        Array [
          Object {
            "end": "2024-06-12T09:00:00+02:00",
            "start": "2024-06-12T00:00:00+02:00",
          },
          Object {
            "end": "2024-06-12T14:00:00+02:00",
            "start": "2024-06-12T12:30:00+02:00",
    -     },
    -     Object {
    -       "end": "2024-06-12T17:00:00+02:00",
    -       "start": "2024-06-12T14:30:00+02:00",
          },
          Object {
            "end": "2024-06-13T00:00:00+02:00",
    -       "start": "2024-06-12T17:15:00+02:00",
    +       "start": "2024-06-11T17:15:00+02:00",
          },
        ],
      ]

      332 |     console.log(freeTime[0].length, expected[0].length);
      333 |
    > 334 |     expect(freeTime).toEqual(expected);
          |                      ^
      335 |   });
      336 | });
      337 |

      at Object.toEqual (j.test.js:334:22)
```
It seems the arrays do not have equal length. The array at index 0 in `expected` has length 4, but `freeTimes` as index 0 has length 3. What version of jest are you using?

**Comment by Theoreumont** [comment]
I don't have any error related to array length.
I'm currently on the last version of Jest, which is to this day, the 29.7.0

I pasted my code in another project to isolate the problem : https://github.com/Theoreumont/bun-bug-report
