### ISSUE TITLE
fs.openSync() fails on Windows with bun, but works with nodejs

### ISSUE THREAD

**Issue by DanTup** [oven-sh/bun#11873]
### What version of Bun is running?

1.1.13+bd6a60512

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Create a file that uses the npm `tmp` package and the following code:

```js
import tmp from "tmp";

console.log(tmp.fileSync().name);
```

Run the file under both nodejs and bun. NodeJS works, but bun throws.

### What is the expected behavior?

Bun should not throw.

### What do you see instead?

I see the following error:

```
C:\Users\danny\AppData\Local\Temp\tmp-10900-Rw7jt3j7ND5y
PS C:\Dev\CodeCrafters\course-sdk> bun .\danny.js
Calling fs.openSync("C:\Users\danny\AppData\Local\Temp\tmp-16428-duMHLM847XLq", 1282, 384)
167 |     opts = args[0];
168 |
169 |   const discardOrDetachDescriptor = opts.discardDescriptor || opts.detachDescriptor;
170 |   const name = tmpNameSync(opts);
171 |   console.log(`Calling fs.openSync("${name}", ${CREATE_FLAGS}, ${opts.mode || FILE_MODE})`);
172 |   var fd = fs.openSync(name, CREATE_FLAGS, opts.mode || FILE_MODE);
                    ^
ENOENT: No such file or directory
   errno: -2
 syscall: "open"
   path: "C:\Users\danny\AppData\Local\Temp\tmp-16428-duMHLM847XLq"

      at fileSync (C:\Dev\CodeCrafters\course-sdk\node_modules\tmp\lib\tmp.js:172:15)
      at C:\Dev\CodeCrafters\course-sdk\danny.js:3:17

Bun v1.1.13 (Windows x64)
```

### Additional information

I'm not certain this isn't a `tmp` issue, because I don't completely understand all the values in `CREATE_FLAGS` in their call. Passing just `"w"` seems to work fine.

However, since it works in nodejs and my assumption is that bun aims to be compatible, I thought I would start here. I'm happy to re-file this against `tmp` if someone can give a detailed description of why the issue is there (since otherwise they may just consider it a bun issue since it works in Node).

Thanks!

(related issue: https://github.com/codecrafters-io/course-sdk/issues/19)

**Comment by KeithBrown39423** [comment]
This issue is still present in 1.2.10
