### ISSUE TITLE
bun build --target=bun breaks Bun.password.verify

### ISSUE THREAD

**Issue by einar-hjortdal** [oven-sh/bun#12116]
### What version of Bun is running?

`1.1.16+bf7b327f6`

### What platform is your computer?

`Linux 5.14.0-427.18.1.el9_4.x86_64 x86_64 x86_64`

### What steps can reproduce the bug?

`Bun.password.verify` works correctly in my unit tests, but once the project it built with `bun build --target=bun` it throws this:
```
679 | }), require_hash = __commonJS({
680 |   "node_modules/sha.js/hash.js"(exports2, module) {
681 |     var Buffer2 = require_safe_buffer().Buffer;
682 |     function Hash(blockSize, finalSize) {
683 |       this._block = Buffer2.alloc(blockSize), this._finalSize = finalSize, this._blockSize = blockSize, this._len = 0;
684 |     Hash.prototype = {}, Hash.prototype.update = function(data, enc) {
                                                  ^
TypeError: undefined is not an object
      at node:crypto:684:58
      at node:crypto:1364:60
      at node:crypto:1153:89
      at createSignature (/home/coachonko/Documents/watercolors/packages/admin/build/server/index.js:19376:45)
      at createCookieValue (/home/coachonko/Documents/watercolors/packages/admin/build/server/index.js:19383:36)
      at createCookie (/home/coachonko/Documents/watercolors/packages/admin/build/server/index.js:19389:36)
      at /home/coachonko/Documents/watercolors/packages/admin/build/server/index.js:19546:32
```

**Comment by Coachonko** [comment]
The problem was elsewhere. My apologies
