### ISSUE TITLE
Failed to start server. Is port in use?

### ISSUE THREAD

**Issue by maxime-aubry** [oven-sh/bun#12127]
### What version of Bun is running?

1.1.16

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

I Have a NestJS project.

Here is the command  to run project into package.json file :

`"start:dev": "bun --watch ./apps/api/src/main.ts"`

When i run this command, "bun start:dev api", I get this error :

```jsonc
[Nest] 23548  - 25/06/2024 00:11:05   ERROR [NestApplication] EADDRINUSE: Failed to start server. Is port 5000 in use? +7ms
175 |             this.httpServer.once('error', errorHandler);
176 |             const isCallbackInOriginalArgs = (0, shared_utils_1.isFunction)(args[args.length - 1]);
177 |             const listenFnArgs = isCallbackInOriginalArgs
178 |                 ? args.slice(0, args.length - 1)
179 |                 : args;
180 |             this.httpAdapter.listen(port, ...listenFnArgs, (...originalCallbackArgs) => {
                                   ^
EADDRINUSE: Failed to start server. Is port 5000 in use?
 syscall: "listen"

      at node:http:433:35
      at F:\Projets\shadow-hunters-web-api\node_modules\@nestjs\core\nest-application.js:180:30
      at new Promise (:1:11)
      at F:\Projets\shadow-hunters-web-api\node_modules\@nestjs\core\nest-application.js:170:16
```

Even if i change port number, i always get this error.

**Comment by j-mcgregor** [comment]
if you're using `Bun.serve` then you have to specify the hostname next to the port number to set the port

**Comment by RiskyMH** [comment]
@BennyAlex I believe your issue is #15425 and should also be fixed in canary:
```ts
bun upgrade --canary
```

**Comment by BennyAlex** [comment]
> [@BennyAlex](https://github.com/BennyAlex) I believe your issue is [#15425](https://github.com/oven-sh/bun/issues/15425) and should also be fixed in canary:
> 
> bun upgrade --canary

no its the same as the issue here.

**Comment by HMBond** [comment]
I had the same error. It could be that instead of the port, the hostname is not available.

I fixed it by changing the hostname, for example:
```
Bun.serve({
  hostname: 'localhost',
  port: 5000
})
```
