### ISSUE TITLE
Error: spawn bun ENOENT

### ISSUE THREAD

**Issue by MrOxMasTer** [oven-sh/bun#12177]
### What version of Bun is running?

1.1.17+bb66bba1b

### What platform is your computer?

windows

### What steps can reproduce the bug?

bun create next-app

### What is the expected behavior?

No mistakes

### What do you see instead?

bun create next-app                                        
√ What is your project named? ... my-app
√ Would you like to use TypeScript? ... No / Yes
√ Would you like to use ESLint? ... No / Yes
√ Would you like to use Tailwind CSS? ... No / Yes
√ Would you like to use `src/` directory? ... No / Yes
√ Would you like to use App Router? (recommended) ... No / Yes        
√ Would you like to customize the default import alias (@/*)? ... No / Yes
Creating a new Next.js app in ...

Using bun.

Initializing project with template: app-tw 

Installing dependencies:
- react
- react-dom
- next

Installing devDependencies:
- typescript
- @types/node
- @types/react
- @types/react-dom
- postcss
- tailwindcss
- eslint
- eslint-config-next

node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: spawn bun ENOENT
    at notFoundError (C:\Users\CD86~1\AppData\Local\Temp\bunx-596791048-create-next-app@latest\node_modules\create-next-app\dist\index.js:8:77149)
    at verifyENOENT (C:\Users\CD86~1\AppData\Local\Temp\bunx-596791048-create-next-app@latest\node_modules\create-next-app\dist\index.js:8:77528)
    at t.emit (C:\Users\CD86~1\AppData\Local\Temp\bunx-596791048-create-next-app@latest\node_modules\create-next-app\dist\index.js:8:77383) 
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
Emitted 'error' event on ChildProcess instance at:
    at t.emit (C:\Users\CD86~1\AppData\Local\Temp\bunx-596791048-create-next-app@latest\node_modules\create-next-app\dist\index.js:8:77424) 
    at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn bun',
  path: 'bun',
  spawnargs: [ 'install' ]
}

Node.js v20.15.0

**Comment by museadam** [comment]
Running `bun create next-app` on my machine I cannot reproduce the bug. You could try uninstalling and reinstalling bun.

**Comment by MrOxMasTer** [comment]
> When running `bun create next-app` on my machine I could not reproduce the bug. You could try uninstalling and reinstalling bun.

I deleted it using this command and installed it using powershell too
```powershell -c ~\.bun\uninstall.ps1```

The result is the same:
![image](https://github.com/oven-sh/bun/assets/59291123/644c97de-918a-4dfb-824a-ca520ac4771f)

The fact is that it sort of installs, but at the same time this error occurs. The bonus is the strange Appdata folder, which (it seems to me) should not appear here.

**Comment by MrOxMasTer** [comment]
I do not know if the Cyrillic alphabet plays a role with my windows User, but it does. Maybe the information will help

**Comment by RiskyMH** [comment]
We've invested a ton of time into making Bun more reliable over the last year. I'm having a really hard time reproducing this. If you're still running into this issue, please let me know and I'll re-open this

**Comment by congweiH** [comment]
I meet this issue

![Image](https://github.com/user-attachments/assets/8427b6bb-1eef-4148-954b-8c94f5042998)
