### ISSUE TITLE
bun:test with `--bail` and `afterAll` hook

### ISSUE THREAD

**Issue by bkniffler** [oven-sh/bun#12250]
### What version of Bun is running?

1.1.10+5102a9443

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

```js
import { afterAll, beforeAll, describe, expect, it } from 'bun:test';

describe('test', () => {
  beforeAll(async () => {
    console.log('Before');
  });

  afterAll(async () => {
    console.log('After');
  });

  it('should work', async () => {
    expect(true).toBe(false);
  });
  it('should work2', async () => {
    expect(true).toBe(true);
  });
});
```

```
bun test --bail
```

Output:
```
x.spec.ts:
Before
 8 |   afterAll(async () => {
 9 |     console.log('After');
10 |   });
11 | 
12 |   it('should work', async () => {
13 |     expect(true).toBe(false);
         ^
error: expect(received).toBe(expected)

Expected: false
Received: true

      at /Users/.../x.spec.ts:13:5
      at /Users/.../x.spec.ts:12:21
✗ test > should work [0.21ms]
Ran 1 tests across 1 files. [7.00ms]
Bailed out after 1 failure
```

### What is the expected behavior?

it outputs `After`

### What do you see instead?

it does not output `After`

**Comment by lafkpages** [comment]
This also applies to `afterEach`, confirmed on Bun v1.3.9.
