### ISSUE TITLE
Bun fails to build a Astro Starlight project with Docker

### ISSUE THREAD

**Issue by eveeifyeve** [oven-sh/bun#12366]
### What version of Bun is running?

Latest as it's a docker image

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

**Requires Bun & Docker**

1. New Starlight project `bun create astro --template starlight`
2. Create Docker Image file:
```docker
FROM oven/bun


COPY . /app
WORKDIR /app


RUN bun install
RUN bun astro telemetry disable

RUN bun run build

EXPOSE 4321

CMD [ "bun run preview" ]
```

3. `docker build .`

### What is the expected behavior?

It should just build into a docker image.

### What do you see instead?
```
#10 [5/5] RUN bun run build
#10 0.285 $ astro build
#10 0.722 ▶ Astro collects anonymous usage data.
#10 0.722   This information helps us improve Astro.
#10 0.722   Run "astro telemetry disable" to opt-out.
#10 0.722   https://astro.build/telemetry
#10 0.722 
#10 1.922 msg.match is not a function. (In 'msg.match(/ec\.config\.mjs.*(imported from|resolved id)/)', 'msg.match' is undefined)
#10 1.922   Stack trace:
#10 1.922     at <anonymous> (/app/node_modules/astro-expressive-code/dist/index.js:39:17)
#10 1.932 error: script "build" exited with code 1
#10 ERROR: process "/bin/sh -c bun run build" did not complete successfully: exit code: 1
------
 > [5/5] RUN bun run build:
0.285 $ astro build
0.722 ▶ Astro collects anonymous usage data.
0.722   This information helps us improve Astro.
0.722   Run "astro telemetry disable" to opt-out.
0.722   https://astro.build/telemetry
0.722 
1.922 msg.match is not a function. (In 'msg.match(/ec\.config\.mjs.*(imported from|resolved id)/)', 'msg.match' is undefined)
1.922   Stack trace:
1.922     at <anonymous> (/app/node_modules/astro-expressive-code/dist/index.js:39:17)
1.932 error: script "build" exited with code 1
------
dockerfile:10
--------------------
   8 |     RUN bun install
   9 |     
  10 | >>> RUN bun run build
  11 |     
  12 |     EXPOSE 4321
--------------------
ERROR: failed to solve: process "/bin/sh -c bun run build" did not complete successfully: exit code: 1
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c bun run build" did not complete successfully: exit code: 1
```

### Additional information

I have tried it with `pnpm` and it works normaly. Bun is the issue.

**Comment by Eveeifyeve** [comment]
It seems `astro-expressive-code` is calling:
```
async function loadEcConfigFile(projectRootUrl) {
  const pathsToTry = [
    // This path works in most scenarios, but not when the integration is processed by Vite
    // due to a Vite bug affecting import URLs using the "file:" protocol
    new URL(`./ec.config.mjs?t=${Date.now()}`, projectRootUrl).href
  ];
  if (import.meta.env?.BASE_URL?.length) {
    pathsToTry.push(`/ec.config.mjs?t=${Date.now()}`);
  }
  for (const path of pathsToTry) {
    try {
      const module = await import(
        /* @vite-ignore */
        path
      );
      if (!module.default) {
        throw new Error(`Missing or invalid default export. Please export your Expressive Code config object as the default export.`);
      }
      return module.default;
    } catch (error) {
      const msg = error instanceof Error ? error.message : error;
      const code = error.code;
      if (code === "ERR_MODULE_NOT_FOUND" || code === "ERR_LOAD_URL") {
        if (msg.match(/ec\.config\.mjs.*(imported from|resolved id)/))
          continue;
      }
      throw new Error(
        `Your project includes an Expressive Code config file ("ec.config.mjs")
				that could not be loaded due to ${code ? `the error ${code}` : "the following error"}: ${msg}`.replace(/\s+/g, " "),
        error instanceof Error ? { cause: error } : void 0
      );
    }
  }
  return {};
}
```

**Comment by Eveeifyeve** [comment]
@paperdave @Jarred-Sumner

**Comment by Eveeifyeve** [comment]
Look no one has responded, I don't think this is worth the hassle of waiting, if you respond re-open this issue, I am done waiting for this issue to be solved.
