### ISSUE TITLE
ReferenceError: Can't find variable: TextDecoderStream

### ISSUE THREAD

**Issue by SalamanderXing** [oven-sh/bun#12459]
### What version of Bun is running?

1.1.18

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

Run the following code I got from the official [vercel ai docs](https://sdk.vercel.ai/docs/reference/ai-sdk-core/stream-object).

```ts
import { openai } from '@ai-sdk/openai';
import { streamObject } from 'ai';
import { z } from 'zod';

const { partialObjectStream } = await streamObject({
  model: openai('gpt-4-turbo'),
  schema: z.object({
    recipe: z.object({
      name: z.string(),
      ingredients: z.array(z.string()),
      steps: z.array(z.string()),
    }),
  }),
  prompt: 'Generate a lasagna recipe.',
});

for await (const partialObject of partialObjectStream) {
  console.clear();
  console.log(partialObject);
}
```

### What is the expected behavior?

No errors raised and object streamed to the console. Works with node v22.4.1.

### What do you see instead?

```
13 |     statusCode === 429 || // too many requests
14 |     statusCode >= 500),
15 |     // server error
16 |     data
17 |   }) {
18 |     super(message);
         ^
AI_APICallError: Failed to process successful response
 url: "https://api.fireworks.ai/inference/v1/chat/completions"

      at new APICallError (/Users/salamanderxing/Documents/gcp-chatbot/main_ts/node_modules/@ai-sdk/provider/dist/index.mjs:18:5)
      at /Users/salamanderxing/Documents/gcp-chatbot/main_ts/node_modules/@ai-sdk/provider-utils/dist/index.mjs:353:13

444 |   if (response.body == null) {
445 |     throw new EmptyResponseBodyError({});
446 |   }
447 |   return {
448 |     responseHeaders,
449 |     value: response.body.pipeThrough(new TextDecoderStream()).pipeThrough(new EventSourceParserStream()).pipeThrough(
                                                                  ^
ReferenceError: Can't find variable: TextDecoderStream
      at /Users/salamanderxing/Documents/gcp-chatbot/main_ts/node_modules/@ai-sdk/provider-utils/dist/index.mjs:449:61
      at /Users/salamanderxing/Documents/gcp-chatbot/main_ts/node_modules/@ai-sdk/provider-utils/dist/index.mjs:442:57
      at /Users/salamanderxing/Documents/gcp-chatbot/main_ts/node_modules/@ai-sdk/provider-utils/dist/index.mjs:342:20

Bun v1.1.18 (macOS arm64)
```

**Comment by ghiscoding** [comment]
https://bun.sh/docs/runtime/nodejs-apis#textdecoderstream

![image](https://github.com/oven-sh/bun/assets/643976/3ab6caf0-b68c-4e69-a72a-c7701b8686fd)

There isn't much Stream supported yet

**Comment by SalamanderXing** [comment]
I see. Thank you hope this gets implemented soon.
