### ISSUE TITLE
Compile Issue w/ @apollo/client

### ISSUE THREAD

**Issue by ksylvest** [oven-sh/bun#12518]
### What version of Bun is running?

1.1.18

### What platform is your computer?

x86

### What steps can reproduce the bug?

Given the following simple project:

**package.json**

```json
{
  "dependencies": {
    "@apollo/client": "^3.10.8",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "typescript": "^5.5.3"
  },
  "devDependencies": {
    "@types/bun": "^1.1.6"
  }
}
```

**demo.tsx**

```tsx
import { renderToString } from "react-dom/server";
import { ApolloClient, ApolloProvider, InMemoryCache } from "@apollo/client";

const client = new ApolloClient({ cache: new InMemoryCache() });

const App = () => <ApolloProvider client={client}>🚀</ApolloProvider>;

Bun.write(Bun.stdout, renderToString(<App />));
```

```bash
bun demo.tsx # 🚀
```

```bash
bun build demo.tsx --outfile demo.jsx
bun demo.jsx
```

```
22302 | Object.assign(exports_rehackt, import_react);
22303 | 
22304 | // node_modules/@apollo/client/react/context/ApolloContext.js
22305 | function getApolloContext() {
22306 |   invariant2("createContext" in exports_rehackt, 45);
22307 |   var context5 = undefined[contextKey];
                         ^
TypeError: undefined is not an object (evaluating '(void 0)[contextKey]')
      at getApolloContext (/Users/kevin/Desktop/bug/demo.jsx:22307:18)
      at ApolloProvider (/Users/kevin/Desktop/bug/demo.jsx:22324:24)
      at renderWithHooks (/Users/kevin/Desktop/bug/demo.jsx:5957:22)
      at renderIndeterminateComponent (/Users/kevin/Desktop/bug/demo.jsx:6015:21)
      at renderElement (/Users/kevin/Desktop/bug/demo.jsx:6178:13)
      at renderNodeDestructiveImpl (/Users/kevin/Desktop/bug/demo.jsx:6282:15)
      at renderNodeDestructive (/Users/kevin/Desktop/bug/demo.jsx:6262:20)
      at renderIndeterminateComponent (/Users/kevin/Desktop/bug/demo.jsx:6051:13)
      at renderElement (/Users/kevin/Desktop/bug/demo.jsx:6178:13)
      at renderNodeDestructiveImpl (/Users/kevin/Desktop/bug/demo.jsx:6282:15)
```

Checking in the ApolloClient, I see the following snippet that matches:

https://github.com/apollographql/apollo-client/blame/main/src/react/context/ApolloContext.ts#L30-L32

The compiled source includes:

```javascript
// node_modules/@apollo/client/react/context/ApolloContext.js
function getApolloContext() {
  invariant2("createContext" in exports_rehackt, 45);
  var context5 = undefined[contextKey];
```

Unclear why it is using `undefined[contextKey]`. Further confusion arises based on the target. When setting `target=browser` or `target=bun` it fails, but for `target=node` it strangely works...

### What is the expected behavior?

Bun prints "🚀".

### What do you see instead?

```
22302 | Object.assign(exports_rehackt, import_react);
22303 | 
22304 | // node_modules/@apollo/client/react/context/ApolloContext.js
22305 | function getApolloContext() {
22306 |   invariant2("createContext" in exports_rehackt, 45);
22307 |   var context5 = undefined[contextKey];
                         ^
TypeError: undefined is not an object (evaluating '(void 0)[contextKey]')
      at getApolloContext (/Users/kevin/Desktop/bug/demo.jsx:22307:18)
      at ApolloProvider (/Users/kevin/Desktop/bug/demo.jsx:22324:24)
      at renderWithHooks (/Users/kevin/Desktop/bug/demo.jsx:5957:22)
      at renderIndeterminateComponent (/Users/kevin/Desktop/bug/demo.jsx:6015:21)
      at renderElement (/Users/kevin/Desktop/bug/demo.jsx:6178:13)
      at renderNodeDestructiveImpl (/Users/kevin/Desktop/bug/demo.jsx:6282:15)
      at renderNodeDestructive (/Users/kevin/Desktop/bug/demo.jsx:6262:20)
      at renderIndeterminateComponent (/Users/kevin/Desktop/bug/demo.jsx:6051:13)
      at renderElement (/Users/kevin/Desktop/bug/demo.jsx:6178:13)
      at renderNodeDestructiveImpl (/Users/kevin/Desktop/bug/demo.jsx:6282:15)
```

**Comment by codehz** [comment]
workaround: downgrade the rehackt to 0.6.0

**Comment by codehz** [comment]
https://npmdiff.dev/rehackt/0.0.6/0.1.0/package/index.js I think I found the reason
```ts
if (0) {
  module.exports = require("react");
}
```
break the bun build

**Comment by ksylvest** [comment]
@codehz thank you sharing your findings around fixing!

**Comment by phryneas** [comment]
This seems to be a problem with bun's over-eager dead code eliminiation that runs too soon - before running `cjs-module-lexer` (or whatever bun uses to determine package shape), so as a result `bun` thinks that `rehackt` doesn't export everything and emits `undefined` in a ton of places.

(red is how it should be, green is what bun makes of it)
```diff
- var context = React.createContext[contextKey];
+ var context = undefined[contextKey];
  if (!context) {
-   Object.defineProperty(React.createContext, contextKey, {
+   Object.defineProperty(undefined, contextKey, {
-     value: context = React.createContext({}),
+     value: context = undefined({}),
      enumerable: false,
      writable: false,
      configurable: true
    });
```

If I sidestep that by replacing
```
if (0) {
```
with
```
if (1<2) {
```
everything works as expected.

Which is a shame because at that point we would be shipping dead code for all our consumers because bun is doing things in an unsafe way.

**Is there any chance this will be change so that bun will analyze the shape of a bundle before eliminating big chunks of it?**
