### ISSUE TITLE
`@eslint/object-schema` throws `p.stdin.end` is not a function on macOS

### ISSUE THREAD

**Issue by amareshsm** [oven-sh/bun#12574]
### What version of Bun is running?

1.1.20+ae1948925

### What platform is your computer?

Darwin 21.5.0 arm64 arm

### What steps can reproduce the bug?

Description:
I tried to build the packages within the [Eslint Rewrite](https://github.com/eslint/rewrite). When using Node.js, `npm run build` functioned correctly on both Windows and macOS. However, when I used the command `bun run --bun build` on Windows, it performed as expected, whereas on macOS, I encountered the following error:

```
Building packages in this order: packages/object-schema, packages/config-array, packages/compat, packages/core, packages/migrate-config
Building packages/object-schema...

> @eslint/object-schema@2.1.4 build
> rollup -c && tsc -p tsconfig.esm.json && npm run build:cts

npm ERR! Lifecycle script `build` failed with error: 
npm ERR! TypeError: p.stdin.end is not a function. (In 'p.stdin.end()', 'p.stdin.end' is Infinity) 
npm ERR!   in workspace: @eslint/object-schema@2.1.4 
npm ERR!   at location: /Users/amareshsm/Desktop/Repositories/rewrite/packages/object-schema 
104 | function buildPackages(packageDirs) {
105 |   console.log(`Building packages in this order: ${packageDirs.join(", ")}`);
106 | 
107 |   for (const packageDir of packageDirs) {
108 |           console.log(`Building ${packageDir}...`);
109 |           execSync(`npm run build -w ${packageDir} --if-present`, {
        ^
error: null
   errno: -1
   code: "1"
 syscall: "spawnSync"
   path: "/bin/sh"

      at new SystemError (node:child_process:902:14)
      at node:child_process:175:24
      at node:child_process:226:23
      at buildPackages (/Users/amareshsm/Desktop/Repositories/rewrite/scripts/build.js:109:3)
      at /Users/amareshsm/Desktop/Repositories/rewrite/scripts/build.js:125:1

Bun v1.1.20 (macOS arm64)
error: script "build" exited with code 1
➜  rewrite git:(bun-test) 
src/index.js → dist/cjs/index.cjs, dist/esm/index.js...
created dist/cjs/index.cjs, dist/esm/index.js in 44ms

> @eslint/object-schema@2.1.4 build:cts
> node -e "fs.copyFileSync('dist/esm/index.d.ts', 'dist/cjs/index.d.cts')"

npm ERR! Lifecycle script `build:cts` failed with error: 
npm ERR! TypeError: p.stdin.end is not a function. (In 'p.stdin.end()', 'p.stdin.end' is Infinity) 
npm ERR!   in workspace: @eslint/object-schema@2.1.4 
npm ERR!   at location: /Users/amareshsm/Desktop/Repositories/rewrite/packages/object-schema 
```
Steps:
1. Clone the [repo](https://github.com/eslint/rewrite) 
2. Do `npm install` 
3. Run Bun build command `bun run --bun build`

### What is the expected behavior?

The packages should be built successfully without any errors.

### What do you see instead?

Instead I got the below error:

```
$ node scripts/build.js
Building packages in this order: packages/object-schema, packages/config-array, packages/compat, packages/core, packages/migrate-config
Building packages/object-schema...

> @eslint/object-schema@2.1.4 build
> rollup -c && tsc -p tsconfig.esm.json && npm run build:cts

npm ERR! Lifecycle script `build` failed with error: 
npm ERR! TypeError: p.stdin.end is not a function. (In 'p.stdin.end()', 'p.stdin.end' is Infinity) 
npm ERR!   in workspace: @eslint/object-schema@2.1.4 
npm ERR!   at location: /Users/amareshsm/Desktop/Repositories/rewrite/packages/object-schema 
104 | function buildPackages(packageDirs) {
105 |   console.log(`Building packages in this order: ${packageDirs.join(", ")}`);
106 | 
107 |   for (const packageDir of packageDirs) {
108 |           console.log(`Building ${packageDir}...`);
109 |           execSync(`npm run build -w ${packageDir} --if-present`, {
        ^
error: null
   errno: -1
   code: "1"
 syscall: "spawnSync"
   path: "/bin/sh"

      at new SystemError (node:child_process:902:14)
      at node:child_process:175:24
      at node:child_process:226:23
      at buildPackages (/Users/amareshsm/Desktop/Repositories/rewrite/scripts/build.js:109:3)
      at /Users/amareshsm/Desktop/Repositories/rewrite/scripts/build.js:125:1

Bun v1.1.20 (macOS arm64)
error: script "build" exited with code 1
➜  rewrite git:(bun-test) 
src/index.js → dist/cjs/index.cjs, dist/esm/index.js...
created dist/cjs/index.cjs, dist/esm/index.js in 44ms

> @eslint/object-schema@2.1.4 build:cts
> node -e "fs.copyFileSync('dist/esm/index.d.ts', 'dist/cjs/index.d.cts')"

npm ERR! Lifecycle script `build:cts` failed with error: 
npm ERR! TypeError: p.stdin.end is not a function. (In 'p.stdin.end()', 'p.stdin.end' is Infinity) 
npm ERR!   in workspace: @eslint/object-schema@2.1.4 
npm ERR!   at location: /Users/amareshsm/Desktop/Repositories/rewrite/packages/object-schema 

```

![image](https://github.com/user-attachments/assets/a2bf8bc2-58af-4d87-8ead-1b1ba3b732bf)

### Additional information

It is failing in CI as well - https://github.com/eslint/rewrite/pull/87

When I used the `bun run --bun build`  command to build each package individually, it worked as expected.

![image](https://github.com/user-attachments/assets/895f26f4-4a37-493c-b1ac-2cf31e142761)

**Comment by amareshsm** [comment]
I also tried to use `spawnSync` instead of `execSync`, but encountered the same error.

**Comment by amareshsm** [comment]
@190n  Are you looking into this issue?

**Comment by robobun** [comment]
**Bun version:** `1.3.11` on `linux x86_64`
**Reported version:** `1.1.20` on `Darwin arm64`

**Attempt 1: Direct `stdin.end()` on spawned child process**

```console
$ cat /tmp/test_stdin.js
const { spawn } = require('child_process');
const p = spawn('cat', [], { stdio: ['pipe', 'pipe', 'pipe'] });
console.log("stdin.end type:", typeof p.stdin.end);
console.log("stdin.end === Infinity:", p.stdin.end === Infinity);
p.stdin.write("hello\n");
p.stdin.end();
p.stdout.on('data', (d) => console.log("stdout:", d.toString().trim()));
p.on('close', () => console.log("done"));

$ bun run --bun /tmp/test_stdin.js
stdin.end type: function
stdin.end === Infinity: false
stdout: hello
done
```

`stdin.end` is correctly a function, not `Infinity`.

**Attempt 2: Simulated npm workspace build via `execSync` (matching issue's pattern)**

Created a workspace with `execSync('npm run build -w packages/a --if-present', { stdio: 'inherit' })` — the same pattern the eslint/rewrite build script uses.

```console
$ bun run --bun build
$ node scripts/build.js

> pkg-a@1.0.0 build
> echo built-a && node -e "console.log('sub-script done')"

built-a
sub-script done
All builds done
```

Works correctly — no `p.stdin.end is not a function` error.

**Attempt 3: All stdio modes for `spawn`**

```console
$ bun run --bun /tmp/test_stdin_comprehensive.js
=== Test 1: spawn with pipe stdin ===
stdin type: object
stdin.end type: function
stdin.end === Infinity: false
=== Test 2: spawn with inherit stdin ===
stdin: null
stdin is null: true
=== Test 3: spawnSync ===
stdin: undefined
=== Test 4: execSync ===
test4
Test 4 done

All tests passed
```

All stdio modes behave correctly.

**Conclusion:** This appears to have been fixed in a version between 1.1.20 and 1.3.11. There have been numerous child process and stdin fixes since the issue was filed (July 2024), including fixes for stdin stream handling, FileSink behavior, and child process stdio management.

## Verification

```console
$ bun run --bun /tmp/test_12574.js
ok
OK: p.stdin.end is a function, stdin piping works, execSync works
```

Exit: `0` · Bun: `1.3.11` (built from main)

---
*Automated investigation. Reopen with more context if this is wrong.*
