### ISSUE TITLE
Importing enum inside of `class` is broken since 1.1.18

### ISSUE THREAD

**Issue by ziggi** [oven-sh/bun#12805]
### What version of Bun is running?

1.1.20+ae1948925, 1.1.21-canary.1+907cd8d45

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

**test.ts**

```ts
export enum TestEnum {
  a,
  b,
  c,
  d,
}
```

**index.ts**
```ts
import { TestEnum } from './test';

class TestClass {
  constructor() {
    console.log(TestEnum);
  }

  testMethod(name: TestEnum) {
    if (name === TestEnum.a) {
      return true;
    }

    return false;
  }
}

new TestClass();
```

**build & run**
```
bun build ./src/index.ts --outdir ./dist/ --target=bun
bun ./dist/index.js
```

### What is the expected behavior?

Result on Bun `1.1.17+bb66bba1b`
```js
// @bun
// src/test.ts
var TestEnum;
(function(TestEnum2) {
  TestEnum2[TestEnum2["a"] = 0] = "a";
  TestEnum2[TestEnum2["b"] = 1] = "b";
  TestEnum2[TestEnum2["c"] = 2] = "c";
  TestEnum2[TestEnum2["d"] = 3] = "d";
})(TestEnum || (TestEnum = {}));

// src/index.ts
class TestClass {
  constructor() {
    console.log(TestEnum);
  }
  testMethod(name) {
    if (name === TestEnum.a) {
      return true;
    }
    return false;
  }
}
new TestClass;
```

```
{
  "0": "a",
  "1": "b",
  "2": "c",
  "3": "d",
  a: 0,
  b: 1,
  c: 2,
  d: 3,
}
```

### What do you see instead?

Result on Bun `1.1.21-canary.1+907cd8d45`

```js
// @bun
// src/index.ts
class TestClass {
  constructor() {
    console.log(TestEnum);
  }
  testMethod(name) {
    if (name === 0 /* a */) {
      return true;
    }
    return false;
  }
}
new TestClass;

```

```
2 | // @bun
3 | // src/index.ts
4 | class TestClass {
5 |     console.log(TestEnum);
                            ^
ReferenceError: Can't find variable: TestEnum
      at new TestClass (C:\Users\ziggi\Desktop\bun_enum\dist\index.js:5:25)
      at C:\Users\ziggi\Desktop\bun_enum\dist\index.js:14:1
note: missing sourcemaps for C:\Users\ziggi\Desktop\bun_enum\dist\index.js
note: consider bundling with '--sourcemap' to get unminified traces

Bun v1.1.21-canary.1+907cd8d45 (Windows x64)
```

### Additional information

I think it's related to https://github.com/oven-sh/bun/issues/2945

**Comment by paperdave** [comment]
it's not marking a dependency on the import, yikes. thanks for finding this

temporarily you can work around this by adding a line referencing the enum at the top level, as this only happens inside the class declaration.

```ts
+TestEnum; // <-- this forcefully adds a dependency on `TestEnum`
```

**Comment by Grimille** [comment]
I had the same issue with LogLevel enum, referencing the enum did the trick, thanks !

**Comment by paperdave** [comment]
(after the linked pr is merged, please stop using the silly workaround)
