### ISSUE TITLE
[SubtleCrypto] Importing keys with invalid usages should return a better error message

### ISSUE THREAD

**Issue by TheDevMinerTV** [oven-sh/bun#12824]
### What is the problem this feature would solve?

When importing a ed25519 private key with invalid usages (`crypto.subtle.importKey('pkcs8', priv, { name: 'Ed25519' }, true, ['verify', 'sign']);`, `verify` should not be here) Bun returns the following error:
```
3 | {
4 |     {
5 |             const privK = await crypto.subtle.importKey('pkcs8', priv, { name: 'Ed25519' }, true, ['verify', 'sign']);
      ^
SyntaxError: A required parameter was missing or out-of-range
      at /tmp/repro.js:5:3
```
which is super confusing because the `^` also isn't properly aligned with the invalid usage or even the function call.

Running the same in Node yields the following:
```
node:internal/crypto/cfrg:67
    throw lazyDOMException(
          ^
DOMException [SyntaxError]: Unsupported key usage for a Ed25519 key
    at verifyAcceptableCfrgKeyUse (node:internal/crypto/cfrg:67:11)
    at Object.cfrgImportKey (node:internal/crypto/cfrg:224:7)
    at SubtleCrypto.importKey (node:internal/crypto/webcrypto:631:10)
    at file:///tmp/repro.js:5:37
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
```
which is slightly less confusing and at least says something about the invalid usage.

### What is the feature you are proposing to solve the problem?

Return a similar error to Node and fix the `^` alignment

**Comment by mikemaccana** [comment]
Node also has a typo here, it should correctly be:

> Unsupported key usage for an Ed25519 key
