### ISSUE TITLE
Sourmaps are broken when using with external modules

### ISSUE THREAD

**Issue by schettn** [oven-sh/bun#12833]
### What version of Bun is running?

1.1.21-canary.1+d321ee97c

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Src file:
```ts
import {defineService, logger, PylonAPI} from '@getcronit/pylon'

const someErrorFn = () => {
  console.log('Hello, World!')
  throw new Error('Hello, World!')
  return 'Hello, world!'
}

export default defineService({
  Query: {
    hello() {
      someErrorFn()
    }
  }
})

export const configureApp: PylonAPI['configureApp'] = app => {
  logger.info('Configuring app')
}

```

Bundle:
```js
// @bun
// src/index.ts
import {defineService, logger} from "@getcronit/pylon";
var someErrorFn = () => {
  console.log("Hello, World!");
  throw new Error("Hello, World!");
  return "Hello, world!";
};
var src_default = defineService({
  Query: {
    hello() {
      someErrorFn();
    }
  }
});

throw new Error("Hello, World!");
var configureApp = (app) => {
  logger.info("Configuring app");
};
export {
  src_default as default,
  configureApp
};

//# debugId=E3A5C5753E67ACF664756E2164756E21
```

Source map:
```json
{
  "version": 3,
  "sources": ["../src/index.ts"],
  "sourcesContent": [
    "import {defineService, logger, PylonAPI} from '@getcronit/pylon'\n\nconst someErrorFn = () => {\n  console.log('Hello, World!')\n  throw new Error('Hello, World!')\n  return 'Hello, world!'\n}\n\nexport default defineService({\n  Query: {\n    hello() {\n      someErrorFn()\n    }\n  }\n})\n\nexport const configureApp: PylonAPI['configureApp'] = app => {\n  logger.info('Configuring app')\n}\n"
  ],
  "mappings": ";;AAAA;AAEA,IAAM,cAAc,MAAM;AACxB,UAAQ,IAAI,eAAe;AAC3B,QAAM,IAAI,MAAM,eAAe;AAC/B,SAAO;AAAA;AAGT,IAAe,4BAAc;AAAA,EAC3B,OAAO;AAAA,IACL,KAAK,GAAG;AACN,kBAAY;AAAA;AAAA,EAEhB;AACF,CAAC;AAEM,IAAM,eAAyC,SAAO;AAC3D,SAAO,KAAK,iBAAiB;AAAA;",
  "debugId": "619B73E58DD9167864756E2164756E21",
  "names": []
}
```

![image](https://github.com/user-attachments/assets/f083a773-2011-4713-8381-2f90626f5583)

See that the error stack of `someErrorFn` points to the `.js` file instead of the source file.

### What is the expected behavior?

The error stack should be:

```bash
GraphQLError: Hello, World!
      at someErrorFn (/Users/schettn/Documents/pylon/pylon-template/src/index.ts:5:8)
      at hello (/Users/schettn/Documents/pylon/pylon-template/src/index.ts:12:7)
```

### What do you see instead?

```bash
ERR 1 | // @bun
2 | // src/index.ts
3 | import {defineService, logger} from "@getcronit/pylon";
4 | var someErrorFn = () => {
5 |   console.log("Hello, World!");
           ^
GraphQLError: Hello, World!
      at someErrorFn (/Users/schettn/Documents/pylon/pylon-template/.pylon/index.js:5:8)
      at hello (/Users/schettn/Documents/pylon/pylon-template/src/index.ts:12:7)

```

**Comment by schettn** [comment]
This only does not work when I call `someErrorFn()` inside the `defineService` from the external package. When I call `someErrorFn()` directly inside a fn defined in the main file it works.


```ts
const someErrorFn = () => {
  console.log('Hello, World!')
  throw new Error('Hello, World!')
  return 'Hello, world!'
}

const originFn = () => {
  someErrorFn()
}

originFn()
```


```bash
1 | import {defineService, logger, PylonAPI} from '@getcronit/pylon'
2 | 
3 | const someErrorFn = () => {
4 |   console.log('Hello, World!')
5 |   throw new Error('Hello, World!')
            ^
error: Hello, World!
      at someErrorFn (/Users/schettn/Documents/pylon/pylon-template/src/index.ts:5:9)
      at originFn (/Users/schettn/Documents/pylon/pylon-template/src/index.ts:18:3)
      at /Users/schettn/Documents/pylon/pylon-template/src/index.ts:21:1
```

**Comment by schettn** [comment]
Update: I used `import 'source-map-support/register'` somewhere in my modules. After removing it it worked!
