### ISSUE TITLE
`signal-exit` package misbehaves with Bun (node compatibility)

### ISSUE THREAD

**Issue by stefreak** [oven-sh/bun#12918]
### What version of Bun is running?

1.1.20+ae1948925

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

1. Write these files:

```js
// onExit1.mjs
import { onExit } from "signal-exit"

process.on("SIGINT", function(signal) { console.log("Native signal handler got " + signal) })
onExit(function(exitCode) { console.log("onExit called with exit code " + exitCode) })

setTimeout(() => {console.log("bye!")}, 600)
setTimeout(() => {process.kill(process.pid, "SIGINT")}, 300)
```

```js
// onExit2.mjs
import { onExit } from "signal-exit"

onExit(function(exitCode) { console.log("onExit called with exit code " + exitCode) })
process.on("SIGINT", function(signal) { console.log("Native signal handler got " + signal) })

setTimeout(() => {console.log("bye!")}, 600)
setTimeout(() => {process.kill(process.pid, "SIGINT")}, 300)
```

```js
// writeFileAtomically1.mjs
import writeFileAtomically from "write-file-atomic"

process.on("SIGINT", function(signal) { console.log("Native signal handler got " + signal) })

await writeFileAtomically("foo.txt", "hello")

setTimeout(() => {console.log("bye!")}, 600)
setTimeout(() => {process.kill(process.pid, "SIGINT")}, 300)
```

```js
// writeFileAtomically2.mjs
import writeFileAtomically from "write-file-atomic"

await writeFileAtomically("foo.txt", "hello")
process.on("SIGINT", function(signal) { console.log("Native signal handler got " + signal) })

setTimeout(() => {console.log("bye!")}, 600)
setTimeout(() => {process.kill(process.pid, "SIGINT")}, 300)
```

2. Install dependencies
```sh
npm i write-file-atomic signal-exit
```

3. Behaviour differs from NodeJS

### What is the expected behavior?

```
% node onExit1.mjs
Native signal handler got SIGINT
bye!
onExit called with exit code 0
```

```
% node onExit2.mjs
Native signal handler got SIGINT
bye!
onExit called with exit code 0
```

```
% node writeFileAtomically1.mjs
Native signal handler got SIGINT
bye!
```

```
% node writeFileAtomically2.mjs
Native signal handler got SIGINT
bye!
```

### What do you see instead?

onExit examples both misbehave (onExit is not being called):

```diff
% bun onExit1.mjs
Native signal handler got SIGINT
bye!
-onExit called with exit code 0
```

```diff
% bun onExit2.mjs
Native signal handler got SIGINT
bye!
-onExit called with exit code 0
```

Variant one of writeFileAtomically does not work:
```diff
% bun writeFileAtomically1.mjs
-Native signal handler got SIGINT
-bye!
```

While variant two works as expected:
```
% bun writeFileAtomically2.mjs
Native signal handler got SIGINT
bye!
```

### Additional information

 % node --version
v21.1.0

% cat package.json
```
{
  "dependencies": {
    "signal-exit": "^4.1.0",
    "write-file-atomic": "^5.0.1"
  }
}
```

**Comment by bauti-defi** [comment]
I believe this may be the same bug I ran into. 

ref here:

https://x.com/BautiDeFi/status/1920983466398617797

**Comment by erictheswift** [comment]
`signal-exit` package relies on process.emit, process.reallyExit overrides to be called, and seems they aren't in bun.

Minimal demo:
```typescript
import { onExit } from 'signal-exit'

process.on('beforeExit', (code) => {
  console.log(`process.on 'beforeExit'`, code)
})
process.on('exit', (code) => {
  console.log(`process.on 'exit'`, code)
})

const processExitOrig = process.exit
process.exit = function (code) {
  console.trace('process.exit(%o)', code)
  return processExitOrig.call(this, code)
}

const reallyExitOrig = process.reallyExit
process.reallyExit = function () {
  console.trace('process.reallyExit(%o)', arguments)
  return reallyExitOrig.apply(this, arguments)
}

const reallyEmitOrig = process.emit
process.emit = function () {
  console.trace('process.emit(%o)', arguments)
  return reallyEmitOrig.apply(this, arguments)
}
onExit(function () {
  console.trace('signal-exit onExit', arguments)
})
```

Compare
```
$ bun --version
1.2.23
$ bun min.ts
process.on 'beforeExit' 0
process.on 'exit' 0
```

to

```
$ node min.ts
Trace: process.emit([Arguments] {
  '0': 'newListener',
  '1': 'SIGWINCH',
  '2': <ref *1> [Function: refreshStderrOnSigWinch] {
    [length]: 0,
    [name]: 'refreshStderrOnSigWinch',
    [prototype]: { [constructor]: [Circular *1] }
  },
  [length]: 3,
  [callee]: [Getter/Setter],
  [Symbol(Symbol.iterator)]: [Function: values] { [length]: 0, [name]: 'values' }
})
    at process.emit (min.ts:24:11)
    at _addListener (node:events:551:14)
    at process.addListener (node:events:600:10)
    at process.getStderr [as stderr] (node:internal/bootstrap/switches/is_main_thread:181:13)
    at console.get (node:internal/console/constructor:220:38)
    at console.value (node:internal/console/constructor:343:50)
    at console.trace (node:internal/console/constructor:438:38)
    at process.emit (min.ts:24:11)
    at _addListener (node:events:551:14)
    at process.addListener (node:events:600:10)
Trace: process.emit([Arguments] {
  '0': 'newListener',
  '1': 'SIGHUP',
  '2': [Function (anonymous)] { [length]: 0, [name]: '' },
  [length]: 3,
  [callee]: [Getter/Setter],
  [Symbol(Symbol.iterator)]: [Function: values] { [length]: 0, [name]: 'values' }
})
    at process.emit (min.ts:24:11)
    at _addListener (node:events:551:14)
    at process.addListener (node:events:600:10)
    at SignalExit.load (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:182:35)
    at SignalExit.onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:156:18)
    at onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:80:28)
    at min.ts:27:1
    at ModuleJob.run (node:internal/modules/esm/module_job:371:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:683:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5)
Trace: process.emit([Arguments] {
  '0': 'newListener',
  '1': 'SIGINT',
  '2': [Function (anonymous)] { [length]: 0, [name]: '' },
  [length]: 3,
  [callee]: [Getter/Setter],
  [Symbol(Symbol.iterator)]: [Function: values] { [length]: 0, [name]: 'values' }
})
    at process.emit (min.ts:24:11)
    at _addListener (node:events:551:14)
    at process.addListener (node:events:600:10)
    at SignalExit.load (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:182:35)
    at SignalExit.onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:156:18)
    at onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:80:28)
    at min.ts:27:1
    at ModuleJob.run (node:internal/modules/esm/module_job:371:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:683:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5)
Trace: process.emit([Arguments] {
  '0': 'newListener',
  '1': 'SIGTERM',
  '2': [Function (anonymous)] { [length]: 0, [name]: '' },
  [length]: 3,
  [callee]: [Getter/Setter],
  [Symbol(Symbol.iterator)]: [Function: values] { [length]: 0, [name]: 'values' }
})
    at process.emit (min.ts:24:11)
    at _addListener (node:events:551:14)
    at process.addListener (node:events:600:10)
    at SignalExit.load (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:182:35)
    at SignalExit.onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:156:18)
    at onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:80:28)
    at min.ts:27:1
    at ModuleJob.run (node:internal/modules/esm/module_job:371:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:683:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5)
Trace: process.emit([Arguments] {
  '0': 'newListener',
  '1': 'SIGALRM',
  '2': [Function (anonymous)] { [length]: 0, [name]: '' },
  [length]: 3,
  [callee]: [Getter/Setter],
  [Symbol(Symbol.iterator)]: [Function: values] { [length]: 0, [name]: 'values' }
})
    at process.emit (min.ts:24:11)
    at _addListener (node:events:551:14)
    at process.addListener (node:events:600:10)
    at SignalExit.load (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:182:35)
    at SignalExit.onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:156:18)
    at onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:80:28)
    at min.ts:27:1
    at ModuleJob.run (node:internal/modules/esm/module_job:371:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:683:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5)
Trace: process.emit([Arguments] {
  '0': 'newListener',
  '1': 'SIGABRT',
  '2': [Function (anonymous)] { [length]: 0, [name]: '' },
  [length]: 3,
  [callee]: [Getter/Setter],
  [Symbol(Symbol.iterator)]: [Function: values] { [length]: 0, [name]: 'values' }
})
    at process.emit (min.ts:24:11)
    at _addListener (node:events:551:14)
    at process.addListener (node:events:600:10)
    at SignalExit.load (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:182:35)
    at SignalExit.onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:156:18)
    at onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:80:28)
    at min.ts:27:1
    at ModuleJob.run (node:internal/modules/esm/module_job:371:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:683:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5)
Trace: process.emit([Arguments] {
  '0': 'newListener',
  '1': 'SIGVTALRM',
  '2': [Function (anonymous)] { [length]: 0, [name]: '' },
  [length]: 3,
  [callee]: [Getter/Setter],
  [Symbol(Symbol.iterator)]: [Function: values] { [length]: 0, [name]: 'values' }
})
    at process.emit (min.ts:24:11)
    at _addListener (node:events:551:14)
    at process.addListener (node:events:600:10)
    at SignalExit.load (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:182:35)
    at SignalExit.onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:156:18)
    at onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:80:28)
    at min.ts:27:1
    at ModuleJob.run (node:internal/modules/esm/module_job:371:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:683:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5)
Trace: process.emit([Arguments] {
  '0': 'newListener',
  '1': 'SIGXCPU',
  '2': [Function (anonymous)] { [length]: 0, [name]: '' },
  [length]: 3,
  [callee]: [Getter/Setter],
  [Symbol(Symbol.iterator)]: [Function: values] { [length]: 0, [name]: 'values' }
})
    at process.emit (min.ts:24:11)
    at _addListener (node:events:551:14)
    at process.addListener (node:events:600:10)
    at SignalExit.load (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:182:35)
    at SignalExit.onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:156:18)
    at onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:80:28)
    at min.ts:27:1
    at ModuleJob.run (node:internal/modules/esm/module_job:371:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:683:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5)
Trace: process.emit([Arguments] {
  '0': 'newListener',
  '1': 'SIGXFSZ',
  '2': [Function (anonymous)] { [length]: 0, [name]: '' },
  [length]: 3,
  [callee]: [Getter/Setter],
  [Symbol(Symbol.iterator)]: [Function: values] { [length]: 0, [name]: 'values' }
})
    at process.emit (min.ts:24:11)
    at _addListener (node:events:551:14)
    at process.addListener (node:events:600:10)
    at SignalExit.load (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:182:35)
    at SignalExit.onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:156:18)
    at onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:80:28)
    at min.ts:27:1
    at ModuleJob.run (node:internal/modules/esm/module_job:371:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:683:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5)
Trace: process.emit([Arguments] {
  '0': 'newListener',
  '1': 'SIGUSR2',
  '2': [Function (anonymous)] { [length]: 0, [name]: '' },
  [length]: 3,
  [callee]: [Getter/Setter],
  [Symbol(Symbol.iterator)]: [Function: values] { [length]: 0, [name]: 'values' }
})
    at process.emit (min.ts:24:11)
    at _addListener (node:events:551:14)
    at process.addListener (node:events:600:10)
    at SignalExit.load (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:182:35)
    at SignalExit.onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:156:18)
    at onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:80:28)
    at min.ts:27:1
    at ModuleJob.run (node:internal/modules/esm/module_job:371:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:683:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5)
Trace: process.emit([Arguments] {
  '0': 'newListener',
  '1': 'SIGTRAP',
  '2': [Function (anonymous)] { [length]: 0, [name]: '' },
  [length]: 3,
  [callee]: [Getter/Setter],
  [Symbol(Symbol.iterator)]: [Function: values] { [length]: 0, [name]: 'values' }
})
    at process.emit (min.ts:24:11)
    at _addListener (node:events:551:14)
    at process.addListener (node:events:600:10)
    at SignalExit.load (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:182:35)
    at SignalExit.onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:156:18)
    at onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:80:28)
    at min.ts:27:1
    at ModuleJob.run (node:internal/modules/esm/module_job:371:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:683:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5)
Trace: process.emit([Arguments] {
  '0': 'newListener',
  '1': 'SIGSYS',
  '2': [Function (anonymous)] { [length]: 0, [name]: '' },
  [length]: 3,
  [callee]: [Getter/Setter],
  [Symbol(Symbol.iterator)]: [Function: values] { [length]: 0, [name]: 'values' }
})
    at process.emit (min.ts:24:11)
    at _addListener (node:events:551:14)
    at process.addListener (node:events:600:10)
    at SignalExit.load (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:182:35)
    at SignalExit.onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:156:18)
    at onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:80:28)
    at min.ts:27:1
    at ModuleJob.run (node:internal/modules/esm/module_job:371:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:683:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5)
Trace: process.emit([Arguments] {
  '0': 'newListener',
  '1': 'SIGQUIT',
  '2': [Function (anonymous)] { [length]: 0, [name]: '' },
  [length]: 3,
  [callee]: [Getter/Setter],
  [Symbol(Symbol.iterator)]: [Function: values] { [length]: 0, [name]: 'values' }
})
    at process.emit (min.ts:24:11)
    at _addListener (node:events:551:14)
    at process.addListener (node:events:600:10)
    at SignalExit.load (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:182:35)
    at SignalExit.onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:156:18)
    at onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:80:28)
    at min.ts:27:1
    at ModuleJob.run (node:internal/modules/esm/module_job:371:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:683:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5)
Trace: process.emit([Arguments] {
  '0': 'newListener',
  '1': 'SIGIOT',
  '2': [Function (anonymous)] { [length]: 0, [name]: '' },
  [length]: 3,
  [callee]: [Getter/Setter],
  [Symbol(Symbol.iterator)]: [Function: values] { [length]: 0, [name]: 'values' }
})
    at process.emit (min.ts:24:11)
    at _addListener (node:events:551:14)
    at process.addListener (node:events:600:10)
    at SignalExit.load (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:182:35)
    at SignalExit.onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:156:18)
    at onExit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:80:28)
    at min.ts:27:1
    at ModuleJob.run (node:internal/modules/esm/module_job:371:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:683:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5)
process.on 'beforeExit' 0
process.on 'exit' 0
Trace: signal-exit onExit [Arguments] { '0': 0, '1': null }
    at min.ts:28:11
    at Emitter.emit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:67:19)
    at #processEmit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:236:27)
    at #process.emit (node_modules/.pnpm/signal-exit@4.1.0/node_modules/signal-exit/dist/mjs/index.js:187:37)
```
