### ISSUE TITLE
React: `renderToReadableStream` error on production mode

### ISSUE THREAD

**Issue by MolikoDeveloper** [oven-sh/bun#12961]
### What version of Bun is running?

1.1.21

### What platform is your computer?

Linux 5.15.0-116-generic x86_64 x86_64

### What steps can reproduce the bug?

package.json
```json
{
  "name": "test",
  "module": "index.tsx",
  "type": "module",
  "devDependencies": {
    "@types/bun": "latest",
    "@types/react-dom": "^18.3.0",
    "@types/react": "18.3.3"
  },
  "peerDependencies": {
    "typescript": "^5.5.4"
  },
  "dependencies": {
    "react-router-dom": "^6.25.1",
    "react-dom": "next",
    "react": "next"
  }
}
```

install all
```bash
bun i
```

*index.tsx*:
```tsx
import { renderToReadableStream } from "react-dom/server";

Bun.serve({
    port: 3090,
    fetch: async (request, server) => {

        const stream = await renderToReadableStream(
            <h1>Render Test</h1>
        );

        return new Response(stream, { status: 200 });
    }
})
```

*.env file*:
```env
NODE_ENV=production
```

```bash
bun index.tsx
```

### What is the expected behavior?

```html
<html>
    <head>
    </head>
    <body>
        <h1>Render Test</h1>
    </body>
</html>
```

### What do you see instead?

on web:
Something went wrong!

on console:
```bash
4478 |           task,
4479 |           node._currentValue,
4480 |           childIndex
4481 |         );
4482 |       childIndex = Object.prototype.toString.call(node);
4483 |       throw Error(
                   ^
error: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner}). If you meant to render a collection of children, use an array instead.
      at retryNode (/home/twitchts/projects/pruebas-ssr-csr/node_modules/react-dom/cjs/react-dom-server.bun.production.js:4483:13)
      at performWork (/home/twitchts/projects/pruebas-ssr-csr/node_modules/react-dom/cjs/react-dom-server.bun.production.js:5040:13)
      at /home/twitchts/projects/pruebas-ssr-csr/node_modules/react-dom/cjs/react-dom-server.bun.production.js:5511:12

4478 |           task,
4479 |           node._currentValue,
4480 |           childIndex
4481 |         );
4482 |       childIndex = Object.prototype.toString.call(node);
4483 |       throw Error(
                   ^
error: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner}). If you meant to render a collection of children, use an array instead.
      at retryNode (/home/twitchts/projects/pruebas-ssr-csr/node_modules/react-dom/cjs/react-dom-server.bun.production.js:4483:13)
      at performWork (/home/twitchts/projects/pruebas-ssr-csr/node_modules/react-dom/cjs/react-dom-server.bun.production.js:5040:13)
      at /home/twitchts/projects/pruebas-ssr-csr/node_modules/react-dom/cjs/react-dom-server.bun.production.js:5511:12
```

### Additional information

this only happens on production mode, when i run it in debug mode works fine

**Comment by MolikoDeveloper** [comment]
I was able to identify that in `react-dom\cjs\react-dom-server.bun.production.js` there is a type called REACT_ELEMENT_TYPE, which does not match the current node.$$type. Could that be the reason?

Their values are different:

> REACT_ELEMENT_TYPE = Symbol.for("react.transitional.element")

> node.$$type = Symbol("react.element")

**Comment by MolikoDeveloper** [comment]
temporal fix adding and modify:
```js
var React = require("react"),
ReactDom = require("react-dom),
  REACT_ELEMENT_TYPE = Symbol.for("react.element"),
  REACT_TRANSITIONAL_ELEMENT_TYPE = Symbol.for("react.transitional.element"),
  ...
  ```
  
  and:
  

```js
function retryNode(request, task){
...
  if(null !== node){
    if ("object" === typeof node) {
      switch(node,$typeof){
        case REACT_ELEMENT_TYPE:
        case REACT_TRANSITIONAL_ELEMENT_TYPE: // same as REACT_ELEMENT_TYPE

        default:
          //throw errors here also, for easy read in the console.
      }
    }
  }
...
}
```

**Comment by MolikoDeveloper** [comment]
im closing this issue and create a new issue in https://github.com/facebook/react/issues/30553
