### ISSUE TITLE
Implement `process.binding("http_parser")` 

### ISSUE THREAD

**Issue by entrptaher** [oven-sh/bun#13072]
The `process.binding("http_parser")` API blocks at least the following packages:
- `msw`
- Vercel `ai` SDK v4 for testing-related code
- `prisma^2` (not later versions, it appears)

Original issue:
----

### What version of Bun is running?

1.1.21+70ca2b76c

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Install and create a prisma@2 project.

```
bunx --bun prisma@^2 init
```

```
28254 |   } else {
28255 |     module2.exports = process.binding("http_parser").HTTPParser;
                                      ^
error: process.binding("http_parser") is not implemented in Bun. If that breaks something, please file an issue and include a reproducible code sample.
      at /tmp/bunx-1000-prisma@^2/node_modules/prisma/build/index.js:28255:31
      at /tmp/bunx-1000-prisma@^2/node_modules/prisma/build/index.js:12:5
      at /tmp/bunx-1000-prisma@^2/node_modules/prisma/build/index.js:28734:20
      at /tmp/bunx-1000-prisma@^2/node_modules/prisma/build/index.js:12:5
      at /tmp/bunx-1000-prisma@^2/node_modules/prisma/build/index.js:30738:16
      at /tmp/bunx-1000-prisma@^2/node_modules/prisma/build/index.js:12:5
      at /tmp/bunx-1000-prisma@^2/node_modules/prisma/build/index.js:30789:35
      at /tmp/bunx-1000-prisma@^2/node_modules/prisma/build/index.js:12:5
      at /tmp/bunx-1000-prisma@^2/node_modules/prisma/build/index.js:30904:38

Bun v1.1.21 (Linux x64)
```

**Comment by pavelsvitek** [comment]
👍🏼  I migrated CI back from `Bun` to `NodeJS`

**Comment by zugdev** [comment]
bumping ^

**Comment by samuellawerentz** [comment]
bumping ^ as it is failing our tests.

**Comment by BleedingDev** [comment]
I have exactly same issue, even though #2297 is closed, MSW still doesn't work. :/

**Comment by david-err** [comment]
As a workaround I downgraded/pinned msw to `2.3.1`, which solved it for my use cases. YMMV

**Comment by oendnsk675** [comment]
> 2.3.1

thanks for now, this can help

**Comment by kettanaito** [comment]
You can certainly downgrade to a version that doesn't rely on the HTTP parser but I wouldn't recommend that as a solution. This is kind of a gray territory here since `HTTPParser` isn't technically a public API in Node.js. It's rather hidden under `_http_common`. The API is still there and you can use it, as we do in MSW for raw socket packet parsing into HTTP messages with the new interception algorithm. 

I can understand if this wouldn't be on top of the Bun's team priority list. That being said, a lot of developers seem to want MSW with Bun, and I hope the team finds some time to look into this. 

We aren't dead-set on `HTTPParser`. We just need some way to parse socket packets. If the Bun team rolls out a custom parser that's compatible with the behaviors from Node's `HTTPParser` and is smaller/faster/better, I will be open to migrating to that parser given it's published as a standalone package for everyone to use and enjoy.

**Comment by trfi** [comment]
Bump

**Comment by kettanaito** [comment]
There's been a useful thread on Twitter recently that suggested we used `llhttp` parser instead (its WASM binding). I'm considering that for MSW in the future but for now we will keep using `HTTPParser` from the internals. 

I am extremely excited to see this merged and grateful to the team for their effort here.

**Comment by nakasyou** [comment]
The class isn't provided from `_http_common` so https://github.com/mastra-ai/mastra/issues/4264 can't be resolved. Can you export it from `_http_common`?
