### ISSUE TITLE
crash in `ASTMemoryAllocator` when using extremely large sources and `--compile`

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#13103]
When using this test case
```ts
itBundled("bun/SourceMapLargeFile", {
  target: "bun",
  compile: true,
  files: {
    "/entry.ts": /* js */ `
      // this test is not checking behaviors with any of these libraries but
      // just using them to increase the size of the binary to see if large
      // payloads have issues. accuracy of large sourcemaps is tested elsewhere.
      import * as aws from ${JSON.stringify(require.resolve("aws-cdk-lib"))};
      import * as webpack from ${JSON.stringify(require.resolve("webpack"))};
      import * as mysql2 from ${JSON.stringify(require.resolve("mysql2"))};

      // this file has comments and weird whitespace, intentionally
      // to make it obvious if sourcemaps were generated and mapped properly
      if           (true) code();
      function code() {
        // hello world
                throw   new
          Error("Hello World");
      }

      console.log(aws, webpack, mysql2);
    `,
  },
  sourceMap: "external",
  onAfterBundle(api) {
    rmSync(api.join("entry.ts"), {}); // Hide the source files for errors
  },
  run: {
    exitCode: 1,
    validate({ stderr }) {
      expect(stderr).toStartWith(
        `1 | // this file has comments and weird whitespace, intentionally
2 | // to make it obvious if sourcemaps were generated and mapped properly
3 | if           (true) code();
4 | function code() {
5 |   // hello world
6 |           throw   new
                    ^
error: Hello World`,
      );
      expect(stderr).toInclude("entry.ts:6:19");
    },
  },
});
```

I get a crash while bundling in ASTMemoryAllocator.

![image](https://github.com/user-attachments/assets/ce92b585-05c8-4c54-9262-a5a376530de4)

~~My proposed solution to this is to just delete `ASTMemoryAllocator`, as it was sort of leftover code from https://github.com/oven-sh/bun/pull/12388. `NewStore` is a better bump allocator. Looking at the remaining usages of it, I think it could be replaced with two things.~~

- ~~add to a way to push and pop reset points onto the threadlocal `NewStore` that already exists (this is most uses boil down to)~~
- ~~an option to configure how much to pre-allocate at initialization (this takes care of bun install's use-case "The default store we use pre-allocates around 16 MB of memory per thread; That adds up in multi-threaded scenarios.")~~

**EDIT**: The above solution is not satisfactory as AstMemoryAllocator is used to hold onto an ast for a lifetime longer than what the store allows for.

Opening an issue to look into later instead of just doing a quick fix, since that quick fix is unlikely to be reliable. the better fix is the harder thing.

**Comment by paperdave** [comment]
In a release build there is undefined behavior causing a module resolve error lol
```
70 |         fallbackBindings = require('@swc/wasm');
                                        ^
error: Could not resolve: "@swc/wasm". Maybe you need to "bun install"?
    at /Users/dave/code/bun/test/node_modules/@swc/core/index.js:70:36
```

**Comment by Jarred-Sumner** [comment]
Fixed as of Bun v1.1.19
```ts
❯ bun-v1.1.19 test test/bundler/bundler_compile.test.ts
bun test v1.1.19 (11084935)

bundler/bundler_compile.test.ts:
569678 |       if (options.sourceMap)
569679 |         result.map = '{"version":3,"sources":[],"names":[],"mappings":""}';
569680 |       return result;
569681 |     };
569682 | 
569683 |     export { $minify2 as minify };
         ^
SyntaxError: Unexpected keyword 'export'
      at <parse> (/$bunfs/root/out:569683:1)

Bun v1.1.19 (macOS arm64)

36 |     },
37 |     run: {
38 |       exitCode: 1,
39 |       validate({ stderr }) {
40 |         console.log(stderr);
41 |         expect(stderr).toInclude("entry.ts:6:19");
                            ^
error: expect(received).toInclude(expected)

Expected to include: "entry.ts:6:19"
Received: "569678 |       if (options.sourceMap)\n569679 |         result.map = '{\"version\":3,\"sources\":[],\"names\":[],\"mappings\":\"\"}';\n569680 |       return result;\n569681 |     };\n569682 | \n569683 |     export { $minify2 as minify };\n         ^\nSyntaxError: Unexpected keyword 'export'\n      at <parse> (/$bunfs/root/out:569683:1)\n\nBun v1.1.19 (macOS arm64)\n"

      at validate (test/bundler/bundler_compile.test.ts:41:24)
      at test/bundler/expectBundled.ts:1637:15
      at test/bundler/expectBundled.ts:576:11
✗ bundler > bun/SourceMapLargeFile [1232.40ms]

 0 pass
 1 fail
 2 expect() calls
Ran 1 tests across 1 files. [1277.00ms]

bun/test on  main [$!?] via 🍞 v1.2.22 
❯ bun-v1.1.18 test test/bundler/bundler_compile.test.ts
bun test v1.1.18 (5a0b9352)

bundler/bundler_compile.test.ts:

951 |             }
952 | 
953 |             return testRef(id, opts);
954 |           }
955 |           if (allErrors.length === 0) {
956 |             throw new Error("Bundle Failed\ncode: " + exitCode + "\nstdout: " + stdout + "\nstderr: " + stderr);
                        ^
error: Bundle Failed
code: null
stdout: 
stderr: 
      at test/bundler/expectBundled.ts:956:19
      at test/bundler/expectBundled.ts:576:11
✗ bundler > bun/SourceMapLargeFile [165.58ms]

 0 pass
 1 fail
Ran 1 tests across 1 files. [208.00ms]
```
