### ISSUE TITLE
Compatibility issue with terminal-kit (node:stream)

### ISSUE THREAD

**Issue by wopian** [oven-sh/bun#13248]
### What version of Bun is running?

1.1.22

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

Install `terminal-kit` (3.1.1) from NPM (`bun add terminal-kit`) and execute the following JavaScript code in Bun (or Node.js to see the correct behaviour)

```js
import kit from 'terminal-kit'

const terminal = kit.terminal

terminal.red('Hello, World!\n')
```

### What is the expected behavior?

`Hello World` printed in red text. This is the behaviour seen when running the code above in Node.js 20.16.0

### What do you see instead?

`Hello World` printed in red text along with an error stack trace where the syscall to `kqueue` had an invalid argument passed to it.

```txt
634 |   //console.log( '\n>>> Action:' , action , '<<<\n' ) ;
635 |   //console.log( 'Attributes:' , attributes ) ;
636 |   if ( action === undefined || action === true ) {
637 |           on = options.onHasFormatting ? options.root.format( ... onFormat ) : options.on ;
638 |           if ( options.str ) { return on ; }
639 |           options.out.write( on ) ;
                    ^
EINVAL: Invalid argument
   errno: -22
 syscall: "kqueue"

      at node:stream:162:43
      at node:stream:171:43
      at applyEscape (/Users/[path]/node_modules/terminal-kit/lib/Terminal.js:639:15)
      at /Users/[path]/node_modules/terminal-kit/lib/Terminal.js:1425:7
      at /Users/[path]/node_modules/terminal-kit/lib/Terminal.js:1421:46
      at /Users/[path]/node_modules/terminal-kit/lib/Terminal.js:523:8
```

**Comment by RADHAsakthivel** [comment]
Question : Is this Error happening for all kernel (OS) or in one OS ??

**Comment by RADHAsakthivel** [comment]
![image](https://github.com/user-attachments/assets/a8d5e9ae-e877-41cd-a03e-d99af0fe79c2)

## I have used "@types/terminal-kit": "^2.5.6" found it's working fine.

**index.ts**
```
import kit from 'terminal-kit'
const terminal = kit.terminal
terminal.red('Hello, World!\n')
```

**Result In Terminal**
```
Hello, World!
```

**Comment by wopian** [comment]
@RADHAsakthivel does it also work with Javascript? Looks like you're using Typescript which I haven't tried above.

**Comment by wopian** [comment]
Output on Bun `1.1.25-canary.20+d4237b075

![image](https://github.com/user-attachments/assets/49add5ce-f782-4f4e-bc11-cf79cf384317)

**Comment by RADHAsakthivel** [comment]
Yes you are right I am using typescript .
Let me check with javascript and get back to you.

**Comment by RADHAsakthivel** [comment]
I am facing issue while setting up the bun canary version setup ``` do this having the issue in bun version 1.1.24 ```

**Comment by wopian** [comment]
This still occurs on canary 1.1.28

**Comment by pcastro-handover** [comment]
same here with `1.1.36+ededc168c` version

**Comment by dukejones** [comment]
Seems to work on bun v1.2.1

**Comment by Jarred-Sumner** [comment]
Fixed in Bun v1.2.0
