### ISSUE TITLE
Bun napi panic

### ISSUE THREAD

**Issue by Miosp** [oven-sh/bun#13253]
### What version of Bun is running?

1.1.22

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64 (also linux on fedora 40)

### What steps can reproduce the bug?

Run my vite dev server with bunx --bun vite dev. After that the dev server starts and displays initial message normally but after opening the link in the browser it crashes.

Unfortunately the bug is not reproducible with bun's vite demo.

### What is the expected behavior?

Dev server serves requests.

### What do you see instead?

thread '<unnamed>' panicked at napi\src\threadsafe_function.rs:235:57:
called `Result::unwrap()` on an `Err` value: Error { status: InvalidArg, reason: "expect Function, got: Object", maybe_raw: 0x0 }
stack backtrace:
   0:     0x7ffc5fd383dd - napi_register_module_v1
   1:     0x7ffc5f558fad - <unknown>
   2:     0x7ffc5fd2dbb1 - napi_register_module_v1
   3:     0x7ffc5fd3a1ca - napi_register_module_v1
   4:     0x7ffc5fd39a99 - napi_register_module_v1
   5:     0x7ffc5fd3a900 - napi_register_module_v1
   6:     0x7ffc5fd3a3f9 - napi_register_module_v1
   7:     0x7ffc5fd3a339 - napi_register_module_v1
   8:     0x7ffc5fd3a322 - napi_register_module_v1
   9:     0x7ffc5fd3c367 - napi_register_module_v1
  10:     0x7ffc5fd3c8b3 - napi_register_module_v1
  11:     0x7ffc5fcffba1 - <unknown>
  12:     0x7ff7688f58c8 - napi_remove_async_cleanup_hook
  13:     0x7ff7688f2cfb - napi_remove_async_cleanup_hook
  14:     0x7ff768497174 - <unknown>
  15:     0x7ff7683c75d5 - <unknown>
  16:     0x7ff76aa8d77b - uv_getnameinfo
  17:     0x7ff76834a975 - <unknown>
  18:     0x7ff7684b0573 - <unknown>
  19:     0x7ff76834e242 - <unknown>
  20:     0x7ff768303aba - <unknown>
  21:     0x7ff768302da0 - <unknown>
  22:     0x7ff7680621bc - <unknown>
  23:     0x7ff76806117b - <unknown>
  24:     0x7ff76ad7e74c - node::RemoveEnvironmentCleanupHook
  25:     0x7ffd3408257d - BaseThreadInitThunk
  26:     0x7ffd3500af28 - RtlUserThreadStart
error: script "dev" exited with code 9

### Additional information

The behavior on my linux machine is the same.

I upgraded from Bun 1.1.17, which had no issues.

**Comment by Jarred-Sumner** [comment]
Does this still occur in Bun v1.1.27?

**Comment by Miosp** [comment]
I think it v1.1.27 fixed the issue both on windows and linux. Nice!

**Comment by Miosp** [comment]
Sorry, for the confusion. It actually still happens. Just this time it is a bit delayed, so in my quick testing the issue did not occur (middle of the night).

**Comment by haxibami** [comment]
I have a similar problem with the following sample project, which uses Astro & lightningcss. 

https://github.com/haxibami/bun-sample

When I remove `lightningcss` or just use `bun run dev` (instead of `bun --bun run dev`), the error disappears. It also doesn't happen with Bun v1.1.20 or lower.

```
thread '<unnamed>' panicked at napi/src/threadsafe_function.rs:235:57:
called `Result::unwrap()` on an `Err` value: Error { status: InvalidArg, reason: "expect Function, got: Object", maybe_raw: 0x0 }
stack backtrace:
   0:      0x98379637713 - <unknown>
   1:      0x98378e47ad0 - <unknown>
   2:      0x9837960b722 - <unknown>
   3:      0x983796391ee - <unknown>
   4:      0x98379638970 - <unknown>
   5:      0x98379639b37 - <unknown>
   6:      0x98379639540 - <unknown>
   7:      0x98379639496 - <unknown>
   8:      0x9837963948f - <unknown>
   9:      0x98378e29414 - <unknown>
  10:      0x98378e298c2 - <unknown>
  11:      0x983795e2dbe - <unknown>
  12:          0x3330fbc - <unknown>
  13:          0x332e94c - <unknown>
  14:          0x2f0fe3a - <unknown>
  15:          0x2e22c15 - <unknown>
  16:          0x3dd9bab - <unknown>
error: script "dev" was terminated by signal SIGABRT (Abort)
zsh: IOT instruction (core dumped)  RUST_BACKTRACE=full bun --bun run dev
```

**Comment by Miosp** [comment]
i use lightning css too, so that may be a good starting point

**Comment by haxibami** [comment]
#13771 (pure Vite + lightningcss) looks similar, but the error seems to be caused by adding `css.lightningcss.visitor` in Vite config, not just using lightningcss (`css.transformer`).

**Comment by eokic** [comment]
Just encountered the same thing on macOS (15.2), Bun (1.1.42) with Astro (5.1) specifically when trying to use LightningCSS 😢. 
`bun dev` works, but `bun --bun dev` throws

```shell
thread '<unnamed>' panicked at napi/src/threadsafe_function.rs:235:57:
called `Result::unwrap()` on an `Err` value: Error { status: InvalidArg, reason: "expect Function, got: Object", maybe_raw: 0x0 }
```

**Comment by kisenaa** [comment]
I got same error with `bunx --bun dev` with Vite + LightningCSS .

```sh
14:25:39 watching for file changes...
thread '<unnamed>' panicked at napi\src\threadsafe_function.rs:235:57:
called `Result::unwrap()` on an `Err` value: Error { status: InvalidArg, reason: "expect Function, got: Object", maybe_raw: 0x0 }
stack backtrace:
   0:     0x7fffcc0ff7b8 - napi_register_module_v1
   1:     0x7fffcb979ffa - <unknown>
   2:     0x7fffcc0f4e37 - napi_register_module_v1
   3:     0x7fffcc101705 - napi_register_module_v1
   4:     0x7fffcc101540 - napi_register_module_v1
   5:     0x7fffcc101b63 - napi_register_module_v1
   6:     0x7fffcc1017e9 - napi_register_module_v1
   7:     0x7fffcc10173f - napi_register_module_v1
   8:     0x7fffcc10172e - napi_register_module_v1
   9:     0x7fffcc115611 - napi_register_module_v1
  10:     0x7fffcc115970 - napi_register_module_v1
  11:     0x7fffcc0cba83 - <unknown>
  12:     0x7ff64be98999 - <unknown>
  13:     0x7ff64bc052bc - <unknown>
  14:     0x7ff64bb0097c - <unknown>
  15:     0x7ff64cc5924b - v8::Number::Value
  16:     0x7ff64ba90dd5 - <unknown>
  17:     0x7ff64bc2969d - <unknown>
  18:     0x7ff64ba93cd6 - <unknown>
  19:     0x7ff64b995add - <unknown>
  20:     0x7ff64b9939bd - <unknown>
  21:     0x7ff64baa00b5 - <unknown>
  22:     0x7ff64b803567 - <unknown>
  23:     0x7ff64b8013b5 - <unknown>
  24:     0x7ff64f28d154 - uv_getnameinfo
  25:     0x7ff81cc3259d - BaseThreadInitThunk
  26:     0x7ff81ef6af78 - RtlUserThreadStart
```

**Comment by kisenaa** [comment]
> I got same error with `bunx --bun dev` with Vite + LightningCSS .
> 
> 14:25:39 watching for file changes...
> thread '<unnamed>' panicked at napi\src\threadsafe_function.rs:235:57:
> called `Result::unwrap()` on an `Err` value: Error { status: InvalidArg, reason: "expect Function, got: Object", maybe_raw: 0x0 }
> stack backtrace:
>    0:     0x7fffcc0ff7b8 - napi_register_module_v1
>    1:     0x7fffcb979ffa - <unknown>
>    2:     0x7fffcc0f4e37 - napi_register_module_v1
>    3:     0x7fffcc101705 - napi_register_module_v1
>    4:     0x7fffcc101540 - napi_register_module_v1
>    5:     0x7fffcc101b63 - napi_register_module_v1
>    6:     0x7fffcc1017e9 - napi_register_module_v1
>    7:     0x7fffcc10173f - napi_register_module_v1
>    8:     0x7fffcc10172e - napi_register_module_v1
>    9:     0x7fffcc115611 - napi_register_module_v1
>   10:     0x7fffcc115970 - napi_register_module_v1
>   11:     0x7fffcc0cba83 - <unknown>
>   12:     0x7ff64be98999 - <unknown>
>   13:     0x7ff64bc052bc - <unknown>
>   14:     0x7ff64bb0097c - <unknown>
>   15:     0x7ff64cc5924b - v8::Number::Value
>   16:     0x7ff64ba90dd5 - <unknown>
>   17:     0x7ff64bc2969d - <unknown>
>   18:     0x7ff64ba93cd6 - <unknown>
>   19:     0x7ff64b995add - <unknown>
>   20:     0x7ff64b9939bd - <unknown>
>   21:     0x7ff64baa00b5 - <unknown>
>   22:     0x7ff64b803567 - <unknown>
>   23:     0x7ff64b8013b5 - <unknown>
>   24:     0x7ff64f28d154 - uv_getnameinfo
>   25:     0x7ff81cc3259d - BaseThreadInitThunk
>   26:     0x7ff81ef6af78 - RtlUserThreadStart

For anyone who still have the error, using lightningcss-wasm solve the issue. I think the problem is bun compatibility with NAPI rs .
