### ISSUE TITLE
bun test segfault

### ISSUE THREAD

**Issue by subtleGradient** [oven-sh/bun#13273]
### How can we reproduce the crash?

I dunno how to mini repro

### Relevant log output

```shell
Run cd frontend; bun test
  cd frontend; bun test
  shell: /usr/bin/bash -e {0}
bun test v1.1.22-canary.96 (df33f2b2)

src/data-stores/RemoteStore.test.ts:
  TERM environment variable not set.
  
  # Unhandled error between tests
  -------------------------------
  
  Error: 
        at new ShellError (12:16)
        at new ShellPromise (72:16)
        at BunShell (187:35)
        at /home/runner/work/v4/v4/frontend/plugins/preload-before-tests.ts:8:11
        at 2:1
        at 2:1
  3 | import { BunPlugin, Loader } from "bun"
  4 | import { afterAll, beforeAll, mock } from "bun:test"
  5 | // eslint-disable-next-line no-restricted-imports
  6 | 
  7 | // @ts-expect-error -- top level await without a separate tsconfig for tests. Remove this if we add a test tsconfig
  8 | await Bun.$`clear`
                     ^
  ShellError: Failed with exit code 1
   info: {
    "exitCode": 1,
    "stderr": "TERM environment variable not set.\n",
    "stdout": ""
  }
  
        at new ShellError (12:16)
        at new ShellPromise (72:16)
        at BunShell (187:35)
        at /home/runner/work/v4/v4/frontend/plugins/preload-before-tests.ts:8:11
  -------------------------------
  
  
src/data-stores/AsyncStore.test.ts:
src/map/measureGlobularDistance.test.ts:

src/map/map-math.test.ts:

src/lib/Store.test.ts:
  ============================================================
  Bun Canary v1.1.22-canary.96 (df33f2b2) Linux x64 (baseline)
  Linux Kernel v6.5.0 | glibc v2.35
  CPU: sse42 popcnt avx avx2
  Args: "bun" "test"
  Features: jsc Bun.stderr Bun.stdout bunfig shell(2) spawn tsconfig_paths tsconfig(2) 
  Elapsed: 170ms | User: 172ms | Sys: 12ms
  RSS: 1.01GB | Peak: 121.63MB | Commit: 1.01GB | Faults: 0
  
  panic(main thread): Segmentation fault at address 0xC
  oh no: Bun has crashed. This indicates a bug in Bun, not your code.
  
  To send a redacted crash report to Bun's team,
  please file a GitHub issue using the link below:
  
   https://bun.report/1.1.22/Bt2df33f2bA2iggmDu+6/iE+xyQ_ksuh5Dksuh5D__ksuh5D+7+54Dkm3u3EA2AY
  
  /home/runner/work/_temp/a3cd300b-9ec2-484e-ba81-d8ad984f6951.sh: line 1:  2049 Illegal instruction     (core dumped) bun test
```

### Stack Trace (bun.report)

Bun v1.1.22 ([`df33f2b`](<https://github.com/oven-sh/bun/tree/df33f2b2a264912c7a742d0c03587082415fbba6>)) on linux x86_64_baseline [TestCommand]

Segmentation fault at address 0x0000000C

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/ld-temp.o#L0>): `llint_op_call`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/ld-temp.o#L0>): `llint_op_call`
- *2 unknown/js code*
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/ld-temp.o#L0>): `llint_op_call`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/ld-temp.o#L0>): `llint_call_javascript`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/ld-temp.o#L0>): `JSC::Interpreter::executeCall`

**Comment by subtleGradient** [comment]
could be related to some react native thing

**Comment by Jarred-Sumner** [comment]
most likely, we are not checking for pending exceptions in a spot we need to check for pending exceptions

**Comment by subtleGradient** [comment]
ya, I updated my mocks to make it stop importing react-native and it solved the segfault
