### ISSUE TITLE
Double parsing cornercase

### ISSUE THREAD

**Issue by carlopi** [oven-sh/bun#133]
Somehow curious case:

```
var Z = new Float64Array([9.9999999999999998E+23]);
```
gives:
```
SyntaxError: Decimal integer literals with a leading zero are forbidden in strict mode
      at /home/carlo/work/bun/strict.js:2:0
```
while working in other engines (even jsc).

**Comment by Jarred-Sumner** [comment]
Yeah, this is definitely a printer bug

This is the output:

```js
var Z = new Float64Array([000000000000000000000000]);
```

**Comment by TimWillebrands** [comment]
Yeah I'm getting this as well on packages using lib0:
```5 |  */
 6 | 
 7 | import * as math from './math.js'
 8 | 
 9 | export const yotta = 1e24
10 | export const zetta = 1e21
           ^
 SyntaxError: Decimal integer literals with a leading zero are forbidden in strict mode
      at /-snip-/server-bun/node_modules/lib0/metric.js:10:7
```

Changing it to this:
``` 9 | export const yotta  = 1000000000000000000000000
10 | export const zetta  = 1000000000000000000000
           ^
 SyntaxError: Decimal integer literals with a leading zero are forbidden in strict mode
      at /-snip-/server-bun/node_modules/lib0/metric.js:10:7
```

Doesn't seem to help

**Comment by Electroid** [comment]
As of `0.2.2`, this appears to be fixed. Feel free to comment if you can still reproduce it.

```js
var Z = new Float64Array([9.9999999999999998E+23]);
console.log(Z); // => Float64Array(1) [ 1000000000000000000000000 ]
export const zetta = 1e21
console.log(zetta); // => 1000000000000000000000
```
