### ISSUE TITLE
`@eslint/eslintrc` `FlatCompat` / `import-fresh` throws an error in Bun

### ISSUE THREAD

**Issue by controversial** [oven-sh/bun#13346]
### What version of Bun is running?

1.1.24+85a329911

### What platform is your computer?

Darwin 24.1.0 arm64 arm

### What steps can reproduce the bug?

module.parent or module.main or module.children properties are always undefined 

---

The `FlatCompat` class exported by `@eslint/eslintrc` is designed to help “legacy” eslint configs (pre-flat config) work with eslint 9+.

The following produces an error in bun:
```ts
import { FlatCompat } from '@eslint/eslintrc';
const compat = new FlatCompat();
const config = compat.extends('eslint-config-airbnb'); // or any “legacy” eslint config
console.log(config);
```

### What is the expected behavior?

```js
// node test.js
[
  {
    rules: {
      'accessor-pairs': 'off',
      'array-callback-return': [Array],
      'block-scoped-var': 'error',
      complexity: [Array],
      'class-methods-use-this': [Array],
      'consistent-return': 'error',
      curly: [Array],
      'default-case': [Array],
...
```

### What do you see instead?

An error from within the [`import-fresh`](https://www.npmjs.com/package/import-fresh) module

```
// bun test.js

27 | 
28 |    delete require.cache[filePath]; // Delete module from cache
29 | 
30 |    const parent = require.cache[parentPath]; // If `filePath` and `parentPath` are the same, cache will already be deleted so we won't get a memory leak in next step
31 | 
32 |    return parent === undefined ? require(filePath) : parent.require(filePath); // In case cache doesn't have parent, fall back to normal require
                                                               ^
TypeError: Cannot read config file: /Users/luke/Developer/misc/bun-eslint-compat/node_modules/eslint-config-airbnb/index.js
Error: parent.require is not a function. (In 'parent.require(filePath)', 'parent.require' is undefined)
Referenced from: 
      at /Users/luke/Developer/misc/bun-eslint-compat/node_modules/import-fresh/index.js:32:59
      at loadJSConfigFile (/Users/luke/Developer/misc/bun-eslint-compat/node_modules/@eslint/eslintrc/lib/config-array-factory.js:237:16)
      at _loadConfigData (/Users/luke/Developer/misc/bun-eslint-compat/node_modules/@eslint/eslintrc/lib/config-array-factory.js:638:42)
      at _loadExtends (/Users/luke/Developer/misc/bun-eslint-compat/node_modules/@eslint/eslintrc/lib/config-array-factory.js:810:25)
      at _normalizeObjectConfigDataBody (/Users/luke/Developer/misc/bun-eslint-compat/node_modules/@eslint/eslintrc/lib/config-array-factory.js:749:25)
      at _normalizeObjectConfigData (/Users/luke/Developer/misc/bun-eslint-compat/node_modules/@eslint/eslintrc/lib/config-array-factory.js:694:20)
      at create (/Users/luke/Developer/misc/bun-eslint-compat/node_modules/@eslint/eslintrc/lib/config-array-factory.js:489:20)
      at config /Users/luke/Developer/misc/bun-eslint-compat/node_modules/@eslint/eslintrc/lib/flat-compat.js:247:47)
      at/Users/luke/Developer/misc/bun-eslint-compat/eslint/bun.js:3:23

Bun v1.1.24 (macOS arm64)
```

**Comment by alex-demchenko** [comment]
still exists in 1.1.33
it blocks for use ESLint 9

**Comment by Yasamato** [comment]
For context:
```shell
$ bunx --bun eslint .

Oops! Something went wrong! :(

ESLint: 9.13.0

TypeError: Cannot read config file: /node_modules/eslint-config-next/core-web-vitals.js
Error: parent.require is not a function. (In 'parent.require(filePath)', 'parent.require' is undefined)
```

File content: `node_modules/eslint-config-next/core-web-vitals.js`:
```js
module.exports = {
  extends: [require.resolve('.'), 'plugin:@next/next/core-web-vitals'],
}
```

Directly running `bun --bun ./node_modules/eslint-config-next/core-web-vitals.js` gives no errror.

Minimal setup to reproduce:
```js
// eslint.config.mjs
import { FlatCompat } from "@eslint/eslintrc";
const compat = new FlatCompat();

export default [...compat.extends("next/core-web-vitals")];

```

package.json:
```json
{
  "devDependencies": {
    "@eslint/eslintrc": "^3.1.0",
    "eslint-config-next": "^15.0.1"
  }
}
```

Now run: `bun install && bunx --bun eslint .`

**Comment by xHeaven** [comment]
Apparently running `bun run lint` in a Nextjs project _is_ working. However, if you do `bun --bun run lint`, it will fail.

With `bun run lint`, [parent](https://github.com/sindresorhus/import-fresh/blob/main/index.js#L30) resolves to `undefined`.

However, with `bun --bun run lint`, [parent](https://github.com/sindresorhus/import-fresh/blob/main/index.js#L30) resolves to
```ts
Module {
  exports: Module {
    ConfigArrayFactory: [class ConfigArrayFactory],
    createContext: [Function: createContext],
    loadConfigFile: [Function: loadConfigFile],
  },
  _compile: [Function: _compile],
  children: [],
  filename: "/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js",
  id: "/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js",
  loaded: true,
  parent: undefined,
  path: "/app/node_modules/@eslint/eslintrc/lib",
  paths: [ "/app/node_modules", "/node_modules" ],
}
```

The latter is... kinda right, though? I mean that _is_ the parent (which, if I understand correctly, is the caller).

Is it possible that this should be resolved in the `import-fresh` package itself?

They could do:
```js
// instead of this
return parent === undefined ? require(filePath) : parent.require(filePath);

// do this, which fixes the issue
return parent?.require === undefined ? require(filePath) : parent.require(filePath);
```

Thoughts?

**Comment by andrejak** [comment]
We're hitting this too, is there any plan for a fix?

**Comment by exoRift** [comment]
This may have been inadvertently fixed in a recent patch. I don't run into this issue on `1.2.14+6a363a38d`. I can't seem to narrow it down to a specific release, though.

**Comment by sebdanielsson** [comment]
Not encountering this issue any longer. Running latest Next.js stable and eslint directly instead of next-lint.

**Comment by robobun** [comment]
## Status: ALREADY FIXED

The core issue reported - that `module.parent`, `module.children`, and `parent.require` were undefined/broken - has been fixed in the current Bun codebase.

## Issue Description

The reporter described that using `@eslint/eslintrc`'s `FlatCompat` class would throw an error because the `import-fresh` module calls `parent.require(filePath)` on a module object from `require.cache`, and that call failed because `parent.require` was `undefined`.

The error was:
```
TypeError: parent.require is not a function
```

## Reproduction Steps and Results

### Test 1: `module.parent` and `module.children`

**child.cjs:**
```js
module.exports = { hello: "world" };
```

**main.cjs:**
```js
console.log("module.parent:", module.parent);
console.log("module.children:", module.children);
require('./child.cjs');
console.log("module.children after require:", module.children.length, "children");
```

**Result with bun-debug (v1.3.10):**
```
module.parent: null
module.children: []
module.children after require: 1 children
```

All three properties work correctly now.

### Test 2: `import-fresh` pattern (the exact failing pattern from the issue)

```js
const filePath = require.resolve('./child.cjs');
const parentPath = __filename;

// First require to populate cache
require(filePath);

// Delete from cache (import-fresh does this)
delete require.cache[filePath];

// Get parent from cache
const parent = require.cache[parentPath];

console.log("parent exists:", parent !== undefined);
console.log("parent.require exists:", typeof parent?.require === 'function');

// This is the line that was failing in the issue
const result = parent.require(filePath);
console.log("parent.require() result:", result);
```

**Result with bun-debug (v1.3.10):**
```
parent exists: true
parent.require exists: true
parent.require() result: { hello: "world" }
PASS: import-fresh pattern works
```

The `parent.require(filePath)` call now works correctly.

## Version Tested

- Bun debug build v1.3.10 (commit 6a8f33e7b1)
- The issue was originally reported against Bun v1.1.24

## Relevant Code Locations

- `src/bun.js/bindings/JSCommonJSModule.cpp` - C++ implementation where `module.require` is created as a bound function during `evaluateCommonJSModuleOnce` (lines 134-143)
- `src/bun.js/bindings/JSCommonJSModule.h` - Header with `m_parent`, `m_children` fields
- `src/js/builtins/CommonJS.ts` - JavaScript builtins for CommonJS including `require.cache` proxy
---
*This is an automated comment.*
