### ISSUE TITLE
quick.db (`LoadLibrary failed: A dynamic link library (DLL)`)

### ISSUE THREAD

**Issue by JazzyArmando1234** [oven-sh/bun#13368]
### How can we reproduce the crash?

```js
const { QuickDB } = require("quick.db");
const db = new QuickDB({filePath: "db.sqlite"});
```

### Relevant log output

```shell
107 |         return opts[p] || p;
108 |       })
109 |     );
110 |     tries.push(n);
111 |     try {
112 |       b = opts.path ? requireFunc.resolve(n) : requireFunc(n);
                                                     ^
TypeError: LoadLibrary failed: A dynamic link library (DLL) in
      at bindings (C:\Users\armir\Desktop\jmk\node_modules\bindings\bindings.js:112:48)
      at new Database (C:\Users\armir\Desktop\jmk\node_modules\better-sqlite3\lib\database.js:48:29)
      at Database (C:\Users\armir\Desktop\jmk\node_modules\better-sqlite3\lib\database.js:11:10)
      at new SqliteDriver (C:\Users\armir\Desktop\jmk\node_modules\quick.db\out\drivers\SqliteDriver.js:12:26)
      at new QuickDB (C:\Users\armir\Desktop\jmk\node_modules\quick.db\out\index.js:29:28)
      at C:\Users\armir\Desktop\jmk\index.js:39:12

Bun v1.1.24 (Windows x64)
```

### Stack Trace (bun.report)

Bun v1.1.24 ([`85a3299`](<https://github.com/oven-sh/bun/tree/85a32991152871b06becd6b411eb663008369769>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x7FFE28163540

- *1 unknown/js code*
- ??? at `0x5f3b5` in ntdll.dll
- ??? at `0x5f0ab` in ntdll.dll
- ??? at `0x5ef8d` in ntdll.dll
- ??? at `0x1e3eb` in KERNEL32.DLL
- [`exit.cpp:137`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/src/appcrt/startup/exit.cpp#L137>): `exit_or_terminate_process`
- [`exit.cpp:274`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/src/appcrt/startup/exit.cpp#L274>): `common_exit`
- [`Global.zig:121`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/src/Global.zig#L121>): `exit`
- [`javascript.zig:1267`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/src/bun.js/javascript.zig#L1267>): `globalExit`
- [`javascript.zig:1179`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/src/bun.js/javascript.zig#L1179>): `eventLoop`

**Comment by mrxbox98** [comment]
Bun doesn't support ``better-sqlite3`` which is what quickdb uses https://github.com/oven-sh/bun/issues/4290

**Comment by CoconutDev13** [comment]
Will that be fixed in future?
