### ISSUE TITLE
`node:readline` and `process.stdin` aren't working as expected on macOS when stdin is piped from parent process

### ISSUE THREAD

**Issue by yukiisbored** [oven-sh/bun#13374]
### What version of Bun is running?

1.1.24+85a329911

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

1. Use the following example sidecar code:
   ```typescript
   import readline from 'node:readline'

   const rl = readline.createInterface({
       input: process.stdin,
       output: process.stdout,
       terminal: false,
   });

   rl.on('line', (line: string) => {
       process.stdout.write(`${line}\n`);
   })

   console.error("Sidecar started");
   ```

2. Use the following example Python driver code:
    ```python3
    from os.path import dirname, join
    import subprocess

    def main():
        # Replace sidecar.ts to whatever you named the sidecar file.
        sidecar_path = join(dirname(__file__), 'sidecar.ts')
        p = subprocess.Popen(['bun', 'run', sidecar_path], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        p.stdin.write(b'hello\n')
        p.stdin.flush()

        for line in p.stdout:
            print(line.decode('utf-8'))
            p.stdin.write(line)
            p.stdin.flush()

    if __name__ == '__main__':
        main()
    ```

3. Run the python driver
    ```console
    $ python driver.py
    ```

There's a more complex driver code in Rust as this bug was originally observed when using Bun as the runtime for a backend running as a [Tauri sidecar](https://tauri.app/v1/guides/building/sidecar/).

https://github.com/yukiisbored/rust-bun-stdio-tests

The code is above is lifted from the Tauri project: https://github.com/tauri-apps/tauri/blob/2b61447dfc167ec11724f99671bf9e2de0bf6768/core/tauri/src/api/process/command.rs

### What is the expected behavior?

On Windows and Linux, It outputs a never ending barrage of `hello`.

```console
yuki@ubuntu % python3 driver.py
hello

hello

hello

hello

hello

^CTraceback (most recent call last):
  File "/home/yuki/projects/rust-bun-stdio-tests/driver.py", line 16, in <module>
    main()
  File "/home/yuki/projects/rust-bun-stdio-tests/driver.py", line 10, in main
    for line in p.stdout:
KeyboardInterrupt
```

On macOS, when Node.js is used instead of Bun, it also outputs a never ending barrage of `hello`.

```patch
- p = subprocess.Popen(['bun', 'run', sidecar_path], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
+ p = subprocess.Popen(['npx', 'tsx', sidecar_path], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```

```console
yuki@macos % python3 driver.py
hello

hello

hello

hello

hello

^CTraceback (most recent call last):
  File "/Users/yuki/projects/rust-bun-stdio-tests/driver.py", line 16, in <module>
    main()
  File "/Users/yuki/projects/rust-bun-stdio-tests/driver.py", line 10, in main
    for line in p.stdout:
KeyboardInterrupt
```

### What do you see instead?

On macOS, when using Bun, nothing happens.

```console
yuki@macos % python3 driver.py

```

### Additional information

- Tried the Bun-specific `process.stdin` API as mentioned in the [Read from stdin](https://bun.sh/guides/process/stdin) guide, no difference.

**Comment by axelson** [comment]
Are there any workarounds for this? This is keeping us stuck on Bun 1.0.26.

**Comment by vladfaust** [comment]
Same issue here.

**Comment by HuakunShen** [comment]
Same issue for me (Bun 1.2.5)
Related issue #10080 

My issue: https://github.com/kunkunsh/kkrpc/issues/11
Trying to write to bun process's stdin, but doesn't work on MacOS.
Deno and NodeJS work on all 3 platforms, Bun works on Windows and Ubuntu, but not MacOS.
