### ISSUE TITLE
Bun 1.1.24 can't run expo project

### ISSUE THREAD

**Issue by leosilberg** [oven-sh/bun#13390]
### What version of Bun is running?

1.1.24

### What platform is your computer?

Windows 11 10.0.22631

### What steps can reproduce the bug?

```
git clone https://github.com/mrzachnugent/react-native-reusables.git

cp -R react-native-reusables/apps/starter-base/ ./my-project

cd my-project && bun install

bun run web
```

### What do you see instead?

```
Starting Metro Bundler
warning: Bundler cache is empty, rebuilding (this may take a minute)
› Detected a change in babel.config.js. Restart the server to see the new results. You may need to clear the bundler cache with the --clear flag for your changes to take effect.
TypeError [ERR_INVALID_ARG_TYPE]: The "streamReadable" argument must be an stream.Readable. Received an instance of Pipeline
TypeError: The "streamReadable" argument must be an stream.Readable. Received an instance of Pipeline
    at new NodeError (node:stream:420:19)
    at newReadableStreamFromStreamReadable (node:stream:2527:41)
    at new Response (node-fetch:48:13)
    at new NFCResponse (C:\Users\...\my-project\node_modules\@expo\cli\build\src\api\rest\cache\response.js:21:8)  
    at C:\Users\...\my-project\node_modules\@expo\cli\src\api\rest\cache\wrapFetchWithCache.ts:194:7
    at processTicksAndRejections (unknown:12:39)
error: script "android" exited with code 1
```

**Comment by robobun** [comment]
Same bug as #8487: Bun's node-fetch polyfill Response constructor calls Readable.toWeb() on any body that is a legacy Stream, so the minipass/cacache `Pipeline` that node-fetch-cache passes to `new Response()` fails with `The "streamReadable" argument must be an stream.Readable. Received an instance of Pipeline` (newReadableStreamFromStreamReadable -> new Response (node-fetch:48) -> new NFCResponse). The Expo failure here goes through @expo/cli's vendored copy of node-fetch-cache, so the fix tracked in #8487 covers it.

Duplicate of #8487

Please add a 👍 or any extra details over there so it all stays in one place. If this is actually a different problem, say so here and we'll reopen.
