### ISSUE TITLE
Unsupported proper logging of AggregateError, Error.cause, modified/accessed Error.stack

### ISSUE THREAD

**Issue by jhmaster2000** [oven-sh/bun#1352]
### Version

`0.6.3`

### Platform

`Linux DESKTOP-A7ND7QS 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### What steps will reproduce the bug?

The following file is `stuff.ts`, displaying the problem of simply accessing `%Error%.stack` causing it to break when logged.
```ts
function getError(msg) {
    return new Error(msg);
}
const err = new Error("A");
const err2 = getError("B");
// With the line below commented out, the stacks will be normal
console.log(void err.stack, void err2.stack);
console.error(err); // expect "at /.../stuff.ts:4:12", get "at /.../stuff.ts:5:22"
console.error(err2);
// expect:
// "at getError (/.../stuff.ts:2:11)
//  at /.../stuff.ts:5:13"
// get:
// "at /.../stuff.ts:2:24"
```
By replacing `console.log(void err.stack, void err2.stack);` line with `err.stack = err2.stack;` we can also see the fact that stack modifications are not respected. (and still trigger the original stack breaking)

By replacing that line with `err2.cause = err;` we can see `%Error%.cause` simply doesn't get printed at all in logged errors.

The following file is `aggregate.ts`
```ts
const aggregate = new AggregateError(
    [new Error('Error 1'), new Error('Error 2')],
    'Aggregate error message.',
    { cause: new Error('Cause') }
);
throw aggregate;
```
Running it in Bun is 99% equivalent to the following file:
```ts
const errors = [new Error('Error 1'), new Error('Error 2')];
console.error(errors[0]);
throw errors[1];
```
given that Bun currently does not display the AggregateError itself, it's message, cause or stack.

### Additional information

Updated for Bun v0.6.3 (issue persists)

**Comment by exoRift** [comment]
`AggregateError` still does not log to the console properly. It drops important information

Bun 1.2.10
