### ISSUE TITLE
`AbortController` doesn't abort within `bun test` (`WebSocket` & `throw new Error`)

### ISSUE THREAD

**Issue by bogeychan** [oven-sh/bun#13554]
### What version of Bun is running?

1.1.26

### What platform is your computer?

WSL Ubuntu

### What steps can reproduce the bug?

```ts
// test.test.ts
import { test } from "bun:test";

export const wsOpen = (ws: WebSocket) =>
  new Promise((resolve) => ws.addEventListener("open", resolve));

export const wsClose = async (ws: WebSocket) =>
  new Promise<CloseEvent>((resolve) => ws.addEventListener("close", resolve));

export const wsMessage = (ws: WebSocket) => {
  return new Promise<MessageEvent>((resolve, reject) => {
    const controller = new AbortController();
    controller.signal.onabort = () => reject("nope");
    ws.addEventListener("message", resolve, {
      signal: controller.signal,
      once: true,
    });
    setTimeout(() => controller.abort(), 1_000);
  });
};

async function run() {
  const server = Bun.serve({
    port: 0,
    fetch(request, server) {
      if (request.url.endsWith("/ws")) {
        if (server.upgrade(request)) {
          return;
        }
      }
      return new Response("Not Found", { status: 404 });
    },
    websocket: {
      message() {
        throw new Error("nope");
      },
    },
  });

  try {
    const ws = new WebSocket(`ws://${server.hostname}:${server.port}/ws`);

    await wsOpen(ws);

    const message = wsMessage(ws);
    ws.send("yay");

    console.log("await");
    await message;
    console.log("received");

    await wsClose(ws);
  } finally {
    server.stop(true);
  }
}

if (process.env.NODE_ENV === "test") {
  test("...", async () => {
    await run();
  });
} else {
  await run();
}
```

Run `bun test` and `bun run ./test.test.ts`

### What is the expected behavior?

both timeout with console output of:

```bash
await
29 |       }
30 |       return new Response("Not Found", { status: 404 });
31 |     },
32 |     websocket: {
33 |       message() {
34 |         throw new Error("nope");
                   ^
error: nope
      at message (/bogeychan/test/test.test.ts:34:15)
error: nope
```

### What do you see instead?

`bun test` **process doesn't terminate** and console output:

```bash
test.test.ts:
await
29 |       }
30 |       return new Response("Not Found", { status: 404 });
31 |     },
32 |     websocket: {
33 |       message() {
34 |         throw new Error("nope");
                   ^
error: nope
      at message (/bogeychan/test/test.test.ts:34:15)
✗ ... [4.46ms]
```

### Additional information

Idk if it's intended but `AbortSignal.timeout` doesn't work in `onmessage` signal with both `bun test` and `bun run`:

_just replace above function with this_

```ts
export const wsMessage = (ws: WebSocket) => {
  return new Promise<MessageEvent>((resolve, reject) => {
    const signal = AbortSignal.timeout(1_000);
    signal.onabort = () => reject("nope");
    ws.addEventListener("message", resolve, {
      signal,
      once: true,
    });
  });
};
```

**Comment by robobun** [comment]
## Status: ALREADY FIXED

The issue reported that `AbortController` doesn't abort within `bun test` when used with WebSocket event listeners, causing the process to hang. This was reported on Bun v1.1.26.

## Testing Environment

- **Bun version**: v1.3.10-debug+6a8f33e7b (current main branch)
- **Platform**: Linux arm64

## What Was Tested

### Test Case 1: AbortController with setTimeout (original issue)

Used the exact code from the issue. The test creates a WebSocket server, connects to it, sends a message (which triggers a `throw new Error("nope")` in the server), and uses `AbortController` with `setTimeout(() => controller.abort(), 1_000)` to timeout after 1 second.

**`bun run` result**: Works correctly - aborts after ~1s, exits with code 1. Output shows "await" followed by the error and rejection.

**`bun test` result**: Works correctly now - completes in ~4.4 seconds, exits with code 1. Shows test failure (expected behavior since the promise rejects) and the process terminates cleanly. **Does NOT hang.**

### Test Case 2: AbortSignal.timeout variant

Replaced `AbortController` + `setTimeout` with `AbortSignal.timeout(1_000)`.

**`bun run` result**: Works correctly - same as Test Case 1.

**`bun test` result**: Works correctly - completes and terminates. **Does NOT hang.**

### Test Case 3: With expect().rejects

Modified the test to properly catch the rejection with `await expect(message).rejects.toBe("nope")`. The abort fires correctly and the rejection is caught. Output shows "rejected as expected", confirming the abort mechanism works properly.

## Conclusion

The bug described in the issue (bun test process doesn't terminate when AbortController.abort() is called) is no longer reproducible on the current main branch (v1.3.10). The issue appears to have been fixed between v1.1.26 and v1.3.10. Several relevant commits exist in the git history that may have contributed to the fix, including work on AbortController/AbortSignal, WebSocket abort handling, and fetch abort signal fixes.
---
*This is an automated comment.*
