### ISSUE TITLE
Crash in @azure/identity or openai lib (related to AbortController)

### ISSUE THREAD

**Issue by randompixel** [oven-sh/bun#13621]
### What version of Bun is running?

1.1.26+0a37423ba

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

I initially added this to #9429 but I'm not sure if that's being looked at any more.

There seems to be an issue with [@azure/identity](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/identity/identity/README.md) package (all the latest versions including beta) where you can call `getBearerTokens()` once and it works, but try and call it a second time and it causes an invisible server hang (as in, `bun dev` is still running but any HTTP request gives connection refused)

The newest AzureOpenAI library is deprecated auth via an API key and moving to using @azure/identity for keys so this stops migration to the latest versions of things.

```javascript
# index.ts
import { DefaultAzureCredential, getBearerTokenProvider } from "@azure/identity";
import { AzureOpenAI } from "openai";
import type { ChatCompletionMessageParam } from "openai/src/resources/index.js";

try {
  Bun.serve({
    async fetch() {
      try {
         const azureADTokenProvider = getBearerTokenProvider(
	  new DefaultAzureCredential(),
	  "https://cognitiveservices.azure.com/.default",
	);
	const endpoint = "<your-azure-deployment-url>";
	const deployment = "<your-azure-deploymentId>";
	const apiVersion = "2024-05-01-preview";
        const backend = new AzureOpenAI({ azureADTokenProvider, endpoint, apiVersion, deployment });
	const messages: ChatCompletionMessageParam[] = [
		{ role: "user", content: "Hello" },
	]
				
	const response = await backend?.chat.completions.create({ messages });
				
	return Response.json(response);
    } catch (error) {
	console.error("Local");
	console.error(error);
	return Response.json(error);
   }
    }, error(error) {
      console.error("Fetch Handler");
      return new Response(`<pre>${error}\n${error.stack}</pre>`, {
				headers: {
					"Content-Type": "text/html",
				},
			});
    }
  });
} catch (error) {
	console.error("Global");
	console.error(error);
}
```

If you run `bun run index.ts` above once entering your own endpoint, deployment and suitable `DefaultAzureCredential`, first time it'll work then the next request it'll crash. None of the catch statements are hit, nor the fetch error handler are hit 

The library seems to use it's own AbortController. I have yet to find any workaround for this. I tried using different `fetch` or `node-fetch` libraries, or passing in a different AbortControllers but the same issue.

### What is the expected behavior?

The code returns a correct response every time and doesn't crash (or is at least catchable!)

### What do you see instead?

```
21 |  * }
22 |  * ```
23 |  */
24 | class AbortError extends Error {
25 |     constructor(message) {
26 |         super(message);
             ^
AbortError: The operation was aborted.
      at new AbortError (/.../<app>/app/node_modules/@azure/identity/node_modules/@azure/abort-controller/dist/commonjs/AbortError.js:26:9)
      at /.../<app>/app/node_modules/@azure/identity/node_modules/@azure/core-rest-pipeline/dist/commonjs/nodeHttpClient.js:282:25
      at abort (native:1:1)
      at /.../<app>/app/node_modules/@azure/identity/node_modules/@azure/core-rest-pipeline/dist/commonjs/nodeHttpClient.js:134:26
```

Followed by `Connection Refused`

**Comment by randompixel** [comment]
Just updated to all the latest package versions and bun `1.1.27+267afa293` but still seeing the issue with the minimal test case above.

```
bun update v1.1.27 (267afa29)

↑ @biomejs/biome 1.8.3 → 1.9.0
↑ @types/bun 1.1.8 → 1.1.9
↑ @azure/openai 2.0.0-beta.1 → 2.0.0-beta.2
↑ @elysiajs/cors 1.1.0 → 1.1.1
↑ elysia 1.1.8 → 1.1.12
↑ openai 4.56.1 → 4.60.0

+ bun-types@1.1.27
```

**Comment by Hazmi35** [comment]
Can confirm on Windows 11, x64. Bun version 1.0.29. AbortError coming from Azure SDK. Also couldn't catch the error
