### ISSUE TITLE
Bun complains about duplicated import

### ISSUE THREAD

**Issue by FelixZY** [oven-sh/bun#13715]
https://github.com/oven-sh/bun/blob/5108e3e0d9f7806c3884e5a678a81dedd61791bc/test/js/node/http/node-http.test.ts#L15-L17

```
bun test v1.1.26 (0a37423b)

my.test.js:

# Unhandled error between tests
-------------------------------
17 | import { createServer as createHttpsServer } from "node:https";
              ^
error: "createHttpsServer" has already been declared
    at /<redacted>/my.test.js:17:10

15 | import https, { createServer as createHttpsServer } from "node:https";
                     ^
note: "createHttpsServer" was originally declared here
   at /<redacted>/my.test.js:15:17
-------------------------------


 0 pass
 1 fail
 1 error
Ran 1 tests across 1 files. [9.00ms]
```

**Comment by sequencerr** [comment]
i guess line 17 is redundant

**Comment by Jarred-Sumner** [comment]
so you're right, but i'm not able to reproduce it throwing an error at start for some reason.

**Comment by RiskyMH** [comment]
> so you're right, but i'm not able to reproduce it throwing an error at start for some reason.

I can reproduce if the file is `.js` and not `.ts` (it must deduplicate in typescript)
