### ISSUE TITLE
Random Segfault running a ts script

### ISSUE THREAD

**Issue by KholdStare** [oven-sh/bun#13739]
### How can we reproduce the crash?

I was running an internal typescript script (cannot share the script or project). It seems somewhat random, perhaps some uninitialized variable somewhere. One time it ran fine, most times there is a Segfault, and one time I got an intelligible backtrace (will include it in the log output below).

Perhaps could be related to the keccak npm library https://github.com/cryptocoinjs/keccak/tree/master . It seems to use some C code , so perhaps there is a bug hiding there.

From the bun.lock file, here are the versions of the libraries that caused the error:

```
keccak@^3.0.0:
  version "3.0.4"
  resolved "https://registry.npmjs.org/keccak/-/keccak-3.0.4.tgz"
  integrity sha512-3vKuW0jV8J3XNTzvfyicFR5qvxrSAGl7KIhvgOu5cmWwM7tZRj3fMbj/pfIf4be7aznbc+prBWGjywox/g2Y6Q==
  dependencies:
    node-addon-api "^2.0.0"
    node-gyp-build "^4.2.0"
    readable-stream "^3.6.0"

ethereum-cryptography@^0.1.3:
  version "0.1.3"
  resolved "https://registry.npmjs.org/ethereum-cryptography/-/ethereum-cryptography-0.1.3.tgz"
  integrity sha512-w8/4x1SGGzc+tO97TASLja6SLd3fRIK2tLVcV2Gx4IB21hE19atll5Cq9o3d0ZmAYC/8aw0ipieTSiekAea4SQ==
  dependencies:
    keccak "^3.0.0"
    pbkdf2 "^3.0.17"
    blakejs "^1.1.0"
    hash.js "^1.1.7"
    bs58check "^2.1.2"
    scrypt-js "^3.0.0"
    secp256k1 "^4.0.1"
    create-hash "^1.2.0"
    create-hmac "^1.1.7"
    randombytes "^2.1.0"
    safe-buffer "^5.1.2"
    setimmediate "^1.0.5"
    "@types/pbkdf2" "^3.0.0"
    browserify-aes "^1.2.0"
    "@types/secp256k1" "^4.0.1"

ethereumjs-util@^7.0.3:
  version "7.1.5"
  resolved "https://registry.npmjs.org/ethereumjs-util/-/ethereumjs-util-7.1.5.tgz"
  integrity sha512-SDl5kKrQAudFBUe5OJM9Ac6WmMyYmXX/6sTmLZ3ffG2eY6ZIGBes3pEDxNN6V72WyOw4CPD5RomKdsa8DAAwLg==
  dependencies:
    "@types/bn.js" "^5.1.0"
    bn.js "^5.1.2"
    create-hash "^1.1.2"
    ethereum-cryptography "^0.1.3"
    rlp "^2.2.4"

"@openzeppelin/upgrades-core@1.24.0":
  version "1.24.0"
  resolved "https://registry.npmjs.org/@openzeppelin/upgrades-core/-/upgrades-core-1.24.0.tgz"
  integrity sha512-lXf1tUrCZ3Q/YmWhw0cuSSOHMp0OAsmeOg1fhSGEM6nQQ6cIVlFvq2pCV5hZMb7xkOm5pmmzV8JW1W3kfW6Lfw==
  dependencies:
    cbor "^8.0.0"
    chalk "^4.1.0"
    debug "^4.1.1"
    solidity-ast "^0.4.15"
    ethereumjs-util "^7.0.3"
    proper-lockfile "^4.1.1"
    compare-versions "^5.0.0"
```

### Relevant log output

The one time it didn't crash, and gave a reasonable backtrace:

```shell
8 |     this._capacity = capacity
 9 |     this._delimitedSuffix = delimitedSuffix
10 |     this._hashBitLength = hashBitLength
11 |     this._options = options
12 |
13 |     this._state = new KeccakState()
                       ^
TypeError: Object is not a constructor (evaluating 'new KeccakState')
      at new Keccak (REDACTED/node_modules/keccak/lib/api/keccak.js:13:19)
      at REDACTED/node_modules/keccak/lib/api/index.js:12:32
      at REDACTED/node_modules/ethereum-cryptography/keccak.js:9:12
      at REDACTED/node_modules/ethereum-cryptography/hash-utils.js:5:20
      at keccak (REDACTED/node_modules/ethereumjs-util/dist/hash.js:21:33)
      at keccak256 (REDACTED/node_modules/ethereumjs-util/dist/hash.js:40:24)
      at hashBytecode (REDACTED/node_modules/@openzeppelin/upgrades-core/dist/version.js:39:34)
      at getVersion (REDACTED/node_modules/@openzeppelin/upgrades-core/dist/version.js:12:27)
      at validate (REDACTED/node_modules/@openzeppelin/upgrades-core/dist/validate/run.js:100:80)
      at new UpgradeableContract (REDACTED/node_modules/@openzeppelin/upgrades-core/dist/standalone.js:11:43)
```

### Stack Trace (bun.report)

Bun v1.1.26 ([`0a37423`](<https://github.com/oven-sh/bun/tree/0a37423bafab6aebe803e5f1594cffa9796f2ae6>)) on linux x86_64_baseline [RunCommand]

Segmentation fault at address 0x00000005

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/0a37423bafab6aebe803e5f1594cffa9796f2ae6/ld-temp.o#L0>): `llint_op_call`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/0a37423bafab6aebe803e5f1594cffa9796f2ae6/ld-temp.o#L0>): `llint_op_construct`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/0a37423bafab6aebe803e5f1594cffa9796f2ae6/ld-temp.o#L0>): `llint_op_call_ignore_result`

**Comment by KholdStare** [comment]
I've tried to reproduce on 1.1.32, and it is no longer crashing. Seems something was fixed since 1.1.26
