### ISSUE TITLE
Panic with vite+lightningcss when using visitors

### ISSUE THREAD

**Issue by corneliusio** [oven-sh/bun#13771]
### What version of Bun is running?

~1.1.26~ 1.3.0

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

Minimal reproduction of bug: https://github.com/corneliusio/vite-lightningcss

### What do you see instead?

```
thread '<unnamed>' panicked at napi/src/threadsafe_function.rs:235:57:
called `Result::unwrap()` on an `Err` value: Error { status: InvalidArg, reason: "expect Function, got: Undefined", maybe_raw: 0x0 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Edit: Have updated to indicate this is still occurring as of v1.3.0

**Comment by mattpilott** [comment]
I've just hit this, it's blocking docker builds, works in node

**Comment by thonkinator** [comment]
This doesn't seem to be an issue anymore, either vite or lightningcss (or both) must have fixed the issue because vite+lightningcss works for me even testing with bun v1.0.0. While I bet the underlying incompatibility is still there, it seems likely to me that this was caused by improper usage in vite that has now been fixed, given that lightningcss itself runs fine, see bun-lightningcss.

**Comment by thonkinator** [comment]
whoops, nevermind. still an issue, forgot to `--bun`

**Comment by mattpilott** [comment]
I've just run into this again
```
thread '<unnamed>' panicked at napi/src/threadsafe_function.rs:235:57:
called `Result::unwrap()` on an `Err` value: Error { status: InvalidArg, reason: "expect Function, got: Undefined", maybe_raw: 0x0 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: script "dev" was terminated by signal SIGABRT (Abort)
```

**Comment by mattpilott** [comment]
Ok update, it seems that despite me using bun, node had become unlinked following an update. I ran `brew link --overwrite node@22` and then bun dev again and voilà it's back. If this is **actually** the solution then we can of course close

**Comment by Razunter** [comment]
I have this issue with Bun 1.2.2 too when running `astro dev` + lightningcss (didn't test without it)

```
thread '<unnamed>' panicked at napi/src/threadsafe_function.rs:235:57:
called `Result::unwrap()` on an `Err` value: Error { status: InvalidArg, reason: "expect Function, got: Object", maybe_raw: 0x0 }
stack backtrace:
   0:     0x153599b599bc - <unknown>
   1:     0x1535993cf493 - <unknown>
   2:     0x153599b2fba2 - <unknown>
   3:     0x153599b5e652 - <unknown>
   4:     0x153599b5e4bb - <unknown>
   5:     0x153599b5eb76 - <unknown>
   6:     0x153599b5e728 - <unknown>
   7:     0x153599b5e689 - <unknown>
   8:     0x153599b5e67c - <unknown>
   9:     0x1535993b036f - <unknown>
  10:     0x1535993b06a5 - <unknown>
  11:     0x153599b0a9ac - <unknown>
  12:          0x36ab71c - <unknown>
```

**Comment by mattpilott** [comment]
Have run into this again

```
thread '<unnamed>' panicked at napi/src/threadsafe_function.rs:235:57:
called `Result::unwrap()` on an `Err` value: Error { status: InvalidArg, reason: "expect Function, got: Object", maybe_raw: 0x0 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: script "dev" was terminated by signal SIGABRT
```

**Comment by kisenaa** [comment]
I got same error with `bunx --bun dev` with Vite + LightningCSS .

```sh
14:25:39 watching for file changes...
thread '<unnamed>' panicked at napi\src\threadsafe_function.rs:235:57:
called `Result::unwrap()` on an `Err` value: Error { status: InvalidArg, reason: "expect Function, got: Object", maybe_raw: 0x0 }
stack backtrace:
   0:     0x7fffcc0ff7b8 - napi_register_module_v1
   1:     0x7fffcb979ffa - <unknown>
   2:     0x7fffcc0f4e37 - napi_register_module_v1
   3:     0x7fffcc101705 - napi_register_module_v1
   4:     0x7fffcc101540 - napi_register_module_v1
   5:     0x7fffcc101b63 - napi_register_module_v1
   6:     0x7fffcc1017e9 - napi_register_module_v1
   7:     0x7fffcc10173f - napi_register_module_v1
   8:     0x7fffcc10172e - napi_register_module_v1
   9:     0x7fffcc115611 - napi_register_module_v1
  10:     0x7fffcc115970 - napi_register_module_v1
  11:     0x7fffcc0cba83 - <unknown>
  12:     0x7ff64be98999 - <unknown>
  13:     0x7ff64bc052bc - <unknown>
  14:     0x7ff64bb0097c - <unknown>
  15:     0x7ff64cc5924b - v8::Number::Value
  16:     0x7ff64ba90dd5 - <unknown>
  17:     0x7ff64bc2969d - <unknown>
  18:     0x7ff64ba93cd6 - <unknown>
  19:     0x7ff64b995add - <unknown>
  20:     0x7ff64b9939bd - <unknown>
  21:     0x7ff64baa00b5 - <unknown>
  22:     0x7ff64b803567 - <unknown>
  23:     0x7ff64b8013b5 - <unknown>
  24:     0x7ff64f28d154 - uv_getnameinfo
  25:     0x7ff81cc3259d - BaseThreadInitThunk
  26:     0x7ff81ef6af78 - RtlUserThreadStart
```

**Comment by kisenaa** [comment]
> I got same error with `bunx --bun dev` with Vite + LightningCSS .
> 
> 14:25:39 watching for file changes...
> thread '<unnamed>' panicked at napi\src\threadsafe_function.rs:235:57:
> called `Result::unwrap()` on an `Err` value: Error { status: InvalidArg, reason: "expect Function, got: Object", maybe_raw: 0x0 }
> stack backtrace:
>    0:     0x7fffcc0ff7b8 - napi_register_module_v1
>    1:     0x7fffcb979ffa - <unknown>
>    2:     0x7fffcc0f4e37 - napi_register_module_v1
>    3:     0x7fffcc101705 - napi_register_module_v1
>    4:     0x7fffcc101540 - napi_register_module_v1
>    5:     0x7fffcc101b63 - napi_register_module_v1
>    6:     0x7fffcc1017e9 - napi_register_module_v1
>    7:     0x7fffcc10173f - napi_register_module_v1
>    8:     0x7fffcc10172e - napi_register_module_v1
>    9:     0x7fffcc115611 - napi_register_module_v1
>   10:     0x7fffcc115970 - napi_register_module_v1
>   11:     0x7fffcc0cba83 - <unknown>
>   12:     0x7ff64be98999 - <unknown>
>   13:     0x7ff64bc052bc - <unknown>
>   14:     0x7ff64bb0097c - <unknown>
>   15:     0x7ff64cc5924b - v8::Number::Value
>   16:     0x7ff64ba90dd5 - <unknown>
>   17:     0x7ff64bc2969d - <unknown>
>   18:     0x7ff64ba93cd6 - <unknown>
>   19:     0x7ff64b995add - <unknown>
>   20:     0x7ff64b9939bd - <unknown>
>   21:     0x7ff64baa00b5 - <unknown>
>   22:     0x7ff64b803567 - <unknown>
>   23:     0x7ff64b8013b5 - <unknown>
>   24:     0x7ff64f28d154 - uv_getnameinfo
>   25:     0x7ff81cc3259d - BaseThreadInitThunk
>   26:     0x7ff81ef6af78 - RtlUserThreadStart

For anyone who still have the error, using lightningcss-wasm solve the issue. I think the problem is bun compatibility with NAPI rs .

**Comment by thonkinator** [comment]
it looks like this may have been fixed in bun v1.3.8? if i create a brand new SvelteKit demo project and configure Vite to use lightningcss, bun v1.3.7 fails with the error but bun v1.3.8 works fine. i seem to remember testing with bun v1.3.8 and it not working, but perhaps the packages also made some change to be more compatible with bun
