### ISSUE TITLE
[Vite + Elysia] RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rtritto** [oven-sh/bun#13880]
### What version of Bun is running?

1.1.27+267afa293

### What platform is your computer?

Windows 11 x64

### What steps can reproduce the bug?

1. `git clone https://github.com/rtritto/template-vike-elysia-solid-daisyui.git`
2. `cd template-vike-elysia-solid-daisyui`
3. `git checkout bug-max-call-stack`
4. `yarn`
5. `yarn dev:debug`

### What is the expected behavior?

No error

### What do you see instead?

```console
Failed to apply Vite SSR stack trace fix: 441 |   var errorString = name + ": " + message;
442 | 
443 |   var state = { nextPosition: null, curPosition: null };
444 |   var processedStack = [];
445 |   for (var i = stack.length - 1; i >= 0; i--) {
446 |     processedStack.push('\n    at ' + wrapCallSite(stack[i], state));
                              ^
RangeError: Maximum call stack size exceeded.
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\source-map-support\source-map-support.js:446:25)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:110:91)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52718:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-BaOMuo4I.js:52723:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)

12:22:42 AM [vite] Error when evaluating SSR module C:/template-vike-elysia-solid-daisyui/src/server/index.ts:
|- TypeError: __vite_ssr_import_2__.serve is not a function. (In '__vite_ssr_import_2__.serve({
  fetch: app.fetch,
  port
})', '__vite_ssr_import_2__.serve' is undefined)
    at <anonymous> (unknown:12:28)
    at processTicksAndRejections (unknown:12:39)

[vite] Server crash: Update a server file or type "r+enter" to restart the server.

  VITE v5.4.3
```

### Additional informations

Using both plugins, `vike/plugin` and `vike-node/plugin` as Vite plugins, I got the "Maximum call stack size exceeded" error.
It works using only one plugin.

[vite.config.ts](https://github.com/rtritto/template-vike-elysia-solid-daisyui/blob/bug-max-call-stack/vite.config.ts)
```ts
import vikeSolid from 'vike-solid/vite'
import { plugin as vike } from 'vike/plugin'
import { vikeNode } from 'vike-node/plugin'

export default {
  // ...
  plugins: [
    vike(),
    vikeSolid(),  // optional
    vikeNode('src/server/index.ts')
  ],
  // ...
}
```

Original issue: https://github.com/vikejs/vike-node/issues/10

Probably related #817 #8823

**Comment by brillout** [comment]
It works with Node.js so it seems to be a Bun bug.

**Comment by rtritto** [comment]
FYI @kravetsone @SaltyAom

**Comment by rtritto** [comment]
Update dependencies and bun to v1.1.29:
```console
Failed to apply Vite SSR stack trace fix: 52723 |     return;
52724 |   }
52725 |   try {
52726 |     new Function("throw new Error(1)")();
52727 |   } catch (e) {
52728 |     const match = /:(\d+):\d+\)$/.exec(e.stack.split("\n")[1]);
                                               ^
RangeError: Maximum call stack size exceeded.
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-DG6Lorbi.js:52728:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-DG6Lorbi.js:52733:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-DG6Lorbi.js:52728:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-DG6Lorbi.js:52733:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-DG6Lorbi.js:52728:40)
      at ssrRewriteStacktrace (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-DG6Lorbi.js:52733:3)
      at prepareStackTrace (C:\template-vike-elysia-solid-daisyui\node_modules\vike-node\dist\plugin\plugins\devServerPlugin.js:114:24)
      at calculateOffsetOnce (C:\template-vike-elysia-solid-daisyui\node_modules\vite\dist\node\chunks\dep-DG6Lorbi.js:52728:40)

12 | export default "unknown";
                                ^
TypeError: __vite_ssr_import_2__.serve is not a function. (In '__vite_ssr_import_2__.serve({
  fetch: app.fetch,
  port
})', '__vite_ssr_import_2__.serve' is undefined)
      at unknown:12:28
      at processTicksAndRejections (unknown:12:39)

[vite] Server crash: Update a server file or type "r+enter" to restart the server.
Re-optimizing dependencies because lockfile has changed
  VITE v5.4.7  ready in 2505 ms
```

**Comment by rtritto** [comment]
@brillout could the problem be related to Vite (or Vite SSR)?
Should I open an issue on Vite?
This issue is a blocker...

**Comment by sunnylost** [comment]
This is a bug with Bun, its behavior is not compatible with Node.

The following code is the simplified version of the code that caused the error.

```js
function a() {
    try {
        new Function("throw new Error(1)")()
    } catch (e) {
        e.stack
    }
}

Error.prepareStackTrace = function() {
    console.log('trigger')
    a()
}

new Error().stack
```

You can try running this snippet in both Node and Bun. In Node(I'm using v22.8.0), "trigger" is only displayed once, but in Bun(v1.1.29), it throws a 'Maximum call stack size exceeded' error.

Code related to `vite` and `vike`:

```ts
// vike/src/utils/getOutDirs.ts 
function getOutDirs(config: ResolvedConfig): OutDirs {
  // this will cause a problem
  debug('getOutDirs()', new Error().stack)
  // ...
}

// vike-node/plugin/plugins/devServerPlugin.ts
function setupErrorStrackRewrite() {
  const _prepareStackTrace = Error.prepareStackTrace;  
  Error.prepareStackTrace = function prepareStackTrace(error, stack) {
    // ...
    ret = vite.ssrRewriteStacktrace(ret)
  }
}

// packages/vite/src/node/ssr/ssrStacktrace.ts
export function ssrRewriteStacktrace(
  stack: string,  
  moduleGraph: EnvironmentModuleGraph,  
): string {  
  calculateOffsetOnce()
  // ...
}

function calculateOffsetOnce() {  
  // ...
  try {  
    new Function('throw new Error(1)')()  
  } catch (e) {  
    // here will invoke `Error.prepareStackTrace()` again
    const match = /:(\d+):\d+\)$/.exec(e.stack.split('\n')[1])  
    offset = match ? +match[1] - 1 : 0  
  }  
}
```
