### ISSUE TITLE
⨯ Failed to start server. Error: listen EACCES: permission denied 0.0.0.0:3006

### ISSUE THREAD

**Issue by Ebrahim-Ramadan** [oven-sh/bun#14066]
### What version of Bun is running?

1.1.26

### What platform is your computer?

windows

### What steps can reproduce the bug?

just ran `bun dev` on a nextjs project
ranodmly on 3pm tuesday

### What is the expected behavior?

```
$ PORT=3005 next dev
server is starting at http:localhost:3005
ready to compile
```

### What do you see instead?

```
$ PORT=3006 next dev
 ⨯ Failed to start server
Error: listen EACCES: permission denied 0.0.0.0:3006
    at Server.setupListenHandle [as _listen2] (node:net:1855:21)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at Q:\picthing-indie\node_modules\next\dist\server\lib\start-server.js:280:16
    at new Promise (<anonymous>)
    at startServer (Q:\picthing-indie\node_modules\next\dist\server\lib\start-server.js:191:11)
    at Q:\picthing-indie\node_modules\next\dist\server\lib\start-server.js:310:52
    at Span.traceAsyncFn (Q:\picthing-indie\node_modules\next\dist\trace\trace.js:154:26)
    at process.<anonymous> (Q:\picthing-indie\node_modules\next\dist\server\lib\start-server.js:310:35)
    at process.emit (node:events:518:28) {
  code: 'EACCES',
  errno: -4092,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 3006
}
```

**Comment by Ebrahim-Ramadan** [comment]
it just got resolved
did not do anything
