### ISSUE TITLE
false-negative test failure when using expect().resolves.not.toThrow()

### ISSUE THREAD

**Issue by nektro** [oven-sh/bun#14076]
### What version of Bun is running?

1.1.27+267afa293

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

```ts
test("foo", async () => {
  await expect(Promise.resolve("hello world")).resolves.not.toThrow();
});
```

### What is the expected behavior?

test passes

### What do you see instead?

```
test/x.test.js:
1 | test("foo", async () => {
2 |   await expect(Promise.resolve("hello world")).resolves.not.toThrow();
                                                                ^
error: expect(received).not.toThrow()

Thrown value: "hello world"

      at /Users/meghandenny/src/bun3/test/x.test.js:2:61
      at /Users/meghandenny/src/bun3/test/x.test.js:1:13
✗ foo [3.07ms]

 0 pass
 1 fail
 1 expect() calls
Ran 1 tests across 1 files. [30.00ms]
```

### Additional information

looks like `.resolves.not` together is causing the test failure and `.toThrow()` is overriding the final message

**Comment by nektro** [comment]
workaround is to replace `await expect(XY).resolves.not.toThrow();` with `await XY;`

**Comment by robobun** [comment]
This is the same bun:test bug tracked in #9687: `await expect(promise).resolves.not.toThrow()` fails with `expect(received).not.toThrow()` / `Thrown value: <resolved value>` even though the promise resolved, because the resolved value is treated as a thrown value. The same fix resolves both reports, so it will be tracked in #9687.

Duplicate of #9687

Please add a 👍 or any extra details over there so it all stays in one place. If this is actually a different problem, say so here and we'll reopen.
