### ISSUE TITLE
Jest: Failed to parse the TypeScript config file

### ISSUE THREAD

**Issue by birkskyum** [oven-sh/bun#14083]
### What version of Bun is running?

1.1.29-canary.12+c298b23c4

### What platform is your computer?

Darwin 24.0.0 arm64 arm

### What steps can reproduce the bug?

Repro here:
https://github.com/birkskyum/jest-config-ts

Just a small jest/ts-node/ts-jest starter with a jest.config.ts and a sum / sum.test file.

### What is the expected behavior?

I'd expect `bun --bun run test` to pass the test like `bun run test` and `npm run test` does

```
 PASS  src/sum.test.js
  ✓ adds 1 + 2 to equal 3 (2 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.121 s, estimated 1 s
Ran all test suites.
```

### What do you see instead?

```
➜ bun --bun run test
$ jest
Error: Jest: Failed to parse the TypeScript config file /Users/admin/repos/bun-kitchensink/jest-config-ts/jest.config.ts
  TypeError: module_1.Module._preloadModules is not a function. (In 'module_1.Module._preloadModules(service.options.require)', 'module_1.Module._preloadModules' is undefined)
    at /Users/admin/repos/bun-kitchensink/jest-config-ts/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:116:12
    at processTicksAndRejections (unknown:12:39)
error: script "test" exited with code 1
```

**Comment by birkskyum** [comment]
Bun 1.1.34

```sh
➜ bun --bun run test
$ jest
 FAIL  src/sum.test.js
  ● Test suite failed to run

    TypeError: Use `new EventEmitter(...)` instead of `EventEmitter(...)`
        at EventEmitter (native)

      at createProcessObject (node_modules/jest-util/build/createProcessObject.js:98:24)
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.026 s, estimated 1 s
Ran all test suites.
error: script "test" exited with code 1
```
