### ISSUE TITLE
Regression with fs/promises.stat

### ISSUE THREAD

**Issue by zouloux** [oven-sh/bun#1410]
### What version of Bun is running?

0.2.2

### What platform is your computer?

Linux 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 unknown

### What steps can reproduce the bug?

```
import { stat } from "fs/promises"

async function isDirectory ( path ) {
    const s = await stat( path )
    return s.isDirectory()
}

isDirectory("./").then( r => console.log( r ) )

```

### How often does it reproduce? Is there a required condition?

Always crashes.
Was working on 0.2.1
Is still working on Darwin

### What do you see instead?

```
stat public/
      at node:fs/promises:5:2
      at node:fs/promises:20:17
      at node:fs/promises:37:6
      at node:fs/promises:36:11
      at /root/server/node_modules/@zouloux/static-http/dist/server.es2020.mjs:9:22
```

### Additional information

File read write access didn't changed.
Also crash if wrapped into a try / catch statement.

**Comment by Jarred-Sumner** [comment]
Does statSync crash?

**Comment by zouloux** [comment]
Will check that soon !

**Comment by mia-z** [comment]
Came across this same issue today as the same thing was happening. 

@Jarred-Sumner statSync is working as normal in my case. 

``` typescript
const routesRoot = resolve(root + "/routes");

const filesInRoot = await readdir(routesRoot);
for (const file of filesInRoot) {
    const fullPath = join(routesRoot, file);
    const fileStats = statSync(fullPath);
    const isDir = await fileStats.isDirectory();
    console.log(fullPath, isDir);
}

/home/miaz/workspace/proxy-tools/routes/messages.ts false
/home/miaz/workspace/proxy-tools/routes/messages true
/home/miaz/workspace/proxy-tools/routes/user.ts false
```

``` typescript
const routesRoot = resolve(root + "/routes");

const filesInRoot = await readdir(routesRoot);
for (const file of filesInRoot) {
    const fullPath = join(routesRoot, file);
    const fileStats = await stat(fullPath);
    const isDir = await fileStats.isDirectory();
    console.log(fullPath, isDir);
}

stat /home/miaz/workspace/proxy-tools/routes/messages.ts
      at node:fs/promises:5:2
      at node:fs/promises:20:17
      at node:fs/promises:37:6
      at node:fs/promises:36:11
      at /home/miaz/workspace/proxy-tools/src/index.ts:22:28
stat /home/miaz/workspace/proxy-tools/routes/messages
      at node:fs/promises:5:2
      at node:fs/promises:20:17
      at node:fs/promises:37:6
      at node:fs/promises:36:11
      at /home/miaz/workspace/proxy-tools/src/index.ts:22:28
stat /home/miaz/workspace/proxy-tools/routes/user.ts
      at node:fs/promises:5:2
      at node:fs/promises:20:17
      at node:fs/promises:37:6
      at node:fs/promises:36:11
      at /home/miaz/workspace/proxy-tools/src/index.ts:22:28
```

I'm running Bun 0.2.2 on WSL2 Ubuntu 22.04

**Comment by mia-z** [comment]
Possibly related to #1328 ?

**Comment by Jarred-Sumner** [comment]
The bug is a really stupid mistake I made

https://github.com/oven-sh/bun/blob/cf46ebdab37a126fefe291e14b5a2597cecbda06/src/bun.js/fs_promises.exports.js#L2-L7

Didn't mean to commit this code. No error is being thrown. It's just an extra `console.trace` if you use the promise version of the function.

**Comment by terrywh** [comment]
should there be tests that checks for these kind of things ?
@Jarred-Sumner
