### ISSUE TITLE
bun install

### ISSUE THREAD

**Issue by kaminskypavel** [oven-sh/bun#14103]
```bash
>>  Installing dependencies...
>>> Unexpected error. Please report it as a bug:
Error: Command failed with exit code 3: bun install
bun install v1.1.29 (6d43b366)
Resolving dependencies
============================================================
Bun v1.1.29 (6d43b366) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "bun" "install"
Features: extracted_packages(178) git_dependencies(4)
Elapsed: 20586ms | User: 1937ms | Sys: 7109ms
RSS: 0.50GB | Peak: 0.52GB | Commit: 0.73GB | Faults: 228846

panic(main thread): Internal assertion failure
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.29/wi16d43b36AggJ+xsqG+xvB+h9Pg/o7DgxktSo7t0Ew/+9Ewi0jGq6gBi8IA0eNrzzCtJLcpLzFFILC5OLSrJzM9TSEvMzCktSgUAiSkKPg

    at CM (C:\Users\kamin\AppData\Local\Temp\bunx-3530938197-create-turbo@latest\node_modules\create-turbo\dist\cli.js:23:57)
    at C:\Users\kamin\AppData\Local\Temp\bunx-3530938197-create-turbo@latest\node_modules\create-turbo\dist\cli.js:23:8077
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ph (C:\Users\kamin\AppData\Local\Temp\bunx-3530938197-create-turbo@latest\node_modules\create-turbo\dist\cli.js:69:2060)
    at async Command.Eg (C:\Users\kamin\AppData\Local\Temp\bunx-3530938197-create-turbo@latest\node_modules\create-turbo\dist\cli.js:94:7474)
    at async Command.parseAsync (C:\Users\kamin\AppData\Local\Temp\bunx-3530938197-create-turbo@latest\node_modules\commander\lib\command.js:936:5) {
  shortMessage: 'Command failed with exit code 3: bun install',
  command: 'bun install',
  escapedCommand: 'bun install',
  exitCode: 3,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'bun install v1.1.29 (6d43b366)\n' +
    'Resolving dependencies\n' +
    '============================================================\n' +
    'Bun v1.1.29 (6d43b366) Windows x64\n' +
    'Windows v.win10_fe\n' +
    'CPU: sse42 avx avx2\n' +
    'Args: "bun" "install"\n' +
    'Features: extracted_packages(178) git_dependencies(4) \n' +
    'Elapsed: 20586ms | User: 1937ms | Sys: 7109ms\n' +
    'RSS: 0.50GB | Peak: 0.52GB | Commit: 0.73GB | Faults: 228846\n' +
    '\n' +
    'panic(main thread): Internal assertion failure\n' +
    'oh no: Bun has crashed. This indicates a bug in Bun, not your code.\n' +
    '\n' +
    "To send a redacted crash report to Bun's team,\n" +
    'please file a GitHub issue using the link below:\n' +
    '\n' +
    ' https://bun.report/1.1.29/wi16d43b36AggJ+xsqG+xvB+h9Pg/o7DgxktSo7t0Ew/+9Ewi0jGq6gBi8IA0eNrzzCtJLcpLzFFILC5OLSrJzM9TSEvMzCktSgUAiSkKPg\n',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

```

**Comment by nektro** [comment]
<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">panic: Internal assertion failure

[output.zig:357](https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/output.zig#L357)	fn panic
[bun.zig:3388](https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/bun.zig#L3388)	fn assertionFailure
[fd.zig:35](https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/fd.zig#L35)	fn uv_get_osfhandle
[install.zig:5314](https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/install/install.zig#L5314)	fn enqueueDependencyWithMainAndSuccessFn
[install.zig:5826](https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/install/install.zig#L5826)	fn processPeerDependencyList
[event_loop.zig:1917](https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/bun.js/event_loop.zig#L1917)	fn tick
[install.zig:11685](https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/install/install.zig#L11685)	fn install
[cli.zig:1585](https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/cli.zig#L1585)	fn start
[cli.zig:62](https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/cli.zig#L62)	fn start
[main.zig:49](https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/main.zig#L49)	fn main
