### ISSUE TITLE
Ubuntu 22.04 installation issues

### ISSUE THREAD

**Issue by ffMathy** [oven-sh/bun#14188]
### Discussed in https://github.com/oven-sh/bun/discussions/4014

<div type='discussions-op-text'>

<sup>Originally posted by **vjpr** August  6, 2023</sup>
### Solution

This fixed it for me: https://askubuntu.com/a/1062184/151910

## error: script "postinstall" exited with code 7 (SIGBUS)

Default version of node is 12.

It seems `node` is used for something...

### Solution

Install latest Node.

Use nvm - https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-22-04#option-3-installing-node-using-the-node-version-manager

```
cd test && /home/vaughan/.bun/bin/bun install
bun install v0.7.2 (9574db35)
 + @types/dedent@0.7.0
 + @types/react@18.0.28
 + @types/react-dom@18.0.11
 + @types/supertest@2.0.12
 + @types/utf-8-validate@5.0.0
 + @prisma/client@5.0.0
 + @swc/core@1.3.38
 + bktree-fast@0.0.7
 + body-parser@1.20.2
 + comlink@4.4.1
 + dedent@0.7.0
 + es-module-lexer@1.3.0
 + esbuild@0.18.6
 + express@4.18.2
 + iconv-lite@0.6.3
 + jest-extended@4.0.0
 + lodash@4.17.21
 + nodemailer@6.9.3
 + pg@8.11.1
 + pg-connection-string@2.6.1
 + postgres@3.3.5
 + prisma@5.0.0
 + socket.io@4.7.1
 + socket.io-client@4.7.1
 + supertest@6.3.3
 + svelte@3.55.1
 + typescript@5.0.2
 + undici@5.20.0
 + vitest@0.32.2
 + webpack@5.88.0
 + webpack-cli@4.7.2
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@12.22.9 | linux | x64
gyp info find Python using Python version 3.10.4 found at "/usr/bin/python3"
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack /tmp/node-gyp@latest--bunx/node_modules/ssri/lib/index.js:16
gyp ERR! stack const getOptString = options => options?.length ? `?${options.join('?')}` : ''
gyp ERR! stack                                         ^
gyp ERR! stack
gyp ERR! stack SyntaxError: Unexpected token '.'
gyp ERR! stack     at wrapSafe (internal/modules/cjs/loader.js:915:16)
gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:963:27)
gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:863:32)
gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:887:19)
gyp ERR! stack     at require (internal/modules/cjs/helpers.js:74:18)
gyp ERR! stack     at Object.<anonymous> (/tmp/node-gyp@latest--bunx/node_modules/make-fetch-happen/lib/cache/policy.js:3:14)
gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:999:30)
gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
gyp ERR! System Linux 5.15.0-46-generic
gyp ERR! command "/usr/bin/node" "/tmp/node-gyp@latest--bunx/node_modules/.bin/node-gyp" "configure" "build"
gyp ERR! cwd /home/vaughan/dev/fork/+bun/bun/test/node_modules/bktree-fast
gyp ERR! node -v v12.22.9
gyp ERR! node-gyp -v v9.4.0
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
error: "node-gyp" exited with code 7 (SIGBUS)

 342 packages installed [6.60s]
error: script "postinstall" exited with code 7 (SIGBUS)
make: *** [Makefile:533: npm-install-dev] Error 7
```</div>

**Comment by nektro** [comment]
npm packages that require node-gyp are sometimes executed with node if that is what is requested in the shebang and `node` is available on the system. the version of node-gyp being used by this package uses [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) which was not supported in node until v14.

**Comment by daviewales** [comment]
I 'fixed' this in my case by creating a symlink on my path `node -> bun'.
