### ISSUE TITLE
Syntax Error in String.raw

### ISSUE THREAD

**Issue by lmachens** [oven-sh/bun#14213]
### What version of Bun is running?

1.1.29

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Run this code:

```js
console.log(String.raw`Hello\user`);
```

### What is the expected behavior?

If you run it with Node.js, it logs `Hello\user`  The `u` is not escaped and you see the `\`.

### What do you see instead?

```
1 | console.log(String.raw`Hello\user`);
                          ^
error: Syntax Error!!
    at C:\dev\the-hidden-gaming-lair\test.js:1:23
    ```

A syntax error, because bun tries to escape Unicode sequence

**Comment by Jarred-Sumner** [comment]
This is a lexer bug. We are validating the input too much in the lexer.

**Comment by nektro** [comment]
this blocks running eslint's own test suite

<details>
<summary> debug log </summary>

```
error: exec: 
 Exception during run: 200 |             errors: [{ messageId: "nested", data: { bref: String.raw`/1`, group: String.raw`(/1)`, otherGroups: "" }, type: "NewExpression" }]
                                                                          ^
error: Syntax Error!!
    at //tests/lib/rules/no-useless-backreference.js:200:69

      at error (//node_modules/shelljs/src/common.js:110:27)
      at execSync (//node_modules/shelljs/src/exec.js:120:12)
      at _exec (//node_modules/shelljs/src/exec.js:223:12)
      at //node_modules/shelljs/src/common.js:335:23
      at //Makefile.js:582:18
      at //node_modules/shelljs/make.js:36:40
      at //Makefile.js:609:12
      at //node_modules/shelljs/make.js:36:40
      at //node_modules/shelljs/make.js:48:23
      at forEach (1:11)

Bun v1.1.30-debug+cf6304222 (macOS arm64)
error: script "test" exited with code 1
```

</details>

**Comment by RiskyMH** [comment]
#15009 seems to have fixed this!
