### ISSUE TITLE
Parser error not clear about private attributes

### ISSUE THREAD

**Issue by berzinv** [oven-sh/bun#14236]
### What version of Bun is running?

1.1.29

### What platform is your computer?

Windows

### What steps can reproduce the bug?

class Points {
	#points: Array<Number>;
	
	constructor(points: Array<Number>) {
		this.#points = points;
	}
	
	length() {
		return this.#points.length;
	}
}

let p = new Points([1, 2, 3]);
console.log(p.length());
console.log(p.#points);  

/* The error I get is
15 | console.log(p.#points);
                   ^
error: Expected identifier but found "#points"
    at C:\Users\berzi\Documents\testpoints.ts:15:15

15 | console.log(p.#points);
                           ^
error: Expected ")" but found ";"
    at C:\Users\berzi\Documents\testpoints.ts:15:23

Bun v1.1.29 (Windows x64)

*/

### What is the expected behavior?

With tsc, the error is very clear 

testpoints.ts:15:15 - error TS18013: Property '#points' is not accessible outside class 'Points' because it has a private identifier.

15 console.log(p.#points);
                 ~~~~~~~


Found 1 error in testpoints.ts:15




### What do you see instead?

_No response_

### Additional information

_No response_

**Comment by Jarred-Sumner** [comment]
yeah this error is not good
