### ISSUE TITLE
Blob LastModified incompatibility with Node

### ISSUE THREAD

**Issue by MissEvelynLily** [oven-sh/bun#14257]
### What version of Bun is running?

Bun v1.1.30-canary.71+af82a446d (macOS arm64)

### What platform is your computer?

Darwin 24.0.0 arm64 arm

### What steps can reproduce the bug?

```js
class MyBlob extends Blob {
  constructor(parts) {
    super(parts);
    this.lastModified = 123;
  }
}

const blob = new MyBlob(["foo"]);

```

### What is the expected behavior?

In node, works fine.

### What do you see instead?

```
bun test.js

1 | class MyBlob extends Blob {
2 |   constructor(parts) {
3 |     super(parts);
4 |     this.lastModified = 123;
        ^
TypeError: Attempted to assign to readonly property.
      at new MyBlob (/Users/emily/Sites/ut-test/up-test.js:4:5)
      at /Users/emily/Sites/ut-test/up-test.js:8:14
```

**Comment by nektro** [comment]
cause of error is here https://github.com/oven-sh/bun/blob/73537de184ed1f34/src/bun.js/webcore/response.classes.ts#L161

**Comment by jimmywarting** [comment]
It's unfortunate that they closed #5980 

like you, i have also stumble upon this issue before as well. Bun have messed up Blob/File class with lots of bloated properties that should not exist on it. that creates issues like this.

when you set the lastModified like this:
```js
  constructor(parts) {
    this.lastModified = 123;
  }
```
what you are really doing is modifying the Blob's lastModified property (that should not exist at all on `Blob.prototype.lastModified`)

---

This should not have to be the solution: but if you have a own `lastModified` date on your own class, it can work

```js
class MyBlob extends Blob {
  lastModified // = null || undefined ( same as doing MyBlob.prototype.lastModified = null )

  constructor(parts) {
    super(parts);

    // what happens now is that you change your own lastModified date 
    // while the Blob.prototype.lastModified remains unchanged. 
    // you are essentially overriding lastModified 
    this.lastModified = 123;
  }
}
```

---

Bun's own Blob & FIle are weird and very buggy sometimes. doing unconventional stuff and not following the web spec here in this regards. Node & Deno's Blob / File are more correctly built.

i have said it before and i will say it again, bun should really separate this into its own counter parts
```js
class Blob {}
class File extends Blob {}
class BunFile extends File {}

Bun.file = (...) => new BunFile(...)
```
