### ISSUE TITLE
LoadLibrary failed: A dynamic link library (DLL) in

### ISSUE THREAD

**Issue by dollyjat** [oven-sh/bun#14283]
### How can we reproduce the crash?

  Admin D:\bunDb via 🍔Bun v1.1.29 
 😊 ➜  bun dev
$ bun run src/index.ts
107 |         return opts[p] || p;
108 |       })
109 |     );
110 |     tries.push(n);
111 |     try {
112 |       b = opts.path ? requireFunc.resolve(n) : requireFunc(n);
                                                     ^
TypeError: LoadLibrary failed: A dynamic link library (DLL) in
      at bindings (D:\bunDb\node_modules\bindings\bindings.js:112:48)
      at new Database (D:\bunDb\node_modules\better-sqlite3\lib\database.js:48:29)
      at D:\bunDb\src\db.ts:3:16

Bun v1.1.29 (Windows x64 baseline)
============================================================
Bun v1.1.29 (6d43b366) Windows x64 (baseline)
Windows v.win10_fe
CPU: sse42 avx
Args: "C:\Users\GauravJatt\scoop\apps\bun\current\bun.exe" "run" "src/index.ts"Features: jsc tsconfig(2) no_avx2 
Builtins: "bun:main" "node:fs" "node:path" "node:string_decoder" "node:util" "node:util/types" 
Elapsed: 282ms | User: 171ms | Sys: 62ms
RSS: 0.14GB | Peak: 0.14GB | Commit: 0.20GB | Faults: 34656

panic(main thread): Segmentation fault at address 0x7FFC6C2E4D80
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.29/er16d43b36AiggggiB_CSntdll.dllqrvXCSntdll.dll26tXCSntdll.dll6otXCYKERNEL32.DLL27xHy39g9Cgk+g9CgjhBkvpzM+z/8GA24//Bg4m5lsD

error: script "dev" exited with code 1

### Stack Trace (bun.report)

Bun v1.1.29 ([`6d43b36`](<https://github.com/oven-sh/bun/tree/6d43b366220099042f28c5fa5c66185fe2580539>)) on windows x86_64_baseline [RunCommand]

Segmentation fault at address 0x7FFC6C2E4D80

- *1 unknown/js code*
- ??? at `0x5deb5` in ntdll.dll
- ??? at `0x5dbab` in ntdll.dll
- ??? at `0x5da8d` in ntdll.dll
- ??? at `0x1e3bb` in KERNEL32.DLL
- [`exit.cpp:137`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/appcrt/startup/exit.cpp#L137>): `exit_or_terminate_process`
- [`exit.cpp:274`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/appcrt/startup/exit.cpp#L274>): `common_exit`
- [`Global.zig:121`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/Global.zig#L121>): `exit`
- [`javascript.zig:1316`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/bun.js/javascript.zig#L1316>): `globalExit`
- [`javascript.zig:1228`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/bun.js/javascript.zig#L1228>): `eventLoop`

Features: jsc, tsconfig, no\_avx2

**Comment by mrxbox98** [comment]
Bun doesn't support ``better-sqlite3`` currently https://github.com/oven-sh/bun/issues/4290
