### ISSUE TITLE
Jest fails to import `createBunWebSocket`

### ISSUE THREAD

**Issue by amadodiazjr** [oven-sh/bun#14360]
### What version of Bun is running?

1.1.10-canary.1+370db0889

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

Repo used to isolate issue.

Please read the README.md for details

https://github.com/amadodiazjr/bun-not-defined

### What is the expected behavior?

`bun run test` succeeds

### What do you see instead?

```
 FAIL  src/index.spec.ts
  ● Test suite failed to run

    ReferenceError: Bun is not defined

    > 1 | import { createBunWebSocket } from 'hono/bun'
        | ^
      2 |
      3 | describe('index', () => {
      4 |   it("should not FAIL", () => {

      at Object.<anonymous> (node_modules/hono/dist/cjs/adapter/bun/ssg.js:26:19)
      at Object.<anonymous> (node_modules/hono/dist/cjs/adapter/bun/index.js:29:18)
      at Object.require (src/index.spec.ts:1:1)
```

**Comment by amadodiazjr** [comment]
Moved to [here](https://github.com/honojs/hono/issues/3490)
