### ISSUE TITLE
top-level await bug with `bun build --bytecode`

### ISSUE THREAD

**Issue by linux-china** [oven-sh/bun#14412]
### What version of Bun is running?

1.1.30+7996d06b8

### What platform is your computer?

Darwin 23.6.0 x86_64 i386

### What steps can reproduce the bug?

I have a `demo.ts`  file with following code: 
```
async function main() {
    console.log("main function");
}

await main()
```

and `bun build --compile ./demo.ts` works well.  

But `bun build --bytecode --compile ./demo.ts` fails with following error:  

```
 $ bun build --bytecode --compile ./demo.ts
5 | await main()
          ^
error: "await" can only be used inside an "async" function
    at /Users/xxx/WebstormProjects/bun-demo/demo.ts:5:7

5 | await main()
                ^
error: Expected "=>" but found end of file
    at /Users/xxx/WebstormProjects/bun-demo/demo.ts:5:13
```

**Comment by 0xFA11** [comment]
+1, I can second that.

this is fine:
`NODE_ENV=production bun build ./index.ts --minify --compile --outfile=bin`

this breaks:
`NODE_ENV=production bun build ./index.ts --minify --compile --bytecode --outfile=bin`

**Comment by ksbrooksjr** [comment]
It seems like it only supports CJS at the moment (top level await is only valid in ESM). Running `bun build --format=esm --bytecode --compile ./demo.ts` fails with the error:

```
error: format must be 'cjs' when bytecode is true. Eventually we'll add esm support as well.
```

**Comment by remorses** [comment]
Is this feature possible or in the works? I am considering if I should remove top level await to add bytecode compilation or should wait for a fix in Bun instead
