### ISSUE TITLE
async_hooks.createHook is not implemented in Bun. Hooks can still be created but will never be called. NotImplementedError: perf_hooks.monitorEventLoopDelay is not yet implemented in Bun.

### ISSUE THREAD

**Issue by ankl209** [oven-sh/bun#14457]
### What version of Bun is running?

1.1.30

### What platform is your computer?

Linux 4.19.91-27.1.al7.x86_64 x86_64 unknown

### What steps can reproduce the bug?

bun install elastic-apm-node
Errors are reported when using this module

### What is the expected behavior?

bun supports async_hooks.createHook

### What do you see instead?

```
"nodejs.memory.heap.used.bytes": 0,
"nodejs.memory.arrayBuffers.bytes": 0
^
code: "ERR_NOT_IMPLEMENTED"
-
at monitorEventLoopDelay (node:perf_hooks:138:24)
at createRuntimeMetrics (/home/build/main.js:34140:23)
at /home/build/main.js:38670:19
at /home/build/main.js:2:45
2024-10-10T02:40:21.111Z require-in-the-middle registering require hook
[bun] Warning: async_hooks.createHook is not implemented in Bun. Hooks can still be created but will never be called.
"nodejs.memory.external.bytes": 0,
 };
NotImplementedError: perf_hooks.monitorEventLoopDelay is not yet implemented in Bun.
-
at new RuntimeCollector (/home/build/main.js:34117:23)
at start (/home/build/main.js:34508:30)
Bun v1.1.29 (Linux x64 baseline)
at /home/build/main.js:1141806:9
```

**Comment by plgrazon** [comment]
@Jarred-Sumner sorry for tagging you on this again.

I added `nodejs-spanner` from Google, and I am getting this issue. I posted on their repo: [LINK](https://github.com/googleapis/nodejs-spanner/issues/2352#issuecomment-3113647789) and it was said that it is a bun issue.

Do we have a regression for this?
