### ISSUE TITLE
too many syntax errors for missing `>` in jsx

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#14476]
### What steps can reproduce the bug?

```ts
"use client";

import { useState } from "react";

export function Client() {
    const [a, b] = useState(2);
    return <div>
       {a} <bu onClick={() => b(x => x + 2)}>a</bu
    </div>
}
```

### What is the expected behavior?

one syntax error

### What do you see instead?

```
9 |     </div>
        ^
error: Expected ">" but found "<"
    at /Users/dave/code/kit_example_01/pages/Client.tsx:9:5

9 |     </div>
         ^
error: Syntax Error!!
    at /Users/dave/code/kit_example_01/pages/Client.tsx:9:6
```

### Additional information

found while testing HMR error handling

**Comment by paperdave** [comment]
fixed on a branch
