### ISSUE TITLE
Bun.spawn with cwd that doesn't exist returns confusing error message

### ISSUE THREAD

**Issue by vjpr** [oven-sh/bun#14535]
### What version of Bun is running?

1.1.30+7996d06b8

### What platform is your computer?

Darwin 24.0.0 arm64 arm

### What steps can reproduce the bug?

```js
await Bun.spawn({
  cmd: cmdArg,
  stdout: 'inherit',
  stderr: 'inherit',
  cwd: 'this/does/not/exist',
})
```

### What is the expected behavior?

```sh
36 | 
37 | const cmdArg = cmd.split(' ')
38 | 
39 | console.error(cmdArg, dir)
40 | 
41 | await Bun.spawn({
               ^
ENOENT: No such file or directory
   errno: -2
 syscall: "posix_spawn"
   cwd: "/this/does/not/exist"
      at /Users/Vaughan/dev/work/docubuild/code/+legacy/docubuild/repos/docubuild-legacy/groups/docubuild-legacy/js/apps/web-legacy/run/prisma.ts:41:11
Bun v1.1.30 (macOS arm64)
error: script "prisma" exited with code 1
```

### What do you see instead?

This shows that path of the executable `/Users/Vaughan/.bun/bin/bunx` which actually exists which is confusing because its the cwd that doesn't and there is no mention of it.

```sh
36 | 
37 | const cmdArg = cmd.split(' ')
38 | 
39 | console.error(cmdArg, dir)
40 | 
41 | await Bun.spawn({
               ^
ENOENT: No such file or directory
   errno: -2
 syscall: "posix_spawn"
   path: "/Users/Vaughan/.bun/bin/bunx"
      at /Users/Vaughan/dev/work/docubuild/code/+legacy/docubuild/repos/docubuild-legacy/groups/docubuild-legacy/js/apps/web-legacy/run/prisma.ts:41:11
Bun v1.1.30 (macOS arm64)
error: script "prisma" exited with code 1
```

### Additional information

https://github.com/oven-sh/bun/pull/7163
https://bun.sh/blog/bun-v1.0.13#bun-spawn-better-errors

_No response_

**Comment by robobun** [comment]
Same bug as #8024: Bun.spawn/Bun.spawnSync with a non-existent cwd throws an ENOENT whose path points at the executable (argv[0]) instead of the missing cwd. The open fix PR #32445 lists both issues and will close both; tracking continues in #8024.

Duplicate of #8024

Please add a 👍 or any extra details over there so it all stays in one place. If this is actually a different problem, say so here and we'll reopen.
