### ISSUE TITLE
StructuredClone() does not clone array of File

### ISSUE THREAD

**Issue by Booteille** [oven-sh/bun#14661]
### What version of Bun is running?

1.1.31+e448c4cc3

### What platform is your computer?

Linux 6.9.3-76060903-generic x86_64 x86_64

### What steps can reproduce the bug?

- Create two files: `file1.txt`, `file2.txt`
- run the following code:

```ts
import fs from "fs";

function main() {
    const file1Path = import.meta.dir + "/file1.txt"
    const file2Path = import.meta.dir + "/file2.txt"

    const file1 = new File([fs.readFileSync(file1Path)], file1Path, { type: 'text/plain' });
    const file2 = new File([fs.readFileSync(file2Path)], file2Path, { type: 'text/plain' });
    
    console.debug(file1Path)

    const files = [file1, file2];

    structuredClone(file1);
    structuredClone(files);

}

main();
```

### What is the expected behavior?

I expect no error to be thrown in the console. (I tried similar code in browser and it worked perfectly)

### What do you see instead?

```console
$ bun run index.ts
/home/booteille/Dev/bun-structured-clone-test/file1.txt
10 |     console.debug(file1Path)
11 | 
12 |     const files = [file1, file2];
13 | 
14 |     structuredClone(file1);
15 |     structuredClone(files);
         ^
TypeError: Unable to deserialize data.
      at main (/home/booteille/Dev/bun-structured-clone-test/index.ts:15:5)
      at /home/booteille/Dev/bun-structured-clone-test/index.ts:19:1

Bun v1.1.31 (Linux x64)
```

### Additional information

Passing an object containing files should also work:

```ts
structuredClone({file1, file2})
```

**Comment by Jarred-Sumner** [comment]
Fixed in #22282
