### ISSUE TITLE
VsCode debug broken in 1.1.31, works in 1.1.30

### ISSUE THREAD

**Issue by Jonatthu** [oven-sh/bun#14674]
### What version of Bun is running?

1.1.31

### What platform is your computer?

MacOS Darwin 24.0.0 arm64 arm

### What steps can reproduce the bug?

Set a breakpoint using vscode bun extension on bun

Just use Bun.serve.

The server work with regular bun run

### What is the expected behavior?

That actually the server starts

**Comment by Jarred-Sumner** [comment]
Confirming this seems to be broken. Pressing pause doesn't work. It doesn't resolve breakpoints.

![Image](https://github.com/user-attachments/assets/226c603d-c71f-432a-9cde-2a8e27aad6dc)

**Comment by Jarred-Sumner** [comment]
Potentially related:
```js
 Error: Invalid debug adapter
    at d.p (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2629:95)
    at d.$acceptDAMessage (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2628:17358)
    at T.S (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2459:14840)
    at T.Q (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2459:14606)
    at T.M (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2459:13639)
    at T.L (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2459:12474)
    at $.value (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2459:11169)
    at l.B (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:437:732)
    at l.fire (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:437:949)
    at s.fire (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1120:14822)
    at G.onmessage (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2475:8223)
```

**Comment by nektro** [comment]
started failing after https://github.com/oven-sh/bun/commit/bbb41beadc5e892bdbf4843e8b08c2a26903b92f

**Comment by nektro** [comment]
looks like diff became `JSGlobalObjectDebuggable::create` instead `BunJSGlobalObjectDebuggable::create` testing that fix and will PR if it works
