### ISSUE TITLE
classic-level npm module crashes

### ISSUE THREAD

**Issue by mkahvi** [oven-sh/bun#14686]
### What version of Bun is running?

1.1.31

### What platform is your computer?

Win11 (Microsoft Windows NT 10.0.22631.0 x64)

### What steps can reproduce the bug?

Don't have simple examples, so...

1) Clone the [PF1 FVTT](<https://gitlab.com/foundryvtt_pathfinder1e/foundryvtt-pathfinder1>) project.
2) `npm ci`
3) `bun run build`
4) `bun run packs:extract`

### What is the expected behavior?

Everything works

### What do you see instead?

```
ModuleError: Iterator is not open: cannot call next() after close()
    at Iterator._next (...\pf1\node_modules\abstract-level\lib\deferred-iterator.js:56:31)
    at ...\pf1\node_modules\abstract-level\lib\deferred-iterator.js:54:32
    at [undefer] (...\pf1\node_modules\abstract-level\abstract-level.js:755:7)
    at ...\pf1\node_modules\abstract-level\abstract-level.js:163:25 {
  code: 'LEVEL_ITERATOR_NOT_OPEN'
}
error: script "packs:extract" exited with code 1
```
This error does not happen if you instead run `npm run packs:extract`

### Additional information

The error occurs via `@foundryvtt/foundryvtt-cli` dependency which uses [classic-level](<https://www.npmjs.com/package/classic-level>) (`abstract-level` in the error)

The project is not currently built to use bun. This is just me experimenting on the possibility of using bun with it and if there's actually any benefits (so far performance when it doesn't crash is roughly identical).

**Comment by mkahvi** [comment]
This no longer seems to be a problem with `1.1.36`, so closing it as indirectly solved.

**Comment by mkahvi** [comment]
This problem has resurfaced after upgrading from 1.1.43 to 1.1.45

**Comment by patrickdalla** [comment]
Hi I came across this same error.

In my case, it hapen when I start a second instance of my app from command line. This second instance is configured to access different database files from the first app.

The first instance works.
