### ISSUE TITLE
AbortController usage in module scope crashes bun with uncatchable error

### ISSUE THREAD

**Issue by Zig1375** [oven-sh/bun#14742]
The #9429 was closed, but the issue is still persist.

What version of Bun is running?
1.0.32

What platform is your computer?
Darwin 24.0.0 arm64 arm

What steps can reproduce the bug?
Usage of the AbortController can crash bun in ways that are uncatchable with a AbortError: The operation was aborted. logged to the terminal. The process exits with a 1 status code .

Here's a very simple example:

```js
import { setTimeout as sleep } from "node:timers/promises";

const abortController = new AbortController();

async function test() {
  await sleep(
    2000,
    () => {
      console.log("Timeout");
    },
    { signal: abortController.signal }
  );
}

test().catch((e) => {
  console.error("caught:", e);
});

abortController.abort();
```

The problem repeats from time to time.

**Comment by Jarred-Sumner** [comment]
It isn't crashing, its exiting with an exit code of 0 and logging the exception as expected.
```js
import { setTimeout as sleep } from "node:timers/promises";

const abortController = new AbortController();

async function test() {
  await sleep(
    2000,
    () => {
      console.log("Timeout");
    },
    { signal: abortController.signal }
  );
}

test().catch((e) => {
  console.error("caught:", e);
});

abortController.abort();
```

Produces the following:
```js
❯ bun repro.mjs && echo 'did not crash'
caught: 14 |
15 | test().catch((e) => {
16 |   console.error("caught:", e);
17 | });
18 |
19 | abortController.abort();
                     ^
error: The operation was aborted
 code: "ABORT_ERR"

      at new AbortError (node:timers/promises:167:14)
      at node:timers/promises:42:18
      at /Users/jarred/Build/dbest-stack/repro.mjs:19:17

did not crash
```

```
❯ node repro.mjs && echo 'did not crash'
caught: AbortError: The operation was aborted
    at Timeout.cancelListenerHandler (node:timers/promises:48:12)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:816:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:751:26)
    at abortSignal (node:internal/abort_controller:382:10)
    at AbortController.abort (node:internal/abort_controller:404:5)
    at file:///Users/jarred/Build/dbest-stack/repro.mjs:19:17
    ... 2 lines matching cause stack trace ...
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5) {
  code: 'ABORT_ERR',
  [cause]: DOMException [AbortError]: This operation was aborted
      at new DOMException (node:internal/per_context/domexception:53:5)
      at AbortController.abort (node:internal/abort_controller:403:18)
      at file:///Users/jarred/Build/dbest-stack/repro.mjs:19:17
      at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
      at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:483:26)
      at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)
}
did not crash
```

Happy to re-open this if you provide a reproduction that causes Bun to exit with a non-zero exit code or otherwise
