### ISSUE TITLE
create react-app fails if npm is not in path

### ISSUE THREAD

**Issue by Bugg4** [oven-sh/bun#14773]
### What version of Bun is running?

1.1.33-canary.12+74e440d58

### What platform is your computer?

Microsoft Windows NT 10.0.19041.0 x64

### What steps can reproduce the bug?

`bun create react-app hello`

### What is the expected behavior?

Bun correctly creates the React app project

### What do you see instead?

```powershell

Creating a new React app in C:\Users\WDAGUtilityAccount\Desktop\test\hello.

'npm' is not recognized as an internal or external command,
operable program or batch file.
Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

'npm' is not recognized as an internal or external command,
operable program or batch file.
1 | 'use strict';
2 |
3 | const isWin = process.platform === 'win32';
4 |
5 | function notFoundError(original, syscall) {
6 |     return Object.assign(new Error(`${syscall} ${original.command} ENOENT`), {
                             ^
error: spawn npm ENOENT
   code: "ENOENT"
 syscall: "spawn npm"
   path: "npm"

      at notFoundError (C:\Users\WDAGUtilityAccount\AppData\Local\Temp\bunx-4277763502-create-react-app@latest\node_modules\cross-spawn\lib\enoent.js:6:26)
      at C:\Users\WDAGUtilityAccount\AppData\Local\Temp\bunx-4277763502-create-react-app@latest\node_modules\cross-spawn\lib\enoent.js:27:25
      at #handleOnExit (node:child_process:449:16)

Bun v1.1.33-canary.12+74e440d58 (Windows x64)
```

### Additional information

Tested both on Windows and WSL.

On WSL, fails with a slightly different error, still related to not finding npm in path (same as https://github.com/oven-sh/bun/issues/5995#issuecomment-2191573753) :

```bash

Creating a new React app in /mnt/c/MYCODE/Personale/.temp/hello.

/bin/sh: 1: npm: not found
Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...


Aborting installation.
Unexpected error. Please report it as a bug:
 7 | function spawn(command, args, options) {
 8 |     // Parse the arguments
 9 |     const parsed = parse(command, args, options);
10 |
11 |     // Spawn the child process
12 |     const spawned = cp.spawn(parsed.command, parsed.args, parsed.options);
                            ^
TypeError: Executable not found in $PATH: "npm"
 code: "ERR_INVALID_ARG_TYPE"

      at spawn (node:child_process:580:8)
      at spawn (node:child_process:9:15)
      at spawn (/tmp/bunx-1000-create-react-app@latest/node_modules/cross-spawn/index.js:12:24)
      at /tmp/bunx-1000-create-react-app@latest/node_modules/create-react-app/createReactApp.js:383:19
      at new Promise (1:11)
      at install (/tmp/bunx-1000-create-react-app@latest/node_modules/create-react-app/createReactApp.js:334:10)
      at /tmp/bunx-1000-create-react-app@latest/node_modules/create-react-app/createReactApp.js:461:16


Deleting generated file... package.json
Deleting hello/ from /mnt/c/MYCODE/Personale/.temp
Done.
```

**Comment by nektro** [comment]
checking the source (https://unpkg.com/browse/create-react-app@5.0.1/createReactApp.js) it appears `create-react-app` presently only detects yarn and npm. supporting other package managers such as Bun Install is an enhancement that would have to be made upstream since while Bun is still the runtime executing this script, they are explicitly calling out to `npm install` as a subprocess which we cannot control.

We're happy to work with the `create-react-app` team if they need any assistance making this change but for now im going to close this issue as there is nothing immediately actionable to do on our end.
