### ISSUE TITLE
TypeError: Argument 1 ('event') to EventTarget.dispatchEvent must be an instance of Event. code: "ERR_INVALID_ARG_TYPE"

### ISSUE THREAD

**Issue by KyrylR** [oven-sh/bun#14876]
### What version of Bun is running?

1.1.33

### What platform is your computer?

Darwin 24.0.0 arm64 arm

### What steps can reproduce the bug?

Clone the: https://github.com/KyrylR/bun-snarkjs-bug

And just run: ```bun run index.ts```

### What is the expected behavior?

But you can use ts-node, and everything works fine (I have used ``` bun ts-node index.ts ```)

Expected output:

```
{
  "proof": {
    "pi_a": [
      "21236250006169796352207286511569407019391404800908777765287033465565737708287",
      "8216410824927631461534034052562982645588558861634320827849577106326568399512",
      "1"
    ],
    "pi_b": [
      [
        "475599640245628625817183026353739382200906861384860100192871892078266508149",
        "2986568908686256832015144204184499153036499198425747032495992918671442747889"
      ],
      [
        "15479813379314021197986280364589686808509053033739574067629958591049345105317",
        "17148894726717770081779360051529861032917889084973039189861167185060593648257"
      ],
      [
        "1",
        "0"
      ]
    ],
    "pi_c": [
      "8554346995919911003109068839433437470965474554200646024639265045532154940629",
      "4622909383007142628747367195968652860342560574797879391642395988833961866134",
      "1"
    ],
    "protocol": "groth16",
    "curve": "bn128"
  },
  "publicSignals": [
    "9962591004958373796587384861155724646515421461836279479625282758066943696076",
    "5092986097197808720933391904982030082759529887148192133346193619492724983554"
  ]
}
```

### What do you see instead?

```
170 |     event.data = data;
171 |     if (q == null) self.dispatchEvent(event);else q.push(event);
172 |   });
173 |   threads.parentPort.on('error', err => {
174 |     err.type = 'Error';
175 |     self.dispatchEvent(err);
               ^
TypeError: Argument 1 ('event') to EventTarget.dispatchEvent must be an instance of Event
 code: "ERR_INVALID_ARG_TYPE"

      at /Users/kyrylr/Desktop/project/node_modules/web-worker/cjs/node.js:175:10
170 |     event.data = data;
171 |     if (q == null) self.dispatchEvent(event);else q.push(event);
172 |   });
173 |   threads.parentPort.on('error', err => {
174 |     err.type = 'Error';
175 |     self.dispatchEvent(err);
               ^
TypeError: Argument 1 ('event') to EventTarget.dispatchEvent must be an instance of Event
 code: "ERR_INVALID_ARG_TYPE"

      at /Users/kyrylr/Desktop/project/node_modules/web-worker/cjs/node.js:175:10
170 |     event.data = data;
171 |     if (q == null) self.dispatchEvent(event);else q.push(event);
172 |   });
173 |   threads.parentPort.on(sh: trace trap  bun run index.ts
```

**Comment by Jarred-Sumner** [comment]
Let us know if you still run into this after upgrading to version 1.3.0

**Comment by KyrylR** [comment]
@heimskr Yeah, it seems to resolve the issue, but in case of the snarkjs package it does not help (the snarkjs stops working properly for some reason)

When I run the ```bun run index.ts``` with web-worker package of version 1.3.0, nothing is looged to the console

On the other hand, I have an output when I am using the ts-node

**Comment by KyrylR** [comment]
Sorry for the long reply

cc @Jarred-Sumner

**Comment by anudit** [comment]
@Jarred-Sumner This still doesn't work with `web-worker@1.5.0` and `bun@1.2.9`

```ts
import { buildBn128, F1Field } from "ffjavascript";

async function main() {
    // false fails (enables workers), true works (disables workers).
    let bn128 = await buildBn128(true);
    const F = new F1Field(bn128.r);

    const a = F.e("9");
    const b = F.sqrt(a);
    console.log(b) // 3n

    bn128.terminate();
}

main()
```

Same: https://github.com/oven-sh/bun/issues/11005

**Comment by anudit** [comment]
@Jarred-Sumner Still doesn't work on `v1.2.13`
