### ISSUE TITLE
`error: h2 is not supported` in `http2-wrapper` package

### ISSUE THREAD

**Issue by jnv** [oven-sh/bun#14958]
### What version of Bun is running?

1.1.34+5e5e7c60f

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

(For faster reproduction, here is a repository with the script below and dependencies: https://github.com/jnv/http2-wrapper-bun-repro)

1. Setup new bun project, install [http2-wrapper](https://github.com/szmarczak/http2-wrapper) with `bun add http2-wrapper`
2. Copy the script in [usage](https://github.com/szmarczak/http2-wrapper#usage) to js file (e.g. `usage.js`):
    ```js
    const http2 = require('http2-wrapper');

    const options = {
      hostname: 'nghttp2.org',
      protocol: 'https:',
      path: '/httpbin/post',
      method: 'POST',
      headers: {
        'content-length': 6,
      },
    };

    const request = http2.request(options, (response) => {
      console.log('statusCode:', response.statusCode);
      console.log('headers:', response.headers);

      const body = [];
      response.on('data', (chunk) => {
        body.push(chunk);
      });
      response.on('end', () => {
        console.log('body:', Buffer.concat(body).toString());
      });
    });

    request.on('error', console.error);

    request.write('123');
    request.end('456');
    ```
4. Run the script with `bun usage.js`

### What is the expected behavior?

The script exits successfully and writes a HTTP response body.

### What do you see instead?

The script crashes with the following error:

```
113 |   }
114 | };
115 | 
116 | // This is basically inverted `closeCoveredSessions(...)`.
117 | const closeSessionIfCovered = (where, coveredSession) => {
118 |   for (let index = 0; index < where.length; index++) {
                                   ^
TypeError: undefined is not an object (evaluating 'where.length')
      at closeSessionIfCovered (/path/to/http2-wrapper-bun-repro/node_modules/http2-wrapper/source/agent.js:118:30)
      at /path/to/http2-wrapper-bun-repro/node_modules/http2-wrapper/source/agent.js:524:7
      at emit (node:events:56:48)
      at #onConnect (node:http2:2076:13)
      at onConnect (node:http2:2218:23)
      at emit (node:events:56:48)
      at handshake (node:net:90:14)
error: h2 is not supported
 code: "ERR_HTTP2_ERROR"

      at native:1:1
      at #onConnect (node:http2:2076:13)
      at onConnect (node:http2:2218:23)
      at emit (node:events:56:48)
      at handshake (node:net:90:14)
```

### Additional information

http2-wrapper is used by [got](https://github.com/sindresorhus/got) among others.

Looking for the error, I found it [in bun's source](https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/js/node/http2.ts#L2812). Perhaps TLSSocket is behaving differently from Node?

**Comment by cirospaciari** [comment]
Today `node:http2` on bun don't support HTTP/1.1 fallback and when using TLS expects the h2 ALPN Protocol with is not being received in this case, when not using TLS its assumes h2c protocol also know as HTTP/2 over TCP or HTTP/2 over cleartext. The difference in node.js is that node.js can receive HTTP/1.1 fallback and upgrade to HTTP/2 using the Upgrade header (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Upgrade), in the future HTTP/1.1 fallback will be implemented and this behavior will match node.js until there I recommend the server to use ALPN Protocol since is the fastest and most supported way of starting a HTTP/2 connection.

**Comment by ivawzh** [comment]
This issue is blocking us from using bun for Crawlee https://github.com/apify/crawlee

**Comment by 5ergiu** [comment]
> This issue is blocking us from using bun for Crawlee https://github.com/apify/crawlee

I had this error `Requested origin https://x does not match server https://x:443` when running Crawlee on Bun.  

The problem is Bun’s stricter HTTP/2 handling. Crawlee uses `got-scraping` under the hood, which defaults to HTTP/2, so you need to force HTTP/1.1.  

✅ Solution for Crawlee:

```ts
const crawler = new CheerioCrawler({
  preNavigationHooks: [
    (_, gotOptions) => {
      gotOptions.http2 = false  // 👈 force HTTP/1.1
    },
  ],
  requestHandler: async ({ request, $ }) => {
    console.log('Scraped:', request.url);
  },
});

**Comment by jnv** [comment]
@5ergiu I believe the choice of HTTP/2 is intentional to avoid bot detection without running the full headless browser. Anyway, [got-scraping](https://github.com/apify/got-scraping) is deprecated now.
