### ISSUE TITLE
Bun cannot initialize expo app with `--bun` flag

### ISSUE THREAD

**Issue by Nanome203** [oven-sh/bun#14955]
### What version of Bun is running?

1.1.34+5e5e7c60f

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

`bun --bun create expo my-app`

### What is the expected behavior?

expo project gets created

### What do you see instead?
- Without Node installed:
```pwsh
× Something went wrong in downloading and extracting the project files: spawn npm.cmd ENOENT
Error: spawn npm.cmd ENOENT
90 |
91 |     {bold  npm:} {cyan npm create ${t}}
92 |     {bold yarn:} {cyan yarn create ${t}}
93 |     {bold pnpm:} {cyan pnpm create ${t}}
94 |     {bold  bun:} {cyan bun create ${t}}
95 |     `)}const{AnalyticsEventPhases:a,AnalyticsEventTypes:l,flushAsync:v,track:A}=await Promise.resolve().then((()=>u(i(4575))));try{const h=await(0,g.resolveStringOrBooleanArgsAsync)(t,r,{"--template":Boolean,"--example":Boolean,"-t":"--template","-e":"--example"});y(`Default args:\n%O`,o);y(`Parsed:\n%O`,h);const{createAsync:p}=await Promise.resolve().then((()=>u(i(1961))));await p(h.projectRoot,{yes:!!o["--yes"],template:h.args["--template"],example:h.args["--example"],install:!o["--no-install"]});A({event:l.CREATE_EXPO_APP,properties:{phase:a.SUCCESS}});await v()}catch(t){if(!(t instanceof d.ExitError)){m.Log.exception(t)}A({event:l.CREATE_EXPO_APP,properties:{phase:a.FAIL,message:t.cause}});await v().finally((()=>{process.exit(t.code||1)}))}finally{const t=await(await Promise.resolve().then((()=>u(i(5897))))).default;await t()}}run()},9247:(t,r,i)=>{"use strict";Object.defineProperty(r,"__esModule",{value:true});r.CLI_NAME=void 0;r.CLI_NAME=i(4147).name},1961:function(t,r,i){"use strict";var o=this&&this._ | ... truncated

TypeError: The "code" argument must be an integer
      at C:\Users\ME\AppData\Local\Temp\bunx-791187370-create-expo@latest\node_modules\create-expo\build\index.js:95:736

Bun v1.1.34 (Windows x64)
```
- With Node installed
```pwsh
× Something went wrong in downloading and extracting the project files: Can't read JSON file: D:\test\package.json
└─ Cause: ENOENT: No such file or directory
JsonFileError: Can't read JSON file: D:\test\package.json
└─ Cause: ENOENT: No such file or directory
90 |
91 |     {bold  npm:} {cyan npm create ${t}}
92 |     {bold yarn:} {cyan yarn create ${t}}
93 |     {bold pnpm:} {cyan pnpm create ${t}}
94 |     {bold  bun:} {cyan bun create ${t}}
95 |     `)}const{AnalyticsEventPhases:a,AnalyticsEventTypes:l,flushAsync:v,track:A}=await Promise.resolve().then((()=>u(i(4575))));try{const h=await(0,g.resolveStringOrBooleanArgsAsync)(t,r,{"--template":Boolean,"--example":Boolean,"-t":"--template","-e":"--example"});y(`Default args:\n%O`,o);y(`Parsed:\n%O`,h);const{createAsync:p}=await Promise.resolve().then((()=>u(i(1961))));await p(h.projectRoot,{yes:!!o["--yes"],template:h.args["--template"],example:h.args["--example"],install:!o["--no-install"]});A({event:l.CREATE_EXPO_APP,properties:{phase:a.SUCCESS}});await v()}catch(t){if(!(t instanceof d.ExitError)){m.Log.exception(t)}A({event:l.CREATE_EXPO_APP,properties:{phase:a.FAIL,message:t.cause}});await v().finally((()=>{process.exit(t.code||1)}))}finally{const t=await(await Promise.resolve().then((()=>u(i(5897))))).default;await t()}}run()},9247:(t,r,i)=>{"use strict";Object.defineProperty(r,"__esModule",{value:true});r.CLI_NAME=void 0;r.CLI_NAME=i(4147).name},1961:function(t,r,i){"use strict";var o=this&&this._ | ... truncated

TypeError: The "code" argument must be an integer
      at C:\Users\ME\AppData\Local\Temp\bunx-791187370-create-expo@latest\node_modules\create-expo\build\index.js:95:736

Bun v1.1.34 (Windows x64)
```
### Additional information

Can initialize expo project with no problem using npx
Also, if Node is installed, then without `--bun` flag, bun can initialize expo project

**Comment by Nanome203** [comment]
Seems like this error is on expo's side. Used to be able to create expo project on bun v1.1.33, now i can't
