### ISSUE TITLE
md5 value not same as nodejs

### ISSUE THREAD

**Issue by qiphon** [oven-sh/bun#1514]
### What version of Bun is running?

0.2.2

### What platform is your computer?

mac m1 

### What steps can reproduce the bug?

import * as crypto from 'crypto';
crypto.createHash('md5').update(str).digest('hex');

word string  -   正确答案

node   -   930581e8505e4b763a96043829396e1c
bun    -   340aadd190173976c40a2e17310179f9

node version  v18.12.1 

bun  version  v0.2.2

### What do you see instead?

it maybe get same md5 value as node

**Comment by Jarred-Sumner** [comment]
@robobun 

```js
console.log("   Bun.MD5:" + Bun.MD5.hash(`正确答案`));
console.log("crypto.MD5:" + crypto.createHash('md5').update(`正确答案`).digest('hex'));

**Comment by robobun** [comment]
@Jarred-Sumner here you go!
```tsx
   Bun.MD5:77,51,186,135,252,150,37,224,64,2,78,167,172,154,93,136
1 | 
2 | console.log("crypto.MD5:" + crypto.createHash("md5").update(`\u6B63\u786E\u7B54\u6848`).digest("hex"));
                               ^
TypeError: crypto.createHash is not a function. (In 'crypto.createHash("md5")', 'crypto.createHash' is undefined)
      at /tmp/bun-dvggHR/index.js:3:28
```
<details>
  <summary>Code</summary>
  
```tsx
console.log("   Bun.MD5:" + Bun.MD5.hash(`正确答案`));

console.log("crypto.MD5:" + crypto.createHash('md5').update(`正确答案`).digest('hex'));
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._

**Comment by Jarred-Sumner** [comment]
@robobun 
```js
import * as crypto from 'crypto';

console.log("   Bun.MD5:", Bun.MD5.hash(`正确答案`, "hex"));
console.log("crypto.MD5:", crypto.createHash('md5').update(`正确答案`).digest('hex'));
```

**Comment by robobun** [comment]
@Jarred-Sumner here you go!
```tsx
   Bun.MD5: 4d33ba87fc9625e040024ea7ac9a5d88
crypto.MD5: 4d33ba87fc9625e040024ea7ac9a5d88
```
<details>
  <summary>Code</summary>
  
```tsx
import * as crypto from 'crypto';



console.log("   Bun.MD5:", Bun.MD5.hash(`正确答案`, "hex"));

console.log("crypto.MD5:", crypto.createHash('md5').update(`正确答案`).digest('hex'));
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._

**Comment by Jarred-Sumner** [comment]
From node
```js
~
❯ node
Welcome to Node.js v18.11.0.
Type ".help" for more information.
> require("crypto").createHash("md5").update("正确答案").digest("hex")
'4d33ba87fc9625e040024ea7ac9a5d88'
>
```

hmm

**Comment by robobun** [comment]
@Jarred-Sumner here you go!
```tsx
error: Unexpected ❯
❯ node
^
/tmp/bun-ouhkj1/index.js:3:1 4
```
<details>
  <summary>Code</summary>
  
```tsx
~

❯ node

Welcome to Node.js v18.11.0.

Type ".help" for more information.

> require("crypto").createHash("md5").update("正确答案").digest("hex")

'4d33ba87fc9625e040024ea7ac9a5d88'

>
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._

**Comment by robobun** [comment]
@Jarred-Sumner here you go!
```tsx
   Bun.MD5:77,51,186,135,252,150,37,224,64,2,78,167,172,154,93,136
warn: Invalid original column value
/tmp/bun-DfvCFl/index.js:1:0 201 | 
2 | console.log("crypto.MD5:" + crypto.createHash("md5").update(`\u6B63\u786E\u7B54\u6848`).digest("hex"));
                               ^
TypeError: crypto.createHash is not a function. (In 'crypto.createHash("md5")', 'crypto.createHash' is undefined)
      at /tmp/bun-DfvCFl/index.js:2:28
```
<details>
  <summary>Code</summary>
  
```tsx
console.log("   Bun.MD5:" + Bun.MD5.hash(`正确答案`));

console.log("crypto.MD5:" + crypto.createHash('md5').update(`正确答案`).digest('hex'));
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._
