### ISSUE TITLE
Bun stack traces with eval() are not good

### ISSUE THREAD

**Issue by johnfn** [oven-sh/bun#15172]
### What version of Bun is running?

1.1.34+5e5e7c60f

### What platform is your computer?

Darwin 24.0.0 arm64 arm

### What steps can reproduce the bug?

let src = "console.log(1); console.log(2); throw new Error('Test')"
eval(src)

### What is the expected behavior?

Error on the 3rd line of the evaluated string

### What do you see instead?

Error on eval()

```
627 |   
628 | 
629 |  
630 | 
631 |  
632 |   eval(myCodeString);
            ^
error: Test
      at compileAndRun 
      at /Users/code/myproject
```

### Additional information

`npx tsx myFile.ts` correctly reports the location of the thrown error

This is particularly problematic if you're evaluating a lot of code, which I am

**Comment by Jarred-Sumner** [comment]
Old:
```js
❯ bun-1.1.34 a.js
1
2
1 | let src = "console.log(1); console.log(2); throw new Error('Test')"
2 | eval(src)
                                          ^
error: Test
      at /Users/jarred/Code/site/a.js:2:1

Bun v1.1.34 (macOS arm64)
```
New:
```js
❯ bun a.js
1
2
1 | console.log(1); console.log(2); throw new Error('Test')
                                          ^
error: Test
      at eval (file:///Users/jarred/Code/site/a.js:1:39)
      at /Users/jarred/Code/site/a.js:2:1
      at loadAndEvaluateModule (1:11)
```

Note how it shows at the call site instead of the `eval` function call!
