### ISSUE TITLE
ENOTDIR: Not a directory, `readFileSync` and file and dir does not exist

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1525]
```js
2 | import { join } from "node:path";
3 | 
4 | export function readFile(cwd: string, filename: string): string {
5 |   const path = join(cwd, filename);
6 |   try {
7 |     return readFileSync(path, "utf-8");
               ^
ENOTDIR: Not a directory
   path: "wpt/wpt/url/idlharness-shadowrealm.window.js"
syscall: "open"
  errno: -20
```

This was run on MacOS silicon using canary (0.2.3). The file `wpt/wpt/url/idlharness-shadowrealm.window.js` does not exist, but the error is misleading. Instead of saying that `wpt/wpt` is not a directory, it should say that the file does not exist.

**Comment by Electroid** [comment]
Fixed as of Bun v1.0.7.

```js
❯ bun read.js
1 | 
2 |   require("fs").readFileSync("wpt/wpt/file.js");
     ^
ENOENT: No such file or directory
   path: "wpt/wpt/file.js"
 syscall: "open"
   errno: -2

      at example/read.js:1:0
      at globalThis (example/read.js:1:44)
```
