### ISSUE TITLE
Error prints twice when async exception is thrown in `describe` block

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1534]
```js
import { describe } from "bun:test";

describe("1", async () => {
  const response = await fetch("//invalid.com/");
});
```

```
temp.test.ts:
1 | import { expect, describe, test } from "bun:test";
2 | 
3 | describe("1", async () => {
   ^
ConnectionRefused: fetch() failed
 path: "//invalid.com/"
      at ~/code/spt/src/temp.test.ts:3:0
1 | import { expect, describe, test } from "bun:test";
2 | 
3 | describe("1", async () => {
   ^
ConnectionRefused: fetch() failed
 path: "//invalid.com/"
      at ~/code/spt/src/temp.test.ts:3:0

 0 pass
 0 fail
 Ran 0 tests across 1 files [237.00ms]
```

**Comment by blackmann** [comment]
Couldn't reproduce; exception was printed once. Can you verify with `~0.6.3`?

**Comment by Electroid** [comment]
This was fixed at some point.
