### ISSUE TITLE
`expect(...).resolves.toSatisfy(...)` passes in the promise directly

### ISSUE THREAD

**Issue by goldenstein64** [oven-sh/bun#15428]
### What version of Bun is running?

1.1.37+8ca0eb831

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Run these tests.

```ts
import { it, expect } from "bun:test";

it("compares promise value", () => {
  expect(Promise.resolve(42)).resolves.toSatisfy((v) => v === 42);
});

it("does not compare promise instance", () => {
  const promise = Promise.resolve(10);
  expect(promise).resolves.not.toSatisfy((v) => v === promise);
});
```

### What is the expected behavior?

Both tests should pass.

### What do you see instead?

Both tests fail.

```
> bun test promise-satisfy.test.ts
bun test v1.1.37 (8ca0eb83)

promise-satisfy.test.ts:
1 | import { it, expect } from "bun:test";
2 | 
3 | it("compares promise value", () => {
4 |   expect(Promise.resolve(42)).resolves.toSatisfy((v) => v === 42);
                                           ^
error: expect(received).toSatisfy(expected)

Expected: [Function]
Received: Promise { <resolved> }

      at [OMITTED]\promise-satisfy.test.ts:4:40
✗ compares promise value
4 |   expect(Promise.resolve(42)).resolves.toSatisfy((v) => v === 42);
5 | });
6 | 
7 | it("does not compare promise instance", () => {
8 |   const promise = Promise.resolve(10);
9 |   expect(promise).resolves.not.toSatisfy((v) => v === promise);
                                   ^
error: expect(received).not.toSatisfy(expected)

Expected: not [Function]

      at [OMITTED]\promise-satisfy.test.ts:9:32
✗ does not compare promise instance

 0 pass
 2 fail
 2 expect() calls
Ran 2 tests across 1 files. [40.00ms]
```

**Comment by goldenstein64** [comment]
Fixed a small typo in the reproduction, sorry!

**Comment by robin-kuzco** [comment]
The root cause of the issue is that matchers from `bun:test` will block until the `Promise` is resolved or rejected:
https://github.com/oven-sh/bun/blob/1bb211df56f528d536803d4a0c15bcfed49d0fb9/src/bun.js/test/expect.zig#L214

The matchers from jest do not block, and instead return `Promise`s that must be awaited.

For example,
```js
async function delay(value) {
  await new Promise((resolve) => setTimeout(resolve, value));
}

// Bun style resolves
test("sync", () => {
  expect.assertions(1);
  expect(delay(100)).resolves.toBe(undefined);
});

// Jest style resolves
test("async", async () => {
  expect.assertions(1);
  await expect(delay(100)).resolves.toBe(undefined);
});
```
