### ISSUE TITLE
Read-only instance accessors defined through Node-API incorrectly have setters

### ISSUE THREAD

**Issue by tniessen** [oven-sh/bun#15429]
### What version of Bun is running?

1.1.37+8ca0eb831

### What platform is your computer?

Linux 6.8.0-1017-azure x86_64 x86_64

### What steps can reproduce the bug?

Due to the nature of the bug, it is difficult to provide a minimal example.

I noticed the bug while trying to use [`node-pqclean`](https://github.com/tniessen/node-pqclean) from within Bun. I will fix the version to 0.6.0 and disable WebAssembly to ensure that both Node.js and Bun will use the native backend.

```console
npm install pqclean@0.6.0 --pqclean-backend=native
```

Here is a `test.js` file that demonstrates the bug using the native addon that was compiled by `node-pqclean` during its installation:

```js
const { KEM } = require('pqclean');

console.log(Object.getOwnPropertyDescriptor(KEM.prototype, 'keySize'));
console.log(Object.getOwnPropertyDescriptor(KEM.prototype, 'keySize').set?.apply({}));

const kem = new KEM('mceliece8192128');
Object.assign(kem, { keySize: 'error' });
```

Note the use of `Object.assign()` to make sure that the behavior does not depend on strict mode.

### What is the expected behavior?

Node.js 22 prints the following:

```console
$ node test.js 
{
  get: [Function (anonymous)],
  set: undefined,
  enumerable: false,
  configurable: false
}
undefined
/home/tniessen/bun-bug/test.js:7
Object.assign(kem, { keySize: 'error' });
       ^

TypeError: Cannot set property keySize of #<KEM> which has only a getter
    at Function.assign (<anonymous>)
    at Object.<anonymous> (/home/tniessen/bun-bug/test.js:7:8)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49

Node.js v22.11.0
```

Note that the property descriptor does not have a setter, and that `Object.assign()` throws an error.

### What do you see instead?

The most recent version of Bun prints the following:

```console
$ bun run test.js 
{
  get: [class get keySize],
  set: [Function],
  enumerable: true,
  configurable: true,
}
true
```

Note that, according to Bun, the property descriptor _does_ have a setter, that calling the setter returns `true`, and that `Object.assign()` does not throw an error.

### Additional information

The property is defined by `node-pqclean` [here](https://github.com/tniessen/node-pqclean/blame/7aa6117c00ee29802b641a31adeff5bb40baf5ed/native/node_pqclean.cc#L674):

```cpp
  Napi::Function func = KEM::DefineClass(env, "KEM", {
    // ...
    Napi::ObjectWrap<KEM>::InstanceAccessor("keySize", &KEM::GetKeySize, nullptr),
    // ...
  });
```

Note that the setter callback is set to `nullptr`.

It seems to me that Bun's implementation of Node-API will always create a no-op setter in that case, instead of omitting the setter, which would explain the behavior I described above:

https://github.com/oven-sh/bun/blob/f21fffd1bf8bee80698efea0938436e53a30c9a2/src/bun.js/bindings/napi.cpp#L562-L570

**Comment by 190n** [comment]
Thanks a lot for the detailed report. We've been fixing a lot of Node-API bugs in #14501, and we've rewritten much of the function you identified. Can you try running `bunx bun-pr 14501` to download a build from that PR, and use the binary it downloads (it will print out the path) to see if this issue is still present?

**Comment by tniessen** [comment]
@190n Amazing, it works:

```console
$ bun-769c6de751dbbf89ed49e93f35a178d4f5c2cec9-pr14501 run test.js 
{
  get: [class get keySize],
  set: undefined,
  enumerable: false,
  configurable: false,
}
undefined
2 | 
3 | console.log(Object.getOwnPropertyDescriptor(KEM.prototype, 'keySize'));
4 | console.log(Object.getOwnPropertyDescriptor(KEM.prototype, 'keySize').set?.apply({}));
5 | 
6 | const kem = new KEM('mceliece8192128');
7 | Object.assign(kem, { keySize: 'error' });
           ^
TypeError: Attempted to assign to readonly property.
      at /home/tniessen/bun-bug/test.js:7:8

Bun v1.1.38-canary.214+769c6de75 (Linux x64)
```
