### ISSUE TITLE
Sass fails to be minified properly using Bun build

### ISSUE THREAD

**Issue by BjornTheProgrammer** [oven-sh/bun#15441]
### What version of Bun is running?

1.1.37

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

When attempting to build a script that calls the `sass.compileString` function, it works if the output is not minified, but fails if it is.

A repo replicating this issue can be found [here](https://github.com/BjornTheProgrammer/bun-sass-issue)

src/index.ts
```ts
import * as sass from 'sass';

// On a completely unrelated note, sass-embedded just hangs forever,
// no matter what you do when built.
// import * as sass from 'sass-embedded';

export const content = sass.compileString(`body {
	background-color: #fff,
}`).css;
```

build.ts
```ts
import { $ } from "bun";

await $`rm -rf dist`

await Bun.build({
	entrypoints: ['./src/index.ts'],
	outdir: './dist',
	minify: true, // issue.ts failes to run when minify is set to true, but works when set to false
	target: 'node',
});

```

issue.ts
```ts
import { content } from "./dist/index.js"

console.log('content:', content);
```

### What is the expected behavior?

The following should be outputted to the terminal
```bash
content: body {
  background-color: #fff;
}
```

### What do you see instead?

```bash
1 | import{createRequire as $G}from"node:module";var xG=Object.create;var{getPrototypeOf:vG,defineProperty:pZ,getOwnPropertyNames:fG}=Object;var gG=Object.prototype.hasOwnProperty;var yG=(Y0,z0,D0)=>{D0=Y0!=null?xG(vG(Y0)):{};let h=z0||!Y0||!Y0.__esModule?pZ(D0,"default",{value:Y0,enumerable:!0}):D0;for(let A0 of fG(Y0))if(!gG.call(h,A0))pZ(h,A0,{get:()=>Y0[A0],enumerable:!0});return h};var cX=(Y0,z0)=>()=>(z0||Y0((z0={exports:{}}).exports,z0),z0.exports);var RJ=$G(import.meta.url);var cZ=cX(()=>{var __dirname="/Users/bjorn/Desktop/bun-sass-issue/node_modules/sass",__filename="/Users/bjorn/Desktop/bun-sass-issue/node_modules/sass/sass.dart.js";if(!globalThis._cliPkgExports)globalThis._cliPkgExports=[];var uX={};globalThis._cliPkgExports.push(uX);uX.load=function(Y0,z0){var D0=typeof process!=="undefined"&&(process.versions||{}).hasOwnProperty("node"),h=D0?Object.create(globalThis):globalThis;if(h.scheduleImmediate=typeof setImmediate!=="undefined"?function(K0){setImmediate(K0)}:function(K0){setTimeout(K0,0)},h.re | ... truncated

TypeError: undefined is not an object (evaluating 'Z._Universe_findRule(H, U._primary)[W]')
      at _Parser_handleIdentifier (/Users/bjorn/Desktop/bun-sass-issue/dist/index.js:1:88113)
      at _Parser_parse (/Users/bjorn/Desktop/bun-sass-issue/dist/index.js:1:86157)
      at _Universe_evalInEnvironment (/Users/bjorn/Desktop/bun-sass-issue/dist/index.js:1:81100)
      at toList$1$growable (/Users/bjorn/Desktop/bun-sass-issue/dist/index.js:76:128503)
      at SourceFile$fromString (/Users/bjorn/Desktop/bun-sass-issue/dist/index.js:21:5418)
      at SpanScanner$ (/Users/bjorn/Desktop/bun-sass-issue/dist/index.js:44:3251)
      at ScssParser$0 (/Users/bjorn/Desktop/bun-sass-issue/dist/index.js:54:29463)
      at BuiltInCallable$function0 (/Users/bjorn/Desktop/bun-sass-issue/dist/index.js:44:36285)
      at call$0 (/Users/bjorn/Desktop/bun-sass-issue/dist/index.js:195:23613)
      at /Users/bjorn/Desktop/bun-sass-issue/dist/index.js:1:3484

Bun v1.1.37 (macOS arm64)
error: script "issue" exited with code 1
```

### Additional information

This was discovered by another user @mindon when using [`bun-plugin-html`](https://github.com/BjornTheProgrammer/bun-plugin-html), and they got the same error message, the above is a simplified reproduction of the issue.

**Comment by pfgithub** [comment]
This is because function names are minified with `--minify-identifiers`, but sass (or maybe the dart compiler) is relying on the function names not changing.

Reproduction:
```js
$> cat a.js
function Demo(){}
console.log(Demo.name);
$> bun build a.js | bun -
Demo
$> bun build --minify-identifiers a.js | bun -
o
```

The same issue occurs using esbuild and many other minifiers with `--minify-identifiers`, although it is sometimes a bit harder to trigger:

```js
$> cat a.js
const o = {b: function Demo(){}};
console.log(o.b.name);
$> bunx esbuild a.js | bun -
Demo
$> bunx esbuild --minify-identifiers a.js | bun -
n
```

esbuild offers a flag `--keep-names` which preserves the function names and works.

---

To get around this for now, build without `--minify-identifiers`. eg:

```js
// Bun.build()
await Bun.build({
	entrypoints: ['./src/index.ts'],
	outdir: './dist',
	minify: {whitespace: true, syntax: true},
	target: 'node',
});

// command line
bun build src/index.ts --outdir=dist --minify-whitespace --minify-syntax --target=node
```

**Comment by BjornTheProgrammer** [comment]
I looked into this myself earlier, and I tracked down the bug in sass specifically to a `constructor.name` call. What is strange, however, is that it would be expected for the same error to occur in esbuild when `keepNames` is set to false, however this just is not the case.

build.ts
```ts
import { $ } from "bun";
import esbuild from "esbuild"

await $`rm -rf dist`
await $`rm -rf dist-esbuild`

await Bun.build({
	entrypoints: ['./src/index.ts'],
	outdir: './dist',
	target: 'node',
	minify: {
		whitespace: true,
		identifiers: false, // This works as expected
		syntax: true,
	},
});

// This also works for some reason, despite keepNames explicitly being disabled and minifyIdentifiers being true.
await esbuild.build({
	entryPoints: ['./src/index.ts'],
	outdir: './dist-esbuild',
	format: 'esm',
	minify: true,
	minifyIdentifiers: true,
	minifySyntax: true,
	minifyWhitespace: true,
	bundle: true,
	keepNames: false
})
```

issue.ts
```ts
import { content } from "./dist/index"
import { content as esbuildContent } from "./dist-esbuild/index"

console.log('content:', content);
console.log('esbuildContent:', esbuildContent);
```

Output
```bash
content: body {
  background-color: #fff;
}
esbuildContent: body {
  background-color: #fff;
}
```

Does esbuild use a different mechanism to ensure that if a constructor.name is called its name doesn't get mangled? I tried investigating, but I couldn't figure it out.

The specific function that is causing this issue is `_instanceTypeFromConstructorMiss`, from within the build output. 

The function is the following
```js
_instanceTypeFromConstructorMiss(instance, $constructor) {
  var effectiveConstructor = instance instanceof A.Closure ? Object.getPrototypeOf(Object.getPrototypeOf(instance)).constructor : $constructor,
    rti = A._Universe_findErasedType(init.typeUniverse, effectiveConstructor.name);
  $constructor.$ccache = rti;
  return rti;
}
```
