### ISSUE TITLE
https-proxy-agent and socks-proxy-agent not working

### ISSUE THREAD

**Issue by volkovcute** [oven-sh/bun#15499]
### What version of Bun is running?

1.1.38

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

1. Created a JS file containing the following code:
```ts
import {HttpsProxyAgent} from 'https-proxy-agent';
import axios from "axios";

const proxy = `http://username:password@185.XXX.XXX.58:59975`;

const agent = new HttpsProxyAgent(proxy);

const main = async () => {
    try {
       axios.get('https://check-host.net/ip', {
           httpsAgent: agent
       }).then((r) => {
           console.log(r.data)
       })
    } catch (error) {
        console.error('Error:', error.message);
    }
};

main();
```
2. run with ```bun run ./src/testmenu.js```
3. run with ```node ./src/testmenu.js```

### What is the expected behavior?

The request must be sent using a proxy

### What do you see instead?

![Image](https://github.com/user-attachments/assets/9c6b0bda-5361-4358-a3fa-fc37dcfc67a0)

![Image](https://github.com/user-attachments/assets/71217c4e-1f5c-435d-bce3-b7c1f9a401f3)

![Image](https://github.com/user-attachments/assets/de2d9739-89af-4d18-8d60-099b1e314521)

### Additional information

The same thing happens with "socks-proxy-agent", while there are no problems with node

**Comment by RiskyMH** [comment]
It seems like the `proxy` package's test doesn't work well on bun either:

https://github.com/TooTallNate/proxy-agents/blob/main/packages/proxy/test/test.ts

```c
// $ bun test ./proxy-repo.test.js 
proxy-repo.test.js:
✓ proxy > authentication > should invoke the `server.authenticate()` function when set [16.00ms]
✓ proxy > authentication > should provide the HTTP client with a 407 response status code
143 |             socket.write(`CONNECT 127.0.0.1:80 HTTP/1.1\r
144 | \r
145 | `);
146 |             socket.setEncoding("utf8");
147 |             const [data] = await once(socket, "data");
148 |             assert(data.indexOf("HTTP/1.1 407") == 0);
                  ^
AssertionError: false == true
 code: "ERR_ASSERTION"

      at proxy-repo.test.js:148:13
      at processTicksAndRejections (native:7:39)
✗ proxy > authentication > should close the socket after a CONNECT request's 407 response status code [15.00ms]
42 | ` + `Proxy-Connection: Keep-Alive\r
43 | ` + `\r
44 | `);
45 |         socket.setEncoding("utf8");
46 |         const [data] = await once(socket, "data");
47 |         assert(data.indexOf(`HTTP/1.1 200 OK\r
             ^
AssertionError: false == true
 code: "ERR_ASSERTION"

      at proxy-repo.test.js:47:9
      at processTicksAndRejections (native:7:39)
✗ proxy > should proxy HTTP GET requests (keep-alive)
75 | ` + `Proxy-Connection: Keep-Alive\r
76 | ` + `\r
77 | `);
78 |         socket.setEncoding("utf8");
79 |         const [data] = await once(socket, "data");
80 |         assert(data.indexOf(`HTTP/1.1 200 Connection established\r
             ^
AssertionError: false == true
 code: "ERR_ASSERTION"

      at proxy-repo.test.js:80:9
      at processTicksAndRejections (native:7:39)
✗ proxy > should establish connection for CONNECT requests (keep-alive)

 2 pass
 3 fail
Ran 5 tests across 1 files. [1078.00ms]
```

**Comment by cirospaciari** [comment]
wonder how to repro this since `test/js/bun/http/proxy.test.ts` passes using axios with `https-proxy-agent`, if the agent has a proxy URL/string property it will be used, but socks is not supported right now infact.

**Comment by Confucian-e** [comment]
I'm using on MacOS. Same Bug.

**Comment by UjmaIT** [comment]
Maybe this fits in here I have simlar issues creating a custom agent:
`//import axios from 'axios';
//import https from 'node:https';

const https = require('https');
const axios = require('axios');

class MyCustomAgent extends https.Agent {
    constructor(options) {
        super(options);
    }

    createConnection(options, callback) {
        console.log(`Custom connection to ${options.host}:${options.port}`);
        return super.createConnection(options, callback);
    }
}

const customAgent = new MyCustomAgent({ 
});

// Set up the options object with the custom agent
const options = {
    httpAgent: customAgent,
    httpsAgent: customAgent,

};

// Make the Axios request using the options object
axios.get('https://httpbin.io/ip', options)
    .then(response => {
        console.log(response.data);
    })
    .catch(error => {
        console.error('Error:', error.message);
    });
`

`$ node src/test_proxy.ts 
Custom connection to httpbin.io:443
{ origin: '1.2.3.4:53440' }

$ bun run src/test_proxy.ts 
{
  origin: "1.2.3.4:54530"}`

**Comment by erikschul** [comment]
IIUC, Bun will observe the `http_proxy` env variable, which causes Bun's http module to fail, because it doesn't support SOCKS.

I doubt it can be implemented in JavaScript, since, IIUC, it is a separate protocol from TCP and UDP, and therefore requires a low-level implementation.

**Comment by mattfysh** [comment]
I believe this is caused by the use of the `CONNECT example.com:443` http opening line, bun seems to expect the path (the string after the http verb) to begin with `/` whereas node does not

```ts
const tunnel = https.request({
  host: proxy.hostname,
  port: proxy.port || '443',
  method: 'CONNECT',
  path: `${url.hostname}:${url.port || '443'}`,
  headers: authHeaders,
  timeout: 5_000,
})
```

```sh
060 |       this._writableState.autoDestroy = !1, this.#fetchRequest = fetch(url, fetchOptions).then((response) => {
                          ^
TypeError: fetch() URL is invalid
 code: "ERR_INVALID_URL"

      at #startStream (node:http:1060:71)
      at _final (node:http:1094:22)
```

**Comment by long2ice** [comment]
So how to fix this?
