### ISSUE TITLE
400 error, bad multipart/form-data request from Codespaces

### ISSUE THREAD

**Issue by markgoho** [oven-sh/bun#15580]
### What version of Bun is running?

1.1.38

### What platform is your computer?

Codespaces

### What steps can reproduce the bug?

1. clone repo: https://github.com/markgoho/test-firebase-login
2. open in Codespaces
3. once Codespaces is built, in terminal, `bun install` (if re-2 hangs, ctrl+c to break out)
4. run `bunx firebase login --no-localhost` (you will need a google account)
5. follow steps up to pasting in auth code
6. error can be seen in `firebase-debug.log`

### What is the expected behavior?

firebase-tools should make a request to the observed url (accounts.google.com/o/auth2/token) and not error

### What do you see instead?

``` bash
[debug] [2024-12-04T18:26:26.462Z] >>> [apiv2][query] POST https://accounts.google.com/o/oauth2/token [none]
[debug] [2024-12-04T18:26:26.462Z] >>> [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[debug] [2024-12-04T18:26:26.483Z] <<< [apiv2][status] POST https://accounts.google.com/o/oauth2/token 400
[debug] [2024-12-04T18:26:26.484Z] <<< [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[debug] [2024-12-04T18:26:26.485Z] Token Fetch Error: FirebaseError: Request to https://accounts.google.com/o/oauth2/token had HTTP Error: 400, Bad multipart/form-data request.
    at new FirebaseError (/workspaces/test-firebase-login/node_modules/firebase-tools/lib/error.js:10:9)
    at responseToError (/workspaces/test-firebase-login/node_modules/firebase-tools/lib/responseToError.js:52:24)
    at <anonymous> (/workspaces/test-firebase-login/node_modules/firebase-tools/lib/apiv2.js:312:61)
    at processTicksAndRejections (native:7:39)
```

### Additional information

I've reported this issue in the `firebase-tools` repo as well: https://github.com/firebase/firebase-tools/issues/8012

However, given the situation "can't be reproduced", and assuming they aren't also using bun, I'm assuming the issue is with bun as `node/npm` aren't present in the Codespace container.
``` bash
@markgoho ➜ /workspaces/test-firebase-login (trunk) $ node -v
bash: node: command not found
@markgoho ➜ /workspaces/test-firebase-login (trunk) $ npm -v
bash: npm: command not found
```

Possibly related: https://github.com/oven-sh/bun/issues/7917

**Comment by MohamedNoordin** [comment]
I'm also getting 400 Bad Request errors caused by external dependencies like @google/genai when using Bun. These issues never happen in Node.js.

**Comment by 7RST1** [comment]
This still happens on the newest canary build
