### ISSUE TITLE
createBrotliCompress crash and does not work

### ISSUE THREAD

**Issue by hhpr98** [oven-sh/bun#15600]
### What version of Bun is running?

1.1.38

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Using script at https://bun.sh/blog/bun-v1.1.8

```
import { createBrotliCompress } from "node:zlib";

const compressor = createBrotliCompress();
compressor.write("Hello, world!");
compressor.end();

const compressed = compressor.read();
console.log(compressed.toString("hex"));
// => 0b068048656c6c6f2c20776f726c642103
```

### What is the expected behavior?

the console will show "0b068048656c6c6f2c20776f726c642103"

### What do you see instead?

Crash when running bun application
![Image](https://github.com/user-attachments/assets/4a883445-f022-41b7-a2fa-e1ec1bfb6921)

**Comment by Jarred-Sumner** [comment]
```
❯ node a.mjs
file:///private/tmp/a.mjs:8
console.log(compressed.toString("hex"));
                       ^

TypeError: Cannot read properties of null (reading 'toString')
    at file:///private/tmp/a.mjs:8:24
    at ModuleJob.run (node:internal/modules/esm/module_job:271:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:547:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)

Node.js v23.2.0

/tmp via 🍞 v1.1.39
❯ bun a.mjs
3 | const compressor = createBrotliCompress();
4 | compressor.write("Hello, world!");
5 | compressor.end();
6 |
7 | const compressed = compressor.read();
8 | console.log(compressed.toString("hex"));
                ^
TypeError: null is not an object (evaluating 'compressed.toString')
      at /private/tmp/a.mjs:8:13

Bun v1.1.39-canary.12+da5d4d791 (macOS arm64)
```

Node behaves the same here
