### ISSUE TITLE
Failure when using `ora`: "undefined is not an object (evaluating 'readline.createInterface')"

### ISSUE THREAD

**Issue by EvHaus** [oven-sh/bun#1570]
### What version of Bun is running?

0.2.2

### What platform is your computer?

Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64 arm

### What steps can reproduce the bug?

Ensure you have the `ora` npm dependency installed, then create a simple TypeScript file:

```typescript
import ora from 'ora';
const spinner = ora('Loading unicorns').start();
spinner.succeed();
```

Then try to run this via bun:

```
bun test.ts
```

### How often does it reproduce? Is there a required condition?

Consistently reproducible.

### What is the expected behavior?

The expectation is that it works and prints a loading spinner in the terminal. Running the same code with `ts-node` works and returns the following:

```
% node --loader=ts-node/esm --experimental-specifier-resolution=node test.ts
(node:58584) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:58584) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
✔ Loading unicorns
```

### What do you see instead?

Bun fails to run the code and outputs the following:

```
[0.03ms] ".env"
2481 |     var { EventEmitter: EE } = __require("events");
2482 |     var { Stream, prependListener } = require_legacy();
2483 | 
2484 |     class Readable extends Stream {
2485 | 
2486 |       constructor(options) {
                                     ^
TypeError: Cannot call a class constructor without |new|
      at Readable (node:stream:2486:34)
      at Readable (/tmp/myproject/node_modules/readable-stream/lib/_stream_readable.js:184:2)
      at Duplex (/tmp/myproject/node_modules/readable-stream/lib/_stream_duplex.js:60:2)
      at new BufferListStream (/tmp/myproject/node_modules/bl/bl.js:33:2)
      at /tmp/myproject/node_modules/ora/utilities.js:9:16
      at new StdinDiscarder (/tmp/myproject/node_modules/ora/utilities.js:13:15)
      at new Ora (/tmp/myproject/node_modules/ora/index.js:34:20)
      at ora (/tmp/myproject/node_modules/ora/index.js:349:8)
      at /tmp/myproject/buntest.ts:3:16
```

**Comment by 0x4a61636f62** [comment]
Similar issue with npm package `@google-cloud/storage`:

```
[0.04ms] ".env"
5495 |     // var Readable = require_readable();
5496 |     var WritableReadable = require_writable_readable();
5497 | 
5498 |     var Duplex = class Duplex extends WritableReadable {
5499 | 
5500 |       constructor(options) {
                                     ^
TypeError: Cannot call a class constructor without |new|
      at Duplex (node:stream:5500:34)
      at new  (/home/myuser/myproject/node_modules/duplexify/index.js:42:2)
      at /home/myuser/myproject/node_modules/duplexify/index.js:41:43
      at createWriteStream (/home/myuser/myproject/node_modules/@google-cloud/storage/build/src/file.js:1448:32)
      at /home/myuser/myproject/node_modules/@google-cloud/storage/build/src/bucket.js:3272:37
      at /home/myuser/myproject/node_modules/@google-cloud/storage/build/src/bucket.js:3266:22
      at /home/myuser/myproject/node_modules/@google-cloud/storage/build/src/bucket.js:3265:45
      at runAttempt (/home/myuser/myproject/node_modules/async-retry/lib/index.js:42:14)
      at /home/myuser/myproject/node_modules/retry/lib/retry_operation.js:116:2
      at run (/home/myuser/myproject/node_modules/async-retry/lib/index.js:55:4)
      at retry (/home/myuser/myproject/node_modules/async-retry/lib/index.js:58:9)
      at /home/myuser/myproject/node_modules/@google-cloud/storage/build/src/bucket.js:3265:32
      at upload (/home/myuser/myproject/node_modules/@google-cloud/storage/build/src/bucket.js:3354:8)
      at /home/myuser/myproject/node_modules/@google-cloud/promisify/build/src/index.js:57:12
      at /home/myuser/myproject/node_modules/@google-cloud/promisify/build/src/index.js:42:15
      at /home/myuser/myproject/src/main.ts:56:8
      at uploadFile (/home/myuser/myproject/src/main.ts:43:26)
      at /home/myuser/myproject/src/main.ts:65:55
      ```

**Comment by Electroid** [comment]
We recently implemented support for `process.stdout` and related APIs, but `ora` also needs `node:readline` which we have not yet implemented, but will soon.

```js
62 | 		this.#rl = readline.createInterface({
                 ^
TypeError: undefined is not an object (evaluating 'readline.createInterface')
      at _realStart (/node_modules/ora/utilities.js:62:13)
      at start (/node_modules/ora/utilities.js:39:3)
      at start (/node_modules/ora/index.js:286:3)
```

**Comment by EvHaus** [comment]
Just tried again with bun 0.5.0 and got a different error now:

```
pipe count=1 opts=%j undefined
in flowing mode!
resume
read - n = 0
need readable false
length less than watermark true
do read
readableAddChunk null
n @ fromList 0
ret @ read null
state.length while ret = null 0
read - n = undefined
read: calling endReadable if length 0 -- length, state.ended 0 true
endEmitted @ endReadable false
read - n = 0
read: emitReadable or endReadable 0 true
endEmitted @ endReadable false
in flowing mode!
resume
read - n = 0
need readable false
length less than watermark true
do read
n @ fromList 0
ret @ read null
state.length while ret = null 0
read - n = undefined
need readable true
length less than watermark true
state.constructed? true
reading, ended or constructing false
n @ fromList 0
ret @ read null
state.length while ret = null 0
read - n = undefined
read: calling endReadable if length 0 -- length, state.ended 0 true
endEmitted @ endReadable false
endReadableNT -- endEmitted, state.length false 0

call pause flowing=%j true
pause
onunpipe
cleanup
end emitted @ endReadableNT
endReadableNT -- endEmitted, state.length true 0
222 | 	clear() {
223 | 		if (!this.#isEnabled || !this.#stream.isTTY) {
224 | 			return this;
225 | 		}
226 | 
227 | 		this.#stream.cursorTo(0);
     ^
TypeError: this.#stream.cursorTo is not a function. (In 'this.#stream.cursorTo(0)', 'this.#stream.cursorTo' is undefined)
      at clear (/node_modules/ora/index.js:227:2)
      at render (/node_modules/ora/index.js:252:2)
      at start (/node_modules/ora/index.js:289:2)

endReadableNT -- endEmitted, state.length true 0
```

**Comment by ThatOneBro** [comment]
I'll take a look at this. I think this has to do with the `tty.WriteStream` properties being `undefined` on `process.{stdout, stderr}` currently. This should be fixed soon
