### ISSUE TITLE
elkjs official example works with node but not with bun

### ISSUE THREAD

**Issue by tylerlong** [oven-sh/bun#15737]
### What version of Bun is running?

1.1.38

### What platform is your computer?

Darwin 23.6.0 x86_64 i386

### What steps can reproduce the bug?

```
bun add elkjs
```

Create `index.js` and copy the sample code from https://github.com/kieler/elkjs?tab=readme-ov-file#example:

```js
const ELK = require('elkjs')
const elk = new ELK()

const graph = {
  id: "root",
  layoutOptions: { 'elk.algorithm': 'layered' },
  children: [
    { id: "n1", width: 30, height: 30 },
    { id: "n2", width: 30, height: 30 },
    { id: "n3", width: 30, height: 30 }
  ],
  edges: [
    { id: "e1", sources: [ "n1" ], targets: [ "n2" ] },
    { id: "e2", sources: [ "n1" ], targets: [ "n3" ] }
  ]
}

elk.layout(graph)
   .then(console.log)
   .catch(console.error)
```

Run it:

```
bun src/index.js
```

### What is the expected behavior?

It should work without errors.

### What do you see instead?

```
48 |     if (!optionsClone.workerFactory) {
49 |       var _require = require('./elk-worker.min.js'),
50 |           _Worker = _require.Worker;
51 | 
52 |       optionsClone.workerFactory = function (url) {
53 |         return new _Worker(url);
                    ^
TypeError: undefined is not a constructor (evaluating 'new _Worker(url)')
      at /Users/tyler.liu/src/ts/bun-elkjs-demo/node_modules/elkjs/lib/main.js:53:16
      at ELK (/Users/tyler.liu/src/ts/bun-elkjs-demo/node_modules/elkjs/lib/elk-api.js:51:18)
      at new ELKNode (/Users/tyler.liu/src/ts/bun-elkjs-demo/node_modules/elkjs/lib/main.js:57:99)
      at /Users/tyler.liu/src/ts/bun-elkjs-demo/src/index.js:2:13
```

### Additional information

`node src/index.js` works

**Comment by Manuelbaun** [comment]
I had to use it like this:

```ts
import ELK from "elkjs";

const elk = new ELK({
    workerFactory: () => {
        // where ever your node modules folder is
        const worker = new Worker("../../../node_modules/elkjs/lib/elk-worker.js");
        return worker;
    },
});

```

Internally Elk is using require to get the worker file, my guess it does not resolve correctly when calling ` require('./elk-worker.min.js')`

```ts
var ELKNode = /*#__PURE__*/function (_ELK) {
  function ELKNode() {
    var options = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
    _classCallCheck(this, ELKNode);
    var optionsClone = Object.assign({}, options);
    var workerThreadsExist = false;
    try {
      require.resolve('web-worker');
      workerThreadsExist = true;
    } catch (e) {}

    // user requested a worker
    if (options.workerUrl) {
      if (workerThreadsExist) {
        var Worker = require('web-worker');
        optionsClone.workerFactory = function (url) {
          return new Worker(url);
        };
      } else {
        console.warn("Web worker requested but 'web-worker' package not installed. \nConsider installing the package or pass your own 'workerFactory' to ELK's constructor.\n... Falling back to non-web worker version.");
      }
    }

    // unless no other workerFactory is registered, use the fake worker
    if (!optionsClone.workerFactory) {
      var _require = require('./elk-worker.min.js'),
        _Worker = _require.Worker;
      optionsClone.workerFactory = function (url) {
        return new _Worker(url);
      };
    }
    return _callSuper(this, ELKNode, [optionsClone]);
  }
  _inherits(ELKNode, _ELK);
  return _createClass(ELKNode);
}(ELK);
```
