### ISSUE TITLE
Bun can't run the current build of rolldown. (Node and Deno are fine)

### ISSUE THREAD

**Issue by Malien** [oven-sh/bun#15732]
### What version of Bun is running?

1.1.38+bf2f153f5

### What platform is your computer?

Darwin 24.1.0 arm64 arm

### What steps can reproduce the bug?

This is probably not the priority of the team, but bun can't run the current build of rolldown. https://github.com/Malien/rolldown-is-broken-in-bun.

This is likely a bun bug ¯\\\_(ツ)_/¯ 

```js
import { rolldown } from "rolldown"

const build = await rolldown({ input: ["./sample.mjs"] });
try {
    await build.generate()
} finally {
    await build.close()
}
```

```sh
❯ bun build.mjs

```

### What is the expected behavior?

Welp. Not the crash.

### What do you see instead?

```
75 |                    summary += "\n...";
76 |                    break;
77 |            }
78 |            summary += getErrorMessage(errors[i]) + "\n";
79 |    }
80 |    const wrapper = new Error(summary);
                      ^
error: Build failed with 1 error:
Error: UNKNOWN_RETURN_VALUE. Cannot convert unknown to `Option<String>` in Arc<ThreadsafeFunction<RenderedChunk, Either<Either<Promise<Option<String>>, Option<Str
ing>>, UnknownReturnValue>, RenderedChunk, false, true>>.
    at get errors (native)
    at handleOutputErrors (<redacted>/rolldown-is-broken-in-bun/node_modules/rolldown/dist/shared/src-DEPa5yhI.mjs:215:20)
    at transformToRollupOutput (<redacted>/rolldown-is-broken-in-bun/node_modules/rolldown/dist/shared/src-DEPa5yhI.mjs:210:2)

 errors: [
  {
    "code": "InvalidArg",
    "originalLine": 207,
    "originalColumn": 27
  }
]

      at normalizeErrors (<redacted>/rolldown-is-broken-in-bun/node_modules/rolldown/dist/shared/src-DEPa5yhI.mjs:80:18)
      at handleOutputErrors (<redacted>/rolldown-is-broken-in-bun/node_modules/rolldown/dist/shared/src-DEPa5yhI.mjs:216:34)
      at transformToRollupOutput (<redacted>/rolldown-is-broken-in-bun/node_modules/rolldown/dist/shared/src-DEPa5yhI.mjs:210:2)

Bun v1.1.38 (macOS arm64)
```

### Additional information

Corresponding rolldown issue: https://github.com/rolldown/rolldown/issues/3139#issuecomment-2538922404

**Comment by HodgeWen** [comment]
I think this should be considered a top priority to address, as a significant portion of people use Bun to run build scripts
