### ISSUE TITLE
bunx --bun vite build  error during build: [vite:css] import.meta is only valid inside modules.

### ISSUE THREAD

**Issue by kunl** [oven-sh/bun#15738]
### What version of Bun is running?

1.1.39

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

1. bun create vite my-app
2. cd my-app
3. pnpm install && pnpm install less
4.  bunx --bun vite build  

package.json
```json
{
  "name": "my-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "bun:build": "bunx --bun vite build"
  },
  "devDependencies": {
    "vite": "^6.0.3"
  },
  "dependencies": {
    "less": "^4.2.1"
  }
}
```

 

app.less -> body { background-color: aliceblue;}
main.js ->   import './app.less'

### What is the expected behavior?

<img width="1635" alt="Image" src="https://github.com/user-attachments/assets/95d7241c-df81-4740-ab7f-cbff50df984f" />

### What do you see instead?

bun bun:build
$ bunx --bun vite build
vite v6.0.3 building for production...
✓ 6 modules transformed.
x Build failed in 49ms
error during build:
[vite:css] import.meta is only valid inside modules.
file: /Users/user/code/code/my-app/src/app.less
    at <parse> (:6)
    at Function (native)
    at new FakeWorker (/Users/user/code/code/my-app/node_modules/.pnpm/vite@6.0.3_less@4.2.1/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:12563:20)
    at new WorkerWithFallback (/Users/user/code/code/my-app/node_modules/.pnpm/vite@6.0.3_less@4.2.1/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:12602:28)
    at makeLessWorker (/Users/user/code/code/my-app/node_modules/.pnpm/vite@6.0.3_less@4.2.1/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:49164:22)
    at <anonymous> (/Users/user/code/code/my-app/node_modules/.pnpm/vite@6.0.3_less@4.2.1/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:49246:11)
    at process (/Users/user/code/code/my-app/node_modules/.pnpm/vite@6.0.3_less@4.2.1/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:49241:19)
    at <anonymous> (/Users/user/code/code/my-app/node_modules/.pnpm/vite@6.0.3_less@4.2.1/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:48168:34)
    at compileCSSPreprocessors (/Users/user/code/code/my-app/node_modules/.pnpm/vite@6.0.3_less@4.2.1/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:48154:40)
    at <anonymous> (/Users/user/code/code/my-app/node_modules/.pnpm/vite@6.0.3_less@4.2.1/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:48226:38)
    at processTicksAndRejections (native:7:39)
error: script "bun:build" exited with code 1

### Additional information

This problem does not exist in vite 5.x, it only appears after upgrading vite to 6.x

**Comment by PalmDevs** [comment]
I can also reproduce this issue. Running Vite with Node works fine.

**Comment by clare0987** [comment]
I can also reproduce this issue + 1

**Comment by kydemy-fran** [comment]
I can also reproduce this issue .
Running `vite` works fine but `bunx --bun vite` fails

**Comment by razor-1** [comment]
Reproduced on bun 1.1.42 and vite 6.0.5

**Comment by HodgeWen** [comment]
I think issues related to **Vite** need to be taken seriously, as many people use Bun to run their build scripts.

**Comment by kaij** [comment]
No known workaround other than downgrading vite to v5. So this also limits bun for nuxt users, as nuxt 3.15 is bundled with vite 6.

**Comment by Jarred-Sumner** [comment]
Repro:

[rep.zip](https://github.com/user-attachments/files/18278296/rep.zip)

**Comment by nick4814** [comment]
For me Vite 6 works on bun v1.1.37. I want to use the latest bun, but settled for no Bun upgrades till this is sorted out

**Comment by LeftGamer1** [comment]
+1 Vite v6.0.7 | bun v1.1.42
Any news?

P.S. for me it does not work on v1.1.37 as nick4814 mentioned

**Comment by paperclover** [comment]
it seems a new version of vite uses `Function.prototype.toString()`, then passing the result of this to `new Function()`. the input file gets run through the transpiler, converting `require` to `import.meta.require`, which is not valid code when run through `new Function`. this only happens when in an ES module.

this isnt exactly what vite is doing, but this example shows it reasonably:
```
function hello() {
    return typeof require('fs') === 'string' ? 'PASS' : "FAIL";
}
const newFunctionBody = `return ${hello.toString()}`;
const loadFakeModule = new Function('require', newFunctionBody)((id) => `fake require ${id}`);
console.log(loadFakeModule());

export {}; // force es module transpilation

```

a reasonable solution for this would be to hoist the require implementation instead of inlining it

```diff
 // @bun
 const { require } = import.meta;
 function hello() {
-  return typeof import.meta.require("fs") === "string" ? "PASS" : "FAIL";
+  return typeof require("fs") === "string" ? "PASS" : "FAIL";
 }
 const newFunctionBody = `return ${hello.toString()}`;
 const loadFakeModule = new Function("require", newFunctionBody)((id) => `fake require ${id}`);
 console.log(loadFakeModule());

 export {};
```

**Comment by nick4814** [comment]
> +1 Vite v6.0.7 | bun v1.1.42 Any news?
> 
> P.S. for me it does not work on v1.1.37 as nick4814 mentioned

Maybe it is due to your Vite version? I am on vite@6.0.6 with bun@1.1.37

Other than that, strange that it works for me on v1.1.37

I haven't tried with [https://bun.sh/blog/bun-v1.1.43](Bun v1.1.43), maybe this is now working? I will try it out tomorrow, it seems from (this comment)[https://github.com/oven-sh/bun/pull/16222#issuecomment-2578960174] that the issue might be fixed
