### ISSUE TITLE
napi_get_value_bigint_{int64,uint64} do not set `lossless`

### ISSUE THREAD

**Issue by 190n** [oven-sh/bun#15797]
### What version of Bun is running?

1.1.38+bf2f153f5

### What platform is your computer?

Darwin 24.1.0 arm64 arm

### What steps can reproduce the bug?

Reproduction from duckdb/duckdb-node-neo#69:

```js
import { DuckDBInstance, DuckDBTimestampValue } from '@duckdb/node-api';

const db = await DuckDBInstance.create(':memory:');
const connection = await db.connect();

await connection.run(`
  CREATE TABLE IF NOT EXISTS test (
    id BIGINT PRIMARY KEY,
    value INTEGER NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL
  );
`);


const query = await connection.prepare(
  'INSERT INTO test (id, value, timestamp) VALUES ($1, $2, $3);',
);
// throws "bigint out of int64 range"
query.bindBigInt(1, BigInt(1));
// Works as expected
query.bindInteger(2, 100);
// throws "micros out of int64 range"
query.bindTimestamp(3, new DuckDBTimestampValue(BigInt(Date.now()) * 1000n));

await query.run();


const appender = await connection.createAppender('main', 'test');

// throws "bigint out of int64 range"
appender.appendBigInt(BigInt(1));
// Works as expected
appender.appendInteger(100);
// throws "Unimplemented type for cast (INT64 -> INT32)""
appender.appendTimestamp(new DuckDBTimestampValue(BigInt(Date.now()) * 1000n));
appender.endRow();

appender.close();
```

### What is the expected behavior?

Code runs with no errors

### What do you see instead?

```
error: bigint out of int64 range
      at appendBigInt (/Users/ben/code/duckdb-demo/node_modules/@duckdb/node-api/lib/DuckDBAppender.js:45:33)
      at /Users/ben/code/duckdb-demo/index.js:31:10
```

### Additional information

This happens because we don't set the `lossless` out-parameter in `napi_get_value_bigint_int64` and `napi_get_value_bigint_uint64`. Solution is to cherry-pick the fixed versions of these functions from #14501.

**Comment by Zambito1** [comment]
Just ran into this issue myself, also using duckdb-node-neo with the appender API.
