### ISSUE TITLE
Types for the `WebSocket` global include methods that don't exist at runtime

### ISSUE THREAD

**Issue by lilnasy** [oven-sh/bun#15883]
### What version of Bun is running?

1.1.40+b5b51004e

### What platform is your computer?

Linux 6.1.91-060191-generic x86_64 unknown

### What steps can reproduce the bug?

The following code type checks okay and has hover descriptions for methods, except they don't match the runtime behavior.
```ts
const x = new WebSocket("https://github.com")

try {
    x.setMaxListeners(1)
} catch (e) {
    console.error(e)
}
try {
    x.resume()
} catch (e) {
    console.error(e)
}
```
![Image](https://github.com/user-attachments/assets/6b699640-0618-43d9-bb29-658fa7060eeb)

### What is the expected behavior?

The types correspond to the actual shape of the object.

```
> xy
WebSocket {}
> xy.__proto__
EventTarget [WebSocket] {
  url: [Getter],
  readyState: [Getter],
  bufferedAmount: [Getter],
  onopen: [Getter/Setter],
  onmessage: [Getter/Setter],
  onerror: [Getter/Setter],
  onclose: [Getter/Setter],
  protocol: [Getter],
  extensions: [Getter],
  binaryType: [Getter/Setter],
  send: [Function: send],
  close: [Function: close],
  ping: [Function: ping],
  pong: [Function: pong],
  terminate: [Function: terminate],
  CONNECTING: 0,
  OPEN: 1,
  CLOSING: 2,
  CLOSED: 3
}
```

### What do you see instead?

```
1 | const x = new WebSocket("https://github.com")
2 | 
3 | try {
4 |     x.setMaxListeners(1)
          ^
TypeError: x.setMaxListeners is not a function. (In 'x.setMaxListeners(1)', 'x.setMaxListeners' is undefined)
      at /workspace/empty/index.ts:4:7

4 |     x.setMaxListeners(1)
5 | } catch (e) {
6 |     console.error(e)
7 | }
8 | try {
9 |     x.resume()
          ^
TypeError: x.resume is not a function. (In 'x.resume()', 'x.resume' is undefined)
      at /workspace/empty/index.ts:9:7
```

**Comment by touhidurrr** [comment]
![Image](https://github.com/user-attachments/assets/eb400cf2-2735-4c9d-a13a-8f406f9b14d9)

i dont know how do they break working types again and again.

**Comment by alii** [comment]
This was fixed in #19017 and was released in the latest version (1.2.10).

Please try updating your @types/bun version
