### ISSUE TITLE
[Bun Shell]: ShellError with path string with NON-ASCII string in Bun shell

### ISSUE THREAD

**Issue by EaGitro** [oven-sh/bun#15929]
### What version of Bun is running?

1.1.42+50eec0025

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Hello! First of all thank you a lot for the great OSS. Bun has changed my coding experience in a big way!

In Bun Shell, Sometimes I get ShellError with path string with non-ascii. I am Japanese, so I am very confused by this error.

Below is examples with Japanese and Spanish.

# Example code 1. (Japanese)

directories: 
```
./
├── jp.ts
└── 日本語
    ├── a.txt
    └── b.txt
```

`jp.ts`:

```typescript
/**
 * jp.ts
 */
// UTF-8, CRLF

import { $ } from "bun";
const dir = import.meta.dir
const jp = "日本語"
const pathstr = `${dir}/${jp}`

console.log({ dir, jp, str: pathstr })
/*
{
  dir: "D:\\tmp\\bun-err",
  jp: "日本語",
  str: "D:\\tmp\\bun-err/日本語",
}
*/

// Below is the instant solution for now. But it may be inconvenient.
console.log(await $`ls ${pathstr}`.text()) // OK


console.log(await $`ls ${dir}/日本語`.text()) // shellError
/*
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "ls: D:\\tmp\\bun-err/u65E5u672Cu8A9E: No such file or directory\n",
  "stdout": ""
}

      at new ShellError (12:16)
      at new ShellPromise (72:16)
      at BunShell (187:35)
      at D:\tmp\bun-err\jp.ts:17:19
*/

// I can't get why this gets an error. 
console.log(await $`ls ${dir}/${jp}`.text()) // ShellError
/*
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "ls: \b__bunstr_0/日本語: No such file or directory\n",
  "stdout": ""
}

      at new ShellError (12:16)
      at new ShellPromise (72:16)
      at BunShell (187:35)
      at D:\tmp\bun-err\jp.ts:8:19
*/


console.log(await $`ls D:\\tmp\\bun-err/${jp}`.text()) // OK

/**
 * wildcards
 */
console.log(await $`cat ${pathstr}/*.txt`.text()) //OK

// With wildcards, Bun does not return any information
console.log(await $`cat ${dir}/${jp}/*.txt`.text()) // ShellError
/*
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "",
  "stdout": ""
}

      at new ShellError (12:16)
      at new ShellPromise (72:16)
      at BunShell (187:35)
      at D:\tmp\bun-err\jp.ts:56:19
*/


// But wildcards in a variable, an error occurs. (also in ascii)
const wildcard = `${pathstr}/*.txt`
console.log(await $`cat ${wildcard}`.text()) // ShellError
/*
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "cat: D:\\tmp\\bun-err/日本語/*.txt: No such file or directory\n",
  "stdout": ""
}

      at new ShellError (12:16)
      at new ShellPromise (72:16)
      at BunShell (187:35)
      at D:\tmp\bun-err\jp.ts:94:19
*/
```

# Example code 2. (Spanish)

directories:
```
├── es.ts
└── español
    ├── a.txt
    └── b.txt
```

`es.ts` :
```typescript
/**
 * es.ts
 */
// UTF-8, CRLF

import { $ } from "bun";
const dir = import.meta.dir
const es = "español"
const pathstr = `${dir}/${es}`

console.log({ dir, jp: es, str: pathstr })
/*
{
  dir: "D:\\tmp\\bun-err",
  jp: "español",
  str: "D:\\tmp\\bun-err/español",
}
*/

// Below is the instant solution for now. But it may be inconvenient.
console.log(await $`ls ${pathstr}`.text()) // OK


console.log(await $`ls ${dir}/español`.text()) // shellError
/*
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "ls: D:\\tmp\\bun-err/espau00F1ol: No such file or directory\n",
  "stdout": ""
}

      at new ShellError (12:16)
      at new ShellPromise (72:16)
      at BunShell (187:35)
      at D:\tmp\bun-err\es.ts:21:19
*/

// I can't get why this gets error. 
console.log(await $`ls ${dir}/${es}`.text()) // ShellError
/*
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "ls: \b__bunstr_0/espaespañol: No such file or directory\n",
  "stdout": ""
}

      at new ShellError (12:16)
      at new ShellPromise (72:16)
      at BunShell (187:35)
      at D:\tmp\bun-err\es.ts:37:19
*/


// This does not occur in Japanese.
console.log(await $`ls D:\\tmp\\bun-err/${es}`.text()) // ShellError
/*
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "ls: D:\\tmp\\bun-err/espaespañol: No such file or directory\n",
  "stdout": ""
}

      at new ShellError (12:16)
      at new ShellPromise (72:16)
      at BunShell (187:35)
      at D:\tmp\bun-err\es.ts:56:19
*/

/**
 * Wildcard
 */
// With wildcards, Bun does not return any info  
console.log(await $`cat ${dir}/${es}/*.txt`.text()) // ShellError
/*
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "",
  "stdout": ""
}

      at new ShellError (12:16)
      at new ShellPromise (72:16)
      at BunShell (187:35)
      at D:\tmp\bun-err\es.ts:73:19
*/


// But wildcards in a variable, an error occurs. (also in ascii)
const wildcard = `${pathstr}/*.txt`
console.log(await $`cat ${wildcard}`.text()) // ShellError
/*
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "cat: D:\\tmp\\bun-err/español/*.txt: No such file or directory\n",
  "stdout": ""
}

      at new ShellError (12:16)
      at new ShellPromise (72:16)
      at BunShell (187:35)
      at D:\tmp\bun-err\es.ts:90:19
*/
```

# Example code 3. (ascii: No Error without wildcard)
```typescript
/**
 * en.ts
 */
// UTF-8, CRLF

import { $ } from "bun";
const dir = import.meta.dir
const en = "english"
const pathstr = `${dir}/${en}`

console.log({ dir, jp: en, str: pathstr })
console.log(await $`ls ${pathstr}`.text()) // OK


console.log(await $`ls ${dir}/english`.text()) // OK 
console.log(await $`ls ${dir}/${en}`.text()) // OK
console.log(await $`ls D:\\tmp\\bun-err/${en}`.text()) // OK

/**
 * wildcards
 */
console.log(await $`cat ${pathstr}/*.txt`.text()) //OK
console.log(await $`cat ${dir}/${en}/*.txt`.text()) // OK


// But wildcards in a variable, an error occurs.
const wildcard = `${pathstr}/*.txt`
console.log(await $`cat ${wildcard}`.text()) // ShellError
/*
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "cat: D:\\tmp\\bun-err/english/*.txt: No such file or directory\n",
  "stdout": ""
}

      at new ShellError (12:16)
      at new ShellPromise (72:16)
      at BunShell (187:35)
      at D:\tmp\bun-err\en.ts:28:19
*/
```

### What is the expected behavior?

The expected behavior is to be able to execute without error.

### What do you see instead?

# When the error occurs

If path string contains a non-ascii string and it is not assigned to a variable. However, even if it is assigned to a variable, an error may still occur.

eg:
- `ls ${pathStringWithNonAscii}` : OK
- `ls ${asciiString}/${nonAscii}`: Error
- `ls D:/${nonAscii}`: maybe Error

When using wildcards, putting wildcards in a variable will cause an error.

eg: 
- `ls ${pathString}/*.txt`: OK
- `ls ${pathStringWithWildcard}` : Error

# Instant solution

You can avoid the error by assigning all path-strings excepting wildcards to variables. However, it may be inconvenient.

### Additional information

Thank you for great OSS!!

**Comment by robobun** [comment]
The failure still present here (`$\`ls ${dir}/日本語\`` running `ls .../u65E5u672Cu8A9E`, `ls ${dir}/español` -> `espau00F1ol`, `echo "rêver"` printing `r\u00EAver`) is the bug tracked in #8745: Bun's transpiler rewrites non-ASCII characters in a tagged template's `.raw` strings to `\uXXXX` escapes, and Bun Shell builds its command from those raw strings, so the shell lexer receives the escapes instead of the characters. The interpolation-only cases in this report (`\b__bunstr_0/...`, `espaespañol`, the `${dir}/${jp}/*.txt` glob) no longer reproduce on current Bun, and the fix for #8745 (#33866) also carries this report's shell repro, so this will be tracked in #8745.

Duplicate of #8745

Please add a 👍 or any extra details over there so it all stays in one place. If this is actually a different problem, say so here and we'll reopen.
