### ISSUE TITLE
Firebase Appcheck "The JWKS endpoint did not contain any signing keys"

### ISSUE THREAD

**Issue by WheelerCC** [oven-sh/bun#15932]
### What version of Bun is running?

1.1.38+bf2f153f5

### What platform is your computer?

Darwin 24.0.0 arm64 arm

### What steps can reproduce the bug?

I'm not pushing for a fix, I'm primarily posting this to assist anyone else that hits this when using appcheck with bun. I don't think firebase officially supports anything other than npm, but this is the only problem that arose when using bun. Otherwise everything _just worked_.

Techstack: Sveltekit app normally hosted using vercel, but occurs in local dev. Browser provides appcheck token to the +server.ts endpoint, where it is verified using the .verifyToken() method.

```typescript
// Normally from the 'X-Firebase-AppCheck' header
const appCheckToken = "..."   
await getAppCheck().verifyToken(appCheckToken);
```

### What is the expected behavior?

When providing a valid appCheckToken, the expected behaviour is for it to return a set of appCheckClaims. Using the same appcheck token with both node and bun yields different results, with node behaving "as expected"

### What do you see instead?

This seems to fail with the following error message/stacktrace when using bun:
```
27 |      * @param errorInfo - The error information (code and message).
28 |      * @constructor
29 |      * @internal
30 |      */
31 |     constructor(errorInfo) {
32 |         super(errorInfo.message);
             ^
error: Error fetching Json Web Keys: The JWKS endpoint did not contain any signing keys
 code: "app-check/invalid-argument"

      at new FirebaseError (/Users/<redacted>/node_modules/firebase-admin/lib/utils/error.js:32:9)
      at new PrefixedFirebaseError (/Users/<redacted>/node_modules/firebase-admin/lib/utils/error.js:69:9)
      at new FirebaseAppCheckError (/Users/<redacted>/node_modules/firebase-admin/lib/app-check/app-check-api-client-internal.js:206:9)
      at mapJwtErrorToAppCheckError (/Users/<redacted>/node_modules/firebase-admin/lib/app-check/token-verifier.js:144:16)
      at /Users/<redacted>/node_modules/firebase-admin/lib/app-check/token-verifier.js:119:24
```

### Additional information

The closest error previously reported to this was https://github.com/firebase/firebase-admin-node/issues/2312, but I believe it's unrelated. This could likely be better reported in the appcheck repo, but given their lack of advertised bun support, I suspect it wouldn't be fixed.

**Comment by fjdvchain** [comment]
@technoplato this might be fixed for you after upgrading your packages to the latest version

https://github.com/oven-sh/bun/issues/10511#issuecomment-2753325083
