### ISSUE TITLE
Strange formatting of additional to extended from Error class on canary build

### ISSUE THREAD

**Issue by kravetsone** [oven-sh/bun#15999]
### What version of Bun is running?

1.1.42-canary.19+145a7fd92

### What platform is your computer?

Microsoft Windows NT 10.0.26100.0 x64

### What steps can reproduce the bug?

```js
export class TelegramError extends Error {
	constructor(error, method, params) {
		super(error.description);

		this.name = method;
		this.method = method;
		this.params = params;
		this.code = error.error_code;

		if (error.parameters) this.payload = error.parameters;
	}
}

throw new TelegramError({ description: "test", error_code: 1 }, "test", {});

```

Bun:

```sh
PS Z:\PROJECTS\GRAMIO\core> bun .\repr.mjs
1 | export class TelegramError extends Error {
2 |     constructor(error, method, params) {
3 |             super(error.description);
      ^
test: test
 method: "test",
 params: {},
   code: 1,

      at new TelegramError (Z:\PROJECTS\GRAMIO\core\repr.mjs:3:3)
      at Z:\PROJECTS\GRAMIO\core\repr.mjs:14:7

Bun v1.1.42-canary.19+145a7fd92 (Windows x64)
```

Node:

```sh
PS Z:\PROJECTS\GRAMIO\core> node .\repr.mjs 
file:///Z:/PROJECTS/GRAMIO/core/repr.mjs:14
throw new TelegramError({ description: "test", error_code: 1 }, "test", {});
      ^

test: test
    at file:///Z:/PROJECTS/GRAMIO/core/repr.mjs:14:7
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5) {
  method: 'test',
  params: {},
  code: 1
}

Node.js v22.10.0
```

https://github.com/oven-sh/bun/pull/15985

### Additional information

The same result on WSL

**Comment by nektro** [comment]
> **What is the expected behavior?**
> No response

almost closed but noticed the source snippet is what's different

```
1 | export class TelegramError extends Error {
2 |     constructor(error, method, params) {
3 |             super(error.description);
      ^
```

vs

```
throw new TelegramError({ description: "test", error_code: 1 }, "test", {});
      ^
```
