### ISSUE TITLE
Forcing Bun execution (`--bun`) of Vite 6 dev with Sass plugin crashes with `import.meta is only valid inside modules`

### ISSUE THREAD

**Issue by jakeboone02** [oven-sh/bun#16008]
### What version of Bun is running?

1.1.42+50eec0025

### What platform is your computer?

Linux 5.15.167.4-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Create a new vanilla JS Vite project, install dependencies, then install `sass`:

```bash
bun create vite bunx-bun-vite-scss-test
# ✔ Select a framework: › Vanilla
# ✔ Select a variant: › JavaScript
cd bunx-bun-vite-scss-test
bun install
bun add -d sass
```

Create a `src/styles.scss` file with any valid contents (I used `h1 { color: rebeccapurple; }`).

Add the following line inside the `<head>` tag in `index.html`:

```html
<link rel="stylesheet" href="./src/styles.scss">
```

Force Bun to run Vite's dev server:

```bash
bun --bun vite
```

### What is the expected behavior?

No error.

### What do you see instead?

```text
$ bunx --bun vite

  VITE v6.0.6  ready in 163 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
5:08:26 PM [vite] Internal server error: import.meta is only valid inside modules.
  Plugin: vite:css
  File: ~/git/bunx-bun-vite-scss-test/styles.scss?direct:12732:20
      at <parse> (:7)
      at AsyncFunction (native)
      at new FakeWorker (~/git/bunx-bun-vite-scss-test/node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:12732:20)
      at new WorkerWithFallback (~/git/bunx-bun-vite-scss-test/node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:12773:28)
      at makeModernScssWorker (~/git/bunx-bun-vite-scss-test/node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:49156:22)
      at <anonymous> (~/git/bunx-bun-vite-scss-test/node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:49302:49)
      at process (~/git/bunx-bun-vite-scss-test/node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:49293:19)
      at <anonymous> (~/git/bunx-bun-vite-scss-test/node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:48417:34)
      at compileCSSPreprocessors (~/git/bunx-bun-vite-scss-test/node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:48403:40)
      at <anonymous> (~/git/bunx-bun-vite-scss-test/node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:48475:38)
      at processTicksAndRejections (native:7:39)
```

### Additional information

Vite 5 does not exhibit this problem, and running `bun vite` doesn't either, so I'm pretty sure it's not a Vite or Sass bug but a Node compatibility issue with Bun.

**Comment by kaij** [comment]
Same as #15738

**Comment by jakeboone02** [comment]
You're right, definitely a dupe. Sorry about that!
