### ISSUE TITLE
Npm installs properly, Bun is not

### ISSUE THREAD

**Issue by Nikita0x** [oven-sh/bun#16015]
### `package.json` file

```json
{
  "name": "unknown",
  "private": true,
  "version": "0.0.1",
  "type": "module",
  "scripts": {
    "dev": "vite --mode dev",
    "prod": "vite --mode prod",
    "build:dev": "ionic build -- --mode dev && npx cap sync",
    "build": "ionic build --prod -- --mode prod && npx cap sync",
    "android": "ionic cap open android"
  },
  "dependencies": {
    "@awesome-cordova-plugins/app-version": "^6.13.0",
    "@capacitor-community/facebook-login": "^6.1.0",
    "@capacitor/android": "6.2.0",
    "@capacitor/app": "6.0.2",
    "@capacitor/core": "6.2.0",
    "@capacitor/device": "^6.0.2",
    "@capacitor/haptics": "6.0.2",
    "@capacitor/keyboard": "6.0.3",
    "@capacitor/status-bar": "6.0.2",
    "@capawesome/capacitor-app-update": "^6.1.0",
    "@ionic/vue": "^8.0.0",
    "@ionic/vue-router": "^8.0.0",
    "@revenuecat/purchases-capacitor": "^9.0.9",
    "axios": "^1.7.9",
    "capacitor-plugin-app-tracking-transparency": "^2.0.5",
    "ionicons": "^7.0.0",
    "onesignal-cordova-plugin": "^5.2.9",
    "pinia": "^2.3.0",
    "pinia-plugin-capacitor-persist": "^1.4.0",
    "posthog-js": "^1.203.1",
    "swiper": "^11.1.15",
    "tailgrids": "^2.2.7",
    "vue": "^3.3.0",
    "vue-i18n": "^10.0.5",
    "vue-router": "^4.2.0"
  },
  "devDependencies": {
    "@capacitor/cli": "6.2.0",
    "@vitejs/plugin-legacy": "^5.0.0",
    "@vitejs/plugin-vue": "^4.0.0",
    "@vue/eslint-config-typescript": "^12.0.0",
    "@vue/test-utils": "^2.3.0",
    "autoprefixer": "^10.4.20",
    "cypress": "^13.5.0",
    "eslint": "^8.35.0",
    "eslint-plugin-vue": "^9.9.0",
    "jsdom": "^22.1.0",
    "postcss": "^8.4.49",
    "prettier": "^3.4.2",
    "prettier-plugin-tailwindcss": "^0.6.9",
    "tailwindcss": "^3.4.17",
    "terser": "^5.4.0",
    "typescript": "~5.6.2",
    "vite": "~5.2.0",
    "vitest": "^0.34.6",
    "vue-tsc": "^2.1.10"
  },
  "description": "no description"
}
```

### How can we reproduce the crash?

Create an Ionic + Vue - project, add package json and try to install. Apparently cypress fails it 

### Relevant log output

```shell

```

### Stack Trace (bun.report)

bun install v1.1.42 (50eec002)
  ⚙️  cypress [1/3] Installing Cypress (version: 13.17.0)

[STARTED] Task without title.
[TITLE]  Downloading Cypress      0% 0s
[TITLE]  Downloading Cypress      1% 20s
[TITLE]  Downloading Cypress      1% 30s
[TITLE]  Downloading Cypress      2% 20s
[TITLE]  Downloading Cypress      2% 25s
[TITLE]  Downloading Cypress      2% 30s
[TITLE]  Downloading Cypress      3% 23s
[TITLE]  Downloading Cypress      3% 26s
[TITLE]  Downloading Cypress      4% 22s
[TITLE]  Downloading Cypress      4% 24s
[TITLE]  Downloading Cypress      5% 21s
[TITLE]  Downloading Cypress      5% 23s
[TITLE]  Downloading Cypress      5% 25s
[TITLE]  Downloading Cypress      6% 22s
[TITLE]  Downloading Cypress      6% 24s
[TITLE]  Downloading Cypress      7% 21s
[TITLE]  Downloading Cypress      7% 23s
[TITLE]  Downloading Cypress      8% 21s
[TITLE]  Downloading Cypress      8% 22s
[TITLE]  Downloading Cypress      9% 20s
[TITLE]  Downloading Cypress      9% 21s
[TITLE]  Downloading Cypress      10% 20s
[TITLE]  Downloading Cypress      10% 21s
[TITLE]  Downloading Cypress      11% 20s
[TITLE]  Downloading Cypress      12% 19s
[TITLE]  Downloading Cypress      12% 20s
[TITLE]  Downloading Cypress      13% 19s
[TITLE]  Downloading Cypress      13% 20s
[TITLE]  Downloading Cypress      14% 19s
[TITLE]  Downloading Cypress      14% 20s
[TITLE]  Downloading Cypress      15% 19s
[TITLE]  Downloading Cypress      16% 18s
[TITLE]  Downloading Cypress      16% 19s
[TITLE]  Downloading Cypress      17% 18s
[TITLE]  Downloading Cypress      17% 19s
[TITLE]  Downloading Cypress      18% 18s
[TITLE]  Downloading Cypress      19% 18s
[TITLE]  Downloading Cypress      20% 17s
[TITLE]  Downloading Cypress      20% 18s
[TITLE]  Downloading Cypress      21% 17s
[TITLE]  Downloading Cypress      22% 17s
[TITLE]  Downloading Cypress      23% 16s
[TITLE]  Downloading Cypress      23% 17s
[TITLE]  Downloading Cypress      24% 16s
[TITLE]  Downloading Cypress      24% 17s
[TITLE]  Downloading Cypress      25% 16s
[TITLE]  Downloading Cypress      26% 16s
[TITLE]  Downloading Cypress      27% 15s
[TITLE]  Downloading Cypress      27% 16s
[TITLE]  Downloading Cypress      28% 15s
[TITLE]  Downloading Cypress      29% 15s
[TITLE]  Downloading Cypress      30% 15s
[TITLE]  Downloading Cypress      31% 15s
[TITLE]  Downloading Cypress      32% 14s
[TITLE]  Downloading Cypress      33% 14s
[TITLE]  Downloading Cypress      34% 14s
[TITLE]  Downloading Cypress      35% 14s
[TITLE]  Downloading Cypress      36% 13s
[TITLE]  Downloading Cypress      36% 14s
[TITLE]  Downloading Cypress      37% 13s
[TITLE]  Downloading Cypress      38% 13s
[TITLE]  Downloading Cypress      39% 13s
[TITLE]  Downloading Cypress      40% 12s
[TITLE]  Downloading Cypress      41% 12s
[TITLE]  Downloading Cypress      42% 12s
[TITLE]  Downloading Cypress      43% 12s
[TITLE]  Downloading Cypress      44% 11s
[TITLE]  Downloading Cypress      45% 11s
[TITLE]  Downloading Cypress      46% 11s
[TITLE]  Downloading Cypress      47% 11s
[TITLE]  Downloading Cypress      48% 11s
[TITLE]  Downloading Cypress      49% 10s
[TITLE]  Downloading Cypress      49% 11s
[TITLE]  Downloading Cypress      50% 10s
[TITLE]  Downloading Cypress      51% 10s
[TITLE]  Downloading Cypress      52% 10s
[TITLE]  Downloading Cypress      53% 10s
[TITLE]  Downloading Cypress      54% 9s
[TITLE]  Downloading Cypress      55% 9s
[TITLE]  Downloading Cypress      56% 9s
[TITLE]  Downloading Cypress      57% 9s
[TITLE]  Downloading Cypress      58% 8s
[TITLE]  Downloading Cypress      58% 9s
[TITLE]  Downloading Cypress      59% 8s
[TITLE]  Downloading Cypress      60% 8s
[TITLE]  Downloading Cypress      61% 8s
[TITLE]  Downloading Cypress      62% 8s
[TITLE]  Downloading Cypress      63% 7s
[TITLE]  Downloading Cypress      64% 7s
[TITLE]  Downloading Cypress      65% 7s
[TITLE]  Downloading Cypress      66% 7s
[TITLE]  Downloading Cypress      67% 7s
[TITLE]  Downloading Cypress      68% 6s
[TITLE]  Downloading Cypress      69% 6s
[TITLE]  Downloading Cypress      70% 6s
[TITLE]  Downloading Cypress      71% 6s
[TITLE]  Downloading Cypress      72% 6s
[TITLE]  Downloading Cypress      73% 5s
[TITLE]  Downloading Cypress      74% 5s
[TITLE]  Downloading Cypress      75% 5s
[TITLE]  Downloading Cypress      76% 5s
[TITLE]  Downloading Cypress      77% 5s
[TITLE]  Downloading Cypress      78% 4s
[TITLE]  Downloading Cypress      79% 4s
[TITLE]  Downloading Cypress      80% 4s
[TITLE]  Downloading Cypress      81% 4s
[TITLE]  Downloading Cypress      82% 4s
[TITLE]  Downloading Cypress      83% 3s
[TITLE]  Downloading Cypress      84% 3s
[TITLE]  Downloading Cypress      85% 3s
[TITLE]  Downloading Cypress      86% 3s
[TITLE]  Downloading Cypress      87% 3s
[TITLE]  Downloading Cypress      88% 2s
[TITLE]  Downloading Cypress      89% 2s
[TITLE]  Downloading Cypress      90% 2s
[TITLE]  Downloading Cypress      91% 2s
[TITLE]  Downloading Cypress      92% 2s
[TITLE]  Downloading Cypress      93% 1s
[TITLE]  Downloading Cypress      94% 1s
[TITLE]  Downloading Cypress      95% 1s
[TITLE]  Downloading Cypress      96% 1s
[TITLE]  Downloading Cypress      97% 1s
[TITLE]  Downloading Cypress      98% 0s
[TITLE]  Downloading Cypress      99% 0s
[TITLE]  Downloading Cypress      100% 0s
[TITLE]  Downloaded Cypress     
[SUCCESS]  Downloaded Cypress     
[STARTED] Task without title.

75 |         };
76 |         const unzipFallback = _.once(unzipWithNode);
77 |         const unzipWithUnzipTool = () => {
78 |           debug('unzipping via `unzip`');
79 |           const inflatingRe = /inflating:/;
80 |           const sp = cp.spawn('unzip', ['-o', zipFilePath, '-d', installDir]);
                             ^
error: Executable not found in $PATH: "unzip"
 code: "ENOENT"
 path: "unzip"

      at spawn (node:child_process:614:33)
      at spawn (node:child_process:12:39)
      at unzipWithUnzipTool (/home/mykyta/work/chat_app/node_modules/cypress/lib/tasks/unzip.js:80:25)
      at /home/mykyta/work/chat_app/node_modules/yauzl/index.js:37:7
      at /home/mykyta/work/chat_app/node_modules/yauzl/index.js:141:16
      at /home/mykyta/work/chat_app/node_modules/yauzl/index.js:631:5
      at /home/mykyta/work/chat_app/node_modules/fd-slicer/index.js:32:7
      at node:fs:182:13

Bun v1.1.42 (Linux x64)

error: postinstall script from "cypress" exited with 1

**Comment by DonIsaac** [comment]
Can you try upgrading to cypress v13.17.0? In that version, [they only use `unzip` on linux machines](https://github.com/cypress-io/cypress/blob/0ddb1197a0d81afafa5758820205bc8b37152c33/cli/lib/tasks/unzip.js#L181).

Otherwise you can try installing `unzip`.

```sh
sudo apt-get install unzip
```

**Comment by Nikita0x** [comment]
Fails on `cypress`. Installing 13.17.0 - did not help.
Installing `unzip` and setting it to $PATH - did not help either. The issue still persists.
