### ISSUE TITLE
Make better-sqlite3 work in bun without needing recompilation

### ISSUE THREAD

**Issue by vedantroy** [oven-sh/bun#16050]
### What version of Bun is running?

1.1.33+247456b67

### What platform is your computer?

Darwin 24.2.0 arm64 arm

### What steps can reproduce the bug?

Do `bun add better-sqlite3`, then try to import and use it.

### What is the expected behavior?

It works.

### What do you see instead?

```
                                                     ^
error: The module 'better_sqlite3' was compiled against a different Node.js ABI version using NODE_MODULE_VERSION 131. This version of Bun requires NODE_MODULE_VERSION 127. Please try re-compiling or re-installing the module.
      at bindings (/Users/.../v1/api/node_modules/bindings/bindings.js:112:48)
      at new Database (/Users/...v1/api/node_modules/better-sqlite3/lib/database.js:48:29)
      at /Users/.../v1/api/src/auth.ts:19:12
```

### Additional information

While the error message is clear, it would be nice if bun just supported `better-sqlite3` out of the box. The reason is, I don't see a claim that `bun:sqlite` is 1:1 compatible with `better-sqlite3`, and libraries like https://www.better-auth.com/, expect a `better-sqlite3` adapter, not a `bun:sqlite` adapter.

**Comment by vedantroy** [comment]
As a concrete example of the issue. I get the error:
```
1 | import{APIError as K,createRouter as yn,getCookie as wn,getSignedCookie as An,setCookie as bn,setSignedCookie as Rn}from"better-call";import{APIError as gr}from"better-call";import{createEndpointCreator as cr,createMiddleware as Be,createMiddlewareCreator as ur}from"better-call";var Ve=Be(async()=>({})),X=ur({use:[Ve,Be(async()=>({}))]}),T=cr({use:[Ve]});function ke(e){return e==="-"||e==="^"||e==="$"||e==="+"||e==="."||e==="("||e===")"||e==="|"||e==="["||e==="]"||e==="{"||e==="}"||e==="*"||e==="?"||e==="\\"?`\\${e}`:e}function lr(e){let t="";for(let r=0;r<e.length;r++)t+=ke(e[r]);return t}function Fe(e,t=!0){if(Array.isArray(e))return`(?:${e.map(d=>`^${Fe(d,t)}}$`).join("|")})`;let r="",n="",i=".";t===!0?(r="/",n="[/\\\\]",i="[^/\\\\]"):t&&(r=t,n=lr(r),n.length>1?(n=`(?:${n})`,i=`((?!${n}).)`):i=`[^${n}]`);let o=t?`${n}+?`:"",a=t?`${n}*?`:"",l=t?e.split(r):[e],c="";for(let s=0;s<l.length;s++){let d=l[s],p=l[s+1],m="";if(!(!d&&s>0)){if(t&&(s===l.length-1?m=a:p!=="**"?m=o:m=""),t&&d==="**"){m&&(c+=s===0?"":m,c+ | ... truncated 
```

When using `bun:sqlite` with better-auth instead of better-sqlite3.

**Comment by vedantroy** [comment]
Issue on better-auth side: https://github.com/better-auth/better-auth/issues/1062

**Comment by felixrydberg** [comment]
Im running into the same issue when using docker and when running ubuntu server on my other machine.
Bun: 1.1.42
Ubuntu: 24.04 LTS

When having better-sqlite3 as a dependency and running bun install it will fail, but if you have node installed it will go through but crash during startup with this error:

Could not locate the bindings file. Tried:                                                                                                                                                                                   nuxi 10:53:24 PM
 → node_modules/better-sqlite3/build/better_sqlite3.node
 → node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → node_modules/better-sqlite3/Debug/better_sqlite3.node
 → node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → node_modules/better-sqlite3/Release/better_sqlite3.node
 → node_modules/better-sqlite3/build/default/better_sqlite3.node
 → node_modules/better-sqlite3/compiled/22.12.0/linux/x64/better_sqlite3.node
 → node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → node_modules/better-sqlite3/lib/binding/node-v127-linux-x64/better_sqlite3.node`

### However
If I keep node & npm installed and run npm install instead of bun install it will install and run just fine with bun run dev

**Comment by 190n** [comment]
The direct cause of this issue is that some part of the package manager doesn't pass through our `NODE_MODULE_VERSION`. We should fix that, but fixing that won't make `better-sqlite3` work because it uses several V8 APIs that Bun doesn't implement. You can track our progress on V8 APIs in #4290.

**Comment by mmvsk** [comment]
You can use this `bun:sqlite` Prisma adapter: [prisma-adapter-bun-sqlite](https://github.com/mmvsk/prisma-adapter-bun-sqlite)

**Comment by ngdangtu-vn** [comment]
> You can use this `bun:sqlite` Prisma adapter: [prisma-adapter-bun-sqlite](https://github.com/mmvsk/prisma-adapter-bun-sqlite)

This is recommend I got from the error message. However, the `better-sqlite3` in my case was a dependency of another dep. Which mean I couldn't directly replace it as the-end developer. Too bad :'(
