### ISSUE TITLE
@tensorflow/tfjs-backend-wasm transpiler bug

### ISSUE THREAD

**Issue by theoparis** [oven-sh/bun#1695]
### What version of Bun is running?

0.4.0

### What platform is your computer?

Linux 6.1.0-gentoo x86_64 AMD Ryzen 5 5600X 6-Core Processor

### What steps can reproduce the bug?

```ts
import "@tensorflow/tfjs-backend-wasm";
import * as tfjs from "@tensorflowjs/tfjs-core";
```

### What do you see instead?

```
〉bun index.ts                                01/01/2023 02:53:03 AM
SyntaxError: Exported binding '$eXp0rT_05000000' needs to refer to a top-level declared variable.
      at /home/theo/Downloads/babylon/node_modules/@tensorflow/tfjs-backend-wasm/dist/base.js:19:0
```

**Comment by theoparis** [comment]
Also seems to occur when using https://elysiajs.com/collections/eden.html with the example server. `bun -v` says 0.4.1 now as well.

```ts
import { Elysia, t } from "elysia";

const app = new Elysia()
	.get("/", () => "Hi Elysia")
	.get("/id/:id", ({ params: { id } }) => id)
	.post("/mirror", ({ body }) => body, {
		schema: {
			body: t.Object({
				id: t.Number(),
				name: t.String(),
			}),
		},
	})
	.listen(8080);

export type App = typeof app;
```

```
SyntaxError: Exported binding '$eXp0rT_05000000' needs to refer to a top-level declared variable.
      at /usr/local/dev/flowtr-panel/node_modules/elysia/dist/index.js:438:0

```

**Comment by Jarred-Sumner** [comment]
I see the bug. Transpiler is printing some numbers backwards. Likely started after the Zig upgrade.

```js
export { Elysia };
var {Type:$eXp0rT_00000000}=import.meta.require("/Users/jarred/Build/elyis/node_modules/@sinclair/typebox/typebox.js");
export {$eXp0rT_00000000 as t};
var {SCHEMA:$eXp0rT_00000001,getPath:$eXp0rT_00000002,createValidationError:$eXp0rT_00000003,getSchemaValidator:$eXp0rT_00000004}=import.meta.require("/Users/jarred/Build/elyis/node_modules/elysia/dist/utils.js");
export {$eXp0rT_01000000 as SCHEMA,$eXp0rT_02000000 as getPath,$eXp0rT_03000000 as createValidationError,$eXp0rT_04000000 as getSchemaValidator};
var {Router:$eXp0rT_00000005}=import.meta.require("/Users/jarred/Build/elyis/node_modules/elysia/dist/router.js");
export {$eXp0rT_05000000 as Router};
```
