### ISSUE TITLE
sharp object is accessible on development but not in built production

### ISSUE THREAD

**Issue by rayriffy** [oven-sh/bun#1709]
### What version of Bun is running?

0.4.0

### What platform is your computer?

Darwin 22.2.0 arm64 arm

### What steps can reproduce the bug?

Because of `bun` cannot do post build for custom sharp binary, alternative package manager has to be used instead. If you want to see that, running `rm -rf node_modules && bun i && BUN=true bun run web:build` on M1 Mac should do it.
1. `git clone https://github.com/rayriffy/svelte-aio.git`
2. `pnpm i`
3. Run development server with `BUN=true bun run dev`
4. Try navigate to [localhost:5173](http://localhost:5173), you will see sample image being automatically optimized, proof that `sharp` is compatible with bun
5. Remove optimized image cache by `rm -rf .svelte-kit/images`
6. Build production site with `BUN=true bun run web:build && bun ./tools/bun-patcher.js`. Patcher is just for initializing server properly.
7. Run production server with `bun ./build/index.js`
8. Navigate to [localhost:3000](http://localhost:3000) and you will see error in terminal.

```
105 | };
106 | const optimizeImage = async (buffer, contentType, quality, width, height) => {
107 |   try {
108 |     const transformer = sharp(buffer);
109 |     console.log(transformer);
110 |     transformer.rotate();
        ^
TypeError: transformer.rotate is not a function. (In 'transformer.rotate()', 'transformer.rotate' is undefined)
      at /Users/rayriffy/Git/svelte-aio/build/server/entries/endpoints/api/_image/_server.ts.js:110:4
      at /Users/rayriffy/Git/svelte-aio/build/server/entries/endpoints/api/_image/_server.ts.js:106:29
      at /Users/rayriffy/Git/svelte-aio/build/server/entries/endpoints/api/_image/_server.ts.js:257:32
```

### What is the expected behavior?

[`Sharp`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4aa9de6b65ff34a5fc453bb07719e7f6dab8f039/types/sharp/index.d.ts#L132) object should be accessible both in development and production

To see what `Sharp` object would look like, in file [`optimizeImage.ts`](https://github.com/rayriffy/svelte-aio/blob/2808b170c8b59f1cd9ef23b9d7b2e861ddda924c/src/lib/api/functions/optimizeImage.ts#L14) add logging to `transformer`. Then run `rm -rf .svelte-kit && bun run dev` then navigate to [localhost:5173](http://localhost:5173) again, if nothing executed then `CMD + Shift + R` to force load image without browser cache.

<details>
<summary><code>console.log(transformer)</code></summary>

```
Sharp {
  _readableState: ReadableState {
    objectMode: false,
    highWaterMark: 16384,
    buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
    pipes: [],
    flowing: null,
    ended: false,
    endEmitted: false,
    reading: false,
    constructed: true,
    sync: true,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    errorEmitted: false,
    emitClose: true,
    autoDestroy: true,
    destroyed: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    defaultEncoding: 'utf8',
    awaitDrainWriters: null,
    multiAwaitDrain: false,
    readingMore: false,
    dataEmitted: false,
    decoder: null,
    encoding: null,
    [Symbol(kPaused)]: null
  },
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  _writableState: WritableState {
    objectMode: false,
    highWaterMark: 16384,
    finalCalled: false,
    needDrain: false,
    ending: false,
    ended: false,
    finished: false,
    destroyed: false,
    decodeStrings: true,
    defaultEncoding: 'utf8',
    length: 0,
    writing: false,
    corked: 0,
    sync: true,
    bufferProcessing: false,
    onwrite: [Function: bound onwrite],
    writecb: null,
    writelen: 0,
    afterWriteTickInfo: null,
    buffered: [],
    bufferedIndex: 0,
    allBuffers: true,
    allNoop: true,
    pendingcb: 0,
    constructed: true,
    prefinished: false,
    errorEmitted: false,
    emitClose: true,
    autoDestroy: true,
    errored: null,
    closed: false,
    closeEmitted: false,
    [Symbol(kOnFinished)]: []
  },
  allowHalfOpen: true,
  options: {
    topOffsetPre: -1,
    leftOffsetPre: -1,
    widthPre: -1,
    heightPre: -1,
    topOffsetPost: -1,
    leftOffsetPost: -1,
    widthPost: -1,
    heightPost: -1,
    width: -1,
    height: -1,
    canvas: 'crop',
    position: 0,
    resizeBackground: [ 0, 0, 0, 255 ],
    useExifOrientation: false,
    angle: 0,
    rotationAngle: 0,
    rotationBackground: [ 0, 0, 0, 255 ],
    rotateBeforePreExtract: false,
    flip: false,
    flop: false,
    extendTop: 0,
    extendBottom: 0,
    extendLeft: 0,
    extendRight: 0,
    extendBackground: [ 0, 0, 0, 255 ],
    withoutEnlargement: false,
    withoutReduction: false,
    affineMatrix: [],
    affineBackground: [ 0, 0, 0, 255 ],
    affineIdx: 0,
    affineIdy: 0,
    affineOdx: 0,
    affineOdy: 0,
    affineInterpolator: 'bilinear',
    kernel: 'lanczos3',
    fastShrinkOnLoad: true,
    tintA: 128,
    tintB: 128,
    flatten: false,
    flattenBackground: [ 0, 0, 0 ],
    negate: false,
    negateAlpha: true,
    medianSize: 0,
    blurSigma: 0,
    sharpenSigma: 0,
    sharpenM1: 1,
    sharpenM2: 2,
    sharpenX1: 2,
    sharpenY2: 10,
    sharpenY3: 20,
    threshold: 0,
    thresholdGrayscale: true,
    trimBackground: [],
    trimThreshold: 0,
    gamma: 0,
    gammaOut: 0,
    greyscale: false,
    normalise: false,
    claheWidth: 0,
    claheHeight: 0,
    claheMaxSlope: 3,
    brightness: 1,
    saturation: 1,
    hue: 0,
    lightness: 0,
    booleanBufferIn: null,
    booleanFileIn: '',
    joinChannelIn: [],
    extractChannel: -1,
    removeAlpha: false,
    ensureAlpha: -1,
    colourspace: 'srgb',
    colourspaceInput: 'last',
    composite: [],
    fileOut: '',
    formatOut: 'input',
    streamOut: false,
    withMetadata: false,
    withMetadataOrientation: -1,
    withMetadataDensity: 0,
    withMetadataIcc: '',
    withMetadataStrs: {},
    resolveWithObject: false,
    jpegQuality: 80,
    jpegProgressive: false,
    jpegChromaSubsampling: '4:2:0',
    jpegTrellisQuantisation: false,
    jpegOvershootDeringing: false,
    jpegOptimiseScans: false,
    jpegOptimiseCoding: true,
    jpegQuantisationTable: 0,
    pngProgressive: false,
    pngCompressionLevel: 6,
    pngAdaptiveFiltering: false,
    pngPalette: false,
    pngQuality: 100,
    pngEffort: 7,
    pngBitdepth: 8,
    pngDither: 1,
    jp2Quality: 80,
    jp2TileHeight: 512,
    jp2TileWidth: 512,
    jp2Lossless: false,
    jp2ChromaSubsampling: '4:4:4',
    webpQuality: 80,
    webpAlphaQuality: 100,
    webpLossless: false,
    webpNearLossless: false,
    webpSmartSubsample: false,
    webpEffort: 4,
    webpMinSize: false,
    webpMixed: false,
    gifBitdepth: 8,
    gifEffort: 7,
    gifDither: 1,
    gifInterFrameMaxError: 0,
    gifInterPaletteMaxError: 3,
    gifReoptimise: false,
    tiffQuality: 80,
    tiffCompression: 'jpeg',
    tiffPredictor: 'horizontal',
    tiffPyramid: false,
    tiffBitdepth: 8,
    tiffTile: false,
    tiffTileHeight: 256,
    tiffTileWidth: 256,
    tiffXres: 1,
    tiffYres: 1,
    tiffResolutionUnit: 'inch',
    heifQuality: 50,
    heifLossless: false,
    heifCompression: 'av1',
    heifEffort: 4,
    heifChromaSubsampling: '4:4:4',
    jxlDistance: 1,
    jxlDecodingTier: 0,
    jxlEffort: 7,
    jxlLossless: false,
    rawDepth: 'uchar',
    tileSize: 256,
    tileOverlap: 0,
    tileContainer: 'fs',
    tileLayout: 'dz',
    tileFormat: 'last',
    tileDepth: 'last',
    tileAngle: 0,
    tileSkipBlanks: -1,
    tileBackground: [ 255, 255, 255, 255 ],
    tileCentre: false,
    tileId: 'https://example.com/iiif',
    tileBasename: '',
    timeoutSeconds: 0,
    linearA: [],
    linearB: [],
    debuglog: [Function: debuglog],
    queueListener: [Function: queueListener],
    input: {
      failOn: 'warning',
      limitInputPixels: 268402689,
      unlimited: false,
      sequentialRead: false,
      buffer: <Buffer ff d8 ff e1 00 92 45 78 69 66 00 00 4d 4d 00 2a 00 00 00 08 00 09 01 00 00 04 00 00 00 01 00 00 03 21 01 01 00 04 00 00 00 01 00 00 03 21 01 02 00 03 ... 75314 more bytes>
    }
  },
  [Symbol(kCapture)]: false
}
```
</details>

### What do you see instead?

With the same `console.log`, run `rm -rf .svelte-kit && BUN=true bun run web:build && bun ./tools/bun-patcher.js && bun ./build/index.js` go back to [localhost:3000](http://localhost:3000) and make sure to cache being hit again. and you will see that `transformer` has become into completely different types.

<details>
<summary><code>console.log(transformer)</code></summary>

```
{
  _readableState: ReadableState {
    pipesCount: 0,
    paused: null,
    flowing: null,
    objectMode: false,
    ended: false,
    endEmitted: false,
    reading: false,
    constructed: true,
    sync: false,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    errorEmitted: false,
    emitClose: true,
    autoDestroy: true,
    destroyed: false,
    closed: false,
    closeEmitted: false,
    multiAwaitDrain: false,
    readingMore: false,
    dataEmitted: false,
    length: 0,
    highWaterMark: 16384,
    buffer: {
      length: 0,
      push: [Function: push],
      unshift: [Function: unshift],
      shift: [Function: shift],
      clear: [Function: clear],
      first: [Function: first],
      concat: [Function: concat],
      join: [Function: join],
      consume: [Function: consume]
    },
    pipes: [],
    errored: null,
    defaultEncoding: "utf8",
    awaitDrainWriters: null,
    decoder: null,
    encoding: null
  },
  on: [Function],
  destroy: [Function: destroy],
  _undestroy: [Function: undestroy],
  _destroy: [Function],
  push: [Function],
  unshift: [Function],
  isPaused: [Function],
  setEncoding: [Function],
  read: [Function],
  _read: [Function],
  pipe: [Function],
  unpipe: [Function],
  addListener: [Function],
  removeListener: [Function],
  off: [Function],
  removeAllListeners: [Function],
  resume: [Function],
  pause: [Function],
  wrap: [Function],
  iterator: [Function],
  asIndexedPairs: [Function: asIndexedPairs],
  drop: [Function: drop],
  filter: [Function: filter],
  flatMap: [Function: flatMap],
  map: [Function: map],
  take: [Function: take],
  every: [Function: every],
  forEach: [Function: forEach],
  reduce: [Function: reduce],
  toArray: [Function: toArray],
  some: [Function: some],
  find: [Function: find],
  [Symbol(nodejs.rejection)]: [Function],
  [Symbol(Symbol.asyncIterator)]: [Function],
  pipe: [Function],
  addListener: [Function],
  on: [Function],
  once: [Function: once],
  prepend: [Function: prepend],
  prependOnce: [Function: prependOnce],
  removeListener: [Function],
  off: [Function],
  removeAllListeners: [Function],
  emit: [Function: emit],
  eventNames: [Function: eventNames],
  listenerCount: [Function: listenerCount],
  listeners: [Function: listeners],
  rawListeners: [Function: rawListeners],
  setMaxListeners: [Function: setMaxListeners],
  getMaxListeners: [Function: getMaxListeners]
}
```
</details>

**Comment by Jarred-Sumner** [comment]
Please try using `sharp` in the canary build of bun:

```bash
bun upgrade --canary
```

This doesn't address the `bun install` issue, but it should address the runtime issue assuming it was due to missing napi symbols

**Comment by rayriffy** [comment]
I understand circumstances with `bun install` but I think issue is not that critical, I gave bun `0.4.1` but it gives the same results but with different logging as before but it's unrelated.

From my observations, what's bun emit here is just a generic stream object. The way `sharp` make their contractors is by using [`sharp.Duplex`](https://nodejs.org/api/stream.html#class-streamduplex) then [slaps `options` object on top](https://github.com/lovell/sharp/blob/844deaf48060d60eb05f3f61c567282e3611f12a/lib/constructor.js#L171-L343). I still couldn't figuring out what's could be a difference when running between `vite dev` and run production builds to make a difference, while interacting the exact same code in `node_modules`.

<details>
<summary>Production  log</summary>

```
rayriffy at r4yr1ffy in ~/Git/svelte-aio on main ✗                                                              [a67ad80]  8:31
> bun -v
0.4.1
rayriffy at r4yr1ffy in ~/Git/svelte-aio on main ✗                                                              [a67ad80]  8:31
> bun ./build/index.js
Listening on 0.0.0.0:3000
EventEmitter {
  _readableState: ReadableState {
    pipesCount: 0,
    paused: null,
    flowing: null,
    objectMode: false,
    ended: false,
    endEmitted: false,
    reading: false,
    constructed: true,
    sync: false,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    errorEmitted: false,
    emitClose: true,
    autoDestroy: true,
    destroyed: false,
    closed: false,
    closeEmitted: false,
    multiAwaitDrain: false,
    readingMore: false,
    dataEmitted: false,
    length: 0,
    highWaterMark: 16384,
    buffer: {
      length: 0,
      push: [Function: push],
      unshift: [Function: unshift],
      shift: [Function: shift],
      clear: [Function: clear],
      first: [Function: first],
      concat: [Function: concat],
      join: [Function: join],
      consume: [Function: consume]
    },
    pipes: [],
    errored: null,
    defaultEncoding: "utf8",
    awaitDrainWriters: null,
    decoder: null,
    encoding: null
  },
  on: [Function],
  destroy: [Function: destroy],
  _undestroy: [Function: undestroy],
  _destroy: [Function],
  push: [Function],
  unshift: [Function],
  isPaused: [Function],
  setEncoding: [Function],
  read: [Function],
  _read: [Function],
  pipe: [Function],
  unpipe: [Function],
  addListener: [Function],
  removeListener: [Function],
  off: [Function],
  removeAllListeners: [Function],
  resume: [Function],
  pause: [Function],
  wrap: [Function],
  iterator: [Function],
  asIndexedPairs: [Function],
  drop: [Function],
  filter: [Function],
  flatMap: [Function],
  map: [Function],
  take: [Function],
  every: [Function],
  forEach: [Function],
  reduce: [Function],
  toArray: [Function],
  some: [Function],
  find: [Function],
  [Symbol(nodejs.rejection)]: [Function],
  [Symbol(Symbol.asyncIterator)]: [Function],
  pipe: [Function],
  addListener: [Function],
  on: [Function],
  once: [Function: once],
  prepend: [Function: prepend],
  prependOnce: [Function: prependOnce],
  removeListener: [Function],
  off: [Function],
  removeAllListeners: [Function],
  emit: [Function: emit],
  eventNames: [Function: eventNames],
  listenerCount: [Function: listenerCount],
  listeners: [Function: listeners],
  rawListeners: [Function: rawListeners],
  setMaxListeners: [Function: setMaxListeners],
  getMaxListeners: [Function: getMaxListeners]
}
105 | };
106 | const optimizeImage = async (buffer, contentType, quality, width, height) => {
107 |   try {
108 |     const transformer = sharp(buffer);
109 |     console.log(transformer);
110 |     transformer.rotate();
        ^
TypeError: transformer.rotate is not a function. (In 'transformer.rotate()', 'transformer.rotate' is undefined)
      at /Users/rayriffy/Git/svelte-aio/build/server/entries/endpoints/api/_image/_server.ts.js:110:4
      at /Users/rayriffy/Git/svelte-aio/build/server/entries/endpoints/api/_image/_server.ts.js:106:29
      at /Users/rayriffy/Git/svelte-aio/build/server/entries/endpoints/api/_image/_server.ts.js:257:32
```
</details>

**Comment by Jarred-Sumner** [comment]
> BUN=true bun run dev

This doesn't run in bun's runtime. `vite dev` runs in Node.js. You want `bun run --bun  vite dev`

**Comment by Jarred-Sumner** [comment]
Oh, `bun ./build/index.js`

**Comment by Jarred-Sumner** [comment]
I think this is an EventEmitter-related issue, however.

**Comment by drinking-code** [comment]
Works when importing sharp with `require()`.  
something in the binary (pipeline) segfaults, tho

**Comment by rayriffy** [comment]
i'm proud to informed that `sharp` is fully functional in `bun@0.6.6` 🎉🎉🎉

ps. still need to install `node_modules` via pnpm tho but it's unrelated to this issue

**Comment by birkskyum** [comment]
> ps. still need to install node_modules via pnpm tho but it's unrelated to this issue

@rayriffy can you elaborate on this? When I try to `pnpm i`, and then use `bun run _` it can't find any of the modules installed with pnpm and I'm suggested to run `bun install`
