### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'this._final')

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1757]
There is a bug with `node:stream` that prevents the [`decompress`](https://www.npmjs.com/package/decompress) package from working.

@robobun 

```js
import decompress from "decompress";
const response = await fetch("https://github.com/oven-sh/bun/releases/download/bun-v0.4.0/bun-linux-aarch64.zip");
const buffer = await response.arrayBuffer();
const files = await decompress(Buffer.from(buffer));
```

**Comment by robobun** [comment]
@Electroid here you go!
```tsx
1 | decompress;
   ^
ReferenceError: Can't find variable: decompress
      at /tmp/bun-w2Mv33/index.tsx:1:0
```
<details>
  <summary>Code</summary>
  
```tsx
decompress
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._

**Comment by Electroid** [comment]
```
5044 |         }
5045 |       }
5046 |     }
5047 |     function prefinish() {
5048 | 
5049 |       if (this._final !== final) {
             ^
TypeError: undefined is not an object (evaluating 'this._final')
      at prefinish (node:stream:5049:10)
      at onFinish (node:stream:4278:10)
      at final (node:stream:5044:10)
      at callFinal (node:stream:4286:8)
      at prefinish (node:stream:4296:10)
      at finishMaybe (node:stream:4309:6)
      at node:stream:4227:8
      at /node_modules/fd-slicer/index.js:238:2
      at /node_modules/yauzl/index.js:537:23
      at /node_modules/yauzl/index.js:631:4
      at /node_modules/fd-slicer/index.js:202:4
5044 |         }
5045 |       }
5046 |     }
5047 |     function prefinish() {
5048 | 
5049 |       if (this._final !== final) {
             ^
```

**Comment by robobun** [comment]
@Electroid here you go!
```tsx
error: Unexpected }
5044 |         }
/tmp/bun-PTq7du/
/tmp/bun-PTq7du/index.tsx:1:16 15
```
<details>
  <summary>Code</summary>
  
```tsx
5044 |         }
5045 |       }
5046 |     }
5047 |     function prefinish() {
5048 | 
5049 |       if (this._final !== final) {
             ^
TypeError: undefined is not an object (evaluating 'this._final')
      at prefinish (node:stream:5049:10)
      at onFinish (node:stream:4278:10)
      at final (node:stream:5044:10)
      at callFinal (node:stream:4286:8)
      at prefinish (node:stream:4296:10)
      at finishMaybe (node:stream:4309:6)
      at node:stream:4227:8
      at /node_modules/fd-slicer/index.js:238:2
      at /node_modules/yauzl/index.js:537:23
      at /node_modules/yauzl/index.js:631:4
      at /node_modules/fd-slicer/index.js:202:4
5044 |         }
5045 |       }
5046 |     }
5047 |     function prefinish() {
5048 | 
5049 |       if (this._final !== final) {
             ^
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._

**Comment by pateketrueke** [comment]
Hi, I am also suffering from this issue, I am using `formidable` to parse `multipart/form-data` requests.

Which is interesting, because despite the error is shown in the console, it ends parsing the body... it happens inside `Transform.prototype._flush` calls.

**Comment by robobun** [comment]
@pateketrueke here you go!
```tsx
    Transform.prototype._flush;
   ^
ReferenceError: Can't find variable: Transform
      at /tmp/bun-V5Bmh2/index.tsx:1:0
```
<details>
  <summary>Code</summary>
  
```tsx
Transform.prototype._flush
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._

**Comment by ThatOneBro** [comment]
This seems to be fixed in canary:
<img width="803" alt="Screen Shot 2023-01-27 at 1 07 15 AM" src="https://user-images.githubusercontent.com/1592008/215028750-19471880-63a8-4068-b3c2-1a9007471aa3.png">
I think this was fixed by this commit: https://github.com/oven-sh/bun/commit/4dfc09018fe3fee391afc7b4edc129730bd037b8

Should be good to use `decompress` now!

**Comment by robobun** [comment]
@ThatOneBro here you go!
```tsx
1 | decompress;
   ^
ReferenceError: Can't find variable: decompress
      at /tmp/bun-OKM9SL/index.tsx:1:0
```
<details>
  <summary>Code</summary>
  
```tsx
decompress
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._

**Comment by ThatOneBro** [comment]
@robobun 
```js
import decompress from "decompress";
const response = await fetch("https://github.com/oven-sh/bun/releases/download/bun-v0.4.0/bun-linux-aarch64.zip");
const buffer = await response.arrayBuffer();
const files = await decompress(Buffer.from(buffer));
```
Just a final proof that this works

**Comment by robobun** [comment]
@ThatOneBro here you go!
```tsx
error: Cannot find module "/tmp/bun-mUWv6c/.bun/install/cache/strip-dirs@2.1.0@4/polyfills.js" from "/tmp/bun-mUWv6c/.bun/install/cache/graceful-fs@4.2.10/graceful-fs.js"
```
<details>
  <summary>Code</summary>
  
```tsx
import decompress from "decompress";
const response = await fetch("https://github.com/oven-sh/bun/releases/download/bun-v0.4.0/bun-linux-aarch64.zip");
const buffer = await response.arrayBuffer();
const files = await decompress(Buffer.from(buffer));
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._
