### ISSUE TITLE
Implement `process.config`

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1777]
We need to implement stubs for `process.config` so some test code works.

```js
38 | const hasIntl = !!process.config.variables.v8_enable_i18n_support;
                     ^
TypeError: undefined is not an object (evaluating 'process.config.variables')
      at /node/test/common/index.js:38:18
      at /node/test/parallel/test-abortcontroller.js:4:6
```

**Comment by Jarred-Sumner** [comment]
added awhile ago
