### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by wmelton** [oven-sh/bun#1865]
### What version of Bun is running?

0.5.1

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### What steps can reproduce the bug?

Create this js file named 'subscribe.js' and try to run it with bun after installing nats: 

```js
import { connect, StringCodec } from "nats";

const nc = await connect({ servers: "demo.nats.io:4222" });
const sc = StringCodec();

// subscriptions can have wildcard subjects
// the '*' matches any string in the specified token position
const s1 = nc.subscribe("help.*.system");
const s2 = nc.subscribe("help.me.*");
// the '>' matches any tokens in that position or following
// '>' can only be specified at the end of the subject
const s3 = nc.subscribe("help.>");

async function printMsgs(s) {
  let subj = s.getSubject();
  console.log(`listening for ${subj}`);
  const c = (13 - subj.length);
  const pad = "".padEnd(c);
  for await (const m of s) {
    console.log(
      `[${subj}]${pad} #${s.getProcessed()} - ${m.subject} ${
        m.data ? " " + sc.decode(m.data) : ""
      }`,
    );
  }
}

printMsgs(s1);
printMsgs(s2);
printMsgs(s3);

// don't exit until the client closes
await nc.closed();
```

### What is the expected behavior?

Runs correctly like node.js

### What do you see instead?

`zsh: segmentation fault  bun subscribe.js`

### Additional information

I wasn't able to trigger a more detailed failure message. `zsh: segmentation fault  bun subscribe.js` is all that's given.

**Comment by Jarred-Sumner** [comment]
Can you go into Console.app and paste the stack trace? If that doesn't have much info, can you download `bun-profile` for x64 from the releases page?

On my M1, it reports this stack trace:
```js
❯ bun index.ts
88 |      * @constructor
89 |      *
90 |      * @api private
91 |      */
92 |     constructor(message, code, chainedError) {
93 |         super(message);
            ^
NatsError: TLS
 code: "TLS"

      at new NatsError (/Users/jarred/Build/bun-repros/1865/node_modules/nats/lib/nats-base-client/error.js:93:8)
      at errorForCode (/Users/jarred/Build/bun-repros/1865/node_modules/nats/lib/nats-base-client/error.js:101:15)
      at /Users/jarred/Build/bun-repros/1865/node_modules/nats/lib/src/node_transport.js:258:25
      at /Users/jarred/Build/bun-repros/1865/node_modules/nats/lib/src/node_transport.js:8:8
      at /Users/jarred/Build/bun-repros/1865/node_modules/nats/lib/src/node_transport.js:4:11
      at /Users/jarred/Build/bun-repros/1865/node_modules/nats/lib/src/node_transport.js:70:40
      at fulfilled (/Users/jarred/Build/bun-repros/1865/node_modules/nats/lib/src/node_transport.js:5:47)
```

**Comment by wmelton** [comment]
Sure: 

```bash
88 |      * @constructor
89 |      *
90 |      * @api private
91 |      */
92 |     constructor(message, code, chainedError) {
93 |         super(message);
            ^
NatsError: TLS
 code: "TLS"

      at new NatsError (/Users/[username]/Documents/Dev/NATS/node_modules/nats/lib/nats-base-client/error.js:93:8)
      at errorForCode (/Users/[username]/Documents/Dev/NATS/node_modules/nats/lib/nats-base-client/error.js:101:15)
      at /Users/[username]/Documents/Dev/NATS/node_modules/nats/lib/src/node_transport.js:258:25
      at /Users/[username]/Documents/Dev/NATS/node_modules/nats/lib/src/node_transport.js:8:8
      at /Users/[username]/Documents/Dev/NATS/node_modules/nats/lib/src/node_transport.js:4:11
      at /Users/[username]/Documents/Dev/NATS/node_modules/nats/lib/src/node_transport.js:70:40
      at fulfilled (/Users/[username]/Documents/Dev/NATS/node_modules/nats/lib/src/node_transport.js:5:47)
```

Looks like same stack trace you're getting actually.

**Comment by birkskyum** [comment]
I see now:

```sh
➜ bun run index.ts
listening for help.*.system
listening for help.me.*
listening for help.>
```

So no segfault

**Comment by Jarred-Sumner** [comment]
Yeah this is very likely fixed

I'm going to close it but if you run into this again please leave a comment @wmelton
