### ISSUE TITLE
readline interface doesn't close

### ISSUE THREAD

**Issue by olebergen** [oven-sh/bun#1873]
### What version of Bun is running?

0.5.1

### What platform is your computer?

Linux 6.0.8-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

```sh
cat << EOT >> readline.mjs
import * as readline from "node:readline";
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});
rl.question("test ", () => {
  rl.close();
});
EOT
bun readline.mjs
```

Type something and press enter

### What is the expected behavior?

The program should exit, after I answer the prompt

### What do you see instead?

After I type something and press enter the input gets printed and the program keeps running, I have to press enter again to close it.
```sh
$ bun readline.mjs
test x
x

```

### Additional information

I tried the async example from `readline.d.ts`, same thing. Both work in node 18

**Comment by ThatOneBro** [comment]
Thank you for reporting this, I actually noticed this just before the release of 0.5.0 but forgot to make a public note. I think I may have found the problem thanks to your example.

**Comment by tsp1998** [comment]
```js
// read-stream.ts
import { ReadStream } from 'fs'

const readStream = async (stream: ReadStream): Promise<string | Buffer> => {
  return new Promise((resolve) => {
    let content = ''
    stream.on('data', (chunk) => {
      content += chunk.toString()
    })
    stream.on('end', () => resolve(content))
  })
}

export default readStream

// parse-content-or-read-stream-to-object.ts
import { ReadStream } from 'fs'
import { createInterface, Interface } from 'readline/promises'
import readStream from '../api/fs/read-stream'

const parseContentOrReadStreamToObject = async (
  contentOrReadStream: string | ReadStream,
  $dataOptional?: $data.ParseContentOrReadStreamToObjectDataOptional
) => {
  const result: typeof $env = {}
  const { attchTo = {}, separtor = '=' } = $dataOptional || {}
  try {
    const processContent = (content: string) => {
      const lines = content.split('\n')
      for (let i = 0; i < lines.length; i++) {
        // const regex = new RegExp(`/${separtor}(.*)/`)
        // let [key, value] = lines[i].split(regex)
        const line = lines[i]
        const separtorIndex = line.indexOf(separtor)
        const key = line.slice(0, separtorIndex).trim()
        const value = line.slice(separtorIndex + 1).trim()
        attchTo[key] = value
        result[key] = value
      }
    }

    if (typeof contentOrReadStream === 'string') {
      processContent(contentOrReadStream)
    } else {
      try {
        const rlInterface = createInterface(contentOrReadStream)
        if (rlInterface instanceof Interface) {
          for await (const line of rlInterface) {
            let [key, value] = line.split(/=(.*)/)
            key = key.trim()
            value = value.trim()
            attchTo[key] = value
            result[key] = value
          }
        }
      } catch (error) {
        console.log(`error`, error)
        const content = await readStream(contentOrReadStream)
        processContent(content as string)
      }
    }
  } catch (error) {
    console.log(`error`, (error as $Error['default']).message)
  }
  return result
}

export default parseContentOrReadStreamToObject

// parse-content-or-read-stream-to-object.test.ts
import parseContentOrReadStreamToObject from '../parse-content-or-read-stream-to-object'
import '../../start/common/init-process-env'
import { createReadStream } from 'fs'

const main = async () => {
  const result = await parseContentOrReadStreamToObject(`
    abc=xyz
    foo=bar
  `)

  console.log('result', result)
  const readableStream = createReadStream('sample.txt')
  const result2 = await parseContentOrReadStreamToObject(readableStream)
  console.log(`result2`, result2)
  // console.log('process.env', process.env)
}

main()

//sample.txt
abc:xyz
foo:bar

```

throws error 
27 |       processContent(contentOrReadStream)
28 |     } else {
29 |       try {
30 |         const rlInterface = createInterface(contentOrReadStream)
31 |         if (rlInterface instanceof Interface) {
32 |           for await (const line of rlInterface) {
                               ^
TypeError: undefined is not an object (evaluating 'line of rlInterface')
      at /home/royaltsp/tsp/royaltsp/royaltsp-ts/src/lib/data/parse-content-or-read-stream-to-object.ts:32:27
      at /home/royaltsp/tsp/royaltsp/royaltsp-ts/src/lib/data/parse-content-or-read-stream-to-object.ts:6:2
      at /home/royaltsp/tsp/royaltsp/royaltsp-ts/src/lib/data/tests/parse-content-or-read-stream-to-object.test.ts:13:24

works fine with node js

**Comment by birkskyum** [comment]
The initial repro does now exit, when the prompt is answered, so it appear to work correctly in 0.8.1
