### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'duck.duckffi_open')

### ISSUE THREAD

**Issue by kimmolinna** [oven-sh/bun#1896]
### What version of Bun is running?

0.5.1

### What platform is your computer?

Darwin 22.2.0 arm64 arm

### What steps can reproduce the bug?

bun add @evan/duckdb
bun test.js

test.js
```js
import { open } from '@evan/duckdb';

const db = open('./example.db');
// or const db = open(':memory:');
```

### What is the expected behavior?

The function shoud return a new database class. 

### What do you see instead?

```js
119 | export function open(path) {
120 |   const db = path === null
121 |     ? duck.duckffi_open(true, 0)
122 |     : duck.duckffi_open(false, ptr(utf8e.encode(path + '\0')));
          ^
TypeError: undefined is not an object (evaluating 'duck.duckffi_open')
      at open (/Users/linna/node_modules/@evan/duckdb/lib.mjs:122:6)
      at open (/Users/linna/node_modules/@evan/duckdb/index.mjs:4:22)
      at /Users/linna/duckdb-bun/test.js:4:11
```

### Additional information

This worked with the previous version. I assume it was 0.4. and something.

**Comment by kimmolinna** [comment]
This is working after `bun upgrade --canary`
