### ISSUE TITLE
ESBuild module resolve error

### ISSUE THREAD

**Issue by dalisoft** [oven-sh/bun#1974]
### What version of Bun is running?

0.5.4

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

- Clone repo via `git clone git@github.com:dalisoft/pnpm-esbuild.git` and go-to cloned folder
- Run `bun install` on each of subfolders
- Run `bun run ./scripts/build.mjs` at `frontend` folder
- YOU WILL SEE ERROR

### What is the expected behavior?

Successfully build

### What do you see instead?

```
❯ bun run ./scripts/build.mjs
✘ [ERROR] Could not resolve "react"

    ../ui-shared/components/Button/Button.jsx:1:24:
      1 │ import { useMemo } from "react";
        ╵                         ~~~~~~~

  You can mark the path "react" as external to exclude it from the bundle, which will remove this
  error.

1631 |     let { file, line, column } = e.location;
1632 |     let pluginText = e.pluginName ? `[plugin: ${e.pluginName}] ` : "";
1633 |     return `
1634 | ${file}:${line}:${column}: ERROR: ${pluginText}${e.text}`;
1635 |   }).join("");
1636 |   let error = new Error(`${text}${summary}`);
                  ^
error: Build failed with 1 error:
../ui-shared/components/Button/Button.jsx:1:24: ERROR: Could not resolve "react"
 errors: [
  {
    "id": "",
    "location": {
      "column": 24,
      "file": "../ui-shared/components/Button/Button.jsx",
      "length": 7,
      "line": 1,
      "lineText": "import { useMemo } from \"react\";",
      "namespace": "",
      "suggestion": ""
    },
    "notes": [
      {
        "location": null,
        "text": "You can mark the path \"react\" as external to exclude it from the bundle, which will remove this error."
      }
    ],
    "pluginName": "",
    "text": "Could not resolve \"react\""
  }
]

      at failureErrorWithLog (/Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/node_modules/esbuild/lib/main.js:1636:14)
      at /Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/node_modules/esbuild/lib/main.js:1048:24
      at /Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/node_modules/esbuild/lib/main.js:1046:6
      at /Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/node_modules/esbuild/lib/main.js:697:8
      at /Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/node_modules/esbuild/lib/main.js:752:8
      at /Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/node_modules/esbuild/lib/main.js:673:6
      at addChunk (node:stream:3014:8)
      at readableAddChunk (node:stream:2987:12)
      at node:stream:5868:8
      at node:stream:6066:35
```

**Comment by Electroid** [comment]
As of Bun v1.0.7, this has been fixed.

```
❯ bun run ./scripts/build.mjs
Build succesfully with 0 errors and 0 warnings
```

If you can still reproduce this error after upgrading, please feel free to re-open this issue.
