### ISSUE TITLE
MongoDB authentication fails

### ISSUE THREAD

**Issue by TechFun4** [oven-sh/bun#1991]
### What version of Bun is running?

0.5.5

### What platform is your computer?

Linux 5.19.0-29-generic x86_64 x86_64 (Ubuntu 22.10)

### What steps can reproduce the bug?

`bun run buntest.js`

buntest.js content:
```js
const mongoose = require('mongoose');

(async () => {
  mongoose.set('strictQuery', true);
  await mongoose.connect(process.env.MONGO_URI, {
    autoIndex: false,
  });
})();
```

### What is the expected behavior?

Establish a connection successfully. The same code authenticates correctly with node.

### What do you see instead?

This error fires instantly:
```js
92 |         if (message instanceof Error) {
93 |             super(message.message);
94 |             this.cause = message;
95 |         }
96 |         else {
97 |             super(message);
                ^
error: Authentication failed.
 code: "18"

      at new MongoError (/home/techfun/tsl-cdn/node_modules/mongodb/lib/error.js:97:12)
      at new MongoServerError (/home/techfun/tsl-cdn/node_modules/mongodb/lib/error.js:133:8)
      at onMessage (/home/techfun/tsl-cdn/node_modules/mongodb/lib/cmap/connection.js:230:29)
      at processIncomingData (/home/techfun/tsl-cdn/node_modules/mongodb/lib/cmap/message_stream.js:125:8)
      at _write (/home/techfun/tsl-cdn/node_modules/mongodb/lib/cmap/message_stream.js:33:8)
      at writeOrBuffer (node:stream:3611:8)
      at node:stream:3571:13
      at ondata (node:stream:2984:20)
      at addChunk (node:stream:2710:8)
      at readableAddChunk (node:stream:2691:12)
      at data (node:net:94:14)
```

### Additional information

mongoose 6.9.0 (depends on mongodb 5.0.0)

**Comment by sp90** [comment]
This error still exist in bun-canary, i ran the follow code as a test for both node and bun

```javascript
const mongoose = require('mongoose');

main()

async function main() {
  try {
    const connection = await mongoose.connect('mongodb+srv://USER:PASS@cluster0.CLUSTER_ID.mongodb.net/DB_NAME');

    console.log(connection);
    console.log('Connected to MongoDB');
  } catch (error) {
    console.log(error);
  }
}
```

I get the following error:
<img width="1394" alt="Screenshot 2023-04-24 at 16 18 23" src="https://user-images.githubusercontent.com/3041602/234024487-00196cfc-aabf-4468-9876-c1ca1283310e.png">

And i have allowed the IP on my atlas connection - i did also find this

<img width="385" alt="Screenshot 2023-04-24 at 16 26 25" src="https://user-images.githubusercontent.com/3041602/234118998-b8b4c17f-b133-444a-a0cf-02522bae872b.png">

**Comment by swagisays** [comment]
same issue

**Comment by sp90** [comment]
A wild hunch its one of the TLS features bun is missing

**Comment by rezcoco** [comment]
Got the same issue here, I'm using 0.5.9

![Screenshot 2023-05-14 135616](https://github.com/oven-sh/bun/assets/77873738/e9b912c9-3f4c-4cf3-ad4a-0cf25c457f8c)

**Comment by cirospaciari** [comment]
> sp90

Sorry that you encounter this problem, thanks for filling this issue.
Can you try setting the options `&tls=true&tlsCAFile=ca_cert.pem` pointing to your CA file? looks like a tls validation issue.

**Comment by sp90** [comment]
Would you mind telling me where do i find the ca_cert on a Mac: or obtain it at least

**Comment by hpx7** [comment]
Seeing this again on bun 1.1.7:

```js
92 |  * @privateRemarks
93 |  * mongodb-client-encryption has a dependency on this error, it uses the constructor with a string argument
94 |  */
95 | class MongoError extends Error {
96 |     constructor(message) {
97 |         super(MongoError.buildErrorMessage(message));
             ^
error: Authentication failed.
 code: "18"

      at new MongoError (/project/node_modules/.pnpm/mongodb@5.9.2/node_modules/mongodb/lib/error.js:97:9)
      at new MongoServerError (/project/node_modules/.pnpm/mongodb@5.9.2/node_modules/mongodb/lib/error.js:147:9)
      at onMessage (/project/node_modules/.pnpm/mongodb@5.9.2/node_modules/mongodb/lib/cmap/connection.js:202:26)
      at processIncomingData (/project/node_modules/.pnpm/mongodb@5.9.2/node_modules/mongodb/lib/cmap/message_stream.js:124:9)
      at _write (/project/node_modules/.pnpm/mongodb@5.9.2/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
      at writeOrBuffer (node:stream:2629:53)
      at node:stream:2612:79
      at ondata (node:stream:2128:43)
      at /project/node_modules/.pnpm/dd-trace@4.36.0/node_modules/dd-trace/packages/datadog-instrumentations/src/net.js:69:20
      at addChunk (node:stream:1953:43)
      at readableAddChunk (node:stream:1907:59)
      at data (node:net:52:17)

Bun v1.1.7 (macOS arm64)
```

The project works with `tsx`, but I get this error when replacing `tsx` with `bun`

**Comment by sp90** [comment]
@hpx7 did you test with node as well, because I have had mongo run for a long time on bun now :) so I think it's unlikely to think the problem stems from the same origin?

**Comment by hpx7** [comment]
I narrowed down the issue to be in conjunction with dd-trace: https://github.com/oven-sh/bun/issues/10468#issuecomment-2119306208

**Comment by emastho** [comment]
Not sure if same issue, but if it helps someone

Connecting like this worked for me

```js
await mongoose.connect("mongodb://localhost:27017/database", {
    authSource: "admin",
    user: "root",
    pass: "example",
});
```
