### ISSUE TITLE
`bun run ora.mjs --no-install` failing to run `error: Cannot find module`

### ISSUE THREAD

**Issue by vithalreddy** [oven-sh/bun#2021]
### What version of Bun is running?

0.5.6

### What platform is your computer?

Linux 5.15.79.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

spin.mjs
```ts
import ora from 'ora';

const spinner = ora('Loading unicorns').start();
const colors = ["red", "blue", "green", "yellow", "cyan", "magenta", "white"];

setInterval(() => {
        const randomColor = colors[Math.floor(Math.random() * colors.length)];
        spinner.color = randomColor;
        spinner.text = 'Loading rainbows';
}, 1000);
```

### What is the expected behavior?

Run without any error

### What do you see instead?

```bash
bun run spin.mjs --no-install

error: Cannot find module "/home/v/.bun/install/cache/is-unicod/utilities.js" from "/home/v/.bun/install/cache/ora@6.1.2/index.js"
```

### Additional information

after adding manual dep using `bun add ora`

gives following error

```bash
╰─ bun run spin.mjs
222 |   clear() {
223 |           if (!this.#isEnabled || !this.#stream.isTTY) {
224 |                   return this;
225 |           }
226 |
227 |           this.#stream.cursorTo(0);
     ^
TypeError: this.#stream.cursorTo is not a function. (In 'this.#stream.cursorTo(0)', 'this.#stream.cursorTo' is undefined)
      at clear (/home/v/Projects/bun/node_modules/ora/index.js:227:2)
      at render (/home/v/Projects/bun/node_modules/ora/index.js:252:2)
      at start (/home/v/Projects/bun/node_modules/ora/index.js:289:2)
      at /home/v/Projects/bun/spin.mjs:3:16
```

**Comment by ThatOneBro** [comment]
Hey @vithalreddy, thank you for posting this issue. However, we are already tracking this here: #1570. 

I'll close this for now but we can continue tracking this issue over there. I should be able to get this in before the next release
