### ISSUE TITLE
[Bun] Fails to import a dependency ONLY if "node_modules" directory exists

### ISSUE THREAD

**Issue by eddyw** [oven-sh/bun#2157]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Darwin 22.3.0 x86_64 i386

### What steps can reproduce the bug?

Clone [this repository (eddyw/bun-bug)](https://github.com/eddyw/bun-bug), then execute the following commands to install and run the `index.mts` script:

```bash
$ bun install
$ bun index.mts # Errors
35 |     }
36 | };
37 | import { BindingScopeEnum } from "../inversify";
38 | import { isPromise } from "../utils/async";
39 | export var tryGetFromScope = function (requestScope, binding) {
40 |     if ((binding.scope === BindingScopeEnum.Singleton) && binding.activated) {
                               ^
TypeError: undefined is not an object (evaluating 'BindingScopeEnum.Singleton')
      at /<REDACTED>/bun-bug/node_modules/inversify/es/scope/scope.js:40:27
      at /<REDACTED>/bun-bug/node_modules/inversify/es/resolution/resolver.js:95:17
      at /<REDACTED>/bun-bug/node_modules/inversify/es/container/container.js:600:25
      at /<REDACTED>/bun-bug/node_modules/inversify/es/container/container.js:359:27
      at step (/<REDACTED>/bun-bug/node_modules/inversify/es/container/container.js:43:17)
      at /<REDACTED>/bun-bug/node_modules/inversify/es/container/container.js:18:8
      at /<REDACTED>/bun-bug/node_modules/inversify/es/container/container.js:14:11
      at /<REDACTED>/bun-bug/index.mts:10:0
```

Now, execute the following command:

```bash
$ rm -rf node_modules/
$ bun index.mts # Works!
Hello bun
```

You can repeat the same steps again to reproduce it once more.

### What is the expected behavior?

It should correctly resolve the dependencies if `node_modules` is present.

### What do you see instead?

It seems to fail importing a dependency file's exports:

```
35 |     }
36 | };
37 | import { BindingScopeEnum } from "../inversify";
38 | import { isPromise } from "../utils/async";
39 | export var tryGetFromScope = function (requestScope, binding) {
40 |     if ((binding.scope === BindingScopeEnum.Singleton) && binding.activated) {
                               ^
TypeError: undefined is not an object (evaluating 'BindingScopeEnum.Singleton')
      at /<REDACTED>/bun-bug/node_modules/inversify/es/scope/scope.js:40:27
      at /<REDACTED>/bun-bug/node_modules/inversify/es/resolution/resolver.js:95:17
      at /<REDACTED>/bun-bug/node_modules/inversify/es/container/container.js:600:25
      at /<REDACTED>/bun-bug/node_modules/inversify/es/container/container.js:359:27
      at step (/<REDACTED>/bun-bug/node_modules/inversify/es/container/container.js:43:17)
      at /<REDACTED>/bun-bug/node_modules/inversify/es/container/container.js:18:8
      at /<REDACTED>/bun-bug/node_modules/inversify/es/container/container.js:14:11
      at /<REDACTED>/bun-bug/index.mts:10:0
```

### Additional information

**Minimal reproduction repository**: [eddyw/bun-bug](https://github.com/eddyw/bun-bug)

You can see in the stack trace where the error is happening. There is this if statement:

```js
     if ((binding.scope === BindingScopeEnum.Singleton) && binding.activated) {
```

The `BindingScopeEnum` is imported from:

```js
import { BindingScopeEnum } from "../inversify";
```

In `inversify.js` is defined as:

```js
var BindingScopeEnum = {
    Request: "Request",
    Singleton: "Singleton",
    Transient: "Transient"
};

// ... code and more code

export { BindingScopeEnum }
```

This work in Node.js if executed with `ts-node` (TypeScript), `ts-node --swc` (use SWC compiler) and `tsx` (esbuild):

```bash
$ ts-node --esm index.mts # (TypeScript compiler) Works
$ ts-node --swc --esm index.mts # (SWC Compiler) Works
$ tsx index.mts # (esbuild) Works
```

**Comment by dylan-conway** [comment]
this is fixed in v0.6.13.
