### ISSUE TITLE
Cannot run payload due to something going wrong in memfs

### ISSUE THREAD

**Issue by thgh** [oven-sh/bun#2247]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

```
npx create-payload-app
# > Typescript
# > blank
bun src/server.ts
```

### What is the expected behavior?

Listening on port 3000

### What do you see instead?

```
bun src/server.ts
[0.04ms] ".env"
232 |         // Number of children.
233 |         _this.length = 0;
234 |         _this.vol = vol;
235 |         _this.parent = parent;
236 |         _this.name = name;
237 |         _this.syncSteps();
            ^
TypeError: _this.syncSteps is not a function. (In '_this.syncSteps()', '_this.syncSteps' is undefined)
      at new Link (/app/node_modules/memfs/lib/node.js:237:8)
      at /app/node_modules/memfs/lib/volume.js:531:19
      at new Volume (/app/node_modules/memfs/lib/volume.js:462:19)
      at /app/node_modules/memfs/lib/index.js:23:14
      at /app/node_modules/webpack-dev-middleware/dist/utils/setupOutputFileSystem.js:10:4
      at /app/node_modules/webpack-dev-middleware/dist/index.js:20:29
      at /app/node_modules/webpack-dev-middleware/dist/cjs.js:3:6
      at /app/node_modules/payload/dist/webpack/init.js:8:33
      at /app/node_modules/payload/dist/express/admin.js:9:15
      at /app/node_modules/payload/dist/initHTTP.js:11:16
      at /app/node_modules/payload/dist/index.js:4:6
      at /app/src/server.ts:2:0
```

### Additional information

Same behaviour in previous versions

**Comment by Jarred-Sumner** [comment]
Thanks for filing

**Comment by Electroid** [comment]
Since Bun v1.0, this error no longer occurs. If you are still running into this issue after upgrading, please re-open this issue and we'll investigate.
