### ISSUE TITLE
process.binding('natives'); error when using dependencyTree module

### ISSUE THREAD

**Issue by Seyaji** [oven-sh/bun#2254]
### What version of Bun is running?

5.7

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

import dependencyTree from "dependency-tree";
import path from "path";

const options = {
  filename: path.resolve(__dirname, "./index.ts"),
  directory: path.resolve(__dirname, "../"),
  tsConfig: path.resolve(__dirname, "../tsconfig.json"),
  webpackConfig: path.resolve(__dirname, "../webpack.config.js"),
};

const tree = dependencyTree(options);

TypeError: process.binding is not supported in Bun. If this breaks a library you're using, please file an issue at https://bun.sh/issues and include a reproducible code sample.
      at /Users/alex/Projects/Personal/canvas-node/node_modules/precinct/index.js:21:16
      at /Users/alex/Projects/Personal/canvas-node/node_modules/dependency-tree/index.js:3:6
      at /Users/alex/Projects/Personal/canvas-node/src/index.ts:5:0

### What is the expected behavior?

It would generate the dependency tree and assing it to the const tree = variable

### What do you see instead?

TypeError: process.binding is not supported in Bun. If this breaks a library you're using, please file an issue at https://bun.sh/issues and include a reproducible code sample.
      at /Users/alex/Projects/Personal/canvas-node/node_modules/precinct/index.js:21:16
      at /Users/alex/Projects/Personal/canvas-node/node_modules/dependency-tree/index.js:3:6
      at /Users/alex/Projects/Personal/canvas-node/src/canvas.ts:5:0

**Comment by jamesonhill** [comment]
Getting a similar error when trying to run a graphql server
```
1 | (function (bindingName){"use strict";if(bindingName==="constants")return @processBindingConstants;const issue={fs:3546,buffer:2020,natives:2254,uv:2891}[bindingName];if(issue)throw new Error(`process.binding("${bindingName}") is not implemented in Bun. Track the status & thumbs up the issue: https://github.com/oven-sh/bun/issues/${issue}`);@throwTypeError(`process.binding("${bindingName}") is not implemented in Bun. If that breaks something, please file an issue and include a reproducible code sample.`)})
                       ^
error: process.binding("natives") is not implemented in Bun. Track the status & thumbs up the issue: https://github.com/oven-sh/bun/issues/2254
      at binding (:1:20)
      at /Users/jamesonhill/Projects/packages/apollo-server/node_modules/diagnostic-channel/dist/src/patchRequire.js:11:32
      at globalThis (/Users/jamesonhill/Projects/packages/apollo-server/node_modules/diagnostic-channel/dist/src/patchRequire.js:63:30)
      at require (:1:20)
      at /Users/jamesonhill/Projects/packages/apollo-server/node_modules/diagnostic-channel/dist/src/channel.js:6:4
      at globalThis (/Users/jamesonhill/Projects/packages/apollo-server/node_modules/diagnostic-channel/dist/src/channel.js:143:25)
      at require (:1:20)
      at /Users/jamesonhill/Projects/packages/apollo-server/node_modules/diagnostic-channel-publishers/dist/src/azure-coretracing.pub.js:4:4
```

**Comment by Ateeq72** [comment]
Similar error when trying to start laravel-echo-server

```
1 | (function (bindingName){"use strict";if(bindingName==="constants")return @processBindingConstants;const issue={fs:3546,buffer:2020,natives:2254,uv:2891}[bindingName];if(issue)throw new Error(`process.binding("${bindingName}") is not implemented in Bun. Track the status & thumbs up the issue: https://github.com/oven-sh/bun/issues/${issue}`);@throwTypeError(`process.binding("${bindingName}") is not implemented in Bun. If that breaks something, please file an issue and include a reproducible code sample.`)})
                       ^
error: process.binding("natives") is not implemented in Bun. Track the status & thumbs up the issue: https://github.com/oven-sh/bun/issues/2254
      at binding (:1:20)
      at /opt/nodejs/lib/node_modules/laravel-echo-server/node_modules/builtin-modules/index.js:8:29
      at globalThis (/opt/nodejs/lib/node_modules/laravel-echo-server/node_modules/builtin-modules/index.js:10:8)
      at require (:1:20)
      at /opt/nodejs/lib/node_modules/laravel-echo-server/node_modules/is-builtin-module/index.js:2:4
      at globalThis (/opt/nodejs/lib/node_modules/laravel-echo-server/node_modules/is-builtin-module/index.js:9:40)
      at require (:1:20)
      at /opt/nodejs/lib/node_modules/laravel-echo-server/node_modules/normalize-package-data/lib/fixer.js:4:4
      at globalThis (/opt/nodejs/lib/node_modules/laravel-echo-server/node_modules/normalize-package-data/lib/fixer.js:311:0)
      at require (:1:20)
      at /opt/nodejs/lib/node_modules/laravel-echo-server/node_modules/normalize-package-data/lib/normalize.js:3:4
      at globalThis (/opt/nodejs/lib/node_modules/laravel-echo-server/node_modules/normalize-package-data/lib/normalize.js:18:49)
      at require (:1:20)
      at /opt/nodejs/lib/node_modules/laravel-echo-server/node_modules/read-pkg/index.js:4:4
      at globalThis (/opt/nodejs/lib/node_modules/laravel-echo-server/node_modules/read-pkg/index.js:47:8)
      at require (:1:20)
      at /opt/nodejs/lib/node_modules/laravel-echo-server/node_modules/read-pkg-up/index.js:3:4
      at globalThis (/opt/nodejs/lib/node_modules/laravel-echo-server/node_modules/read-pkg-up/index.js:30:1)
      at require (:1:20)
      at pkgUp (/opt/nodejs/lib/node_modules/laravel-echo-server/node_modules/yargs/yargs.js:373:10)
      at parseArgs (/opt/nodejs/lib/node_modules/laravel-echo-server/node_modules/yargs/yargs.js:680:28)
      at /opt/nodejs/lib/node_modules/laravel-echo-server/node_modules/yargs/yargs.js:502:22
      at /opt/nodejs/lib/node_modules/laravel-echo-server/node_modules/yargs/lib/usage.js:43:28
      at get (/opt/nodejs/lib/node_modules/laravel-echo-server/node_modules/yargs/yargs.js:670:8)
      at /opt/nodejs/lib/node_modules/laravel-echo-server/dist/cli/index.js:13:22
      at globalThis (/opt/nodejs/lib/node_modules/laravel-echo-server/dist/cli/index.js:14:5)
      at require (:1:20)
      at /opt/nodejs/lib/node_modules/laravel-echo-server/bin/server.js:10:4
      at globalThis (/opt/nodejs/lib/node_modules/laravel-echo-server/bin/server.js:12:16)
```

**Comment by praashie** [comment]
The same error happens when importing [`applicationinsights`](https://www.npmjs.com/package/applicationinsights), as the [module `diagnostic-channel` tries to access `process.binding('natives')`](https://github.com/microsoft/node-diagnostic-channel/blob/master/src/diagnostic-channel/src/patchRequire.ts#L23C63-L23C63):

```typescript
const nativeModules = Object.keys(process.binding("natives"));
```

This case seems to tolerate receiving empty objects from the `process.binding()` call.

**Comment by devalberg** [comment]
Same here with [applicationinsights](https://www.npmjs.com/package/applicationinsights)

**Comment by sljeff** [comment]
This package also has the same error: [github-copilot-cli](https://www.npmjs.com/package/@githubnext/github-copilot-cli)

**Comment by gigpiged** [comment]
Same here with [Netlify CLI](https://www.npmjs.com/package/netlify-cli)
