### ISSUE TITLE
`ReferenceError: Cannot access uninitialized variable` when using Puppeteer

### ISSUE THREAD

**Issue by swissspidy** [oven-sh/bun#2316]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

```ts
// script.ts
import puppeteer from "puppeteer";

const browser = await puppeteer.launch();
```

`package.json` has `"type": "module"` and references `puppeteer` `^19.6.3`.

### What is the expected behavior?

No error and Puppeteer should run.

### What do you see instead?

```
$ bun script.ts 
28 | import { ElementHandle, } from '../api/ElementHandle.js';
29 | import { assert } from '../util/assert.js';
30 | import { AsyncIterableUtil } from '../util/AsyncIterableUtil.js';
31 | import { getQueryHandlerAndSelector } from './GetQueryHandler.js';
32 | import { CDPJSHandle } from './JSHandle.js';
33 | import { debugError, isString } from './util.js';
   ^
ReferenceError: Cannot access uninitialized variable.
      at /path/to/../node_modules/puppeteer-core/lib/esm/puppeteer/common/ElementHandle.js:33:0
```

**Comment by uqe** [comment]
Same issue.

Bun: v0.5.7
Puppeteer: v19.7.5

**Comment by way-zer** [comment]
Relevant issue(esm circular dependency)
Bun: v0.5.7
@deepkit/type: 1.0.1-alpha.91
```ts
import {as} from "@deepkit/type"
as()
```
Output:
```
1 | /*@ts-ignore*/
2 | import { __ΩTypeParameter as __ΩTypeParameter } from './type.js';
   ^
ReferenceError: Cannot access uninitialized variable.
      at node_modules/@deepkit/type/dist/esm/src/reflection/extends.js:2:0
```

**Comment by wavded** [comment]
I think I have the same issue:

Bun: 0.6.2
Puppeteer: 20.2.1

```
25 |     return (kind === "a" ? f.call(receiver, value) : f ? f.value = value : state.set(receiver, value)), value;
26 | };
27 | var _CDPJSHandle_disposed, _CDPJSHandle_context, _CDPJSHandle_remoteObject;
28 | import { JSHandle } from '../api/JSHandle.js';
29 | import { assert } from '../util/assert.js';
30 | import { createJSHandle, releaseObject, valueFromRemoteObject, withSourcePuppeteerURLIfNone, } from './util.js';
   ^
ReferenceError: Cannot access uninitialized variable.
      at /path/to.../node_modules/puppeteer/node_modules/puppeteer-core/lib/esm/puppeteer/common/JSHandle.js:30:0
      at /path/to.../node_modules/puppeteer/node_modules/puppeteer-core/lib/esm/puppeteer/common/ElementHandle.js:33:0
      at /path/to.../node_modules/puppeteer/node_modules/puppeteer-core/lib/esm/puppeteer/common/util.js:32:0
      at /path/to.../node_modules/puppeteer/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:24:0
```

**Comment by dylan-conway** [comment]
Puppeteer is working in 0.6.6
