### ISSUE TITLE
"bun install" leads to missing dependencies in the node_modules folder

### ISSUE THREAD

**Issue by alimustafa-poder** [oven-sh/bun#2358]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Windows 11 WSL2

### What steps can reproduce the bug?

I have a project with this structure
|
|------backend (contains package.json)
|------frontend (contains package.json)
|------package.json
|------gitignore
|------and rest of configs

Steps to reproduce

- Download the attached zip folder (2.21 MB uncompressed)
- Install the dependencies in both bun and npm
- Check the size of node_modules for both bun and npm
- Try running scripts

At this moment, I am running  bun install in the root, backend, and frontend. I used npm install and the modules installed were 1.01GB and then I used bun install and the node_modules were 446MBs. I tried installing using "bun install --backend=copyfile ---force" command by Jarred on discord. But the size of node_modules stayed the same. I am getting errors like the one below when I run `bun run start` in my frontend folder:
```
TypeError: undefined is not an object (evaluating 'delete import.meta.require.cache[import.meta.require.resolve("./paths")]')
```
```
error: Cannot find package "vm" from "/home/blogProj/Bayaan-Blogging-App/frontend/node_modules/html-webpack-plugin/index.js"
```

And these errors when I run the script `bun run dev` in backend:
```
fork@node:child_process:685:18
run@/home/blogProj/Bayaan-Blogging-App/backend/node_modules/nodemon/lib/monitor/run.js:93:19
@/home/blogProj/Bayaan-Blogging-App/backend/node_modules/nodemon/lib/nodemon.js:170:18
@/home/blogProj/Bayaan-Blogging-App/backend/node_modules/nodemon/lib/config/index.js:57:14
promiseReactionJob@[native code]
[]
error: Not implemented
      at node:child_process:686:18
```

Initially, I was getting errors on modules not found, but after clean installing like 5 times (until now) I am getting a wide variety of errors. Some pertain to process.binding with these errors:
```
TypeError: process.binding is not supported in Bun. If this breaks a library you're using, please file an issue at https://bun.sh/issues and include a reproducible code sample.
at /Users/alex/Projects/Personal/canvas-node/node_modules/precinct/index.js:21:16
at /Users/alex/Projects/Personal/canvas-node/node_modules/dependency-tree/index.js:3:6
at /Users/alex/Projects/Personal/canvas-node/src/index.ts:5:0
```
When I run the script in the root of the project where I am running both the frontend and the backend concurrently using the `concurrently` package, this is what I get:
```
root@DESKTOP-11:/home/blogProj/Bayaan-Blogging-App# bun run dev
$ concurrently --kill-others-on-fail \"bun run client\" \"bun run server\"
[2] client" exited with code 2
--> Sending SIGTERM to other processes..
[3] "bun exited with code 2
--> Sending SIGTERM to other processes..
[0] "bun exited with code 2
--> Sending SIGTERM to other processes..
[5] server" exited with code 2
--> Sending SIGTERM to other processes..
[2] /bin/sh: 1: Syntax error: Unterminated quoted string
[3] /bin/sh: 1: Syntax error: Unterminated quoted string
[0] /bin/sh: 1: Syntax error: Unterminated quoted string
[5] /bin/sh: 1: Syntax error: Unterminated quoted string
[1] run exited with code 127
--> Sending SIGTERM to other processes..
[4] run exited with code 127
77 |     }
78 | }
79 | 
80 | function killPid(pid, signal) {
81 |     try {
82 |         process.kill(parseInt(pid, 10), signal);
            ^
TypeError: process.kill is not a function. (In 'process.kill(parseInt(pid, 10), signal)', 'process.kill' is undefined)
      at killPid (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:82:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:64:16
      at killAll (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:56:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:47:12
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:103:16
      at #maybeClose (node:child_process:1175:6)
      at #handleOnExit (node:child_process:949:4)
      at node:child_process:1099:10
77 |     }
78 | }
79 | 
80 | function killPid(pid, signal) {
81 |     try {
82 |         process.kill(parseInt(pid, 10), signal);
            ^
TypeError: process.kill is not a function. (In 'process.kill(parseInt(pid, 10), signal)', 'process.kill' is undefined)
      at killPid (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:82:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:64:16
      at killAll (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:56:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:47:12
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:103:16
      at #maybeClose (node:child_process:1175:6)
      at #handleOnExit (node:child_process:949:4)
      at node:child_process:1099:10
77 |     }
78 | }
79 | 
80 | function killPid(pid, signal) {
81 |     try {
82 |         process.kill(parseInt(pid, 10), signal);
            ^
TypeError: process.kill is not a function. (In 'process.kill(parseInt(pid, 10), signal)', 'process.kill' is undefined)
      at killPid (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:82:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:64:16
      at killAll (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:56:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:47:12
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:103:16
      at #maybeClose (node:child_process:1175:6)
      at #handleOnExit (node:child_process:949:4)
      at node:child_process:1099:10
77 |     }
78 | }
79 | 
80 | function killPid(pid, signal) {
81 |     try {
82 |         process.kill(parseInt(pid, 10), signal);
            ^
TypeError: process.kill is not a function. (In 'process.kill(parseInt(pid, 10), signal)', 'process.kill' is undefined)
      at killPid (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:82:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:64:16
      at killAll (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:56:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:47:12
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:103:16
      at #maybeClose (node:child_process:1175:6)
      at #handleOnExit (node:child_process:949:4)
      at node:child_process:1099:10
77 |     }
78 | }
79 | 
80 | function killPid(pid, signal) {
81 |     try {
82 |         process.kill(parseInt(pid, 10), signal);
            ^
TypeError: process.kill is not a function. (In 'process.kill(parseInt(pid, 10), signal)', 'process.kill' is undefined)
      at killPid (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:82:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:64:16
      at killAll (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:56:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:47:12
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:103:16
      at #maybeClose (node:child_process:1175:6)
      at #handleOnExit (node:child_process:949:4)
      at node:child_process:1099:10
77 |     }
78 | }
79 | 
80 | function killPid(pid, signal) {
81 |     try {
82 |         process.kill(parseInt(pid, 10), signal);
            ^
TypeError: process.kill is not a function. (In 'process.kill(parseInt(pid, 10), signal)', 'process.kill' is undefined)
      at killPid (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:82:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:64:16
      at killAll (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:56:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:47:12
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:103:16
      at #maybeClose (node:child_process:1175:6)
      at #handleOnExit (node:child_process:949:4)
      at node:child_process:1099:10
77 |     }
78 | }
79 | 
80 | function killPid(pid, signal) {
81 |     try {
82 |         process.kill(parseInt(pid, 10), signal);
            ^
TypeError: process.kill is not a function. (In 'process.kill(parseInt(pid, 10), signal)', 'process.kill' is undefined)
      at killPid (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:82:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:64:16
      at killAll (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:56:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:47:12
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:103:16
      at #maybeClose (node:child_process:1175:6)
      at #handleOnExit (node:child_process:949:4)
      at node:child_process:1099:10
77 |     }
78 | }
79 | 
80 | function killPid(pid, signal) {
81 |     try {
82 |         process.kill(parseInt(pid, 10), signal);
            ^
TypeError: process.kill is not a function. (In 'process.kill(parseInt(pid, 10), signal)', 'process.kill' is undefined)
      at killPid (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:82:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:64:16
      at killAll (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:56:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:47:12
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:103:16
      at #maybeClose (node:child_process:1175:6)
      at #handleOnExit (node:child_process:949:4)
      at node:child_process:1099:10
77 |     }
78 | }
79 | 
80 | function killPid(pid, signal) {
81 |     try {
82 |         process.kill(parseInt(pid, 10), signal);
            ^
TypeError: process.kill is not a function. (In 'process.kill(parseInt(pid, 10), signal)', 'process.kill' is undefined)
      at killPid (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:82:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:64:16
      at killAll (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:56:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:47:12
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:103:16
      at #maybeClose (node:child_process:1175:6)
      at #handleOnExit (node:child_process:949:4)
      at node:child_process:1099:10
77 |     }
78 | }
79 | 
80 | function killPid(pid, signal) {
81 |     try {
82 |         process.kill(parseInt(pid, 10), signal);
            ^
TypeError: process.kill is not a function. (In 'process.kill(parseInt(pid, 10), signal)', 'process.kill' is undefined)
      at killPid (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:82:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:64:16
      at killAll (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:56:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:47:12
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:103:16
      at #maybeClose (node:child_process:1175:6)
      at #handleOnExit (node:child_process:949:4)
      at node:child_process:1099:10
77 |     }
78 | }
79 | 
80 | function killPid(pid, signal) {
81 |     try {
82 |         process.kill(parseInt(pid, 10), signal);
            ^
TypeError: process.kill is not a function. (In 'process.kill(parseInt(pid, 10), signal)', 'process.kill' is undefined)
      at killPid (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:82:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:64:16
      at killAll (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:56:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:47:12
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:103:16
      at #maybeClose (node:child_process:1175:6)
      at #handleOnExit (node:child_process:949:4)
      at node:child_process:1099:10
77 |     }
78 | }
79 | 
80 | function killPid(pid, signal) {
81 |     try {
82 |         process.kill(parseInt(pid, 10), signal);
            ^
TypeError: process.kill is not a function. (In 'process.kill(parseInt(pid, 10), signal)', 'process.kill' is undefined)
      at killPid (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:82:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:64:16
      at killAll (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:56:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:47:12
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:103:16
      at #maybeClose (node:child_process:1175:6)
      at #handleOnExit (node:child_process:949:4)
      at node:child_process:1099:10
77 |     }
78 | }
79 | 
80 | function killPid(pid, signal) {
81 |     try {
82 |         process.kill(parseInt(pid, 10), signal);
            ^
TypeError: process.kill is not a function. (In 'process.kill(parseInt(pid, 10), signal)', 'process.kill' is undefined)
      at killPid (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:82:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:64:16
      at killAll (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:56:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:47:12
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:103:16
      at #maybeClose (node:child_process:1175:6)
      at #handleOnExit (node:child_process:949:4)
      at node:child_process:1099:10
77 |     }
78 | }
79 | 
80 | function killPid(pid, signal) {
81 |     try {
82 |         process.kill(parseInt(pid, 10), signal);
            ^
TypeError: process.kill is not a function. (In 'process.kill(parseInt(pid, 10), signal)', 'process.kill' is undefined)
      at killPid (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:82:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:64:16
      at killAll (/home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:56:8)
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:47:12
      at /home/blogProj/Bayaan-Blogging-App/node_modules/tree-kill/index.js:103:16
      at #maybeClose (node:child_process:1175:6)
      at #handleOnExit (node:child_process:949:4)
      at node:child_process:1099:10
[1] /bin/sh: 1: run: not found
[4] /bin/sh: 1: run: not found
error: script "dev" exited with code 1 (SIGHUP)
```
**PS: The main issue at hand is that I am getting module not found errors and the discrepancy in the size of node_modules while installing with bun.**

**The size of the folder attached in 2.21MB (uncompressed) and it is expected to be 1.09 GB when all the dependencies in all of the folders are installed.**

[Bayaan-Blogging-App.zip](https://github.com/oven-sh/bun/files/10935017/Bayaan-Blogging-App.zip)

### What is the expected behavior?

The expected behavior is that the node_modules would be the same size in bun as it is in npm. The node_modules folder in bun is expected to be 1.09 GBs with all the dependencies installing successfully.

**Comment by Jarred-Sumner** [comment]
The specific errors here are caused by Node.js compatibility bugs in Bun's runtime, not node_modules-related issues
-  #401 
- `import.meta.require.cache`
- fork

Can you try running in Node and see if that produces errors? If so, then that is the answer to whether this is a bug in bun install (yes) or Node.js compatibility issues in Bun's runtime (no)

**Comment by alimustafa-poder** [comment]
I tried running in node and there are no errors.

Edit: I did `npm install` and it installed all the dependencies (456 MBs), then I did bun run and the application was running as expected. In contrast, I did `bun install` and it installed all the dependencies (446MBs) there was no error. Then I did bun run and the application worked as expected. (For the previous tests, I had to navigate to the individual folder i.e., `cd backend->bun run dev` and `cd frontend->bun run start`). The environment I was using for the previous tests was WSL2. The only error I get now is when I run `bun run` in the root of the folder and it is because of using the package `concurrently` I think. The error I get is this:
```
$ concurrently --kill-others-on-fail \"bun run client\" \"bun run server\" 
[0] /bin/sh: 1: Syntax error: Unterminated quoted string
[2] /bin/sh: 1: Syntax error: Unterminated quoted string
[3] /bin/sh: 1: Syntax error: Unterminated quoted string
[5] /bin/sh: 1: Syntax error: Unterminated quoted string
[5] server" exited with code 2
--> Sending SIGTERM to other processes..
[3] "bun exited with code 2
--> Sending SIGTERM to other processes..
[2] client" exited with code 2
--> Sending SIGTERM to other processes..
[0] "bun exited with code 2
--> Sending SIGTERM to other processes..
[1] /bin/sh: 1: run: not found
[4] /bin/sh: 1: run: not found
[4] run exited with code 127
--> Sending SIGTERM to other processes..
[1] run exited with code 127
error: script "dev" exited with code 1 (SIGHUP)
```
I am no longer getting an error regarding the vm module or any other missing module error in `bun run`.

**Comment by alimustafa-poder** [comment]
I am closing this becuase this was misunderstanding on my part. The bun install works perfectly and there are no missing dependencies.
