### ISSUE TITLE
process.binding is not supported in Bun -> error when running dagger.io client

### ISSUE THREAD

**Issue by Edregol** [oven-sh/bun#2372]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Debian GNU/Linux 11 (bullseye) in Docker Desktop 4.17.0 (99724) on Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

`package.json` :
```json
{
    "name": "app",
    "version": "0.0.1",
    "type": "module",
    "devDependencies": {
        "@dagger.io/dagger": "^0.4.0",
    },
}
```

`build.mts` :
```typescript
import Client, { connect } from "@dagger.io/dagger";

connect(async (client: Client) => {
  let nodeCache = client.cacheVolume("node");
});
```

run `bun run build.mts`

### What is the expected behavior?

I'd expect this to run without errors.

### What do you see instead?

bun throws an error:
```
 6 | let writev = fs.writev
 7 | /* istanbul ignore next */
 8 | if (!writev) {
 9 |   // This entire block can be removed if support for earlier than Node.js
10 |   // 12.9.0 is not needed.
11 |   const binding = process.binding('fs')
                      ^
TypeError: process.binding is not supported in Bun. If this breaks a library you're using, please file an issue at https://bun.sh/issues and include a reproducible code sample.
      at /workspaces/frontend/node_modules/fs-minipass/index.js:11:18
      at /workspaces/frontend/node_modules/tar/lib/create.js:7:6
      at /workspaces/frontend/node_modules/tar/index.js:4:20
      at /workspaces/frontend/node_modules/@dagger.io/dagger/dist/provisioning/bin.js:27:0
```

### Additional information

As you might expect, I've reported this due to the prompt I've got. Love bun to bits. Hope this helps to improve it. Let me know if you need more information.

**Comment by Jarred-Sumner** [comment]
`writev` was implemented in Bun v0.6.xx
