### ISSUE TITLE
nunjucks errors out in bun

### ISSUE THREAD

**Issue by SNSTRUTHERS** [oven-sh/bun#2514]
### What version of Bun is running?

0.5.8

### What platform is your computer?

Linux 6.1.11-76060111-generic x86_64 x86_64 - Pop_OS

### What steps can reproduce the bug?

1. create and go to a new empty directory
2. execute the following commands; terminal output should look similar to what is shown below:
```sh
$ bun install nunjucks
bun add v0.5.8 (1a25af5e)

 installed nunjucks@3.2.3 with binaries:
  - nunjucks-precompile


 5 packages installed [190.00ms]
$ echo "import nunjucks from 'nunjucks'; console.dir(new nunjucks.Environment(new nunjucks.FileSystemLoader('templates')));" > test.js
$ echo '{ "type": "module" }' > package.json
$ bun test.js
```

### What is the expected behavior?

When executing `test.js` with `node`, the following output is given:
```
Environment {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  opts: {
    dev: false,
    autoescape: true,
    throwOnUndefined: false,
    trimBlocks: false,
    lstripBlocks: false
  },
  loaders: [
    FileSystemLoader {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      pathsToNames: {},
      noCache: false,
      searchPaths: [Array],
      cache: {},
      [Symbol(kCapture)]: false
    }
  ],
  globals: {
    range: [Function: range],
    cycler: [Function: cycler],
    joiner: [Function: joiner]
  },
  filters: {
    abs: [Function: abs],
    batch: [Function: batch],
    capitalize: [Function: capitalize],
    center: [Function: center],
    default: [Function: default_],
    dictsort: [Function: dictsort],
    dump: [Function: dump],
    escape: [Function: escape],
    safe: [Function: safe],
    first: [Function: first],
    forceescape: [Function: forceescape],
    groupby: [Function: groupby],
    indent: [Function: indent],
    join: [Function: join],
    last: [Function: last],
    length: [Function: lengthFilter],
    list: [Function: list],
    lower: [Function: lower],
    nl2br: [Function: nl2br],
    random: [Function: random],
    reject: [Function: filter],
    rejectattr: [Function: rejectattr],
    select: [Function: filter],
    selectattr: [Function: selectattr],
    replace: [Function: replace],
    reverse: [Function: reverse],
    round: [Function: round],
    slice: [Function: slice],
    sum: [Function: sum],
    sort: [Function: macro],
    string: [Function: string],
    striptags: [Function: striptags],
    title: [Function: title],
    trim: [Function: trim],
    truncate: [Function: truncate],
    upper: [Function: upper],
    urlencode: [Function: urlencode],
    urlize: [Function: urlize],
    wordcount: [Function: wordcount],
    float: [Function: float],
    int: [Function: macro],
    d: [Function: default_],
    e: [Function: escape]
  },
  tests: {
    callable: [Function: callable],
    defined: [Function: defined],
    divisibleby: [Function: divisibleby],
    escaped: [Function: escaped],
    equalto: [Function: equalto],
    eq: [Function: equalto],
    sameas: [Function: equalto],
    even: [Function: even],
    falsy: [Function: falsy],
    ge: [Function: ge],
    greaterthan: [Function: greaterthan],
    gt: [Function: greaterthan],
    le: [Function: le],
    lessthan: [Function: lessthan],
    lt: [Function: lessthan],
    lower: [Function: lower],
    ne: [Function: ne],
    null: [Function: nullTest],
    number: [Function: number],
    odd: [Function: odd],
    string: [Function: string],
    truthy: [Function: truthy],
    undefined: [Function: undefinedTest],
    upper: [Function: upper],
    iterable: [Function: iterable],
    mapping: [Function: mapping]
  },
  asyncFilters: [],
  extensions: {},
  extensionsList: [],
  [Symbol(kCapture)]: false
}
```

### What do you see instead?

The following error:
```
93 | 
94 |     var _this;
95 | 
96 |     _this = _EventEmitter.call(this) || this; // Unfortunately necessary for backwards compatibility
97 | 
98 |     (_this2 = _this).init.apply(_this2, arguments);
        ^
TypeError: undefined is not an object (evaluating '(_this2 = _this).init.apply')
      at EmitterObj (~/Documents/bun-server/node_modules/nunjucks/src/object.js:98:4)
      at Loader (~/Documents/bun-server/node_modules/nunjucks/src/loader.js:16:11)
      at new FileSystemLoader (~/Documents/bun-server/node_modules/nunjucks/src/node-loaders.js:25:12)
      at /~/Documents/bun-server/test.js:3:25
```

### Additional information

This appears to be an issue with how Bun interprets code which has been transpiled via Babel, as the [line where the issue appears takes place in the GitHub repo](https://github.com/mozilla/nunjucks/blob/fd500902d7c88672470c87170796de52fc0f791a/nunjucks/src/object.js#L67) uses modern `class` syntax, but a `cat` of the file where the error takes place on the local machine has telltale signs of Babel transpilation:
```js
function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } }

function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); return Constructor; }

function _inheritsLoose(subClass, superClass) { subClass.prototype = Object.create(superClass.prototype); subClass.prototype.constructor = subClass; _setPrototypeOf(subClass, superClass); }

function _setPrototypeOf(o, p) { _setPrototypeOf = Object.setPrototypeOf || function _setPrototypeOf(o, p) { o.__proto__ = p; return o; }; return _setPrototypeOf(o, p); }

var EventEmitter = require('events');

var lib = require('./lib');

// [...]
```

This makes sense, as this is a JavaScript library intended for both servers & browsers which was first being developed well over a decade ago (i.e. when this syntax wasn't as commonly available on most browsers).

**Comment by Electroid** [comment]
This issue has been fixed, tested using Bun v1.0.7.

```
❯ bun test.js
{
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  [Symbol(kCapture)]: false,
  opts: {
    dev: false,
    autoescape: true,
    throwOnUndefined: false,
    trimBlocks: false,
    lstripBlocks: false
  },
  ... omitted ...
}
```
