### ISSUE TITLE
escapeHTML causes crash in docker container

### ISSUE THREAD

**Issue by etinquis** [oven-sh/bun#2515]
### What version of Bun is running?

oven/bun:0.5.8 and oven/bun:0.5.3

### What platform is your computer?

Windows Host (Microsoft Windows NT 10.0.19045.0 x64), Linux Container (Linux 5.10.16.3-microsoft-standard-WSL2 x86_64 unknown)

### What steps can reproduce the bug?

```pwsh
docker --context linux run --rm -it -v "$PWD`:/home/bun/app" oven/bun:0.5.8 bun run server.ts
```

server.ts
```typescript
import { escapeHTML } from 'bun';

console.trace('link', escapeHTML("<a href='google.com'>a</a>")); // ok
console.trace('double escape', escapeHTML(escapeHTML("<a href='google.com'>a</a>"))); // crash
console.trace('script', escapeHTML("<script type='text/javascript'>console.log('aaa');</script>")); // crash

console.trace('done');
```

### What is the expected behavior?

Script runs to completion

### What do you see instead?

Output:
```
link &lt;a href=&#x27;google.com&#x27;&gt;a&lt;/a&gt;
      at /home/bun/app/server.ts:3:0
```
then the container exits.

**Comment by Jarred-Sumner** [comment]
@etinquis we have fixed a bug in escapeHTML in the canary build of bun

may be worth trying the canary build

**Comment by etinquis** [comment]
Yup, no crash on canary, thanks!
```pwsh
> docker --context linux run --rm -it -v "$PWD`:/home/bun/app" oven/bun:canary bun run server.ts
link &lt;a href=&#x27;google.com&#x27;&gt;a&lt;/a&gt;
      at /home/bun/app/server.ts:3:0
double escape &amp;lt;a href=&amp;#x27;google.com&amp;#x27;&amp;gt;a&amp;lt;/a&amp;gt;
      at /home/bun/app/server.ts:4:0
script &lt;script type=&#x27;text/javascript&#x27;&gt;console.log(&#x27;aaa&#x27;);&lt;/script&gt;
      at /home/bun/app/server.ts:5:0
done
      at /home/bun/app/server.ts:7:0
```
