### ISSUE TITLE
Undefined error using readline AsyncIterator

### ISSUE THREAD

**Issue by controversial** [oven-sh/bun#2597]
### What version of Bun is running?

0.6.0

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

Run the following script (replace `test.txt` with a real path)

```js
import readline from 'readline';
import { createReadStream } from 'fs';

const path = new URL('test.txt', import.meta.url);
const stream = createReadStream(path);
const rl = readline.createInterface({ input: stream });

console.log(await rl[Symbol.asyncIterator]().next());
```

`node test.js`

### What is the expected behavior?

```
❯ node test.js
{ value: 'hello world', done: false }
```

### What do you see instead?

```
❯ bun test.js
[0.05ms] ".env"
3 | 
4 | const path = new URL('test.txt', import.meta.url);
5 | const stream = createReadStream(path);
6 | const rl = readline.createInterface({ input: stream });
7 | 
8 | console.log(await rl[Symbol.asyncIterator]().next());
                      ^
TypeError: undefined is not an object (evaluating 'rl[Symbol.asyncIterator]().next')
      at /Users/luke/Developer/marriagepact/dataset/test.js:8:18
```

### Additional information

A similar error occurs using the more “standard” async iterator syntax as follows:
```js
for await (const line of rl) {
  console.log(line);
}
```
Here, Bun’s error is
```
8 | for await (const line of rl) {
                     ^
TypeError: undefined is not an object (evaluating 'line of rl')
      at /Users/luke/Developer/marriagepact/dataset/test.js:8:17
```

**Comment by controversial** [comment]
Oops, closing as a duplicate of #2535
