### ISSUE TITLE
Implement `node:diagnostics_channel`

### ISSUE THREAD

**Issue by itsezc** [oven-sh/bun#2688]
### What version of Bun is running?

0.6.0

### What platform is your computer?

Linux 5.10.102.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Install and setup a CF worker: https://developers.cloudflare.com/workers/wrangler/commands/#init and ensure you setup a vitest test.

Then run `bun test`

### What is the expected behavior?

The test to be run successfully, similar to the node environment.

### What do you see instead?

```sh
bun test v0.6.0 (b5b4356d)

index.test.ts:
15772 |     var { parserStates, opcodes, states, emptyBuffer } = require_constants4();
15773 |     var { kReadyState, kSentClose, kResponse, kReceivedClose } = require_symbols4();
15774 |     var { isValidStatusCode, failWebsocketConnection, websocketMessageReceived } = require_util5();
15775 |     var { WebsocketFrameSend } = require_frame();
15776 |     var channels = {};
15777 |     channels.ping = diagnosticsChannel.channel("undici:websocket:ping");
                        ^
TODO: node:diagnostics_channel is not implemented yet in Bun.
```

**Comment by xhyrom** [comment]
Look into https://bun.sh/docs/runtime/nodejs-apis

**Comment by ImLunaHey** [comment]
Just hit this too.

```
➜  ticket-genie git:(main) ✗ bun run dist/main.cjs
[0.09ms] ".env"
 9 | 
10 | class NotImplementedError extends Error {
11 |   code;
12 |   constructor(feature, issue) {
13 | 
14 |     super(feature + " is not yet implemented in Bun." + (issue ? " Track the status & thumbs up the issue: https://github.com/oven-sh/bun/issues/" + issue : ""));
       ^
NotImplementedError: node:diagnostics_channel is not yet implemented in Bun. Track the status & thumbs up the issue: https://github.com/oven-sh/bun/issues/2688
 code: "ERR_NOT_IMPLEMENTED"

      at node:diagnostics_channel:21:2
      at node_modules/undici/lib/websocket/connection.js (/Users/xo/code/ImLunaHey/ticket-genie/dist/main.cjs:54939:20)
      at __require2 (/Users/xo/code/ImLunaHey/ticket-genie/dist/main.cjs:35:9)
      at node_modules/undici/lib/websocket/websocket.js (/Users/xo/code/ImLunaHey/ticket-genie/dist/main.cjs:55370:43)
      at __require2 (/Users/xo/code/ImLunaHey/ticket-genie/dist/main.cjs:35:9)
      at node_modules/undici/index.js (/Users/xo/code/ImLunaHey/ticket-genie/dist/main.cjs:55868:28)
      at __require2 (/Users/xo/code/ImLunaHey/ticket-genie/dist/main.cjs:35:9)
      at node_modules/@discordjs/rest/dist/index.js (/Users/xo/code/ImLunaHey/ticket-genie/dist/main.cjs:60384:25)
      at __require2 (/Users/xo/code/ImLunaHey/ticket-genie/dist/main.cjs:35:9)
      at node_modules/discord.js/src/client/BaseClient.js (/Users/xo/code/ImLunaHey/ticket-genie/dist/main.cjs:71640:19)
      at __require2 (/Users/xo/code/ImLunaHey/ticket-genie/dist/main.cjs:35:9)
      at node_modules/discord.js/src/index.js (/Users/xo/code/ImLunaHey/ticket-genie/dist/main.cjs:101125:26)
      at __require2 (/Users/xo/code/ImLunaHey/ticket-genie/dist/main.cjs:35:9)
      at src/client.ts (/Users/xo/code/ImLunaHey/ticket-genie/dist/main.cjs:107218:30)
      at __init (/Users/xo/code/ImLunaHey/ticket-genie/dist/main.cjs:32:16)
      at /Users/xo/code/ImLunaHey/ticket-genie/dist/main.cjs:109950:0
      at (eval) (/Users/xo/code/ImLunaHey/ticket-genie/dist/main.cjs:110277:0)

﻿```

**Comment by Illyism** [comment]
Unblocks:
- undici: https://github.com/oven-sh/bun/issues/1987
- wrangler

Bumping @TiranexDev (@Jarred-Sumner tweeted we should ask for updates)

**Comment by TiranexDev** [comment]
> Bumping @TiranexDev

Sorry but I don't really work with this undici, you have to wait until someone else from core team responds

**Comment by krvajal** [comment]
This will also allow support for dd-trace-js

**Comment by Electroid** [comment]
You can test this right now using `bun upgrade --canary`. This will be release in Bun v0.7.2.

**Comment by krvajal** [comment]
I just tried, still getting a segmentation fault. Not sure if related to this or something else. Can I generate core dump somehow?
```
[1]    22338 segmentation fault  bun run ./src/index.ts

```

**Comment by TiranexDev** [comment]
> I just tried, still getting a segmentation fault. Not sure if related to this or something else. Can I generate core dump somehow?
> ```
> [1]    22338 segmentation fault  bun run ./src/index.ts
> 
> ```

What is the content of index.ts?
