### ISSUE TITLE
node:http.ServerResponse.assignSocket is not implemented

### ISSUE THREAD

**Issue by pasha-vuiko** [oven-sh/bun#2690]
### What version of Bun is running?

0.5.9

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

node:http.ServerResponse.assignSocket is not implemented. 

I was trying to write adapter for Fastify for native Bun http server. I was trying to implement it with fastify.inject() like this:

```
import {fastify} from "fastify";

const fastifyServer = fastify();

fastifyServer.get("/", async (request, reply) => {
  return {
    hello: "world",
  };
});

await fastifyServer.ready();

Bun.serve({
  port: 3000,
  async fetch(request) {
    let response = await fastifyServer.inject({
      method: request.method,
      url: request.url,
      payload: request.body,
      headers: request.headers,
    });

    return new Response(response.body, {
      headers: response.headers,
      status: response.statusCode,
      statusText: response.statusMessage,
    });
 
  },
});

```

So the problem is that fastify.inject() uses http.ServerResponse.assignSocket and bunch of other unimplemented Node.js http server stuff. I think it would be nice to have the ability to implement adapter like this, as possibly we can get ability to use Fastify with native Bun's http server

### What is the expected behavior?

node:http.ServerResponse.assignSocket should be implemented

**Comment by Electroid** [comment]
Newest issue: #6667 

```
622 | }
623 | var OriginalWriteHeadFn, OriginalImplicitHeadFn;
624 | 
625 | class ServerResponse extends Writable {
626 | 
627 |   constructor(c) {
                             ^
TypeError: Cannot call a class constructor without |new|
      at ServerResponse (node:http:627:26)
      at new Response (example/node_modules/light-my-request/lib/response.js:10:2)
```

**Comment by fdaciuk** [comment]
@Electroid I'm using Bun in production, and trying to test my API with Fastify, but Bun is returning a new error now:

```
177 |   response._lightMyRequest.headers = Object.assign({}, response.getHeaders())
178 |
179 |   // Add raw headers
180 |   ;['Date', 'Connection', 'Transfer-Encoding'].forEach((name) => {
181 |     const regex = new RegExp('\\r\\n' + name + ': ([^\\r]*)\\r\\n')
182 |     const field = response._header.match(regex)
                        ^
TypeError: undefined is not an object (evaluating 'response._header.match')
      at /code/fastify-inject/node_modules/light-my-request/lib/response.js:182:19
      at forEach (:1:21)
      at copyHeaders (/code/fastify-inject/node_modules/light-my-request/lib/response.js:180:4)
      at /code/fastify-inject/node_modules/light-my-request/lib/response.js:65:3
      at /code/fastify-inject/node_modules/fastify/lib/error-handler.js:42:9
      at fallbackErrorHandler (/code/fastify-inject/node_modules/fastify/lib/error-handler.js:127:3)
      at handleError (/code/fastify-inject/node_modules/fastify/lib/error-handler.js:34:5)
      at onErrorHook (/code/fastify-inject/node_modules/fastify/lib/reply.js:839:5)
      at /code/fastify-inject/node_modules/fastify/lib/reply.js:157:5
      at preValidationCallback (/code/fastify-inject/node_modules/fastify/lib/handleRequest.js:87:5)

Bun v1.1.7 (Linux x64)
```

The code:

```js
import Fastify from "fastify"

const app = Fastify()

app.get("/hello", (_req, reply) => {
  reply.send("Hello World!")
})

async function test() {
  const result = await app.inject({
    method: "GET",
    url: "/hello"
  })

  console.log(result.payload)
}

test()
```

Node.js just works.

**Comment by yazaldefilimone** [comment]
> I can't reproduce the error.
> 
> Bun version: 1.3.1+89fa0f343 Platform: Linux 6.17.5-061705-generic x86_64 x86_64

same here...
