### ISSUE TITLE
Flagging Node Dependencies with `--external` does not work

### ISSUE THREAD

**Issue by TotalTechGeek** [oven-sh/bun#2701]
### What version of Bun is running?

v0.6.0

### What platform is your computer?

Darwin 21.4.0 arm64 arm

## test.js
```javascript
import { timingSafeEqual } from 'crypto'

console.log(
    timingSafeEqual(
        Buffer.from('abc'), 
        Buffer.from('abc')
    )
)
```

## cmd 
```
bun build test.js --outfile test.out.js --external node:crypto --external crypto
```

I am trying it with both just in case.

### What is the expected behavior?

That crypto is omitted from the bundling. 

### What do you see instead?

The following shows up in the output file: 
```javascript
/* node:crypto */
var require_crypto = __commonJS((exports, module) => {
  var dw = Object.create;
  var Ya = Object.defineProperty;
  var cw = Object.getOwnPropertyDescriptor;
  var pw = Object.getOwnPropertyNames;
  var vw = Object.getPrototypeOf;
  var bw = Object.prototype.hasOwnProperty;
  var S0 = (t, e) => () => (t && (e = t(t = 0)), e);
  var T = (t, e) => () => (e || t((e = { exports: {} }).exports, e), e.exports);
  var mw = (t, e) => {
    for (var r in e)
      Ya(t, r, { get: e[r], enumerable: true });
  };
  ```
  
  Note that there appears to be a null byte present in the comment emitted: 
  
  
![image](https://user-images.githubusercontent.com/2261916/233232036-1f136edb-392f-4dc5-8d3c-879d216289e8.png)

### Additional information

Yes, I know that I did not specify `--platform=node` here. 

But the injections that Bun does for the browser seemingly cannot be suppressed by `--export`.

@paperdave May have aleady mentioned this bug.

**Comment by paperclover** [comment]
yeah this is known but i dont think we have an issue filed for it.

i have a test to make sure the null byte doesn't show up but we need to be able to mark this external with --external

footnote: embedding the crypto polyfill is intentional, null byte and external stuff is a bug.

**Comment by paperclover** [comment]
null byte (and importing these at all) will be tested in bundler test `browser/NodePolyfills`

external bug will be tested in bundler test `browser/NodePolyfillExternal`

**Comment by Jarred-Sumner** [comment]
null byte issue is fixed

**Comment by mattfysh** [comment]
A workaround is to run a multi-stage build, eg.

```
echo "import 'crypto-js'" > start.js
bun build --outdir stage1 --target browser --external crypto-js start.js
bun build --outdir stage2 --target node stage1/start.js
```

Note: you need to use `--target node` and not `--target bun` for the second stage, or else the `node:*` prefixes will be stripped from specifiers

It's a good idea to understand why people want to use `--target browser` but exclude node builtins. In my case I am bundling for cloudflare, which has both browser and nodejs APIs available, and my goal is to:

1. Use the `browser` field of package.json as the preferred entry point, to eliminate or minimize nodejs api usage (e.g. `debug` package). `--conditions browser` does not use the package.json `browser` field

2. Exclude node builtins, as there is a decent level of nodejs compatibility in the cloudflare environment

**Comment by mattfysh** [comment]
this is how i'm currently bundling for cloudflare: https://gist.github.com/mattfysh/897c3c83e06353bbf542122cec38eaa6

**Comment by RiskyMH** [comment]
It now throws this error which still is missing the point on `--external`:

```js
1 | import { timingSafeEqual } from 'crypto'
             ^
error: Browser polyfill for module "node:crypto" doesn't have a matching export named "timingSafeEqual"
    at ~/test.ts:1:10

1 | import { timingSafeEqual } from 'crypto'
             ^
note: Bun's bundler defaults to browser builds instead of node or bun builds. If you want to use node or bun builds, you can set the target to "node" or "bun" in the transpiler options.
   at ~/test.ts:1:10
```
