### ISSUE TITLE
Accessing readonly constructor parameters inside constructor while also extending a class gives error

### ISSUE THREAD

**Issue by vitoke** [oven-sh/bun#2744]
### What version of Bun is running?

0.6.0

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

Create a file with the following code:

```ts
class Parent {}

class Child extends Parent {
  calc: number;

  constructor(readonly value: number) {
    super();
    this.calc = value / 2;
  }
}

const a = new Child(6);
console.log(a.calc);
```

And run it with `bun`

### What is the expected behavior?

Since this is valid TypeScript, the expected behavior is a console output of `3`

### What do you see instead?

I get the following output:

```console
 5 | class Parent {}
 6 | 
 7 | class Child extends Parent {
 8 |   calc: number;
 9 | 
10 |   constructor(readonly value: number) {
                           ^
ReferenceError: 'super()' must be called in derived constructor before accessing |this| or returning non-object.
      at new Child (./src/index.ts:10:23)
      at ./src/index.ts:16:10
```

### Additional information

When not extending another class, the code works fine. Also, when making the `value` property not `readonly`, the code works fine.

**Comment by Jarred-Sumner** [comment]
Looks like a minification bug. This happens because we default to enabling --minify-syntax in the runtime in v0.6. You can switch to 0.5.9 and it should work there.

```ts
❯ bun-debug build /tmp/abc.ts
// /tmp/abc.ts
class Parent {
}

class Child extends Parent {
  value;
  calc;
  constructor(value) {
    super();
    this.value = value;
    this.calc = value / 2;
  }
}
export {
  Child
};
```

```ts
❯ bun-debug build --minify-syntax /tmp/abc.ts
// /tmp/abc.ts
class Parent {
}

class Child extends Parent {
  value;
  calc;
  constructor(value) {
    this.value = value;
    super(), this.calc = value / 2;
  }
}
export {
  Child
};
```

0.5.9:
```
❯ ~/.bun/bin/bun build --platform=bun /tmp/abc.ts
class Parent {
}

export class Child extends Parent {
  value;
  calc;
  constructor(value) {
    super();
    this.value = value;
    this.calc = value / 2;
  }
}
```
