### ISSUE TITLE
Cannot declare a var variable that shadows a let/const/class variable: 'cb'. while parsing module

### ISSUE THREAD

**Issue by FridayCandour** [oven-sh/bun#2862]
### What version of Bun is running?

canary 0.6.0

### What platform is your computer?

linux deb

### What steps can reproduce the bug?

this error came as a result of trying bookshelf orm on bun.

steps to reproduce

bun install knex bookshelf elysia

import knex from "knex";
import bookshelf from "bookshelf";

console.log(bookshelf, knex); // functions

knex({
  client: "sqlite3",
  connection: {
    host: "127.0.0.1",
    charset: "utf8",
  },
});

### What is the expected behavior?

Knex is a purpolar sql query builder for js, we need it to work in bun.

knex should succeccfully initialise the db amd be able to run transactions on bun.

### What do you see instead?

// error

```
[Function] [Function]
Knex: run
$ npm install sqlite3 --save
Cannot declare a var variable that shadows a let/const/class variable: 'cb'. while parsing module "/project/node_modules/sqlite3/lib/sqlite3.js"
loadCJS2ESM@[native code]
requireESM@[native code]
internalRequire@[native code]
require@[native code]
initializeDriver@/project/node_modules/knex/lib/client.js:136:35
Client@/project/node_modules/knex/lib/client.js:53:34
Client_SQLite3@/project/node_modules/knex/lib/dialects/sqlite3/index.js:22:12
knex@/project/node_modules/knex/lib/knex-builder/Knex.js:6:100
module code@/project/DB/models.js:173:5
evaluate@[native code]
moduleEvaluation@[native code]
moduleEvaluation@[native code]
@[native code]
asyncFunctionResume@[native code]
asyncModuleEvaluation@[native code]
@[native code]
189 |     try {
190 |       this.driver = this._driver();
191 |     } catch (e) {
192 |       const message = `Knex: run\n$ npm install ${this.driverName} --save`;
193 |       this.logger.error(`${message}\n${e.message}\n${e.stack}`);
194 |       throw new Error(`${message}\n${e.message}`);
                ^
error: Knex: run
$ npm install sqlite3 --save
Cannot declare a var variable that shadows a let/const/class variable: 'cb'. while parsing module "/project/node_modules/sqlite3/lib/sqlite3.js"
      at initializeDriver (/project/node_modules/knex/lib/client.js:194:12)
      at new Client (/project/node_modules/knex/lib/client.js:75:6)
      at new Client_SQLite3 (/project/node_modules/knex/lib/dialects/sqlite3/index.js:22:4)
      at /project/node_modules/knex/lib/knex-builder/Knex.js:16:27
      at /project/DB/models.js:9:0
189 |     try {
190 |       this.driver = this._driver();
191 |     } catch (e) {
192 |       const message = `Knex: run\n$ npm install ${this.driverName} --save`;
193 |       this.logger.error(`${message}\n${e.message}\n${e.stack}`);
194 |       throw new Error(`${message}\n${e.message}`);
                ^
error: Knex: run
$ npm install sqlite3 --save
Cannot declare a var variable that shadows a let/const/class variable: 'cb'. while parsing module "/project/node_modules/sqlite3/lib/sqlite3.js"
      at initializeDriver (/project/node_modules/knex/lib/client.js:194:12)
      at new Client (/project/node_modules/knex/lib/client.js:75:6)
      at new Client_SQLite3 (/project/node_modules/knex/lib/dialects/sqlite3/index.js:22:4)
      at /project/node_modules/knex/lib/knex-builder/Knex.js:16:27
      at /project/DB/models.js:9:0



```

**Comment by FridayCandour** [comment]
further debugging

``` [Function] [Function]
Knex: run
$ npm install sqlite3 --save
symbol 'napi_register_module_v1' not found in native module. Is this a Node API (napi) module?
dlopen@[native code]
internalRequire@[native code]
require@[native code]
@/project/node_modules/sqlite3/lib/sqlite3-binding.js:9:38
h@bun:wrap:1:8839
internalRequire@[native code]
require@[native code]
@/project/node_modules/sqlite3/lib/sqlite3.js:25:38
h@bun:wrap:1:8839
internalRequire@[native code]
require@[native code]
initializeDriver@/project/node_modules/knex/lib/client.js:136:35
Client@/project/node_modules/knex/lib/client.js:53:34
Client_SQLite3@/project/node_modules/knex/lib/dialects/sqlite3/index.js:22:12
knex@/project/node_modules/knex/lib/knex-builder/Knex.js:6:100
module code@/project/DB/models.js:173:5
evaluate@[native code]
moduleEvaluation@[native code]
moduleEvaluation@[native code]
@[native code]
asyncFunctionResume@[native code]
asyncModuleEvaluation@[native code]
[Function] [Function]
Knex: run
$ npm install sqlite3 --save
symbol 'napi_register_module_v1' not found in native module. Is this a Node API (napi) module?
dlopen@[native code]
internalRequire@[native code]
require@[native code]
@/project/node_modules/sqlite3/lib/sqlite3-binding.js:9:38
h@bun:wrap:1:8839
internalRequire@[native code]
require@[native code]
@/project/node_modules/sqlite3/lib/sqlite3.js:25:38
h@bun:wrap:1:8839
internalRequire@[native code]
require@[native code]
initializeDriver@/project/node_modules/knex/lib/client.js:136:35
Client@/project/node_modules/knex/lib/client.js:53:34
Client_SQLite3@/project/node_modules/knex/lib/dialects/sqlite3/index.js:22:12
knex@/project/node_modules/knex/lib/knex-builder/Knex.js:6:100
module code@/project/DB/models.js:173:5
evaluate@[native code]
moduleEvaluation@[native code]
moduleEvaluation@[native code]
@[native code]
asyncFunctionResume@[native code]
asyncModuleEvaluation@[native code]
@[native code]
asyncFunctionResume@[native code]
asyncModuleEvaluation@[native code]
@[native code]
asyncFunctionResume@[native code]
promiseReactionJobWithoutPromise@[native code]
189 |     try {
190 |       this.driver = this._driver();
191 |     } catch (e) {
192 |       const message = `Knex: run\n$ npm install ${this.driverName} --save`;
193 |       this.logger.error(`${message}\n${e.message}\n${e.stack}`);
194 |       throw new Error(`${message}\n${e.message}`);
                ^
error: Knex: run
$ npm install sqlite3 --save
symbol 'napi_register_module_v1' not found in native module. Is this a Node API (napi) module?
      at initializeDriver (/project/node_modules/knex/lib/client.js:194:12)
      at new Client (/project/node_modules/knex/lib/client.js:75:6)
      at new Client_SQLite3 (/project/node_modules/knex/lib/dialects/sqlite3/index.js:22:4)
      at /project/node_modules/knex/lib/knex-builder/Knex.js:16:27
      at /project/DB/models.js:9:0```
