### ISSUE TITLE
mongodb UNABLE_TO_GET_ISSUER_CERT_LOCALLY with 0.6.1

### ISSUE THREAD

**Issue by RUSHt** [oven-sh/bun#2922]
### What version of Bun is running?

0.6.1

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

This works OK in 0.5.9, but fails when bun upgrade > 0.6.1.  Reverted with npm i bun@0.5.9 and works again.

```
        console.log('connect')
        const _DB = 'mongodb+srv://'+DBuser+':'+DBpw+Cluster+DBdefault+'?retryWrites=true&w=majority';
        const client = new MongoClient(_DB);
        console.log('got client')
        await client.connect();
        console.log('got connect')
```

Output on fail is:-

```
connect
got client
94 |         if (message instanceof Error) {
95 |             super(message.message);
96 |             this.cause = message;
97 |         }
98 |         else {
99 |             super(message);
                ^
error: UNABLE_TO_GET_ISSUER_CERT_LOCALLY
 code: "undefined"

      at new MongoError (/Users/<user>/Dev/<app>/node_modules/mongodb/lib/error.js:99:12)
      at new MongoSystemError (/Users/<user>/Dev/<app>/node_modules/mongodb/lib/error.js:589:12)
      at new MongoServerSelectionError (/Users/<user>/Dev/<app>/node_modules/mongodb/lib/error.js:611:8)
      at /Users/<user>/Dev/<app>/node_modules/mongodb/lib/sdam/topology.js:278:37
```

### What is the expected behavior?

If it worked I'd expect to see:-

```
connect
got client
got connect
```

### What do you see instead?

```
connect
got client
94 |         if (message instanceof Error) {
95 |             super(message.message);
96 |             this.cause = message;
97 |         }
98 |         else {
99 |             super(message);
                ^
error: UNABLE_TO_GET_ISSUER_CERT_LOCALLY
 code: "undefined"

      at new MongoError (/Users/<user>/Dev/<app>/node_modules/mongodb/lib/error.js:99:12)
      at new MongoSystemError (/Users/<user>/Dev/<app>/node_modules/mongodb/lib/error.js:589:12)
      at new MongoServerSelectionError (/Users/<user>/Dev/<app>/node_modules/mongodb/lib/error.js:611:8)
      at /Users/<user>/Dev/<app>/node_modules/mongodb/lib/sdam/topology.js:278:37
```

### Additional information

Would be neat to have ability to downgrade bun, without reverting to npm i.

**Comment by cirospaciari** [comment]
Sorry that you encounter this problem, thanks for filling this issue.
Can you try setting the options `&tls=true&tlsCAFile=ca_cert.pem` pointing to your CA file? looks like a `tls` validation issue.

**Comment by RUSHt** [comment]
Sorry, but there is no CA file.  In production the server is fronted by AWS Load Balancer which provides certs, this is occurring on localhost.
