### ISSUE TITLE
bun install: exec permission for binary not set (node_modules/esbuild-darwin-arm64/bin/esbuild EACCES)

### ISSUE THREAD

**Issue by samopus1io** [oven-sh/bun#2956]
### What version of Bun is running?

0.6.2

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

- `bun install` project with vite v4.3
- run vite 
- getting error: node_modules/esbuild-darwin-arm64/bin/esbuild EACCES /@react-refresh

Haven't had that problem using `yarn`. Seems to not happen on linux x86.

Works fine after chmod 755 on  node_modules/esbuild-darwin-arm64/bin/esbuild

**Comment by eknowles** [comment]
[related esbuild source code](https://github.com/evanw/esbuild/blob/main/npm/esbuild-wasm/bin/esbuild)

**Comment by Electroid** [comment]
Are you still running into this issue?

**Comment by cesargdm** [comment]
@Electroid I do, with bun version `1.0.12` and vite `4.5.0`, I get the error output:

```
failed to load config from /.../vite.config.ts
error when starting dev server:
Error: The service was stopped: spawn /.../node_modules/@esbuild/darwin-arm64/bin/esbuild EACCES
    at /.../node_modules/esbuild/lib/main.js:1083:25
    at responseCallbacks.<computed> (/.../node_modules/esbuild/lib/main.js:703:9)
    at ChildProcess.afterClose (/.../node_modules/esbuild/lib/main.js:693:28)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Works for me after running `chmod -R 755 node_modules/@esbuild/darwin-arm64`

> I've been running on this since 0.x bun and I haven't been able to use vite with bun
