### ISSUE TITLE
EdgeDB compatibility

### ISSUE THREAD

**Issue by colinhacks** [oven-sh/bun#3009]
### What version of Bun is running?

0.6.3

### What steps can reproduce the bug?

[edgedb 2.zip](https://github.com/oven-sh/bun/files/11538133/edgedb.2.zip)

```bash
$ edgedb project init
$ bun install
$ bun run index.ts
```

### What is the expected behavior?

Print uuid:

```bash
$ npx tsx index.ts
44e728aa-f904-11ed-afc5-bb333e2ee45d
```

### What do you see instead?

```bash
$ bun run index.ts
Unexpected connection error: 386 |         //Client always request Cert
387 |         this._requestCert = true;
388 |         this._rejectUnauthorized = rejectUnauthorized;
389 |         if (tls) {
390 | 
391 |           tls.rejectUnauthorized = rejectUnauthorized;
             ^
TypeError: Attempted to assign to readonly property.
      at connect (node:net:391:10)
      at /Users/colinmcd94/Downloads/edgedb/node_modules/edgedb/dist/rawConn.js:217:21
      at connectWithTimeout (/Users/colinmcd94/Downloads/edgedb/node_modules/edgedb/dist/rawConn.js:216:36)
      at /Users/colinmcd94/Downloads/edgedb/node_modules/edgedb/dist/retry.js:49:25
      at retryingConnect (/Users/colinmcd94/Downloads/edgedb/node_modules/edgedb/dist/retry.js:43:31)
      at /Users/colinmcd94/Downloads/edgedb/node_modules/edgedb/dist/baseClient.js:344:27

386 |         //Client always request Cert
387 |         this._requestCert = true;
388 |         this._rejectUnauthorized = rejectUnauthorized;
389 |         if (tls) {
390 | 
391 |           tls.rejectUnauthorized = rejectUnauthorized;
             ^
```

**Comment by cirospaciari** [comment]
completed by https://github.com/oven-sh/bun/pull/3457
