### ISSUE TITLE
DOMPurify bug

### ISSUE THREAD

**Issue by Wattville** [oven-sh/bun#3102]
### What version of Bun is running?

0.6.3

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

installing and importing the module `isomorphic-dompurify` or `dompurify` with `jsdom`

### What is the expected behavior?

running smoothly

### What do you see instead?

`[0.03ms] ".env"
4 | const ROOT = Symbol();
5 | const NEXT = Symbol();
6 | const ITERATE_FUNC = Symbol();
7 |
8 | class TreeIterator {
9 |         constructor(tree, root, firstResult, iterateFunction) {
                                    ^
TypeError: Cannot call a class constructor without |new|

at TreeIterator (/home/watty/bun-projects/backend-project/node_modules/symbol-tree/lib/TreeIterator.js:9:32)
      at ancestorsIterator (/home/watty/bun-projects/backend-project/node_modules/symbol-tree/lib/SymbolTree.js:428:23)
      at /home/watty/bun-projects/backend-project/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:104:25
      at _preInsertValidity (/home/watty/bun-projects/backend-project/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:629:8)
      at _preInsert (/home/watty/bun-projects/backend-project/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:749:4)
      at setDocumentType (/home/bun-projects/backend-project/node_modules/jsdom/lib/jsdom/browser/parser/html.js:127:4)
      at _setDocumentType (/home/bun-projects/backend-project/node_modules/parse5/dist/cjs/parser/index.js:240:8)
      at /home/bun-projects/backend-project/node_modules/parse5/dist/cjs/parser/index.js:1272:4
      at onDoctype (/home/bun-projects/backend-project/node_modules/parse5/dist/cjs/parser/index.js:752:16)
      at emitCurrentDoctype (/home/bun-projects/backend-project/node_modules/parse5/dist/cjs/tokenizer/index.js:413:8)
      at _stateDoctypeName (/home/bun-projects/backend-project/node_modules/parse5/dist/cjs/tokenizer/index.js:2197:16)
      at _callState (/home/bun-projects/backend-project/node_modules/parse5/dist/cjs/tokenizer/index.js:777:16)
      at _runParsingLoop (/home/bun-projects/backend-project/node_modules/parse5/dist/cjs/tokenizer/index.js:226:16)
      at write (/home/bun-projects/backend-project/node_modules/parse5/dist/cjs/tokenizer/index.js:251:8)
      at parse (/home/bun-projects/backend-project/node_modules/parse5/dist/cjs/parser/index.js:101:8)
      at new JSDOM (/home/bun-projects/backend-project/node_modules/jsdom/lib/api.js:42:4)
      at /home/bun-projects/backend-project/node_modules/isomorphic-dompurify/index.js:1:224
      at /home/bun-projects/backend-project/node_modules/isomorphic-dompurify/index.js:1:259
      at /home/bun-projects/backend-project/test.js:1:0 `

### Additional information

code I ran:
`import DOMPurify from 'isomorphic-dompurify';

const clean = DOMPurify.sanitize('asdasd');`

**Comment by paperclover** [comment]
Fixed in https://github.com/oven-sh/bun/pull/3294 (0.6.9)
