### ISSUE TITLE
the Got library not work with Bun

### ISSUE THREAD

**Issue by drag0n-app** [oven-sh/bun#3150]
### What version of Bun is running?

0.6.5

### What platform is your computer?

Darwin 22.1.0 arm64 arm

### What steps can reproduce the bug?

import got from 'got';

let response = await got('https://bun.sh/');
console.log(response.statusCode);

### What is the expected behavior?

200

### What do you see instead?

 7 | const ClientRequest = require('./client-request.js');
 8 | const IncomingMessage = require('./incoming-message.js');
 9 | const auto = require('./auto.js');
10 | const {
11 |    HttpOverHttp2,
12 |    HttpsOverHttp2
    ^
TypeError: undefined is not an object (evaluating 'new tls.TLSSocket(new stream.PassThrough)._handle._parentWrap')

**Comment by Jarred-Sumner** [comment]
I don’t think it’ll fix this particular issue but small chance it will

Can you try upgrading to v0.6.6?

**Comment by drag0n-app** [comment]
v0.6.6 still showing the same error

**Comment by shuiRong** [comment]
same issue same "got" 

bun version: 0.6.7

```
 bun run src/index.ts
[0.21ms] ".env"
1 | 'use strict';
2 | const stream = require('stream');
3 | const tls = require('tls');
4 | 
5 | // Really awesome hack.
6 | const JSStreamSocket = (new tls.TLSSocket(new stream.PassThrough()))._handle._parentWrap.constructor;
                           ^
TypeError: undefined is not an object (evaluating 'new tls.TLSSocket(new stream.PassThrough)._handle._parentWrap')
      at /Users/xxx/Work/site-fetcher/node_modules/http2-wrapper/source/utils/js-stream-socket.js:6:24
      at (eval) (/Users/xxx/Work/site-fetcher/node_modules/http2-wrapper/source/utils/js-stream-socket.js:8:17)
      at /Users/xxxx/Work/site-fetcher/node_modules/http2-wrapper/source/proxies/h1-over-h2.js:5:6
      at (eval) (/Users/xxxx/Work/site-fetcher/node_modules/http2-wrapper/source/proxies/h1-over-h2.js:90:0)
      at /Users/xxxx/Work/site-fetcher/node_modules/http2-wrapper/source/index.js:12:1
      at (eval) (/Users/xxxxx/Work/site-fetcher/node_modules/http2-wrapper/source/index.js:50:0)
```

**Comment by 3ldar** [comment]
It seems the above issue is fixed in canary build `0.6.14` but now it raises another error like the one below:
```
218 |         this.on('newListener', event => {
219 |             if (event === 'retry' && this.listenerCount('retry') > 0) {
220 |                 throw new Error('A retry listener has been attached already.');
```
[Source to line](https://github.com/sindresorhus/got/blob/b1d61c173a681755ac23afb2f155f08801c1e7e4/source/core/index.ts#L221C1-L225C6)

The above error still occurs as of v0.8.0

**Comment by ajschmidt8** [comment]
I'm also experiencing this issue with bun version `0.6.13`.

Here's my minimal reproducer:

```ts
import got from "got";
await got('https://bun.sh/');
```

My stack trace is identical to what `3ldar` posted:

<details><summary>Full Stack Trace</summary>
<p>

```
215 |                 Object.assign(this.options.headers, source.headers);
216 |             }
217 |         });
218 |         this.on('newListener', event => {
219 |             if (event === 'retry' && this.listenerCount('retry') > 0) {
220 |                 throw new Error('A retry listener has been attached already.');
                          ^
error: A retry listener has been attached already.
      at /workspaces/nap-hugo/backend/node_modules/got/dist/source/core/index.js:220:22
      at makeRequest (/workspaces/nap-hugo/backend/node_modules/got/dist/source/as-promise/index.js:107:12)
      at /workspaces/nap-hugo/backend/node_modules/got/dist/source/as-promise/index.js:125:8
      at /workspaces/nap-hugo/backend/node_modules/p-cancelable/index.js:63:3
      at new PCancelable (/workspaces/nap-hugo/backend/node_modules/p-cancelable/index.js:31:18)
      at asPromise (/workspaces/nap-hugo/backend/node_modules/got/dist/source/as-promise/index.js:21:20)
      at lastHandler (/workspaces/nap-hugo/backend/node_modules/got/dist/source/create.js:42:26)
      at iterateHandlers (/workspaces/nap-hugo/backend/node_modules/got/dist/source/create.js:49:18)
44 |             enumerable: true,
45 |             configurable: true,
46 |             writable: true,
47 |             value: void 0
48 |         });
49 |         Error.captureStackTrace(this, this.constructor);
            ^
RequestError: Attempted to assign to readonly property.
 code: "ERR_GOT_REQUEST_ERROR"

      at new RequestError (/workspaces/nap-hugo/backend/node_modules/got/dist/source/core/errors.js:49:8)
      at _beforeError (/workspaces/nap-hugo/backend/node_modules/got/dist/source/core/index.js:310:20)
      at /workspaces/nap-hugo/backend/node_modules/got/dist/source/core/index.js:772:12
```

</p>
</details> 

~~From the stack trace details and the `nodejs-apis` chart linked below, I think it could have something to do with `events.on` not being implemented in the `node:events` library yet.~~

- https://bun.sh/docs/runtime/nodejs-apis

Actually, I'm not sure if my statement above is accurate.

**Comment by ajschmidt8** [comment]
related: https://github.com/oven-sh/bun/issues/2679

**Comment by paperclover** [comment]
![image](https://github.com/oven-sh/bun/assets/24465214/6c94c538-aa4d-4c3a-bc5c-cf9720a86fac)

bun's `node:http.IncomingMessage` does not allow ovewriting these properties because they are only getters:
 
![image](https://github.com/oven-sh/bun/assets/24465214/1587c7d6-3c20-4bfa-9825-b1992dc4c73c)

**Comment by sirenkovladd** [comment]
@paperdave I guess this is the main reason (in my case) https://github.com/oven-sh/bun/issues/4397

**Comment by muhamed-didovic** [comment]
Hi, version 1.0.2 shows still the same error, any info on when PR could be merged?

**Comment by paperclover** [comment]
the pr has failing tests unfortunatly

**Comment by gilmillasseau** [comment]
Hey @paperdave I just updated Bun and this is still happening #6427, do you know if this will be picked up soon? I also tried with the latest version `"got": "13.0.0",`

**Comment by eliellis** [comment]
Just ran into this one today while experimenting with Bun in an existing codebase (`bun v1.0.15`). This would be really great to have support for since Got is such a popular choice for making HTTP requests in modern Node.js. 

Thank you guys for all the hard work so far. ❤️

**Comment by paperclover** [comment]
it is very close but there are some https / compression issues with got after the pr. i've been prioritizing windows mostly and havent had time to finish that pr.

**Comment by MetaMmodern** [comment]
I see a different error, but nevertheless Got doesn't work with Bun.

```
972 |         });
973 |         this[kUnproxyEvents] = proxy_events_1.default(request, this, proxiedRequestEvents);
974 |         this[kRequest] = request;
975 |         this.emit('uploadProgress', this.uploadProgress);
976 |         // Send body
977 |         const body = this[kBody];
                                                                         ^
RequestError: Unable to connect. Is the computer able to access the url?
 code: "ConnectionRefused"

      at projectName/node_modules/got/dist/source/core/index.js:977:68
      at projectName/node_modules/@szmarczak/http-timer/dist/source/index.js:48:34
      at native:1:1
      at promiseReactionJob (native:1:1)
      at processTicksAndRejections (native:1:1)
```

The code I ran is same as minimal repro in comments above.

~~@paperdave let us know please if there's a Bun internal library that could replace got or any other recommended lib. thanks~~ 
found it supports fetch. neat! https://bun.sh/guides/http/fetch

**Comment by RokoTechnology** [comment]
can confirm still issue as of bun 1.0.25 and got 14.0.0

**Comment by jdalton** [comment]
@paperdave 
> it is very close but there are some https / compression issues with got after the pr. i've been prioritizing windows mostly and havent had time to finish that pr.

The PR at https://github.com/oven-sh/bun/pull/4395 seems really involved. Would a quick fix be to simply add the setter?

**Update:**

Related PR fix for the setter: https://github.com/oven-sh/bun/pull/8368

**Comment by jdalton** [comment]
Update:

Related PR fix for the setter: https://github.com/oven-sh/bun/pull/8368

**Comment by luckyyyyy** [comment]
This is currently one of the issues blocking me, is there any progress?
![image](https://github.com/oven-sh/bun/assets/9210430/8075e7c1-0036-4c7e-9208-4216ebc48baf)

**Comment by edgarasben** [comment]
The same issue still in bun 1.1.0

**Comment by IAkumaI** [comment]
The issue is still here in the latest 1.1.4
Any updates?

**Comment by edgarasben** [comment]
Yes, `got` package still doesn't work in `1.1.4`

**Comment by timz-dev** [comment]
I experience the same error with `got` using bun version `1.1.4`

```typescript
[0-0] 89 |                 Object.assign(this.options.headers, source.headers);
[0-0] 90 |             }
[0-0] 91 |         });
[0-0] 92 |         this.on('newListener', event => {
[0-0] 93 |             if (event === 'retry' && this.listenerCount('retry') > 0) {
[0-0] 94 |                 throw new Error('A retry listener has been attached already.');
[0-0]                            ^
[0-0] error: A retry listener has been attached already.
[0-0]       at /Users/timarzoltan/dev/dc-automation-wdio/node_modules/got/dist/source/core/index.js:94:23
[0-0]       at makeRequest (/Users/timarzoltan/dev/dc-automation-wdio/node_modules/got/dist/source/as-promise/index.js:113:13)
[0-0]       at /Users/timarzoltan/dev/dc-automation-wdio/node_modules/got/dist/source/as-promise/index.js:131:9
[0-0]       at /Users/timarzoltan/dev/dc-automation-wdio/node_modules/p-cancelable/index.js:68:4
[0-0]       at new Promise (:1:21)
[0-0]       at new PCancelable (/Users/timarzoltan/dev/dc-automation-wdio/node_modules/p-cancelable/index.js:34:19)
[0-0]       at asPromise (/Users/timarzoltan/dev/dc-automation-wdio/node_modules/got/dist/source/as-promise/index.js:21:21)
[0-0]       at lastHandler (/Users/timarzoltan/dev/dc-automation-wdio/node_modules/got/dist/source/create.js:42:27)
[0-0]       at iterateHandlers (/Users/timarzoltan/dev/dc-automation-wdio/node_modules/got/dist/source/create.js:49:19)
[0-0]       at /Users/timarzoltan/dev/dc-automation-wdio/node_modules/webdriver/build/request/node.js:17:27
[0-0]       at _libRequest (/Users/timarzoltan/dev/dc-automation-wdio/node_modules/webdriver/build/request/node.js:15:23)
[0-0]       at /Users/timarzoltan/dev/dc-automation-wdio/node_modules/webdriver/build/request/index.js:147:30
[0-0]       at _request (/Users/timarzoltan/dev/dc-automation-wdio/node_modules/webdriver/build/request/index.js:140:20)
```

**Comment by palmamartin** [comment]
I'm seeing the following error using bun version `1.1.4`. A third-party library uses `got` which we depend on to use:
```
1212 |         this[kStopReading] = true;
1213 |         if (!(error instanceof RequestError)) {
1214 |             error = new RequestError(error.message, error, this);
1215 |         }
1216 |         const typedError = error;
1217 |         const { response } = typedError;
                    ^
RequestError: Attempted to assign to readonly property.
 code: "ERR_GOT_REQUEST_ERROR"

      at _beforeError (/Users/m/src/github.com/project/importer/node_modules/got/dist/source/core/index.js:1217:14)
      at /Users/m/src/github.com/project/importer/node_modules/got/dist/source/core/index.js:1262:35
      at asyncFunctionResume (native:1:1)
      at promiseReactionJobWithoutPromiseUnwrapAsyncContext (native:1:1)
      at promiseReactionJob (native:1:1)
      at processTicksAndRejections (native:1:1)
      at /Users/m/src/github.com/project/importer/node_modules/got/dist/source/core/index.js:1043:21
      at _onResponseBase (/Users/m/src/github.com/project/importer/node_modules/got/dist/source/core/index.js:778:27)
      at /Users/m/src/github.com/project/importer/node_modules/got/dist/source/core/index.js:948:24
      at _onResponse (/Users/m/src/github.com/project/importer/node_modules/got/dist/source/core/index.js:946:23)
      at /Users/m/src/github.com/project/importer/node_modules/got/dist/source/core/index.js:962:23
      at emit (native:1:1)
      at /Users/m/src/github.com/project/importer/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20
      at node:http:916:58
```

**Comment by IAkumaI** [comment]
@palmamartin I saw this error on the not last version of got, too.
In fact, no one got version works

**Comment by SteveYuOWO** [comment]
Yes, got package still doesn't work in `1.1.5`

**Comment by nxht** [comment]
It seems the issue is fixed in 1.1.9 during #11082 ?
For my case, the got library works fine now.

**Comment by edgarasben** [comment]
Yes, `got` is now working in `1.1.9'!

**Comment by IAkumaI** [comment]
Confirm. Also works. Not production tested, but at least works on simple requests

**Comment by IAkumaI** [comment]
Hm...seems like it has some problems with https websites.
For example
```
await got('https://github.com/');
```
Hangs forever. Timeout, error catching, anything does not work at all.

**Comment by nektro** [comment]
looks like this appears to be working now :) if any other issues are discovered feel free to open a new issue, but for now we'll close this one. you may need to run `bun upgrade` to get the latest fixes.
