### ISSUE TITLE
Nats.io Connection Error

### ISSUE THREAD

**Issue by metecik** [oven-sh/bun#3170]
### What version of Bun is running?

0.6.6

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

Using nats npm library:     "nats": "^1.4.12"

When you try to connect nats you get error:
```
405 |         this._secureEstablished = false;
406 |         this._securePending = true;
407 |         if (connectListener) this.on("secureConnect", connectListener);
408 |       } else if (connectListener) this.on("connect", connectListener);
409 | 
410 |       bunConnect(
         ^
error: Failed to connect
      at connect (node:net:410:6)
      at /Work/matches/base/node_modules/nats/lib/nats.js:938:16
      at new  (/Work/matches/base/node_modules/nats/lib/nats.js:225:2)
      at /Work/matches/base/node_modules/nats/lib/nats.js:250:9
      at connect (/Work/matches/base/lib/natsClient.js:59:18)
      at /Work/matches/workers/socket/server.js:63:0
```

### What is the expected behavior?

connect and listen nats channels

**Comment by nektro** [comment]
note to future self, this works sometimes in present versions but is very flaky. needs more investigation
