### ISSUE TITLE
Test does not fail with certain uncaught errors

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#3247]
In the example below, a WebSocket handler in `serve()` has an uncaught exception, but does not fail the test, since it times out instead.

```
56 |   });
57 |   describe("ping()", () => {
58 |     for (const { label, message, bytes } of messages) {
59 |       test(label, (done) => ({
60 |         open(ws) {
61 |           ws.ping(message);
              ^
error: ping requires an ArrayBufferView
      at open (/bun/test/js/bun/websocket/websocket-server2.test.ts:61:10)
      at fetch (/bun/test/js/bun/websocket/websocket-server2.test.ts:84:12)
Timeout: test "ArrayBuffer (utf-8)" timed out after 100ms
✗ WebSocketServer > ping() > ArrayBuffer (utf-8) [197.95ms]

**Comment by Jarred-Sumner** [comment]
sidenote: why does ping require an ArrayBufferView? Can’t it transcode the string to UTF-8 like everywhere else

**Comment by Electroid** [comment]
It will, that is just a failing test because it's not implemented yet.
