### ISSUE TITLE
vue ssr support

### ISSUE THREAD

**Issue by Years-Enron** [oven-sh/bun#3295]
### What version of Bun is running?

0.6.8

### What platform is your computer?

Linux 6.3.5-200.fc38.x86_64 x86_64 unknown

### What steps can reproduce the bug?

```
git clone https://github.com/vuejs/vue-hackernews-2.0.git
cd vue-hackernews-2.0
bun install
bun run server.js
```

**Comment by Jarred-Sumner** [comment]
Looks like https://github.com/oven-sh/bun/pull/3294 is not fully fixed.

It's the same pattern. After importing a massive number of files, we get a crash while GC is visiting.

**Comment by birkskyum** [comment]
With 0.8 I get:

```sh
➜ bun run server.js
server started at localhost:8080
164 |     rawEmitters.push(rawEmitter);
165 |     container = FsWatchFileInstances[fullPath] = {
166 |       listeners: listeners,
167 |       rawEmitters: rawEmitters,
168 |       options: options,
169 |       watcher: fs.watchFile(fullPath, options, function(curr, prev) {
                   ^
TypeError: undefined is not a function (near '...fs.watchFile...')
      at setFsWatchFileListener (/Users/admin/repos/vue-hackernews-2.0/node_modules/chokidar/lib/nodefs-handler.js:169:15)
      at /Users/admin/repos/vue-hackernews-2.0/node_modules/chokidar/lib/nodefs-handler.js:223:13
      at /Users/admin/repos/vue-hackernews-2.0/node_modules/chokidar/lib/nodefs-handler.js:255:15
      at /Users/admin/repos/vue-hackernews-2.0/node_modules/chokidar/lib/nodefs-handler.js:473:15
```

- #3812

**Comment by birkskyum** [comment]
The server is starting as expected now.
