### ISSUE TITLE
fetch is not a function. It's Object.

### ISSUE THREAD

**Issue by mariodian** [oven-sh/bun#3303]
### What version of Bun is running?

0.6.9

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Errors while running application with [Node-Fetch](https://www.npmjs.com/package/node-fetch) as a dependency within a 3rd party package [bfx-api-node-rest](https://github.com/bitfinexcom/bfx-api-node-rest).

A test code:

````node
import {type Serve} from "bun";

const { RESTv2 } = require('bfx-api-node-rest');

const rest = new RESTv2({
  apiKey: 'asdf',
  apiSecret: 'asdf',
  transform: true, // to have full models returned by all methods
});

export default {
  fetch: async (resp) => {
    const response = await rest.wallets({});

    console.log(response)

    return new Response('test')
  }
} satisfies Serve;
````

### What is the expected behavior?

Connect to the Bitfinex API and return he list of crypto wallets.

### What do you see instead?

The following error when I open `http://localhost:3000`:

````node
139 |     return !!this._agent
140 |   }
141 |
142 |   async _request (url, reqOpts, transformer, cb) {
143 |     try {
144 |       const resp = await fetch(url, reqOpts)
                             ^
TypeError: fetch is not a function. (In 'fetch(url, reqOpts)', 'fetch' is an instance of Object)
      at /Users/mariodian/Source/Bitcoin/bfx-tools/src/server/node_modules/bfx-api-node-rest/lib/rest2.js:144:25
      at _request (/Users/mariodian/Source/Bitcoin/bfx-tools/src/server/node_modules/bfx-api-node-rest/lib/rest2.js:142:18)
      at _makeAuthRequest (/Users/mariodian/Source/Bitcoin/bfx-tools/src/server/node_modules/bfx-api-node-rest/lib/rest2.js:180:26)
      at /Users/mariodian/Source/Bitcoin/bfx-tools/src/server/index.ts:13:27
      at /Users/mariodian/Source/Bitcoin/bfx-tools/src/server/index.ts:12:16
GET - http://localhost:3000/ failed
139 |     return !!this._agent
140 |   }
141 |
142 |   async _request (url, reqOpts, transformer, cb) {
143 |     try {
144 |       const resp = await fetch(url, reqOpts)
                             ^
TypeError: fetch is not a function. (In 'fetch(url, reqOpts)', 'fetch' is an instance of Object)
      at /Users/mariodian/Source/Bitcoin/bfx-tools/src/server/node_modules/bfx-api-node-rest/lib/rest2.js:144:25
      at _request (/Users/mariodian/Source/Bitcoin/bfx-tools/src/server/node_modules/bfx-api-node-rest/lib/rest2.js:142:18)
      at _makeAuthRequest (/Users/mariodian/Source/Bitcoin/bfx-tools/src/server/node_modules/bfx-api-node-rest/lib/rest2.js:180:26)
      at /Users/mariodian/Source/Bitcoin/bfx-tools/src/server/index.ts:13:27
      at /Users/mariodian/Source/Bitcoin/bfx-tools/src/server/index.ts:12:16
````

**Comment by paperclover** [comment]
not fixed
```
const fetch = require("node-fetch");
console.log(typeof fetch);
```
