### ISSUE TITLE
Bun does not print an error’s `cause` when outputting an error.

### ISSUE THREAD

**Issue by dtinth** [oven-sh/bun#3311]
### What version of Bun is running?

0.6.9

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

`a.js`:

```js
try {
  throw new Error('Inner')
} catch (e) {
  throw new Error('Outer', { cause: e })
}
```

`bun a.js`

### What is the expected behavior?

The error log should display the cause of an error, to make debugging easy:

```
Error: Outer
      at /private/tmp/a/a.js:4:8
  [cause]: Error: Inner
        at /private/tmp/a/a.js:2:8
}
```

For example, this is Node.js output

```
/private/tmp/a/a.js:4
  throw new Error('Outer', { cause: e })
  ^

Error: Outer
    at Object.<anonymous> (/private/tmp/a/a.js:4:9)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    ... 4 lines matching cause stack trace ...
    at node:internal/main/run_main_module:23:47 {
  [cause]: Error: Inner
      at Object.<anonymous> (/private/tmp/a/a.js:2:9)
      at Module._compile (node:internal/modules/cjs/loader:1218:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
      at Module.load (node:internal/modules/cjs/loader:1081:32)
      at Module._load (node:internal/modules/cjs/loader:922:12)
      at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
      at node:internal/main/run_main_module:23:47
}
```

### What do you see instead?

```
1 | try {
2 |   throw new Error('Inner')
3 | } catch (e) {
4 |   throw new Error('Outer', { cause: e })
            ^
error: Outer
      at /private/tmp/a/a.js:4:8
```

### Additional information

Right now I have to do this. IMO developers shouldn’t have to write such things by themselves as it should be handled automatically by the runtime (like Node):

```ts
function logError(error: string) {
    console.log(error)
    if (error.cause) {
        console.error(error.cause)
        if ((error.cause as any).cause) {
             console.error((error.cause as any).cause)
        }
    }
}
```

**Comment by Electroid** [comment]
Yes, we'll need to change our error printing code to support this.

**Comment by leepowelldev** [comment]
Would be great if this could support nested `cause` too:

```
throw new Error('Outer', { cause: Error('Inner', { cause: e  }) })
```

**Comment by naterkane** [comment]
Not displaying the call stack has made debugging even the most trivial errors give me flashbacks to the pre-venkman javascript days.

**Comment by Electroid** [comment]
This has been fixed.

```js
❯ bun index.ts
1 | try {
2 |   throw new Error('Inner')
3 | } catch (e) {
4 |   throw new Error('Outer', { cause: e })
            ^
error: Outer
      at /index.ts:4:9

1 | try {
2 |   throw new Error('Inner')
            ^
error: Inner
      at /index.ts:2:9
```
