### ISSUE TITLE
React hooks not working inside TSX/JSX file (with Hono).

### ISSUE THREAD

**Issue by mtlaso** [oven-sh/bun#3346]
### What version of Bun is running?

0.6.10

### What platform is your computer?

Linux 6.2.6-76060206-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Init project
``` sh
bun create hono hono-app           # Init app
cd hono-app                        # Go to dir
bun add react react-dom @types/react hono     # Install react packages and update hono
```

2. Delete `src/index.ts` and add `src/index.tsx`

```tsx
// index.tsx

import { Hono } from "hono";
import { serveStatic } from "hono/bun";

import LoginPage from "./LoginPage";

const port = process.env.PORT ?? 8000;
const app = new Hono();

app.get("/login", (c) => {
  return c.html(<LoginPage />);
});

console.log(`Server on http://localhost:${port}`);

export default {
  port,
  fetch: app.fetch,
};
```

3. Create Login component `src/LoginView.tsx`

```tsx
// LoginPage.tsx

import { useState } from "react";

const LoginPage = () => {
  const [id, setId] = useState(1); // <------- Error right here
  return (
      <div>
        <h1>LoginView</h1>
      </div>
  );
};

export default LoginPage;

```

4. Update `tsconfig.json`
```json
{
  "compilerOptions": {
    // React (JSX)
    "jsx": "react-jsx",
    "jsxFactory": "jsx",
    "jsxFragmentFactory": "Fragment",
    "jsxImportSource": "hono/jsx",

    "lib": ["ESNext"],
    "module": "esnext",
    "target": "ESNext",
    "moduleResolution": "node",
    "strict": true,
    "skipLibCheck": true,
    "allowJs": true,
    "allowSyntheticDefaultImports": true,

    // "bun-types" is the important part
    "types": ["bun-types"]
  }
}

```

5. Run `bun run src/index.tsx`

6. Navigate to page `localhost:<port>/login`

7. Expect an error now!

### What is the expected behavior?

To see a rendered page.

### What do you see instead?

An error (Internal Server Error).
```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
1617 | 
1618 |   return dispatcher.useContext(Context);
1619 | }
1620 | function useState(initialState) {
1621 |   var dispatcher = resolveDispatcher();
1622 |   return dispatcher.useState(initialState);
             ^
TypeError: null is not an object (evaluating 'dispatcher.useState')
      at useState (/home/user/desktop/dev/bun/hono-app/node_modules/react/cjs/react.development.js:1622:9)
      at /home/user/desktop/dev/bun/hono-app/src/LoginPage.tsx:6:22
      at toStringToBuffer (/home/user/desktop/dev/bun/hono-app/node_modules/hono/dist/middleware/jsx/index.js:123:16)
      at toString (/home/user/desktop/dev/bun/hono-app/node_modules/hono/dist/middleware/jsx/index.js:72:4)
      at /home/user/desktop/dev/bun/hono-app/node_modules/hono/dist/context.js:66:15
      at dispatch (/user/desktop/Bureau/dev/bun/hono-app/node_modules/hono/dist/hono-base.js:200:14)

      at /home/user/desktop/dev/bun/hono-app/node_modules/hono/dist/hono-base.js:18:2
```

### Additional information

Commenting `const [id, setId] = useState(1);` in `LoginPage.tsx` removes the error. Using other hooks such as `useEffect` gives the same error.

**Comment by Jarred-Sumner** [comment]
IIRC, Hono uses its own JSX runtime. Is that possibly conflicting? What if you use renderToString or renderToReadableStream imported from react-dom?

**Comment by mtlaso** [comment]
> IIRC, Hono uses its own JSX runtime. Is that possibly conflicting? What if you use renderToString or renderToReadableStream imported from react-dom?

Thank you for your quick answer, can you explain what you mean by **use renderToString or renderToReadableStream_**. I am quite a beginner in the react ecosystem.

**Comment by Jarred-Sumner** [comment]
```js 
import {renderToString} from “react-dom”

import LoginPage from "./LoginPage";

const port = process.env.PORT ?? 8000;
const app = new Hono();

app.get("/login", (c) => {
  return c.text(renderToString(<LoginPage />));
});

console.log(`Server on http://localhost:${port}`);

export default {
  port,
  fetch: app.fetch,
};
```

**Comment by mtlaso** [comment]
> ```js
> import {renderToString} from “react-dom”
> 
> import LoginPage from "./LoginPage";
> 
> const port = process.env.PORT ?? 8000;
> const app = new Hono();
> 
> app.get("/login", (c) => {
>   return c.text(renderToString(<LoginPage />));
> });
> 
> console.log(`Server on http://localhost:${port}`);
> 
> export default {
>   port,
>   fetch: app.fetch,
> };
> ```

Tried that, it worked, but it displayed everything as text, not html. Though, I had to comment `jsxImportSource": "hono/jsx"` from `ts.config` for it to work. Otherwise, it says : `Argument of type 'HtmlEscapedString' is not assignable to parameter of type 'ReactElement<any, string | JSXElementConstructor<any>>'.
`

Like this :
```tsx
// index.tsx

import { Hono } from "hono";
import { serveStatic } from "hono/bun";
import { renderToString } from "react-dom/server";

import LoginPage from "./LoginPage";

const port = process.env.PORT ?? 8000;
const app = new Hono();

app.get("/login", (c) => {
  // Render the component to a readable stream
  return c.text(renderToString(<LoginPage />));
});

console.log(`Server on http://localhost:${port}`);

export default {
  port,
  fetch: app.fetch,
};
```

**Comment by sor4chi** [comment]
Hello, appliquant.
I commented "hono/jsx" and the type error also disappeared.
Wouldn't regenerating node_modules or restarting ts-language-server fix it?

**Comment by robobun** [comment]
This is not a Bun bug - it's a fundamental incompatibility between two different JSX systems.

**The problem:** You're using `jsxImportSource: "hono/jsx"` in your tsconfig.json, which tells the compiler to use Hono's JSX runtime. However, you're trying to use React hooks (`useState` from "react") inside your components.

**Why this doesn't work:** React hooks require React's internal dispatcher/reconciler to function. When you set `jsxImportSource: "hono/jsx"`, your JSX is being processed by Hono's lightweight server-side JSX implementation - which is **not React** and has no React runtime. The error message "Invalid hook call" and "dispatcher is null" is React telling you there's no React runtime available to handle the hook.

**This is expected behavior** - it would behave identically in Node.js, esbuild, Vite, or any other bundler. You cannot mix React hooks with non-React JSX implementations.

**Solutions:**
1. **Use React's JSX** if you need React hooks: Remove `jsxImportSource: "hono/jsx"` and use `react-dom/server`'s `renderToString` or `renderToReadableStream` (as @Jarred-Sumner suggested)
2. **Use Hono's JSX without React hooks**: Hono's JSX is designed for server-side HTML generation and doesn't support React's stateful features
3. **Keep them separate**: Use Hono for routing and Hono JSX for simple server-rendered pages, but use React (with its own JSX runtime) for interactive components

Closing as this is working as intended - it's a usage error, not a Bun issue.
