### ISSUE TITLE
Issue with node-appwrite package

### ISSUE THREAD

**Issue by gtrabanco** [oven-sh/bun#3386]
### What version of Bun is running?

0.6.10

### What platform is your computer?

Darwin 22.5.0 x86_64 i386

### What steps can reproduce the bug?

```ts
import { Client, Databases } from "node-appwrite";

// Init SDK
export const client = new Client();

if (
  !process.env.APPWRITE_ENDPOINT ||
  !process.env.APPWRITE_PROJECTID ||
  !process.env.APPWRITE_APIKEY
) {
  throw new Error(`Fatal error: Appwrite configuration was not set`);
}

client
  .setEndpoint(process.env.APPWRITE_ENDPOINT) // Your API Endpoint
  .setProject(process.env.APPWRITE_PROJECTID) // Your project ID
  .setKey(process.env.APPWRITE_APIKEY); // Your secret API key

const database = new Databases(client);

console.log(await database.list());
```

### What is the expected behavior?

An array of my databases

### What do you see instead?

```shell
$ bun run index.ts
[0.05ms] ".env"
1 | class AppwriteException extends Error {
2 |   constructor(message, code, type, response) {
3 |     super(message);
        ^
error: Adapter 'http' is not available in the build
 code: "undefined"

      at new AppwriteException (~/MyProjects/appwrite-test/node_modules/node-appwrite/lib/exception.js:3:4)
      at ~/MyProjects/appwrite-test/node_modules/node-appwrite/lib/client.js:178:22
```

### Additional information

Using bun canary build of commit: 4a13a53058eca1c3d96847277878a19192dd2a34

**Comment by gtrabanco** [comment]
This is related to #3371.

Should I close the issue?

**Comment by birkskyum** [comment]
@gtrabanco , can you retry this now that #3371 is resolved?

**Comment by birkskyum** [comment]
@gtrabanco , I tried to add the env variables, and got this with bun 0.8, so it seems to be working now:

```zig
➜ bun run index.js
[0.06ms] ".env"
{
  total: 1,
  databases: [
    {
      $id: "64e7d1058ee9df4f0601",
      name: "etstedb",
      $createdAt: "2023-08-24T21:52:05.586+00:00",
      $updatedAt: "2023-08-24T21:52:05.586+00:00"
    }
  ]
}
```

@gtrabanco  does it work for you as well?

**Comment by birkskyum** [comment]
can be closed

**Comment by gtrabanco** [comment]
Yes, sorry. I was out.

 👍
