### ISSUE TITLE
Puppeteer, cosmiconfig - RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by 0x00ahmad** [oven-sh/bun#3592]
### What version of Bun is running?

0.6.13

### What platform is your computer?

Linux 6.3.9-zen1-1-zen x86_64 unknown || Arch

### What steps can reproduce the bug?

- Setup a simple bun repo
- Install puppeteeer (mine is version 20.8.0, at the time of writing this)
- paste the sample code from https://pptr.dev/#example into <filename>.ts file
- bun run main.ts (or whatever your filename is)

### What is the expected behavior?

Puppeteer should run and it's browser window should open as it normally does with NodeJS

### What do you see instead?

v-checker on  main [?] via 🍞 v0.6.13
\>_ bun run main.ts 
[0.02ms] ".env"
36 | 
37 |   searchFromDirectorySync(dir) {
38 |     const absoluteDir = _path.default.resolve(process.cwd(), dir);
39 | 
40 |     const run = () => {
41 |       const result = this.searchDirectorySync(absoluteDir);
                         ^
RangeError: Maximum call stack size exceeded.
      at run (/run/media/drives/documentSSD/main/GitHub/side-projects/v-checker/node_modules/cosmiconfig/dist/ExplorerSync.js:41:21)
      at cacheWrapperSync (/run/media/drives/documentSSD/main/GitHub/side-projects/v-checker/node_modules/cosmiconfig/dist/cacheWrapper.js:28:17)
      at cacheWrapperSync (/run/media/drives/documentSSD/main/GitHub/side-projects/v-checker/node_modules/cosmiconfig/dist/cacheWrapper.js:28:17)
      at cacheWrapperSync (/run/media/drives/documentSSD/main/GitHub/side-projects/v-checker/node_modules/cosmiconfig/dist/cacheWrapper.js:28:17)
      at cacheWrapperSync (/run/media/drives/documentSSD/main/GitHub/side-projects/v-checker/node_modules/cosmiconfig/dist/cacheWrapper.js:28:17)
      at cacheWrapperSync (/run/media/drives/documentSSD/main/GitHub/side-projects/v-checker/node_modules/cosmiconfig/dist/cacheWrapper.js:28:17)
      at cacheWrapperSync (/run/media/drives/documentSSD/main/GitHub/side-projects/v-checker/node_modules/cosmiconfig/dist/cacheWrapper.js:28:17)
      at cacheWrapperSync (/run/media/drives/documentSSD/main/GitHub/side-projects/v-checker/node_modules/cosmiconfig/dist/cacheWrapper.js:28:17)
      at cacheWrapperSync (/run/media/drives/documentSSD/main/GitHub/side-projects/v-checker/node_modules/cosmiconfig/dist/cacheWrapper.js:28:17)
      at cacheWrapperSync (/run/media/drives/documentSSD/main/GitHub/side-projects/v-checker/node_modules/cosmiconfig/dist/cacheWrapper.js:28:17)

**Comment by Jarred-Sumner** [comment]
I have a feeling this will only repro with some files/folders matching whats on your computer. It doesn't repro for me on macOS. It sounds like it would be fixed by #1579 though

**Comment by 0x00ahmad** [comment]
I don't think it's a mac specific issue, but I may be wrong. Because I have a pretty good idea of why it's happening according to my assessment so far : 

For context :: All of my code lives in a secondary ssd(/run/media/drives/documentSSD/main/...)

It has to do with how they are path finding their configuration files. Because of the sheer amount of directories the function is looking processing while looking for configuration files.

As my mount path has way more intermediary directories, example in /, /run, /run/media, /run/media/drives .... and so on, compared to something like /home/user/Documents/.... It quickly reaches the stack limit.

![image](https://github.com/oven-sh/bun/assets/69459394/fb5f70d9-cfde-487d-b5a4-0ce0417b1080)
![image](https://github.com/oven-sh/bun/assets/69459394/5e43f20f-bb6c-40fe-a400-e153c77abc95)

And so,  when I put the code under /home/user/Documents/v-checker/... directory, it ran fine.

![image](https://github.com/oven-sh/bun/assets/69459394/c32ea022-84f1-4f16-978e-dc3291d635c3)

**Comment by daanlenaerts** [comment]
I'm having the same issue. It is however not entirely clear to me how you fixed it. Could you elaborate a bit on this?
I'm just running this in an `oven/bun` Docker container in the /app directory. So there don't seem to be a lot of intermediary directories.

**Comment by 0x00ahmad** [comment]
I have already elaborated in my prior comment on how I fixed the issue on my system :^)

In your case, it would help if you could share a stack trace of the error, as currently; I cannot provide further hints as to what the issue could be on your end

**Comment by daanlenaerts** [comment]
@0x00ahmad In my case I was able to solve this by adding an empty Puppeteer configuration file. I noticed, however, that there is no default Chromium download happening either when Puppeteer is installed through Bun. That's another issue though.

**Comment by 0x00ahmad** [comment]
Hmm I see. 

Yes I can't say much anything about the default chromium install as I provide my own chromium source path to puppeteer everytime I use it.

**Comment by RiskyMH** [comment]
We've invested a ton of time into making Bun more reliable over the last year. I'm having a really hard time reproducing this. If you're still running into this issue, please let me know and I'll re-open this
