### ISSUE TITLE
TensorFlow.js error: Invalid napi_status

### ISSUE THREAD

**Issue by itsyoboieltr** [oven-sh/bun#3618]
### What version of Bun is running?

0.6.14

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

1. bun init -y
2. bun install @tensorflow/tfjs-node
3. update index.ts with simple TensorFlow.js code example

index.ts
```
import * as tf from '@tensorflow/tfjs-node';

const model = tf.sequential({
  layers: [
    tf.layers.dense({ units: 128, activation: 'relu', inputShape: [1] }),
    tf.layers.dense({ units: 3 }),
    tf.layers.softmax(),
  ],
});

model.compile({
  optimizer: 'adam',
  loss: 'categoricalCrossentropy',
  metrics: ['categoricalAccuracy'],
});

const result = model.predict(tf.tensor([0]));
if (Array.isArray(result)) throw new Error('Expected a single tensor');
const prediction = await result.data();

console.log(prediction);
```

4. bun run index.ts

```
56 | var bindingPath = binary.find(path.resolve(path.join(__dirname, '/../package.json')));
57 | // Check if the node native addon module exists.
58 | // tslint:disable-next-line:no-require-imports
59 | var fs = require('fs');
60 | if (!fs.existsSync(bindingPath)) {
61 |     throw new Error("The Node.js native addon module (tfjs_binding.node) can not " +
              ^
error: The Node.js native addon module (tfjs_binding.node) can not be found at path: {path-to-project-folder}/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node. 
Please run command 'npm rebuild @tensorflow/tfjs-node --build-addon-from-source' to rebuild the native addon module. 
If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue.
      at {path-to-project-folder}/node_modules/@tensorflow/tfjs-node/dist/index.js:61:10
      at globalThis ({path-to-project-folder}/node_modules/@tensorflow/tfjs-node/dist/index.js:93:59)
```

5. npm rebuild @tensorflow/tfjs-node --build-addon-from-source (according to error message instructions)

```
rebuilt dependencies successfully
```

6. bun run index.ts

```
247 |         var info = this.tensorMap.get(dataId);
248 |         if (info.values != null) {
249 |             return info.values;
250 |         }
251 |         else {
252 |             return this.binding.tensorDataSync(info.id);
                       ^
error: Invalid napi_status: 

      at {path-to-project-folder}/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:252:19
      at {path-to-project-folder}/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:239:38
      at step ({path-to-project-folder}/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:64:17)
      at {path-to-project-folder}/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:45:52
      at {path-to-project-folder}/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:39:8
      at {path-to-project-folder}/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:35:11
      at {path-to-project-folder}/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:237:15
      at {path-to-project-folder}/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:5241:15
```

7. npm install -D ts-node

8. npx ts-node-esm index.ts 

Expected output:

```
Float32Array(3) [
  0.3333333432674408,
  0.3333333432674408,
  0.3333333432674408
]
```

### What is the expected behavior?

```
Float32Array(3) [
  0.3333333432674408,
  0.3333333432674408,
  0.3333333432674408
]
```

### What do you see instead?

```
247 |         var info = this.tensorMap.get(dataId);
248 |         if (info.values != null) {
249 |             return info.values;
250 |         }
251 |         else {
252 |             return this.binding.tensorDataSync(info.id);
                       ^
error: Invalid napi_status: 

      at {path-to-project-folder}/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:252:19
      at {path-to-project-folder}/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:239:38
      at step ({path-to-project-folder}/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:64:17)
      at {path-to-project-folder}/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:45:52
      at {path-to-project-folder}/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:39:8
      at {path-to-project-folder}/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:35:11
      at {path-to-project-folder}/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:237:15
      at {path-to-project-folder}/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:5241:15
```

### Additional information

The tfjs-node package uses the [node-gyp](https://github.com/nodejs/node-gyp) package to handle cross-compiling the C++ code required to bind TensorFlow to Node.js. 
Source: https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md

**Comment by Jarred-Sumner** [comment]
Thank you. The thrown error regarding `napi_status` is a bug in our napi implementation. Not exactly sure where yet.

**Comment by asilvas** [comment]
confirmed still in 0.7.1. sub'd

**Comment by itsyoboieltr** [comment]
Confirmed still in 0.7.3. Is this on the roadmap to fix until 1.0? @Jarred-Sumner

**Comment by itsyoboieltr** [comment]
Confirmed for 0.8 too

**Comment by MathieuNls** [comment]
Confirmed in 1.0 too.

**Comment by peacefulotter** [comment]
Any news on this please? @Jarred-Sumner

**Comment by xrehpicx** [comment]
any work arounds for now?

**Comment by itsyoboieltr** [comment]
Sadly the only current workaround is using Node. It would be great if this could be supported, I can't wait personally to use Bun for my machine learning projects! @Jarred-Sumner

**Comment by peacefulotter** [comment]
> Sadly the only current workaround is using Node. It would be great if this could be supported, I can't wait personally to use Bun for my machine learning projects! @Jarred-Sumner 

Would love to use it for ML as well, and I think it's quite important considering ML in js is growing rapidly these days

**Comment by Jarred-Sumner** [comment]
This PR fixes the issue https://github.com/oven-sh/bun/pull/7311

<img width="726" alt="image" src="https://github.com/oven-sh/bun/assets/709451/10c52141-98f6-4e8c-a717-3930146fd4bc">
