### ISSUE TITLE
`new Buffer.alloc(n)` does not work (Breaks `form-data` package)

### ISSUE THREAD

**Issue by Wattville** [oven-sh/bun#3638]
### What version of Bun is running?

0.6.13

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

```
const form = new FormData();

form.append('my_buffer', Buffer.from([0x4a, 0x42, 0x20, 0x52, 0x6f, 0x63, 0x6b, 0x73]));
```

from https://www.npmjs.com/package/form-data

### What is the expected behavior?

appends a buffer to a form

### What do you see instead?

```
 
318 |   return this._boundary;
319 | };
320 |
321 | FormData.prototype.getBuffer = function() {
322 |   var dataBuffer = new Buffer.alloc( 0 );
                       ^
TypeError: function is not a constructor (evaluating 'new Buffer.alloc(0)')
      at /home/watty/bun-projects/node_modules/form-data/lib/form_data.js:322:19
      at /home/watty/bun-projects/upload-asset-functions/uploadAsset.ts:35:20
      at uploadAsset (/home/watty/bun-projects/upload-asset-functions/uploadAsset.ts:7:4)
      at /home/watty/bun-project/main-functions/uploadAssets.ts:233:43
```

**Comment by wzulfikar** [comment]
Encountered the same issue. It still work without constructor. For my case, I had the issue when using `Buffer.from`.

Works in `node`, doesn't work in `bun repl`:

![image](https://github.com/oven-sh/bun/assets/7823011/add1b443-1a36-4188-86f2-17e4f63d649f)

```ts
Buffer.from([0x48, 0x65, 0x6C, 0x6C, 0x6F]) // Works in both node / bun
new Buffer.from([0x48, 0x65, 0x6C, 0x6C, 0x6F]) // Works in node but not bun
```
