### ISSUE TITLE
Lambda build-layer error: stream.getWindowSize is not a function

### ISSUE THREAD

**Issue by MeStrak** [oven-sh/bun#3646]
### What version of Bun is running?

0.6.14

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Running the commands below will try to build, but generates the error message instead:

```bash
git clone git@github.com:oven-sh/bun.git- Clone bun repo
cd bun/packages/bun-lambda
bun run build-layer
```

### What is the expected behavior?

The bun-lambda should be built and .zip file generated.

### What do you see instead?

Build is not completed and the error below is shown:

```bash
mestrak@strak bun-lambda % bun run build-layer -- \
  --arch x64 \
  --release canary \
  --output /path/to/layer.zip
$ bun scripts/build-layer.ts --arch x64 --release canary --output /path/to/layer.zip
4 | const settings_1 = require("./settings");
5 | function termwidth(stream) {
6 |     if (!stream.isTTY) {
7 |         return 80;
8 |     }
9 |     const width = stream.getWindowSize()[0];
                      ^
TypeError: stream.getWindowSize is not a function. (In 'stream.getWindowSize()', 'stream.getWindowSize' is undefined)
      at termwidth (/Users/mestrak/dev/bun/packages/bun-lambda/node_modules/@oclif/core/lib/screen.js:9:18)
      at /Users/mestrak/dev/bun/packages/bun-lambda/node_modules/@oclif/core/lib/screen.js:19:34
      at globalThis (/Users/mestrak/dev/bun/packages/bun-lambda/node_modules/@oclif/core/lib/screen.js:20:58)
      at /Users/mestrak/dev/bun/packages/bun-lambda/node_modules/@oclif/core/lib/errors/errors/pretty-print.js:6:6
      at globalThis (/Users/mestrak/dev/bun/packages/bun-lambda/node_modules/@oclif/core/lib/errors/errors/pretty-print.js:48:18)
      at /Users/mestrak/dev/bun/packages/bun-lambda/node_modules/@oclif/core/lib/errors/handle.js:7:6
error: script "build-layer" exited with code 1 (SIGHUP)
```

### Additional information

I also noticed someone mention this problem here: https://github.com/oven-sh/bun/issues/2712, but as the other issue has been labelled as docs and was not created to report this specific bug I've created this issue.

I originally ran this with bun v0.6.5, then updated to 0.6.14 to see if it resolved the issue. I had slightly different error text with 0.6.5, including below for completeness.

```bash
mestrak@strak bun-lambda % bun run build-layer -- \
  --arch x64 \
  --release canary \
  --output /path/to/layer.zip
$ bun scripts/build-layer.ts --arch x64 --release canary --output /path/to/layer.zip
1 | "use strict";
2 | Object.defineProperty(exports, "__esModule", { value: true });
3 | exports.execute = exports.ux = exports.flush = exports.settings = exports.toConfiguredId = exports.toStandardizedId = exports.tsPath = exports.toCached = exports.run = exports.Plugin = exports.Parser = exports.Interfaces = exports.HelpBase = exports.Help = exports.loadHelpClass = exports.Flags = exports.Errors = exports.Config = exports.CommandHelp = exports.Command = exports.Args = void 0;
4 | const semver = require("semver");
5 | const command_1 = require("./command");
          ^
TypeError: stream.getWindowSize is not a function. (In 'stream.getWindowSize()', 'stream.getWindowSize' is undefined) while parsing module "/Users/mestrak/dev/bun/packages/bun-lambda/node_modules/@oclif/core/lib/screen.js" while parsing module "/Users/mestrak/dev/bun/packages/bun-lambda/node_modules/@oclif/core/lib/errors/errors/pretty-print.js" while parsing module "/Users/mestrak/dev/bun/packages/bun-lambda/node_modules/@oclif/core/lib/errors/handle.js" while parsing module "/Users/mestrak/dev/bun/packages/bun-lambda/node_modules/@oclif/core/lib/errors/index.js" while parsing module "/Users/mestrak/dev/bun/packages/bun-lambda/node_modules/@oclif/core/lib/cli-ux/index.js" while parsing module "/Users/mestrak/dev/bun/packages/bun-lambda/node_modules/@oclif/core/lib/command.js"
      at /Users/mestrak/dev/bun/packages/bun-lambda/node_modules/@oclif/core/lib/index.js:5:6
      at (eval) (/Users/mestrak/dev/bun/packages/bun-lambda/node_modules/@oclif/core/lib/index.js:57:17)
error: script "build-layer" exited with code 1 (SIGHUP)
```

**Comment by Electroid** [comment]
Implemented in 728c8fdcdb4e9276a7bd0721bad3b5d0cbed67fa and will be available in the next release, v0.7, or now if you run: `bun upgrade --canary`
