### ISSUE TITLE
Huge Error for crypto.createCipheriv

### ISSUE THREAD

**Issue by vrn-dev** [oven-sh/bun#3781]
### What version of Bun is running?

0.70

### What platform is your computer?

Linux 6.2.6-76060206-generic x86_64 x86_64

### What steps can reproduce the bug?

```ts
const encrypt = async (data: string) => {
	const alg = 'aes-256-cbc';
	const initVector = env.IV as string;
	const securityKey = env.CRYPTO_SECRET as string;
	const cipher = createCipheriv(alg, securityKey, initVector);
	let encryptedData = cipher.update(data, 'utf-8', 'base64');
	encryptedData += cipher.final('base64');
	await write('license.hcx', encryptedData)
}
```

`bun run file.ts`

### What is the expected behavior?

Throwing a short readable error.

### What do you see instead?

```
[0.02ms] ".env"

1 | 
2 | Use Chrome, Firefox or Internet Explorer 11`)}var P=N0().Buffer,X=QQ;X&&X.getRandomValues?_.exports=C:_.exports=F;function C(z,T){if(z>k)throw new RangeError("requested too many random bytes");var H=P.allocUnsafe(z);if(z>0)if(z>j)for(var J=0;J<z;J+=j)X.getRandomValues(H.slice(J,J+j));else X.getRandomValues(H);return typeof T=="function"?process.nextTick(function(){T(null,H)}):H}}}),B0=S0({"node_modules/inherits/inherits_browser.js"(N,_){typeof Object.create=="function"?_.exports=function(j,k){k&&(j.super_=k,j.prototype=Object.create(k.prototype,{constructor:{value:j,enumerable:!1,writable:!0,configurable:!0}}))}:_.exports=function(j,k){if(k){j.super_=k;var F=function(){};F.prototype=k.prototype,j.prototype=new F,j.prototype.constructor=j}}}}),YQ=S0({"node_modules/hash-base/index.js"(N,_){var j=N0().Buffer,k=B0();function F(X,C){if(!j.isBuffer(X)&&typeof X!="string")throw new TypeError(C+" must be a string or a buffer")}function P(X){A$.Transform.call(this),this._block=j.allocUnsafe(X),this._blockSize=X,this._blockOffset=0,this._length=[0,0,0,0],this._finalized=!1}k(P,A$.Transform),P.prototype._transform=function(X,C,z){var T=null;try{this.update(X,C)}catch(H){T=H}z(T)},P.prototype._flush=function(X){var C=null;try{this.push(this.digest())}catch(z){C=z}X(C)},P.prototype.update=function(X,C){if(F(X,"Data"),this._finalized)throw new Error("Digest already called");j.isBuffer(X)||(X=j.from(X,C));for(var z=this._block,T=0;this._blockOffset+X.length-T>=this._blockSize;){for(var H=this._blockOffset;H<this._blockSize;)z[H++]=X[T++];this._update(),this._blockOffset=0}for(;T<X.length;)z[this._blockOffset++]=X[T++];for(var J=0,W=X.length*8;W>0;++J)this._length[J]+=W,W=this._length[J]/4294967296|0,W>0&&(this._length[J]-=4294967296*W);return this},P.prototype._update=function(){throw new Error("_update is not implemented")},P.prototype.digest=function(X){if(this._finalized)throw new Error("Digest already called");this._finalized=!0;var C=this._digest();X!==void 0&&(C=C.toString(X)),this._block.fill(0),this._blockOffset=0;for(var z=0;z<4;++z)this._length[z]=0;return C},P.prototype._digest=function(){throw new Error("_digest is not implemented")},_.exports=P}}),ZQ=S0({"node_modules/md5.js/index.js"(N,_){var j=B0(),k=YQ(),F=N0().Buffer,P=new Array(16);function X(){k.call(this,64),this._a=1732584193,this._b=4023233417,this._c=2562383102,this._d=271733878}j(X,k),X.prototype._update=function(){for(var W=P,D=0;D<16;++D)W[D]=this._block.readInt32LE(D*4);var E=this._a,R=this._b,M=this._c,v=this._d;E=z(E,R,M,v,W[0],3614090360,7),v=z(v,E,R,M,W[1],3905402710,12),M=z
  
**** About 800_000 more characters here ******

**** About 400 newlines at the end ****** 

^

RangeError: Invalid key length
 code: "ERR_CRYPTO_INVALID_KEYLEN"

      at W (node:crypto:2:106806)
      at xxx/license.ts:43:16
      at encrypt (xxx/license.ts:39:23)
      at xxx/license.ts:61:6
make: *** [Makefile:2: gen-license] Error 1
```

**Comment by nektro** [comment]
hiya! would love to get this fixed if it's still affecting you. do you have a more complete reproduction?

**Comment by Jarred-Sumner** [comment]
This error was fixed awhile ago. We truncate long source stacktraces nowadays. And usually we show the error from the user's code instead of the builtin
