### ISSUE TITLE
Implement `utils.forOwn`

### ISSUE THREAD

**Issue by danthegoodman1** [oven-sh/bun#3823]
### What version of Bun is running?

0.6.14

### What platform is your computer?

Darwin 22.5.0 x86_64 i386

### What steps can reproduce the bug?

```ts
import puppeteer from 'puppeteer-extra'
import StealthPlugin from 'puppeteer-extra-plugin-stealth'

puppeteer.use(StealthPlugin())
```

```
bun run index.ts                                                          1:58PM

22 | }
23 |
24 | function cloneObjectDeep(obj, instanceClone) {
25 |   if (utils.isObject(obj)) {
26 |     var res = {};
27 |     utils.forOwn(obj, function(obj, key) {
        ^
TypeError: utils.forOwn is not a function. (In 'utils.forOwn(obj, function(obj, key) {
        this[key] = cloneDeep(obj, instanceClone);
      }, res)', 'utils.forOwn' is undefined)
      at cloneObjectDeep (/Users/dangoodman/tangiaCode/testBunPupp/node_modules/merge-deep/node_modules/clone-deep/index.js:27:4)
      at cloneDeep (/Users/dangoodman/tangiaCode/testBunPupp/node_modules/merge-deep/node_modules/clone-deep/index.js:16:13)
      at mergeDeep (/Users/dangoodman/tangiaCode/testBunPupp/node_modules/merge-deep/index.js:19:15)
      at new PuppeteerExtraPlugin (/Users/dangoodman/tangiaCode/testBunPupp/node_modules/puppeteer-extra-plugin/dist/index.cjs.js:61:21)
      at new StealthPlugin (/Users/dangoodman/tangiaCode/testBunPupp/node_modules/puppeteer-extra-plugin-stealth/index.js:74:4)
      at defaultExport (/Users/dangoodman/tangiaCode/testBunPupp/node_modules/puppeteer-extra-plugin-stealth/index.js:172:52)
      at /Users/dangoodman/tangiaCode/testBunPupp/index.ts:4:14
```

### What is the expected behavior?

Import works like it does in NodeJS. I'm no JS modules expert, but this seems to be related to how the `utils` is imported and/or parsed.

### What do you see instead?

```
bun run index.ts                                                          1:58PM
22 | }
23 |
24 | function cloneObjectDeep(obj, instanceClone) {
25 |   if (utils.isObject(obj)) {
26 |     var res = {};
27 |     utils.forOwn(obj, function(obj, key) {
        ^
TypeError: utils.forOwn is not a function. (In 'utils.forOwn(obj, function(obj, key) {
        this[key] = cloneDeep(obj, instanceClone);
      }, res)', 'utils.forOwn' is undefined)
      at cloneObjectDeep (/Users/dangoodman/tangiaCode/testBunPupp/node_modules/merge-deep/node_modules/clone-deep/index.js:27:4)
      at cloneDeep (/Users/dangoodman/tangiaCode/testBunPupp/node_modules/merge-deep/node_modules/clone-deep/index.js:16:13)
      at mergeDeep (/Users/dangoodman/tangiaCode/testBunPupp/node_modules/merge-deep/index.js:19:15)
      at new PuppeteerExtraPlugin (/Users/dangoodman/tangiaCode/testBunPupp/node_modules/puppeteer-extra-plugin/dist/index.cjs.js:61:21)
      at new StealthPlugin (/Users/dangoodman/tangiaCode/testBunPupp/node_modules/puppeteer-extra-plugin-stealth/index.js:74:4)
      at defaultExport (/Users/dangoodman/tangiaCode/testBunPupp/node_modules/puppeteer-extra-plugin-stealth/index.js:172:52)
      at /Users/dangoodman/tangiaCode/testBunPupp/index.ts:4:14
```

### Additional information

Please let me know what other info I can collect to make this more clear!

**Comment by Hanaasagi** [comment]
Hey, maybe you can take a look at this https://github.com/berstend/puppeteer-extra/issues/690

**Comment by danthegoodman1** [comment]
Thanks @Hanaasagi , I had tried that before making the issue but maybe I need to try another version of `clone-deep` and `merge-deep`

**Comment by Hanaasagi** [comment]
I think I know why this code works fine in Node but throws an error in Bun.

In clone-deep package, https://github.com/jonschlinkert/clone-deep/blob/8ab50fb93db4eb9288a6a9b6042dbe3e9a1ac7fb/utils.js#L14

```
require('shallow-clone', 'clone');
require('kind-of', 'typeOf');
require('for-own');
```

Compared to other `require`, `require('for-own')` only pass one argument.


https://github.com/jonschlinkert/lazy-cache/blob/06265aa4a6750aae03e1814fbb740dde6311fb2b/index.js#L22C1-L22C1

```
  var proxy = function(mod, name) {
    name = name || camelcase(mod);

```

Here, the `name` is `undefined`, so it will use the value `camelcase(mod)`. However, in Bun and Node, the value of this `mod` is different.


We can run the following code to compare the results.

```JavaScript
function lazyCache(fn) {
  var proxy = function(mod, name) {
    console.log("name is", name, "mod is", mod);

    Object.defineProperty(proxy, name, {
      enumerable: true,
      configurable: true,
      get: getter,
    });

    function getter() { }
    return getter;
  };
  return proxy;
}

var utils = lazyCache(require);
require = utils;
require("for-own");

```

Output

```
# node
name is undefined mod is for-own

# Bun
name is undefined mod is /home/kumiko/zig/tmp/test_3823/node_modules/for-own/index.js
```

In Bun, `mod` is a full path, after `camelcase`, it will be `homeKumikoZigTmpTest3823NodeModulesForOwnIndexJs`. So we used the wrong value in `Object.defineProperty`


### Environment

- Bun 0.7.3
- yarn.lock

```
clone-deep@^0.2.4:
  version "0.2.4"
  resolved "https://registry.npmjs.org/clone-deep/-/clone-deep-0.2.4.tgz"
  integrity sha512-we+NuQo2DHhSl+DP6jlUiAhyAjBQrYnpOk15rN6c6JSPScjiCLh8IbSU+VTcph6YS3o7mASE8a0+gbZ7ChLpgg==
  dependencies:
    for-own "^0.1.3"
    is-plain-object "^2.0.1"
    kind-of "^3.0.2"
    lazy-cache "^1.0.3"
    shallow-clone "^0.1.2"

lazy-cache@^1.0.3:
  version "1.0.4"
  resolved "https://registry.npmjs.org/lazy-cache/-/lazy-cache-1.0.4.tgz"
  integrity sha512-RE2g0b5VGZsOCFOCgP7omTRYFqydmZkBwl5oNnQ1lDYC57uyO9KqNnNVxT7COSHTxrRCWVcAVOcbjk+tvh/rgQ==

```

**Comment by nick-kang** [comment]
Used `pnpm patch` to manually remove `merge-deep` usage. It looks like `this.default` is just an empty object, so maybe we don't even need the merge defaults?

Here's our patch file:

```patch
diff --git a/dist/index.cjs.js b/dist/index.cjs.js
index 4c86e3414196609aa3d7bac51b5c074f4e2cbf3e..0ca94f6e2e169dfe33a0f41f41c62e4fe253f757 100644
--- a/dist/index.cjs.js
+++ b/dist/index.cjs.js
@@ -12,7 +12,7 @@ function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'defau
 var debug = _interopDefault(require('debug'));
 
 /** @private */
-const merge = require('merge-deep');
+// const merge = require('merge-deep');
 /**
  * Base class for `puppeteer-extra` plugins.
  *
@@ -58,7 +58,7 @@ class PuppeteerExtraPlugin {
     constructor(opts) {
         this._debugBase = debug(`puppeteer-extra-plugin:base:${this.name}`);
         this._childClassMembers = [];
-        this._opts = merge(this.defaults, opts || {});
+        this._opts = {...this.defaults, ...(opts || {})} // merge(this.defaults, opts || {});
         this._debugBase('Initialized.');
     }
     /**
diff --git a/dist/index.esm.js b/dist/index.esm.js
index 2c62e9cfebc6ef4bac4d98c80fd950b3409bcc0b..5d3ef8f34c68ff718071b4631e95e5cb75607dc7 100644
--- a/dist/index.esm.js
+++ b/dist/index.esm.js
@@ -6,7 +6,7 @@
 import debug from 'debug';
 
 /** @private */
-const merge = require('merge-deep');
+// const merge = require('merge-deep');
 /**
  * Base class for `puppeteer-extra` plugins.
  *
@@ -52,7 +52,7 @@ class PuppeteerExtraPlugin {
     constructor(opts) {
         this._debugBase = debug(`puppeteer-extra-plugin:base:${this.name}`);
         this._childClassMembers = [];
-        this._opts = merge(this.defaults, opts || {});
+        this._opts = {...this.defaults, ...(opts || {})} // merge(this.defaults, opts || {});
         this._debugBase('Initialized.');
     }
     /**
diff --git a/dist/index.js b/dist/index.js
index d8ef6f4b3e118bb3f2460cb7874bbb0f1616884c..7dd9d471169b372d4527d723fac06a53adb04e29 100644
--- a/dist/index.js
+++ b/dist/index.js
@@ -6,7 +6,7 @@ Object.defineProperty(exports, "__esModule", { value: true });
 exports.PuppeteerExtraPlugin = void 0;
 const debug_1 = __importDefault(require("debug"));
 /** @private */
-const merge = require('merge-deep');
+// const merge = require('merge-deep');
 /**
  * Base class for `puppeteer-extra` plugins.
  *
@@ -52,7 +52,7 @@ class PuppeteerExtraPlugin {
     constructor(opts) {
         this._debugBase = (0, debug_1.default)(`puppeteer-extra-plugin:base:${this.name}`);
         this._childClassMembers = [];
-        this._opts = merge(this.defaults, opts || {});
+        this._opts = {...this.defaults, ...(opts || {})} // merge(this.defaults, opts || {});
         this._debugBase('Initialized.');
     }
     /**
```

**Comment by danthegoodman1** [comment]
That patch is great, but I’d much prefer to see it fixed as it’s part of the node compatibility promise.

**Comment by danthegoodman1** [comment]
Actually this seems to work fine now with 1.0.0

@Jarred-Sumner I don't want to prematurely close, but the example works without failure now:

```
➜  dangoodman: ~/testbun bun index.ts                                                                                                                7:54AM
➜  dangoodman: ~/testbun
```

Do you want to verify before I close?

**Comment by seanwessmith** [comment]
@danthegoodman1 can you try again on bun@1.0.2 its failing on my machine

bun run build/index.js
654 | 
655 | // node_modules/clone-deep/utils.js
656 | var require_utils = __commonJS((exports, module) => {
657 |   var utils = require_lazy_cache()(require);
658 |   var fn = require;
659 |   require = utils;
      ^
TypeError: Attempted to assign to readonly property.
      at /Users/sws/Documents/fun/test/bun-test/build/index.js:659:2
      at /Users/sws/Documents/fun/test/bun-test/build/index.js:17:71
      at /Users/sws/Documents/fun/test/bun-test/build/index.js:701:14
      at /Users/sws/Documents/fun/test/bun-test/build/index.js:17:71
      at /Users/sws/Documents/fun/test/bun-test/build/index.js:853:14
      at /Users/sws/Documents/fun/test/bun-test/build/index.js:17:71
      at /Users/sws/Documents/fun/test/bun-test/build/index.js:884:15
      at /Users/sws/Documents/fun/test/bun-test/build/index.js:17:71
      at /Users/sws/Documents/fun/test/bun-test/build/index.js:1021:33
      at /Users/sws/Documents/fun/test/bun-test/build/index.js:17:71

**Comment by jdalton** [comment]
Bun now produces the node output `name is undefined mod is for-own`.
