### ISSUE TITLE
Implement `module.parent` in CommonJS

### ISSUE THREAD

**Issue by hyuzea** [oven-sh/bun#3852]
### What version of Bun is running?

0.7.1

### What platform is your computer?

ubuntu 22.04

### What steps can reproduce the bug?

bun --bun nodemon ./bin/www

### What is the expected behavior?

No errors

### What do you see instead?
```
[0.04ms] ".env"
12 |   });
13 | }
14 | 
15 | function version(callback) {
16 |   // first find the package.json as this will be our root
17 |   var promise = findPackage(path.dirname(module.parent.filename))
                                            ^
TypeError: undefined is not an object (evaluating 'module.parent.filename')
      at version (/data/www/backend/node_modules/nodemon/lib/version.js:17:41)
      at pin (/data/www/backend/node_modules/nodemon/lib/version.js:10:9)
      at /data/www/backend/node_modules/nodemon/lib/config/index.js:81:4
      at normaliseRules (/data/www/backend/node_modules/nodemon/lib/config/load.js:161:2)
      at ready (/data/www/backend/node_modules/nodemon/lib/config/load.js:102:8)
      at /data/www/backend/node_modules/nodemon/lib/config/load.js:113:12
      at /data/www/backend/node_modules/nodemon/lib/config/load.js:145:6
```

### Additional information

example  the `module` and `parent` in node are
```js
{
  module: Module {
    id: '/data/www/backend/node_modules/nodemon/lib/version.js',
    path: '/data/www/backend/node_modules/nodemon/lib',
    exports: [Function: version] { pin: [Function: pin] },
    filename: '/data/www/backend/node_modules/nodemon/lib/version.js',
    loaded: true,
    children: [],
    paths: [
      // skipped...
    ]
  },


  parent: Module {
    id: '/data/www/backend/node_modules/nodemon/lib/config/index.js',
    path: '/data/www/backend/node_modules/nodemon/lib/config',
    exports: {
      //skipped...
    },
    filename: '/data/www/backend/node_modules/nodemon/lib/config/index.js',
    loaded: true,
    children: [
      //skipped...
    ],
    paths: [
      //skipped...
    ]
  }
}
```

**Comment by jwoo0122** [comment]
This is required to (naively) use yarn pnp, cause it relies on parent object. Related: #3124
