### ISSUE TITLE
`touch` module not working / `import('constants')` incorrect

### ISSUE THREAD

**Issue by vjpr** [oven-sh/bun#3863]
### What version of Bun is running?

0.7.1

### What steps can reproduce the bug?

```
import touch from 'touch'

// A non-existent file.
touch('/tmp/blah1')
```

### What is the expected behavior?

No error.

### What do you see instead?

```
$ bun touch.js

2 | import {default as default2} from "node:fs/promises";
3 | import * as Stream from "node:stream";
4 | var callbackify = function(fsFunction, args) {
5 |   try {
6 |
7 |     const result = fsFunction.apply(fs, args.slice(0, args.length - 1)), callback = args[args.length - 1];
                      ^
ENOENT: No such file or directory
   path: "/tmp/blah1"
 syscall: "open"
   errno: -2

      at callbackify (node:fs:7:19)
      at open2 (node:fs:105:2)
      at open (/Users/Vaughan/dev/scratch/bun-readable-stream/node_modules/.pnpm/touch@3.1.0/node_modules/touch/index.js:100:4)
      at new Touch (/Users/Vaughan/dev/scratch/bun-readable-stream/node_modules/.pnpm/touch@3.1.0/node_modules/touch/index.js:82:6)
      at /Users/Vaughan/dev/scratch/bun-readable-stream/node_modules/.pnpm/touch@3.1.0/node_modules/touch/index.js:12:4
      at /Users/Vaughan/dev/scratch/bun-readable-stream/node_modules/.pnpm/touch@3.1.0/node_modules/touch/index.js:11:12
      at /Users/Vaughan/dev/scratch/bun-readable-stream/touch.js:3:0
```

### Additional information

https://nodejs.org/api/fs.html#file-open-constants
https://nodejs.org/api/fs.html#file-system-flags

```
        console.log('this.path', this.path, this.oflags)
        fs2.open(this.path, this.oflags, (er, fd) => this.onopen(er, fd));
```

```
this.path /Users/Vaughan/dev-mono/thirtyfive/_tmp_35045_0ec9956cac29823c5aa5cef42b891b53 66
```

https://man7.org/linux/man-pages/man2/open.2.html:

> In addition, zero or more file creation flags and file status
>       flags can be bitwise-or'd in flags.  The file creation flags are
>       O_CLOEXEC, O_CREAT, O_DIRECTORY, O_EXCL, O_NOCTTY, O_NOFOLLOW,
>       O_TMPFILE, and O_TRUNC.

**Comment by vjpr** [comment]
# Cause

```
import fs from 'fs'
import constants from 'constants'

const flags = constants.O_CREAT | constants.O_RDWR
console.log({flags})

fs.open('/tmp/blah4', flags, (e, fd) => {
  console.log(e, fd)
})
```

## Node

```
{ flags: 514 }
```

## Bun

```
{ flags: 66 }
```

**Comment by vjpr** [comment]
<img width="1603" alt="Screenshot 2023-07-28 at 3 54 01 pm" src="https://github.com/oven-sh/bun/assets/281413/99f9d9d5-9475-4505-81eb-571f37b64669">

Constants are all different.
