### ISSUE TITLE
Private key signing errors; private key string is prepended the letter 'n' on every line

### ISSUE THREAD

**Issue by chenglou** [oven-sh/bun#3911]
### What version of Bun is running?

0.7.2 (canary)

### What platform is your computer?

macOS

### What steps can reproduce the bug?

See below. I'm kinda positive there's some line breaking escaping issue going on here

### What is the expected behavior?

Successful key signing

### What do you see instead?

<img width="107" alt="Screenshot 2023-07-31 at 08 05 22" src="https://github.com/oven-sh/bun/assets/1909539/782b1f9d-ef67-4a17-b5e0-2c9baf5b5a34">

Stack trace:

```
- error Error: error:0908F066:PEM routines:get_header_and_data:bad end line
    at Sign.sign (node:internal/crypto/sig:131:29)
    at Object.sign (/Users/chenglou/github/gallery/node_modules/jwa/index.js:153:45)
    at Object.jwsSign [as sign] (/Users/chenglou/github/gallery/node_modules/jws/lib/sign-stream.js:32:24)
    at GoogleToken.requestToken (/Users/chenglou/github/gallery/node_modules/gtoken/build/src/index.js:232:31)
    at GoogleToken.getTokenAsyncInner (/Users/chenglou/github/gallery/node_modules/gtoken/build/src/index.js:166:21)
    at GoogleToken.getTokenAsync (/Users/chenglou/github/gallery/node_modules/gtoken/build/src/index.js:145:55)
    at GoogleToken.getToken (/Users/chenglou/github/gallery/node_modules/gtoken/build/src/index.js:97:21)
    at JWT.refreshTokenNoCache (/Users/chenglou/github/gallery/node_modules/google-auth-library/build/src/auth/jwtclient.js:172:36)
    at JWT.refreshToken (/Users/chenglou/github/gallery/node_modules/google-auth-library/build/src/auth/oauth2client.js:153:24)
    at JWT.getRequestMetadataAsync (/Users/chenglou/github/gallery/node_modules/google-auth-library/build/src/auth/oauth2client.js:298:28)
    at JWT.getRequestMetadataAsync (/Users/chenglou/github/gallery/node_modules/google-auth-library/build/src/auth/jwtclient.js:94:26)
    at JWT.getRequestHeaders (/Users/chenglou/github/gallery/node_modules/google-auth-library/build/src/auth/oauth2client.js:261:37)
    at GoogleAuth.authorizeRequest (/Users/chenglou/github/gallery/node_modules/google-auth-library/build/src/auth/googleauth.js:666:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: undefined
```

**Comment by cirospaciari** [comment]
Thanks for reporting, can you tell me more about how you did setup the key file reading?

I did this simple testing with, fs, import, and require and got a success message:

```js
import { JWT } from "google-auth-library";
import fs from "fs";
const keys = JSON.parse(fs.readFileSync("keys.json"));
// import keys from "./keys.json"
// const keys = require("./keys.json");

async function main() {
  const client = new JWT({
    email: keys.client_email,
    key: keys.private_key,
    scopes: ["https://www.googleapis.com/auth/cloud-platform"],
  });
  const url = `https://dns.googleapis.com/dns/v1/projects/${keys.project_id}`;
  const res = await client.request({ url });
  console.log("DNS Info:");
  console.log(res.data);
  const tokenInfo = await client.getTokenInfo(client.credentials.access_token);
  console.log(tokenInfo);
}
main().catch(console.error);
```

**Comment by chenglou** [comment]
Ah I got it. Bun's way of loading `.env.local` caused the escaping issue:

So this works in node:

```
KEY="a\nb"
```

Bun fails on KEY and ends up with `"a\nnb"`

Just checked that this repros on canary still

**Comment by cirospaciari** [comment]
I see, getting a fix for this soon, thanks for the reply.
