### ISSUE TITLE
subsequent runs cause seg fault or bad memory pointer

### ISSUE THREAD

**Issue by danthegoodman1** [oven-sh/bun#3931]
### What version of Bun is running?

0.7.1

### What platform is your computer?

Darwin 22.5.0 x86_64 i386

### What steps can reproduce the bug?

```ts
import { appendFile, readFile, readdir, unlink } from "fs/promises"
import { Node } from "./types"

const channel = "techsmith314"

const files = (await readdir(`${channel}/raw_data`)).filter((e) => e.endsWith(".json"))

let outFile = `${channel}/prepared_data.jsonl`

try {
  await unlink(outFile)
} catch (error) {}

let buffer = ""
for (const file of files) {
  const content = await readFile(`${channel}/raw_data/${file}`, "utf-8")
  const lines = content.split("\n").filter((l) => l !== "")
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]
    const node: Node = JSON.parse(line)
    const msg = `${node.commenter.displayName}: ${node.message.messageFragments.map((m) => m.text)}\n`
    buffer += msg
    if (buffer.length > 12_000) {
      await appendFile(outFile, JSON.stringify({t: buffer}) + "\n")
    }
    // pop out the first one
    buffer = buffer.split("\n").slice(1).join("\n")
  }
}

console.log("done!")
```

### What is the expected behavior?

Should work every time

### What do you see instead?

```
➜  dangoodman: ~/tangiaCode/ChatLLMs/chat bun run prepare.ts                                                  1:07PM
1 | import { appendFile, readFile, readdir, unlink } from "fs/promises"
2 | import { Node } from "./types"
3 |
4 | const channel = "techsmith314"
5 |
6 | const files = (await readdir(`${channel}/raw_data`)).filter((e) => e.endsWith(".json"))
                                                                                         ^
TypeError: e.endsWith is not a function. (In 'e.endsWith(".json")', 'e.endsWith' is 1.0028852895063658e-303)
      at /Users/dangoodman/tangiaCode/ChatLLMs/chat/prepare.ts:6:86
      at /Users/dangoodman/tangiaCode/ChatLLMs/chat/prepare.ts:6:6
➜  dangoodman: ~/tangiaCode/ChatLLMs/chat curl -fsSL https://bun.sh/install | bash                            1:07PM
######################################################################## 100.0%
bun was installed successfully to ~/.bun/bin/bun
Run 'bun --help' to get started
➜  dangoodman: ~/tangiaCode/ChatLLMs/chat bun run prepare.ts                                                  1:07PM
done!
➜  dangoodman: ~/tangiaCode/ChatLLMs/chat bun run prepare.ts                                                  1:07PM
1 | import { appendFile, readFile, readdir, unlink } from "fs/promises"
2 | import { Node } from "./types"
3 |
4 | const channel = "techsmith314"
5 |
6 | const files = (await readdir(`${channel}/raw_data`)).filter((e) => e.endsWith(".json"))
                                                                                         ^
TypeError: e.endsWith is not a function. (In 'e.endsWith(".json")', 'e.endsWith' is 1.0028852895063658e-303)
      at /Users/dangoodman/tangiaCode/ChatLLMs/chat/prepare.ts:6:86
      at /Users/dangoodman/tangiaCode/ChatLLMs/chat/prepare.ts:6:6
➜  dangoodman: ~/tangiaCode/ChatLLMs/chat                                                                     1:08PM
```

### Additional information

Don't need the types and file, just listing a folder with `x.y.json` files causes this.

If I reinstall, it works fine, but then subsequent executions fail... if I try to console.log the `e.endsWith` I get a seg fault and no other info

**Comment by danthegoodman1** [comment]
This didn't happen in 0.6.x

**Comment by Jarred-Sumner** [comment]
This is a very strange bug. 

I am able to reproduce it

**Comment by Jarred-Sumner** [comment]
More minimal reproduction:
```js
import { readdir } from "fs/promises";
const files = await readdir(`/tmp`, {});
console.log(files.map((a) => a));
```

The `.map` is important. I suspect when we fill the JSArray we are not filling it completely or we are putting a `0` in there

**Comment by danthegoodman1** [comment]
Thanks for that, I should have provided a more minimal example (was in a super rush)

**Comment by danthegoodman1** [comment]
what's weirder is that reinstalling fixes it almost every time (had one time where it didn't iirc)

**Comment by danthegoodman1** [comment]
make that 2 times... 3 times... (just got 5 times in a row)

**Comment by danthegoodman1** [comment]
Now that’s some god tier bug fixing speed
