### ISSUE TITLE
Installing postgraphile with the bun package manager causes it to fail

### ISSUE THREAD

**Issue by Malvolio** [oven-sh/bun#3999]
### What version of Bun is running?

0.7.2

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

With the following `package.json`
```
{
  "scripts": {
    "db": "postgraphile -c 'postgres:///postgres'"
  },
  "dependencies": {
    "postgraphile": "^4.13.0"
  }
}
```

run the following

```
bun install
bun run db
```

Then click on the graphiql link

### What is the expected behavior?

Expected the graphiql page to load normally in the browser, including the Docs and Explorer

### What do you see instead?

Error: Must provide document.
    at devAssert (/Users/john.doe/persrepo/node-phile/node_modules/graphql/jsutils/devAssert.js:12:11)
    at assertValidExecutionArguments (/Users/john.doe/persrepo/node-phile/node_modules/graphql/execution/execute.js:208:40)
    at Object.execute (/Users/john.doe/persrepo/node-phile/node_modules/graphql/execution/execute.js:112:3)
    at /Users/john.doe/persrepo/node-phile/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:720:61
    at /Users/john.doe/persrepo/node-phile/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:106:20
    at /Users/john.doe/persrepo/node-phile/node_modules/postgraphile/build/postgraphile/withPostGraphileContext.js:172:30
    at func (/Users/john.doe/persrepo/node-phile/node_modules/postgraphile/build/postgraphile/withPostGraphileContext.js:35:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/john.doe/persrepo/node-phile/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:711:34
    at async Promise.all (index 0)
An unexpected error occurred whilst processing 'graphqlRouteHandler'; this indicates a bug. The connection will be terminated.
TypeError: Cannot set properties of undefined (setting 'statusCode')
    at graphqlRouteHandler (/Users/john.doe/persrepo/node-phile/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:812:39)
```

Any query will fail, resulting in the same error.

### Additional information

It’s fine to use bun to *run* postgraphile, but if the package manager function from bun is used at all, postgraphile will no longer work in that directory.  Bizarre.

**Comment by Electroid** [comment]
This is likely because the postinstall script is not running, see #4959 for details. We will fix this, but closing this as a duplicate.

**Comment by Malvolio** [comment]
> This is likely because the postinstall script is not running, see #4959 for details. We will fix this, but closing this as a duplicate.

Thanks for the update Electroid.  Even if you don’t add default-trusted list, how about a command-line option, such as

`bun add postgraphile --trust`

**Comment by Jarred-Sumner** [comment]
I am not convinced this issue is related to postinstall scripts running. The stack trace does not mention any `.node` files missing.
