### ISSUE TITLE
 v0.7.2+ regression: TypeError: undefined is not an object (evaluating '__classPrivateFieldGet(this, _Client_fetch, "f").call')

### ISSUE THREAD

**Issue by azu** [oven-sh/bun#4029]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

- Reproduce Repository: https://github.com/azu/bun-notion-client-bug

```bash
git clone https://github.com/azu/bun-notion-client-bug
cd bun-notion-client-bug
bun install
bun run index.ts

334 |         };
335 |         if (bodyAsJsonString !== undefined) {
336 |             headers["content-type"] = "application/json";
337 |         }
338 |         try {
339 |             const response = await errors_1.RequestTimeoutError.rejectAfterTimeout(__classPrivateFieldGet(this, _Client_fetch, "f").call(this, url.toString(), {
                                                                                      ^
TypeError: undefined is not an object (evaluating '__classPrivateFieldGet(this, _Client_fetch, "f").call')
      at /Users/azu/ghq/github.com/azu/bun-notion-client-bug/node_modules/@notionhq/client/build/src/Client.js:339:83
      at request (/Users/azu/ghq/github.com/azu/bun-notion-client-bug/node_modules/@notionhq/client/build/src/Client.js:311:20)
      at /Users/azu/ghq/github.com/azu/bun-notion-client-bug/index.ts:3:23

```

- Reproduce Code:

`idnex.ts`:
```ts
import { Client } from "@notionhq/client";
const notion = new Client({ auth: "secret_dummy" });
const response = await notion.databases.query({
    database_id: "dummy",
    filter: {
        property: 'Name',
        title: {
            "equals": "test"
        }
    }
});
```

### What is the expected behavior?

Can fetch.

(This reproduce repo uses dummy api token for easy testing, so It will be "API token is invalid." error.)

### What do you see instead?

Throw an runtime error.
Probably, Its related with WeakMap.

```
334 |         };
335 |         if (bodyAsJsonString !== undefined) {
336 |             headers["content-type"] = "application/json";
337 |         }
338 |         try {
339 |             const response = await errors_1.RequestTimeoutError.rejectAfterTimeout(__classPrivateFieldGet(this, _Client_fetch, "f").call(this, url.toString(), {
                                                                                      ^
TypeError: undefined is not an object (evaluating '__classPrivateFieldGet(this, _Client_fetch, "f").call')
      at /Users/azu/ghq/github.com/azu/bun-notion-client-bug/node_modules/@notionhq/client/build/src/Client.js:339:83
      at request (/Users/azu/ghq/github.com/azu/bun-notion-client-bug/node_modules/@notionhq/client/build/src/Client.js:311:20)
      at /Users/azu/ghq/github.com/azu/bun-notion-client-bug/index.ts:3:23
```

https://github.com/azu/bun-notion-client-bug/blob/8bee7e1c53dd7ab5ed1b94a1305d8fde7b11ff9c/node_modules/%40notionhq/client/build/src/Client.js#L339
https://github.com/azu/bun-notion-client-bug/blob/8bee7e1c53dd7ab5ed1b94a1305d8fde7b11ff9c/node_modules/@notionhq/client/build/src/Client.js#L8-L11

This `__classPrivateFieldGet(...)` returns `undefined` and cause this error.

### Additional information

I've tested bun 0.7.1 and work fine

| Version | Result |
| --- | --- |
| 0.7.1 | 🟢 |
| 0.7.2 | 🟥 |
| 0.7.3 | 🟥 |

I think that this regression is introruded in bun 0.7.2.

**Comment by Jarred-Sumner** [comment]
@paperdave this most likely came from converting our builtins to CJS

**Comment by Jarred-Sumner** [comment]
Confirming the linked PR fixes it

<img width="1114" alt="image" src="https://github.com/oven-sh/bun/assets/709451/e6e99468-3847-4069-930c-2dd5f57d5719">
