### ISSUE TITLE
readline/promises and fs.createReadStream don't work as expected

### ISSUE THREAD

**Issue by janwilmake** [oven-sh/bun#4084]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

This runs well in node.js

```
import { createInterface } from "readline/promises";
import { fs } from "./fs.js";
/**
Function to read any file per line.

Resolves when close is called or at the end of the file.
 */
export const readFilePerLine = async (
  absoluteFilePath: string,
  withLine: (line: string, close: () => void) => void
) => {
  if (!fs.existsSync(absoluteFilePath)) return;
  const readStream = fs.createReadStream(absoluteFilePath, {
    encoding: "utf8",
  });

  console.log({ readStream });
  const lineInterface = createInterface(readStream);

  await new Promise<void>((resolve) => {
    const close = () => {
      lineInterface.close();
    };

    lineInterface.addListener("close", () => {
      // NB: this calls when you call close, as well as whenever
      resolve();
    });

    // TODO: how can I give the line number somehow?
    lineInterface.addListener("line", (line) => withLine(line, close));
  });

  lineInterface.removeAllListeners();
};
```

test:

```
import { readFilePerLine } from "./readFilePerLine.js";

readFilePerLine(
  "/Users/king/os/packages/control-fs/fs-util/src/readFilePerLine.test.ts",
  (line, clone) => {
    console.log(line);
  }
);
```

In bun I get this:

```
TypeError: undefined is not an object
      at node:stream:2:91738
      at new InterfaceConstructor (node:readline:1:41486)
      at new Interface2 (node:readline:1:48128)
      at new Interface2 (node:readline:1:96098)
      at createInterface (node:readline:1:97628)
      at /.../packages/control-fs/fs-util/src/readFilePerLine.ts:18:24
      at readFilePerLine (/.../packages/control-fs/fs-util/src/readFilePerLine.ts:9:2)
      at /.../packages/control-fs/fs-util/src/readFilePerLine.test.ts:3:0
```

### What is the expected behavior?

Works the same as node:readline

### What do you see instead?

Crash

**Comment by janwilmake** [comment]
Besides that, this should work fine:

```
  const readStream = fs.createReadStream(absoluteFilePath, "utf8");
```

But in bun it gives me this:

```
TypeError: Expected options to be an object
      at new ReadStream2 (node:fs:1:15402)
      at ReadStream2 (node:fs:1:14734)
      at new ReadStream (/.../node_modules/graceful-fs/graceful-fs.js:299:13)
      at createReadStream (/.../node_modules/graceful-fs/graceful-fs.js:341:11)
      at /.../packages/control-fs/fs-util/src/readFilePerLine.ts:13:21
      at readFilePerLine (/.../packages/control-fs/fs-util/src/readFilePerLine.ts:9:
```

Clearly fs.createReadStream is missing some overwrites

**Comment by janwilmake** [comment]
Update: I found that `import { createInterface } from "readline";` does the same as `import { createInterface } from "readline/promises";` and in bun it works.

So my problem is solved, but this isn't good behaviour I'd think

Have you considered all functions in "readline/promises"?

**Comment by Electroid** [comment]
Tested in Bun v1.0.7, and the error no longer occurs.
