### ISSUE TITLE
support typescript@5 decorator

### ISSUE THREAD

**Issue by sirenkovladd** [oven-sh/bun#4122]
### What version of Bun is running?

v0.7.3

### What platform is your computer?

Linux 5.19.0-50-generic x86_64 x86_64

### What steps can reproduce the bug?

package.json
```json
{
  "name": "bun-test",
  "module": "index.ts",
  "type": "commonjs",
  "author": "Sirenko Vlad",
  "devDependencies": {
    "@types/node": "^20.4.9",
    "bun-types": "latest"
  },
  "peerDependencies": {
    "typescript": "5"
  }
}
```

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "ES2022",
    "outDir": "./built"
  }
}
```

4122.ts
```ts
function wrap<This, T>(value: T, ctx: ClassFieldDecoratorContext<This, T>) {
  console.log('Wrapping', value, ctx);
  ctx.addInitializer(function W() {
    console.log('Initialized', this, value);
  });
};

class A {
  @wrap
  public a: number = 1;
}

const a = new A();
```

### What is the expected behavior?

```sh
❯ npx tsc && node built/4122.js         
Wrapping undefined {
  kind: 'field',
  name: 'a',
  static: false,
  private: false,
  access: { has: [Function: has], get: [Function: get], set: [Function: set] },
  addInitializer: [Function (anonymous)]
}
Initialized A {} undefined
```

### What do you see instead?

```sh
❯ bun 4122.ts 
Wrapping {} a
1 | function wrap<This, T>(value: T, ctx: ClassFieldDecoratorContext<This, T>) {
2 |   console.log('Wrapping', value, ctx);
3 |   ctx.addInitializer(function W() {
      ^
TypeError: ctx.addInitializer is not a function. (In 'ctx.addInitializer(function W() {
    console.log("Initialized", this, value);
  })', 'ctx.addInitializer' is undefined)
      at wrap (<cut>/4122.ts:3:2)
      at <cut>/4122.ts:10:9
```

### Additional information

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#decorators

**Comment by birkskyum** [comment]
Problems with typescript 5 `export type * from ""` as well. ([link](https://github.com/microsoft/TypeScript/pull/52217))

I get:

```
error: Expected "=" but found "from"

export type * from 'my-package';
```

**Comment by sirenkovladd** [comment]
This issue is with `decorator`, not `export`/`type`

**Comment by Jarred-Sumner** [comment]
> Problems with typescript 5 `export type * from ""` as well. ([link](https://github.com/microsoft/TypeScript/pull/52217))
> 
> I get:
> 
> ```
> error: Expected "=" but found "from"
> 
> export type * from 'my-package';
> ```

Fix for this https://github.com/oven-sh/bun/pull/4125

**Comment by aleksei-baryshnikov** [comment]
Is it being planned tbd?

**Comment by smartrusorg** [comment]
Waiting to support new typescript 5 decorators

**Comment by KaloyanGG** [comment]
I am waiting too, please fix this

**Comment by PodaruDragos** [comment]
seems like ts 5 decorators are working, but not as they should. second parameter passed to the decorators which is the context is always undefined.

**Comment by lkwr** [comment]
> seems like ts 5 decorators are working, but not as they should. second parameter passed to the decorators which is the context is always undefined.

i think thats because internally they are treated as experimental decorators (that behind the "experimentalDecorators" flag) which also has the target/class/function as the first parameter.

**Comment by jeremychone** [comment]
I can confirm that when using `Bun.build`, the decorators are transpiled with `__legacyDecorateClassTS`, which I assume are the TypeScript experimental decorators.

This happens when the `experimentalDecorators` is not set to true, so `tsc` will generate the newer style.

> Note: They are mostly incompatible, and in fact, the TypeScript implementation of the new decorator spec does shim the `class...` as I think it is required to have the right hook in the right place to follow the new spec while it is not yet implemented by JavaScript.

**Comment by Spenhouet** [comment]
Is there any workaround?

**Comment by jeremychone** [comment]
@Spenhouet, not that I know of, since Bun is generating this.

Interestingly, for my libraries, I rolled back from TS5 Decorators to TS4 experimental decorators. Here are the two main reasons:

- TS4 Experimental decorators do not require "class .." to be shimmed, and therefore, are less intrusive on the code. I think I encountered a corner case with the TS5 Decorators shimming where statics in classes were not behaving correctly. These issues are quite hard to investigate, and often, the only solution is to forego those lost features. This might be a corner case, but I'm not sure.

- Support for Bun.

Also, the decorators in the "can I use" matrix have no implementation plan, so we will have to do the shimming for many years to come (possibly for the next 5 years).

All things considered, while sticking with an old spec always feels odd, I think the net value of sticking with TS4 experimental decorators might be the better option. They are less intrusive in the code and offer better support.

Regardless, it would be great for Bun to follow the `tsconfig.json` `experimentalDecorators` setting and implement both, so we can revisit the decision at the user level.

**Comment by fredgrafia** [comment]
Same problem here.
```
TypeError: context.addInitializer is not a function.
(In 'context.addInitializer(contextInitializer)', 'context.addInitializer' is undefined)
```
While waiting I'm transpilling with **tsc** and using bun to run the generated .js files.

**Comment by PodaruDragos** [comment]
to be honest i think this should get more attention, but on the other hand even if @Jarred-Sumner fixes this, we still need to also add the `context.metadata` there since it's part of the new `ts` decorators added in `ts 5.2`. So i would assume it's better to wait for both.

**Comment by pokatomnik** [comment]
Deno contributor have implemented this in January btw.
They made experimental Typescript decorators optional and modern ones are enabled by default right now.

**Comment by jeremychone** [comment]
@pokatomnik Do you know if they shim js `class`. Last time I use the latest decorator with tsc, it change my `class ...` to `prototype ...`

**Comment by pokatomnik** [comment]
> @pokatomnik Do you know if they shim js `class`. Last time I use the latest decorator with tsc, it change my `class ...` to `prototype ...`

That's what typescript does. Not deno itself

**Comment by Autumnlight02** [comment]
experimentalDecorators should not be turned of! They're an old standard of that proposal, the new one is on by default!

**Comment by jeremychone** [comment]
I would also concur with @Autumnlight02 that the experimentalDecorators need to be preserved. It's quite involved to move from one to another, so preserving both is very useful.

**Comment by Jarred-Sumner** [comment]
Just to clear up ambiguity 

Bun will support both ES decorators and TS decorators. We just haven’t gotten around to implementing this in the transpiler yet (and JSC hasn’t in the engine yet)

**Comment by WillsterJohnson** [comment]
related; `accessor` keyword, which was introduced as part of stage 3, also doesn't work.

```
49 |   accessor foo = 1;
                ^
error: Expected ";" but found "foo"
    at /path/to/file.ts
```

**Comment by Atulin** [comment]
Seems like #6051 is related? Just ran into an issue with `accessor`s myself:

```
17 |    @state() accessor _loading: boolean;
                        ^
error: Expected ";" but found "_loading"
    at G:\MyProject\src-webcomponents\quote-box.ts:17:20
17 |    @state() accessor _loading: boolean;
                                ^
error: Expected identifier but found ":"
    at G:\MyProject\src-webcomponents\quote-box.ts:17:28
18 |    @state() accessor _quote: Quote;
                        ^
error: Expected ";" but found "_quote"
    at G:\MyProject\src-webcomponents\quote-box.ts:18:20
18 |    @state() accessor _quote: Quote;
                              ^
error: Expected identifier but found ":"
    at G:\MyProject\src-webcomponents\quote-box.ts:18:26
```

when running a simple build script:

```ts
import { Glob } from "bun";

const glob = new Glob("{src,src-webcomponents}/**/*.{ts,js}");

const files = [];
for await (const file of glob.scan()) {
	files.push(file);
}

const result = await Bun.build({
	entrypoints: files,
	outdir: "./.build",
	splitting: true,
	minify: true,
});

if (!result.success) {
	for (const message of result.logs) {
		console.error(message);
	}
}
```

**Comment by andeeplus** [comment]
Anyone planning to use or implement stage 3 decorators will find this link very useful. As you can see, no one has found a bulletproof solution yet, but esbuild and babel seem to work smoothly for most cases. 

https://github.com/evanw/decorator-tests

Considering that [Bun's bundler API is inspired heavily by esbuild Migrating to Bun's bundler from esbuild should be relatively painless](https://bun.sh/docs/bundler/vs-esbuild), addressing this gap would be a significant step and would definitely put Bun in a favorable position for those seeking this feature.

**Comment by pauliesnug** [comment]
bump?

**Comment by pauliesnug** [comment]
> Anyone planning to use or implement stage 3 decorators will find this link very useful. As you can see, no one has found a bulletproof solution yet, but esbuild and babel seem to work smoothly for most cases.
> 
> https://github.com/evanw/decorator-tests
> 
> Considering that [Bun's bundler API is inspired heavily by esbuild Migrating to Bun's bundler from esbuild should be relatively painless](https://bun.sh/docs/bundler/vs-esbuild), addressing this gap would be a significant step and would definitely put Bun in a favorable position for those seeking this feature.

deno has native support for it as far as i know as well, no hacky layers involved

**Comment by andeeplus** [comment]
> deno has native support for it as far as i know as well, no hacky layers involved

To my knowledge, even though we might not notice it, it seems that Deno utilizes SWC behind the scenes.

https://choubey.gitbook.io/internals-of-deno/architecture/tsc

**Comment by Kleywalker** [comment]
I am going to develop a framework that will rely heavily on decorators. I would prefer to use the latest state (3) of the art technology. 

I really would like this feature to be implemented soon! :)

There is a nice article that shows how to use the new decorators wis TS5.*: [TypeScript Decorators Stage 3: Technical Challenges and Tips for Overcoming Them | by Aude LELLOUCHE | Medium](https://medium.com/@aude.lellouche/typescript-decorators-stage-3-technical-challenges-and-tips-for-overcoming-them-8deed94a3de7)

Running the following example:
```typescript
@loggableClass()
class Decorated {
  public constructor() {
    console.log(`Decorated constructor called`);
  }

  @logged
  @loggableMethod("label")
  public methodDecorated(): void {
    console.log("Decorated method called");
  }
}

const decorated = new Decorated();
decorated.methodDecorated();

// decorators.TypeScript
export type Constructor = { new (...args: any[]): NonNullable<unknown> };
export type ConstructorParams<T extends Constructor> = ConstructorParameters<T>;
export type Context = {
  kind: string;
  name: string | symbol;
  access: {
    get?(): unknown;
    set?(value: unknown): void;
    has?(value: unknown): boolean;
  };
  private?: boolean;
  static?: boolean;
  addInitializer?(initializer: () => void): void;
};

export type ClassDecorator = <T extends Constructor>(
  target: T,
  context: Context
) => T | void;

export type Method = (...args: any[]) => any;

export function loggableClass(): any {
  return function <T extends Constructor>(constructor: T, context: Context): T {
    return class extends constructor {
      public constructor(...args: any[]) {
        super(...args);
        console.log(
          `Constructor ${constructor.name} has been decorated. It a ${String(
            context.name
          )}`,
          context
        );
      }
    };
  };
}

export function loggableMethod(label: string): Method {
  return <T extends Method>(value: T, context: Context): Method => {
    return function (this: any, ...args: any[]): T {
      console.log(
        `Method ${value.name} has been decorated`,
        context,
        args,
        label
      );
      return value.call(this, ...args) as unknown as T;
    };
  };
}

export function logged(original: any, context: any): any {
  function replacementMethod(this: any, ...args: any[]): any {
    console.log("LOG: Entering method.", context);
    const result = original.call(this, ...args);
    console.log("LOG: Exiting method.");
    return result;
  }
  return replacementMethod;
}
```

result in the following output: 
```sh
Decorated constructor called
42 |     return class extends constructor {
43 |       public constructor(...args: any[]) {
44 |         super(...args);
45 |         console.log(
46 |           `Constructor ${constructor.name} has been decorated. It a ${String(}
47 |             context.name
                 ^
TypeError: undefined is not an object (evaluating 'context.name')
      at new  (./index.ts:47:13)
      at ./index.ts:14:19
```

**Comment by Kleywalker** [comment]
Additional Information:
[Differences with Experimental Legacy Decorators | March 16th, 2023 | Announcing TypeScript 5.0](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#differences-with-experimental-legacy-decorators)

---

[NPM | reflect-metadata](https://www.npmjs.com/package/reflect-metadata)

> NOTE: Now that both [Decorators](https://github.com/tc39/proposal-decorators) and [Decorator Metadata](https://github.com/tc39/proposal-decorator-metadata) have achieved Stage 3 within TC39, the API proposed below is no longer being considered for standardization. However, this package will continue to support projects that leverage TypeScript's legacy --experimentalDecorators option as some projects may not be able to migrate to use standard decorators.

---

Metadata of the context is very necessary! :)

**Comment by rvion** [comment]
Any progress on native tc39 decorators ? it's blocking modern mobx usage with tc39 decorators amongst other things

**Comment by J4C0B3Y** [comment]
I have multiple parts of my code base that are waiting on bun's support for tc39 decorators,
support for these decorators should be kind of a high priority as many people are waiting.

**Comment by Atulin** [comment]
As a "workaround" I found myself just running Parcel from a Bun build script for the files that use decorators. Not a great solution, but gets the job done.

**Comment by rvion** [comment]
> As a "workaround" I found myself just running Rollup from a Bun build script for the files that use decorators. Not a great solution, but gets the job done.

is that automated ?
if so, would you mind sharing a bit more what you do ?
if not, is there a way to automate that in a handy way using bun `loaders` https://bun.sh/docs/bundler/loaders or some kind of similar api ? e.g. let bun automatically run a quick check on every file to see if theit contains decorators, and if so, transparently call rollup in the background ?

**Comment by Atulin** [comment]
Depends what you mean by "automated". I use it programmatically in a build script instead of `Bun.build()`

```ts
const compileAll = async () => {
	const files = [...new Glob(`${_source}/**/[!_]*.ts`).scanSync()];

	await using bundle = await rollup({
		input: files,
		output: {
			file: join(_dest, "components.js"),
			format: "esm",
			sourcemap: true,
		},
		plugins: [
			multi(),
			resolve(),
			!values.full && minifyHTML(),
			esbuild({
				tsconfig: join(_root, "..", "typescript", "tsconfig.json"),
				treeShaking: true,
				minify: !values.full,
				legalComments: "eof",
			}),
		],
	});

	await bundle.write({
		file: join(_dest, "components.js"),
		format: "umd",
		name: "components",
		sourcemap: true,
	});
};
```

**Comment by rvion** [comment]
@Atulin I made it fully transparent if you want:
also ping @Kleywalker , @J4C0B3Y , @fredgrafia , @Spenhouet , @jeremychone @DeniroBlack , @sirenkovladd 

- makes bun work like if it had `native decorator` support 🎉 
- single-file bun plugin you can add in your project
- you can make bun automatically load it by adding 3 lines in your `bunfig.toml` (see below)
- contains a super naive custom cache so it's actually fast (5x/10x faster than node+vitest) for my specific project
- allow you to swap between various transpiler to (babel(works), esbuild (works in run mode, not test), typescript (did not test it, debug it yourself :)) => easy to support more
- but let's be honest; **it's rather ugly**; really hope bun get decorator support soon. 🙏 

ping @Jarred-Sumner : a few bugs I found:

 - using `esbuild` in a bun plugin only works in `bun run`, not `bun test` (macos) => esbuild throw saying it has been disabled/killed (can't rememeber the actuall issue); sad 😢
 
 - changing how `.ts, .tsx` files are loaded break the --watch, both in `bun --watch` and `bun test --watch)
      - using virtual module as dependency does not work
      - had to resort to adding some fake dependency to an empty generated module + watching the src folder myself; sad 😢

### `bunfig.toml`

_makes the plugin be automatically applied both on `bun` and `bun test`_

```toml
preload = ["./bunPlugin.ts"]
[test]
preload = ["./bunPlugin.ts"]
```

### `.gitignore`

```.gitignore
bunPlugin.cache
bunPlugin.reload.ts
```

### `package.json`

if you use babel as your transpiler, I had to add those (probably @babel/core too 🤔 )
I'll probably switch to typescript later, but have some actual work to do first 🙈 

```
      "@babel/plugin-syntax-import-attributes": "^7.26.0",
      "@babel/preset-react": "^7.26.3",
      "@babel/preset-typescript": "^7.27.0",
      "@types/bun": "^1.2.8",
```

### `bunPlugin.ts` 

- 👉 change the regex to match your files containing decorators (or just all of your src/ folder like I do) 
    - (my regexp will not match any of your code; you need to see those lines when starting:)
    ```
    [bun] evaluating plugin module
    [bun] manually watching /Users/loco/dev/monoloco/src/
    [bun] setup took 7ms
    [bun] restoring module with 481 entries
    [bun] saving cache with 481 entries (spent 4.57ms transpiling)
    ```
- 👉 remove the `vitest` automatic conversion if you don't need it
- 👉 if you prefer to use `esbuild` or `typescript` rather than `babel`, change the const to pick an other transpiler
     - tested `esbuild`, but it only works in 

```ts
import * as babel from '@babel/core'
import { plugin } from 'bun'
import chalk from 'chalk'
import fs from 'fs'
import debounce from 'lodash/debounce'

// 0. minor setup
let totalTimeSpentTranspiling = 0
const RELOAD_HACK_FILENAME = 'bunPlugin.reload.ts'

const startSetup = Date.now()
const log = (str: string): void => console.log(chalk.dim(`[bun] ${str}`))
log(`evaluating plugin module`)

plugin({
   name: 'typescript-with-native-decorators',
   setup(build): void {
      // 1. watch files manually since --watch is broken when using bun plugin 🥲
      const folderToWatch = import.meta.dir + '/src/'
      log(`manually watching ${folderToWatch}`)
      const watchFileSet = new Set<string | null>()
      fs.watch(folderToWatch, { recursive: true }, (event, filename) => {
         const needestart = watchFileSet.has(filename)
         log(`file ${filename} changed (in set: ${watchFileSet.has(filename)})`) // ${[...watchFileSet.values()]}
         if (needestart) void Bun.file(`./${RELOAD_HACK_FILENAME}`).write(`// '${Math.random()})\n`)
      })

      // 2. change how .ts and .tsx files are loaded
      log(`setup took ${Date.now() - startSetup}ms`)
      const filter = /.*monoloco\/src.*\.(ts|tsx)$/
      build.onLoad({ filter }, async (args): Promise<{ loader: 'js'; contents: string }> => {
         try {
            watchFileSet.add(args.path.replace(folderToWatch, ''))
            const codeTs = await Bun.file(args.path).text()
            const startTranspiling = performance.now()
            let codeJS = await transpileFile(args.path, codeTs)

            // 3. inject a dependency on a file that do NOT go though the plugin
            if (!codeJS.startsWith(`import '${RELOAD_HACK_FILENAME}'`))
               codeJS = `import '${RELOAD_HACK_FILENAME}'\n${codeJS}`

            totalTimeSpentTranspiling += performance.now() - startTranspiling
            addToCache(codeTs, codeJS)
            return { loader: 'js', contents: codeJS }
         } catch (e) {
            console.log(`[🔴] `, e)
            return { contents: '', loader: 'js' }
         }
      })
   },
})

// 4. cache system
const oldCache: Map<string, string> = (await Bun.file('./bunPlugin.cache').exists())
   ? new Map(JSON.parse((await Bun.file('./bunPlugin.cache').text()) || '[]'))
   : new Map()

const cache = new Map<string, string>()
log(`restoring module with ${oldCache.size} entries`)

export const getFromCache = (content: string): string | undefined => {
   if (cache.has(content)) return cache.get(content)
   if (oldCache.has(content)) {
      const value = oldCache.get(content)
      if (value) cache.set(content, value)
      return value
   }
   return
}
const saveCacheImpl = debounce(() => {
   log(`saving cache with ${cache.size} entries (spent ${totalTimeSpentTranspiling.toFixed(2)}ms transpiling)`) // prettier-ignore
   void Bun.file('./bunPlugin.cache').write(JSON.stringify([...cache.entries()]))
}, 50)

export const addToCache = (codeTS: string, codeJS: string): void => {
   cache.set(codeTS, codeJS)
   saveCacheImpl()
}

const MODE: 'babel' | 'esbuild' | 'typescript' = 'babel'

async function transpileFile(name: string, codeTs: string): Promise<string> {
   // 1. try to return the cached version
   const cache = getFromCache(codeTs)
   if (cache) return cache

   // or transpile a new
   const codeJs = await transpileFileForReal(name, codeTs)
   addToCache(codeTs, codeJs)
   return codeJs
}

async function transpileFileForReal(name: string, codeTS: string): Promise<string> {
   if (MODE === 'babel') return transpileFileWithBabel(name, codeTS)
   if (MODE === 'esbuild') return transpileFileWithEsbuild(name, codeTS)
   if (MODE === 'typescript') return transpileFileWithTypescript(name, codeTS)
   throw new Error(`MODE ${MODE} is ont supported`)
}

// alt 1. babel  -------------------------------------------------------------------------
async function transpileFileWithBabel(name: string, codeTS: string): Promise<string> {
   const res = await babel.transformAsync(codeTS, {
      filename: name,
      plugins: [
         ['@babel/plugin-proposal-decorators', { version: '2023-05' }],
         '@babel/plugin-syntax-import-attributes',
      ],
      presets: [
         ['@babel/preset-typescript', { allowDeclareFields: true }],
         ['@babel/preset-react', { runtime: 'automatic' }],
      ],
   })
   const codeJS = res?.code ?? ''
   return name.endsWith('.test.ts') || name.endsWith('.test.tsx')
      ? autoConvertVitestToBunTest(codeJS)
      : codeJS
}

// alt 2. esbuild ------------------------------------------------------------------------
async function transpileFileWithEsbuild(name: string, file: string): Promise<string> {
   const esbuild = (await import('esbuild')).default
   const result = await esbuild.transform(file, {
      loader: 'ts',
      target: 'chrome110',
   })
   return result.code
}

// alt 3. esbuild ------------------------------------------------------------------------
async function transpileFileWithTypescript(name: string, file: string): Promise<string> {
   const typescript = (await import('typescript')).default
   const codeJS = typescript.transpileModule(file, {
      compilerOptions: {
         module: typescript.ModuleKind.ESNext,
         target: typescript.ScriptTarget.ESNext,
         jsx: typescript.JsxEmit.React,
         decorators: true,
         importAttributes: true,
      },
   })
   return codeJS.outputText
}

// bonus for those who use vitest --------------------------------------------------------
function autoConvertVitestToBunTest(finalCode_: string): string {
   return (
      finalCode_
         .replaceAll(`from 'vitest'`, `from 'bun:test'`)
         .replaceAll('vitest.spyOn', `require('bun:test').spyOn`)
         .replaceAll('vitest.mock', `require('bun:test').mock`)
         .replaceAll('vi.spyOn', `require('bun:test').spyOn`)
         .replaceAll('vi.mock', `require('bun:test').mock`)
         // https://bun.sh/docs/test/mocks#restore-all-function-mocks-to-their-original-values-with-mock-restore
         .replaceAll('vitest.restoreAllMocks()', `require('bun:test').mock.restore()`)
   )
}
```

**Comment by rvion** [comment]
(also, warning to everyone using ['@babel/plugin-proposal-decorators', { version: '2023-05' }]
there is a completely ABSURD and hard to debug issue if you use the "type-only" `declare` keyword in classes with some hierarchy `class Sub extends Base  { declare foo: string }`). If you do so, decorators around getters on the base class will not work due to a weird parsing issue in babel 🤦🤦🤦. kinda unbelievable at first, but true. Lost a few hours to that in my mobx-heavy code; `@computed get myObservableValue() {...}`only works if I don't use `declare` in the class 🧨 )

**Comment by angelhdzmultimedia** [comment]
👋Any update? This is causing us hours of debugging, because for example I recently moved to bun for everything, 
and after hours of debugging, I realize I'm using bun and that it doesn't work with the new decorators yet, and replacing the command with `bunx tsx watch src/main.ts` works right away. With nuxt no issues because it uses rollup and esbuild and it works with new decorators (using `experimental.decorators` in `nuxt.config.ts`).

**Comment by alexhanga** [comment]
@instilled this Issue is about Stage 3 decorators, not a legacy.
