### ISSUE TITLE
Support Parcel

### ISSUE THREAD

**Issue by birkskyum** [oven-sh/bun#4142]
### What version of Bun is running?

0.7.4+78defe7a87226b5b10766e24fae458a62811dab2

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Make an index.html file:

```html
​<html>
  <head>
    <title>My First Parcel App</title>
  </head>
  <body>
    <h1>Hello, World!</h1>
  </body>
</html>
```

Run `bun --bun x parcel index.html`

### What is the expected behavior?

```zig
➜ bun --bun x parcel index.html 
Server running at http://localhost:1234
✨ Built in 2ms
```

This is the case if `--bun` flag is removed

### What do you see instead?

```zig

➜ bun --bun x parcel index.html
[bun] Warning: worker_threads.Worker option "execArgv" is not implemented.
dyld[63445]: missing symbol called
error: "parcel" exited with code 9 (SIGKILL)

```

### Additional information

Related to
- #4130 
- #4075

**Comment by birkskyum** [comment]
Now I get:

```sh
➜ bun --bun x parcel index.html
3592 |         // $FlowFixMe
3593 |         (0, ($parcel$interopDefault($5VgCY$fs))).statSync = (filename)=>{
3594 |             return this.fs.statSync(filename);
3595 |         };
3596 |         try {
3597 |             m.load(filePath);
                   ^
TypeError: m.load is not a function. (In 'm.load(filePath)', 'm.load' is undefined)
      at load (/private/tmp/parcel@latest--bunx/node_modules/@parcel/package-manager/lib/index.js:3597:13)
      at processTicksAndRejections (:61:77)

17 |   try {
18 |     binding = require('./build/Release/watcher.node');
19 |   } catch (err) {
20 |     try {
21 |       binding = require('./build/Debug/watcher.node');
22 |     } catch (err) {
                                                                                                                                                                                                                                                                                                                                        ^
error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-darwin-arm64. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.
      at /private/tmp/parcel@latest--bunx/node_modules/@parcel/watcher/index.js:22:324
      at anonymous (native:1:1)
      at /private/tmp/parcel@latest--bunx/node_modules/@parcel/fs/lib/index.js:7:5
      at anonymous (native:1:1)
      at /private/tmp/parcel@latest--bunx/node_modules/@parcel/package-manager/lib/index.js:10:5
      at anonymous (native:1:1)
      at /private/tmp/parcel@latest--bunx/node_modules/@parcel/core/lib/worker.js:63:1
      at anonymous (native:1:1)
      at /private/tmp/parcel@latest--bunx/node_modules/@parcel/workers/lib/child.js:108:32
      at childInit (/private/tmp/parcel@latest--bunx/node_modules/@parcel/workers/lib/child.js:107:25)
17 |   try {
18 |     binding = require('./build/Release/watcher.node');
19 |   } catch (err) {
20 |     try {
21 |       binding = require('./build/Debug/watcher.node');
22 |     } catch (err) {
```

**Comment by sarahkadar** [comment]
@birkskyum I might be wrong and can't test it right now, but you may need to add `@parcel/watcher` to `trustedDependencies` in your `package.json` because only the top 500 packages get their postinstall scripts ran automatically and my guess is that it may not be on that list.

**Comment by birkskyum** [comment]
@KTamas , thank you for the tip - I tried just now but I can't make it work.

**Comment by chdominguez** [comment]
Any news on this? I cannot seem to make parcel work when installed with bun.

**Comment by sarahkadar** [comment]
Yeah I'm still waiting on it as well.

**Comment by koddr** [comment]
The same problems with Bun `v1.1.7` and Parcel bundler `v2.12.0`:

- https://github.com/gowebly/gowebly/issues/71
- https://github.com/parcel-bundler/parcel/issues/9707

🙏

**Comment by jtenner** [comment]
I hit similar trouble using `bunx --bun parcel`

It just looks like a `napi` feature hasn't been implemented yet. Perhaps someone might be able to point me in the right direction to get this working?

It's blocking me from using bun at work with parcel.

Edit: I meant to say "point me in the right direction to help contribute to this issue..."

Might be time to learn some zig?

**Comment by jtenner** [comment]
Also, I wanted to point out that `@parcel/watch` requires the use of `detect-libc`.

This wouldn't normally be a problem but...

```ts
> await import("detect-libc")
Object [Module] {
  GLIBC: 'glibc',
  MUSL: 'musl',
  default: {
    GLIBC: 'glibc',
    MUSL: 'musl',
    family: [Function: family],
    familySync: [Function: familySync],
    isNonGlibcLinux: [Function: isNonGlibcLinux],
    isNonGlibcLinuxSync: [Function: isNonGlibcLinuxSync],
    version: [Function: version],
    versionSync: [Function: versionSync]
  },
  family: [Function: family],
  familySync: [Function: familySync],
  isNonGlibcLinux: [Function: isNonGlibcLinux],
  isNonGlibcLinuxSync: [Function: isNonGlibcLinuxSync],
  version: [Function: version],
  versionSync: [Function: versionSync]
}
```

This actually looks fine, and uses a function to find the libc family. However, parcel uses the `detect-libc` package which doesn't expect `family` to be a function.

```ts
let name = `@parcel/watcher-${process.platform}-${process.arch}`;
if (process.platform === 'linux') {
  const { MUSL, family } = require('detect-libc');
  if (family === MUSL) {
    name += '-musl';
  } else {
    name += '-glibc';
  }
}
```

As you can see here, `family` is a function and will never equal `MUSL`, and thus, we get some issues.

We can solve this problem by calling `await import("@parcel/watcher")` instead of using `import watcher from "@parcel/watcher"`, and I think this is unintended behavior.

**Comment by birkskyum** [comment]
Now getting:

```zig
➜ bun --bun x parcel index.html
3619 |                     (0, ($parcel$interopDefault($aniHR$module)))._extensions[".js"](m, filename);
3620 |                 };
3621 |             }
3622 |         }
3623 |         try {
3624 |             m.load(filePath);
                     ^
TypeError: m.load is not a function. (In 'm.load(filePath)', 'm.load' is undefined)
      at load (/private/tmp/bunx-501-parcel@latest/node_modules/@parcel/package-manager/lib/index.js:3624:15)

Error: symbol 'napi_register_module_v1' not found in native module. Is this a Node API (napi) module?
```

**Comment by jacobjuul** [comment]
seems to work for me if I just run it like this 
```bash
bun parcel index.html
```

**Comment by simnalamburt** [comment]
It works well in my environment as well

**Comment by birkskyum** [comment]
it's still breaking for me with: `bun --bun parcel index.html`

it the --bun flag isn't supplied, it's just using node

**Comment by simnalamburt** [comment]
Sorry, didn't know that. I could reproduce this issue.

Repo link: https://github.com/simnalamburt/parcel-practice/

<img width="1887" alt="Image" src="https://github.com/user-attachments/assets/b73043a5-b951-40c2-aafc-44328b8ee060" />

```console
❯ bun run build
$ parcel build --public-url './' src/index.html
428 |                     (0, ($parcel$interopDefault($i45p4$module)))._extensions['.js'](m, filename);
429 |                 };
430 |             }
431 |         }
432 |         try {
433 |             m.load(filePath);
                    ^
TypeError: m.load is not a function. (In 'm.load(filePath)', 'm.load' is undefined)
      at load (/Users/simnalamburt/personal/parcel-practice/node_modules/.pnpm/@parcel+package-manager@2.14.4_@parcel+core@2.14.4_@swc+helpers@0.5.15__@swc+helpers@0.5.15/node_modules/@parcel/package-manager/lib/index.js:433:15)

Error: symbol 'napi_register_module_v1' not found in native module. Is this a Node API (napi) module?


TypeError: symbol 'napi_register_module_v1' not found in native module. Is this a Node API (napi) module?
    at dlopen (unknown)
    at <anonymous> (/Users/simnalamburt/personal/parcel-practice/node_modules/.pnpm/@parcel+watcher@2.5.1/node_modules/@parcel/watcher/index.js:15:13)
    at anonymous (unknown)
    at <anonymous> (/Users/simnalamburt/personal/parcel-practice/node_modules/.pnpm/@parcel+fs@2.14.4_@parcel+core@2.14.4_@swc+helpers@0.5.15_/node_modules/@parcel/fs/lib/index.js:9:5)
    at anonymous (unknown)
    at <anonymous> (/Users/simnalamburt/personal/parcel-practice/node_modules/.pnpm/@parcel+package-manager@2.14.4_@parcel+core@2.14.4_@swc+helpers@0.5.15__@swc+helpers@0.5.15/node_modules/@parcel/package-manager/lib/index.js:6:5)
    at anonymous (unknown)
    at <anonymous> (/Users/simnalamburt/personal/parcel-practice/node_modules/.pnpm/@parcel+core@2.14.4_@swc+helpers@0.5.15/node_modules/@parcel/core/lib/worker.js:67:10)
    at anonymous (unknown)
    at <anonymous> (/Users/simnalamburt/personal/parcel-practice/node_modules/.pnpm/@parcel+workers@2.14.4_@parcel+core@2.14.4_@swc+helpers@0.5.15_/node_modules/@parcel/workers/lib/child.js:110:21)
Error: symbol 'napi_register_module_v1' not found in native module. Is this a Node API (napi) module?


TypeError: symbol 'napi_register_module_v1' not found in native module. Is this a Node API (napi) module?
    at dlopen (unknown)
    at <anonymous> (/Users/simnalamburt/personal/parcel-practice/node_modules/.pnpm/@parcel+watcher@2.5.1/node_modules/@parcel/watcher/index.js:15:13)
    at anonymous (unknown)
    at <anonymous> (/Users/simnalamburt/personal/parcel-practice/node_modules/.pnpm/@parcel+fs@2.14.4_@parcel+core@2.14.4_@swc+helpers@0.5.15_/node_modules/@parcel/fs/lib/index.js:9:5)
    at anonymous (unknown)
    at <anonymous> (/Users/simnalamburt/personal/parcel-practice/node_modules/.pnpm/@parcel+package-manager@2.14.4_@parcel+core@2.14.4_@swc+helpers@0.5.15__@swc+helpers@0.5.15/node_modules/@parcel/package-manager/lib/index.js:6:5)
    at anonymous (unknown)
    at <anonymous> (/Users/simnalamburt/personal/parcel-practice/node_modules/.pnpm/@parcel+core@2.14.4_@swc+helpers@0.5.15/node_modules/@parcel/core/lib/worker.js:67:10)
    at anonymous (unknown)
    at <anonymous> (/Users/simnalamburt/personal/parcel-practice/node_modules/.pnpm/@parcel+workers@2.14.4_@parcel+core@2.14.4_@swc+helpers@0.5.15_/node_modules/@parcel/workers/lib/child.js:110:21)
Error: symbol 'napi_register_module_v1' not found in native module. Is this a Node API (napi) module?


TypeError: symbol 'napi_register_module_v1' not found in native module. Is this a Node API (napi) module?
    at dlopen (unknown)
    at <anonymous> (/Users/simnalamburt/personal/parcel-practice/node_modules/.pnpm/@parcel+watcher@2.5.1/node_modules/@parcel/watcher/index.js:15:13)
    at anonymous (unknown)
    at <anonymous> (/Users/simnalamburt/personal/parcel-practice/node_modules/.pnpm/@parcel+fs@2.14.4_@parcel+core@2.14.4_@swc+helpers@0.5.15_/node_modules/@parcel/fs/lib/index.js:9:5)
    at anonymous (unknown)
    at <anonymous> (/Users/simnalamburt/personal/parcel-practice/node_modules/.pnpm/@parcel+package-manager@2.14.4_@parcel+core@2.14.4_@swc+helpers@0.5.15__@swc+helpers@0.5.15/node_modules/@parcel/package-manager/lib/index.js:6:5)
    at anonymous (unknown)
    at <anonymous> (/Users/simnalamburt/personal/parcel-practice/node_modules/.pnpm/@parcel+core@2.14.4_@swc+helpers@0.5.15/node_modules/@parcel/core/lib/worker.js:67:10)
    at anonymous (unknown)
    at <anonymous> (/Users/simnalamburt/personal/parcel-practice/node_modules/.pnpm/@parcel+workers@2.14.4_@parcel+core@2.14.4_@swc+helpers@0.5.15_/node_modules/@parcel/workers/lib/child.js:110:21)
Error: symbol 'napi_register_module_v1' not found in native module. Is this a Node API (napi) module?


TypeError: symbol 'napi_register_module_v1' not found in native module. Is this a Node API (napi) module?
    at dlopen (unknown)
    at <anonymous> (/Users/simnalamburt/personal/parcel-practice/node_modules/.pnpm/@parcel+watcher@2.5.1/node_modules/@parcel/watcher/index.js:15:13)
    at anonymous (unknown)
    at <anonymous> (/Users/simnalamburt/personal/parcel-practice/node_modules/.pnpm/@parcel+fs@2.14.4_@parcel+core@2.14.4_@swc+helpers@0.5.15_/node_modules/@parcel/fs/lib/index.js:9:5)
    at anonymous (unknown)
    at <anonymous> (/Users/simnalamburt/personal/parcel-practice/node_modules/.pnpm/@parcel+package-manager@2.14.4_@parcel+core@2.14.4_@swc+helpers@0.5.15__@swc+helpers@0.5.15/node_modules/@parcel/package-manager/lib/index.js:6:5)
    at anonymous (unknown)
    at <anonymous> (/Users/simnalamburt/personal/parcel-practice/node_modules/.pnpm/@parcel+core@2.14.4_@swc+helpers@0.5.15/node_modules/@parcel/core/lib/worker.js:67:10)
    at anonymous (unknown)
    at <anonymous> (/Users/simnalamburt/personal/parcel-practice/node_modules/.pnpm/@parcel+workers@2.14.4_@parcel+core@2.14.4_@swc+helpers@0.5.15_/node_modules/@parcel/workers/lib/child.js:110:21)
error: script "build" exited with code 1
```

**Comment by simnalamburt** [comment]
I think this issue would be much easier to fix on the Parcel side. They just need to upgrade Parcel to use the latest version of NAPI.
