### ISSUE TITLE
`fn.emit is not a function` with `enquirer`

### ISSUE THREAD

**Issue by colinhacks** [oven-sh/bun#4153]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Simple repro with ESM:

```ts
import Enquirer from 'enquirer';

const answers = await Enquirer.prompt([
  {
    type: 'input',
    name: 'first_name',
    message: "What's your first name",
  },
]);

console.log(answers);
```

Error:

```
$ bun run enquirer.ts
[0.36ms] ".env.local", ".env.development", ".env"
214 |   static get prompt() {
215 |     const fn = (questions, ...rest) => {
216 |       let enquirer = new this(...rest);
217 |       let emit = enquirer.emit.bind(enquirer);
218 |       enquirer.emit = (...args) => {
219 |         fn.emit(...args);
            ^
TypeError: fn.emit is not a function. (In 'fn.emit(...args)', 'fn.emit' is undefined)
      at /Users/colinmcd94/Documents/bun/fun/node_modules/enquirer/index.js:219:8
      at /Users/colinmcd94/Documents/bun/fun/node_modules/enquirer/index.js:131:4
      at ask (/Users/colinmcd94/Documents/bun/fun/node_modules/enquirer/index.js:93:12)
      at /Users/colinmcd94/Documents/bun/fun/node_modules/enquirer/index.js:85:14
      at prompt (/Users/colinmcd94/Documents/bun/fun/node_modules/enquirer/index.js:81:15)
      at /Users/colinmcd94/Documents/bun/fun/enquirer.ts:3:22
```

**Comment by colinhacks** [comment]
Sister PR for `create-playwright`: https://github.com/microsoft/create-playwright/pull/95/files
