### ISSUE TITLE
Implement `worker_threads.Worker` option "eval"

### ISSUE THREAD

**Issue by armanbilge** [oven-sh/bun#4165]
### What is the problem this feature would solve?

```
[bun] Warning: worker_threads.Worker option "eval" is not implemented.
```

More broadly, this seems to be a blocker to run Vite with bun. https://vitejs.dev/

### What is the feature you are proposing to solve the problem?

Implement the `eval` option.

**Comment by armanbilge** [comment]
If there's a rough sketch for how this might be implemented, I could definitely take a stab at it.

https://github.com/oven-sh/bun/blob/1a6a52314f88946e66ac0f36d00d624ec1a5296f/src/js/node/worker_threads.ts#L212-L225

**Comment by ToshY** [comment]
I've encountered the same issue when trying to use bun for running `encore production` (from [Webpack Encore](https://github.com/symfony/webpack-encore)).

```console
$ encore production
[0.05ms] ".env"
Running webpack ...

[bun] Warning: worker_threads.Worker option "eval" is not implemented.
[bun] Warning: worker_threads.Worker option "stdout" is not implemented.
[bun] Warning: worker_threads.Worker option "stderr" is not implemented.
[bun] Warning: worker_threads.Worker option "resourceLimits" is not implemented.
[0.00ms] ".env"
[0.00ms] ".env"
[0.00ms] ".env"
error: [native code]
error: [native code]
error: [native code]
error: script "build" exited with code 1 (SIGHUP)
```

So it's not just `eval`, but other worker options as well.

**Comment by unpseudocomplique** [comment]
To add more context got the same issue with pdfmake
https://discord.com/channels/876711213126520882/1139142483805229217/1146723275095933038

**Comment by ToshY** [comment]
@Jarred-Sumner  @paperdave 

Could either one of you possibly you give some insight if these options will be implemented (in the near future)?

**Comment by ToshY** [comment]
@Jarred-Sumner @paperdave ping

**Comment by wottpal** [comment]
Encountered this when running honojs via cloudflare wrangler (don't know which part is the problem here).

Reproduction:

```
bun create hono@latest # pick cloudflare-workers
cd my-app
bun run dev
```

**Comment by LoveMeWithoutAll** [comment]
I encoutered a same issue. 

`[bun] Warning: worker_threads.Worker option "eval" is not implemented.`

**Comment by ventsislav-georgiev** [comment]
Adding `eslint`'s `no-unresolved` rule to the list of affected packages by this missing feature:
<img width="688" alt="image" src="https://github.com/oven-sh/bun/assets/5616486/d2bd31d9-2e39-43d0-93ce-274316837730">

**Comment by stevejhiggs** [comment]
With the upgrade to eslint 9 using eslint-plugin-prettier/recommended settings also causes this error to occur

**Comment by chimericdream** [comment]
I'm not sure how one might apply this workaround to ESLint specifically, but I was able to get past this and similar warnings in a Storybook build in my team's monorepo. Until `eval` and others are added to Bun, something like this can at least clean up the warnings in the output:

```ts
// Note: this is specific to Storybook/Vite, but in theory it should be adaptable in other situations
async viteFinal(config) {
    const { mergeConfig } = await import('vite');

    return mergeConfig(config, {
        build: {
            rollupOptions: {
                onwarn(
                    warning: Rollup.RollupLog,
                    warn: Rollup.LoggingFunction
                ) {
                    // @TODO: revisit this down the road to see if these still error on Bun
                    const ignoredBunErrors = [
                        'EVAL',
                        'MODULE_LEVEL_DIRECTIVE',
                    ];

                    if (
                        warning.code &&
                        ignoredBunErrors.includes(warning.code)
                    ) {
                        return;
                    }

                    warn(warning);
                },
            },
        },
    });
},
```

**Comment by Jarred-Sumner** [comment]
This will be fixed by https://github.com/oven-sh/bun/pull/11537

**Comment by skeie** [comment]
Any idea which Bun release #11537 will be part of? Looks like it did not make it into 1.1.13?

**Comment by Jarred-Sumner** [comment]
@skeie it did, what error did you see?

**Comment by skeie** [comment]
Oh, I did not see it in the change log, and my bad. Its not eval now, but `stdout` and a couple of others. Do you have any idea if this will be fixed in the nearest future? Last project we have that is not running bun 🤞 

This is the error

```
> [build 12/12] RUN bun run webpack --config webpack.prod.js:                                                   
#18 4.484 14 |     return;                                                                                       
#18 4.484 15 |   warned.add(feature), console.warn(new NotImplementedError(feature, issue));                     
#18 4.484 16 | }, $;                                                                                             
#18 4.484 17 |                                                                                                   
#18 4.484 18 | class NotImplementedError extends Error {
#18 4.484 19 |   constructor(feature, issue) {
#18 4.484                                          ^
#18 4.484 NotImplementedError: worker_threads.Worker option "stdout" is not yet implemented in Bun.
#18 4.484  code: "ERR_NOT_IMPLEMENTED"
#18 4.484 
#18 4.484       at internal:shared:9:37
#18 4.484       at new Worker (node:worker_threads:120:14)
#18 4.484       at initialize (/app/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:149:20)
#18 4.484       at new ExperimentalWorker (/app/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:145:10)
#18 4.484       at createWorker (/app/node_modules/jest-worker/build/WorkerPool.js:44:12)
#18 4.484       at new BaseWorkerPool (/app/node_modules/jest-worker/build/base/BaseWorkerPool.js:127:27)
#18 4.484       at new WorkerPool (:1:23)
#18 4.484       at new Worker (/app/node_modules/jest-worker/build/index.js:167:26)
#18 4.484       at getWorker (/app/node_modules/terser-webpack-plugin/dist/index.js:362:9)
#18 4.484       at /app/node_modules/terser-webpack-plugin/dist/index.js:450:41
#18 4.484       at /app/node_modules/terser-webpack-plugin/dist/index.js:390:39
#18 4.484       at next (/app/node_modules/terser-webpack-plugin/dist/utils.js:63:7)
#18 4.484       at forEach (:1:11)
#18 4.484       at /app/node_modules/terser-webpack-plugin/dist/utils.js:65:26
#18 4.484       at new Promise (:1:11)
#18 4.484       at throttleAll (/app/node_modules/terser-webpack-plugin/dist/utils.js:41:10)
#18 4.484       at /app/node_modules/terser-webpack-plugin/dist/index.js:579:11
#18 4.484 
#18 4.484 14 |     return;
#18 4.484 15 |   warned.add(feature), console.warn(new NotImplementedError(feature, issue));
#18 4.484 16 | }, $;
#18 4.484 17 | 
#18 4.484 18 | class NotImplementedError extends Error {
#18 4.484 19 |   constructor(feature, issue) {
#18 4.484                                          ^
#18 4.484 NotImplementedError: worker_threads.Worker option "stderr" is not yet implemented in Bun.
#18 4.484  code: "ERR_NOT_IMPLEMENTED"
#18 4.484 
#18 4.484       at internal:shared:9:37
#18 4.484       at new Worker (node:worker_threads:120:14)
#18 4.484       at initialize (/app/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:149:20)
#18 4.484       at new ExperimentalWorker (/app/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:145:10)
#18 4.484       at createWorker (/app/node_modules/jest-worker/build/WorkerPool.js:44:12)
#18 4.484       at new BaseWorkerPool (/app/node_modules/jest-worker/build/base/BaseWorkerPool.js:127:27)
#18 4.484       at new WorkerPool (:1:23)
#18 4.484       at new Worker (/app/node_modules/jest-worker/build/index.js:167:26)
#18 4.484       at getWorker (/app/node_modules/terser-webpack-plugin/dist/index.js:362:9)
#18 4.484       at /app/node_modules/terser-webpack-plugin/dist/index.js:450:41
#18 4.484       at /app/node_modules/terser-webpack-plugin/dist/index.js:390:39
#18 4.484       at next (/app/node_modules/terser-webpack-plugin/dist/utils.js:63:7)
#18 4.484       at forEach (:1:11)
#18 4.484       at /app/node_modules/terser-webpack-plugin/dist/utils.js:65:26
#18 4.484       at new Promise (:1:11)
#18 4.484       at throttleAll (/app/node_modules/terser-webpack-plugin/dist/utils.js:41:10)
#18 4.484       at /app/node_modules/terser-webpack-plugin/dist/index.js:579:11
#18 4.484 
#18 4.484 14 |     return;
#18 4.484 15 |   warned.add(feature), console.warn(new NotImplementedError(feature, issue));
#18 4.484 16 | }, $;
#18 4.484 17 | 
#18 4.484 18 | class NotImplementedError extends Error {
#18 4.484 19 |   constructor(feature, issue) {
#18 4.484                                          ^
#18 4.484 NotImplementedError: worker_threads.Worker option "resourceLimits" is not yet implemented in Bun.
#18 4.484  code: "ERR_NOT_IMPLEMENTED"
#18 4.484 
#18 4.484       at internal:shared:9:37
#18 4.484       at new Worker (node:worker_threads:120:14)
#18 4.484       at initialize (/app/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:149:20)
#18 4.484       at new ExperimentalWorker (/app/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:145:10)
#18 4.484       at createWorker (/app/node_modules/jest-worker/build/WorkerPool.js:44:12)
#18 4.484       at new BaseWorkerPool (/app/node_modules/jest-worker/build/base/BaseWorkerPool.js:127:27)
#18 4.484       at new WorkerPool (:1:23)
#18 4.484       at new Worker (/app/node_modules/jest-worker/build/index.js:167:26)
#18 4.484       at getWorker (/app/node_modules/terser-webpack-plugin/dist/index.js:362:9)
#18 4.484       at /app/node_modules/terser-webpack-plugin/dist/index.js:450:41
#18 4.484       at /app/node_modules/terser-webpack-plugin/dist/index.js:390:39
#18 4.484       at next (/app/node_modules/terser-webpack-plugin/dist/utils.js:63:7)
#18 4.484       at forEach (:1:11)
#18 4.484       at /app/node_modules/terser-webpack-plugin/dist/utils.js:65:26
#18 4.484       at new Promise (:1:11)
#18 4.484       at throttleAll (/app/node_modules/terser-webpack-plugin/dist/utils.js:41:10)
#18 4.484       at /app/node_modules/terser-webpack-plugin/dist/index.js:579:11
#18 4.484 
#18 4.522 184 |   postMessage(...args) {
#18 4.522 185 |     return this.#worker.postMessage(...args);
#18 4.522 186 |   }
#18 4.522 187 |   #onClose(e) {
#18 4.522 188 |     this.#onExitPromise = e.code, this.emit("exit", e.code);
#18 4.522 189 |   #onError(event) {
#18 4.522                 ^
#18 4.522 error: 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522           ^
#18 4.522 error: Invalid flag "n" in regular expression
#18 4.522     at blob:4186377f-1b49-40a7-87ea-ab570a06b31f:1:7
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522            ^
#18 4.522 error: Invalid flag "o" in regular expression
#18 4.522     at blob:4186377f-1b49-40a7-87ea-ab570a06b31f:1:8
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522              ^
#18 4.522 error: Invalid flag "e" in regular expression
#18 4.522     at blob:4186377f-1b49-40a7-87ea-ab570a06b31f:1:10
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522               ^
#18 4.522 error: Invalid flag "_" in regular expression
#18 4.522     at blob:4186377f-1b49-40a7-87ea-ab570a06b31f:1:11
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522                 ^
#18 4.522 error: Invalid flag "o" in regular expression
#18 4.522     at blob:4186377f-1b49-40a7-87ea-ab570a06b31f:1:13
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522                  ^
#18 4.522 error: Duplicate flag "d" in regular expression
#18 4.522     at blob:4186377f-1b49-40a7-87ea-ab570a06b31f:1:14
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522                    ^
#18 4.522 error: Invalid flag "l" in regular expression
#18 4.522     at blob:4186377f-1b49-40a7-87ea-ab570a06b31f:1:16
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522                     ^
#18 4.522 error: Invalid flag "e" in regular expression
#18 4.522     at blob:4186377f-1b49-40a7-87ea-ab570a06b31f:1:17
#18 4.522 
#18 4.522  cause: {
#18 4.522   "isTrusted": true
#18 4.522 }
#18 4.522 
#18 4.522       at #onError (node:worker_threads:189:11)
#18 4.522 184 |   postMessage(...args) {
#18 4.522 185 |     return this.#worker.postMessage(...args);
#18 4.522 186 |   }
#18 4.522 187 |   #onClose(e) {
#18 4.522 188 |     this.#onExitPromise = e.code, this.emit("exit", e.code);
#18 4.522 189 |   #onError(event) {
#18 4.522                 ^
#18 4.522 error: 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522           ^
#18 4.522 error: Invalid flag "n" in regular expression
#18 4.522     at blob:40ac68f0-f750-4b9e-a300-9b4ef0565b22:1:7
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522            ^
#18 4.522 error: Invalid flag "o" in regular expression
#18 4.522     at blob:40ac68f0-f750-4b9e-a300-9b4ef0565b22:1:8
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522              ^
#18 4.522 error: Invalid flag "e" in regular expression
#18 4.522     at blob:40ac68f0-f750-4b9e-a300-9b4ef0565b22:1:10
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522               ^
#18 4.522 error: Invalid flag "_" in regular expression
#18 4.522     at blob:40ac68f0-f750-4b9e-a300-9b4ef0565b22:1:11
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522                 ^
#18 4.522 error: Invalid flag "o" in regular expression
#18 4.522     at blob:40ac68f0-f750-4b9e-a300-9b4ef0565b22:1:13
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522                  ^
#18 4.522 error: Duplicate flag "d" in regular expression
#18 4.522     at blob:40ac68f0-f750-4b9e-a300-9b4ef0565b22:1:14
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522                    ^
#18 4.522 error: Invalid flag "l" in regular expression
#18 4.522     at blob:40ac68f0-f750-4b9e-a300-9b4ef0565b22:1:16
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522                     ^
#18 4.522 error: Invalid flag "e" in regular expression
#18 4.522     at blob:40ac68f0-f750-4b9e-a300-9b4ef0565b22:1:17
#18 4.522 
#18 4.522  cause: {
#18 4.522   "isTrusted": true
#18 4.522 }
#18 4.522 
#18 4.522       at #onError (node:worker_threads:189:11)
#18 4.522 184 |   postMessage(...args) {
#18 4.522 185 |     return this.#worker.postMessage(...args);
#18 4.522 186 |   }
#18 4.522 187 |   #onClose(e) {
#18 4.522 188 |     this.#onExitPromise = e.code, this.emit("exit", e.code);
#18 4.522 189 |   #onError(event) {
#18 4.522                 ^
#18 4.522 error: 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522           ^
#18 4.522 error: Invalid flag "n" in regular expression
#18 4.522     at blob:f739a19f-0066-4d38-a31e-209a744005ae:1:7
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522            ^
#18 4.522 error: Invalid flag "o" in regular expression
#18 4.522     at blob:f739a19f-0066-4d38-a31e-209a744005ae:1:8
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522              ^
#18 4.522 error: Invalid flag "e" in regular expression
#18 4.522     at blob:f739a19f-0066-4d38-a31e-209a744005ae:1:10
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522               ^
#18 4.522 error: Invalid flag "_" in regular expression
#18 4.522     at blob:f739a19f-0066-4d38-a31e-209a744005ae:1:11
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522                 ^
#18 4.522 error: Invalid flag "o" in regular expression
#18 4.522     at blob:f739a19f-0066-4d38-a31e-209a744005ae:1:13
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522                  ^
#18 4.522 error: Duplicate flag "d" in regular expression
#18 4.522     at blob:f739a19f-0066-4d38-a31e-209a744005ae:1:14
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522                    ^
#18 4.522 error: Invalid flag "l" in regular expression
#18 4.522     at blob:f739a19f-0066-4d38-a31e-209a744005ae:1:16
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522                     ^
#18 4.522 error: Invalid flag "e" in regular expression
#18 4.522     at blob:f739a19f-0066-4d38-a31e-209a744005ae:1:17
#18 4.522 
#18 4.522  cause: {
#18 4.522   "isTrusted": true
#18 4.522 }
#18 4.522 
#18 4.522       at #onError (node:worker_threads:189:11)
#18 4.522 184 |   postMessage(...args) {
#18 4.522 185 |     return this.#worker.postMessage(...args);
#18 4.522 186 |   }
#18 4.522 187 |   #onClose(e) {
#18 4.522 188 |     this.#onExitPromise = e.code, this.emit("exit", e.code);
#18 4.522 189 |   #onError(event) {
#18 4.522                 ^
#18 4.522 error: 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522           ^
#18 4.522 error: Invalid flag "n" in regular expression
#18 4.522     at blob:cad12c44-ed21-42b6-a8d4-03deb52487d9:1:7
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522            ^
#18 4.522 error: Invalid flag "o" in regular expression
#18 4.522     at blob:cad12c44-ed21-42b6-a8d4-03deb52487d9:1:8
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522              ^
#18 4.522 error: Invalid flag "e" in regular expression
#18 4.522     at blob:cad12c44-ed21-42b6-a8d4-03deb52487d9:1:10
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522               ^
#18 4.522 error: Invalid flag "_" in regular expression
#18 4.522     at blob:cad12c44-ed21-42b6-a8d4-03deb52487d9:1:11
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522                 ^
#18 4.522 error: Invalid flag "o" in regular expression
#18 4.522     at blob:cad12c44-ed21-42b6-a8d4-03deb52487d9:1:13
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522                  ^
#18 4.522 error: Duplicate flag "d" in regular expression
#18 4.522     at blob:cad12c44-ed21-42b6-a8d4-03deb52487d9:1:14
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522                    ^
#18 4.522 error: Invalid flag "l" in regular expression
#18 4.522     at blob:cad12c44-ed21-42b6-a8d4-03deb52487d9:1:16
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522                     ^
#18 4.522 error: Invalid flag "e" in regular expression
#18 4.522     at blob:cad12c44-ed21-42b6-a8d4-03deb52487d9:1:17
#18 4.522 
#18 4.522  cause: {
#18 4.522   "isTrusted": true
#18 4.522 }
#18 4.522 
#18 4.522       at #onError (node:worker_threads:189:11)
#18 4.522 184 |   postMessage(...args) {
#18 4.522 185 |     return this.#worker.postMessage(...args);
#18 4.522 186 |   }
#18 4.522 187 |   #onClose(e) {
#18 4.522 188 |     this.#onExitPromise = e.code, this.emit("exit", e.code);
#18 4.522 189 |   #onError(event) {
#18 4.522                 ^
#18 4.522 error: 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522           ^
#18 4.522 error: Invalid flag "n" in regular expression
#18 4.522     at blob:55c0fd76-0e88-47bd-aef5-d01068320d30:1:7
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522            ^
#18 4.522 error: Invalid flag "o" in regular expression
#18 4.522     at blob:55c0fd76-0e88-47bd-aef5-d01068320d30:1:8
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522              ^
#18 4.522 error: Invalid flag "e" in regular expression
#18 4.522     at blob:55c0fd76-0e88-47bd-aef5-d01068320d30:1:10
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522               ^
#18 4.522 error: Invalid flag "_" in regular expression
#18 4.522     at blob:55c0fd76-0e88-47bd-aef5-d01068320d30:1:11
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522                 ^
#18 4.522 error: Invalid flag "o" in regular expression
#18 4.522     at blob:55c0fd76-0e88-47bd-aef5-d01068320d30:1:13
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522                  ^
#18 4.522 error: Duplicate flag "d" in regular expression
#18 4.522     at blob:55c0fd76-0e88-47bd-aef5-d01068320d30:1:14
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522                    ^
#18 4.522 error: Invalid flag "l" in regular expression
#18 4.522     at blob:55c0fd76-0e88-47bd-aef5-d01068320d30:1:16
#18 4.522 
#18 4.522 1 | /app/node_modules/jest-worker/build/workers/threadChild.js
#18 4.522                     ^
#18 4.522 error: Invalid flag "e" in regular expression
#18 4.522     at blob:55c0fd76-0e88-47bd-aef5-d01068320d30:1:17
#18 4.522 
#18 4.522  cause: {
#18 4.522   "isTrusted": true
#18 4.522 }
#18 4.522 
#18 4.522       at #onError (node:worker_threads:189:11)
#18 4.522 
#18 4.522 Bun v1.1.13 (Linux arm64)
#18 4.685 error: "webpack" exited with code 1
```

**Comment by mardukbp** [comment]
I can confirm that stdout and stderr are missing. I got the following errors with bun 1.1.13:

NotImplementedError: worker_threads.Worker option "stdout" is not yet implemented in Bun.

NotImplementedError: worker_threads.Worker option "stderr" is not yet implemented in Bun.

**Comment by Jarred-Sumner** [comment]
Yes, the `stdout` and `stderr` options are tracked in #10768
