### ISSUE TITLE
MongoClient fails to connect with filepath for Certificate

### ISSUE THREAD

**Issue by Angusross111** [oven-sh/bun#4169]
### What version of Bun is running?

0.7.4

### What platform is your computer?

Linux 6.4.6-76060406-generic x86_64 x86_64

### What steps can reproduce the bug?

```
const client = new MongoClient(MONGODB_URI, {
    tls: true,
    tlsCAFile: "./cert.pem",
    tlsAllowInvalidHostnames: true,
});
```
Try to connect to a Mongo server that needs a CA file for TLS.

### What is the expected behavior?

The Mongo driver should connect correctly

### What do you see instead?

```
92 |  * @privateRemarks
93 |  * mongodb-client-encryption has a dependency on this error, it uses the constructor with a string argument
94 |  */
95 | class MongoError extends Error {
96 |     constructor(message) {
97 |         super(MongoError.buildErrorMessage(message));
            ^
error: UNABLE_TO_GET_ISSUER_CERT_LOCALLY
 code: "undefined"

      at new MongoError (/home/angus.ross/personal/bun-playground/node_modules/mongodb/lib/error.js:97:8)
      at new MongoSystemError (/home/angus.ross/personal/bun-playground/node_modules/mongodb/lib/error.js:619:12)
      at new MongoServerSelectionError (/home/angus.ross/personal/bun-playground/node_modules/mongodb/lib/error.js:641:8)
      at /home/angus.ross/personal/bun-playground/node_modules/mongodb/lib/sdam/topology.js:278:37
```

**Comment by Angusross111** [comment]
This seems to be fixed now, works in `v1.0.13` and `v1.0.15`
