### ISSUE TITLE
Module._nodeModulePaths readonly property

### ISSUE THREAD

**Issue by Burak-Esen** [oven-sh/bun#424]
Hi, I try to run project includes module-alias npm package. I got that error
``` ~/.bun/bin/bun run index.js 
12 | var modulePaths = []
13 | var moduleAliases = {}
14 | var moduleAliasNames = []
15 | 
16 | var oldNodeModulePaths = Module._nodeModulePaths
17 | Module._nodeModulePaths = function (from) {
   ^
 TypeError: Attempted to assign to readonly property.
      at /project/node_modules/module-alias/index.js:17:0
      at bun:wrap:1:16354
      at /project/node_modules/module-alias/register.js:1:8
      at /project/index.js:1:8```

**Comment by Jarred-Sumner** [comment]
If you want to alias modules, you can use [tsconfig.json's "paths"](https://www.typescriptlang.org/tsconfig#paths) syntax (if not using tsconfig.json, you can make the filename "jsconfig.json")

**Comment by Burak-Esen** [comment]
I tried with jsconfig and without using module-alias package. It works !
