### ISSUE TITLE
Bun crashing when importing a module that does not exists

### ISSUE THREAD

**Issue by pdenapo** [oven-sh/bun#4240]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Linux 5.15.0-79-generic x86_64 x86_64 (Linux Mint 21.2)

### What steps can reproduce the bug?

Create a file importing a module that does not exists in the registry as

import {prueba} from "prueba.js";

and run it under bun.

### What is the expected behavior?

Bun should not crash!

### What do you see instead?

error: package "prueba.js" not found registry.npmjs.org/prueba.js 404
Segmentation fault (core dumped)

**Comment by Jarred-Sumner** [comment]
Looks like a crash in auto install

**Comment by pdenapo** [comment]
This bug is still there in 0.8.1 !

**Comment by birkskyum** [comment]
I get a somewhat different output with 0.8.1 on macos:

```sh
➜ bun foo.js

error: Could not resolve: "prueba.js". Maybe you need to "bun install"?
import {prueba} from "prueba.js";
```

**Comment by Hanaasagi** [comment]
This can be reproduced in a scenario where there are no other files except for index.js.

![2023-08-26_14-14](https://github.com/oven-sh/bun/assets/9482395/f078909c-53a6-4fa6-9ac1-a3deff0ae7b2)

#### coredump info

```
warning: Section `.reg-xstate/987172' in core file too small.
#0  0x00007f002368e83c in ?? () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f0023926400 (LWP 987172))]
(gdb) bt
#0  0x00007f002368e83c in ?? () from /usr/lib/libc.so.6
#1  0x00007f002363e668 in raise () from /usr/lib/libc.so.6
#2  0x00007f0023626542 in abort () from /usr/lib/libc.so.6
#3  0x0000562ca29bc449 in os.abort () at /home/kumiko/zig/zig-linux-x86_64-0.12.0-dev.163+6780a6bbf/lib/std/os.zig:598
#4  0x0000562ca29b8154 in debug.panicImpl (trace=0x0, first_trace_addr=..., msg=...)
    at /home/kumiko/zig/zig-linux-x86_64-0.12.0-dev.163+6780a6bbf/lib/std/debug.zig:440
#5  0x0000562ca29b6e74 in src.main.panic (msg=..., error_return_trace=0x0, addr=...) at /home/kumiko/zig/bun/src/main.zig:88
#6  0x0000562ca29b8657 in debug.panicExtra__anon_3405 (trace=0x0, ret_addr=..., args=...)
    at /home/kumiko/zig/zig-linux-x86_64-0.12.0-dev.163+6780a6bbf/lib/std/debug.zig:373
#7  0x0000562ca29b6f05 in builtin.panicOutOfBounds (index=4294967295, len=1)
    at /home/kumiko/zig/zig-linux-x86_64-0.12.0-dev.163+6780a6bbf/lib/std/builtin.zig:836
#8  0x0000562ca3fd1770 in src.install.install.PackageManager.enqueueDependencyToRoot (
    this=0x562ca597cc08 <src.install.install.PackageManager.instance>, name=..., version=0x7fff287cd010, version_buf=...,
    behavior=(unknown: 0x2)) at /home/kumiko/zig/bun/src/install/install.zig:1823
#9  0x0000562ca3b4fbfd in src.resolver.resolver.Resolver.enqueueDependencyToResolve (r=0x39706110c50, package_json_=0x0, esm=...,
    behavior=(unknown: 0x2), input_package_id_=0x7fff287cdf6c, version=..., version_buf=...)
    at /home/kumiko/zig/bun/src/resolver/resolver.zig:2150
#10 0x0000562ca34e0fcc in src.resolver.resolver.Resolver.loadNodeModules (r=0x39706110c50, import_path=..., kind=stmt,
    _dir_info=0x562ca59186f0 <src.allocators.BSSMap.BSSMapType.instance.3+33384>, global_cache=auto, forbid_imports=false)
    at /home/kumiko/zig/bun/src/resolver/resolver.zig:1802
#11 0x0000562ca34dd207 in src.resolver.resolver.Resolver.resolveWithoutRemapping (r=0x39706110c50,
    source_dir_info=0x562ca59186f0 <src.allocators.BSSMap.BSSMapType.instance.3+33384>, import_path=..., kind=stmt,
    global_cache=auto) at /home/kumiko/zig/bun/src/resolver/resolver.zig:2314
#12 0x0000562ca2f005f4 in src.resolver.resolver.Resolver.resolveWithoutSymlinks (r=0x39706110c50, source_dir=..., import_path_=...,
    kind=stmt, global_cache=auto) at /home/kumiko/zig/bun/src/resolver/resolver.zig:1383
#13 0x0000562ca2a367b8 in src.resolver.resolver.Resolver.resolveAndAutoInstall (r=0x39706110c50, source_dir=..., import_path=...,
    kind=stmt, global_cache=auto) at /home/kumiko/zig/bun/src/resolver/resolver.zig:890
#14 0x0000562ca2b330af in src.linker.Linker.link__anon_54197 (linker=0x39706111990, file_path=..., result=0x7fff287d7158, origin=...)
    at /home/kumiko/zig/bun/src/linker.zig:352
#15 0x0000562ca345d17e in src.bun.js.module_loader.ModuleLoader.transpileSourceCode__anon_160256 (jsc_vm=0x39706110000,
    specifier=..., display_specifier=..., referrer=..., input_specifier=..., path=..., loader=jsx, log=0x7fff287dbb00,
    virtual_source=0x0, ret=0x7fff287dbf50, promise_ptr=0x7fff287db9f8, source_code_printer=0x397062d0070,
    globalObject=0x7f00174c4068) at /home/kumiko/zig/bun/src/bun.js/module_loader.zig:1561
#16 0x0000562ca3461c10 in Bun__transpileFile (jsc_vm=0x39706110000, globalObject=0x7f00174c4068, specifier_ptr=0x7fff287dbfd0,
    referrer=0x7fff287dbfb8, ret=0x7fff287dbf50, allow_promise=true) at /home/kumiko/zig/bun/src/bun.js/module_loader.zig:1948
--Type <RET> for more, q to quit, c to continue without paging--
#17 0x0000562ca27caccf in Bun::fetchESMSourceCode<true> (globalObject=0x7f00174c4068, res=0x7fff287dbf50, specifier=0x7fff287dbfd0,
    referrer=0x7fff287dbfb8) at src/bun.js/bindings/ModuleLoader.cpp:619
#18 Bun::fetchESMSourceCodeAsync (globalObject=globalObject@entry=0x7f00174c4068, res=res@entry=0x7fff287dbf50,
    specifier=specifier@entry=0x7fff287dbfd0, referrer=referrer@entry=0x7fff287dbfb8) at src/bun.js/bindings/ModuleLoader.cpp:724
#19 0x0000562ca287d070 in Zig::GlobalObject::moduleLoaderFetch (globalObject=0x7f00174c4068, loader=<optimized out>, key=...,
    value1=..., value2=...) at src/bun.js/bindings/ZigGlobalObject.cpp:4328
#20 0x0000562ca17069cd in JSC::JSModuleLoader::fetch(JSC::JSGlobalObject*, JSC::JSValue, JSC::JSValue, JSC::JSValue) ()
#21 0x0000562ca1704aa1 in JSC::moduleLoaderFetch(JSC::JSGlobalObject*, JSC::CallFrame*) ()
#22 0x00007ee7c00081b8 in ?? ()
#23 0x00007fff287dc160 in ?? ()
#24 0x0000562ca1803083 in js_trampoline_op_call ()
#25 0x0000000000000000 in ?? ()

```

#### Related code

out of bound here.

```
#7  0x0000562ca29b6f05 in builtin.panicOutOfBounds (index=4294967295, len=1)
```

https://github.com/oven-sh/bun/blob/e1dacf88d0778fb9f2aa6932dcc67f9980e03265/src/install/install.zig#L1823
