### ISSUE TITLE
`tree-sitter` package not working - symbol not found in flat namespace

### ISSUE THREAD

**Issue by vjpr** [oven-sh/bun#4254]
### What version of Bun is running?

0.8.0

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

 ```
const Parser = await import('tree-sitter')
const {tsx} = await import('tree-sitter-typescript')
const parser = new Parser()
parser.setLanguage(tsx)
const tree = parser.parse(sourceCode)
console.log(tree.rootNode.toString())
```

### What do you see instead?

```
1 | (function (id){"use strict";var cached=@requireMap.@get(id);const last5=id.substring(id.length-5);if(cached)return cached.exports;if(last5===".json"){var fs=globalThis[Symbol.for("_fs")]||=@Bun.fs(),exports=JSON.parse(fs.readFileSync(id,"utf8"));return @requireMap.@set(id,@createCommonJSModule(id,exports,!0)),exports}else if(last5===".node"){const module=@createCommonJSModule(id,{},!0);return process.dlopen(module,id),@requireMap.@set(id,module),module.exports}else if(last5===".toml"){var fs=globalThis[Symbol.for("_fs")]||=@Bun.fs(),exports=@Bun.TOML.parse(fs.readFileSync(id,"utf8"));return @requireMap.@set(id,@createCommonJSModule(id,exports,!0)),exports}else{var exports=@requireESM(id);const cachedModule=@requireMap.@get(id);if(cachedModule)return cachedModule.exports;return @requireMap.@set(id,@createCommonJSModule(id,exports,!0)),exports}})
                       ^
TypeError: dlopen(/xxx/node_modules/.pnpm/tree-sitter@0.20.5/node_modules/tree-sitter/build/Release/tree_sitter_runtime_binding.node, 0x0001): symbol not found in flat namespace '__ZN2v812BackingStore12EmptyDeleterEPvmS1_'
      at internalRequire (:1:20)
      at /xxx/node_modules/.pnpm/tree-sitter@0.20.5/node_modules/tree-sitter/index.js:3:2
      at globalThis (/xxx/node_modules/.pnpm/tree-sitter@0.20.5/node_modules/tree-sitter/index.js:708:28)
```

**Comment by vjpr** [comment]
Dupe: https://github.com/oven-sh/bun/issues/4188
