### ISSUE TITLE
`http.server` crashes after exception in the dev build.

### ISSUE THREAD

**Issue by Hanaasagi** [oven-sh/bun#4298]
### What version of Bun is running?

0.8.0_debug

### What platform is your computer?

Linux 6.4.11-arch2-1 x86_64 unknown

### What steps can reproduce the bug?

server.js

```JavaScript
import { createServer, request } from "node:http";

const server = createServer(function(req, res) {
  // NOTE: url is not imported !!!
  // we need a exception here to reproduce.
  let option = url.parse(req.url);
});

server.listen(1087);
console.log("Listening on port 1087");
```

Run

```
curl 127.0.0.1:1087
```

### What is the expected behavior?

No crash.

### What do you see instead?

Crash

### coredump stack

```
#0  0x00007f8e6568e83c in ?? () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f8e65930400 (LWP 722865))]
(gdb) bt
#0  0x00007f8e6568e83c in ?? () from /usr/lib/libc.so.6
#1  0x00007f8e6563e668 in raise () from /usr/lib/libc.so.6
#2  0x00007f8e65626542 in abort () from /usr/lib/libc.so.6
#3  0x000055bbc411f9c9 in os.abort () at /home/kumiko/zig/zig-linux-x86_64-0.11.0-dev.4006+bf827d0b5/lib/std/os.zig:617
#4  0x000055bbc411b729 in debug.panicImpl (trace=0x0, first_trace_addr=..., msg=...)
    at /home/kumiko/zig/zig-linux-x86_64-0.11.0-dev.4006+bf827d0b5/lib/std/debug.zig:356
#5  0x000055bbc411a0cb in builtin.default_panic ()
    at /home/kumiko/zig/zig-linux-x86_64-0.11.0-dev.4006+bf827d0b5/lib/std/builtin.zig:814
#6  src.panic_handler.NewPanicHandler((function 'default_panic')).handle_panic () at /home/kumiko/zig/bun/src/panic_handler.zig:49
#7  src.main.panic (msg=..., error_return_trace=0x0, addr=...) at /home/kumiko/zig/bun/src/main.zig:9
#8  0x000055bbc411bce7 in debug.assert (ok=false)
    at /home/kumiko/zig/zig-linux-x86_64-0.11.0-dev.4006+bf827d0b5/lib/std/debug.zig:258
#9  0x000055bbc503ad0c in src.bun.js.api.server.NewRequestContext(false,true,src.bun.js.api.server.NewServer(src.bun.js.bindings.generated_classes.JSDebugHTTPServer,false,true)).finalizeWithoutDeinit (this=0x374aa470000)
    at /home/kumiko/zig/bun/src/bun.js/api/server.zig:1519
#10 0x000055bbc4af9b5b in src.bun.js.api.server.NewRequestContext(false,true,src.bun.js.api.server.NewServer(src.bun.js.bindings.generated_classes.JSDebugHTTPServer,false,true)).finalize (this=0x374aa470000) at /home/kumiko/zig/bun/src/bun.js/api/server.zig:1585
#11 0x000055bbc503b6fc in src.bun.js.api.server.NewRequestContext(false,true,src.bun.js.api.server.NewServer(src.bun.js.bindings.generated_classes.JSDebugHTTPServer,false,true)).renderMissing (ctx=0x374aa470000) at /home/kumiko/zig/bun/src/bun.js/api/server.zig:1205
#12 0x000055bbc58dcc9a in src.bun.js.api.server.NewServer(src.bun.js.bindings.generated_classes.JSDebugHTTPServer,false,true).onRequest () at /home/kumiko/zig/bun/src/bun.js/api/server.zig:5422
#13 src.deps.uws.NewApp(false).RouteHandler(*src.bun.js.api.server.NewServer(src.bun.js.bindings.generated_classes.JSDebugHTTPServer,false,true),(function 'onRequest')).handle (res=0x55bbc89ac390, req=0x7ffd6e6e2bb0, user_data=0x374aa240700)
    at /home/kumiko/zig/bun/src/deps/uws.zig:1438
#14 0x000055bbc6ab8ac2 in ofats::any_detail::handler_traits<bool, uWS::HttpRouter<uWS::HttpContextData<false>::RouterData>*>::large_handler<uWS::HttpContext<false>::onHttp(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ofats::any_invocable<void (uWS::HttpResponse<false>*, uWS::HttpRequest*)>&&, bool)::{lambda(auto:1*)#1}>::call(ofats::any_detail::storage&, uWS::HttpRouter<uWS::HttpContextData<false>::RouterData>*) ()
#15 0x000055bbc6ab46db in uWS::HttpRouter<uWS::HttpContextData<false>::RouterData>::executeHandlers(uWS::HttpRouter<uWS::HttpContextData<false>::RouterData>::Node*, int, uWS::HttpContextData<false>::RouterData&) ()
#16 0x000055bbc6ab268b in ofats::any_detail::handler_traits<void*, void*, uWS::HttpRequest*>::small_handler<uWS::HttpContext<false>::init()::{lambda(us_socket_t*, char*, int)#1}::operator()(us_socket_t*, char*, int) const::{lambda(void*, uWS::HttpRequest*)#1}>::call(ofats::any_detail::storage&, void*, uWS::HttpRequest*) ()
#17 0x000055bbc6ab31b1 in uWS::HttpParser::consumePostPadded(char*, unsigned int, void*, void*, ofats::any_invocable<void* (void*, uWS::HttpRequest*)>&&, ofats::any_invocable<void* (void*, std::basic_string_view<char, std::char_traits<char> >, bool)>&&, ofats::any_inv--Type <RET> for more, q to quit, c to continue without paging--
ocable<void* (void*)>&&) ()
#18 0x000055bbc6ab19d1 in uWS::HttpContext<false>::init()::{lambda(us_socket_t*, char*, int)#1}::__invoke(us_socket_t*, char*, int)
    ()
#19 0x000055bbc6b03328 in us_internal_dispatch_ready_poll (p=<optimized out>, error=0, events=1) at src/loop.c:328
#20 0x000055bbc6b02b32 in us_loop_run_bun_tick (loop=0x55bbc899ed90) at src/eventing/epoll_kqueue.c:215
#21 0x000055bbc4aafa01 in src.deps.uws.Loop.tick (this=0x55bbc899ed90) at /home/kumiko/zig/bun/src/deps/uws.zig:823
#22 0x000055bbc45cc4d3 in src.bun.js.event_loop.EventLoop.autoTickActive (this=0x374aa100100)
    at /home/kumiko/zig/bun/src/bun.js/event_loop.zig:784
#23 0x000055bbc4d13b98 in src.bun_js.Run.start (this=0x55bbc72604d0 <src.bun_js[run]>) at /home/kumiko/zig/bun/src/bun_js.zig:348
#24 0x000055bbc46fb8c9 in src.bun.js.javascript.OpaqueWrap__anon_48571__struct_115963.callback (ctx=0x55bbc72604d0 <src.bun_js[run]>)
    at /home/kumiko/zig/bun/src/bun.js/javascript.zig:104
#25 0x000055bbc3e50ed1 in JSC__VM__holdAPILock (arg0=<optimized out>, ctx=0x55bbc72604d0 <src.bun_js[run]>,
    callback=0x55bbc46fb850 <src.bun.js.javascript.OpaqueWrap__anon_48571__struct_115963.callback>)
    at src/bun.js/bindings/bindings.cpp:3941
#26 0x000055bbc41ee0c9 in src.bun.js.bindings.shimmer.Shimmer("JSC","VM",src.bun.js.bindings.bindings.VM).cppFn ()
    at /home/kumiko/zig/bun/src/bun.js/bindings/shimmer.zig:186
#27 src.bun.js.bindings.bindings.VM.holdAPILock (this=0x7f8e19000000, ctx=0x55bbc72604d0 <src.bun_js[run]>,
    callback=0x55bbc46fb850 <src.bun.js.javascript.OpaqueWrap__anon_48571__struct_115963.callback>)
    at /home/kumiko/zig/bun/src/bun.js/bindings/bindings.zig:5004
#28 0x000055bbc45f9a5d in src.bun_js.Run.boot (ctx_=..., entry_path=...) at /home/kumiko/zig/bun/src/bun_js.zig:233
#29 0x000055bbc45faf3e in src.cli.run_command.RunCommand.exec__anon_82932 (ctx_=...)
    at /home/kumiko/zig/bun/src/cli/run_command.zig:966
#30 0x000055bbc460efc3 in src.cli.Command.start (allocator=..., log=0x55bbc77ce440 <src.cli.Cli.log_>)
    at /home/kumiko/zig/bun/src/cli.zig:1425
#31 0x000055bbc411c6f6 in src.cli.Cli.start__anon_4585 (allocator=...) at /home/kumiko/zig/bun/src/cli.zig:57
#32 0x000055bbc411a4ef in src.main.main () at /home/kumiko/zig/bun/src/main.zig:38
#33 0x000055bbc4119ee6 in start.callMain () at /home/kumiko/zig/zig-linux-x86_64-0.11.0-dev.4006+bf827d0b5/lib/std/start.zig:598
#34 start.initEventLoopAndCallMain () at /home/kumiko/zig/zig-linux-x86_64-0.11.0-dev.4006+bf827d0b5/lib/std/start.zig:542
#35 start.callMainWithArgs () at /home/kumiko/zig/zig-linux-x86_64-0.11.0-dev.4006+bf827d0b5/lib/std/start.zig:492
#36 main (c_argc=3, c_argv=0x7ffd6e6f3778, c_envp=0x7ffd6e6f3798)
    at /home/kumiko/zig/zig-linux-x86_64-0.11.0-dev.4006+bf827d0b5/lib/std/start.zig:507

```

### Related code

https://github.com/oven-sh/bun/blob/9c68abdb8d51951f83b4b253cf5dd3922c2c58b5/src/bun.js/api/server.zig#L1512-L1521

From the log, I saw `finalizeWithoutDeinit` is called twice, so it will assert error.

**Comment by Jarred-Sumner** [comment]
how did we not catch this in tests

**Comment by Hanaasagi** [comment]
there were no unit tests for http 500 in node-http.test.ts before.
