### ISSUE TITLE
Puppeteer is not working under Web Worker on Ubuntu WSL

### ISSUE THREAD

**Issue by phtdacosta** [oven-sh/bun#4305]
### What version of Bun is running?

0.8.0

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

1. I start a web worker (copy-paste from the example on Bun's website)
2. I postMessage a simple JSON to to the worker
3. I have an async function imported from another file which does the Puppeteer stuff and it loads successfully
4. I send the JSON to this function using Puppeteer

I profiled my entire code and it does not go any further from the precise following line
```
const browser = await puppeteer.launch({ headless: 'new' })
```

### What is the expected behavior?

Run Puppeteer

### What do you see instead?

The following error,

```
ErrorEvent {
  type: "error",
  message: "269 |             if (this.puppeteer.configuration.browserRevision) {\n270 |                 throw new Error(`Tried to find the browser at the configured path (${executablePath}) for revision ${this.puppeteer.browserRevision}, but no executable was found.`);\n271 |             }\n272 |             switch (this.product) {\n273 |                 case 'chrome':\n274 |                     throw new Error(`Could not find Chrome (ver. ${this.puppeteer.browserRevision}). This can occur if either\\n` +\n                              ^\nerror: Could not find Chrome (ver. 116.0.5845.96). This can occur if either\n 1. you did not perform an installation before running the script (e.g. `npm install`) or\n 2. your cache path is incorrectly configured (which is: /home/user/.cache/puppeteer).\nFor (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.\n      at resolveExecutablePath (/mnt/c/Users/user/Desktop/project/js-api/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:274:26)\n      at /mnt/c/Users/user/Desktop/project/js-api/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:91:31\n"
}
```

even though I have installed headless Chrome as in this tutorial:

https://linux.how2shout.com/how-to-install-and-use-chrome-headless-on-ubuntu/#2_Install_Google_Chrome_Browser_on_Ubuntu

**Comment by phtdacosta** [comment]
The problem was much deeper down than I first thought it to be, it was not Bun's web workers, it was a Puppeteer-WSL issue.

Running it on Linux is already more burdensome than on Windows and under WSL it just gets worse, so you must do a lot of weird tweaks to the system in order make it work.

1. use ```puppeteer-core``` instead of ```puppeteer```
2. use ```executablePath: '/usr/bin/chromium-browser',``` in Puppeteer's launch function options
3. check this link https://stackoverflow.com/questions/59979188/error-failed-to-launch-the-browser-process-puppeteer
4. check this other link https://askubuntu.com/questions/1258137/cannot-communicate-with-server-post-http-localhost-v2-apps-dial-unix-run-sn
5. download the standalone chromium using snap ```sudo snap install chromium```

It will likely make it.
