### ISSUE TITLE
Class names are missing from stack traces

### ISSUE THREAD

**Issue by xeraph-dev** [oven-sh/bun#4323]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Darwin 22.5.0 x86_64 i386

### Running this code

_bug.js_
```javascript
class Class {
  name() {
    console.log(new Error().stack);
  }
}

new Class().name();
```

### with node.js
```shell
node bug.js
```
```shell
Error
    at Class.name (/private/tmp/bun-error-stack/bug.js:7:17)
    at Object.<anonymous> (/private/tmp/bun-error-stack/bug.js:12:13)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47
```

### with deno
```shell
deno run bug.js
```
```shell
Error
    at Class.name (file:///private/tmp/bun-error-stack/bug.js:7:17)
    at file:///private/tmp/bun-error-stack/bug.js:12:13
```

### with bun
```shell
bun run bug.js
```
```shell
Error: 
    at name (/private/tmp/bun-error-stack/bug.js:6:33)
    at module code (/private/tmp/bun-error-stack/bug.js:12:15)
```

### What is the expected behavior?

The first line of the stack should start with `at Class.name` instead of `at name`.

**Comment by MulverineX** [comment]
Looks like the bot is failing to figure this one out on its own, hopefully someone steers through this issue, it's pretty annoying especially in environments where many classes share the same method names.
