### ISSUE TITLE
`ssh2` is not able to sign with private key

### ISSUE THREAD

**Issue by jkbz64** [oven-sh/bun#4487]
### What version of Bun is running?

0.8.1

### What platform is your computer?

Linux 6.4.0-asahi-10-1-edge-ARCH aarch64 unknown

### What steps can reproduce the bug?

```js
import { readFileSync } from "node:fs";
import { Client } from "ssh2";

const connection = new Client();
connection
  .on("ready", () => {
    console.log("Client :: ready");
  })
  .connect({
    host: "<host>",
    port: 22,
    username: "<user>",
    privateKey: readFileSync("<path to pkey>"),
  });
```

### What is the expected behavior?

Should output `Client :: ready`

### What do you see instead?

```
8797 |   }
8798 | }), require_sign = __commonJS({
8799 |   "node_modules/browserify-sign/browser/sign.js"(exports, module) {
8800 |     var Buffer2 = require_safe_buffer().Buffer, createHmac = require_browser3(), crt = require_browserify_rsa(), EC = require_elliptic().ec, BN = require_bn3(), parseKeys = require_parse_asn1(), curves = require_curves2();
8801 | 
8802 |     function sign(hash, key, hashType, signType, tag) {
                                     ^
error: Error signing data with key: wrong private key type
      at sign (node:crypto:8802:34)
      at node:crypto:8944:74
      at sign (/tmp/ssh2/node_modules/ssh2/lib/protocol/keyParser.js:393:15)
      at /tmp/ssh2/node_modules/ssh2/lib/client.js:467:32
      at authPK (/tmp/ssh2/node_modules/ssh2/lib/protocol/Protocol.js:692:4)
      at USERAUTH_PK_OK (/tmp/ssh2/node_modules/ssh2/lib/client.js:466:12)
      at 60 (/tmp/ssh2/node_modules/ssh2/lib/protocol/handlers.misc.js:504:19)
      at onPayload (/tmp/ssh2/node_modules/ssh2/lib/protocol/Protocol.js:2052:9)
      at decrypt (/tmp/ssh2/node_modules/ssh2/lib/protocol/crypto.js:987:20)
      at parsePacket (/tmp/ssh2/node_modules/ssh2/lib/protocol/Protocol.js:2021:9)
```

### Additional information

The same exact code works on node, tried to use `Bun.file` API instead of `readFileSync`, same result. Used standard `ssh-keygen` ssh-rsa key without password.

**Comment by FrancescoMasaia** [comment]
We replicated the same error in 1.0.4 version too

**Comment by jawaad-juggle** [comment]
Hey, I've run into this issue too. Did you managed to work a way around this?

**Comment by FrancescoMasaia** [comment]
Removed bun as dependency I’m not using bun anymore for that projectIl giorno 1 nov 2023, alle ore 11:58, jawaad-juggle ***@***.***> ha scritto:﻿
Hey, I've run into this issue too. Did you managed to work a way around this?

**Comment by osbre** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/4290 ?

**Comment by nektro** [comment]
in a debug build:

![Image](https://github.com/user-attachments/assets/758c0220-16fa-4f63-8285-53eaf6e832e9)

**Comment by jlucaso1** [comment]
@nektro @jkbz64 @cirospaciari 
This is working on latest bun version (1.2.5)

**Comment by cirospaciari** [comment]
@jlucaso1 thank you for testing @jkbz64 please reopen if you have another repro.
