### ISSUE TITLE
CommonJS module.exports is not a function

### ISSUE THREAD

**Issue by hyuzea** [oven-sh/bun#4506]
### What version of Bun is running?

0.8.2+f73f77d0dec9006f5f42ff401fb32f9eaefa749a

### What steps can reproduce the bug?

see  https://replit.com/@Yusham1/bun-require-module-exported-as-function#src/index.js

```js
const isNaturalNumber = require('is-natural-number')

console.info(isNaturalNumber)
console.info(isNaturalNumber(123))
```

### What is the expected behavior?

no error

### What do you see instead?

```
Module {
  __esModule: true,
  default: [Function: isNaturalNumber]
}

TypeError: isNaturalNumber is not a function. (In 'isNaturalNumber(123)', 'isNaturalNumber' is an instance of Module)
```

**Comment by birkskyum** [comment]
Works when using import instead of require

```ts
import isNaturalNumber from 'is-natural-number'

console.info(isNaturalNumber)
console.info(isNaturalNumber(123))
```

**Comment by Kleywalker** [comment]
Is this related to issue [#7636](https://github.com/oven-sh/bun/issues/7636). Are there any plans to implement this soon?

**Comment by CoolSpot** [comment]
Still an issue in Bun 1.0.29:
![image](https://github.com/oven-sh/bun/assets/3990370/e80b4667-0a1c-4007-9509-3cc0ea71407d)

```
│ │ │ │ ├─┬ decompress-unzip@3.4.0
│ │ │ │ │ ├── is-zip@1.0.0
│ │ │ │ │ ├── read-all-stream@3.1.0 deduped
│ │ │ │ │ ├── stat-mode@0.2.2
│ │ │ │ │ ├── strip-dirs@1.1.1 deduped
│ │ │ │ │ ├── through2@2.0.5
│ │ │ │ │ ├── vinyl@1.2.0
│ │ │ │ │ └── yauzl@2.10.0
```

Not sure if it is is-natural-number's problem, but it behaves differently than nodejs and thus breaks compatibility.

**Comment by karlhorky** [comment]
A similar error also happens with [`ley`](https://github.com/lukeed/ley):

```bash
$ bunx --bun ley up
[ley] Loading configuration

[ley] An error occurred:

      TypeError: require("postgres") is not a function. (In 'require("postgres")({
          onnotice: () => {
          },
          ...config,
          max: 1
        })', 'require("postgres")' is an instance of Module)
        at <anonymous> (/Users/k/p/courses/node_modules/ley/lib/clients/postgres.js:5:2)
        at <anonymous> (/Users/k/p/courses/node_modules/ley/index.js:57:25)
        at processTicksAndRejections (:12:39)
      originalLine: 5
      originalColumn: 31
```

Reproduction steps:

```bash
➜  p mkdir a
➜  p cd a

➜  a bun init -y
Done! A package.json file was saved in the current directory.
 + index.ts
 + .gitignore
 + tsconfig.json (for editor auto-complete)
 + README.md

To get started, run:
  bun run index.ts

➜  a bun add postgres
bun add v1.1.20 (ae194892)

installed postgres@3.4.4

1 package installed [686.00ms]

➜  a bun add ley
bun add v1.1.20 (ae194892)

installed ley@0.8.1 with binaries:
 - ley

6 packages installed [203.00ms]

➜  a mkdir migrations

➜  a bunx --bun ley up

[ley] An error occurred:

      TypeError: require("postgres") is not a function. (In 'require("postgres")({
          onnotice: () => {
          },
          ...config,
          max: 1
        })', 'require("postgres")' is an instance of Module)
        at <anonymous> (/Users/k/p/a/node_modules/ley/lib/clients/postgres.js:5:2)
        at <anonymous> (/Users/k/p/a/node_modules/ley/index.js:38:25)
        at processTicksAndRejections (:12:39)
      originalLine: 5
      originalColumn: 31
```

**Comment by Jarred-Sumner** [comment]
Confirmed this reproduces as of Bun v1.1.35

This is caused by us reading the `jsnext:main` field in package.json:

https://github.com/oven-sh/bun/blob/d879f4370db3f9cdfa79c10cf7440d16bcf52beb/src/options.zig#L490-L492

The `is-natural-number` package has an `export default function` for the `jsnext:main` module. This causes us to return a CommonJS module with `{ exports: { default: [Function] } }`.

The decision to pay attention to the `jsnext:main` field was probably wrong, but it is also a breaking change to fix it. I kind of think we should make the change, but perhaps only for the runtime and not at build-time.

**Comment by karlhorky** [comment]
@Jarred-Sumner ah interesting, so if I try to apply it to [my case with Postgres.js](https://github.com/oven-sh/bun/issues/4506#issuecomment-2259890350)

I see this in the `package.json` for Postgres.js:

https://github.com/porsager/postgres/blob/a2c7de12b3bfc6809051d94ba6115150f80678e3/package.json#L1-L14

```json
{
  "name": "postgres",
  "version": "3.4.5",
  "description": "Fastest full featured PostgreSQL client for Node.js",
  "type": "module",
  "module": "src/index.js",
  "main": "cjs/src/index.js",
  "exports": {
    "types": "./types/index.d.ts",
    "bun": "./src/index.js",
    "workerd": "./cf/src/index.js",
    "import": "./src/index.js",
    "default": "./cjs/src/index.js"
  },
```

And this in the `./src/index.js` file:

https://github.com/porsager/postgres/blob/a2c7de12b3bfc6809051d94ba6115150f80678e3/src/index.js#L47-L49

```js
export default Postgres

function Postgres(a, b) {
```
