### ISSUE TITLE
Tree-sitter-node segfaults

### ISSUE THREAD

**Issue by sualehasif** [oven-sh/bun#4554]
### What version of Bun is running?

v0.8.1

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

We extensively use: https://github.com/tree-sitter/node-tree-sitter. Using it in a simple script like:

```
const Parser = require('tree-sitter');
const JavaScript = require('tree-sitter-javascript');

const parser = new Parser();
parser.setLanguage(JavaScript);
const sourceCode = 'let x = 1; console.log(x);';
const tree = parser.parse(sourceCode);
```

causes a dyld segfault in bun

### What is the expected behavior?
```
➜  server ✗ node src/test.cjs
(program (lexical_declaration (variable_declarator name: (identifier) value: (number))) (expression_statement (call_expression function: (member_expression object: (identifier) property: (property_identifier)) arguments: (arguments (identifier)))))
```

### What do you see instead?

```
➜  serve ✗ bun src/test.cjs
[0.33ms] ".env"
1 | (function (id){"use strict";var cached=@requireMap.@get(id);const last5=id.substring(id.length-5);if(cached)return cached.exports;if(last5===".json"){var fs=globalThis[Symbol.for("_fs")]||=@Bun.fs(),exports=JSON.parse(fs.readFileSync(id,"utf8"));return @requireMap.@set(id,@createCommonJSModule(id,exports,!0)),exports}else if(last5===".node"){const module=@createCommonJSModule(id,{},!0);return process.dlopen(module,id),@requireMap.@set(id,module),module.exports}else if(last5===".toml"){var fs=globalThis[Symbol.for("_fs")]||=@Bun.fs(),exports=@Bun.TOML.parse(fs.readFileSync(id,"utf8"));return @requireMap.@set(id,@createCommonJSModule(id,exports,!0)),exports}else{var exports=@requireESM(id);const cachedModule=@requireMap.@get(id);if(cachedModule)return cachedModule.exports;return @requireMap.@set(id,@createCommonJSModule(id,exports,!0)),exports}})
                       ^
TypeError: dlopen(/Users/sualeh/code/everysphere/backend/node_modules/.pnpm/tree-sitter@0.20.5/node_modules/tree-sitter/build/Release/tree_sitter_runtime_binding.node, 0x0001): symbol not found in flat namespace '__ZN2v812BackingStore12EmptyDeleterEPvmS1_'
      at internalRequire (:1:20)
      at /Users/sualeh/code/everysphere/backend/node_modules/.pnpm/tree-sitter@0.20.5/node_modules/tree-sitter/index.js:3:2
      at globalThis (/Users/sualeh/code/everysphere/backend/node_modules/.pnpm/tree-sitter@0.20.5/node_modules/tree-sitter/index.js:708:28)
      at require (:1:20)
      at /Users/sualeh/code/everysphere/backend/server/src/test.cjs:1:6
      at globalThis (/Users/sualeh/code/everysphere/backend/server/src/test.cjs:8:36)
```

### Additional information

It seems like `_v8::BackingStore::EmptyDeleter(void*, unsigned long, void*)` is not implemented by bun?

Potentially a duplicate of https://github.com/oven-sh/bun/issues/4254

```
    "tree-sitter": "^0.20.5",
    "tree-sitter-javascript": "^0.20.1",
    "tree-sitter-python": "^0.20.4",
    "tree-sitter-typescript": "^0.20.1"
```

**Comment by sualehasif** [comment]
Btw, if I can help resolve this in any way please let me know. I dont know much about the internals of bun so unclear how easy/hard it is to fix this.

**Comment by sualehasif** [comment]
The problems probably stems from this somewhat harmless [line](https://github.com/tree-sitter/node-tree-sitter/blob/02cf55a84c597f250c87c303872808924db0a573/src/conversions.cc#L40) in treesitter.

that said, i can imagine a world where a proper patch requires writing bun bindings to treesitter

**Comment by sualehasif** [comment]
Dupe: #4188
