### ISSUE TITLE
createWebSocketStream in `ws` package not implemented

### ISSUE THREAD

**Issue by sapter** [oven-sh/bun#4568]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

The `createWebSocketStream` method from the `ws` package breaks. 
Users get a `Not supported yet in Bun` error when trying to use it.

```ts
import WebSocket, { createWebSocketStream } from "ws";

{...}

const s = new WebSocket(this.env.SOCKET_URL);
// The line below breaks in Bun :=(
const duplex: Duplex = createWebSocketStream(s, { decodeStrings: false }); 
```

### What is the expected behavior?

The `createWebSocketStream` works

### What do you see instead?

`Not supported yet in Bun` error

### Additional information

Looks like Bun overwrites the `ws` package. But not all methods in that package have been implemented leaving many users unable to use the package.

**Comment by sapter** [comment]
Related to #3613

**Comment by RobertAron** [comment]
I'm also really looking forward to using the `ws` support. Specifically my use case is utilizing mqtt.

https://github.com/mqttjs/MQTT.js

**Comment by cyrus-za** [comment]
Same here. Use case prisma pulse https://www.prisma.io/docs/data-platform/pulse/what-is-pulse

**Comment by sorenbs** [comment]
We would like for Prisma Pulse to support Bun. Is there a way we can help get this prioritised?

**Comment by RobertAron** [comment]
I think this is resolved with version 1.1  :D

![Screenshot 2024-04-01 at 12 20 45 PM](https://github.com/oven-sh/bun/assets/11590571/2cb96017-2eff-4985-9bcf-9347cd80facc)

**Comment by RobertAron** [comment]
Just got the opportunity to try this out today and unfortunately it doesn't seem like `mqtt.js` is working. 

```
812 | class Receiver {
813 |   constructor() {
814 |     throw new Error("Not supported yet in Bun");
815 |   }
816 | }
817 | var createWebSocketStream = (ws) => {

error: Not supported yet in Bun
      at ws:817:57
      at streamBuilder (/Users/robert/Desktop/dev/event-rewrite/node_modules/mqtt/build/lib/connect/ws.js:113:29)
      at wrapper (/Users/robert/Desktop/dev/event-rewrite/node_modules/mqtt/build/lib/connect/index.js:130:16)
      at connect (/Users/robert/Desktop/dev/event-rewrite/node_modules/mqtt/build/lib/client.js:215:23)
      at new MqttClient (/Users/robert/Desktop/dev/event-rewrite/node_modules/mqtt/build/lib/client.js:191:13)
      at connect (/Users/robert/Desktop/dev/event-rewrite/node_modules/mqtt/build/lib/connect/index.js:132:20)
      at makeMqttClient (/Users/robert/Desktop/dev/event-rewrite/apps/common/dist/connection-utils.js:11:24)
      at /Users/robert/Desktop/dev/event-rewrite/apps/batcher/src/utils/connections.ts:5:25
```

**Comment by neverstew** [comment]
I would love to see this resolved, as it's currently blocking me from using Bun with the `@atproto/sync` library (which handles reading from the ATProto Firehose).

**Comment by b0o** [comment]
> I would love to see this resolved, as it's currently blocking me from using Bun with the @atproto/sync library (which handles reading from the ATProto Firehose).

I have the same use case. This would be really nice :)

**Comment by Steve-Mcl** [comment]
> unfortunately it doesn't seem like `mqtt.js` is working.

Same here.

![Image](https://github.com/user-attachments/assets/ff708d08-5c4c-4f9a-9479-8bad649f96f2)


Is support for `createWebSocketStream` on the roadmap?

**Comment by ApprenticeofEnder** [comment]
Literally had to switch back to `pnpm` as a result of this. If no one else is doing this I might just do it myself at some point.

**Comment by RiskyMH** [comment]
> Literally had to switch back to `pnpm` as a result of this. If no one else is doing this I might just do it myself at some point.

This should only be a bun runtime issue and `bun install` shouldn't affect this. If you don't have node.js installed then `bunx next` type thing can pretend to be node though.

**Comment by tubbo** [comment]
> I would love to see this resolved, as it's currently blocking me from using Bun with the `@atproto/sync` library (which handles reading from the ATProto Firehose).
> 
> I'd also like to add that I sunk a bit of time into finding this, and a very quick update of the docs to show that there is still non-compatibility with node in the Websocket connection client would be a really helpful short-term patch.

hey me too! strange bc i feel like installing the `ws` pkg should resolve this?
