### ISSUE TITLE
Expected scope error when using abstract class with decorator

### ISSUE THREAD

**Issue by Zikoat** [oven-sh/bun#4579]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

tsconfig.json
```json
{
  "compilerOptions": {
...
    "module": "NodeNext",
    "target": "ESNext",
    "moduleResolution": "NodeNext",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  },
}
```
User.ts
```ts
import { Field } from "type-graphql";
import "reflect-metadata";

export abstract class User {
  @Field(() => Number)
  abstract myNumber: number;

  myFunc = () => 1;
}

console.log("success");
```

### What is the expected behavior?

```
$ npm i typescript@latest ts-node reflect-metadata type-graphql
$ npx ts-node-esm ./User.ts
success
```

### What do you see instead?

```
$ bun ./User.ts 
[0.01ms] ".env"


error: Expected scope (src.js_ast.Scope.Kind.function_args, 155) in /home/zikoat/dev/reproducebug/User.ts, found scope (src.js_ast.Scope.Kind.function_args, 108)

console.log("success");
                       ^
/home/zikoat/dev/reproducebug/User.ts:13:24 206


uh-oh: 

error: Expected scope (src.js_ast.Scope.Kind.function_args, 155) in /home/zikoat/dev/reproducebug/User.ts, found scope (src.js_ast.Scope.Kind.function_args, 108)

console.log("success");
                       ^
/home/zikoat/dev/reproducebug/User.ts:13:24 206

bun will crash now 😭😭😭

----- bun meta -----
Bun v0.8.1 (16b4bf34) Linux x64 #1 SMP Fri Jan 27 02:56:13 UTC 2023
AutoCommand: dotenv 
Elapsed: 12ms | User: 6ms | Sys: 6ms
RSS: 33.55MB | Peak: 52.15MB | Commit: 33.55MB | Faults: 0
----- bun meta -----

0   0x558e9e9f9bbb
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???
10  ???
11  ???
12  ???
13  ???
14  ???
15  ???
16  ???
17  ???
18  ???
19  ???
20  ???
21  ???
22  ???

Crash report saved to:
  ~/.bun/.bun-crash/v0.8.1-1694177371109.crash

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

thread 22037 panic: 

error: Expected scope (src.js_ast.Scope.Kind.function_args, 155) in /home/zikoat/dev/reproducebug/User.ts, found scope (src.js_ast.Scope.Kind.function_args, 108)

console.log("success");
                       ^
/home/zikoat/dev/reproducebug/User.ts:13:24 206

Unwind information for `:0x558e9e0689a0` was not available, trace may be incomplete

Aborted
```

**Comment by mars-lan** [comment]
FWIW, esbuild had a similar issue before: https://github.com/evanw/esbuild/issues/3684

**Comment by Zikoat** [comment]
This still reproduces in Bun v1.1.12.

Replit reproduction: https://replit.com/@zikoat/SkinnyKnottyOutliner?v=1

### Relevant log output

```shell
+ /nix/store/9bi40hvb51maxmlx8cgm721xx5dqgdaa-bun-1.1.11-wrapped/bin/bun index.ts
10 | console.log("success");
                           ^
error: Expected scope (src.js_ast.Scope.Kind.function_args, 134) in /home/runner/SkinnyKnottyOutliner/index.ts, found scope (src.js_ast.Scope.Kind.function_args, 103)
    at /home/runner/SkinnyKnottyOutliner/index.ts:10:23

============================================================
Bun v1.1.11 (4fb6056f) Linux x64
Args: "/nix/store/v0ps8nmsgbpdskm751vqg0s80nzkpiif-bun-1.1.11/bin/bun" "index.ts"
Features: jsc tsconfig 
Builtins: "bun:main" 
Elapsed: 16ms | User: 6ms | Sys: 16ms
RSS: 1.07GB | Peak: 36.06MB | Commit: 1.07GB | Faults: 0

panic(main thread): 10 | console.log("success");
                           ^
error: Expected scope (src.js_ast.Scope.Kind.function_args, 134) in /home/runner/SkinnyKnottyOutliner/index.ts, found scope (src.js_ast.Scope.Kind.function_args, 103)
    at /home/runner/SkinnyKnottyOutliner/index.ts:10:23

oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.11/la14fb6056AiggggEq6y0oDwqjpnD8nj5kDo15snDkpvyrD4ptrqDi7m1oD8i/qnD21n+kD0q47gDA0eNqVjzFrAzEMhff+BS8iUw6C73wuHdq5U4YOGQ0Nh89J3Z6kYNmQQH988eWapRRaTU8f0nuScgZNB5+gXIeeSXgKVSpnUTmDeuJj7dcL7HElxfsgsqqkueIen6q4g9+rmilnzez6Ok/PbUiJ07fLI1yVwefzKfgcRhDPpwBrSV6/y36QrHeV6G2kUR8K+RyZ9kM6ygaMvW8gErRvjKFNhSikdvcRiS5b4pwvLyVPscJIYzjrLBs4cKF/pnS2uX1brx7ycrZ9wL9H335edi2a7ifr7Rz1Bd1Cgfo
```


### Stack Trace (bun.report)

Bun v1.1.11 ([`4fb6056`](<https://github.com/oven-sh/bun/tree/4fb6056f85c9cf643caa9c2afdefe4917c513fb5>)) on linux x86_64 [AutoCommand]

**panic**: [1m1 | [0m[0m[35mfunction[0m b(target: [0m[34many[0m) {}[0m[35mclass[0m a {@b(() => [0m[33m1[0m) [0m[34mabstract[0m [0m[1m[34md[0m[0m[2m;[0me = () => [0m[33m1[0m[0m[2m;[0m}console[0m[3m[1m.log[0m([0m[32m"success"[0m)[0m[2m;[0m
                                                                                                  [1m[31m[1m^[0m
[31merror[0m[2m: [0m[1mExpected scope (src.js_ast.Scope.Kind.function_args, 62) in /home/runner/SkinnyKnottyOutliner/index.ts, found scope (src.js_ast.Scope.Kind.function_args, 38)[0m
    [2mat [0m[36m/home/runner/SkinnyKnottyOutliner/index.ts[0m[2m:[0m[33m1[0m[2m:[0m[33m95[0m

- [`debug.zig:373`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/deps/zig/lib/std/debug.zig#L373>): `debug.panicExtra__anon_467203`
- [`debug.zig:348`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/deps/zig/lib/std/debug.zig#L348>): `debug.panic__anon_446288`
- [`Global.zig:183`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/Global.zig#L183>): `src.Global.panic__anon_409518`
- [`js_parser.zig:14268`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/js_parser.zig#L14268>): `src.js_parser.NewParser_`
- [`js_parser.zig:6790`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/js_parser.zig#L6790>): `src.js_parser.NewParser_`
- [`js_parser.zig:15630`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/js_parser.zig#L15630>): `src.js_parser.NewParser_`
- [`js_parser.zig:19329`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/js_parser.zig#L19329>): `src.js_parser.NewParser_`
- [`js_parser.zig:21184`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/js_parser.zig#L21184>): `src.js_parser.NewParser_`
- [`js_parser.zig:15601`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/js_parser.zig#L15601>): `src.js_parser.NewParser_`
- [`js_parser.zig:15397`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/js_parser.zig#L15397>): `src.js_parser.NewParser_`

**Comment by Zikoat** [comment]
Expected behavior without experimentalDecorators:
Error: `Decorators are not valid here.`

Expected behavior with experimentalDecorators:
Logs: `success`

**Comment by dylan-conway** [comment]
Fixed in Bun v1.1.16 by @forcefieldsovereign with #11902
