### ISSUE TITLE
Incompatible with lru-native2 dependency

### ISSUE THREAD

**Issue by beetlebum** [oven-sh/bun#4597]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

- Attempt to run a large NodeJS project that contains the `lru-native2` dependency
- `bun src/index.ts`

### What is the expected behavior?

The application to run

### What do you see instead?

```
error: Cannot find module "./build/Release/native" from "/project/node_modules/lru-native2/index.js"
libc++abi: Pure virtual function called!
```

### Additional information

https://github.com/kibae/node-lru-native/blob/master/index.js
Not too familiar with Bun or NodeAPI but I believe this library is a simple C++ wrapper.

**Comment by artberri** [comment]
The reason for that is that `bun` does not run lifecycle scripts by default and `lru-native2` makes use of them to compile some C++ code after installation.

You need to add  `lru-native2` to the [`trustedDependencies`](https://bun.sh/docs/cli/install#trusted-dependencies) on your `package.json` and the code will be compiled.

The problem in this case is that after doing it an error still happens:

```
TypeError: dlopen(/xxxxxxx/node_modules/lru-native2/build/Release/native.node, 0x0001): tried: '/xxxxxxx/node_modules/lru-native2/build/Release/native.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/xxxxxxx/node_modules/lru-native2/build/Release/native.node' (no such file), '/xxxxxxx/node_modules/lru-native2/build/Release/native.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
      at internalRequire (:1:20)
      at /xxxxxxx/node_modules/lru-native2/index.js:2:7
      at globalThis (/xxxxxxx/node_modules/lru-native2/index.js:2:51)
      at processTicksAndRejections (:1:2602)
```

### What version of Bun is running?

1.0.1


### What platform is your computer?

Darwin 22.6.0 arm64 arm

**Comment by Electroid** [comment]
Duplicate of #4959

**Comment by Jarred-Sumner** [comment]
This was not fixed in #4959 because `lru-native2` did not make the top 500 allowlist
