### ISSUE TITLE
cucumber fails to run

### ISSUE THREAD

**Issue by cdmistman** [oven-sh/bun#4610]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 5.15.90 x86_64 unknown

### What steps can reproduce the bug?

```sh
$ bun add @cucumber/cucumber
# ...
$ bun --bun run cucumber-js
TypeError: undefined is not a constructor (evaluating 'new console_1.Console(this.stream)')
    at new ConsoleLogger (/app/upm/tests/node_modules/@cucumber/cucumber/lib/api/console_logger.js:8:56)
    at <anonymous> (/app/upm/tests/node_modules/@cucumber/cucumber/lib/api/load_configuration.js:21:8)
    at loadConfiguration (/app/upm/tests/node_modules/@cucumber/cucumber/lib/api/load_configuration.js:17:8)
    at <anonymous> (/app/upm/tests/node_modules/@cucumber/cucumber/lib/cli/index.js:46:26)
    at run (/app/upm/tests/node_modules/@cucumber/cucumber/lib/cli/index.js:19:14)
    at <anonymous> (/app/upm/tests/node_modules/@cucumber/cucumber/lib/cli/run.js:31:4)
    at run (/app/upm/tests/node_modules/@cucumber/cucumber/lib/cli/run.js:16:8)
    at <anonymous> (/app/upm/tests/node_modules/@cucumber/cucumber/bin/cucumber.js:2:37)
    at global code (/app/upm/tests/node_modules/@cucumber/cucumber/bin/cucumber.js:3:8)
error: "cucumber-js" exited with code 1 (SIGHUP)
```

### What is the expected behavior?

i expect the behavior with `--bun` to match this behavior, which is actually using node:

```sh
$ bun run cucumber-js      


0 scenarios
0 steps
0m00.000s (executing steps: 0m00.000s)
```

**Comment by birkskyum** [comment]
- https://github.com/oven-sh/bun/issues/3625

**Comment by muratbigin** [comment]
mubi@murats-MacBook-Pro OpusFlow % bun --bun run cucumber-js


0 scenarios
0 steps
0m00.000s
┌─────────────────────────────────────────────────────────────────────────────────┐
│ Cucumber is publishing new releases under @cucumber/cucumber on npm:            │
│ https://www.npmjs.com/package/@cucumber/cucumber                                │
│                                                                                 │
│ Features in the latest version include:                                         │
│ * BeforeEach and AfterEach hooks                                                │
│ * Searchable HTML reports                                                       │
│ * Native ESM support                                                            │
│ * Write scenarios in Markdown                                                   │
│                                                                                 │
│ Full changelog: https://github.com/cucumber/cucumber-js/blob/main/CHANGELOG.md  │
│ Upgrading guide: https://github.com/cucumber/cucumber-js/blob/main/UPGRADING.md │


Have any idea for solution
