### ISSUE TITLE
bun install doesn't work with workspaces

### ISSUE THREAD

**Issue by giladv** [oven-sh/bun#4628]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

1. create a simple workspaces setup
```json
"workspaces": {
    "packages": [
      "packages/*"
    ]
  }
```
2. on ``packages/package1`` do ``bun init``
3. run bun install from anywhere

### What is the expected behavior?

to install deps

### What do you see instead?

```
bun install v1.0.0 (822a00c4)
 + package1@workspace:packages/package1

 1 packages installed [7.00ms]
Failed to install 1 packages
error: Unexpected installing bun-types
```

**Comment by cpreston321** [comment]
Hey @giladv i think the way you setup the workspaces wrong. https://bun.sh/docs/install/workspaces

it should be 

```json
{
  "name": "my-project",
  "version": "1.0.0",
  "workspaces": ["packages/*"]
}
```

**Comment by giladv** [comment]
thanks, but still doesn't work with proposed change

**Comment by ferdy-roz** [comment]
only works for me for an internal package named `@foo/bar` in the `package.json` where I declare a dependency I name it like 

```
"@foo/bar": "workspace:bar"
```

 (as opposed to the docs, saying I should be able to declare a dep by naming it

```
"@foo/bar": "*"
```

**Comment by divmgl** [comment]
I have all of the setup correct and `bun i` runs immensely fast, which is super cool. Unfortunately, our monorepo doesn't work at all. Here's an example error we're getting:

```tsx
❯ pnpm dev

> @ dev /Users/dexter/dev/my_company/my_company
> pnpm -r --parallel dev:dr

Scope: 4 of 5 workspace projects
packages/queue dev:dr$ doppler run --project=my_company-queue --config=dev pnpm dev
packages/app dev:dr$ doppler run --project=my_company-app --config=dev pnpm dev
packages/server dev:dr$ doppler run --project=my_company-server --config=dev pnpm dev
packages/server dev:dr: > @my_company/server@0.0.0 dev /Users/dexter/dev/my_company/my_company/packages/server
packages/server dev:dr: > nodemon -q --exec node --inspect -r ts-node/register src/index.ts
packages/queue dev:dr: > @my_company/queue@0.0.0 dev /Users/dexter/dev/my_company/my_company/packages/queue
packages/queue dev:dr: > DEBUG=queue nodemon -q --exec node --inspect=9339 -r ts-node/register src/index.ts
packages/app dev:dr: > @my_company/app@0.0.0 dev /Users/dexter/dev/my_company/my_company/packages/app
packages/app dev:dr: > vite
packages/server dev:dr: Debugger listening on ws://127.0.0.1:9229/ff39403c-98bc-4710-9e62-5c7b7f5d7f9d
packages/server dev:dr: For help, see: https://nodejs.org/en/docs/inspector
packages/queue dev:dr: Debugger listening on ws://127.0.0.1:9339/8f64e0a1-9120-4696-a2bf-e1921ee1219e
packages/queue dev:dr: For help, see: https://nodejs.org/en/docs/inspector
packages/app dev:dr:   VITE v4.3.4  ready in 793 ms
packages/app dev:dr:   ➜  Local:   http://localhost:5173/
packages/app dev:dr:   ➜  Network: use --host to expose
packages/queue dev:dr: /Users/dexter/dev/my_company/my_company/node_modules/ts-node/src/index.ts:859
packages/queue dev:dr:     return new TSError(diagnosticText, diagnosticCodes, diagnostics);
packages/queue dev:dr:            ^
packages/queue dev:dr: TSError: ⨯ Unable to compile TypeScript:
packages/queue dev:dr: src/ManagedWorker.ts(31,7): error TS2322: Type 'Redis' is not assignable to type 'ConnectionOptions | undefined'.
packages/queue dev:dr:   Type 'import("/Users/dexter/dev/my_company/my_company/node_modules/ioredis/built/Redis").default' is not assignable to type 'import("/Users/dexter/dev/my_company/my_company/node_modules/bullmq/node_modules/ioredis/built/Redis").default'.
packages/queue dev:dr:     Types of property 'options' are incompatible.
packages/queue dev:dr:       Type 'import("/Users/dexter/dev/my_company/my_company/node_modules/ioredis/built/redis/RedisOptions").RedisOptions' is not assignable to type 'import("/Users/dexter/dev/my_company/my_company/node_modules/bullmq/node_modules/ioredis/built/redis/RedisOptions").RedisOptions'.
packages/queue dev:dr:         Type 'RedisOptions' is not assignable to type 'CommonRedisOptions'.
packages/queue dev:dr:           Types of property 'Connector' are incompatible.
packages/queue dev:dr:             Type 'import("/Users/dexter/dev/my_company/my_company/node_modules/ioredis/built/connectors/ConnectorConstructor").default | undefined' is not assignable to type 'import("/Users/dexter/dev/my_company/my_company/node_modules/bullmq/node_modules/ioredis/built/connectors/ConnectorConstructor").default | undefined'.
packages/queue dev:dr:               Type 'import("/Users/dexter/dev/my_company/my_company/node_modules/ioredis/built/connectors/ConnectorConstructor").default' is not assignable to type 'import("/Users/dexter/dev/my_company/my_company/node_modules/bullmq/node_modules/ioredis/built/connectors/ConnectorConstructor").default'.
packages/queue dev:dr:                 Type 'import("/Users/dexter/dev/my_company/my_company/node_modules/ioredis/built/connectors/AbstractConnector").default' is not assignable to type 'import("/Users/dexter/dev/my_company/my_company/node_modules/bullmq/node_modules/ioredis/built/connectors/AbstractConnector").default'.
packages/queue dev:dr:                   Property 'connecting' is protected but type 'AbstractConnector' is not a class derived from 'AbstractConnector'.
packages/queue dev:dr: src/ManagedWorker.ts(91,7): error TS2322: Type 'Redis' is not assignable to type 'ConnectionOptions | undefined'.
packages/queue dev:dr:     at createTSError (/Users/dexter/dev/my_company/my_company/node_modules/ts-node/src/index.ts:859:12)
packages/queue dev:dr:     at reportTSError (/Users/dexter/dev/my_company/my_company/node_modules/ts-node/src/index.ts:863:19)
packages/queue dev:dr:     at getOutput (/Users/dexter/dev/my_company/my_company/node_modules/ts-node/src/index.ts:1077:36)
packages/queue dev:dr:     at Object.compile (/Users/dexter/dev/my_company/my_company/node_modules/ts-node/src/index.ts:1433:41)
packages/queue dev:dr:     at Module.m._compile (/Users/dexter/dev/my_company/my_company/node_modules/ts-node/src/index.ts:1617:30)
packages/queue dev:dr:     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
packages/queue dev:dr:     at Object.require.extensions.<computed> [as .ts] (/Users/dexter/dev/my_company/my_company/node_modules/ts-node/src/index.ts:1621:12)
packages/queue dev:dr:     at Module.load (node:internal/modules/cjs/loader:1117:32)
packages/queue dev:dr:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
packages/queue dev:dr:     at Module.require (node:internal/modules/cjs/loader:1141:19) {
packages/queue dev:dr:   diagnosticCodes: [ 2322, 2322 ]
packages/queue dev:dr: }
packages/server dev:dr: /Users/dexter/dev/my_company/my_company/node_modules/ts-node/src/index.ts:859
packages/server dev:dr:     return new TSError(diagnosticText, diagnosticCodes, diagnostics);
packages/server dev:dr:            ^
packages/server dev:dr: TSError: ⨯ Unable to compile TypeScript:
packages/server dev:dr: src/index.ts(67,3): error TS2769: No overload matches this call.
packages/server dev:dr:   Overload 1 of 3, '(plugin: FastifyPluginCallback<FastifySentryOptions, RawServerDefault, FastifyTypeProviderDefault>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
packages/server dev:dr:     Type 'Http' is not assignable to type 'Integration'.
packages/server dev:dr:       Types of property 'setupOnce' are incompatible.
packages/server dev:dr:         Type '(_addGlobalEventProcessor: (callback: EventProcessor) => void, setupOnceGetCurrentHub: () => Hub) => void' is not assignable to type '(addGlobalEventProcessor: (callback: EventProcessor) => void, getCurrentHub: () => Hub) => void'.
packages/server dev:dr:           Types of parameters '_addGlobalEventProcessor' and 'addGlobalEventProcessor' are incompatible.
packages/server dev:dr:             Types of parameters 'callback' and 'callback' are incompatible.
packages/server dev:dr:               Type 'import("/Users/dexter/dev/my_company/my_company/node_modules/@sentry/types/types/eventprocessor").EventProcessor' is not assignable to type 'import("/Users/dexter/dev/my_company/my_company/node_modules/@immobiliarelabs/fastify-sentry/node_modules/@sentry/node/node_modules/@sentry/types/types/eventprocessor").EventProcessor'.
packages/server dev:dr:                 Types of parameters 'hint' and 'hint' are incompatible.
packages/server dev:dr:                   Type 'import("/Users/dexter/dev/my_company/my_company/node_modules/@immobiliarelabs/fastify-sentry/node_modules/@sentry/node/node_modules/@sentry/types/types/event").EventHint' is not assignable to type 'import("/Users/dexter/dev/my_company/my_company/node_modules/@sentry/types/types/event").EventHint'.
packages/server dev:dr:                     Types of property 'captureContext' are incompatible.
packages/server dev:dr:                       Type 'import("/Users/dexter/dev/my_company/my_company/node_modules/@immobiliarelabs/fastify-sentry/node_modules/@sentry/node/node_modules/@sentry/types/types/scope").CaptureContext | undefined' is not assignable to type 'import("/Users/dexter/dev/my_company/my_company/node_modules/@sentry/types/types/scope").CaptureContext | undefined'.
packages/server dev:dr:                         Type 'Scope' is not assignable to type 'CaptureContext | undefined'.
packages/server dev:dr:                           Type 'import("/Users/dexter/dev/my_company/my_company/node_modules/@immobiliarelabs/fastify-sentry/node_modules/@sentry/node/node_modules/@sentry/types/types/scope").Scope' is not assignable to type 'import("/Users/dexter/dev/my_company/my_company/node_modules/@sentry/types/types/scope").Scope'.
packages/server dev:dr:                             Types of property 'update' are incompatible.
packages/server dev:dr:                               Type '(captureContext?: import("/Users/dexter/dev/my_company/my_company/node_modules/@immobiliarelabs/fastify-sentry/node_modules/@sentry/node/node_modules/@sentry/types/types/scope").CaptureContext | undefined) => import("/Users/dexter/dev/my_company/my_company/node_modules/@immobiliarelabs/fastify-sentry/node_modules/@sen...' is not assignable to type '(captureContext?: import("/Users/dexter/dev/my_company/my_company/node_modules/@sentry/types/types/scope").CaptureContext | undefined) => import("/Users/dexter/dev/my_company/my_company/node_modules/@sentry/types/types/scope").Scope'.
packages/server dev:dr:                                 Types of parameters 'captureContext' and 'captureContext' are incompatible.
packages/server dev:dr:                                   Type 'import("/Users/dexter/dev/my_company/my_company/node_modules/@sentry/types/types/scope").CaptureContext | undefined' is not assignable to type 'import("/Users/dexter/dev/my_company/my_company/node_modules/@immobiliarelabs/fastify-sentry/node_modules/@sentry/node/node_modules/@sentry/types/types/scope").CaptureContext | undefined'.
packages/server dev:dr:                                     Type 'Scope' is not assignable to type 'CaptureContext | undefined'.
packages/server dev:dr:                                       Type 'import("/Users/dexter/dev/my_company/my_company/node_modules/@sentry/types/types/scope").Scope' is not assignable to type 'import("/Users/dexter/dev/my_company/my_company/node_modules/@immobiliarelabs/fastify-sentry/node_modules/@sentry/node/node_modules/@sentry/types/types/scope").Scope'.
packages/server dev:dr:                                         Types of property 'addEventProcessor' are incompatible.
packages/server dev:dr:                                           Type '(callback: import("/Users/dexter/dev/my_company/my_company/node_modules/@sentry/types/types/eventprocessor").EventProcessor) => import("/Users/dexter/dev/my_company/my_company/node_modules/@sentry/types/types/scope").Scope' is not assignable to type '(callback: import("/Users/dexter/dev/my_company/my_company/node_modules/@immobiliarelabs/fastify-sentry/node_modules/@sentry/node/node_modules/@sentry/types/types/eventprocessor").EventProcessor) => import("/Users/dexter/dev/my_company/my_company/node_modules/@immobiliarelabs/fastify-sentry/node_modules/@sentry/node/n...'.
packages/server dev:dr:                                             Types of parameters 'callback' and 'callback' are incompatible.
packages/server dev:dr:                                               Type 'import("/Users/dexter/dev/my_company/my_company/node_modules/@immobiliarelabs/fastify-sentry/node_modules/@sentry/node/node_modules/@sentry/types/types/eventprocessor").EventProcessor' is not assignable to type 'import("/Users/dexter/dev/my_company/my_company/node_modules/@sentry/types/types/eventprocessor").EventProcessor'.
packages/server dev:dr:                                                 Types of parameters 'event' and 'event' are incompatible.
packages/server dev:dr:                                                   Type 'import("/Users/dexter/dev/my_company/my_company/node_modules/@sentry/types/types/event").Event' is not assignable to type 'import("/Users/dexter/dev/my_company/my_company/node_modules/@immobiliarelabs/fastify-sentry/node_modules/@sentry/node/node_modules/@sentry/types/types/event").Event'.
packages/server dev:dr:                                                     Types of property 'spans' are incompatible.
packages/server dev:dr:                                                       Type 'import("/Users/dexter/dev/my_company/my_company/node_modules/@sentry/types/types/span").Span[] | undefined' is not assignable to type 'import("/Users/dexter/dev/my_company/my_company/node_modules/@immobiliarelabs/fastify-sentry/node_modules/@sentry/node/node_modules/@sentry/types/types/span").Span[] | undefined'.
packages/server dev:dr:                                                         Type 'import("/Users/dexter/dev/my_company/my_company/node_modules/@sentry/types/types/span").Span[]' is not assignable to type 'import("/Users/dexter/dev/my_company/my_company/node_modules/@immobiliarelabs/fastify-sentry/node_modules/@sentry/node/node_modules/@sentry/types/types/span").Span[]'.
packages/server dev:dr:                                                           Type 'import("/Users/dexter/dev/my_company/my_company/node_modules/@sentry/types/types/span").Span' is not assignable to type 'import("/Users/dexter/dev/my_company/my_company/node_modules/@immobiliarelabs/fastify-sentry/node_modules/@sentry/node/node_modules/@sentry/types/types/span").Span'.
packages/server dev:dr:                                                             Types of property 'name' are incompatible.
packages/server dev:dr:                                                               Type 'string | undefined' is not assignable to type 'string'.
packages/server dev:dr:                                                                 Type 'undefined' is not assignable to type 'string'.
packages/server dev:dr:   Overload 2 of 3, '(plugin: FastifyPluginAsync<FastifySentryOptions, RawServerDefault, FastifyTypeProviderDefault>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
packages/server dev:dr:     Argument of type 'FastifySentryPlugin' is not assignable to parameter of type 'FastifyPluginAsync<FastifySentryOptions, RawServerDefault, FastifyTypeProviderDefault>'.
packages/server dev:dr:       Target signature provides too few arguments. Expected 3 or more, but got 2.
packages/server dev:dr:   Overload 3 of 3, '(plugin: FastifyPluginCallback<FastifySentryOptions, RawServerDefault, FastifyTypeProviderDefault> | FastifyPluginAsync<...> | Promise<...> | Promise<...>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
packages/server dev:dr:     Type 'Http' is not assignable to type 'Integration'.
packages/server dev:dr:     at createTSError (/Users/dexter/dev/my_company/my_company/node_modules/ts-node/src/index.ts:859:12)
packages/server dev:dr:     at reportTSError (/Users/dexter/dev/my_company/my_company/node_modules/ts-node/src/index.ts:863:19)
packages/server dev:dr:     at getOutput (/Users/dexter/dev/my_company/my_company/node_modules/ts-node/src/index.ts:1077:36)
packages/server dev:dr:     at Object.compile (/Users/dexter/dev/my_company/my_company/node_modules/ts-node/src/index.ts:1433:41)
packages/server dev:dr:     at Module.m._compile (/Users/dexter/dev/my_company/my_company/node_modules/ts-node/src/index.ts:1617:30)
packages/server dev:dr:     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
packages/server dev:dr:     at Object.require.extensions.<computed> [as .ts] (/Users/dexter/dev/my_company/my_company/node_modules/ts-node/src/index.ts:1621:12)
packages/server dev:dr:     at Module.load (node:internal/modules/cjs/loader:1117:32)
packages/server dev:dr:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
packages/server dev:dr:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
packages/server dev:dr:   diagnosticCodes: [ 2769 ]
packages/server dev:dr: }
```

In other words, basically all of the packages fail with resolution errors.

**Comment by divmgl** [comment]
^^^ disregard my last comment. This was user error. `node_modules` wasn't completely wiped in all subdirectories.

**Comment by divmgl** [comment]
^^^ I was able to confirm that this happens when multiple versions of the same package are resolved. I upgraded my `ioredis` version up to parity with BullMQ's and it started working. It'd be nice to not have to do this.

**Comment by joswayski** [comment]
--- retracting my comment until i can do more testing sorry :$

**Comment by giladv** [comment]
just to be clear, the bug i'm mentioning has nothing to do with referring to other workspace packages. the most basic workspace setup does not work currently

**Comment by dylang** [comment]
I'm seeing this as well. I'm not sure if you are running into the same symptom though.

For me, it's going through the work of installing all dependencies, but only `node_modules` in the root exists at the end. Workspaces with conflicting versions don't have their own `node_modules` directories with their specific version of those modules.

My issue is the same as this: https://github.com/oven-sh/bun/issues/4274

**Comment by ferdy-roz** [comment]
my symptoms were that it couldn't resolve dependencies that were in the same monorepo (i.e. one workspace depending on another). i seem to have solved it by simply removing those dependencies altogether from the workspace package.jsons

**Comment by Borjagodoy** [comment]
In my case I think I have the same error as you, I'm doing the example that comes in the bun doc on monorepos using workspaces and the problem comes when calling a component within another, ie stuff-a as a dependency of stuff-b, there is no way to detect it. I think it is for lack of scope ... believe that the issue is the same as this one 

https://github.com/oven-sh/bun/issues/3806

[EDIT]: Feel like if you import the dependencie in stuff-b as  `"dependencies": {   "stuff-a": "workspace:*"}` works the bun install, but persist the problem when you do a bun add

**Comment by Jarred-Sumner** [comment]
This specific scenario no longer occurs, most likely as of a few versions ago but certainly at least on Bun v1.0.11
<img width="418" alt="image" src="https://github.com/oven-sh/bun/assets/709451/ace8983a-08d4-412a-a492-28e6f4cc6af1">

**Comment by quantizor** [comment]
@Jarred-Sumner this is still broken, you can see it in action for styled-components in this PR https://github.com/styled-components/styled-components/pull/3959

`packages/styled-components` should use react 17 and `packages/sandbox` should use react 18

if you run `bun run test` you'll see all the failures from the mismatching React version that don't exist in trunk when they were consistent

**Comment by quantizor** [comment]
Opened a new issue https://github.com/oven-sh/bun/issues/7791
