### ISSUE TITLE
Fastify randomly fails on plugin registration

### ISSUE THREAD

**Issue by divmgl** [oven-sh/bun#4641]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

```json
// package.json
{
  "dependencies": {
    "bullmq": "3.6.2",
    "fastify": "^4.22.2",
    "ioredis": "5.3.0"
  }
}
```
```ts
import fastify from "fastify";
import { Redis } from "ioredis";
import { Queue } from "bullmq";

const redis = new Redis();
const bullmq = new Queue("my-random-queue", {
  connection: redis,
});

function createPlugin() {
  return (fastify, opts, done) => {
    fastify.get("/health", (_req, res) => {
      res.send("OK!").status(200);
    });

    done();
  };
}

async function start() {
  const server = fastify();

  server.register(createPlugin());

  await server.listen({ host: "0.0.0.0", port: 13337 });
}

void start();
```
```
$ bun i
$ bun --watch run index.ts
```

### What is the expected behavior?

It works.

### What do you see instead?
Run it, and then you'll get:

```
29 |   if (cache) {
30 |     const keys = Object.keys(cache)
31 |
32 |     for (let i = 0; i < keys.length; i++) {
33 |       const key = keys[i]
34 |       if (cache[key].exports === func) {
             ^
TypeError: undefined is not an object (evaluating 'cache[key].exports')
      at getPluginName (/Users/dimgl/dev/playground/bun-testing/node_modules/fastify/lib/pluginUtils.js:34:10)
      at override (/Users/dimgl/dev/playground/bun-testing/node_modules/fastify/lib/pluginOverride.js:30:17)
      at /Users/dimgl/dev/playground/bun-testing/node_modules/avvio/plugin.js:79:20
      at loadPlugin (/Users/dimgl/dev/playground/bun-testing/node_modules/avvio/plugin.js:272:2)
      at processTicksAndRejections (:1:2602)
```

### Additional information

This is not the only issue it's having. It's also having a TypeScript bug, I'll open a separate ticket for this.

**Comment by mthalesb** [comment]
Same error here. I'm using Ubuntu 22.04 with WSL 2

**Comment by gabeklavans** [comment]
I get the exact same error when trying to register a custom router block, specifically while ALSO establishing a db connection with supabase-js. Very strange, doesn't happen when I run the same code with ts-node. 

Here's my minimal example:
```typescript
import { createClient } from "@supabase/supabase-js";
import Fastify, { FastifyInstance } from "fastify";

export const fastify = Fastify({});

fastify.register((fastify: FastifyInstance, opt, done) => {
    fastify.get("/hi", (req, reply) => {
        reply.send(200)
    })

    done();
});

const supabase = createClient("url", "api-key");

fastify.listen({ host: "127.0.0.1", port: 3001 });
```

Running on Ubuntu jammy inside docker, bun 1.0.1

**Comment by fabiancook** [comment]
This was what I was running into here: https://github.com/oven-sh/bun/issues/4880 

1.0.2 may have resolved your issue. I see fastify receiving requests with 1.0.2 in an environment that it hadn't with 1.0.0 -> https://github.com/opennetwork/logistics/actions/runs/6206964124/job/16851733018#step:11:749

**Comment by divmgl** [comment]
@fabiancook you're absolutely right. This is fixed. Huge.
