### ISSUE TITLE
Error running bun nextjs app in docker

### ISSUE THREAD

**Issue by abhi12299** [oven-sh/bun#4671]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

1. Run `bunx create-next-app` command to initialise a new nextjs app.

2. Add the following `Dockerfile` to the project:

```dockerfile
FROM oven/bun:1.0

WORKDIR /app

COPY package.json .

COPY bun.lockb .

RUN bun install

COPY . .

CMD [ "bun", "run", "dev"]
```

3. Build the docker image:

```bash
docker build -t bunnext:latest .
```

4. Run the docker image:

```bash
docker run -p 3000:3000 bunnext:latest
```

5. Open the browser at localhost:3000 and the container stops without any error message.

### What is the expected behavior?

The container should keep running and the web app should load successfully.

### Additional information

1. The `bun run dev` command works fine outside of Docker.
2. Docker is running on M1.

**Comment by abhi12299** [comment]
Container logs before it stops:

<img width="860" alt="image" src="https://github.com/oven-sh/bun/assets/36722596/1116eb25-2dc3-4a1f-96dd-c113473ec8c0">

**Comment by karthik-js** [comment]
@abhi12299 Try running again. It added necessary types to make it typescript worthy. It should work the next time

**Comment by abhi12299** [comment]
No luck with that too. Did the necessary changes in `tsconfig.json` and it still exits without any error message.

```js
// tsconfig.json
{
    "compilerOptions": {
        // ...,
        "plugins": [
            {
                "name": "next"
            }
        ]
    },
    "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"]
}
```

<img width="501" alt="image" src="https://github.com/oven-sh/bun/assets/36722596/7e081075-bbbf-4a9a-a795-112f858f0f99">

**Comment by phijma-leukeleu** [comment]
Got exactly the same problem, using Nuxt. Same cause probably. 😢

**Comment by peterhijma** [comment]
Got the same problem with Nuxt.

**Comment by karthik-js** [comment]
Observations: 

Next.js spawns workers to handle routing etc.

I have created two projects with [app router](https://github.com/karthik-js/bun-next-app-dir) and [pages router](https://github.com/karthik-js/bun-next-pages-dir)

When we run the projects locally, they work fine. 

But when run in Docker they fail with the same error:
![Screenshot 2023-09-10 at 12 35 08 AM](https://github.com/oven-sh/bun/assets/40170831/d757199a-8630-4c51-8fd0-d8ccdf1d9b71)

So the possible options to get this result:

1. Either we are doing something wrong with how we are using the image (which is highly unlikely)
2. Bun has issues with the creation of workers as the error points out in the screenshot i.e. failing to find port

@peterhijma Most probably the same issue with Nuxt

**Comment by ericklarsen** [comment]
@karthik-js I also got quite similiar issue with you. I still can't run my nextjs app with bun run dev.
![image](https://github.com/oven-sh/bun/assets/32609329/30f4d9b7-c1b2-4761-8c9d-c520d776a1db)

**Comment by karthik-js** [comment]
@ericklarsen not sure if that is same issue. It shows in ur error that it is a dom exception. If you can share a repro repo. I will try to debug and help you

**Comment by terion-labs** [comment]
Getting in docker:

```
bun install v1.0.0 (822a00c4)
ERROR  EBADF: Bad file descriptor
at <anonymous> (node_modules/nuxi/dist/shared/nuxi.615ae2d1.mjs:5962:29)
at <anonymous> (node_modules/nuxi/dist/shared/nuxi.31a0124f.mjs:11:30)
...
ERROR  EBADF: Bad file descriptor
Checked 1049 installs across 970 packages (no changes) [1235.00ms]
error: script "postinstall" exited with code 1 (SIGHUP)
```

**Comment by karthik-js** [comment]
Issue is already being tracked by the bun team here: https://github.com/oven-sh/bun/issues/3776

**Comment by abhi12299** [comment]
@karthik-js I think that the issue you're referencing is different from this one. Here it fails inside of docker, works well without it.

**Comment by karthik-js** [comment]
Check the 3rd point where he mentions worker threads. It was added to the bun. Now Next.js companion PR has to be merged and needs to be released.

**Comment by terion-labs** [comment]
> Check the 3rd point where he mentions worker threads. It was added to the bun. Now Next.js companion PR has to be merged and needs to be released.

It's not only about Next, seems to be more general

**Comment by p2pdops** [comment]
Looks like `PORT` environment variable is `0` somehow,
Maybe bun is parsing empty env variable of PORT, which would be null to `0`


I'm able to run next.js with bun inside docker ( same docker file of @abhi12299 )

Just created .env file with 
```
PORT=3002
```
Make sure .dockerignore not excluding .env and run
`docker build -t bun-next-test:latest .` 
`docker run -p 3002:3002 bun-next-test` 

<img width="605" alt="image" src="https://github.com/oven-sh/bun/assets/48751317/ce6352e9-671c-4ebf-bd21-ee5e6ca1f0da">

Other way without .env file is using `docker run -e`

`docker run -p 3002:3002 -e PORT='3002' bun-next-test` 


*chose port number 3002 because other ports in my machine are busy

**Comment by landsman** [comment]
I noticed a similar thing when I used bun only as a docker image for an app that uses npm as a package manager. I wasn't able to build it inside a docker container.

```log
Step 6/20 : RUN bun run build
 ---> Running in 3c9568b05b80
$ next build
error: script "build" exited with code 11 (SIGSEGV)
```

**Comment by jamierpond** [comment]
@landsman same here

**Comment by karthik-js** [comment]
@landsman same here

**Comment by annminn104** [comment]
> Observations:
> 
> Next.js spawns workers to handle routing etc.
> 
> I have created two projects with [app router](https://github.com/karthik-js/bun-next-app-dir) and [pages router](https://github.com/karthik-js/bun-next-pages-dir)
> 
> When we run the projects locally, they work fine.
> 
> But when run in Docker they fail with the same error: ![Screenshot 2023-09-10 at 12 35 08 AM](https://user-images.githubusercontent.com/40170831/266798506-d757199a-8630-4c51-8fd0-d8ccdf1d9b71.png)
> 
> So the possible options to get this result:
> 
> 1. Either we are doing something wrong with how we are using the image (which is highly unlikely)
> 2. Bun has issues with the creation of workers as the error points out in the screenshot i.e. failing to find port
> 
> @peterhijma Most probably the same issue with Nuxt

I also got the same error when building with nextjs. My console log also shows the same error. I wonder if you have found any solution
