### ISSUE TITLE
Error encountered while executing create-astro@latest command

### ISSUE THREAD

**Issue by jgalaber** [oven-sh/bun#4672]
### What is the type of issue?

Example code is not working

### What is the issue?

Hello,

First and foremost, I wanted to extend my heartfelt congratulations for the outstanding work you are doing. I'm genuinely impressed and love the product you are putting out.

However, while I was following the provided documentation, I encountered an issue with the create-astro command:

`bunx create-astro@latest my-astro-project-using-bun`

The error message returned is as follows:

```
610 |   }
611 |   get stdio() {
612 |     return this.#stdioObject ??= this.#createStdioObject();
613 |   }
614 |

615 |   spawn(options) {
                 ^
ENOSYS: Function not implemented
 syscall: "open"
   errno: -38
      at spawn (node:child_process:615:14)
      at node:child_process:2:40
      at node:child_process:33:44
      at /home/jgalaber/.bun/install/global/node_modules/create-astro/dist/index.js:277:2
      at new Promise (:1:20)
      at getName (/home/jgalaber/.bun/install/global/node_modules/create-astro/dist/index.js:276:33)
      at /home/jgalaber/.bun/install/global/node_modules/create-astro/dist/index.js:438:49
      at getContext (/home/jgalaber/.bun/install/global/node_modules/create-astro/dist/index.js:415:26)
      at /home/jgalaber/.bun/install/global/node_modules/create-astro/dist/index.js:1112:20
error: "create-astro" exited with code 1 (SIGHUP).
```

Best regards,

Jgalaber

### Where did you find it?

https://docs.astro.build/es/recipes/bun/

_No response_

**Comment by noClaps** [comment]
Try using `bunx create-astro my-astro-project-using-bun`. I think the `@latest` part is what breaks it.

https://bun.sh/guides/ecosystem/astro

**Comment by jgalaber** [comment]
> Try using `bunx create-astro my-astro-project-using-bun`. I think the `@latest` part is what breaks it.
> 
> https://bun.sh/guides/ecosystem/astro

Hello,

Thank you, but I have already tried that command and it doesn't work. I'm encountering the exact same issue. Also, the @latest does not affect.

**Comment by Mis-nomer** [comment]
With the latest version of Bun, you can use `bun create astro@latest my-astro-project-using-bun`
