### ISSUE TITLE
TypeError: process.binding("tty_wrap") is not implemented in Bun.

### ISSUE THREAD

**Issue by legzdev** [oven-sh/bun#4694]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.4.12-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

Execute a script (`bun script.js`) with:

```js
const input = require("readline-sync").question

let text = input("Input: ")
```

### What is the expected behavior?

Wait for a text input from the user

### What do you see instead?

```
1 | (function (bindingName){"use strict";if(bindingName==="constants")return @processBindingConstants;const issue={fs:3546,buffer:2020,natives:2254,uv:2891}[bindingName];if(issue)throw new Error(`process.binding("${bindingName}") is not implemented in Bun. Track the status & thumbs up the issue: https://github.com/oven-sh/bun/issues/${issue}`);@throwTypeError(`process.binding("${bindingName}") is not implemented in Bun. If that breaks something, please file an issue and include a reproducible code sample.`)})
                       ^
TypeError: process.binding("tty_wrap") is not implemented in Bun. If that breaks something, please file an issue and include a reproducible code sample.
      at binding (:1:20)
      at /home/ghost/node_modules/readline-sync/lib/readline-sync.js:19:8
      at globalThis (/home/ghost/node_modules/readline-sync/lib/readline-sync.js:1329:78)
      at require (:1:20)
      at /home/ghost/bing.js:2:6
      at globalThis (/home/ghost/bing.js:208:5)
```

**Comment by mifopen** [comment]
same with importing `ioredis-mock` which is quite popular.
`ioredis-mock` -> `fengari` -> `readline-sync`

**Comment by peterabrahamdev** [comment]
I had the same error and it's probably due to the "readline-sync" import. When I took it out of my project, the error went away.

**Comment by Jarred-Sumner** [comment]
This will ship in Bun v1.0.23
