### ISSUE TITLE
Sveltekit +page.server.js unable to find bun:sqlite

### ISSUE THREAD

**Issue by Mehdi-YC** [oven-sh/bun#4704]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.3.11-200.fc38.x86_64 x86_64 unknown

### What steps can reproduce the bug?

install sveltekit , drizzle orm , and have bun installed

create adatabase , 

try to import the database from $lib/server/database.js to your +page.server.js

### What is the expected behavior?

import the db and use it to load some data

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/44881216/4bde1588-7e1b-457b-8944-6508e690d60c)

**Comment by kuatroka** [comment]
I'be got the same on mac

I also tried a simpler option
//+page.svelte
```
<script>
import { Database } from "bun:sqlite";

const db = new Database(":memory:");
const query = db.query("select 'Hello world' as message;");
export const result = query.get(); // => { message: "Hello world" }

</script>

<h1>
    {JSON.stringify(result, null, 2)}
</h1>
```

Error output
```
3:46:02 PM [vite] Error when evaluating SSR module /src/routes/test/+page.svelte: failed to import "bun:sqlite"
|- Error: Cannot find module 'bun:sqlite' imported from '/Users/yo_macbook/Documents/dev/test-bun/src/routes/test/+page.svelte'
    at nodeImport (file:///Users/yo_macbook/Documents/dev/test-bun/node_modules/vite/dist/node/chunks/dep-df561101.js:56010:25)
    at ssrImport (file:///Users/yo_macbook/Documents/dev/test-bun/node_modules/vite/dist/node/chunks/dep-df561101.js:55912:30)
    at eval (/Users/yo_macbook/Documents/dev/test-bun/src/routes/test/+page.svelte:4:37)
    at async instantiateModule (file:///Users/yo_macbook/Documents/dev/test-bun/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9)

Internal server error: Cannot find module 'bun:sqlite' imported from '/Users/yo_macbook/Documents/dev/test-bun/src/routes/test/+page.svelte'
      at nodeImport (file:///Users/yo_macbook/Documents/dev/test-bun/node_modules/vite/dist/node/chunks/dep-df561101.js:56010:25)
      at ssrImport (file:///Users/yo_macbook/Documents/dev/test-bun/node_modules/vite/dist/node/chunks/dep-df561101.js:55912:30)
      at eval (/Users/yo_macbook/Documents/dev/test-bun/src/routes/test/+page.svelte:4:37)
      at async instantiateModule (file:///Users/yo_macbook/Documents/dev/test-bun/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9)
Error: Cannot find module 'bun:sqlite' imported from '/Users/yo_macbook/Documents/dev/test-bun/src/routes/test/+page.svelte'
    at nodeImport (file:///Users/yo_macbook/Documents/dev/test-bun/node_modules/vite/dist/node/chunks/dep-df561101.js:56010:25)
    at ssrImport (file:///Users/yo_macbook/Documents/dev/test-bun/node_modules/vite/dist/node/chunks/dep-df561101.js:55912:30)
    at eval (/Users/yo_macbook/Documents/dev/test-bun/src/routes/test/+page.svelte:4:37)
    at async instantiateModule (file:///Users/yo_macbook/Documents/dev/test-bun/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9) {
  code: 'ERR_MODULE_NOT_FOUND'
  ```

**Comment by kuatroka** [comment]
I have also tried to install 'better-sqlite3' and use that instead of the native bun:sqlite, but getting errors here too
```
3:55:15 PM [vite] Error when evaluating SSR module /src/routes/superinvestors_sqlite/+page.server.ts: failed to import "/src/lib/server/db/sqlite.ts"
|- Error: Could not locate the bindings file. Tried:
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/build/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/compiled/18.16.0/darwin/arm64/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/lib/binding/node-v108-darwin-arm64/better_sqlite3.node
    at bindings (/Users/yo_macbook/Documents/dev/test-bun/node_modules/bindings/bindings.js:126:9)
    at new Database (/Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/lib/database.js:48:64)
    at eval (/Users/yo_macbook/Documents/dev/test-bun/src/lib/server/db/sqlite.ts:7:12)
    at async instantiateModule (file:///Users/yo_macbook/Documents/dev/test-bun/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9)

Internal server error: Could not locate the bindings file. Tried:
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/build/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/compiled/18.16.0/darwin/arm64/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/lib/binding/node-v108-darwin-arm64/better_sqlite3.node
      at bindings (/Users/yo_macbook/Documents/dev/test-bun/node_modules/bindings/bindings.js:126:9)
      at new Database (/Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/lib/database.js:48:64)
      at eval (/Users/yo_macbook/Documents/dev/test-bun/src/lib/server/db/sqlite.ts:7:12)
      at async instantiateModule (file:///Users/yo_macbook/Documents/dev/test-bun/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9)
Error: Could not locate the bindings file. Tried:
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/build/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/compiled/18.16.0/darwin/arm64/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/lib/binding/node-v108-darwin-arm64/better_sqlite3.node
    at bindings (/Users/yo_macbook/Documents/dev/test-bun/node_modules/bindings/bindings.js:126:9)
    at new Database (/Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/lib/database.js:48:64)
    at eval (/Users/yo_macbook/Documents/dev/test-bun/src/lib/server/db/sqlite.ts:7:12)
    at async instantiateModule (file:///Users/yo_macbook/Documents/dev/test-bun/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9) {
  tries: [
    '/Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/build/better_sqlite3.node',
    '/Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/build/Debug/better_sqlite3.node',
    '/Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/build/Release/better_sqlite3.node',
    '/Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/out/Debug/better_sqlite3.node',
    '/Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/Debug/better_sqlite3.node',
    '/Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/out/Release/better_sqlite3.node',
    '/Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/Release/better_sqlite3.node',
    '/Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/build/default/better_sqlite3.node',
    '/Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/compiled/18.16.0/darwin/arm64/better_sqlite3.node',
    '/Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node',
    '/Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node',
    '/Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node',
    '/Users/yo_macbook/Documents/dev/test-bun/node_modules/better-sqlite3/lib/binding/node-v108-darwin-arm64/better_sqlite3.node'
  ]
}
```

Another maybe related thing that errors out is the `tsconfig.json` file even after adding the 'bun-types' to it

![image](https://github.com/oven-sh/bun/assets/9093546/fac6f9bd-9134-4c77-8b91-e7c921ae12d0)

**Comment by Mehdi-YC** [comment]
@kuatroka  the better-sqlite3 is actually a "better-sqlite3" problem and not related with bun at all , you need to build it or something go check in the repo's issues

**Comment by kuatroka** [comment]
Ok, thanks. I thought bun was a drop-in replacement for node, so my assumption was/is that I can just install node packages with no fuss. Isn't that so?

**Comment by Mehdi-YC** [comment]
@kuatroka yes you can but if you try now better-sqlite3 will not work ven with node so it's not related with bun at all

**Comment by pdenapo** [comment]
How are exactly running your svelte-kit project? With the bun adapter?
Beware that if you run it with

bun run dev

(and not with bun --bun run dev), this runs vite and vite might run your script using node!

I suggest that you add a test to see if your code is really running under bun, like

console.log(typeof Bun)

(returns object under Bun, but undefined under node)

Also I suggest that you share an example code in a public github repository, so everyone here 
can run your code exactly in the same way that you did.

[see https://bun.sh/guides/ecosystem/vite ]

**Comment by kuatroka** [comment]
Thanks a lot @pdenapo ! That's exactly the kind of helpful answers that one is very keen to see🙏
I was running it wrong.

After running it as you suggested `bun --bun run dev` all good and functions as it should. Again thanks a lot.
My issues is solved.
`Sveltekit `+page.server.ts` finds 'bun:sqlite' and runs it perfectly

**Comment by buzzy** [comment]
@pdenapo Thank you! I had the same issue! The bun people should really make it MUCH clearer that you need to use the --bun parameter. Why in the world is that not the default when running the bun binary???

**Comment by SlavenIvanov** [comment]
Why do we need to run with `--bun` . Can't bun do that automatically?
