### ISSUE TITLE
gulp not running due to node:Console

### ISSUE THREAD

**Issue by noraj** [oven-sh/bun#4737]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.4.12-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

- bun add gulp
- bun install
- bun run gulp

### What is the expected behavior?

gulp running like it would on nodejs

### What do you see instead?

```
➜ bun run gulp
15 | 
16 | // Needed to add this because node 10 decided to start coloring log output randomly
17 | var console;
18 | if (nodeVersion.major >= 10) {
19 |   // Node 10 also changed the way this is constructed
20 |   console = new Console({
                ^
TypeError: undefined is not a constructor (evaluating 'new Console({
      stdout: process.stdout,
      stderr: process.stderr,
      colorMode: !1
    })')
      at /home/noraj/Dev/rawsec-cybersecurity-inventory/node_modules/fancy-log/index.js:20:12
      at globalThis (/home/noraj/Dev/rawsec-cybersecurity-inventory/node_modules/fancy-log/index.js:92:23)
      at require (:1:20)
      at /home/noraj/Dev/rawsec-cybersecurity-inventory/node_modules/gulp-cli/lib/shared/log/to-console.js:3:4
      at globalThis (/home/noraj/Dev/rawsec-cybersecurity-inventory/node_modules/gulp-cli/lib/shared/log/to-console.js:58:17)
      at require (:1:20)
      at /home/noraj/Dev/rawsec-cybersecurity-inventory/node_modules/gulp-cli/index.js:20:4
      at globalThis (/home/noraj/Dev/rawsec-cybersecurity-inventory/node_modules/gulp-cli/index.js:111:17)
```

### Additional information

Ref. https://bun.sh/docs/runtime/nodejs-apis

> If you run into any bugs with a particular package, please [open an issue](https://bun.sh/issues). Opening issues for compatibility bugs helps us prioritize what to work on next.

Seems due at least to [node:console](https://nodejs.org/api/console.html) incomplete support.

Asking for bun support on upstream https://github.com/gulpjs/gulp/issues/2737

**Comment by brianblakely** [comment]
This issue also blocks compatibility with [patch-console](https://www.npmjs.com/package/patch-console) ([relevant source code](https://github.com/vadimdemedes/patch-console/blob/master/source/index.ts#L41)), which is used by packages like [Ink](https://www.npmjs.com/package/ink).

**Comment by rvbuelow** [comment]
Seems to be this issue https://github.com/oven-sh/bun/issues/3625

**Comment by noraj** [comment]
The console part seems to be fixed so now it can run but there is another issue for gulp.

## bun 1.0.3

```
$ bun run build    
$ gulp
[20:30:03] Using gulpfile ~/Dev/rawsec-cybersecurity-inventory/gulpfile.mjs
[20:30:03] Starting 'default'...
[20:30:03] Starting 'clean'...
[20:30:03] The following tasks did not complete: default, clean
[20:30:03] Did you forget to signal async completion?
```

## nodejs 20.2.0

```
 npm run build                                                                                                                                                                                               [10/26]
                                                                                                                                                                                                                     
> rawsec-cybersecurity-list@1.0.0 build                                                                                                                                                                              
> gulp                                                                                                                                                                                                               
                                                                                                                                                                                                                     
[20:28:43] Using gulpfile ~/Dev/rawsec-cybersecurity-inventory/gulpfile.mjs                                                                                                                                          
[20:28:43] Starting 'default'...                                                                                                                                                                                     
[20:28:43] Starting 'clean'...                                                                                                                                                                                       
[20:28:43] Finished 'clean' after 8.57 ms                                                                                                                                                                            
[20:28:43] Starting 'build'...                                                                                                                                                                                       
[20:28:43] Starting 'pug_data'...                                                                                                                                                                                    
[20:28:43] Finished 'pug_data' after 884 ms                                                               
[20:28:43] Starting 'count_items'...                                                                      
[20:28:43] Finished 'count_items' after 769 μs                                                            
[20:28:43] Starting 'pug_src'...                                                                          
Number of items: 1382                                                                                     
[20:28:45] Finished 'pug_src' after 2 s                                                                   
[20:28:45] Starting 'api_clean'...                                                                        
[20:28:46] Finished 'api_clean' after 328 ms                                                              
[20:28:46] Starting 'api_build'...                                                                        
[20:28:46] Finished 'api_build' after 236 ms                                                              
[20:28:46] Starting 'api_copy'...                                                                         
[20:28:47] Finished 'api_copy' after 1.34 s
[20:28:47] Starting 'bulma'...      
[20:28:47] Starting 'bulmajs'...              
[20:28:47] Starting 'tablefilter'...
[20:28:47] Starting 'sweetalert2'...
[20:28:47] Starting 'jquery'...        
[20:28:47] Starting 'minisearch'...
[20:28:47] Starting 'js'...                 
[20:28:47] Starting 'fontawesome'...
[20:28:47] Starting 'font_mfizz'...         
[20:28:47] Starting 'images'...  
[20:28:47] Starting 'css'...               
[20:28:50] Finished 'sweetalert2' after 2.81 s
[20:28:50] Finished 'jquery' after 2.81 s
[20:28:50] Finished 'css' after 2.81 s
[20:28:50] Finished 'bulma' after 2.84 s
[20:28:50] Finished 'bulmajs' after 2.84 s
[20:28:50] Finished 'minisearch' after 2.86 s
[20:28:50] Finished 'font_mfizz' after 3.03 s
[20:28:50] Finished 'images' after 3.07 s
[20:28:51] Finished 'tablefilter' after 3.35 s
[20:28:51] Finished 'js' after 3.52 s
[20:28:51] Finished 'fontawesome' after 3.56 s
[20:28:51] Finished 'build' after 8.35 s
[20:28:51] Finished 'default' after 8.36 s
```
