### ISSUE TITLE
Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by anexa-digital** [oven-sh/bun#4819]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64 / Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

1.  ` bun i --save venom-bot`
2.  create a simple server.ts importing venom package
3.  `bun run server.ts`

### What is the expected behavior?

Run server.ts without error.

### What do you see instead?

Something went wrong installing the "sharp" module

Cannot find module "../build/Release/sharp-linux-x64.node" from "/home/gerardo/dev/venom/node_modules/sharp/lib/sharp.js"

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
      at /home/gerardo/dev/venom/node_modules/sharp/lib/sharp.js:34:8
      at globalThis (/home/gerardo/dev/venom/node_modules/sharp/lib/sharp.js:34:33)
      at require (:1:20)
      at /home/gerardo/dev/venom/node_modules/sharp/lib/constructor.js:8:0
      at globalThis (/home/gerardo/dev/venom/node_modules/sharp/lib/constructor.js:386:17)
      at require (:1:20)
      at /home/gerardo/dev/venom/node_modules/sharp/lib/index.js:3:6
      at globalThis (/home/gerardo/dev/venom/node_modules/sharp/lib/index.js:13:17)

**Comment by anexa-digital** [comment]
Duplicated  https://github.com/oven-sh/bun/issues/4549
