### ISSUE TITLE
MongoDb driver crashes using node:net on localhost

### ISSUE THREAD

**Issue by RodolphoVSantoro** [oven-sh/bun#4832]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.5.2-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

1. Lift a mongoDb server locally on the port 27017
2. Create a database 'mongo-app'
3. Create this package json:
```json
{ 
    "dependencies": { 
        "mongodb": "^5.8.0"
    } 
}
```

4. Create this env file:
```
connectionString="mongodb://localhost:27017"
dbName="mongo-app"
```

5. Create this index.ts
```ts
import { MongoClient } from "mongodb";

const connectionString = process.env.connectionString;
if(!connectionString) {
    throw new Error("No connection string provided");
}

const client = new MongoClient(connectionString);

const dbName = process.env.dbName;
if(!dbName) {
    throw new Error("No db name provided");
}
const clientConnection = await client.connect();
const db = client.db(dbName);

const animalsSchema = db.collection("animals");

await animalsSchema.insertOne({ name: "dog", age: 5 });
const result = await animalsSchema.findOne();
console.log(result);

await clientConnection.close();
```

6. Run `bun run index.ts`

### What is the expected behavior?

The script should create a document on the mongo database, and log it to the console

### What do you see instead?

The terminal looks like this after i execute the script
```sh
[0.04ms] ".env"
[0.00ms] ".env"
214 |     if (this.remotePort = port, socket.data = this, socket.timeout(this.timeout), socket.ref(), this[bunSocketInternal] = socket, this.connecting = !1, !this.#upgraded)
215 |       this.emit("connect", this);
216 |     Socket2.#Drain(socket);
217 |   }
218 | 
219 |   connect(port, host, connectListener) {
                     ^
error: Failed to connect
      at connect (node:net:219:18)
      at makeConnection (/home/rodolphovs/Desktop/projects/bun-mongoose/node_modules/mongodb/lib/cmap/connect.js:276:17)
      at connect (/home/rodolphovs/Desktop/projects/bun-mongoose/node_modules/mongodb/lib/cmap/connect.js:33:4)
      at checkServer (/home/rodolphovs/Desktop/projects/bun-mongoose/node_modules/mongodb/lib/sdam/monitor.js:204:4)
      at /home/rodolphovs/Desktop/projects/bun-mongoose/node_modules/mongodb/lib/sdam/monitor.js:237:8
      at /home/rodolphovs/Desktop/projects/bun-mongoose/node_modules/mongodb/lib/sdam/monitor.js:341:12
      at new MonitorInterval (/home/rodolphovs/Desktop/projects/bun-mongoose/node_modules/mongodb/lib/sdam/monitor.js:352:12)
      at connect (/home/rodolphovs/Desktop/projects/bun-mongoose/node_modules/mongodb/lib/sdam/monitor.js:91:27)
      at connect (/home/rodolphovs/Desktop/projects/bun-mongoose/node_modules/mongodb/lib/sdam/server.js:106:12)
214 |     if (this.remotePort = port, socket.data = this, socket.timeout(this.timeout), socket.ref(), this[bunSocketInternal] = socket, this.connecting = !1, !this.#upgraded)
215 |       this.emit("connect", this);
216 |     Socket2.#Drain(socket);
217 |   }
218 | 
219 |   connect(port, host, connectListener) {
                     ^
error: Failed to connect
      at connect (node:net:219:18)
      at makeConnection (/home/rodolphovs/Desktop/projects/bun-mongoose/node_modules/mongodb/lib/cmap/connect.js:276:17)
      at connect (/home/rodolphovs/Desktop/projects/bun-mongoose/node_modules/mongodb/lib/cmap/connect.js:33:4)
      at checkServer (/home/rodolphovs/Desktop/projects/bun-mongoose/node_modules/mongodb/lib/sdam/monitor.js:204:4)
      at /home/rodolphovs/Desktop/projects/bun-mongoose/node_modules/mongodb/lib/sdam/monitor.js:237:8
      at /home/rodolphovs/Desktop/projects/bun-mongoose/node_modules/mongodb/lib/sdam/monitor.js:341:12
      at new MonitorInterval (/home/rodolphovs/Desktop/projects/bun-mongoose/node_modules/mongodb/lib/sdam/monitor.js:352:12)
      at connect (/home/rodolphovs/Desktop/projects/bun-mongoose/node_modules/mongodb/lib/sdam/monitor.js:91:27)
      at connect (/home/rodolphovs/Desktop/projects/bun-mongoose/node_modules/mongodb/lib/sdam/server.js:106:12)
92 |  * @privateRemarks
93 |  * mongodb-client-encryption has a dependency on this error, it uses the constructor with a string argument
94 |  */
95 | class MongoError extends Error {
96 |     constructor(message) {
97 |         super(MongoError.buildErrorMessage(message));
            ^
error: Server selection timed out after 30000 ms
 code: "undefined"

      at new MongoError (/home/rodolphovs/Desktop/projects/bun-mongoose/node_modules/mongodb/lib/error.js:97:8)
      at new MongoSystemError (/home/rodolphovs/Desktop/projects/bun-mongoose/node_modules/mongodb/lib/error.js:622:12)
      at new MongoServerSelectionError (/home/rodolphovs/Desktop/projects/bun-mongoose/node_modules/mongodb/lib/error.js:641:8)
      at /home/rodolphovs/Desktop/projects/bun-mongoose/node_modules/mongodb/lib/sdam/topology.js:278:37
```

### Additional information

- It only happens on my local database. I can connect to an atlas database using https
- I can connect to my local database using node 12, 16, 18 and 20
- The issue seems to be related to not using TLS on localhost. It crashes when the mongo driver does :
```ts
const net = require("net");
// driver code continues...
if (useTLS) {
  // driver code continues...
}
else {
  socket = net.createConnection({host: "localhost", port: 27017}); // <--- crashes here
}
```

**Comment by nmrusso** [comment]
Same here! But thank you I am going to test with mongo atlas.

**Comment by ivanbacher** [comment]
I had a similar error. Try changing `localhost` to `127.0.0.1` in your connection string. This worked for me.

**Comment by RodolphoVSantoro** [comment]
> I had a similar error. Try changing `localhost` to `127.0.0.1` in your connection string. This worked for me.

Same error for me even with `connectionString="mongodb://127.0.0.1:27017"` unfortunately

**Comment by cirospaciari** [comment]
@RodolphoVSantoro can you tell me more about the version of MongoDB that you are running? did you try the docker image https://hub.docker.com/_/mongo? also can you try the `mongodb` 6.0.0?

**Comment by RodolphoVSantoro** [comment]
@cirospaciari @ivanbacher @Murzbul 
Using that mongo docker image solved it
Even on `mongodb 5.8.0`
Thanks!
