### ISSUE TITLE
Bun Install - Arm64(M1) - Incompatible Architecture (node-expat)

### ISSUE THREAD

**Issue by codebykenny** [oven-sh/bun#4833]
### What version of Bun is running?

1.0

### What platform is your computer?

Darwin 22.1.0 arm64 arm

### What steps can reproduce the bug?

```bash
bun install xml2json
```

```js
// index.js
const xml2json = require("xml2json");
```

```bash
bun run index.js
```

### What is the expected behavior?

Bun install should correctly install the `arm64` version of node-export submodule, instead it seems to be installing the `x86_64` version

### What do you see instead?

```bash
~/Coding/bun-xml2json ❯ bun run index.js 
1 | (function (id){"use strict";var cached=@requireMap.@get(id);const last5=id.substring(id.length-5);if(cached)return cached.exports;if(last5===".json"){var fs=globalThis[Symbol.for("_fs")]||=@Bun.fs(),exports=JSON.parse(fs.readFileSync(id,"utf8"));return @requireMap.@set(id,@createCommonJSModule(id,exports,!0)),exports}else if(last5===".node"){const module=@createCommonJSModule(id,{},!0);return process.dlopen(module,id),@requireMap.@set(id,module),module.exports}else if(last5===".toml"){var fs=globalThis[Symbol.for("_fs")]||=@Bun.fs(),exports=@Bun.TOML.parse(fs.readFileSync(id,"utf8"));return @requireMap.@set(id,@createCommonJSModule(id,exports,!0)),exports}else{var exports=@requireESM(id);const cachedModule=@requireMap.@get(id);if(cachedModule)return cachedModule.exports;return @requireMap.@set(id,@createCommonJSModule(id,exports,!0)),exports}})
                       ^
TypeError: dlopen(/Users/kenny/Coding/bun-xml2json/node_modules/node-expat/build/Release/node_expat.node, 0x0001): tried: '/Users/kenny/Coding/bun-xml2json/node_modules/node-expat/build/Release/node_expat.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/kenny/Coding/bun-xml2json/node_modules/node-expat/build/Release/node_expat.node' (no such file), '/Users/kenny/Coding/bun-xml2json/node_modules/node-expat/build/Release/node_expat.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
      at internalRequire (:1:20)
      at bindings (/Users/kenny/Coding/bun-xml2json/node_modules/bindings/bindings.js:112:47)
      at /Users/kenny/Coding/bun-xml2json/node_modules/node-expat/lib/node-expat.js:4:6
      at globalThis (/Users/kenny/Coding/bun-xml2json/node_modules/node-expat/lib/node-expat.js:113:9)
      at require (:1:20)
      at /Users/kenny/Coding/bun-xml2json/node_modules/xml2json/lib/xml2json.js:1:4
      at globalThis (/Users/kenny/Coding/bun-xml2json/node_modules/xml2json/lib/xml2json.js:185:11)
      at require (:1:20)
      at /Users/kenny/Coding/bun-xml2json/node_modules/xml2json/lib/index.js:3:8
      at globalThis (/Users/kenny/Coding/bun-xml2json/node_modules/xml2json/lib/index.js:4:8)
      at require (:1:20)
      at /Users/kenny/Coding/bun-xml2json/node_modules/xml2json/index.js:1:7
      at globalThis (/Users/kenny/Coding/bun-xml2json/node_modules/xml2json/index.js:1:7)
      at require (:1:20)
      at /Users/kenny/Coding/bun-xml2json/index.js:1:6
      at globalThis (/Users/kenny/Coding/bun-xml2json/index.js:1:6)
```

### Additional information

MacOS 13.0 Ventura

Apple M1 Max

**Comment by ekhodx** [comment]
Does this module work on arm64 from nodejs?

I tried running your example on arm64 linux (also M1 machine if you are curios)
Platform: `Linux 6.4.0-asahi-10-edge-ARCH aarch64 unknown`

<details>

<summary>
And I guess I get different error then yours
</summary>

```
121 |         throw e;
122 |       }
123 |     }
124 |   }
125 |
126 |   err = new Error(
            ^
error: Could not locate the bindings file. Tried:
 → /home/zerdox/projects/personal/playground/xml2json/node_modules/node-expat/lib/build/node_expat.node
 → /home/zerdox/projects/personal/playground/xml2json/node_modules/node-expat/lib/build/Debug/node_expat.node
 → /home/zerdox/projects/personal/playground/xml2json/node_modules/node-expat/lib/build/Release/node_expat.node
 → /home/zerdox/projects/personal/playground/xml2json/node_modules/node-expat/lib/out/Debug/node_expat.node
 → /home/zerdox/projects/personal/playground/xml2json/node_modules/node-expat/lib/Debug/node_expat.node
 → /home/zerdox/projects/personal/playground/xml2json/node_modules/node-expat/lib/out/Release/node_expat.node
 → /home/zerdox/projects/personal/playground/xml2json/node_modules/node-expat/lib/Release/node_expat.node
 → /home/zerdox/projects/personal/playground/xml2json/node_modules/node-expat/lib/build/default/node_expat.node
 → /home/zerdox/projects/personal/playground/xml2json/node_modules/node-expat/lib/compiled/18.15.0/linux/arm64/node_expat.node
 → /home/zerdox/projects/personal/playground/xml2json/node_modules/node-expat/lib/addon-build/release/install-root/node_expat.node
 → /home/zerdox/projects/personal/playground/xml2json/node_modules/node-expat/lib/addon-build/debug/install-root/node_expat.node
 → /home/zerdox/projects/personal/playground/xml2json/node_modules/node-expat/lib/addon-build/default/install-root/node_expat.node
 → /home/zerdox/projects/personal/playground/xml2json/node_modules/node-expat/lib/lib/binding/node-v108-linux-arm64/node_expat.node
      at bindings (/home/zerdox/projects/personal/playground/xml2json/node_modules/bindings/bindings.js:126:8)
      at /home/zerdox/projects/personal/playground/xml2json/node_modules/node-expat/lib/node-expat.js:4:6
      at globalThis (/home/zerdox/projects/personal/playground/xml2json/node_modules/node-expat/lib/node-expat.js:113:9)
      at require (:1:20)
      at /home/zerdox/projects/personal/playground/xml2json/node_modules/xml2json/lib/xml2json.js:1:4
      at globalThis (/home/zerdox/projects/personal/playground/xml2json/node_modules/xml2json/lib/xml2json.js:185:11)
      at require (:1:20)
      at /home/zerdox/projects/personal/playground/xml2json/node_modules/xml2json/lib/index.js:3:8
      at globalThis (/home/zerdox/projects/personal/playground/xml2json/node_modules/xml2json/lib/index.js:4:8)
      at require (:1:20)
      at /home/zerdox/projects/personal/playground/xml2json/node_modules/xml2json/index.js:1:7
      at globalThis (/home/zerdox/projects/personal/playground/xml2json/node_modules/xml2json/index.js:1:7)
      at require (:1:20)
      at /home/zerdox/projects/personal/playground/xml2json/index.js:1:6
      at globalThis (/home/zerdox/projects/personal/playground/xml2json/index.js:1:6)
```

</details>

**Comment by birkskyum** [comment]
probably needs the 
- #606

**Comment by birkskyum** [comment]
try adding trustedDependencies:["xml2json", "node-expat"] in package.json, delete bun.lockb and node_modules, and then `bun install` again.
- #4959

**Comment by ekhodx** [comment]
> try adding trustedDependencies:["xml2json", "node-expat"] in package.json, delete bun.lockb and node_modules, and then bun install again. 

Also cleared bun's global cache because there was feeling that nothing changed at all, deps were installed in less then a second.

```
rm -rf ~/.local/share/bun/install/cache/ ./node_modules/ ./bun.lockb
bun install
bun run index.js
```

Nothing changed

**Comment by codebykenny** [comment]
@ZerdoX-x yes this dependency works with node on arm64

@birkskyum I did what you suggested and I still receive the same error.

```json
{
	"name": "bun-xml2json",
	"version": "1.0.0",
	"description": "",
	"main": "index.js",
	"scripts": {
		"test": "echo \"Error: no test specified\" && exit 1"
	},
	"keywords": [],
	"author": "",
	"license": "ISC",
	"dependencies": {
		"xml2json": "^0.12.0"
	},
	"trustedDependencies": [
		"xml2json",
		"node-expat"
	]
}
```

```bash
~/Coding/bun-xml2json ❯ bun run index.js 
1 | (function (id){"use strict";var cached=@requireMap.@get(id);const last5=id.substring(id.length-5);if(cached)return cached.exports;if(last5===".json"){var fs=globalThis[Symbol.for("_fs")]||=@Bun.fs(),exports=JSON.parse(fs.readFileSync(id,"utf8"));return @requireMap.@set(id,@createCommonJSModule(id,exports,!0)),exports}else if(last5===".node"){const module=@createCommonJSModule(id,{},!0);return process.dlopen(module,id),@requireMap.@set(id,module),module.exports}else if(last5===".toml"){var fs=globalThis[Symbol.for("_fs")]||=@Bun.fs(),exports=@Bun.TOML.parse(fs.readFileSync(id,"utf8"));return @requireMap.@set(id,@createCommonJSModule(id,exports,!0)),exports}else{var exports=@requireESM(id);const cachedModule=@requireMap.@get(id);if(cachedModule)return cachedModule.exports;return @requireMap.@set(id,@createCommonJSModule(id,exports,!0)),exports}})
                       ^
TypeError: dlopen(/Users/kenny/Coding/bun-xml2json/node_modules/node-expat/build/Release/node_expat.node, 0x0001): tried: '/Users/kenny/Coding/bun-xml2json/node_modules/node-expat/build/Release/node_expat.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/kenny/Coding/bun-xml2json/node_modules/node-expat/build/Release/node_expat.node' (no such file), '/Users/kenny/Coding/bun-xml2json/node_modules/node-expat/build/Release/node_expat.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
      at internalRequire (:1:20)
      at bindings (/Users/kenny/Coding/bun-xml2json/node_modules/bindings/bindings.js:112:47)
      at /Users/kenny/Coding/bun-xml2json/node_modules/node-expat/lib/node-expat.js:4:6
      at globalThis (/Users/kenny/Coding/bun-xml2json/node_modules/node-expat/lib/node-expat.js:113:9)
      at require (:1:20)
      at /Users/kenny/Coding/bun-xml2json/node_modules/xml2json/lib/xml2json.js:1:4
      at globalThis (/Users/kenny/Coding/bun-xml2json/node_modules/xml2json/lib/xml2json.js:185:11)
      at require (:1:20)
      at /Users/kenny/Coding/bun-xml2json/node_modules/xml2json/lib/index.js:3:8
      at globalThis (/Users/kenny/Coding/bun-xml2json/node_modules/xml2json/lib/index.js:4:8)
      at require (:1:20)
      at /Users/kenny/Coding/bun-xml2json/node_modules/xml2json/index.js:1:7
      at globalThis (/Users/kenny/Coding/bun-xml2json/node_modules/xml2json/index.js:1:7)
      at require (:1:20)
      at /Users/kenny/Coding/bun-xml2json/index.js:1:6
      at globalThis (/Users/kenny/Coding/bun-xml2json/index.js:1:6)
      ```

**Comment by codebykenny** [comment]
This is still happening on bun `1.0.6`

**Comment by Electroid** [comment]
Duplicate of #4959 (we fill fix this)
