### ISSUE TITLE
Cannot call a class constructor without |new|

### ISSUE THREAD

**Issue by endel** [oven-sh/bun#5006]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

```typescript
import http from "http";

class MyClass {
  constructor() {
    http.OutgoingMessage.call(this);
  }
}

const instance = new MyClass();
console.log(instance);
```

### What is the expected behavior?

❯ npx tsx cannot-call-a-class-constructor.ts

```
MyClass {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  outputData: [],
  outputSize: 0,
  writable: true,
  destroyed: false,
  _last: false,
  chunkedEncoding: false,
  shouldKeepAlive: true,
  maxRequestsOnConnectionReached: false,
  _defaultKeepAlive: true,
  useChunkedEncodingByDefault: true,
  sendDate: false,
  _removedConnection: false,
  _removedContLen: false,
  _removedTE: false,
  strictContentLength: false,
  _contentLength: null,
  _hasBody: true,
  _trailer: '',
  finished: false,
  _headerSent: false,
  _closed: false,
  socket: null,
  _header: null,
  _keepAliveTimeout: 0,
  _onPendingData: [Function: nop],
  [Symbol(kCapture)]: false,
  [Symbol(kBytesWritten)]: 0,
  [Symbol(kNeedDrain)]: false,
  [Symbol(corked)]: 0,
  [Symbol(kOutHeaders)]: null,
  [Symbol(errored)]: null
}
```

### What do you see instead?

❯ bun run cannot-call-a-class-constructor.ts

```
516 |   }
517 | }
518 |
519 | class OutgoingMessage extends Writable {
520 |
521 |   constructor() {
                             ^
TypeError: Cannot call a class constructor without |new|
      at OutgoingMessage (node:http:521:26)
      at new MyClass (/Users/endel/Projects/colyseus/bun-express/cannot-call-a-class-constructor.ts:5:4)
      at /Users/endel/Projects/colyseus/bun-express/cannot-call-a-class-constructor.ts:9:17
```

### Additional information

This code runs correctly using `npx tsx cannot-call-a-class-constructor.ts`

**Comment by sirenkovladd** [comment]
related to https://github.com/oven-sh/bun/issues/4415

**Comment by RyanWhipple** [comment]
I believe I have the same issue using `nock` and `axios`

```typescript
import axios from "axios"
import * as nock from "nock"

nock.load(filepathToPreviouslySavedNockRecording.json)

const bulbasaur = await axios({
  method: "GET",
  url: "https://pokeapi.co/api/v2/pokemon/bulbasaur"
})
```

I get:
```console
519 | class OutgoingMessage extends Writable {
520 | 
521 |   constructor() {
                             ^
TypeError: Cannot call a class constructor without |new|
      at OutgoingMessage (node:http:521:26)
      at new OverriddenClientRequest (/Users/rwhipple/Documents/study-bun/node_modules/nock/lib/intercept.js:279:4)
      at /Users/rwhipple/Documents/study-bun/node_modules/nock/lib/intercept.js:427:13
      at /Users/rwhipple/Documents/study-bun/node_modules/nock/lib/common.js:96:13
      at /Users/rwhipple/Documents/study-bun/node_modules/follow-redirects/index.js:284:8
      at new RedirectableRequest (/Users/rwhipple/Documents/study-bun/node_modules/follow-redirects/index.js:66:2)
      at request (/Users/rwhipple/Documents/study-bun/node_modules/follow-redirects/index.js:523:13)
      at /Users/rwhipple/Documents/study-bun/node_modules/axios/lib/adapters/http.js:438:10
      at dispatchHttpRequest (/Users/rwhipple/Documents/study-bun/node_modules/axios/lib/adapters/http.js:149:54)
      at /Users/rwhipple/Documents/study-bun/node_modules/axios/lib/adapters/http.js:143:4
```

**Comment by dhrn** [comment]
+1

**Comment by karl-run** [comment]
Related to #4787, seems to be the same underlying cause.

**Comment by alexmacarthur** [comment]
I'm seeing the same issue using [Inquirer.js](https://github.com/SBoudrias/Inquirer.js).

**Comment by gvilums** [comment]
Can't repro this on 1.1.7 so I'm going to close this, if it's still relevant feel free to reopen
