### ISSUE TITLE
ReferenceError: Can't find variable: __dirname

### ISSUE THREAD

**Issue by kenzuya** [oven-sh/bun#5094]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.2.0-32-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Create file `test.js`
```js
// test.js

// @bun
console.log(__dirname);

```
2. Run `bun run test.js`

### What is the expected behavior?

```console
/home/kenzuya/Projects/WatchDown-Bot
```

### What do you see instead?

```console
1 | 
2 | console.log(__dirname);
               ^
ReferenceError: Can't find variable: __dirname
      at /home/kenzuya/Projects/WatchDown-Bot/test.js:2:12
```

**Comment by jonathangaldino** [comment]
I'm experiencing the same.

1. Building the project`$ bun build ./src/index.ts --outdir ./build --target bun`
2. `$ bun run build/index.js`
Output:

```bash
➜  bun run build/index.js                                
[0.54ms] ".env.local"
1 | __dirname
   ^
ReferenceError: Can't find variable: __dirname
      at /Users/john/www/bunapp/build/index.js:24576:69
API is listening on port 3000
```

The app runs, but any requests throws this reference error.

**Comment by 5ch3m45** [comment]
I'm experiencing too.
1. Create bun using expressjs and prisma sqlite
2. Build the project `bun build ./server.ts --compile --outfile maul`
Then i got:
```
maulanaia@Maulanas-MacBook-Pro bun % ./maul
1 | __dirname
   ^
ReferenceError: Can't find variable: __dirname
      at compiled://root/maul:23326:69
      at processTicksAndRejections (:1:2602)
Listening on port 8080...
```

**Comment by surajmandalcell** [comment]
Facing the same issue when compiling
```js
bun build ./src/index.ts --outfile ./dist/server --compile
```

Error:
```
❯ ./dist/server
1 | __dirname
   ^
ReferenceError: Can't find variable: __dirname
      at compiled://root/server:25756:69
      at processTicksAndRejections (:1:2602)
Listening: http://localhost:3001
```

**Comment by CaptainN** [comment]
I'm getting a similar error after compilation (`bun build ./src/index.ts --outdir ./dist --target bun`)- I think it's from the prisma client package, and it seems to be this bit of output code wrapped in an eval:

```js
dirname = (0, eval)("__dirname")
```

BTW, if I use my extant swc transpilation step, that export set (it's separate js files) runs just fine under bun - cool!

**Comment by henriquebonfim** [comment]
get the same error using `bun init` with prisma.

error:

```
ReferenceError: __dirname is not defined in ES module scope
    at <anonymous> (/workspaces/<MY_PROJECT>/api/src/server.ts:18:15)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

Node.js v18.17.1
Bun 1.0.1

Edit:

Currently using this workaround (https://github.com/oven-sh/bun/issues/2865):

```
import path from 'path';
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
```

**Comment by SDrinkwater** [comment]
I am also getting the same error on bun v1.0.2 with Prisma v5.3.1:

```
__dirname
^
ReferenceError: Can't find variable: __dirname
```

**Comment by manutzsong** [comment]
For Prisma. Follow this link code [https://github.com/prisma/prisma/issues/4816#issuecomment-1399967863](https://github.com/prisma/prisma/issues/4816#issuecomment-1399967863)

```
import type { PrismaClient as ImportedPrismaClient } from '@prisma/client';
import { createRequire } from 'module';

const require = createRequire(import.meta.url ?? __filename);

const { PrismaClient: RequiredPrismaClient } = require('@prisma/client');

const _PrismaClient: typeof ImportedPrismaClient = RequiredPrismaClient;

export class PrismaClient extends _PrismaClient {}
```

**Comment by jaspersmitNL** [comment]
Is there any propper fix for this?

**Comment by Klerith** [comment]
Facing the same issue here.

**Comment by Hanaasagi** [comment]
same to https://github.com/oven-sh/bun/issues/4301

**Comment by nektro** [comment]
this looks to be working now. are you able to confirm?

**Comment by qlaffont** [comment]
@nektro can confirm it still doesn't work : 
![image](https://github.com/oven-sh/bun/assets/10044790/c6381ed5-b410-46cc-971d-a735e451d6e6)

**Comment by BrianIto** [comment]
This is fixed using Bun 1.1.24 in my working directory.

The problem is when Bun is compiled, it came with no such file or directory on Unix-based (Linux x64 or Dawin, macOS).

ENOENT: No such file or directory
   errno: -2
 syscall: "open"
   path: "/home/runner/work/<PROJECT_NAME>/<PROJECT_NAME>/<FILE>"

I understand this, because it really doesnt exists. I need a workaround, just out of ideas. haha
