### ISSUE TITLE
bun run dev crashes when using create-next-app

### ISSUE THREAD

**Issue by michidk** [oven-sh/bun#5135]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```
❯ bunx create-next-app --typescript --tailwind --eslint
✔ What is your project named? … test
✔ Would you like to use `src/` directory? … No / **Yes**
✔ Would you like to use App Router? (recommended) … No / **Yes**
✔ Would you like to customize the default import alias? … **No** / Yes
Creating a new Next.js app in [REDACTED].
[...]
[install completes successful]
 cd test
 bun run dev
```

### What is the expected behavior?

Web server starts and bun don't crashes

### What do you see instead?

```
❯ bun run dev
$ next dev
[REDACTED]/test/node_modules/next/dist/server/web/spec-extension/adapters/headers.js:187
    [Symbol.iterator]() {
            ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> ([REDACTED]/test/node_modules/next/dist/server/web/spec-extension/adapters/headers.js:187:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> ([REDACTED]/test/node_modules/next/dist/server/api-utils/index.js:67:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

**Comment by abdulahmad586** [comment]
Upgrading my node version to 18.18.2 worked for me! or whatever the LTS is

**Comment by Electroid** [comment]
That is an error stack from Node.js. If you want to run it using Bun, run: `bun --bun run dev`
