### ISSUE TITLE
Incorrect line and column numbers when SyntaxError happens

### ISSUE THREAD

**Issue by telesvar** [oven-sh/bun#5192]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

Run:

```js
function testStrictMode() {
    with ({ a: 1 }) {  // Should throw an error in strict mode.
        console.log(a);
    }
}

testStrictMode();
```

### What is the expected behavior?

```
1 | function testStrictMode() {
2 |     with ({ a: 1 }) {  // Should throw an error in strict mode
        ^
SyntaxError: 'with' statements are not valid in strict mode.
      at /Users/aidarhanovs/Projects/exp/Scanner.ts:2:5
```

### What do you see instead?

```
1 | function testStrictMode() {
2 |     with ({ a: 1 }) {  // Should throw an error in strict mode
3 |         console.log(a);
            ^
SyntaxError: 'with' statements are not valid in strict mode.
      at /Users/aidarhanovs/Projects/exp/Scanner.ts:3:8
```

### Additional information

Not only the line number is incorrect but the column number is off-by-one. So, the starting position of the `console` is actually 3:9.

**Comment by RiskyMH** [comment]
A less interesting error now:
```js
% bun index.js
 6 |     "use strict";
 7 | 
 8 |     //
 9 |     if (entry.instantiate)
10 |         return entry.instantiate;
11 |     var instantiatePromise = (async () => {
                                               ^
TypeError: Expected CommonJS module to have a function wrapper. If you weren't messing around with Bun's internals, this is a bug in Bun
```
