### ISSUE TITLE
Bun install has trouble with `sharp` npm package

### ISSUE THREAD

**Issue by sbdchd** [oven-sh/bun#5193]
### What version of Bun is running?

1.0.1

### What platform is your computer?

Darwin 21.5.0 arm64 arm

### What steps can reproduce the bug?

```
bun init -y
bun add sharp
echo "import sharp from 'sharp';sharp()" > index.ts
bun run index.ts
```

### What is the expected behavior?

runs successfully

### What do you see instead?

```
❯ bun run index.ts                                                                     5.55s
32 |     if (loadedModule) {
33 |       const [, loadedPackage] = loadedModule.match(/node_modules[\\/]([^\\/]+)[\\/]/);
34 |       help.push(`- Ensure the version of sharp aligns with the ${loadedPackage} package: "npm ls sharp"`);
35 |     }
36 |   }
37 |   throw new Error(help.join('\n'));
            ^
error: 
Something went wrong installing the "sharp" module

Cannot find module "../build/Release/sharp-darwin-arm64v8.node" from "~/Downloads/test/node_modules/sharp/lib/sharp.js"

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
      at ~/Downloads/test/node_modules/sharp/lib/sharp.js:37:8
      at globalThis (~/Downloads/test/node_modules/sharp/lib/sharp.js:37:33)
      at require (:1:20)
      at ~/Downloads/test/node_modules/sharp/lib/constructor.js:11:0
      at globalThis (~/Downloads/test/node_modules/sharp/lib/constructor.js:439:17)
      at require (:1:20)
      at ~/Downloads/test/node_modules/sharp/lib/index.js:6:6
      at globalThis (~/Downloads/test/node_modules/sharp/lib/index.js:16:17)
```

**Comment by ghost** [comment]
This can be closed as issue is already open. https://github.com/oven-sh/bun/issues/4549
