### ISSUE TITLE
node:vm runInThisContext options is ignored

### ISSUE THREAD

**Issue by ArtemGovorov** [oven-sh/bun#5221]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### What steps can reproduce the bug?

test.js
```
try {
    require('node:vm').runInThisContext(`boom;`, { filename: 'sample.js', lineOffset: 2 })
} catch (e) {
    console.log(e.stack)
}
```

node
```
$ node test.js
sample.js:3
boom;
^

ReferenceError: boom is not defined
    at sample.js:3:1
    (irrelevant bits of stack)
```

bun
```
$ bun run test.js
ReferenceError: Can't find variable: boom
    at eval code (:1:5)
    (irrelevant bits of stack)
```

### What is the expected behavior?

Instead of outputting the provided file name and using the provided line shift like node and printing `at sample.js:3:1`, Bun prints `at eval code (:1:5)`.

**Comment by Jarred-Sumner** [comment]
yeah we have not implemented these options yet

**Comment by Jarred-Sumner** [comment]
```
site on  main [$?⇣] via 🍞 v1.2.22
❯ bun-v1.1.27 a.js
ReferenceError: Can't find variable: boom
    at eval code (sample.js:2:5)
    at runInThisContext (native)
    at <anonymous> (/Users/jarred/Code/site/a.js:2:24)
    at <anonymous> (:11:43)

site on  main [$?⇣] via 🍞 v1.2.22
❯ bun-v1.1.26 a.js
ReferenceError: Can't find variable: boom
    at eval code (file:///:1:5)
    at runInThisContext (native)
    at <anonymous> (/Users/jarred/Code/site/a.js:2:24)
    at <anonymous> (:11:43)
```

Implemented in Bun v1.1.27 (current version is 1.2.21, sorry we took awhile to update this issue)
