### ISSUE TITLE
`ReferenceError`: Can't find variable: `indexedDB`

### ISSUE THREAD

**Issue by talensjr** [oven-sh/bun#5245]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Running bun to run the entry file of the project, for example:
```sh
bun app.js
```

where app.js loads the dependency:
```ts
const logger = require("parse-server").logger;

logger.info("started listening on 8080");
```

I don't know how to create an online reproducible sandbox with Bun and dependencies installed.

Throws an error and exits the process.

### What is the expected behavior?

Project runs correctly, same as it does with `node`.

### What do you see instead?

```sh
16 |         request.onabort = request.onerror = () => reject(request.error);
17 |     });
18 | }
19 | function createStore(dbName, storeName) {
20 |     const dbp = safariFix__default['default']().then(() => {
21 |         const request = indexedDB.open(dbName);
                            ^
ReferenceError: Can't find variable: indexedDB
      at /home/talensjr/www/revieve/revieve-server/node_modules/idb-keyval/dist/index.cjs:21:24
      at processTicksAndRejections (:1:2602)
```

### Additional information

The package that throws the error is a dependency of [parse](https://github.com/parse-community/Parse-SDK-JS).

**Comment by talensjr** [comment]
It also gives this following error
```sh
360 |   var keys = Object.keys(add), i = keys.length;
361 |   while (i--)
362 |     origin[keys[i]] = add[keys[i]];
363 |   return origin;
364 | 
365 | }, kCustomPromisifiedSymbol = Symbol.for("util.promisify.custom"), promisify = function promisify2(original) {
                                                                                                                                                                                                       ^
TypeError: The "original" argument must be of type Function
      at promisify2 (node:util:365:196)
      at /home/talensjr/www/revieve/revieve-server/node_modules/jose/lib/jwk/key/rsa.js:13:24
      at globalThis (/home/talensjr/www/revieve/revieve-server/node_modules/jose/lib/jwk/key/rsa.js:117:17)
      at require (:1:20)
      at /home/talensjr/www/revieve/revieve-server/node_modules/jose/lib/jwk/import.js:7:6
      at globalThis (/home/talensjr/www/revieve/revieve-server/node_modules/jose/lib/jwk/import.js:134:17)
      at require (:1:20)
      at /home/talensjr/www/revieve/revieve-server/node_modules/jose/lib/help/get_key.js:3:6
      at globalThis (/home/talensjr/www/revieve/revieve-server/node_modules/jose/lib/help/get_key.js:33:27)
      at require (:1:20)
      at /home/talensjr/www/revieve/revieve-server/node_modules/jose/lib/jwe/encrypt.js:6:6
      at globalThis (/home/talensjr/www/revieve/revieve-server/node_modules/jose/lib/jwe/encrypt.js:214:17)
      at require (:1:20)
      at /home/talensjr/www/revieve/revieve-server/node_modules/jose/lib/jwe/index.js:1:6
      at globalThis (/home/talensjr/www/revieve/revieve-server/node_modules/jose/lib/jwe/index.js:15:25)
      at require (:1:20)
      at /home/talensjr/www/revieve/revieve-server/node_modules/jose/lib/index.js:2:2
      at globalThis (/home/talensjr/www/revieve/revieve-server/node_modules/jose/lib/index.js:8:0)
      at require (:1:20)
      at /home/talensjr/www/revieve/revieve-server/node_modules/jwks-rsa/src/utils.js:1:6
      at globalThis (/home/talensjr/www/revieve/revieve-server/node_modules/jwks-rsa/src/utils.js:19:0)
      at require (:1:20)
      at /home/talensjr/www/revieve/revieve-server/node_modules/jwks-rsa/src/JwksClient.js:2:8
      at globalThis (/home/talensjr/www/revieve/revieve-server/node_modules/jwks-rsa/src/JwksClient.js:91:0)
      at require (:1:20)
      at /home/talensjr/www/revieve/revieve-server/node_modules/jwks-rsa/src/index.js:1:8
      at globalThis (/home/talensjr/www/revieve/revieve-server/node_modules/jwks-rsa/src/index.js:22:35)
      at require (:1:20)
      at /home/talensjr/www/revieve/revieve-server/node_modules/parse-server/lib/Adapters/Auth/apple.js:7:6
      at globalThis (/home/talensjr/www/revieve/revieve-server/node_modules/parse-server/lib/Adapters/Auth/apple.js:94:0)
      at require (:1:20)
      at /home/talensjr/www/revieve/revieve-server/node_modules/parse-server/lib/Adapters/Auth/index.js:7:6
```

but I've already mentioned it in [this issue](https://github.com/oven-sh/bun/issues/5122)

**Comment by talensjr** [comment]
Looks like the original issue has been somehow solved, I am not able to reproduce it again. 
I've tested fresh install with both `bun` and `npm`, and the running the script with `bun`, and it is not showing anymore, weird because I am on the same version of bun still, but seems that it is not happening anymore.
I will close this issue for now.
