### ISSUE TITLE
ReferenceError: Bun is not defined

### ISSUE THREAD

**Issue by bobbymannino** [oven-sh/bun#5263]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

Create a SvelteKit project and then install bun-types. Try and add `Bun.version` into the code anywhere - client or server - throws an error.

### What is the expected behavior?

It causes a 500 error

### Additional information

Am i doing something wrong?

**Comment by g-ioannou** [comment]
Got the same issue with sveltekit on Darwin 22.3.0 arm64 arm.

Used `Bun.password` which ran initally, but got `ReferenceError: Bun is not defined` after a while.

Using `Bun.password` outside of of the sveltekit project works as expected.

**Comment by Jarred-Sumner** [comment]
It’s running in Node. Make sure you pass -b or —bun

**Comment by bobbymannino** [comment]
Tried that as well. Get this error

```
failed to load config from /Users/bobbymannino/Library/Mobile Documents/com~apple~CloudDocs/Sites/Demos/view-transitions-api-demo/vite.config.ts
error when starting dev server:
undefined
error: script "dev" exited with code 1 (SIGHUP)
```

And i have installed the bun sveltekit adapter too

**Comment by fractal-solutions** [comment]
Getting the same issue using Bun.sleepSync(100) inside the loader.load() function of a GLTFLoader in Three.js.

![IMG_20230913_202221_114.jpg](https://github.com/oven-sh/bun/assets/125031230/8ae8b396-118a-4016-aa3f-70a658ebb86e)

**Comment by ThatXliner** [comment]
> Tried that as well. Get this error
> 
> ```
> failed to load config from /Users/bobbymannino/Library/Mobile Documents/com~apple~CloudDocs/Sites/Demos/view-transitions-api-demo/vite.config.ts
> error when starting dev server:
> undefined
> error: script "dev" exited with code 1 (SIGHUP)
> ```
> 
> And i have installed the bun sveltekit adapter too

Had this error to when i was trying to run SvelteKit with `bun --bun`.  (Bun 1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983, Darwin 22.5.0 x86_64 i386). This issue is reported [here](https://github.com/oven-sh/bun/issues/5100) as well (I haven’t found the *oldest* issue that reports this problem though)

**Comment by emircanerkul** [comment]
+1, I also observed the same problem while using sveltekit +page.svelte

**Comment by wpmcdonnell** [comment]
Same with Vite + React + SWC

**Comment by jokroese** [comment]
I'm experiencing this issue with SvelteKit too. Is there anything I can do to help investigate this?

**Comment by MosheRivkin** [comment]
> I'm experiencing this issue with SvelteKit too. Is there anything I can do to help investigate this?

Vite's CLI use `node` by default.
try to add `bunx --bun` to the scripts in `package.json`
```json-diff#package.json
"scripts": {
	"dev": "bunx --bun vite",
	"build": "bunx --bun vite build",
	"preview": "bunx --bun vite preview",
}
``` 
[sorce: Build a frontend using Vite and Bun](https://bun.sh/guides/ecosystem/vite)

**Comment by fran-cadenas-fu** [comment]
I'm getting the same error on NextJS rout handlers. It suddenly stopped working.

**Comment by notramo** [comment]
Just to be clear, `bun-types` is only TS definitions, does not add any JS functions/objects to the global scope, only TS types. This means that the global `Bun` object is not available in the browser (the above screenshot implies it's accessed from code that runs in the browser).

Bun-specific code can be used only `+page.server.ts` and `+server.ts`, but requires a `typeof Bun !== 'undefined'` check when used in `+page.svelte` or `+page.ts`, so it's only accessed during SSR.

**Comment by kapitche** [comment]
> I'm getting the same error on NextJS route handlers. It suddenly stopped working.

Same here, can't hash my data using Bun.password because then I get
```bash
 ⨯ ReferenceError: Bun is not defined
    at POST (webpack-internal:///(rsc)/./src/app/api/register/route.ts:72:32)
    at async /Users/USERNAME/Documents/GitHub/PROJECT/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:62609
```

Does anyone have any idea?

**Comment by fran-cadenas-fu** [comment]
> > I'm getting the same error on NextJS route handlers. It suddenly stopped working.
> 
> Same here, can't hash my data using Bun.password because then I get
> 
> ```shell
>  ⨯ ReferenceError: Bun is not defined
>     at POST (webpack-internal:///(rsc)/./src/app/api/register/route.ts:72:32)
>     at async /Users/USERNAME/Documents/GitHub/PROJECT/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:62609
> ```
> 
> Does anyone have any idea?

In my case it was a problem of the all routes handler.

**Comment by kapitche** [comment]
> > > I'm getting the same error on NextJS route handlers. It suddenly stopped working.
> > 
> > 
> > Same here, can't hash my data using Bun.password because then I get
> > ```shell
> >  ⨯ ReferenceError: Bun is not defined
> >     at POST (webpack-internal:///(rsc)/./src/app/api/register/route.ts:72:32)
> >     at async /Users/USERNAME/Documents/GitHub/PROJECT/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:62609
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Does anyone have any idea?
> 
> In my case it was a problem of the all routes handler.

Did you find a fix yet?

**Comment by ko-devHong** [comment]
> > I'm experiencing this issue with SvelteKit too. Is there anything I can do to help investigate this?
> 
> Vite's CLI use `node` by default. try to add `bunx --bun` to the scripts in `package.json`
> 
> ```json
> "scripts": {
> 	"dev": "bunx --bun vite",
> 	"build": "bunx --bun vite build",
> 	"preview": "bunx --bun vite preview",
> }
> ```
> 
> [sorce: Build a frontend using Vite and Bun](https://bun.sh/guides/ecosystem/vite)

I'm using my custom cli library.
it works if I use your command. 
Thanks

- my use
```json
"scripts": {
	"dev": "bunx --bun custom-cli dev",
}
```

**Comment by prisius** [comment]
i have this in my package.json
```
"scripts": {
	"dev": "bunx --bun vite",
	"build": "bunx --bun vite build",
	"preview": "bunx --bun vite preview",
}
```
still can't get bun working. I got bun is not defined.

I am using vite vanilla javascript.

How to get sure if vite is not using node ?

**Comment by bobbymannino** [comment]
i think they changed it to now have a space after bun in bunx `bun x --bun vite`

**Comment by prisius** [comment]
> > i think they changed it to now have a space after bun in bunx `bun x --bun vite`
> 
> i think that the change was that you can type `bun` instead of `bunx` to run vite, so you can type `bun --bun vite` (or maybe it was possible all the time🤔 anyway back then the example in the docs was with `bunx`)

```
bun --bun vite
```
won't work.

I tried on Windows and Ubuntu. Same problem.

What am i doing wrong ?

**Comment by prisius** [comment]
> > > i think they changed it to now have a space after bun in bunx `bun x --bun vite`
> > 
> > 
> > i think that the change was that you can type `bun` instead of `bunx` to run vite, so you can type `bun --bun vite` (or maybe it was possible all the time🤔 anyway back then the example in the docs was with `bunx`)
> 
> ```
> bun --bun vite
> ```
> 
> won't work.
> 
> I tried on Windows and Ubuntu. Same problem.
> 
> What am i doing wrong ?

Removing nodejs didn't work either.

**Comment by prisius** [comment]
### bun init works !

I think it has something to do with vite.

Somehow vite doesn't recognize Bun with vanilla js and typescript. I didn't tested with React.

**Comment by Jarred-Sumner** [comment]
If you run into this in the future, it means the environment is not running in Bun, and probably running in Node. The most common reason this happens if a there's a `#!/usr/bin/env node` at the top of the file.

To forcefully make it so any process spawning node is actually spawning Bun:
```
bun --bun <script>
```
