### ISSUE TITLE
Uncatchable AbortError in discord.js when using Bun instead of NodeJS

### ISSUE THREAD

**Issue by ThePotatoChronicler** [oven-sh/bun#5373]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Linux 6.5.2-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

package.json
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "scripts": {},
  "keywords": [],
  "dependencies": {
    "discord.js": "^14.13.0"
  }
}
```

main.mjs
```js
import { Client } from "discord.js"
const client = new Client({intents: 0});
setTimeout(() => { client.destroy() }, 2000);
await client.login(process.env["TOKEN"])
```

```
$ npm install
...
$ TOKEN="VALID_TOKEN" node index.mjs
$ TOKEN="VALID_TOKEN" bun index.mjs
167 |   }
168 | }
169 | 
170 | class AbortError extends Error {
171 | 
172 |   constructor() {
                             ^
error: The operation was aborted
 code: "ABORT_ERR"

      at new AbortError (node:timers/promises:172:26)
      at node:timers/promises:46:34
      at /tmp/test/node_modules/@discordjs/ws/dist/index.js:710:6
      at destroy (/tmp/test/node_modules/@discordjs/ws/dist/index.js:691:16)
      at /tmp/test/node_modules/@discordjs/ws/dist/index.js:1194:20
      at destroy (/tmp/test/node_modules/@discordjs/ws/dist/index.js:1191:16)
      at /tmp/test/node_modules/discord.js/src/client/websocket/WebSocketManager.js:329:10
      at destroy (/tmp/test/node_modules/discord.js/src/client/websocket/WebSocketManager.js:324:18)
      at /tmp/test/node_modules/discord.js/src/client/Client.js:251:10
```

### What is the expected behavior?

Both NodeJS and Bun exit successfully.

### What do you see instead?

Bun exits due to an uncaught AbortError

### Additional information

The `AbortError` is practically impossible to try-catch, at least for me

I would love to add a more minimal example, but I honestly have no idea what is happening.

**Comment by v3nntrnx** [comment]
I had this too, though I dont remember what I did to fix it

**Comment by Electroid** [comment]
Thanks for reporting this issue! Looks it was already reported, so we'll track it in this issue: #5185
