### ISSUE TITLE
bun fails at module resolution with bun workspaces

### ISSUE THREAD

**Issue by nikivdev** [oven-sh/bun#5388]
### What version of Bun is running?

1.0.1+92e95c86dd100f167fb4cf8da1db202b5211d2c1

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

On this repo:

https://github.com/learn-anything/learn-anything.xyz

I tried to migrate from pnpm to bun. Everything worked perfectly with pnpm before.

After [replacing all pnpm things with bun](https://github.com/learn-anything/learn-anything.xyz/commit/732aa2270a2a40b5afcff49795ae55681c02e7f7).

I get this error trying to run `bun web:dev`

<img width="760" alt="image" src="https://github.com/oven-sh/bun/assets/6391776/be6d2d1a-37f8-46fc-83c2-88215a966a8a">

Which is a bug because its there in the package.json dep

<img width="615" alt="image" src="https://github.com/oven-sh/bun/assets/6391776/fa9b8405-e176-42f4-9454-9b052610c0ac">

And I ran `bun i` at root and have these workspaces setup:

https://github.com/learn-anything/learn-anything.xyz/blob/main/package.json#L81

What am I doing wrong?

Would be grateful for helping me migrate away from pnpm to bun now that it reached 1.0

### What is the expected behavior?

Everything works. I can run my scripts without failure.

### What do you see instead?

```
  VITE v4.4.9  ready in 730 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
  ➜  Inspect: http://localhost:3000/__inspect/
  ➜  press h to show help

  ➜  Page Routes:
     ┌─ http://localhost:3000/auth
     ├─ http://localhost:3000/
     ├─ http://localhost:3000/pricing
     ├─ http://localhost:3000/@(username)/
     ├─ http://localhost:3000/@(username)/
     ├─ http://localhost:3000/:topic/edit
     └─ http://localhost:3000/:topic/

  ➜  API Routes:
     None! 👻

🔥 GET http://localhost:3000/3d-printing/edit
Failed to resolve import "graphql-mobius" from "src/root.tsx". Does the file exist?
🔥 GET http://localhost:3000/3d-printing/edit
6:01:15 PM [vite] Internal server error: Failed to resolve import "graphql-mobius" from "src/root.tsx". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/nikiv/src/app/learn-anything.xyz/website/src/root.tsx:3:19
  1  |  import { createComponent as _$createComponent } from "solid-js/web";
  2  |  import { $$decline as _$$decline } from "solid-refresh"; // @refresh reload
  3  |  import Mobius from "graphql-mobius";
     |                      ^
  4  |  import { Suspense, createContext, createSignal, useContext } from "solid-js";
  5  |  import FileRoutes from "solid-start/root/FileRoutes";
      at formatError (file:///Users/nikiv/src/app/learn-anything.xyz/node_modules/vite/dist/node/chunks/dep-df561101.js:43993:46)
      at TransformContext.error (file:///Users/nikiv/src/app/learn-anything.xyz/node_modules/vite/dist/node/chunks/dep-df561101.js:43989:19)
      at normalizeUrl (file:///Users/nikiv/src/app/learn-anything.xyz/node_modules/vite/dist/node/chunks/dep-df561101.js:41801:33)
      at async file:///Users/nikiv/src/app/learn-anything.xyz/node_modules/vite/dist/node/chunks/dep-df561101.js:41945:47
      at async Promise.all (index 2)
      at async TransformContext.transform (file:///Users/nikiv/src/app/learn-anything.xyz/node_modules/vite/dist/node/chunks/dep-df561101.js:41870:13)
      at async file:///Users/nikiv/src/app/learn-anything.xyz/node_modules/vite-plugin-inspect/dist/index.mjs:922:19
      at async Object.transform (file:///Users/nikiv/src/app/learn-anything.xyz/node_modules/vite/dist/node/chunks/dep-df561101.js:44283:30)
      at async loadAndTransform (file:///Users/nikiv/src/app/learn-anything.xyz/node_modules/vite/dist/node/chunks/dep-df561101.js:54950:29)
      at async viteTransformMiddleware (file:///Users/nikiv/src/app/learn-anything.xyz/node_modules/vite/dist/node/chunks/dep-df561101.js:64345:32)
6:01:15 PM [vite] ✨ new dependencies optimized: clsx, @solid-primitives/keyboard
6:01:15 PM [vite] ✨ optimized dependencies changed. reloading
🔥 GET http://localhost:3000/3d-printing/edit
Failed to resolve import "graphql-mobius" from "src/root.tsx". Does the file exist?
6:01:16 PM [vite] Internal server error: Failed to resolve import "graphql-mobius" from "src/root.tsx". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/nikiv/src/app/learn-anything.xyz/website/src/root.tsx:3:19
  1  |  import { createComponent as _$createComponent } from "solid-js/web";
  2  |  import { $$decline as _$$decline } from "solid-refresh"; // @refresh reload
  3  |  import Mobius from "graphql-mobius";
     |                      ^
  4  |  import { Suspense, createContext, createSignal, useContext } from "solid-js";
  5  |  import FileRoutes from "solid-start/root/FileRoutes";
      at formatError (file:///Users/nikiv/src/app/learn-anything.xyz/node_modules/vite/dist/node/chunks/dep-df561101.js:43993:46)
      at TransformContext.error (file:///Users/nikiv/src/app/learn-anything.xyz/node_modules/vite/dist/node/chunks/dep-df561101.js:43989:19)
      at normalizeUrl (file:///Users/nikiv/src/app/learn-anything.xyz/node_modules/vite/dist/node/chunks/dep-df561101.js:41801:33)
      at async file:///Users/nikiv/src/app/learn-anything.xyz/node_modules/vite/dist/node/chunks/dep-df561101.js:41945:47
      at async Promise.all (index 2)
      at async TransformContext.transform (file:///Users/nikiv/src/app/learn-anything.xyz/node_modules/vite/dist/node/chunks/dep-df561101.js:41870:13)
      at async file:///Users/nikiv/src/app/learn-anything.xyz/node_modules/vite-plugin-inspect/dist/index.mjs:922:19
      at async Object.transform (file:///Users/nikiv/src/app/learn-anything.xyz/node_modules/vite/dist/node/chunks/dep-df561101.js:44283:30)
      at async loadAndTransform (file:///Users/nikiv/src/app/learn-anything.xyz/node_modules/vite/dist/node/chunks/dep-df561101.js:54950:29)
      at async viteTransformMiddleware (file:///Users/nikiv/src/app/learn-anything.xyz/node_modules/vite/dist/node/chunks/dep-df561101.js:64345:32)
```

**Comment by nikitavoloboev** [comment]
I thought maybe instead of just running `bun i` at root, I would try do this:

<img width="720" alt="image" src="https://github.com/oven-sh/bun/assets/6391776/39363773-f735-468a-91df-692be1ada0df">

But that shows some other error. No idea what I am doing wrong. 😿
