### ISSUE TITLE
OS Module information functions do not work with template strings

### ISSUE THREAD

**Issue by ArkinSolomon** [oven-sh/bun#5424]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Darwin 23.0.0 x86_64 i386

### What steps can reproduce the bug?

In Node.Js, even though `os.platform` (and other functions like it) are technically functions [according to the docs](https://nodejs.org/api/os.html#osplatform), when using template strings, `os.platform` is converted to a string, which is [intended behavior](https://github.com/nodejs/node/blob/dac5f296914503629097b283cdced2df85878833/test/parallel/test-os.js#L239). 

Running the following code in Bun:

```js
const os = require('os')

console.log(typeof os.platform)
console.log(os.platform())
console.log(`${os.platform}`)
```

Results in: 

```
function
darwin
function platform() {
    [native code]
}
```

### What is the expected behavior?

In Node.Js, running the same code results in:

```
function
darwin
darwin
```

### Additional information

In Node.Js

```js
console.log(os.platform[Symbol.toPrimitive]()) // => 'darwin'
```

But in Bun, the code produces the following output:

```
TypeError: os.platform[Symbol.toPrimitive] is not a function. (In 'os.platform[Symbol.toPrimitive]()', 'os.platform[Symbol.toPrimitive]' is undefined)
      at /path/to/test.js:2:12
      at globalThis (/path/to/test.js:2:45)
```

**Comment by RiskyMH** [comment]
We've invested a ton of time into making Bun more reliable over the last year. I'm having a really hard time reproducing this. If you're still running into this issue, please let me know and I'll re-open this
