### ISSUE TITLE
Unable to use bun to run a webpack project

### ISSUE THREAD

**Issue by doberkofler** [oven-sh/bun#5558]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

**run:**

```bash
bun webpack_ban.ts
````

**webpack_ban.ts:**

```typescript
import path from 'path';
import webpack from 'webpack';

const compiler = webpack({
	mode: 'development',
	entry: './webpack_ban_test.ts',
	output: {
		path: path.resolve('./temp'),
		filename: '[name].js',
	},
	module: {
		rules: [
			{
				test: /.tsx?$/i,
				exclude: [/vendor/, /node_modules/],
				use: [{
					loader: 'ts-loader',
					options: {
						transpileOnly: true
					}
				}],
			},
		],
	},
	resolve: {
		extensions: ['.ts', '.tsx', '.js', '.jsx'],
	},
});
compiler.run((err, stats) => {
	if (err) {
		console.error(err);
	} else if (stats) {
		console.log(stats.toString());
	}
});
```

**webpack_ban_test.ts:**

```typescript
console.log('hello world');
```

### What is the expected behavior?

I would expect bun to run my webpack script

### What do you see instead?

```bash
webpack.JavascriptModulesPlugin has moved to webpack.javascript.JavascriptModulesPlugin
webpack.LibraryTemplatePlugin is deprecated and has been replaced by compilation.outputOptions.library or compilation.addEntry + passing a library option
SingleEntryPlugin was renamed to EntryPlugin
webpack.WebpackOptionsDefaulter is deprecated and has been replaced by webpack.config.getNormalizedWebpackOptions and webpack.config.applyWebpackOptionsDefaults
asset main.js 2.26 KiB [emitted] (name: main)
./webpack_ban_test.ts 39 bytes [not cacheable] [built] [code generated] [1 error]

ERROR in ./webpack_ban_test.ts
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: undefined is not a constructor (evaluating 'new console_1.Console(process.stderr)')
    at <anonymous> (/Users/user/MyDev/ljs_app/trunk/periscope/node_modules/ts-loader/dist/logger.js:11:44)
    at global code (/Users/user/MyDev/ljs_app/trunk/periscope/node_modules/ts-loader/dist/logger.js:29:8)
    at anonymous (native)
    at require (:1:11)
    at <anonymous> (/Users/user/MyDev/ljs_app/trunk/periscope/node_modules/ts-loader/dist/instances.js:13:6)
    at global code (/Users/user/MyDev/ljs_app/trunk/periscope/node_modules/ts-loader/dist/instances.js:341:8)
    at anonymous (native)
    at require (:1:11)
    at <anonymous> (/Users/user/MyDev/ljs_app/trunk/periscope/node_modules/ts-loader/dist/index.js:5:6)
    at global code (/Users/user/MyDev/ljs_app/trunk/periscope/node_modules/ts-loader/dist/index.js:255:8)

webpack 5.88.2 compiled with 1 error in 226 ms
```

**Comment by Electroid** [comment]
Looks like this is the same issue as: #3625 
We also have a fix that is almost ready here: #5448
