### ISSUE TITLE
`cpy` library fails with "undefined is not an object" error (probably related to node:streams and p-event)

### ISSUE THREAD

**Issue by ryangrahamnc** [oven-sh/bun#5560]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 19.6.0 x86_64 i386

### What steps can reproduce the bug?

Make a new bun proj in a test directory. And make sure the `cpy` library is installed:
```
bun init
bun i cpy
```

Make a file called **dir1/a.txt**:
```
aaaa
```

Another file called **index.ts**:
```
import cpy from 'cpy';

try {
    await cpy('./dir1/**', './dir2');
} catch (err) {
    console.log((err as Error).stack);
    throw err;
}
```

Then run it:
```
bun index.ts 
```

### What is the expected behavior?

Copy of `dir1/a.txt` to `dir2/a.txt`. This is what `node` does.

### What do you see instead?

```
Error: Cannot read from `/Users/ryan/crap/issue-reports/bun/cpy1/dir1/a.txt`: undefined is not an object
    at <anonymous> (/Users/ryan/crap/issue-reports/bun/cpy1/node_modules/cp-file/fs.js:20:81)
    at asyncFunctionResume (native)
    at promiseReactionJobWithoutPromiseUnwrapAsyncContext (native)
    at promiseReactionJob (native)
    at processTicksAndRejections (native)
Caused By: TypeError: undefined is not an object
    at <anonymous> (node:stream:1743:162)
    at <anonymous> (/Users/ryan/crap/issue-reports/bun/cpy1/node_modules/p-event/index.js:71:13)
    at new Promise (:1:11)
    at pEventMultiple (/Users/ryan/crap/issue-reports/bun/cpy1/node_modules/p-event/index.js:19:12)
    at pEvent (/Users/ryan/crap/issue-reports/bun/cpy1/node_modules/p-event/index.js:104:18)
    at <anonymous> (/Users/ryan/crap/issue-reports/bun/cpy1/node_modules/cp-file/fs.js:19:10)
    at createReadStream (/Users/ryan/crap/issue-reports/bun/cpy1/node_modules/cp-file/fs.js:15:34)
    at <anonymous> (/Users/ryan/crap/issue-reports/bun/cpy1/node_modules/cp-file/index.js:11:66)
    at processTicksAndRejections (:55:39)
CpyError: Cannot copy from `dir1/a.txt` to `dir2/a.txt`: Cannot read from `/Users/ryan/crap/issue-reports/bun/cpy1/dir1/a.txt`: undefined is not an object
```

### Additional information

It seems the error is more related to a p-event library call. But going through `cpy` seems to be the easiest way to show it off with a small amount of code.

The problem could be because I'm on Catalina (10.15), which is a fairly old version of osx.

**Comment by ryangrahamnc** [comment]
I've simplified it down to this:
```
import gracefulFs from 'graceful-fs';

const path = 'a.txt';
const read = gracefulFs.createReadStream(path, {});

read.on('readable', () => {
    console.log('become readable');
});

console.log('got to end');
```
Outputs (assuming a.txt exists):
```
TypeError: undefined is not an object
      at node:stream:1743:322
      at /Users/ryan/crap/issue-reports/bun/cpy1/run2.js:6:0
```

graceful-fs is building a clone of `fs` and is possibly (not quite sure) monkey patching it.
It probably has its own assumptions on how node's fs library runs.

Also maybe this could be similar to https://github.com/oven-sh/bun/issues/4084

**Comment by ryangrahamnc** [comment]
I've simplified it down again to how the `graceful-fs` lib is using `fs`:
```
import fs from 'fs';

const fs$ReadStream = fs.ReadStream;

function MyReadStream(path, options) {
    fs$ReadStream.apply(this, arguments);
    return this;
}
MyReadStream.prototype = Object.create(fs$ReadStream.prototype);

const path = 'a.txt';
const read = new MyReadStream(path, {});

read.on('data', (data) => {
    console.log('got some data', data);
});

console.log('got to end');
```

running node:
```
➜ imac cpy1 git:(master) ✗ node run2.js
got to end
got some data <Buffer 61 61 61 61 0a>
➜ imac cpy1 git:(master) ✗
```

running bun:
```
➜ imac cpy1 git:(master) ✗ bun run2.js
1738 |         if (this._readableState.needReadable)
1739 |           maybeReadMore(this, this._readableState);
1740 |       });
1741 |     }
1742 | 
1743 |     Readable.prototype = {}, ObjectSetPrototypeOf(Readable.prototype, Stream.prototype), ObjectSetPrototypeOf(Readable, Stream), Readable.prototype.on = function(ev, fn) {
                                                                                                                                                                                                                                                                                                                                     ^
TypeError: undefined is not an object
      at node:stream:1743:322
      at /Users/ryan/crap/issue-reports/bun/cpy1/run2.js:14:0
```

My guess without looking deeply is that inheriting the base `fs` classes (using the function + prototype manipulation method rather than real classes) makes it lose a proper reference to the `this` var.

Redefining the class as `class MyReadStream extends fs.ReadStream {}` works fine. But we cant really force all libraries like graceful-fs to swap to this `class` method.

**Comment by whjvenyl** [comment]
Identical issue with the library recursive-copy, which is using graceful-fs as well.

**Comment by paperclover** [comment]
this fix was applied to writestream but not readstream: we need to stop using an ES6 class for `ReadStream` as well as `NativeReadable`. code for this is in `src/js/node/fs.js` and `stream.js`

**Comment by zadokdaniel** [comment]
After some poking around, I think I understand the problem.

```typescript
// node_modules/graceful-fs.js:297
function ReadStream (path, options) {
    if (this instanceof ReadStream)
      return fs$ReadStream.apply(**this**, arguments), *this*
    else
      return ReadStream.apply(Object.create(ReadStream.prototype), arguments)
}
```
` **this** !== *this*`

\*\*this** and \*this* (ref. code above) are not the same, so although `apply` does its job, the `ReadStream`'s function returns the same reference passed to the original constructor of `ReadStream`.
The crash happens on the 'data' event when the function tries to access `this._readableState`, which is undefined. Probably because `gracful-fs` returns the wrong value based on the assumption that the `this` given is the `this` returned (by reference), which is incorrect in the current case.

```typescript
// src/js/node/stream.js:2289
Readable.prototype.on = function (ev, fn) {
      const res = Stream.prototype.on.call(this, ev, fn);
      const state = this._readableState;
      if (ev === "data") {
        **state.readableListening** = this.listenerCount("readable") > 0;
        if (state.flowing !== false) {
          $debug("in flowing mode!", this.__id);
```

`state.readableListening` cannot have value on the account `this._readableState` is undefined.

Removing `, *this*` on `graceful-fs.js` does the job, and everything is back to normal, which made me conclude somewhere in the code flow, the original object's reference gets lost, and a new one is returned instead.
I tried to follow the constructors and figure out where it happens, but this is a tough bug to find, specifically without a debugger.

Do you guys agree with my theory, or should I be looking for something else? 
Is it possible to throw a `debugger` keyword and follow it from a test project into Bun's core modules?

**Comment by nektro** [comment]
(status update for Bun 1.1.10)

- this now runs and exits with with no errors
- does create `dir2/`
- does create `dir2/a.txt`

however I can confirm we are still lacking emitting the `'readable'` event in many cases and the file ends up with no content.
they should likely be using the `'data'` event but will continue to investigate this as it is probably affecting others as well
