### ISSUE TITLE
Handled errors they are still thrown in console (with async fetch)

### ISSUE THREAD

**Issue by TiBianMod** [oven-sh/bun#5566]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

`index.ts`

```ts
import type { Errorlike } from "bun";

class RouteNotFoundException extends Error implements Errorlike {
    code = "E_ROUTE_NOT_FOUND";
    message = "Route not found!";
}

Bun.serve({
    port: 4000,
    // The issue is coming from the "async"
    // But we need the use of `async fetch`
    async fetch(request) {
        if (request.url === "http://127.0.0.1:4000/") {
            return Response.json({ all: "good" });
        }

        throw new RouteNotFoundException();
    },
    error(error: Errorlike) {
        // we always have a correct response
        // the error is handled...
        // but, with async fetch we also log the error in the console, Opps :(
        if (error.code === "E_ROUTE_NOT_FOUND") {
            return Response.json({
                code: error.code,
                message: error.message,
            });
        }
    },
});

console.log("Listening on : http://127.0.0.1:4000");
```

run `bun --watch index.ts`

visit [http://127.0.0.1:4000/somewhere](http://127.0.0.1:4000/somewhere)

### What is the expected behavior?

No errors in the console, because the error is handled..

### What do you see instead?

```bash
1 | import type { Errorlike } from "bun";
2 | 
3 | class RouteNotFoundException extends Error implements Errorlike {
   ^
error: Route not found!
 code: "E_ROUTE_NOT_FOUND"

      at new RouteNotFoundException (/path/to/index.ts:3:0)
      at /path/to/index.ts:16:14
      at fetch (/path/to/index.ts:11:16)
```

### Additional information

The issue is coming from the `async fetch`, if we remove the `async` from fetch then we will not see any errors.
But we need the use of `async fetch`

**Comment by Jarred-Sumner** [comment]
Can you try returning a response in the Error handler?

**Comment by TiBianMod** [comment]
```ts
Bun.serve({
    port: 4000,
    async fetch() {
        throw new Error("Route not found!");
    },
    error() {
        return Response.json({ some: "response" });
    },
});

console.log("Listening on : http://127.0.0.1:4000");
```

same behavior !!

**Comment by Electroid** [comment]
Duplicate of #1435
