### ISSUE TITLE
TypeError: function is not a constructor

### ISSUE THREAD

**Issue by acoollevel** [oven-sh/bun#5601]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Using package `axios-ntlm`:

```
import { NtlmClient } from 'axios-ntlm';

(async () => {

    let credentials: NtlmCredentials = {
        username: 'username',
        password: "password",
        domain: 'domain'
    }

    let client = NtlmClient(credentials)

    try {
        let resp = await client({
            url: 'https://protected.site.example.com',
            method: 'get'
        });
        console.log(resp.data);
    }
    catch (err) {
        console.log(err)
        console.log("Failed")
    }

})()
```

### What is the expected behavior?

In Node v18, the package works as expected for making an authenticated request to an NTLM protected resource.

### What do you see instead?

```
1 | 'use strict';
2 | // Original file https://raw.githubusercontent.com/elasticio/node-ntlm-client/master/lib/ntlm.js
3 | var os = require('os'), flags = require('./flags'), hash = require('./hash');
4 | var NTLMSIGNATURE = "NTLMSSP\0";
5 | function createType1Message(workstation, target) {
6 |     var dataPos = 32, pos = 0, buf = new Buffer.alloc(1024);
                                         ^
TypeError: function is not a constructor (evaluating 'new Buffer.alloc(1024)')
      at createType1Message (/Users/levi/Code/ntlm_proxy/node_modules/axios-ntlm/lib/ntlm.js:6:37)
      at /Users/levi/Code/ntlm_proxy/node_modules/axios-ntlm/lib/ntlmClient.js:110:32
      at step (/Users/levi/Code/ntlm_proxy/node_modules/axios-ntlm/lib/ntlmClient.js:56:17)
      at /Users/levi/Code/ntlm_proxy/node_modules/axios-ntlm/lib/ntlmClient.js:37:52
      at /Users/levi/Code/ntlm_proxy/node_modules/axios-ntlm/lib/ntlmClient.js:31:8
      at new Promise (:1:20)
      at /Users/levi/Code/ntlm_proxy/node_modules/axios-ntlm/lib/ntlmClient.js:27:11
      at /Users/levi/Code/ntlm_proxy/node_modules/axios-ntlm/lib/ntlmClient.js:90:31

Failed
1 | 'use strict';
2 | // Original file https://raw.githubusercontent.com/elasticio/node-ntlm-client/master/lib/ntlm.js
3 | var os = require('os'), flags = require('./flags'), hash = require('./hash');
4 | var NTLMSIGNATURE = "NTLMSSP\0";
5 | function createType1Message(workstation, target) {
6 |     var dataPos = 32, pos = 0, buf = new Buffer.alloc(1024);
                                         ^
TypeError: function is not a constructor (evaluating 'new Buffer.alloc(1024)')
      at createType1Message (/Users/levi/Code/ntlm_proxy/node_modules/axios-ntlm/lib/ntlm.js:6:37)
      at /Users/levi/Code/ntlm_proxy/node_modules/axios-ntlm/lib/ntlmClient.js:110:32
      at step (/Users/levi/Code/ntlm_proxy/node_modules/axios-ntlm/lib/ntlmClient.js:56:17)
      at /Users/levi/Code/ntlm_proxy/node_modules/axios-ntlm/lib/ntlmClient.js:37:52
      at /Users/levi/Code/ntlm_proxy/node_modules/axios-ntlm/lib/ntlmClient.js:31:8
      at new Promise (:1:20)
      at /Users/levi/Code/ntlm_proxy/node_modules/axios-ntlm/lib/ntlmClient.js:27:11
      at /Users/levi/Code/ntlm_proxy/node_modules/axios-ntlm/lib/ntlmClient.js:90:31
```

### Additional information

Happy to provide any additional details as needed.

**Comment by paperclover** [comment]
related/duplicate of #3638. i think we need to fix `.from` too

the issue is simply these functions are defined in native code, so `new` does not work on them by default.

**Comment by ashutosh887** [comment]
@paperdave @acoollevel 
Let me try this issue... Please assign

**Comment by paperclover** [comment]
I've been working on this for a little bit and it's actually a little bit trickier than I realized; there isn't a super trivial "can construct" flag we can add to the native host functions, making this less friendly of a good first issue as i thought.
