### ISSUE TITLE
Uncaught Error: Cannot find module 'qrious'

### ISSUE THREAD

**Issue by igortas** [oven-sh/bun#5609]
### What version of Bun is running?

1.0.2

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

This is weird case which happened once, when I've removed ```package-lock.json``` and ```node_modules```, with ```ncu -u``` comamnd from ```npm-check-updates``` tool to upgrade all my packages to latest version, and looks ```bun install``` step skipped the installation of ```qrious``` package (version 4.0.2, probably some error).

Running then the ```CRA``` app, the error below was showned, so I need to reinstall the ```qrious``` package.
```
Uncaught Error: Cannot find module 'qrious'
    at webpackMissingModule (index.js:133:1)
    at ./node_modules/react-qrious/lib/use-qrious.js (index.js:133:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/components/shared/QRCode/index.tsx (setCanvasSize.ts:8:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
```

### What is the expected behavior?

```bun install``` to throw error if have some problem with installing some package, without proceeding (or run ```bun install``` with flag for this option)

### What do you see instead?

```
Uncaught Error: Cannot find module 'qrious'
    at webpackMissingModule (index.js:133:1)
    at ./node_modules/react-qrious/lib/use-qrious.js (index.js:133:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/components/shared/QRCode/index.tsx (setCanvasSize.ts:8:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
```

**Comment by Electroid** [comment]
Could you provide some example code so we can try to reproduce this issue?

**Comment by RiskyMH** [comment]
We've invested a ton of time into making Bun more reliable over the last year. I'm having a really hard time reproducing this without more information like `package.json`.

If you're still running into this issue, please let me know and I'll re-open and investigate more.
