### ISSUE TITLE
Add support for Module._initPaths() call

### ISSUE THREAD

**Issue by iatsiuk** [oven-sh/bun#5630]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Add support for `Module._initPaths()` function call. The purpose of this function is to initialize the module search path for Node.js.

For example, you can do trick like this:
```js
process.env.NODE_PATH = __dirname;
// Initialize the module search path to include the current directory
require('module').Module._initPaths()

// now it's possible require modules by absolute path from root folder,
// using 'lib/logger', not '../../../lib/logger' here:
const logger = require('lib/logger');
```

### What is the expected behavior?

`require("module").Module._initPaths` should not be throwing an error.

### What do you see instead?

```sh
❯ bun src/index.js
[1.62ms] ".env"
1 | process.env.NODE_PATH = __dirname;
2 | require('module').Module._initPaths();
   ^
TypeError: require("module").Module._initPaths is not a function. (In 'require("module").Module._initPaths()', 'require("module").Module._initPaths' is undefined)
      at /app/src/index.js:2:0
      at globalThis (/app/src/index.js:55:14)
```

### Additional information

This code is commonly used in Node.js projects to ensure that modules installed in the current directory are available to the project. It is particularly useful when working with local modules that are not published to the npm registry. By setting the NODE_PATH environment variable and initializing the module search path, Node.js can find and load these local modules.

**Comment by hoiekim** [comment]
FYI:
I use `Module._initPaths()` for Node apps to replicate what `paths` in `tsconfig.json` does. I needed to do so because Node couldn't run the app that uses `paths` option after compiling to Javascript, so I had to tell Node where to resolve import modules. However, [Bun recognizes `paths` out of box](https://bun.sh/docs/runtime/typescript#path-mapping) so I didn't have to use `Module._initPaths()` anymore. Here's what I do:
```javascript
const setModulePaths = () => {
  try {
    const paths = ["src", "dist"];
    const isWindows = process.platform === "win32";
    process.env.NODE_PATH = paths.join(isWindows ? ";" : ":");
    require("module").Module._initPaths();
  } catch (e) {
    console.warn(
      "Failed to set module paths. If you're using Bun, you can ignore this warning."
    );
  }
};
```
I'm not saying that it's the only use case for this feature and I think it's worth to keep this issue open and see what others think.

**Comment by maxwellb** [comment]
Currently blocking running latest n8n with bun.

```
$ which node
/srv/apps/.bun/bin/node

$ bun --version
1.2.19

$ n8n start
Initializing n8n process
TypeError: module.constructor._initPaths is not a function. (In 'module.constructor._initPaths()', 'module.constructor._initPaths' is undefined)
    at init (/srv/apps/.bun/install/global/node_modules/n8n/src/load-nodes-and-credentials.ts:70:21)
    at init (/srv/apps/.bun/install/global/node_modules/n8n/src/load-nodes-and-credentials.ts:61:12)
    at init (/srv/apps/.bun/install/global/node_modules/n8n/src/commands/base-command.ts:98:47)
    at processTicksAndRejections (native)
Exiting due to an error.
module.constructor._initPaths is not a function. (In 'module.constructor._initPaths()', 'module.constructor._initPaths' is undefined)
```

**Comment by useafterfree** [comment]
@maxwellb : Since bun "does the right thing" with paths, this call is not necessary as far as I can tell.
Here is the try/catch in that block similar to @hoiekim's example:
```
		try {
			// @ts-ignore
			// eslint-disable-next-line @typescript-eslint/no-unsafe-call
			module.constructor._initPaths();
		} catch (e) {
			console.warn("Failed to set module paths. If you're using Bun, you can ignore this warning.");
		}
```

Here are the changes I made to get bun working in the n8n build > docker path: https://github.com/useafterfree/n8n/commit/33be9667a6d0dc9e70636bf01603f0de23a8ceb7
