### ISSUE TITLE
Error on next build

### ISSUE THREAD

**Issue by confact** [oven-sh/bun#5667]
### What version of Bun is running?

1.0.2

### What platform is your computer?

Ubuntu 20.04

### What steps can reproduce the bug?

bun run -b build

### What is the expected behavior?

to build next static pages without issues

### What do you see instead?

```
TypeError: null is not an object (evaluating 'dispatcher.useContext')
    at useContext (/home/confact/Documents/projects/erro-frontend/node_modules/react/cjs/react.development.js:1617:38)
    at useSWRConfig (/home/confact/Documents/projects/erro-frontend/node_modules/swr/_internal/dist/index.mjs:592:67)
    at useSWRArgs (/home/confact/Documents/projects/erro-frontend/node_modules/swr/_internal/dist/index.mjs:635:19)
    at useApi (/home/confact/Documents/projects/erro-frontend/.next/server/chunks/9842.js:32:8)
    at useUser (/home/confact/Documents/projects/erro-frontend/.next/server/chunks/9842.js:27:9)
```

### Additional information

works fine when building it without bun, with node. it is building without issues.

**Comment by confact** [comment]
Updated the description as it seems to be SWR  that trigger this error.

**Comment by confact** [comment]
Figure out it was mutate, on useSWRConfig. I moved to global mutate and that solve the issue. I guess SWR is acting a bit weird in bun right now, as this works fine when building with node.
