### ISSUE TITLE
cannot declare a var variable that shadows a let/const/class variable

### ISSUE THREAD

**Issue by Enubia** [oven-sh/bun#5732]
### What version of Bun is running?

1.0.3+cc54b62fac41c0977c7dfc4c6ba550a6408fa15f

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

make-error-cause (dependency of gulp-uglify) throws during a gulp build pipeline.

Example to reproduce the issue.

```js
const { src, dest, task } = require('gulp');
const uglify = require('gulp-uglify');
const plumber = require('gulp-plumber');

task('default', (done) => {
    src('./test.js')
        .pipe(plumber((err) => {
            console.log(err);
        }))
        .pipe(uglify())
        .pipe(dest('./dist/test.js'))
        .on('end', () => {
            console.log('end');
            done();
        });
});
```

### What is the expected behavior?

```sh
../Workspace/dev-env/test-gulp❯ npx gulp   
[13:30:43] Using gulpfile /Volumes/Workspace/dev-env/test-gulp/gulpfile.js
[13:30:43] Starting 'default'...
end
[13:30:43] Finished 'default' after 22 ms
```

### What do you see instead?

```sh
../Workspace/dev-env/test-gulp❯ bun gulpfile.js 
 8 | function makeErrorCause(value, _super) {
 9 |     if (_super === void 0) { _super = makeErrorCause.BaseError; }
10 |     return makeError(value, _super);
11 | }
12 | var makeErrorCause;
13 | (function (makeErrorCause) {
              ^
SyntaxError: Cannot declare a var variable that shadows a let/const/class variable: 'makeErrorCause'.
      at /Volumes/Workspace/dev-env/test-gulp/node_modules/make-error-cause/dist/index.js:13:10
../Workspace/dev-env/test-gulp❯ 
```

**Comment by Enubia** [comment]
nevermind me, I did not execute this script with `bunx gulp` but instead tried to run the gulpfile directly with `bun gulpfile.js`

**Comment by Enubia** [comment]
reopening because I think it could be still valid tho

in case you execute the provided script with either

```sh
node gulpfile.js
```
```sh
npx gulp
```
```sh
bunx gulp
```

it works as intended

but if you try to run the script via 

```sh
bun gulpfile.js
```

the aforementioned error occurs

**Comment by paperclover** [comment]
transpiler bug, minimal repro. @dylan-conway 
```
function A() {
}
var A;
```

**Comment by AxeemHaider** [comment]
still same error did you able to find solution of it @paperdave

**Comment by jlucaso1** [comment]
Same error when trying to run lib https://github.com/WhiskeySockets/Baileys/issues/586
```ts
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
SyntaxError: Cannot declare a var variable that shadows a let/const/class variable: '__importStar'.
```
@paperdave @dylan-conway

**Comment by roysG** [comment]
Any update?

**Comment by Araxeus** [comment]
> Same error when trying to run lib [WhiskeySockets/Baileys#586](https://github.com/WhiskeySockets/Baileys/issues/586)

This is because of transpiling issues, if you clone Baileys and directly the ts files with Bun, you avoid this error (but you get other errors about missing function from `Crypto`)

**Comment by Jarred-Sumner** [comment]
Fixedin Bun v1.1.21

**Comment by tobiashochguertel** [comment]
I still have this issue with `bun` **1.1.38+bf2f153f5**

```shell
$ bun run ./src/cli.ts serve /Users/tobiashochgurtel/work-dev/shell-scripts/shell-scripting-library/zsh-cheatsheet/script.cheatsheet.md
88976 |   return "#" + e2;
88977 | }
88978 | function i(e2) {
88979 |   return {};
88980 | }
88981 | var l = { class: "header-anchor", symbol: "#", renderHref: a, renderAttrs: i };
        ^
SyntaxError: Cannot declare a function that shadows a let/const/class/function variable 'i'.
      at <parse> (/Users/tobiashochgurtel/work-dev/npm/md-renderer/packages/webservice/dist/startWebService.js:88981:1)
      at native:11:43
note: missing sourcemaps for /Users/tobiashochgurtel/work-dev/npm/md-renderer/packages/webservice/dist/startWebService.js
note: consider bundling with '--sourcemap' to get unminified traces

Bun v1.1.38 (macOS arm64)
error: script "cli" exited with code 1
error: Process exited with code: 1
```

The generated JavaScript code:

```javascript
...
function i(e2) {
  return {};
}
var l = { class: "header-anchor", symbol: "#", renderHref: a, renderAttrs: i };
...
```
