### ISSUE TITLE
Trusted dependencies and C++ bindings

### ISSUE THREAD

**Issue by jakeg** [oven-sh/bun#5796]
### What version of Bun is running?

1.0.2

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

I'm trying to get [KalumaJS](https://kalumajs.org/) working in Bun. I'm using my fork at https://github.com/jakeg/kaluma-cli which has upgraded [`serialport`](https://github.com/serialport/node-serialport) to the latest version.

Some serialport functions like [SerialPort.list()](https://serialport.io/docs/api-serialport#list) call C++ functions directly.

I think serialport or one of its dependencies that deal with bindings is doing some lifecycle script to bind these C++ functions. My guess is these lifecycle scripts aren't running because serialport or one of its dependencies [isn't trusted](https://bun.sh/docs/cli/install#trusted-dependencies).

If I install serialport locally I can run `SerialPort.list()` fine:
```js
import { SerialPort } from 'serialport'
let list = await SerialPort.list()
console.log('list', list)
```

But when I run it within my fork of KalumaJS  I get:
```
kaluma.js:149
    SerialPort.list()
               ^

TypeError: SerialPort.list is not a function
at Command.<anonymous> (/mnt/c/code/debug2/node_modules/@kaluma/cli/bin/kaluma.js:149:16)
    at Command.listener [as _actionHandler] (/mnt/c/code/debug2/node_modules/commander/lib/command.js:488:17)
...
```

This all works fine if installed with npm.

**Comment by jakeg** [comment]
Seems to be unrelated to what I'm suggesting above, so closing.
