### ISSUE TITLE
TypeError: Module._load is not a function.

### ISSUE THREAD

**Issue by noraj** [oven-sh/bun#5925]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

ArchLinux Linux 6.5.3-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

- git clone https://gitlab.com/rawsec/rawsec-cybersecurity-list.git
- git checkout dev
- cd docusaurus
- bun install
- bun run build

### What is the expected behavior?

With nodejs v20.7.0

```
➜ yarn run build
yarn run v1.22.19
warning package.json: No license field
$ docusaurus build
[INFO] [en] Creating an optimized production build...

✔ Client
  

✔ Server
  Compiled successfully in 27.52s

Component Item was not imported, exported, or provided by MDXProvider as global scope
Component Item was not imported, exported, or provided by MDXProvider as global scope
Component Item was not imported, exported, or provided by MDXProvider as global scope
Component Item was not imported, exported, or provided by MDXProvider as global scope

✔ Client
  

● Server █████████████████████████ cache (99%) shutdown IdleFileCachePlugin
 stored

[SUCCESS] Generated static files in "build".
[INFO] Use `npm run serve` command to test your build locally.
Done in 37.17s.
```

### What do you see instead?

With bun 1.0.3

```
➜ /home/noraj/.asdf/installs/bun/1.0.3/bin/bun run build 
$ docusaurus build
[INFO] [en] Creating an optimized production build...

✔ Client
  

✖ Server
  Compiled with some errors in 19.34s



TypeError: Module._load is not a function. (In 'Module._load(file, parentModule)', 'Module._load' is undefined)
    at eval (native)
    at runInNewContext (native)
[ERROR] Unable to build website for locale en.
175 |                 reject(err);
176 |             }
177 |             // Let plugins consume all the stats
178 |             const errorsWarnings = stats?.toJson('errors-warnings');
179 |             if (stats?.hasErrors()) {
180 |                 reject(new Error('Failed to compile with errors.'));
                          ^
error: Failed to compile with errors.
      at /home/noraj/Dev/rawsec-cybersecurity-inventory/docusaurus/node_modules/@docusaurus/core/lib/webpack/utils.js:180:23
      at processQueueWorker (/home/noraj/Dev/rawsec-cybersecurity-inventory/docusaurus/node_modules/webpack/lib/MultiCompiler.js:491:5)
      at processTicksAndRejections (:55:76)

✔ Client
  

● Server █████████████████████████ cache (99%) shutdown IdleFileCachePlugin
 stored

error: script "build" exited with code 1 (SIGHUP)
```

### Additional information

this parent-module was fixed #4742 but docusaurus is still not running

**Comment by Electroid** [comment]
It looks like we uncovered a new bug: `TypeError: Module._load is not a function.`

**Comment by DecathectZero** [comment]
I'm also getting this when running https://www.npmjs.com/package/@vanilla-extract/vite-plugin with `bunx --bun vite`

**Comment by DecathectZero** [comment]
+1 here, mostly looking at vanilla-extract

**Comment by lontten** [comment]
+1

**Comment by Jarred-Sumner** [comment]
We still haven't implemented this function as of Bun v1.1.27

**Comment by leetcow** [comment]
I'm getting a different error trying to set up vanilla extract using the esbuild plugin:

```
error: undefined is not an object (evaluating 'require('@vanilla-extract/css/adapter').setAdapter')
```
