### ISSUE TITLE
NestJS | A circular dependency has been detected

### ISSUE THREAD

**Issue by diavrank** [oven-sh/bun#5934]
### What version of Bun is running?

1.0.3+67defd95afb8f19259b2bde9be10e1a76a8137b5

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Create a project in Nestjs

Run the project with: `NODE_ENV=localdev nest start --exec "bun run"`

Have some classes in the project where some of their properties has the data type Long.

For example:

```ts
class SuperheroResponseDto extends ResponseDto {
      public failoverVersion: Long; //  error TS2304: Cannot find name 'Long'.
}
```

### What is the expected behavior?

It shouldn't mark any errors as it is working well with Nodejs 18 and yarn.

### What do you see instead?

```ts
165 |         }
166 |         return (0, lodash_1.omit)(paramObject, pathsToOmit);
167 |     }
168 |     createNotBuiltInTypeReference(key, metadata, trueMetadataType, schemas, pendingSchemaRefs) {
169 |         if ((0, shared_utils_1.isUndefined)(trueMetadataType)) {
170 |             throw new Error(`A circular dependency has been detected (property key: "${key}"). Please, make sure that each side of a bidirectional relationships are using lazy resolvers ("type: () => ClassType").`);
                      ^
error: A circular dependency has been detected (property key: "myProp"). Please, make sure that each side of a bidirectional relationships are using lazy resolvers ("type: () => ClassType").
      at createNotBuiltInTypeReference (/Users/myuser/Projects/scaffold/nestjs/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:170:18)
      at /Users/myuser/Projects/scaffold/nestjs/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:79:29
      at map (:1:20)
      at exploreModelSchema (/Users/myuser/Projects/scaffold/nestjs/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:92:35)
      at createNotBuiltInTypeReference (/Users/myuser/Projects/scaffold/nestjs/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:175:31)
      at /Users/myuser/Projects/scaffold/nestjs/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:79:29
      at map (:1:20)
      at exploreModelSchema (/Users/myuser/Projects/scaffold/nestjs/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:92:35)
      at create (/Users/myuser/Projects/scaffold/nestjs/node_modules/@nestjs/swagger/dist/services/response-object-factory.js:46:21)
      at /Users/myuser/Projects/scaffold/nestjs/node_modules/@nestjs/swagger/dist/explorers/nestjs-response.explorer.js:53:135
      at /Users/myuser/Projects/scaffold/nestjs/node_modules/lodash/lodash.js:13469:37
      at /Users/myuser/Projects/scaffold/nestjs/node_modules/lodash/lodash.js:4967:14
      at baseForOwn (/Users/myuser/Projects/scaffold/nestjs/node_modules/lodash/lodash.js:3032:23)
      at mapValues (/Users/myuser/Projects/scaffold/nestjs/node_modules/lodash/lodash.js:13468:6)
      at mapResponsesToSwaggerResponses (/Users/myuser/Projects/scaffold/nestjs/node_modules/@nestjs/swagger/dist/explorers/nestjs-response.explorer.js:53:10)
      at explorenestjsResponseMetadata (/Users/myuser/Projects/scaffold/nestjs/node_modules/@nestjs/swagger/dist/explorers/nestjs-response.explorer.js:28:15)
      at /Users/myuser/Projects/scaffold/nestjs/node_modules/@nestjs/swagger/dist/swagger-explorer.js:72:41
      at reduce (:1:20)
      at /Users/myuser/Projects/scaffold/nestjs/node_modules/lodash/lodash.js:13469:37
      at /Users/myuser/Projects/scaffold/nestjs/node_modules/lodash/lodash.js:4967:14
      at baseForOwn (/Users/myuser/Projects/scaffold/nestjs/node_modules/lodash/lodash.js:3032:23)
      at mapValues (/Users/myuser/Projects/scaffold/nestjs/node_modules/lodash/lodash.js:13468:6)
      at /Users/myuser/Projects/scaffold/nestjs/node_modules/@nestjs/swagger/dist/swagger-explorer.js:71:18
      at next (/Users/myuser/Projects/scaffold/nestjs/node_modules/iterare/lib/map.js:13:33)
      at next (/Users/myuser/Projects/scaffold/nestjs/node_modules/iterare/lib/filter.js:12:21)
      at from (:1:20)
      at generateDenormalizedDocument (/Users/myuser/Projects/scaffold/nestjs/node_modules/@nestjs/swagger/dist/swagger-explorer.js:63:34)
      at map (:1:20)
      at scanModuleRoutes (/Users/myuser/Projects/scaffold/nestjs/node_modules/@nestjs/swagger/dist/swagger-scanner.js:49:34)
      at /Users/myuser/Projects/scaffold/nestjs/node_modules/@nestjs/swagger/dist/swagger-scanner.js:39:35
      at map (:1:20)
      at scanApplication (/Users/myuser/Projects/scaffold/nestjs/node_modules/@nestjs/swagger/dist/swagger-scanner.js:27:34)

```

### Additional information

This issue is related to this one https://github.com/oven-sh/bun/issues/4644 because if I change the data type from Long to any, the error disappears.

**Comment by Electroid** [comment]
Closed for same reason as #4644
