### ISSUE TITLE
Error with HMR in NestJS app | Error: spawn EBADF

### ISSUE THREAD

**Issue by diavrank** [oven-sh/bun#5935]
### What version of Bun is running?

1.0.3+67defd95afb8f19259b2bde9be10e1a76a8137b5

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

1. Create a Nestjs app
2. Run the app: `NODE_ENV=local nest start --watch --exec "bun run"`

Note: The environment variable shouldn't not affect to your app. 

3. Do a change in a file (e.g. add a `console.log('hello world') `)
4. Wait like 5 seconds
5. Verify that the app is stopped with an error.

### What is the expected behavior?

To restart the server correctly with the new changes

### What do you see instead?

```shell
[5:01:20 PM] File change detected. Starting incremental compilation...

DeprecationWarning: 'getMutableClone' has been deprecated since v4.0.0. Use an appropriate `factory.update...` method instead, use `setCommentRange` or `setSourceMapRange`, and avoid setting `parent`.
DeprecationWarning: 'createLiteral' has been deprecated since v4.0.0. Use `factory.createStringLiteral`, `factory.createStringLiteralFromNode`, `factory.createNumericLiteral`, `factory.createBigIntLiteral`, `factory.createTrue`, `factory.createFalse`, or the factory supplied by your transformation context instead.
node:internal/child_process:413
    throw errnoException(err, 'spawn');
    ^

Error: spawn EBADF
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:757:9)
    at /Users/myuser/Projects/nestjs/api/node_modules/tree-kill/index.js:33:18
    at buildProcessTree (/Users/myuser/Projects/nestjs/api/node_modules/tree-kill/index.js:90:14)
    at module.exports (/Users/myuser/Projects/nestjs/api/node_modules/tree-kill/index.js:32:9)
    at /Users/myuser/Projects/nestjs/api/node_modules/@nestjs/cli/actions/start.action.js:72:17
    at Object.onWatchStatusChange (/Users/myuser/Projects/nestjs/api/node_modules/@nestjs/cli/lib/compiler/watch-compiler.js:64:17)
    at /Users/myuser/Projects/nestjs/api/node_modules/typescript/lib/typescript.js:126329:117
    at emitFilesAndReportErrors (/Users/myuser/Projects/nestjs/api/node_modules/typescript/lib/typescript.js:126148:13)
    at result.afterProgramCreate (/Users/myuser/Projects/nestjs/api/node_modules/typescript/lib/typescript.js:126329:13) {
  errno: -9,
  code: 'EBADF',
  syscall: 'spawn'
}

Node.js v18.16.1
error: script "start:dev" exited with code 1 (SIGHUP)
error: script "start" exited with code 1 (SIGHUP)
```

I don't know why it says at end Node.js v18.16.1 If I ran it with Bun.

**Comment by Electroid** [comment]
That is an error with Node.js, you'll want to start `nest` using Bun, like so:

```
bunx nest --bun [...]
```

**Comment by diavrank** [comment]
@Electroid do you have the reference link to see a detailed example with that command?

afaik, I had seen that it was with this way:

```ts
nest start --watch --exec "bun run"
```

**Comment by Electroid** [comment]
> @Electroid do you have the reference link to see a detailed example with that command?
> 
> afaik, I had seen that it was with this way:
> 
> ```ts
> nest start --watch --exec "bun run"
> ```

Could you try?

```
nest start --watch --exec "bun --bun run"
```

**Comment by diavrank** [comment]
Let me try it today later and I will let you know if it works

**Comment by diavrank** [comment]
@Electroid I just tried:

```shell
nest start --watch --exec "bun --bun run"
```

but I got the same error :/

Can we reopen this issue?

I am using Nest.js 10

**Comment by diavrank** [comment]
I also tried:

```
bunx nest start --bun --watch
```

but got the same result. I realized that with the above command, the process created is a nodejs process:

```shell
app git:(feat/bun) ✗ lsof -i tcp:3000 
COMMAND   PID     USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
node    32129 myuser   48u  IPv6 0x16e99644524de0f7      0t0  TCP *:hbci (LISTEN)
```

whereas the other command `nest start --watch --exec "bun --bun run"` is a bun process:
```shell
➜  app git:(feat/bun) ✗ lsof -i tcp:3000 
COMMAND   PID     USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
bun     31608 diavrank   27u  IPv6 0x16e99644327218f7      0t0  TCP *:hbci (LISTEN)
```

**Comment by diavrank** [comment]
I also tried `NODE_ENV=localdev bunx --bun nest start --watch`

but I got this error:

```shell
[3:17:49 PM] Starting compilation in watch mode...

[3:19:22 PM] Found 0 errors. Watching for file changes.

error: Cannot find module "typeorm/connection/Connection" from "/Users/myuser/Projects/javascript/src/app/folder/services/file.service.ts"

Bun v1.1.9-canary.1+bbaeeaeed (macOS arm64)
```
