### ISSUE TITLE
Puppeteer not working on Docker

### ISSUE THREAD

**Issue by JawadAhbab** [oven-sh/bun#5943]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Chromium is pre-downloaded in the image in this location `/usr/bin/chromium`

```ts
const browser = await puppeteer.launch({
    headless: 'new',
    executablePath: `/usr/bin/chromium`,
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
})
```

### What do you see instead?

Getting this error
```
$ bun run src/index.ts
71 |             return (0, util_js_1.emplace)(this.searchCache, from, search);
72 |         }
73 |         return search();
74 |     }
75 |     #readConfiguration(filepath) {
76 |         const contents = fs_1.default.readFileSync(filepath, 'utf8');
                             ^
EBADF: Bad file descriptor
 syscall: "fstat"
   errno: -9

      at #readConfiguration (/home/bun/app/node_modules/puppeteer/node_modules/cosmiconfig/dist/ExplorerSync.js:76:25)
      at search (/home/bun/app/node_modules/puppeteer/node_modules/cosmiconfig/dist/ExplorerSync.js:44:39)
      at emplace (/home/bun/app/node_modules/puppeteer/node_modules/cosmiconfig/dist/util.js:12:19)
      at getInternalOptions (/home/bun/app/node_modules/puppeteer/node_modules/cosmiconfig/dist/index.js:74:36)
      at cosmiconfigSync (/home/bun/app/node_modules/puppeteer/node_modules/cosmiconfig/dist/index.js:183:28)
      at getConfiguration (/home/bun/app/node_modules/puppeteer/lib/esm/puppeteer/getConfiguration.js:35:19)
      at /home/bun/app/node_modules/puppeteer/lib/esm/puppeteer/puppeteer.js:19:22
      at loadCJS2ESM (:1:20)
      at requireESM (:1:20)
```

**Comment by sandersemmel** [comment]
Same issue here:

```
Error message:

69 |             return (0, util_js_1.emplace)(this.searchCache, from, search);
70 |         }
71 |         return search();
72 |     }
73 |     #readConfiguration(filepath) {
74 |         const contents = fs_1.default.readFileSync(filepath, 'utf8');
                             ^
EBADF: Bad file descriptor
 syscall: "fstat"
   errno: -9

      at #readConfiguration (/app/node_modules/cosmiconfig/dist/ExplorerSync.js:74:25)
      at search (/app/node_modules/cosmiconfig/dist/ExplorerSync.js:44:39)
      at emplace (/app/node_modules/cosmiconfig/dist/util.js:12:19)
      at getInternalOptions (/app/node_modules/cosmiconfig/dist/index.js:74:36)
      at cosmiconfigSync (/app/node_modules/cosmiconfig/dist/index.js:183:28)
      at getConfiguration (/app/node_modules/puppeteer/lib/esm/puppeteer/getConfiguration.js:35:19)
      at /app/node_modules/puppeteer/lib/esm/puppeteer/puppeteer.js:19:22
      at processTicksAndRejections (:55:76)
```


Using this as base image:
https://hub.docker.com/r/oven/bun/

**Comment by Electroid** [comment]
Related #4798

**Comment by JawadAhbab** [comment]
> Related #4798

Seems like this a very major issue with Bun with Linux OS. But I wander this issue is very old and still not fixed. So, I think we should not expect to resolve this issue anytime soon 😔

**Comment by shiny** [comment]
Nuxt3 not working on Docker too
```bash
 => ERROR [5/5] RUN bun install                                                                                                                     2.7s
------
 > [5/5] RUN bun install:
0.061 bun install v1.0.3 (25e69c71)
2.700
2.700  ERROR  EBADF: Bad file descriptor
2.700
2.700   at perr (node_modules/nuxi/dist/shared/nuxi.4456790d.mjs:5962:29)
2.700   at <anonymous> (node_modules/nuxi/dist/shared/nuxi.c0869f34.mjs:11:30)
2.700   at asyncFunctionResume (native)
2.700   at importModule (node_modules/nuxi/dist/shared/nuxi.c0869f34.mjs:10:29)
2.700   at <anonymous> (node_modules/nuxi/dist/shared/nuxi.bf5ca6d6.mjs:9046:13)
2.700   at asyncFunctionResume (native)
2.700   at promiseReactionJobWithoutPromiseUnwrapAsyncContext (native)
2.700   at promiseReactionJob (native)
2.700   at processTicksAndRejections (native)
2.700
2.700
2.700
2.700  ERROR  EBADF: Bad file descriptor
2.700
2.703
2.703  4 packages installed [2.47s]
------
Dockerfile:5
--------------------
   3 |     WORKDIR /app
   4 |     COPY . /app
   5 | >>> RUN bun install
   6 |
   7 |
--------------------
ERROR: failed to solve: process "/bin/sh -c bun install" did not complete successfully: exit code: 1
```

Process to reproduce

Environment:
- macOS Ventura with OrbStack
- Docker image: oven/bun

```bash
bunx nuxi@latest init my-app
```

Create a Dockerfile with contents
```dockerfile
FROM oven/bun as base
RUN mkdir -p /app
WORKDIR /app
COPY . /app
RUN bun install
```

```bash
docker build .
```


However,  everything works if I install bun from npm, that's strange.

```Dockerfile
FROM node
RUN mkdir -p /app
RUN npm install -g bun
WORKDIR /app
COPY . /app
RUN bun install
RUN bun run build
CMD ["bun", ".output/server/index.mjs"]
```

**Comment by mvgiacomello** [comment]
> However, everything works if I install bun from npm, that's strange.

This did not work for me, unfortunately.

**Comment by PnsDev** [comment]
I'm running into the initial error when using this docker image: 
https://hub.docker.com/r/oven/bun/

<details>
<summary>Trace</summary>
<be>

```
71 |             return (0, util_js_1.emplace)(this.searchCache, from, search);
72 |         }
73 |         return search();
74 |     }
75 |     #readConfiguration(filepath) {
76 |         const contents = fs_1.default.readFileSync(filepath, 'utf8');
                             ^
EBADF: Bad file descriptor
 syscall: "fstat"
   errno: -9

      at #readConfiguration (/app/node_modules/cosmiconfig/dist/ExplorerSync.js:76:25)
      at search (/app/node_modules/cosmiconfig/dist/ExplorerSync.js:44:39)
      at emplace (/app/node_modules/cosmiconfig/dist/util.js:12:19)
      at getInternalOptions (/app/node_modules/cosmiconfig/dist/index.js:74:36)
      at cosmiconfigSync (/app/node_modules/cosmiconfig/dist/index.js:183:28)
      at getConfiguration (/app/node_modules/puppeteer/lib/esm/puppeteer/getConfiguration.js:35:19)
      at /app/node_modules/puppeteer/lib/esm/puppeteer/puppeteer.js:19:22
      at processTicksAndRejections (:55:76)

error: script "start" exited with code 1 (SIGHUP)

```

</details>

> However, everything works if I install bun from npm, that's strange.

Tested this ^ but sadly it did not work.

**Comment by Resonious** [comment]
Happening to me, not on docker.

I hacked around this with `if (error.code === 'EBADF') return null;` on line 49 of `node_modules/cosmiconfig/dist/readFile.js`. No clue what the ramifications are, but everything works fine for my purposes.
