### ISSUE TITLE
Importing dependency using dynamic `require()` calls does not work

### ISSUE THREAD

**Issue by marvinruder** [oven-sh/bun#6004]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

```bash
mkdir bun-selenium
cd bun-selenium
bun init # accept all default values
bun add selenium-webdriver
echo 'import "selenium-webdriver"' > index.ts
bun build index.ts --outfile=bundle.js --target=bun
bun ./bundle.js
```

### What is the expected behavior?

Import succeeds and running the bundle completes without errors.

### What do you see instead?

```
../../../bazel-bin/javascript/node/selenium-webdriver/lib/atoms/get-attribute.js


error: Cannot find module "/Users/bazel-bin/javascript/node/selenium-webdriver/lib/atoms/get-attribute.js" from "/Users/mruder/git-repos/bun-selenium/bundler.js"

1138 |         console.log(`../../../bazel-bin/${file}`);
1139 |         return import.meta.require(path.resolve(`../../../bazel-bin/${file}`));
1140 |       } catch (ex2) {
1141 |         console.log(ex2);
1142 | 
1143 |         throw Error(`Failed to import atoms module ${module2}. If running in dev mode, you` + ` need to run \`bazel build ${bazelTarget}\` from the project` + `root: ${ex}`);
                 ^
error: Failed to import atoms module get-attribute.js. If running in dev mode, you need to run `bazel build //javascript/node/selenium-webdriver/lib/atoms:get-attribute.js` from the projectroot: ResolveMessage: Cannot find module "./atoms/get-attribute.js" from "/Users/mruder/git-repos/bun-selenium/bundler.js"
      at requireAtom (/Users/mruder/git-repos/bun-selenium/bundler.js:1143:14)
      at /Users/mruder/git-repos/bun-selenium/bundler.js:1256:21
      at /Users/mruder/git-repos/bun-selenium/bundler.js:2:74
      at /Users/mruder/git-repos/bun-selenium/bundler.js:1669:16
      at /Users/mruder/git-repos/bun-selenium/bundler.js:2:74
      at /Users/mruder/git-repos/bun-selenium/bundler.js:19676:12
```

### Additional information

The bazel-related log output is probably irrelevant, it results from a try-catch statement where the catch block is likely supposed to run while developing `selenium-webdriver` only. 

The important part is that the calls of the `require(…)` statement in https://github.com/SeleniumHQ/selenium/blob/44ac51fbbc680b93a17575b78199d1f8f65c23b9/javascript/node/selenium-webdriver/lib/http.js#L57 cannot be resolved by the bundler. This is [supported](https://esbuild.github.io/api/#glob) by `esbuild`. Will we see something similar in Bun soon?

**Comment by mxnr** [comment]
Just to add here, on Bun 1.1.30 the issue still persists.
@marvinruder were you able to resolve this somehow?

**Comment by marvinruder** [comment]
@mxnr Unfortunately not, I stopped trying to migrate my projects to Bun a long time ago.

**Comment by ipundit** [comment]
I coded a [workaround](https://gitlab.com/eazypaper/browsertabswitcher/-/blame/main/node_modules/selenium-webdriver/lib/http.js?ref_type=heads#L50-59) for Selenium, but it won't work in the general case. It illustrates the strategy of patching a dependent library to use static require() calls instead of unsupported dynamic ones.
