### ISSUE TITLE
Could not locate the bindings file for rpio on raspi

### ISSUE THREAD

**Issue by Capt0rr** [oven-sh/bun#6022]
### What version of Bun is running?

1.0.3

### What platform is your computer?

Linux 6.1.21-v8+ aarch64 unknown (raspi4)

### What steps can reproduce the bug?

```
pi@raspberrypi:~/i2cfix $ cat package.json
{
  "name": "i2cfix",
  "module": "src/index.js",
  "type": "module",
  "devDependencies": {
    "bun-types": "latest"
  },
  "peerDependencies": {},
  "dependencies": {
    "node-gyp": "^9.4.0",
    "rpio": "^2.4.2"
  },
  "trustedDependencies": [
    "rpio",
    "node-gyp"
  ]
}
```

```
pi@raspberrypi:~/i2cfix $ cat src/index.js
import io from 'rpio';
```

```
pi@raspberrypi:~/i2cfix $ bun run src/index.js
121 |         throw e;
122 |       }
123 |     }
124 |   }
125 |
126 |   err = new Error(
            ^
error: Could not locate the bindings file. Tried:
 → /home/pi/i2cfix/node_modules/rpio/lib/build/rpio.node
 → /home/pi/i2cfix/node_modules/rpio/lib/build/Debug/rpio.node
 → /home/pi/i2cfix/node_modules/rpio/lib/build/Release/rpio.node
 → /home/pi/i2cfix/node_modules/rpio/lib/out/Debug/rpio.node
 → /home/pi/i2cfix/node_modules/rpio/lib/Debug/rpio.node
 → /home/pi/i2cfix/node_modules/rpio/lib/out/Release/rpio.node
 → /home/pi/i2cfix/node_modules/rpio/lib/Release/rpio.node
 → /home/pi/i2cfix/node_modules/rpio/lib/build/default/rpio.node
 → /home/pi/i2cfix/node_modules/rpio/lib/compiled/18.15.0/linux/arm64/rpio.node
 → /home/pi/i2cfix/node_modules/rpio/lib/addon-build/release/install-root/rpio.node
 → /home/pi/i2cfix/node_modules/rpio/lib/addon-build/debug/install-root/rpio.node
 → /home/pi/i2cfix/node_modules/rpio/lib/addon-build/default/install-root/rpio.node
 → /home/pi/i2cfix/node_modules/rpio/lib/lib/binding/node-v108-linux-arm64/rpio.node
      at bindings (/home/pi/i2cfix/node_modules/bindings/bindings.js:126:8)
      at /home/pi/i2cfix/node_modules/rpio/lib/rpio.js:17:4
      at globalThis (/home/pi/i2cfix/node_modules/rpio/lib/rpio.js:1198:36)
```

```
pi@raspberrypi:~/i2cfix $ find node_modules/rpio -name *.node
node_modules/rpio/build/Release/rpio.node
node_modules/rpio/build/Release/obj.target/rpio.node
```

### What is the expected behavior?

Bun should find the .node files in the right dir.

### What do you see instead?

See above.

### Additional information

Works with nodejs.

**Comment by Electroid** [comment]
Duplicate of #4959

**Comment by Jarred-Sumner** [comment]
This was not fixed by https://github.com/oven-sh/bun/issues/4959, as it did not make the list of top 500 post-install scripts. 

We need to instead add a warning message explaining that the package `rpio` had a postinstall script which was skipped, and needs to be added to `trustedDependencies` for the package to fully work as expected.

This issue will be fixed by #7594
