### ISSUE TITLE
Bun 1.0.3 - fetch does not preserve headers on 303 redirect

### ISSUE THREAD

**Issue by etinquis** [oven-sh/bun#6053]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Docker Desktop on Windows

### What steps can reproduce the bug?

server.ts
```ts
import { Serve } from 'bun';

console.log('starting server');

export default {
    port: 80,
    fetch(req: Request) {
        const url = new URL(req.url);

        if(req.method == 'PUT') {
            return new Response(null, {status: 303, headers: { 'Location' : '/redirect'}} );
        }
        const header = req.headers.get('X-Test');
        return new Response(`Redirected ${header}`, {status: 200});
    }
} satisfies Serve;
```

client.ts
```ts
const response = await fetch('http://localhost:80', { verbose: true, method:'PUT', headers:{ 'X-Test': 'TEST'}});
console.trace(response, await response.text());
```

```
docker run --rm -v .:/home/bun/app --name bun-server oven/bun:1.0.3 bun run server.ts
docker exec -it bun-server bun run client.ts
```

### What is the expected behavior?

When running with bun 1.0.2:
```
docker run --rm -v .:/home/bun/app --name bun-server oven/bun:1.0.2 bun run server.ts
docker exec -it bun-server bun run client.ts
```

```
Request: PUT /
        x-test: TEST
        Connection: keep-alive
        User-Agent: Bun/1.0.2
        Accept: */*
        Host: localhost
        Accept-Encoding: gzip, deflate
        Content-Length: 0

Response: < 303 See Other
<       Location: /redirect
<       Date: Mon, 25 Sep 2023 20:53:55 GMT
<       Content-Length: 0

Request: GET /redirect
        x-test: TEST
        Connection: keep-alive
        User-Agent: Bun/1.0.2
        Accept: */*
        Host: localhost
        Accept-Encoding: gzip, deflate

Response: < 200 OK
<       content-type: text/plain;charset=utf-8
<       Date: Mon, 25 Sep 2023 20:53:55 GMT
<       Content-Length: 15

Response (0 KB) {
  ok: true,
  url: "http://localhost/redirect",
  headers: Headers {
    "content-type": "text/plain;charset=utf-8",
    "date": "Mon, 25 Sep 2023 20:53:55 GMT",
    "content-length": "15"
  },
  statusText: "OK",
  redirected: true,
  bodyUsed: true,
  status: 200
} Redirected TEST
      at /home/bun/app/client.ts:2:0
```

### What do you see instead?

```
Request: PUT /
        x-test: TEST
        Connection: keep-alive
        User-Agent: Bun/1.0.3
        Accept: */*
        Host: localhost
        Accept-Encoding: gzip, deflate
        Content-Length: 0

Response: < 303 See Other
<       Location: /redirect
<       Date: Mon, 25 Sep 2023 20:55:25 GMT
<       Content-Length: 0

Request: GET /redirect
        Connection: keep-alive
        User-Agent: Bun/1.0.3
        Accept: */*
        Host: localhost
        Accept-Encoding: gzip, deflate

Response: < 200 OK
<       content-type: text/plain;charset=utf-8
<       Date: Mon, 25 Sep 2023 20:55:25 GMT
<       Content-Length: 15

Response (0 KB) {
  ok: true,
  url: "http://localhost/redirect",
  headers: Headers {
    "content-type": "text/plain;charset=utf-8",
    "date": "Mon, 25 Sep 2023 20:55:25 GMT",
    "content-length": "15"
  },
  statusText: "OK",
  redirected: true,
  bodyUsed: true,
  status: 200
} Redirected null
      at /home/bun/app/client.ts:2:0
```

`X-Test` header is not passed to the redirect GET.

**Comment by colinhacks** [comment]
This was changed here to conform more closely to the `fetch` specification: https://github.com/oven-sh/bun/pull/5729/files

Spec: https://fetch.spec.whatwg.org/#http-redirect-fetch

<img width="1010" alt="Screenshot 2023-09-25 at 8 06 36 PM" src="https://github.com/oven-sh/bun/assets/3084745/489aba52-b909-4d03-a008-148e924218b9">

**Comment by etinquis** [comment]
@colinhacks See my comment on https://github.com/whatwg/fetch/issues/1711.  By my reading (given that request-body-header name is defined as a subset of headers), this implementation does not comply with the spec.

```
A request-body-header name is a [header name](https://fetch.spec.whatwg.org/#header-name) that is a [byte-case-insensitive](https://infra.spec.whatwg.org/#byte-case-insensitive) match for one of:

`Content-Encoding`
`Content-Language`
`Content-Location`
`Content-Type`
```
