### ISSUE TITLE
Cannot install bun on Mac

### ISSUE THREAD

**Issue by wkaskie** [oven-sh/bun#6177]
### What version of Bun is running?

n/a

### What platform is your computer?

Mac M1

### What steps can reproduce the bug?

in a command prompt, run `npm i -g bun`

### What is the expected behavior?

bun will install

### What do you see instead?

npm ERR! code 1
npm ERR! path /Users/<user>/.nvm/versions/node/v18.13.0/lib/node_modules/bun
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! Failed to find package "@oven/bun-darwin-aarch64". You may have used the "--no-optional" flag when running "npm install".
npm ERR! Error: Failed to install package "bun"
npm ERR!     at /Users/<user>/.nvm/versions/node/v18.13.0/lib/node_modules/bun/install.js:311:11
npm ERR!     at Generator.throw (<anonymous>)
npm ERR!     at rejected (/Users/<user>/.nvm/versions/node/v18.13.0/lib/node_modules/bun/install.js:35:27)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/<user>/.npm/_logs/2023-09-29T16_52_52_592Z-debug-0.log

### Additional information

I also tried installing locally without the "-g" flag. And tried `yarn global add bun`. The results are the same

**Comment by masterujjval** [comment]
have u tried ``` npm install bun ``` ?

**Comment by cyfung1031** [comment]
Your npm is broken.
I think even `npm install cowsay` could not run in your Mac
Would you consider to reinstall npm?

**Comment by ryoppippi** [comment]
You need paste the log here

**Comment by edison-manrique** [comment]
this works for me `sudo npm install bun`

**Comment by wkaskie** [comment]
I did try npm install bun, to see if it would work locally.
I didn't try with 'sudo', I'll try that.
The log was pasted with the original question.  What are you looking for?

Thanks all for your replies!

**Comment by wkaskie** [comment]
Tried yarn add, npm install, npm install -g, sudo npm install and sudo npm install -g...they all throw the same error:
`npm ERR! Failed to find package "@oven/bun-darwin-aarch64".`

**Comment by shubham-bgi** [comment]
`npm i -g -f bun`
Try this, not a permanent solution, but working.

**Comment by MARCA-Charlie** [comment]
Same error on M2 Pro. Problem appears to be with ```"@oven/bun-darwin-aarch64"``` package.

```npm i @oven/bun-darwin-aarch64``` yields the following error.

```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @oven/bun-darwin-aarch64@1.0.4: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  arm64
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64
```
The complete log:
```
0 verbose cli /Users/charlietimlin/.nvm/versions/node/v14.18.3/bin/node /Users/charlietimlin/.nvm/versions/node/v14.18.3/bin/npm
1 info using npm@8.13.1
2 info using node@v14.18.3
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:/Users/charlietimlin/.nvm/versions/node/v14.18.3/lib/node_modules/npm/npmrc Completed in 4ms
6 timing config:load:builtin Completed in 4ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/Users/charlietimlin/Documents/localDevelopment/webflow/.npmrc Completed in 0ms
10 timing config:load:project Completed in 5ms
11 timing config:load:file:/Users/charlietimlin/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/Users/charlietimlin/.nvm/versions/node/v14.18.3/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 18ms
19 timing npm:load:configload Completed in 18ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm i @oven/bun-darwin-aarch64
23 verbose argv "i" "@oven/bun-darwin-aarch64"
24 timing npm:load:setTitle Completed in 6ms
25 timing config:load:flatten Completed in 4ms
26 timing npm:load:display Completed in 10ms
27 verbose logfile logs-max:10 dir:/Users/charlietimlin/.npm/_logs
28 verbose logfile /Users/charlietimlin/.npm/_logs/2023-10-05T21_29_58_461Z-debug-0.log
29 timing npm:load:logFile Completed in 3ms
30 timing npm:load:timers Completed in 1ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 39ms
33 timing arborist:ctor Completed in 1ms
34 silly logfile start cleaning logs, removing 1 files
35 silly logfile done cleaning log files
36 timing arborist:ctor Completed in 0ms
37 timing idealTree:init Completed in 27ms
38 timing idealTree:userRequests Completed in 0ms
39 silly idealTree buildDeps
40 silly fetch manifest @oven/bun-darwin-aarch64@*
41 http fetch GET 200 https://registry.npmjs.org/@oven%2fbun-darwin-aarch64 12ms (cache hit)
42 silly placeDep ROOT @oven/bun-darwin-aarch64@1.0.4 OK for: @marca/webflow-tools@1.0.0 want: *
43 timing idealTree:#root Completed in 19ms
44 timing idealTree:node_modules/@oven/bun-darwin-aarch64 Completed in 0ms
45 silly fetch manifest @oven/bun-darwin-aarch64@1.0.3
46 silly fetch manifest @oven/bun-linux-aarch64@1.0.3
47 http fetch GET 200 https://registry.npmjs.org/@oven%2fbun-linux-aarch64 7ms (cache hit)
48 silly fetch manifest @oven/bun-linux-x64@1.0.3
49 http fetch GET 200 https://registry.npmjs.org/@oven%2fbun-linux-x64 4ms (cache hit)
50 silly fetch manifest @oven/bun-linux-x64-baseline@1.0.3
51 http fetch GET 200 https://registry.npmjs.org/@oven%2fbun-linux-x64-baseline 4ms (cache hit)
52 silly placeDep node_modules/bun @oven/bun-darwin-aarch64@1.0.3 OK for: bun@1.0.3 want: 1.0.3
53 silly placeDep ROOT @oven/bun-linux-aarch64@1.0.3 OK for: bun@1.0.3 want: 1.0.3
54 silly placeDep ROOT @oven/bun-linux-x64@1.0.3 OK for: bun@1.0.3 want: 1.0.3
55 silly placeDep ROOT @oven/bun-linux-x64-baseline@1.0.3 OK for: bun@1.0.3 want: 1.0.3
56 timing idealTree:node_modules/bun Completed in 28ms
57 timing idealTree:node_modules/@oven/bun-linux-aarch64 Completed in 0ms
58 timing idealTree:node_modules/@oven/bun-linux-x64 Completed in 0ms
59 timing idealTree:node_modules/@oven/bun-linux-x64-baseline Completed in 0ms
60 timing idealTree:node_modules/bun/node_modules/@oven/bun-darwin-aarch64 Completed in 0ms
61 timing idealTree:buildDeps Completed in 48ms
62 timing idealTree:fixDepFlags Completed in 1ms
63 timing idealTree Completed in 78ms
64 timing command:i Completed in 83ms
65 verbose stack Error: Unsupported platform
65 verbose stack     at checkPlatform (/Users/charlietimlin/.nvm/versions/node/v14.18.3/lib/node_modules/npm/node_modules/npm-install-checks/lib/index.js:34:25)
65 verbose stack     at Arborist.[checkPlatform] (/Users/charlietimlin/.nvm/versions/node/v14.18.3/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:240:5)
65 verbose stack     at Arborist.[checkEngineAndPlatform] (/Users/charlietimlin/.nvm/versions/node/v14.18.3/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:234:29)
65 verbose stack     at Arborist.buildIdealTree (/Users/charlietimlin/.nvm/versions/node/v14.18.3/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:221:42)
65 verbose stack     at async Promise.all (index 1)
65 verbose stack     at async Arborist.reify (/Users/charlietimlin/.nvm/versions/node/v14.18.3/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
65 verbose stack     at async Install.exec (/Users/charlietimlin/.nvm/versions/node/v14.18.3/lib/node_modules/npm/lib/commands/install.js:145:5)
65 verbose stack     at async module.exports (/Users/charlietimlin/.nvm/versions/node/v14.18.3/lib/node_modules/npm/lib/cli.js:78:5)
66 verbose pkgid @oven/bun-darwin-aarch64@1.0.4
67 verbose cwd /Users/charlietimlin/Documents/localDevelopment/webflow
68 verbose Darwin 22.4.0
69 verbose node v14.18.3
70 verbose npm  v8.13.1
71 error code EBADPLATFORM
72 error notsup Unsupported platform for @oven/bun-darwin-aarch64@1.0.4: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
73 error notsup Valid OS:    darwin
73 error notsup Valid Arch:  arm64
73 error notsup Actual OS:   darwin
73 error notsup Actual Arch: x64
74 verbose exit 1
75 timing npm Completed in 166ms
76 verbose unfinished npm timer reify 1696541398540
77 verbose unfinished npm timer reify:loadTrees 1696541398543
78 verbose code 1
79 error A complete log of this run can be found in:
79 error     /Users/charlietimlin/.npm/_logs/2023-10-05T21_29_58_461Z-debug-0.log

```

**Comment by shubham-bgi** [comment]
Found a fix for me by making a fresh install of nvm and node.

I was using nvm which I migrated from an intel to M1. That's why it is causing issues. 
you can check in `open ~/.nvm/.cache/bin/` where you can see the version of the node along with its architecture.
To find the nvm location use `where npm` generally is in ~/.nvm.

**Comment by wkaskie** [comment]
I probably have the same issue @shubham-bgi . I also migrated from an Intel to an M1. I'm going to try the `-f` flag and see if that gets me past the error, at least.

**Comment by wkaskie** [comment]
the `-f` flag didn't help. Going to try to remove and reinstall node and nvm 🤦‍♂️

**Comment by wkaskie** [comment]
Fresh installation worked! Thanks @shubham-bgi !

**Comment by AstralBaby** [comment]
im facing this issue on M1 using a fresh Node 20 install, in my case i was able to successfully install the bun-darwin-aarch64 package. any ideas?

**Comment by AstralBaby** [comment]
> Fresh installation worked! Thanks @shubham-bgi !

how did you fix it? i had a fresh installation it doesnt work i upgraded my os, i already tried with force and sudo and it seems like nothing works.

**Comment by dominictobias-bullish** [comment]
This happened to me twice today not sure why (I'm on a gross corporate mac with all kinds of security spyware modifying files) but as others have said installing bun again worked (no need to do it via NPM) `curl -fsSL https://bun.sh/install | bash`

**Comment by bhagyaarakeri** [comment]
I was facing same issue after migration from old laptop to new M2 Mac. I tried all the steps mentioned above, reinstalled node by removing old files. But did not work. I tried by installing rosetta. It worked!
