### ISSUE TITLE
Error decorators with graphql in nestjs

### ISSUE THREAD

**Issue by tuan-zigvy** [oven-sh/bun#6181]
### What version of Bun is running?

v1.0.3 

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

error: Schema must contain uniquely named types but contains multiple types named "Profile".
      at new GraphQLSchema (/home/tuan-dd/repos/project_mentor/node_modules/graphql/type/schema.js:219:14)
      at /home/tuan-dd/repos/project_mentor/node_modules/@nestjs/graphql/dist/schema-builder/graphql-schema.factory.js:38:23

### What is the expected behavior?

```
@ObjectType()
@Entity({ name: 'profiles' })
export class Profile extends BaseEntityExtend {
  @Field(() => User)
  @OneToOne(() => User, (user) => user.profile)
  @JoinColumn()
  owner: Relation<User>;

  @Field(() => Number)
  @Column()
  ownerId: number;

  @Field(() => GraphQLJSON)
  @Column({ type: 'json', default: {} })
  meta_data: IMetaDataProfile;

  @Field()
  @Column({ type: 'decimal', width: 100, default: 100 })
  score: number;
}
```

**Comment by tuan-zigvy** [comment]
Help me please
