### ISSUE TITLE
dts-buddy does not work

### ISSUE THREAD

**Issue by ryoppippi** [oven-sh/bun#6196]
### What version of Bun is running?
1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?
Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

- git clone https://github.com/Rich-Harris/dts-buddy
- bun i
- bun run test/test.js

### What is the expected behavior?

Test works fine

### What do you see instead?

https://github.com/Rich-Harris/dts-buddy/issues/56

```sh
✦ ➜ bun i
 ➜ bun run test/test.js
• • • • • • • • ✘ • • • • • • • • ✘ ✘ • •   (18 / 21)

   FAIL  "basic"
    index.d.ts  (equal)

        ··declare·module·'basic'·{
        Expected:
        ++→/**·A·vector·with·two·components·*/
        ++→export·interface·Vector2·{
        ++→→/**·The·x·component·*/
        ++→→x:·number;
        ++→→/**·The·y·component·*/
        ++→→y:·number;
        ++→}
        ··→/**
        ··→·*·Add·two·vectors
        ··→·*·@param·a·the·first·vector
        ··→·*·@param·b·the·second·vector
        ··→·*·*/
        ··→export·function·add(a:·Vector2,·b:·Vector2):·Vector2;
        Actual:
        --→/**·A·vector·with·two·components·*/
        --→interface·Vector2·{
        --→→/**·The·x·component·*/
        --→→x:·number;
        --→→/**·The·y·component·*/
        --→→y:·number;
        --→}
        ··}
        ··↵
        ··declare·module·'basic/subpackage'·{
        ··→/**
        ··→·*·Multiply·two·vectors
        ··→·*·*/
        Actual:
        --→export·function·multiply(a:·any,·b:·any):·any;
        Expected:
        ++→export·function·multiply(a:·import('basic').Vector2,·b:·import('basic').Vector2):·import('basic').Vector2;
        ··}
        ··↵
        ··//#·sourceMappingURL=index.d.ts.map

    at <anonymous> (/private/tmp/dts-buddy/node_modules/uvu/assert/index.mjs:32:85)
    at equal (/private/tmp/dts-buddy/node_modules/uvu/assert/index.mjs:44:96)
    at <anonymous> (/private/tmp/dts-buddy/test/test.js:54:2)
    at asyncFunctionResume (native)
    at promiseReactionJobWithoutPromiseUnwrapAsyncContext (native)
    at promiseReactionJob (native)
    at processTicksAndRejections (native)


   FAIL  "ts"
    index.d.ts  (equal)

        Actual:
        --declare·module·'ts/subpackage'·{
        --→import·type·{·Vector2·}·from·'ts';
        --→/**
        --→·*·Multiply·two·vectors
        --→·*/
        --→export·function·multiply(a:·Vector2,·b:·Vector2):·Vector2;
        --}
        --↵
        ··declare·module·'ts'·{
        ··→/**·A·vector·with·two·components·*/
        ··→export·interface·Vector2·{
        ··→→/**·The·x·component·*/
        ··→→x:·number;
        ··→→/**·The·y·component·*/
        ··→→y:·number;
        ··→}
        ··→/**·A·vector·with·three·components·*/
        ··→export·interface·Vector3·extends·Vector2·{
        ··→→/**·The·z·component·*/
        ··→→z:·number;
        ··→}
        ··→/**
        ··→·*·Add·two·vectors
        ··→·*/
        ··→export·function·add(a:·Vector2,·b:·Vector2):·Vector2;
        ··}
        ··↵
        Expected:
        ++declare·module·'ts/subpackage'·{
        ++→import·type·{·Vector2·}·from·'ts';
        ++→/**
        ++→·*·Multiply·two·vectors
        ++→·*/
        ++→export·function·multiply(a:·Vector2,·b:·Vector2):·Vector2;
        ++}
        ++↵
        ··//#·sourceMappingURL=index.d.ts.map

    at <anonymous> (/private/tmp/dts-buddy/node_modules/uvu/assert/index.mjs:32:85)
    at equal (/private/tmp/dts-buddy/node_modules/uvu/assert/index.mjs:44:96)
    at <anonymous> (/private/tmp/dts-buddy/test/test.js:54:2)
    at asyncFunctionResume (native)
    at promiseReactionJobWithoutPromiseUnwrapAsyncContext (native)
    at promiseReactionJob (native)
    at processTicksAndRejections (native)


   FAIL  "export-default-as"
    index.d.ts  (equal)

        ··declare·module·'export-default-as'·{
        ··→/**
        ··→·*·Add·two·numbers
        ··→·*·*/
        Actual:
        --→export·default·function·add(a:·number,·b:·number):·number;
        Expected:
        ++→export·function·add(a:·number,·b:·number):·number;
        ··}
        ··↵
        ··//#·sourceMappingURL=index.d.ts.map

    at <anonymous> (/private/tmp/dts-buddy/node_modules/uvu/assert/index.mjs:32:85)
    at equal (/private/tmp/dts-buddy/node_modules/uvu/assert/index.mjs:44:96)
    at <anonymous> (/private/tmp/dts-buddy/test/test.js:54:2)
    at asyncFunctionResume (native)
    at promiseReactionJobWithoutPromiseUnwrapAsyncContext (native)
    at promiseReactionJob (native)
    at processTicksAndRejections (native)



  Total:     21
  Passed:    18
  Skipped:   0
  Duration:  15897.03ms
```

**Comment by ryoppippi** [comment]
In Canary `1.0.4+c21be13be42f6ca9ec368bd52eee4dc6129f156c`

```sh
➜ bun run test/test.js
• • • • • • • • • ✘ • • • • • • • • ✘ ✘ • •   (19 / 22)

   FAIL  "basic"
    index.d.ts  (equal)

        ··declare·module·'basic'·{
        Expected:
        ++→/**·A·vector·with·two·components·*/
        ++→export·interface·Vector2·{
        ++→→/**·The·x·component·*/
        ++→→x:·number;
        ++→→/**·The·y·component·*/
        ++→→y:·number;
        ++→}
        ··→/**
        ··→·*·Add·two·vectors
        ··→·*·@param·a·the·first·vector
        ··→·*·@param·b·the·second·vector
        ··→·*·*/
        ··→export·function·add(a:·Vector2,·b:·Vector2):·Vector2;
        Actual:
        --→/**·A·vector·with·two·components·*/
        --→interface·Vector2·{
        --→→/**·The·x·component·*/
        --→→x:·number;
        --→→/**·The·y·component·*/
        --→→y:·number;
        --→}
        ··}
        ··↵
        ··declare·module·'basic/subpackage'·{
        ··→/**
        ··→·*·Multiply·two·vectors
        ··→·*·*/
        Actual:
        --→export·function·multiply(a:·any,·b:·any):·any;
        Expected:
        ++→export·function·multiply(a:·import('basic').Vector2,·b:·import('basic').Vector2):·import('basic').Vector2;
        ··}
        ··↵
        ··//#·sourceMappingURL=index.d.ts.map

    at assert (/private/tmp/dts-buddy/node_modules/uvu/assert/index.mjs:32:85)
    at equal (/private/tmp/dts-buddy/node_modules/uvu/assert/index.mjs:44:96)
    at <anonymous> (/private/tmp/dts-buddy/test/test.js:55:2)
    at asyncFunctionResume (native)
    at promiseReactionJobWithoutPromiseUnwrapAsyncContext (native)
    at promiseReactionJob (native)
    at processTicksAndRejections (native)


   FAIL  "ts"
    index.d.ts  (equal)

        Actual:
        --declare·module·'ts/subpackage'·{
        --→import·type·{·Vector2·}·from·'ts';
        --→/**
        --→·*·Multiply·two·vectors
        --→·*/
        --→export·function·multiply(a:·Vector2,·b:·Vector2):·Vector2;
        --}
        --↵
        ··declare·module·'ts'·{
        ··→/**·A·vector·with·two·components·*/
        ··→export·interface·Vector2·{
        ··→→/**·The·x·component·*/
        ··→→x:·number;
        ··→→/**·The·y·component·*/
        ··→→y:·number;
        ··→}
        ··→/**·A·vector·with·three·components·*/
        ··→export·interface·Vector3·extends·Vector2·{
        ··→→/**·The·z·component·*/
        ··→→z:·number;
        ··→}
        ··→/**
        ··→·*·Add·two·vectors
        ··→·*/
        ··→export·function·add(a:·Vector2,·b:·Vector2):·Vector2;
        ··}
        ··↵
        Expected:
        ++declare·module·'ts/subpackage'·{
        ++→import·type·{·Vector2·}·from·'ts';
        ++→/**
        ++→·*·Multiply·two·vectors
        ++→·*/
        ++→export·function·multiply(a:·Vector2,·b:·Vector2):·Vector2;
        ++}
        ++↵
        ··//#·sourceMappingURL=index.d.ts.map

    at assert (/private/tmp/dts-buddy/node_modules/uvu/assert/index.mjs:32:85)
    at equal (/private/tmp/dts-buddy/node_modules/uvu/assert/index.mjs:44:96)
    at <anonymous> (/private/tmp/dts-buddy/test/test.js:55:2)
    at asyncFunctionResume (native)
    at promiseReactionJobWithoutPromiseUnwrapAsyncContext (native)
    at promiseReactionJob (native)
    at processTicksAndRejections (native)


   FAIL  "export-default-as"
    index.d.ts  (equal)

        ··declare·module·'export-default-as'·{
        ··→/**
        ··→·*·Add·two·numbers
        ··→·*·*/
        Actual:
        --→export·default·function·add(a:·number,·b:·number):·number;
        Expected:
        ++→export·function·add(a:·number,·b:·number):·number;
        ··}
        ··↵
        ··//#·sourceMappingURL=index.d.ts.map

    at assert (/private/tmp/dts-buddy/node_modules/uvu/assert/index.mjs:32:85)
    at equal (/private/tmp/dts-buddy/node_modules/uvu/assert/index.mjs:44:96)
    at <anonymous> (/private/tmp/dts-buddy/test/test.js:55:2)
    at asyncFunctionResume (native)
    at promiseReactionJobWithoutPromiseUnwrapAsyncContext (native)
    at promiseReactionJob (native)
    at processTicksAndRejections (native)



  Total:     22
  Passed:    19
  Skipped:   0
  Duration:  21862.27ms
```

**Comment by ryoppippi** [comment]
It works on 1.0.6

**Comment by ryoppippi** [comment]
OH not works...

**Comment by maxmilton** [comment]
I've been using `dts-buddy` successfully in my bun projects for quite a while now. @ryoppippi check if it works now for you and consider closing this issue.
