### ISSUE TITLE
Graphql problem: Failed to construct 'Request': signal is not of type AbortSignal

### ISSUE THREAD

**Issue by pstachula-dev** [oven-sh/bun#6304]
### What version of Bun is running?

1.0.4+df9461ecc58e2882afa34cdf59d9887d9242b5f9

### What platform is your computer?

Linux 6.4.16-1-MANJARO x86_64 unknown

### What steps can reproduce the bug?

I have Fastify server with REST and Graphql endpoints.

On REST everything works fine, but on Graphql-yoga I have errors:

```
"stack":
          Error: Failed to construct 'Request': signal is not of type AbortSignal.
              at Request (native)
              at normalizeNodeRequest (/home/pawel/projects/work/bun-beta/node_modules/@whatwg-node/server/esm/utils.js:95:32)
              at handleNodeRequest (/home/pawel/projects/work/bun-beta/node_modules/@whatwg-node/server/esm/createServerAdapter.js:112:51)
              at <anonymous> (/home/pawel/projects/work/bun-beta/src/index.ts:71:8)
              at handler (/home/pawel/projects/work/bun-beta/src/index.ts:70:23)
```

**Comment by Electroid** [comment]
Duplicate of #5589

**Comment by klippx** [comment]
I am still getting this on graphql-yoga (`5.0.0`) and bun (`1.0.14`)
