### ISSUE TITLE
Error with `@terascope/fetch-github-release`

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#6309]
Hi! I'm trying to use this module https://github.com/terascope/fetch-github-release but it just gives an error :(
Is something just not compatible with Bun yet? Or am I just stupid and didn't make it work properly?

_Originally reported on Discord: [`Need help with Nodejs module on Bun`](https://discord.com/channels/876711213126520882/1159243234241953863/1159243234241953863)_

**Comment by colinhacks** [comment]
Reproduction

```ts
const { downloadRelease } = require("@terascope/fetch-github-release");

const user = "colinhacks";
const repo = "zod";
const outputdir = "./downloads";
const leaveZipped = false;
const disableLogging = false;

// Define a function to filter releases.
function filterRelease(release) {
  // Filter out prereleases.
  return release.prerelease === false;
}

// Define a function to filter assets.
function filterAsset(asset) {
  // Select assets that contain the string 'windows'.
  return asset.name.includes("windows");
}

downloadRelease(
  user,
  repo,
  outputdir,
  filterRelease,
  filterAsset,
  leaveZipped,
  disableLogging
)
  .then(function () {
    console.log("All done!");
  })
  .catch(function (err) {
    // console.log(`ERROR`);
    console.log(err);
    console.error(err.message);
  });

```

Error

```
$ bun run fgr.ts     
121 |   connecting = !1;
122 |   timeout = 0;
123 |   isServer = !1;
124 |   #address;
125 | 
126 |   address() {
                     ^
TypeError: undefined is not an object
      at address (node:http:126:18)
      at node:http:164:38
      at ip (/Users/colinmcd94/Documents/bun/fun/node_modules/got/dist/source/core/index.js:1398:71)
      at /Users/colinmcd94/Documents/bun/fun/node_modules/got/dist/source/core/index.js:793:27
      at _onResponseBase (/Users/colinmcd94/Documents/bun/fun/node_modules/got/dist/source/core/index.js:778:26)
      at /Users/colinmcd94/Documents/bun/fun/node_modules/got/dist/source/core/index.js:948:18
      at _onResponse (/Users/colinmcd94/Documents/bun/fun/node_modules/got/dist/source/core/index.js:946:22)
      at /Users/colinmcd94/Documents/bun/fun/node_modules/got/dist/source/core/index.js:962:17
      at /Users/colinmcd94/Documents/bun/fun/node_modules/@szmarczak/http-timer/dist/source/index.js:43:19
```

**Comment by colinhacks** [comment]
Reproduction (you have to remove some error handling logic from inside `node_modules/got` to get a more informative error here.)

```ts
const { downloadRelease } = require("@terascope/fetch-github-release");

const user = "colinhacks";
const repo = "zod";
const outputdir = "./downloads";
const leaveZipped = false;
const disableLogging = false;

// Define a function to filter releases.
function filterRelease(release) {
  // Filter out prereleases.
  return release.prerelease === false;
}

// Define a function to filter assets.
function filterAsset(asset) {
  // Select assets that contain the string 'windows'.
  return asset.name.includes("windows");
}

downloadRelease(
  user,
  repo,
  outputdir,
  filterRelease,
  filterAsset,
  leaveZipped,
  disableLogging
)
  .then(function () {
    console.log("All done!");
  })
  .catch(function (err) {
    // console.log(`ERROR`);
    console.log(err);
    console.error(err.message);
  });
```

Error

```
bun run fgr.ts     
121 |   connecting = !1;
122 |   timeout = 0;
123 |   isServer = !1;
124 |   #address;
125 | 
126 |   address() {
                     ^
TypeError: undefined is not an object
      at address (node:http:126:18)
      at node:http:164:38
      at ip (/Users/colinmcd94/Documents/bun/fun/node_modules/got/dist/source/core/index.js:1398:71)
      at /Users/colinmcd94/Documents/bun/fun/node_modules/got/dist/source/core/index.js:793:27
      at _onResponseBase (/Users/colinmcd94/Documents/bun/fun/node_modules/got/dist/source/core/index.js:778:26)
      at /Users/colinmcd94/Documents/bun/fun/node_modules/got/dist/source/core/index.js:948:18
      at _onResponse (/Users/colinmcd94/Documents/bun/fun/node_modules/got/dist/source/core/index.js:946:22)
      at /Users/colinmcd94/Documents/bun/fun/node_modules/got/dist/source/core/index.js:962:17
      at /Users/colinmcd94/Documents/bun/fun/node_modules/@szmarczak/http-timer/dist/source/index.js:43:19
```

**Comment by Alixxx-please** [comment]
https://github.com/oven-sh/bun/commit/5da79a8366e74e921dbf752ba2a33b4308170b48 will fix this issue? So next release it should work?
