### ISSUE TITLE
Failed to load url bun:sqlite

### ISSUE THREAD

**Issue by quantuminformation** [oven-sh/bun#6354]
### What version of Bun is running?

1.0.5+4a2e1574e4d4001b60c96a315491dd622d7d54b6

### What platform is your computer?

Darwin 23.0.0 x86_64 i386

### What steps can reproduce the bug?

I have a SolidStart app with tsconfig:

```js
{
  "compilerOptions": {
    // add Bun type definitions
    "types": ["bun-types"],

    // enable latest features
    "lib": ["ESNext"],
    "module": "esnext",
    "target": "esnext",

    // if TS 5.x+
    "moduleResolution": "bundler",
    "noEmit": true,
    "allowImportingTsExtensions": true,
    "moduleDetection": "force",

    "jsx": "react-jsx", // support JSX
    "allowJs": true, // allow importing `.js` from `.ts`

    // best practices
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true,
    "composite": true,
    "downlevelIteration": true,
    "allowSyntheticDefaultImports": true,
    "paths": {
      "~/*": ["./src/*"]
    }
  }
}
```

### What is the expected behavior?

No error

### What do you see instead?

```
➜  coffeeconnect git:(drizzle) ✗ bun dev
$ concurrently -c auto bun:dev:*
[solid] $ solid-start dev
[solid]  solid-start dev
[solid]  version  0.3.6
[solid]  adapter  node
[solid]
[solid]   VITE v4.4.11  ready in 769 ms
[solid]
[solid]   ➜  Local:   http://localhost:3000/
[solid]   ➜  Network: use --host to expose
[solid]   ➜  Inspect: http://localhost:3000/__inspect/
[solid]
[solid]   ➜  Page Routes:
[solid]      ┌─ http://localhost:3000/*404
[solid]      ├─ http://localhost:3000/
[solid]      ├─ http://localhost:3000/:lang.old
[solid]      ├─ http://localhost:3000/:lang/
[solid]      ├─ http://localhost:3000/:lang/sign_in
[solid]      ├─ http://localhost:3000/:lang/sign_up
[solid]      └─ http://localhost:3000/:lang/terms
[solid]
[solid]   ➜  API Routes:
[solid]      None! 👻
[solid]
[solid] GET http://localhost:3000/
[solid] Failed to load url bun:sqlite (resolved id: bun:sqlite) in /Users/nikos/WebstormProjects/coffeeconnect/src/lib/db/index.ts. Does the file exist?
[solid] 14:53:52 [vite] Error when evaluating SSR module /src/lib/db/index.ts: failed to import "bun:sqlite"
[solid] |- Error: Cannot find module 'bun:sqlite' imported from '/Users/nikos/WebstormProjects/coffeeconnect/src/lib/db/index.ts'
[solid]     at nodeImport (file:///Users/nikos/WebstormProjects/coffeeconnect/node_modules/.pnpm/vite@4.4.11/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:56075:25)
[solid]     at ssrImport (file:///Users/nikos/WebstormProjects/coffeeconnect/node_modules/.pnpm/vite@4.4.11/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:55977:30)
[solid]     at eval (/Users/nikos/WebstormProjects/coffeeconnect/src/lib/db/index.ts:4:37)
[solid]     at async instantiateModule (file:///Users/nikos/WebstormProjects/coffeeconnect/node_modules/.pnpm/vite@4.4.11/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:56039:9)

```

### Additional information

package

```json
{
  "name": "cafeskillz",
  "scripts": {
    "db:migrate:create": "drizzle-kit generate:sqlite --config drizzle.config.ts",
    "db:migrate": "bun ./src/lib/db/migrate.ts",
    "db:seed": "bun ./src/lib/db/seed.ts",
    "db:delete": "rm sqlite.db",
    "db:reset": "concurrently -m 1 -c auto bun:db:delete bun:db:migrate bun:db:seed",
    "typesense:start": "docker run --name typesense-cs -d --rm -p 8108:8108 -v/tmp/cs-ts-data:/data typesense/typesense:0.25.0 --data-dir /data --api-key=78f964f5029c49848e16f7dbb0317839",
    "typesense:stop": "docker stop typesense-ecs",
    "build": "concurrently -m 1 -c auto bun:build:*",
    "build:solid": "solid-start build",
    "dev": "concurrently -c auto bun:dev:*",
    "dev:solid": "solid-start dev",
    "lint": "eslint \"**/*.{ts,tsx}\" && tsc -p tsconfig.json --noEmit --skipLibCheck --pretty",
    "lint:fix": "eslint src/**/*.{ts,tsx} --fix",
    "test": "bun test",
    "test:watch": "bun test --watch",
    "start": "solid-start start",
    "prettier": "prettier --write \"**/*.{js,json,ts,tsx,css,scss,html}\"",
    "debug": "bun --inspect-brk src/lib/db/seed_index.ts"
  },
  "type": "module",
  "dependencies": {
    "@solid-primitives/i18n": "^2.0.0",
    "@solid-primitives/props": "^3.1.8",
    "@solidjs/meta": "^0.28.6",
    "@solidjs/router": "^0.8.3",
    "@tanstack/solid-query": "5.0.0-alpha.20",
    "@trpc/client": "^10.38.5",
    "@trpc/server": "^10.38.5",
    "bcryptjs": "^2.4.3",
    "dotenv": "^16.3.1",
    "drizzle-orm": "^0.28.6",
    "p-queue": "^7.4.1",
    "solid-app-router": "^0.4.2",
    "solid-headless": "^0.13.1",
    "solid-heroicons": "^3.2.4",
    "solid-js": "latest",
    "solid-start": "latest",
    "solid-start-trpc": "latest",
    "solid-trpc": "0.1.0-sssr.7",
    "typesense": "^1.7.1",
    "validator": "^13.11.0",
    "zod": "^3.22.4"
  },
  "devDependencies": {
    "@solidjs/testing-library": "^0.8.4",
    "@tailwindcss/forms": "^0.5.6",
    "@testing-library/jest-dom": "^6.1.3",
    "@testing-library/user-event": "^14.5.1",
    "@types/bcryptjs": "^2.4.4",
    "@types/validator": "^13.11.2",
    "@typescript-eslint/eslint-plugin": "^6.7.4",
    "@typescript-eslint/parser": "^6.7.4",
    "autoprefixer": "^10.4.16",
    "better-sqlite3": "^8.7.0",
    "bun-types": "^1.0.4",
    "concurrently": "^8.2.1",
    "cross-env": "^7.0.3",
    "drizzle-kit": "^0.19.13",
    "eslint": "^8.50.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "eslint-plugin-solid": "^0.13.0",
    "jsdom": "^22.1.0",
    "postcss": "^8.4.31",
    "prettier": "^3.0.3",
    "prettier-plugin-tailwindcss": "^0.5.5",
    "solid-start-node": "latest",
    "tailwindcss": "^3.3.3",
    "typescript": "^5.2.2",
    "vite": "4.4.11"
  }
}
```

**Comment by Electroid** [comment]
Try `bun --bun dev`, the error suggests that the code is running in Node instead.
