### ISSUE TITLE
Support Rakkas (Vite/React framework) - Create CLI

### ISSUE THREAD

**Issue by birkskyum** [oven-sh/bun#6384]
Rakkas - [Website](https://rakkasjs.org/) - [GitHub](https://github.com/rakkasjs/rakkasjs)

### What version of Bun is running?

1.0.5+35109160ca5d439116bedeb3302ec3745e2895d5

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

* `bunx --bun create-rakkas-app@latest my-rakkas-app`

### What is the expected behavior?

```sh
? Enable features TypeScript, Prettier, ESLint, Vitest, Demo
Project generated in my-rakkas-app. Do the following to get started:
  cd my-rakkas-app3   # Go to the project directory
  npm install         # Install dependencies
  npm run dev         # Start development server
  npm run build       # Build for production
  npm start           # Start production server

```

### What do you see instead?

```sh
➜ bunx --bun create-rakkas-app@latest my-rakkas-app
 RAKKAS  0.6.20 💃
? Enable features 
2055 |         state.dataEmitted = !0, this.emit("data", ret);
2056 |       return ret;
2057 |     }, Readable.prototype._read = function(n) {
2058 |       throw new ERR_METHOD_NOT_IMPLEMENTED("_read()");
2059 | 
2060 |     }, Readable.prototype.pipe = function(dest, pipeOpts) {
                                                                                     ^
TypeError: undefined is not an object
      at node:stream:2060:82
      at /private/tmp/create-rakkas-app@latest--bunx/node_modules/cpr/lib/index.js:178:12
      at callback (/private/tmp/create-rakkas-app@latest--bunx/node_modules/graceful-fs/polyfills.js:306:16)
      at processTicksAndRejections (:55:76)
```

**Comment by birkskyum** [comment]
now it throws at:

```sh
➜ bunx --bun create-rakkas-app@latest my-rakkas-app
 RAKKAS  0.6.20 💃
? Enable features TypeScript, Prettier, ESLint, Vitest, Demo
173 |             fromFile.on('error', onError);
174 |             toFile.on('error', onError);
175 |             toFile.once('finish', function() {
176 |                 cb(err);
177 |             });
178 |             fromFile.pipe(toFile);
                  ^
TypeError: undefined is not an object
      at node:stream:2087:83
      at /private/tmp/bunx-501-create-rakkas-app@latest/node_modules/cpr/lib/index.js:178:13
      at callback (/private/tmp/bunx-501-create-rakkas-app@latest/node_modules/graceful-fs/polyfills.js:306:17)

Bun v1.1.8-canary.1+3c082012b (macOS arm64)
```

**Comment by birkskyum** [comment]
The creation script completes as expected:

```sh
➜ bunx --bun create-rakkas-app@latest my-rakkas-app3
 RAKKAS  0.6.20 💃
? Enable features TypeScript, Prettier, ESLint, Vitest, Demo
Project generated in my-rakkas-app3. Do the following to get started:
  cd my-rakkas-app3   # Go to the project directory
  bun install         # Install dependencies
  bun run dev         # Start development server
  bun run build       # Build for production
  bun start           # Start production server
```

Revision: 1.1.10-canary.1+4b8f89cb7
