### ISSUE TITLE
bun 1.0.5 crashes in docker container

### ISSUE THREAD

**Issue by sartak** [oven-sh/bun#6426]
### What version of Bun is running?

1.0.5+1bf28e0d77a8b2261befbdb708cefd03e0126960

### What platform is your computer?

Linux 5.4.0-144-generic x86_64 x86_64

### What steps can reproduce the bug?

```
λ echo 'console.log("Hello, world!");' > hello.js
λ bun run hello.js
Aborted (core dumped)
```

### What is the expected behavior?

bun prints `Hello, world!`

### What do you see instead?

bun exits with `Aborted (core dumped)`

### Additional information

This is crash is a regression; bun 1.0.4 was working (mostly) fine in the same environment.

```
λ gdb bun core
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
…
Reading symbols from bun...
(No debugging symbols found in bun)
[New LWP 104]
[New LWP 105]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `bun run hello.js'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139868208651200)
    at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
[Current thread is 1 (Thread 0x7f359ae45bc0 (LWP 104))]

(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139868208651200)
    at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=139868208651200)
    at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=139868208651200, signo=signo@entry=6)
    at ./nptl/pthread_kill.c:89
#3  0x00007f359ae8c476 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/posix/raise.c:26
#4  0x00007f359ae72885 in __GI_abort () at ./stdlib/abort.c:100
#5  0x0000562ed4f3623e in ?? ()
#6  0x0000562ed4f35839 in ?? ()
#7  0x00007f359aee3ee8 in __pthread_once_slow (once_control=0x562ed6ce68e8,
    init_routine=0x562ed43272e0) at ./nptl/pthread_once.c:116
#8  0x0000562ed4f35579 in ?? ()
#9  0x00007f359aee3ee8 in __pthread_once_slow (once_control=0x562ed6ce68d8,
    init_routine=0x562ed43272e0) at ./nptl/pthread_once.c:116
#10 0x0000562ed4ef1b78 in ?? ()
#11 0x0000562ed45ed726 in ?? ()
#12 0x0000562ed460a670 in ?? ()
#13 0x0000562ed610e06d in ?? ()
#14 0x0000562ed36494a0 in ?? ()
#15 0x0000562ed3848362 in ?? ()
#16 0x0000562ed386df0d in ?? ()
#17 0x0000562ed386f20f in ?? ()
#18 0x0000562ed3616040 in ?? ()
#19 0x0000562ed3613eaa in ?? ()
#20 0x00007f359ae73d90 in __libc_start_call_main (
    main=main@entry=0x562ed3613b60, argc=argc@entry=3,
    argv=argv@entry=0x7ffe06034308)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#21 0x00007f359ae73e40 in __libc_start_main_impl (main=0x562ed3613b60, argc=3,
    argv=0x7ffe06034308, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7ffe060342f8)
    at ../csu/libc-start.c:392
#22 0x0000562ed32d812a in ?? ()
```

If you ship bun builds with debugging symbols, I'd be happy to switch to that to give a better stacktrace.

**Comment by Electroid** [comment]
Related to #6421

**Comment by Jarred-Sumner** [comment]
Please upgrade to Bun v1.0.6 (released 10 minutes ago) which should fix this

Leave a comment if you still run into it

**Comment by sartak** [comment]
My app works again now, thank you for the quick fix!
