### ISSUE TITLE
dyld[30845]: missing symbol called / undefined symbol: uv_mutex_lock

### ISSUE THREAD

**Issue by zx8086** [oven-sh/bun#6506]
### What version of Bun is running?

1.0.6

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Install Couchbase Server / Couchbase Capella Cloud -> _docker run -t --name db -p 8091-8096:8091-8096 -p 11210-11211:11210-11211 couchbase/server:enterprise-7.2.0_ or _https://cloud.couchbase.com/_ 
Install Couchbase SDK ->  _bun add couchbase@4.2.7_
Run Bun -> _bun index.js_

_index.js_
```js
const couchbase = require('couchbase')

async function main() {
  const cluster = await couchbase.connect(
    'couchbase://127.0.0.1',
    {
      username: 'username',
      password: 'password',
    })

  const bucket = cluster.bucket('default')
  const coll = bucket.defaultCollection()
  await coll.upsert('testdoc', { foo: 'bar' })

  const res = await coll.get('testdoc')
  console.log(res.content)
}

// Run the main function
main()
  .then((_) => {
    console.log ('Success!')
  })
  .catch((err) => {
    console.log('ERR:', err)
  })
```

Reference: https://docs.couchbase.com/nodejs-sdk/current/hello-world/start-using-sdk.html

### What is the expected behavior?

Runs and connects to a Couchbase Instance

### What do you see instead?

bun add couchbase@4.2.5
```
bun run index.js       
121 |         throw e;
122 |       }
123 |     }
124 |   }
125 | 
126 |   err = new Error(
            ^
error: Could not locate the bindings file. Tried:
 → /Users/me/Documents/bun-couchbase/node_modules/couchbase/build/couchbase_impl.node
 → /Users/me/Documents/bun-couchbase/node_modules/couchbase/build/Debug/couchbase_impl.node
 → /Users/me/Documents/bun-couchbase/node_modules/couchbase/build/Release/couchbase_impl.node
 → /Users/me/Documents/bun-couchbase/node_modules/couchbase/out/Debug/couchbase_impl.node
 → /Users/me/Documents/bun-couchbase/node_modules/couchbase/Debug/couchbase_impl.node
 → /Users/me/Documents/bun-couchbase/node_modules/couchbase/out/Release/couchbase_impl.node
 → /Users/me/Documents/bun-couchbase/node_modules/couchbase/Release/couchbase_impl.node
 → /Users/me/Documents/bun-couchbase/node_modules/couchbase/build/default/couchbase_impl.node
 → /Users/me/Documents/bun-couchbase/node_modules/couchbase/compiled/20.8.0/darwin/arm64/couchbase_impl.node
 → /Users/me/Documents/bun-couchbase/node_modules/couchbase/addon-build/release/install-root/couchbase_impl.node
 → /Users/me/Documents/bun-couchbase/node_modules/couchbase/addon-build/debug/install-root/couchbase_impl.node
 → /Users/me/Documents/bun-couchbase/node_modules/couchbase/addon-build/default/install-root/couchbase_impl.node
 → /Users/me/Documents/bun-couchbase/node_modules/couchbase/lib/binding/node-v115-darwin-arm64/couchbase_impl.node
      at bindings (/Users/me/Documents/bun-couchbase/node_modules/bindings/bindings.js:126:8)
      at /Users/me/Documents/bun-couchbase/node_modules/couchbase/dist/binding.js:160:6
      at globalThis (/Users/me/Documents/bun-couchbase/node_modules/couchbase/dist/binding.js:161:18)
      at overridableRequire (:1:20)
      at /Users/me/Documents/bun-couchbase/node_modules/couchbase/dist/couchbase.js:21:18
      at globalThis (/Users/me/Documents/bun-couchbase/node_modules/couchbase/dist/couchbase.js:81:44)
      at overridableRequire (:1:20)
      at /Users/me/Documents/bun-couchbase/index.js:1:6
      at globalThis (/Users/me/Documents/bun-couchbase/index.js:29:28)
```

bun add couchbase@4.2.7
```
dyld[30845]: missing symbol called
zsh: killed     bun run index.js
```

npm i couchbase couchbase@4.2.7

```
233 |     target.push(`libc=${libc}`)
234 |   }
235 |   if (typeof __webpack_require__ === 'function') {
236 |     target.push('webpack=true')
237 |   }
238 |   throw new Error(
            ^
error: Could not find native build for platform=darwin, arch=arm64, runtime=node, nodeVersion=20.8.0, sslType=openssl3 loaded from /Users/me/Documents/bun-couchbase/node_modules/couchbase.
      at resolvePrebuild (/Users/me/Documents/bun-couchbase/node_modules/couchbase/scripts/prebuilds.js:238:8)
      at loadPrebuild (/Users/me/Documents/bun-couchbase/node_modules/couchbase/scripts/prebuilds.js:119:24)
      at /Users/me/Documents/bun-couchbase/node_modules/couchbase/dist/binding.js:158:6
      at globalThis (/Users/me/Documents/bun-couchbase/node_modules/couchbase/dist/binding.js:159:18)
      at overridableRequire (:1:20)
      at /Users/me/Documents/bun-couchbase/node_modules/couchbase/dist/couchbase.js:21:18
      at globalThis (/Users/me/Documents/bun-couchbase/node_modules/couchbase/dist/couchbase.js:102:44)
      at overridableRequire (:1:20)
```

**Comment by Electroid** [comment]
Possibly related to #4959

**Comment by zx8086** [comment]
@Electroid How would i be able to verify? The trustedDependancies approach doesn't work.

**Comment by zx8086** [comment]
@Electroid  Maybe I can reach out to couchbase ?

**Comment by Electroid** [comment]
This is very likely a bug in Bun, not couchbase. We will fix it.

**Comment by mikypilota** [comment]
Same happening with [libxmljs](https://github.com/libxmljs/libxmljs). The library needs to run compilation scripts so it's added to `trustedDependencies`, however, after installation, when running any file with `bun /path/to/file.ts` that imports and uses `libxmljs`, I get:


~~~bash
dyld[<process number>]: missing symbol called
[1]    <process number> killed     bun ./bin/file.ts
~~~

Runs fine on `ts-node`

**Comment by zx8086** [comment]
> Same happening with [libxmljs](https://github.com/libxmljs/libxmljs). The library needs to run compilation scripts so it's added to `trustedDependencies`, however, after installation, when running any file with `bun /path/to/file.ts` that imports and uses `libxmljs`, I get:
> 
> 
> 
> 
> 
> ~~~bash
> 
> dyld[<process number>]: missing symbol called
> 
> [1]    <process number> killed     bun ./bin/file.ts
> 
> ~~~
> 
> 
> 
> Runs fine on `ts-node`

Yeah along the same lines

**Comment by zx8086** [comment]
Any progress / ETA on this ? Been wanting to use Bun for some projects but at this point if this is abandoned, would like to know

**Comment by fatlard1993** [comment]
Seeing the same thing when trying to use [robotjs](https://github.com/octalmage/robotjs) after getting it to build by installing `node-gyp` and adding `robotjs` to the `trustedDependencies`

**Comment by alumni** [comment]
Same thing happens in bun 1.0.18 on macos arm64 if I do `require('@sap/hana-client')`. The package was installed with pnpm and comes with prebuilt binaries (no postinstall step).

**Comment by zx8086** [comment]
SAP and Couchbase are two enterprise solution together with OpenTelemetry that we use in our corporation. This to me makes Bun not production ready.

**Comment by mikypilota** [comment]
If my understanding is correct, it is not the specific compatibility with CouchBase, SAP or libxmljs that has to be looked into, but rather that these packages rely on some modules for which Bun does not yet offer compatibility.

They must be yellow or red modules of [this list](https://bun.sh/docs/runtime/nodejs-apis).

We need to find a quick way to determine which of these modules is the culprit. Maybe we will find out the underlying issue is all about the same module for all of the above mentioned packages, so we can ask to prioritise its implementation for next releases. I would love to help myself for the implementation of these but my Zig skills are not yet up to speed for it.

**Comment by alumni** [comment]
> SAP and Couchbase are two enterprise solution together with OpenTelemetry that we use in our corporation.

For telemetry we're using `dynatrace` like most SAP products, it used to crash at import when `bun` 1.0.0 was launched, now it's no longer crashing (at least at import, haven't tried anything more than that). But yeah, as an alternative, support for any other OpenTelemetry-compatible framework would be great to have.

For `@sap/hana-client`, there is a pure-JS client called `hdb`, but it's quite buggy with certain data types even on nodejs, so the NAPI client would be great to have.

BTW, on Linux x64 the error is more explicit (using `bun@1.0.19`):
```
TypeError: <repo>/node_modules/.pnpm/@sap+hana-client@2.19.20/node_modules/@sap/hana-client/prebuilt/linuxx86_64-gcc6/hana-client.node: undefined symbol: uv_mutex_lock
```

**Comment by zx8086** [comment]
@Electroid  @Jarred-Sumner 

Any timelines for when this will be looked into or completed, it seems every other NPM compatibility issue is being looked into and resolved, even when logged after this.

**Comment by VesterDe** [comment]
This same issue seems to happen when importing any version of `pdfjs-dist`. Which is the prebuilt version of [this](https://github.com/mozilla/pdf.js).

**Comment by calumk** [comment]
Issue also arrising with [node-snap7](https://www.npmjs.com/package/node-snap7)

**Comment by zx8086** [comment]
Waiting for this to ditch node... this and http2 for gRPC 

![305356514-e07c2d6f-709d-42c6-bb86-70b33ba329fb](https://github.com/oven-sh/bun/assets/1085655/ed373130-a399-4e8e-9a01-a5af17f8f8ea)

**Comment by zx8086** [comment]
@Electroid @Jarred-Sumner 

We were excited for Bun, eagerly anticipating starting new projects with Bun, which means delaying or holding development to really give us time to implement & test before fully committing. 

Would help to know if this is feasible & timelines or just to abandon this endeavour. Do you need any help ?

**Comment by ilchenkoArtem** [comment]
the same with `subset-iconfont` package 

```ts
import { MiProvider } from 'subset-iconfont';


const mdi = new MiProvider(['shopping-cart', "shopping-cart-checkout", "delete"], {
  formats: ['woff2'],
  generateMinCss: false,
  generateCssMap: false,
  writeOutFiles: ['web', 'webfonts',"metadata"]
});

mdi.makeFonts('./outputDir').then((result) => {
  console.log('Done!');
});

```

**Comment by MZ-Dlovely** [comment]
new discovery: This error can also occur in `ssh2`

```ts
import 'ssh2'

console.log('ssh2')
// const ssh2 = new Client()
// ssh2.on('ready', () => {
//   console.log('Client :: ready')
//   ssh2.end()
// })
```

```bash
$ bun run test.ts
dyld[7636]: missing symbol called
```

**Comment by JacksonKearl** [comment]
Same in tree-sitter

**Comment by tinypell3ts** [comment]
Same with [ora](https://www.npmjs.com/package/ora).

```
dyld[24639]: missing symbol called
[1]    24639 killed     bun run src/Onboard.ts
```

**Comment by benrohel** [comment]
Same with Konva;

**Comment by paperclover** [comment]
missing symbol called can mean any missing symbol, but the `uv_mutex_t` apis (mentioned at one point in this thread) should not be hard to implement (bun does not use libuv on posix platforms)

**Comment by zx8086** [comment]
@Electroid @Jarred-Sumner @paperdave Thanks for the insight, got it working and now testing... hopefully should be able to close this. 

Running brew install --HEAD libuv
Removing bun.lock & node_modules
Bun Update (with couchbase still in trusted dependencies)

Got a Post install message

**Comment by MataAzi** [comment]
Same on node-ssh

**Comment by gerardmarquinarubio** [comment]
> This same issue seems to happen when importing any version of `pdfjs-dist`. Which is the prebuilt version of [this](https://github.com/mozilla/pdf.js).

Check https://github.com/oven-sh/bun/issues/6608#issuecomment-2008316410, solved it by doing some manual module overriding shenanigans

**Comment by zx8086** [comment]
Figure out the needed dependancies required for postinstall

Running brew install --HEAD libuv
Removing bun.lock & node_modules
Bun Update (with couchbase still in trusted dependencies)

**Comment by Electroid** [comment]
While that is a workaround, we do want to have a proper fix.

**Comment by ohroy** [comment]
frida same

**Comment by jviel** [comment]
the proposed workaround didn't work for me on Linux or Mac.
trying to use zeromq library
```shell
bun: symbol lookup error: /node_modules/zeromq/prebuilds/linux-x64/node.napi.glibc.node: undefined symbol: uv_async_init
```
I can't wait until this is fixed 🤞  - It's the last blocker for my ditching Node + Express + Socket.io

**Comment by alumni** [comment]
> the proposed workaround didn't work for me with Bun v1.1.8 on Linux or Mac.

@jviel Didn't work for me either.

**Comment by Kulimeya** [comment]
Have the same problem with ssh2. I installed it, pushed it to my test server without local testing, worked. Then some hours later I wanted to run my local test setup on my Mac, got this error. Is the only solution to remove it from my project even if my code is already working on the server, just so I can continue developing locally?

**Comment by rgigger** [comment]
Same here. Trying to use ssh2 but I get the above error.

**Comment by nesterow** [comment]
Same. I'm using CGO, linking against c archive `go build -buildmode=c-archive` - works with nodejs.
I am using `node-addon-api`, but the same error was with `node.h`. It seems it happens before or during addon import.
```bash
dyld[<pid>]: missing symbol called
[1]   <pid> abort
```
[binding.gyp](https://github.com/nesterow/dal/blob/main/binding.gyp)

**Comment by Max2Wynn** [comment]
1.1.25 workds. just run `bun upgrade`

**Comment by gle6as** [comment]
> 1.1.25 workds. just run `bun upgrade`

thanks, just spent an hour to figure out how to setup local dev without ssh2

**Comment by aurum16** [comment]
@mikypilota hello, i want to ask you a specific question. can you give me an e-mail address where I can reach you?

**Comment by schroeder-g** [comment]
> Same happening with [libxmljs](https://github.com/libxmljs/libxmljs). The library needs to run compilation scripts so it's added to `trustedDependencies`, however, after installation, when running any file with `bun /path/to/file.ts` that imports and uses `libxmljs`, I get:

Bump, re: libxmljs, using bun `v1.1.34`

**Comment by zackradisic** [comment]
Going to close this as this [new issue tracks](https://github.com/oven-sh/bun/issues/18546) which specific `uv_*` functions are supported and unsupported
