### ISSUE TITLE
NextJS: cannot init a project

### ISSUE THREAD

**Issue by Hunam6** [oven-sh/bun#6540]
### What version of Bun is running?

1.0.6+969da088f5db3258a803ec186012e30f992829b4

### What platform is your computer?

Linux 5.15.0-1034-oracle aarch64 aarch64

### What steps can reproduce the bug?

`bunx create-next-app@latest`

### What is the expected behavior?

NextJS prompting for project configuration

```
$ bunx create-next-app@latest
? What is your project named? › my-app
```

### What do you see instead?

```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'fs/promises'
Require stack:
- /tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Module.4282 (/tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js:74:36214)
    at __nccwpck_require__ (/tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js:74:59951)
    at /tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js:74:60815
    at Object.<anonymous> (/tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js:74:60859)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js'
  ]
}
```

**Comment by Hunam6** [comment]
I had an old Node version installed, I've updated my Node version to latest and it's now working. Shouldn't Bun be independent of Node?

**Comment by Electroid** [comment]
So this is actually running in Node, because `create-next-app` has a script that specifically calls `node`. If you want it to force run Bun, you'll need to do `bunx --bun  create-next-app@latest`

**Comment by Hunam6** [comment]
Oh okay thank you!
