### ISSUE TITLE
happy-DOM error this._getWindow is not a function

### ISSUE THREAD

**Issue by croqaz** [oven-sh/bun#6594]
### What version of Bun is running?

1.0.6

### What platform is your computer?

Void Linux 6.5.7_1 x86_64 x86_64

### What steps can reproduce the bug?

Trying to run a simple happy-dom script from:
https://github.com/capricorn86/happy-dom/wiki/Getting-started#usage

From package.json - "happy-dom": "12.9.1"

```js
const { Window } = require('happy-dom');

const window = new Window({
   url: 'https://localhost:8080',
   width: 1024,
   height: 768
});
const document = window.document;

document.body.innerHTML = '<div class="container"></div>';

const container = document.querySelector('.container');
const button = document.createElement('button');

container.appendChild(button);

// Outputs "<div class="container"><button></button></div>"
console.log(document.body.innerHTML);
```

### What is the expected behavior?

It should print some HTML, not crash.

### What do you see instead?

bun happy.js

```
<div class="container"><button></button></div>
75 |      * @see https://www.quirksmode.org/js/events_order.html#link4
76 |      * @param event Event.
77 |      * @returns The return value is false if event is cancelable and at least one of the event handlers which handled this event called Event.preventDefault().
78 |      */
79 |     dispatchEvent(event) {
80 |         const window = this._getWindow();
                           ^
TypeError: this._getWindow is not a function. (In 'this._getWindow()', 'this._getWindow' is undefined)
      at dispatchEvent (/root/PWD/node_modules/happy-dom/cjs/event/EventTarget.cjs:80:23)
      at dispatchEvent (/root/PWD/node_modules/happy-dom/cjs/event/EventTarget.cjs:102:20)
      at /root/PWD/node_modules/happy-dom/cjs/nodes/document/Document.cjs:877:12
```

### Additional information

The same script works in Node.js v18.18.1.

**Comment by croqaz** [comment]
Also similar bug in happy-DOM: https://github.com/oven-sh/bun/issues/5847

I am only trying it because it's mentioned in the ecosystem test runner: https://bun.sh/guides/test/happy-dom

**Comment by croqaz** [comment]
The issue may be fixed in https://github.com/capricorn86/happy-dom/issues/1085
It's not released yet.
