### ISSUE TITLE
Error: Cannot find module 'combined-stream'

### ISSUE THREAD

**Issue by pro-sumer** [oven-sh/bun#6642]
### What version of Bun is running?

1.0.7

### What platform is your computer?

Linux 6.1.0-rpi4-rpi-v8 aarch64 unknown

### What steps can reproduce the bug?

Run a package that requires axios/form-data after executing `bun install`.

### What is the expected behavior?

Script works fine.

### What do you see instead?

```
node:internal/modules/cjs/loader:1080
  throw err;
  ^
Error: Cannot find module 'combined-stream'
Require stack:
- /usr/local/src/personal/my-test-script/node_modules/form-data/lib/form_data.js
- /usr/local/src/personal/my-test-script/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js
- /usr/local/src/personal/my-test-script/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js
- /usr/local/src/personal/my-test-script/node_modules/jsdom/lib/jsdom/living/generated/XMLHttpRequest.js
- /usr/local/src/personal/my-test-script/node_modules/jsdom/lib/jsdom/living/interfaces.js
- /usr/local/src/personal/my-test-script/node_modules/jsdom/lib/jsdom/browser/Window.js
- /usr/local/src/personal/my-test-script/node_modules/jsdom/lib/api.js
- /usr/local/src/personal/my-test-script/my-test-script.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/usr/local/src/personal/my-test-script/node_modules/form-data/lib/form_data.js:1:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
   code: 'MODULE_NOT_FOUND',
   requireStack: [
     '/usr/local/src/personal/my-test-script/node_modules/form-data/lib/form_data.js',
     '/usr/local/src/personal/my-test-script/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js',
     '/usr/local/src/personal/my-test-script/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js',
     '/usr/local/src/personal/my-test-script/node_modules/jsdom/lib/jsdom/living/generated/XMLHttpRequest.js',
     '/usr/local/src/personal/my-test-script/node_modules/jsdom/lib/jsdom/living/interfaces.js',
     '/usr/local/src/personal/my-test-script/node_modules/jsdom/lib/jsdom/browser/Window.js',
     '/usr/local/src/personal/my-test-script/node_modules/jsdom/lib/api.js',
     '/usr/local/src/personal/my-test-script/my-test-script.js'
   ]
}
```

### Additional information

- Package `combined-stream` is actually installed in `node_modules`...
- When I use `npm install` instead of `bun install` it works fine

**Comment by Electroid** [comment]
Could you share the package.json and code that you used?

**Comment by pro-sumer** [comment]
It's a personal project with private code that I run with a restricted user account on a Raspberry Pi, but this artificial demo project seems to reproduce this issue as well:

Code/install as user `user1`.

`package.json`:
```
{
  "dependencies": {
    "axios": "latest"
  }
}
```

`demo.js`:
```
#!/usr/bin/env node

const axios = require('axios')
```

Install dependencies:
```
bun install --no-save
```

Execute:
```
sudo -u user2 node ./demo.js
```

(both `user1` and `user2` belong to the same group)

Result:
```
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'combined-stream'
Require stack:
- /tmp/node_modules/form-data/lib/form_data.js
- /tmp/node_modules/axios/dist/node/axios.cjs
- /tmp/demo.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/tmp/node_modules/form-data/lib/form_data.js:1:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/node_modules/form-data/lib/form_data.js',
    '/tmp/node_modules/axios/dist/node/axios.cjs',
    '/tmp/demo.js'
  ]
}
```

This works fine (no errors) if:
* I use `npm install --no-save` instead of `bun install --no-save`
* `demo.js` is executed by `user1`

So it might be a user/permission issue, but why would npm and Bun behave differently then?

**Comment by pro-sumer** [comment]
Accidentally closed…

**Comment by pro-sumer** [comment]
Accidentally closed…

**Comment by miso-belica** [comment]
I am getting probably a similar error for package https://www.npmjs.com/package/node-phpass. When I delete `node_modules` and run `bun install` it shows me this:

```
[0.69ms] ".env"
bun install v1.0.7 (b0393fba)
[14.69ms] migrated lockfile from package-lock.json

 147 packages installed [2.19s]
```

But then when I run my Jest it gives me **Cannot find module 'node-phpass' from 'src/user/user.model.ts'**. I see the package is not in `node_modules` at all. What is special is that the package is defined like this in "package.json" `"node-phpass": "git+https://github.com/glauberportella/password-hash.git#78a8a4cefe0ff204313894ba1696eba9bb971a6a",`
