### ISSUE TITLE
Some HTTP tests are failing with supertest-fetch in Bun but not in Node

### ISSUE THREAD

**Issue by v1rtl** [oven-sh/bun#6736]
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157

### What platform is your computer?

Linux 6.5.6-arch2-1-g14 x86_64

### What steps can reproduce the bug?

I'm switching [@tinyhttp/unless](https://github.com/tinyhttp/unless) to Bun and I faced an issue where tests fail with Bun test runner but pass with Node test runner. I perform HTTP tests using [supertest-fetch](https://github.com/jwalton/node-supertest-fetch/) library.

A code snippet using `bun:test`:

```ts
import { describe, it } from 'bun:test'
import { unless, UnlessMiddlewareOptions, CustomUnless } from '@tinyhttp/unless'
import type { Request, Response } from '@tinyhttp/app'
import { IncomingMessage, Server, ServerResponse, createServer } from 'node:http'
import { makeFetch } from 'supertest-fetch'

function exampleMiddleware(_: IncomingMessage, res: ServerResponse): void {
  res.setHeader('MW', 1)
}

function InitAppAndTestUnless(options: UnlessMiddlewareOptions | CustomUnless) {
  const app = createServer((req: Request, res: Response) => {
    unless({ handler: exampleMiddleware, type: 'mw' }, options)(req, res, () => {
      return
    })
    res.statusCode = 200
    res.end()
  })

  const fetch = makeFetch(app as unknown as Server)

  return fetch
}

describe('Unless Middleware custom parameter test', () => {
  it('should execute if function returns false', async () => {
    const fetch = InitAppAndTestUnless(() => false)

    await fetch('/').expectStatus(200).expectHeader('MW', 1)
  })

  it('should not execute if function returns true', async () => {
    const fetch = InitAppAndTestUnless(() => true)

    await fetch('/').expectStatus(200).expectHeader('MW', undefined)
  })
})
```

### What is the expected behavior?

All tests cases should be passing.

Example using `node:test` instead (the rest of the code is unchanged, with `bunx tsx src/index.test.ts`)

```
▶ Unless Middleware custom parameter test
  ✔ should execute if function returns false (57.932853ms)
  ✔ should not execute if function returns true (64.107398ms)

ℹ tests 2
ℹ suites 1
ℹ pass 2
ℹ fail 0
ℹ cancelled 0
ℹ skipped 0
ℹ todo 0
ℹ duration_ms 122.040251
```

### What do you see instead?

One of the cases fails:

```js
bun test
bun test v1.0.7 (b0393fba)

tests/index.test.ts:
349 |       return "".concat(msg).concat(skipped ? skippedMsg : "", `
350 | `).concat(res).concat(other).concat(end).concat(indicator);
351 |     }
352 |     var AssertionError = function(_Error) {
353 | 
354 |       function AssertionError2(options) {
                                                               ^
AssertionError: Request "GET /" should have correct header MW"
 code: "ERR_ASSERTION"

      at new AssertionError2 (node:assert:354:60)
      at innerFail (node:assert:427:44)
      at deepStrictEqual (node:assert:519:112)
      at /home/v1rtl/Coding/tinyhttp/unless/node_modules/supertest-fetch/lib/Test.js:176:24
      at step (/home/v1rtl/Coding/tinyhttp/unless/node_modules/supertest-fetch/lib/Test.js:52:17)
      at /home/v1rtl/Coding/tinyhttp/unless/node_modules/supertest-fetch/lib/Test.js:33:52
      at fulfilled (/home/v1rtl/Coding/tinyhttp/unless/node_modules/supertest-fetch/lib/Test.js:24:47)
      at processTicksAndRejections (:61:76)
✗ Unless Middleware custom parameter test > should execute if function returns false [75.54ms]
✓ Unless Middleware custom parameter test > should not execute if function returns true [3.37ms]
```

### Additional information

I have tried this with supertest and switched to uvu - the results were the same. I even wrote a simple HTTP testing wrapper to try instead of supertest-fetch. One of the potential reasons could be that headers aren't cleaned up but that's my guess.

**Comment by talentlessguy** [comment]
There's a new kind of error on Bun 1.0.12:

```
app.test.ts:
18 |             if (address !== null) {
19 |                 return resolve(new Server(server, address, false));
20 |             }
21 |             var errHandler = function (err) {
22 |                 if (err.code === 'EADDRINUSE') {
23 |                     reject(new Error('Address in use'));
                              ^
error: Address in use
      at errHandler (/tmp/test/node_modules/supertest-fetch/lib/Server.js:23:27)
      at node:events:33:50
      at node:events:2:48
      at listen (node:http:359:16)
      at /tmp/test/node_modules/supertest-fetch/lib/Server.js:33:12
      at new Promise (:1:20)
      at /tmp/test/node_modules/supertest-fetch/lib/Server.js:13:15
      at fetch (/tmp/test/node_modules/supertest-fetch/lib/index.js:58:22)
      at /tmp/test/app.test.ts:27:18
      at /tmp/test/app.test.ts:26:49
✗ Unless Middleware custom parameter test > should execute if function returns false [3.57ms]
18 |             if (address !== null) {
19 |                 return resolve(new Server(server, address, false));
20 |             }
21 |             var errHandler = function (err) {
22 |                 if (err.code === 'EADDRINUSE') {
23 |                     reject(new Error('Address in use'));
                              ^
error: Address in use
      at errHandler (/tmp/test/node_modules/supertest-fetch/lib/Server.js:23:27)
      at node:events:33:50
      at node:events:2:48
      at listen (node:http:359:16)
      at /tmp/test/node_modules/supertest-fetch/lib/Server.js:33:12
      at new Promise (:1:20)
      at /tmp/test/node_modules/supertest-fetch/lib/Server.js:13:15
      at fetch (/tmp/test/node_modules/supertest-fetch/lib/index.js:58:22)
      at /tmp/test/app.test.ts:33:18
      at /tmp/test/app.test.ts:32:52
✗ Unless Middleware custom parameter test > should not execute if function returns true [1.08ms]

 0 pass
 2 fail
Ran 2 tests across 1 files. [33.00ms]
```

as said before, this only happens in Bun. There are no problems with Node.js

**Comment by rupurt** [comment]
I get something similar on async tests with `bun:test` and fastify. Most of the time the fetch request hits the server after the test has completed and fastify rejects it because it's stopping the server. Works fine with `node:test` and `tsx`

```shell
{"level":30,"time":1700246569144,"pid":874959,"hostname":"kawasaki-desktop","msg":"Server listening at http://[::]:8080"}
{"level":30,"time":1700246569145,"pid":874959,"hostname":"kawasaki-desktop","reqId":"req-3","res":{"statusCode":503},"msg":"request aborted - refusing to accept new requests as server is closing"}
21 |     {
22 |       method: 'GET',
23 |       headers: { 'Content-Type': 'application/json' },
24 |     },
25 |   );
26 |   expect(response.status).toEqual(200);
      ^
error: expect(received).toEqual(expected)
```

```typescript
// import { beforeEach, afterEach, expect, test } from 'bun:test';
import { beforeEach, afterEach, test } from 'node:test';
import assert from 'node:assert';

import { DEFAULT_HTTP_SERVER_FACTORY_CONFIG, HTTPServerFactory } from '../factories';
import { HTTPServer } from './http-server.js';

let httpServer: HTTPServer;

beforeEach(() => {
  httpServer = HTTPServerFactory.create({ http: { port: DEFAULT_HTTP_SERVER_FACTORY_CONFIG.port } });
});
afterEach(() => {
  httpServer.close();
});

test('returns a /ping with the current unix time on the server', async (t) => {
  const lr = await httpServer.listen();
  const rr = await httpServer.ready()

  const response = await fetch(
    `http://localhost:${DEFAULT_HTTP_SERVER_FACTORY_CONFIG.port}/probes/ping`,
    {
      method: 'GET',
      headers: { 'Content-Type': 'application/json' },
    },
  );
  assert.equal(response.status, 200);
  const result = await response.json();
  assert.equal(result.pong > 0, true);
});
```

**Comment by i-void** [comment]
My test's with GraphQL yoga's test executor also  have some weird behavior. It works with vitest pretty well.
```
describe('yoga', () => {
  it('should work', async () => {
    const query = graphql(/* GraphQL */ `
      query Hello($name: String!) {
        hello(name: $name)
      }
    `)
    const result = await executor({
      document: query,
      variables: {
        name: 'Osman'
      }
    })
    console.log('result', result)
    if (!("data" in result)) throw new Error('No data')
    expect(result.data?.hello).toBe('Hello Osman! Welcome')
  })
})
```
```
result {
  errors: [
    1 | export default "native";
    ^
GraphQLError: Failed to construct 'Request': Invalid URL "/graphql"
 path: "undefined"
      at Request (native:1:1)
      at fetchFn (/home/cm/Programming/CozyFW/sampleProject/node_modules/@whatwg-node/server/esm/createServerAdapter.js:212:64)
      at new ValueOrPromise (/home/cm/Programming/CozyFW/sampleProject/node_modules/value-or-promise/build/main/ValueOrPromise.js:14:21)
      at then (/home/cm/Programming/CozyFW/sampleProject/node_modules/value-or-promise/build/main/ValueOrPromise.js:39:23)
      at /home/cm/Programming/CozyFW/sampleProject/node_modules/@graphql-tools/executor-http/esm/index.js:81:26
      at new ValueOrPromise (/home/cm/Programming/CozyFW/sampleProject/node_modules/value-or-promise/build/main/ValueOrPromise.js:14:21)
      at executor (/home/cm/Programming/CozyFW/sampleProject/node_modules/@graphql-tools/executor-http/esm/index.js:51:20)
      at /home/cm/Programming/CozyFW/sampleProject/src/app/modules/hello/test/yoga.spec.ts:20:26
      at /home/cm/Programming/CozyFW/sampleProject/src/app/modules/hello/test/yoga.spec.ts:14:21

  ],
}
```

**Comment by E-ricus** [comment]
I just got a similar error with the same stack trace as @i-void trying to test a yoga server. Using bun version 1.1.33 on macos
```
Result  {
  errors: [
    218 |   Object.defineProperty(globalThis, "Request", {
219 |     enumerable: true,
220 |     writable: true,
221 |     value: new Proxy(Request, {
222 |       construct(target, args, newTarget) {
223 |         const request = Reflect.construct(target, args, newTarget);
      ^
GraphQLError: Failed to construct 'Request': Invalid URL "/graphql"
```

Has anyone figured a workaround?
