### ISSUE TITLE
documentation updates for react section to easily integrate with existing CRA

### ISSUE THREAD

**Issue by kamikaz1k** [oven-sh/bun#71]
(I can put up a PR if you're welcoming PRs)

Requires `react` version >17 because of the `react/jsx-dev-runtime` dependency for the compiler

if working with an existing CRA, you need to update `./public/index.html` to:
1. remove `%PUBLIC_URL%`
2. add a `<script src="/src/index.js" async type="module"></script>` to the document `body`.

I don't know if you have intentions to include support within `bun` to handle this out of the box.
I'd imagine if bun is going to be only for development workflows, then you wouldn't want to mess with the `index.html` file.

**Comment by Jarred-Sumner** [comment]
This is a good point. The docs for this need to be better and honestly, it needs to Just Work instead of having to edit HTML files by hand.

**Comment by birkskyum** [comment]
Running create react app with Bun gives a modal with the following content:

```sh
Compiled with problems:

ERROR
[eslint] Cannot read config file: /Users/admin/repos/cra-test/my-app/node_modules/eslint-config-react-app/base.js
Error: stacks.shift is not a function. (In 'stacks.shift()', 'stacks.shift' is undefined)
Referenced from: BaseConfig

ERROR
  Error: Child compilation failed:
  [eslint] Cannot read config file: /Users/admin/repos/cra-test/my-app/node_modules/eslint-config-react-app/base.js
  Error: stacks.shift is not a function. (In 'stacks.shift()', 'stacks.shift' is undefined)
  Referenced from: BaseConfig
  ```

**Comment by birkskyum** [comment]
This ticket could very well be a tracking issue like "Support Create React App (CRA)"

**Comment by birkskyum** [comment]
It now prints:

```zig
➜ bun --bun run start
$ react-scripts start


error: Cannot find module "/Users/admin/repos/cra-test/my-app/build/package.json" from "/Users/admin/repos/cra-test/my-app/node_modules/react-scripts/config/paths.js"
error: script "start" exited with code 1 (SIGHUP)
```

**Comment by birkskyum** [comment]
Latest canary can start the dev server! 🎉

Still I get this in the console:

- `bun --bun run start`

```zig
Compiled successfully!

You can now view my-app in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://192.168.0.115:3000

Note that the development build is not optimized.
To create a production build, use npm run build.

webpack compiled successfully
71 | 
72 |             return;
73 |           }
74 | 
75 |           client.isAlive = false;
76 |           client.ping(() => {});
              ^
TypeError: client.ping is not a function. (In 'client.ping(() => {
          })', 'client.ping' is undefined)
      at /Users/admin/repos/cra-test/my-app/node_modules/webpack-dev-server/lib/servers/WebsocketServer.js:76:10
      at forEach (:1:20)
      at /Users/admin/repos/cra-test/my-app/node_modules/webpack-dev-server/lib/servers/WebsocketServer.js:64:6
65 |         /**
66 |          * @param {ClientConnection} client
67 |          */
68 |         (client) => {
69 |           if (client.isAlive === false) {
70 |             client.terminate();
```

- `bun --bun run build`

```zig
➜ bun --bun run build
error: Cannot find module "/Users/admin/repos/cra-test/my-app/build" from "bun:main"
```

- `bun --bun run test` (and pressed `a` to run all tests)

```zig

  ● Test suite failed to run

    TypeError: undefined is not an object (evaluating 'Module._extensions[".js"]')

      at addHook (node_modules/pirates/lib/index.js:90:41)
      at requireAndTranspileModule (node_modules/@jest/transform/build/ScriptTransformer.js:855:34)
      at processTicksAndRejections (:55:39)
```

**Comment by Electroid** [comment]
We revamped our [documentation](https://bun.sh/docs) since this issue was created, so going to close as outdated. For the issues discussed, these are tracked elsewhere.

* #5998
