### ISSUE TITLE
[macro] crash with large complex array

### ISSUE THREAD

**Issue by codehz** [oven-sh/bun#7116]
### What version of Bun is running?

1.0.11+f7f6233ea

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

comptime.ts
```ts
import { readdirSync } from "fs";

export function files() {
  const dirents = readdirSync("./", { withFileTypes: true });
  const arr = () => dirents.flatMap((x) => {
    if (x.isFile()) {
      return {
        name: x.name,
        contents: Bun.file(x.name),
      };
    }
    return [];
  });
  return [
    ...arr(),
    ...arr(),
    ...arr(),
    ...arr(),
    ...arr(),
    ...arr(),
    ...arr(),
    ...arr(),
    ...arr(),
    ...arr(),
    ...arr(),
    ...arr(),
    ...arr(),
    ...arr(),
    ...arr(),
    ...arr(),
  ];
}

console.log(files());
```
runtime.ts
```ts
import { files } from "./comptime" assert { type: "macro" }

console.log(files())
```

### What is the expected behavior?

no crash

### What do you see instead?

crash randomly

some error messages:
```
36 |   },
37 |   {
38 |     name: "comptime.ts",
39 |     contents
40 | 
41 |   },
  {
    name: "runtime.ts",
                ^
ReferenceError: Can't find variable: contents
      at ###/bun-bug/empty/runtime.ts:3:12
```

```
fish: Job 1, 'bun run runtime.ts' terminated by signal SIGSEGV (Address boundary error)
```

```
SyntaxError: Unexpected token ','
      at ###/bun-bug/empty/runtime.ts:1:0
```

```
Expected property key

uh-oh: Expected property key
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.0.11 (f7f6233e) macOS Silicon 23.1.0
RunCommand: macros 
Elapsed: 18ms | User: 19ms | Sys: 8ms
RSS: 29.97MB | Peak: 29.97MB | Commit: 33.55MB | Faults: 0
----- bun meta -----

0   0x105cc7e44
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???
10  ???
11  ???
12  ???
13  ???
14  ???
15  ???
16  ???
17  ???
18  ???

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

thread 657422 panic: Expected property key
fish: Job 1, 'bun run runtime.ts' terminated by signal SIGABRT (Abort)
```

### Additional information

if it is not crash, just append more files, I got pretty consistent crash when there is more than 10 files (even without manually repeating)

**Comment by Jarred-Sumner** [comment]
Can confirm this is still ongoing
