### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by tdortman** [oven-sh/bun#7121]
### What version of Bun is running?

1.0.11+f7f6233ea

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

When I bundle [my project](https://github.com/TiltedToast/hifumi) using bun something seems to go wrong when it's trying to execute it, not sure. Below is a little part of the bundle, that shows that the `client` variable it's complaining about should be available. [Here](https://github.com/TiltedToast/hifumi/blob/3f30dd0bd115424c9172a185fc1ab6e5b20c74a5/src/app.ts) is also the .ts file which the snippet is generated from.

The command used to generate this is `bun build src/app.ts --target=bun --outfile hifumi.js`, the same thing also happens when minifying and/or compiling the code.

```js
import {existsSync as existsSync2, rmSync as rmSync2} from "fs";
var import_discord8, config19, import_strftime3, startTime, client, prefixMap, statusArr, botIsLoading, stopSignals;
var init_app = __esm(() => {
  init_dedent();
  import_discord8 = __toESM(require_src(), 1);
  config19 = __toESM(require_config(), 1);
  import_strftime3 = __toESM(require_strftime(), 1);
  init_loops();
  init_config4();
  init_db2();
  init_schema2();
  init_interactions();
  init_messages();
  init_utils4();
  startTime = Date.now();
  client = new import_discord8.Client({
    intents: [
      import_discord8.GatewayIntentBits.Guilds,
      import_discord8.GatewayIntentBits.GuildMembers,
      import_discord8.GatewayIntentBits.GuildEmojisAndStickers,
      import_discord8.GatewayIntentBits.GuildMessages,
      import_discord8.GatewayIntentBits.GuildMessageReactions,
      import_discord8.GatewayIntentBits.MessageContent,
      import_discord8.GatewayIntentBits.DirectMessages
    ],
    partials: [import_discord8.Partials.Channel]
  });
  prefixMap = new Map;
  statusArr = [];
  botIsLoading = true;
  client.once("ready", async () => {
    const time3 = import_strftime3.default("%d/%m/%Y %H:%M:%S");
    const doneLoadingTime = Date.now();
    if (!client.user)
      return;
    console.log(`Started up in ${(doneLoadingTime - startTime) / 1000} seconds on ${time3}`);
    console.log("Logged in as:");
    console.log(client.user.username);
    console.log(client.user.id);
    console.log("------------------");
    statusArr = await db4.select().from(statuses);
    if (statusArr.length)
      startStatusLoop(client).catch(console.error);
    avoidDbSleeping().catch(console.error);
    for (const prefixDoc of await db4.select().from(prefixes)) {
      prefixMap.set(prefixDoc.serverId, prefixDoc.prefix);
    }
    botIsLoading = false;
    const logChannel = client.channels.cache.get(LOG_CHANNEL);
    if (isDev())
      return;
    if (existsSync2("./temp/update.txt"))
      return rmSync2("./temp/update.txt");
    await logChannel.send(dedent_default`
        Logged in as:
        ${client.user.username}
        Time: ${time3}
        --------------------------
        `);
  });
  client.on("messageCreate", handleMessage);
  client.on("interactionCreate", handleInteraction);
  process.on("unhandledRejection", console.error);
  process.on("uncaughtException", console.error);
  stopSignals = ["SIGTERM", "SIGINT"];
  if (process.platform === "win32") {
    stopSignals.push("SIGKILL");
  }
  stopSignals.forEach((signal) => {
    process.on(signal, async () => {
      await client.destroy();
      console.log("Closed Discord connection");
      process.exit(0);
    });
  });
  await client.login("");
});
init_app();
  ```

### What is the expected behavior?

Bun should correctly recognise `client` as a valid identifier.

### What do you see instead?

```console
SyntaxError: Unexpected identifier 'client'
      at /home/tim/projects/hifumi/hifumi.js:167763
```

**Comment by tdortman** [comment]
Did some more testing and removing the await fixes it, though a new unrelated problem promptly shows up. The code runs perfectly fine without bundling/with node so I doubt it's really the library being broken

```console
33759 |     const rawTable = new MySqlTable(name, schema, baseName);
33760 |     const builtColumns = Object.fromEntries(Object.entries(columns).map(([name2, colBuilderBase]) => {
33761 |       const colBuilder = colBuilderBase;
33762 |       const column7 = colBuilder.build(rawTable);
33763 | 
33764 |       rawTable[InlineForeignKeys2].push(...colBuilder.buildForeignKeys(column7, rawTable));
         ^
TypeError: undefined is not an object (evaluating 'rawTable[InlineForeignKeys2].push')
      at /home/tim/projects/hifumi/hifumi.js:33764:6
      at map (:1:20)
      at mysqlTableWithSchema (/home/tim/projects/hifumi/hifumi.js:33761:44)
      at /home/tim/projects/hifumi/hifumi.js:36085:14
      at /home/tim/projects/hifumi/hifumi.js:31:70
      at /home/tim/projects/hifumi/hifumi.js:36191:2
      at /home/tim/projects/hifumi/hifumi.js:31:70
      at /home/tim/projects/hifumi/hifumi.js:94178:2
      at /home/tim/projects/hifumi/hifumi.js:31:70
      at /home/tim/projects/hifumi/hifumi.js:167694:2
 ```

**Comment by Jarred-Sumner** [comment]
Fixed by @snoglobe in https://github.com/oven-sh/bun/pull/14218
