### ISSUE TITLE
`expect(...)toContain("")` handles `""` incorrectly

### ISSUE THREAD

**Issue by CharString** [oven-sh/bun#7144]
### What version of Bun is running?

1.0.11+f7f6233ea

### What platform is your computer?

Linux 6.1.0-0.deb11.11-amd64 x86_64 unknown

### What steps can reproduce the bug?

```console
$ bun add -d fast-check
```
Create `string.test.ts` with this contents

```ts
import { describe, it, expect, test } from "bun:test";
import fc from "fast-check";

describe("The empty string", () => {
  const emptyString = "";
  it("has a 0 length", () => expect(emptyString).toHaveLength(0));
  it("is found in all strings", () => {
    fc.assert(
      fc.property(fc.string(), (string: string) => {
        expect(string.indexOf(emptyString)).toBe(0);
        expect(string).toContain(emptyString);
      })
    );
  });

  describe('forms the (strings, concatenation, "") monoid', () => {
    const cat = (a: string, b: string) => a + b;

    test("concatenation is associative on string", () => {
      fc.assert(
        fc.property(
          fc.string(),
          fc.string(),
          fc.string(),
          (a: string, b: string, c: string) =>
            expect(cat(cat(a, b), c)).toBe(cat(a, cat(b, c)))
        )
      );
    });

    test('concatenation with "" is identity', () => {
      fc.assert(
        fc.property(fc.string(), (a: string) => {
          expect(cat(a, emptyString)).toBe(a);
          expect(cat(emptyString, a)).toBe(a);
        })
      );
    });
  });
}
```

### What is the expected behavior?

These tests should pass.

### What do you see instead?

```console
bun test v1.0.11 (f7f6233e)

string.test.ts:
121 |     }
122 |     return defaultReportMessageInternal(out, stringifySecond);
123 | }
124 | function buildError(errorMessage, out) {
125 |     if (!out.runConfiguration.errorWithCause) {
126 |         throw new Error(errorMessage);
                  ^
error: Property failed after 1 tests
{ seed: 2018390894, path: "0:0:0:0", endOnFailure: true }
Counterexample: ["","",""]
Shrunk 3 time(s)
Got error: Property failed by returning false

Hint: Enable verbose mode in order to have the list of all failing values encountered during the run
      at buildError (/home/chars/tmp/bun_playground/node_modules/fast-check/lib/esm/check/runner/utils/RunDetailsFormatter.js:126:14)
      at throwIfFailed (/home/chars/tmp/bun_playground/node_modules/fast-check/lib/esm/check/runner/utils/RunDetailsFormatter.js:138:10)
      at assert (/home/chars/tmp/bun_playground/node_modules/fast-check/lib/esm/check/runner/Runner.js:69:8)
      at /home/chars/tmp/bun_playground/string.test.ts:20:6
✗ The empty string > forms the (strings, concatenation, "") monoid > concatenation is associative on string [6.69ms]
✓ The empty string > forms the (strings, concatenation, "") monoid > concatenation with "" is identity [5.09ms]
✓ The empty string > has a 0 length [0.07ms]
121 |     }
122 |     return defaultReportMessageInternal(out, stringifySecond);
123 | }
124 | function buildError(errorMessage, out) {
125 |     if (!out.runConfiguration.errorWithCause) {
126 |         throw new Error(errorMessage);
                  ^
error: Property failed after 1 tests
{ seed: 773790787, path: "0:1:1", endOnFailure: true }
Counterexample: [" "]
Shrunk 2 time(s)
Got error: expect(received).toContain(expected)

Expected to contain: ""
Received: " "

    at toContain (native)
    at <anonymous> (/home/chars/tmp/bun_playground/string.test.ts:12:4)
    at run (/home/chars/tmp/bun_playground/node_modules/fast-check/lib/esm/check/property/Property.generic.js:46:37)
    at runIt (/home/chars/tmp/bun_playground/node_modules/fast-check/lib/esm/check/runner/Runner.js:18:12)
    at check (/home/chars/tmp/bun_playground/node_modules/fast-check/lib/esm/check/runner/Runner.js:61:160)
    at assert (/home/chars/tmp/bun_playground/node_modules/fast-check/lib/esm/check/runner/Runner.js:65:17)
    at <anonymous> (/home/chars/tmp/bun_playground/string.test.ts:9:15)

Hint: Enable verbose mode in order to have the list of all failing values encountered during the run
      at buildError (/home/chars/tmp/bun_playground/node_modules/fast-check/lib/esm/check/runner/utils/RunDetailsFormatter.js:126:14)
      at throwIfFailed (/home/chars/tmp/bun_playground/node_modules/fast-check/lib/esm/check/runner/utils/RunDetailsFormatter.js:138:10)
      at assert (/home/chars/tmp/bun_playground/node_modules/fast-check/lib/esm/check/runner/Runner.js:69:8)
      at /home/chars/tmp/bun_playground/string.test.ts:8:4
✗ The empty string > is found in all strings [3.03ms]

 2 pass
 2 fail
 217 expect() calls
Ran 4 tests across 1 files. [105.00ms]
```

### Additional information

The tests pass when run with `bun x jest`

**Comment by prathamVaidya** [comment]
Can I work on this?

**Comment by SeedyROM** [comment]
If a string with only a single space should contain an empty list, wouldn't every single contain an empty list? This doesn't make sense to me. The docs for `.toContain` in jest make this a little bit clearer: https://jestjs.io/docs/expect#tocontain

**Comment by CharString** [comment]
@SeedyROM 
> .toContain can also check whether a string is a substring of another string.

```
❯ bun repl
Welcome to Bun v1.0.13
Type ".help" for more information.
[!] Please note that the REPL implementation is still experimental!
    Don't consider it to be representative of the stability or behavior of Bun overall.
> " ".indexOf("")
0
```
This issue is not about arrays.

@Jarred-Sumner The new title doesn't reflect the string-concatenation associativity test failing.

**Comment by SeedyROM** [comment]
I could be wrong but I think your fast check tests aren't actually asserting what you want.

**Comment by CharString** [comment]
> I could be wrong but I think your fast check tests aren't actually asserting what you want.

The associativity test should assert that for any tuple of strings `[a, b, c]` this should hold: `(a + b) + c === a + (b + c)`, which fails for `["", "", ""]`

The other assertion that fails should assert that any string a contains "".

Did I make a mistake? When you run this test with jest and node, they all pass.

> strings are arrays of characters when you use `toContain`.

That implementation detail should matter as much for the assertion as whether bun uses the heap or the stack to compute the result.
