### ISSUE TITLE
`next dev` does not work if `next` is installed globally using bun

### ISSUE THREAD

**Issue by l4zy0n3** [oven-sh/bun#718]
### Version

0.1.4

### Platform

Linux d00m 5.18.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 12 Jul 2022 15:40:51 +0000 x86_64 GNU/Linux

### What steps will reproduce the bug?

1. `bun i next -g`
2. `bun create next ./test-app` && `cd ./test-app`
3. `next dev`

> Issue 1
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
It looks like you're trying to use TypeScript but do not have the required package(s) installed.

Please install @types/node by running:

	yarn add --dev @types/node

If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files in your pages directory).
```
Not sure how/why it depends on `yarn`
5. `yarn add --dev @types/node`
6. `next dev`

> Issue 2
```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (/home/yt/projects/test-app/node_modules/react/cjs/react.development.js:1618:21)
    at Html (webpack-internal:///../../../../usr/lib/node_modules/next/dist/pages/_document.js:260:106)
    at renderWithHooks (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5661:16)
    at renderIndeterminateComponent (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5734:15)
    at renderElement (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5949:7)
    at renderNodeDestructiveImpl (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:6107:11)
    at renderNodeDestructive (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:6079:14)
    at finishClassComponent (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5691:3)
    at renderClassComponent (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5699:3)
    at renderElement (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5946:7)
```

### How often does it reproduce? Is there a required condition?

Everytime

### What is the expected behavior?

Server runs on http://localhost:3000

### What do you see instead?

```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (/home/yt/projects/test-app/node_modules/react/cjs/react.development.js:1618:21)
    at Html (webpack-internal:///../../../../usr/lib/node_modules/next/dist/pages/_document.js:260:106)
    at renderWithHooks (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5661:16)
    at renderIndeterminateComponent (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5734:15)
    at renderElement (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5949:7)
    at renderNodeDestructiveImpl (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:6107:11)
    at renderNodeDestructive (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:6079:14)
    at finishClassComponent (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5691:3)
    at renderClassComponent (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5699:3)
    at renderElement (/usr/lib/node_modules/next/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5946:7)
```

**Comment by xhyrom** [comment]
If you want to use nextjs with bun, use `bun dev` instead `next dev`

https://github.com/oven-sh/bun/tree/main/examples/next#cloning-the-repo

**Comment by l4zy0n3** [comment]
> If you want to use nextjs with bun, use `bun dev` instead `next dev`
> 
> https://github.com/oven-sh/bun/tree/main/examples/next#cloning-the-repo

`bun dev` works for me, but should it not be cross-compatible with `next dev`

**Comment by Electroid** [comment]
This is no longer reproducible using Bun v1.0.7 and Next.js v13.5.6. If you are still running into this bug, please feel free to re-open this issue.
