### ISSUE TITLE
devcontainer build error

### ISSUE THREAD

**Issue by jmhungdev** [oven-sh/bun#743]
### Version

`@vscode/dev-container-cli 0.241.3.`

### Platform

`Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64`

### What steps will reproduce the bug?

Following this guide: https://github.com/oven-sh/bun#vscode-dev-container-linux 
up to the step of `devcontainer build`

### What do you see instead?
```
[+] Building 213.3s (14/16)                                                     
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 35B                                           0.0s
 => [internal] load metadata for docker.io/bunbunbunbun/bun-base-with-zig  1.0s
 => [auth] bunbunbunbun/bun-base-with-zig-and-webkit:pull token for regis  0.0s
 => ERROR importing cache manifest from bun.devcontainer:latest            1.4s
 => [internal] load build context                                          0.0s
 => => transferring context: 491B                                          0.0s
 => [bun.devcontainer 1/9] FROM docker.io/bunbunbunbun/bun-base-with-zig-  0.0s
 => [auth] library/bun.devcontainer:pull token for registry-1.docker.io    0.0s
 => CACHED [bun.devcontainer 2/9] RUN apt-get -y update && update-alterna  0.0s
 => CACHED [bun.devcontainer 3/9] COPY .devcontainer/workspace.code-works  0.0s
 => CACHED [bun.devcontainer 4/9] COPY .devcontainer/zls.json /build/work  0.0s
 => CACHED [bun.devcontainer 5/9] COPY .devcontainer/limits.conf /etc/sec  0.0s
 => CACHED [bun.devcontainer 6/9] COPY .devcontainer/scripts/ /scripts/    0.0s
 => CACHED [bun.devcontainer 7/9] COPY .devcontainer/scripts/getting-star  0.0s
 => [bun.devcontainer 8/9] RUN mkdir -p /home/ubuntu/.bun /home/ubuntu/  210.7s
```

```
#13 232.1 error: the following build command failed with exit code 9:
#13 232.1 /home/ubuntu/zls/zig-cache/o/7f1cfb4bad3d0bdd8da0f89db0bd1c8f/build /build/zig/zig /home/ubuntu/zls /home/ubuntu/zls/zig-cache /root/.cache/zig -Drelease-fast
------
[2022-07-16T07:26:47.435Z] error: failed to solve: executor failed running [/bin/sh -c mkdir -p /home/ubuntu/.bun /home/ubuntu/.config $GITHUB_WORKSPACE/bun &&     bash /scripts/common-debian.sh &&     bash /scripts/github.sh &&     bash /scripts/nice.sh &&     bash /scripts/zig-env.sh]: exit code: 1
[2022-07-16T07:26:47.460Z] Stop (234906 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /Users/jimmyhung/bun/Dockerfile -t vsc-bun-cdeb2e108ae571519b571d93b83fc08c --target bun.devcontainer --cache-from bun.devcontainer:latest /Users/jimmyhung/bun
[2022-07-16T07:26:47.461Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /Users/jimmyhung/bun/Dockerfile -t vsc-bun-cdeb2e108ae571519b571d93b83fc08c --target bun.devcontainer --cache-from bun.devcontainer:latest /Users/jimmyhung/bun
[2022-07-16T07:26:47.461Z]     at GR (/Users/jimmyhung/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:240:1436)
[2022-07-16T07:26:47.461Z]     at runMicrotasks (<anonymous>)
[2022-07-16T07:26:47.461Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-07-16T07:26:47.461Z]     at async Hu (/Users/jimmyhung/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:239:2796)
[2022-07-16T07:26:47.461Z]     at async tb (/Users/jimmyhung/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:239:1779)
[2022-07-16T07:26:47.461Z]     at async QR (/Users/jimmyhung/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:2006)
[2022-07-16T07:26:47.461Z]     at async cb (/Users/jimmyhung/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:3110)
[2022-07-16T07:26:47.461Z]     at async i_ (/Users/jimmyhung/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:13194)
[2022-07-16T07:26:47.461Z]     at async n_ (/Users/jimmyhung/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:12950)
[2022-07-16T07:26:47.466Z] Stop (236071 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/jimmyhung/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/jimmyhung/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/jimmyhung/bun --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/jimmyhung/bun --log-level debug --log-format json --config /Users/jimmyhung/bun/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-07-16T07:26:47.466Z] Exit code 1
[2022-07-16T07:26:47.469Z] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/jimmyhung/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/jimmyhung/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/jimmyhung/bun --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/jimmyhung/bun --log-level debug --log-format json --config /Users/jimmyhung/bun/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-07-16T07:26:47.470Z] Exit code 1
```

**Comment by ethanburrell** [comment]
I have the same issue. To repro I followed the steps in `README.md` under Developing bun.

**Comment by ethanburrell** [comment]
What version of `devcontainer` are you on? I'm on `0.241.3`

**Comment by shanejohnpaul** [comment]
Having same issue on `0.241.3` devcontainer.

**Comment by jmhungdev** [comment]
I am using `0.241.3`, updated the issue.

**Comment by zhuzilin** [comment]
The last step needs around 4GB of memory, while the default memory limit of docker on mac is 2GB. So maybe the solution is to manually adjust the docker's memory limit.

**Comment by Jarred-Sumner** [comment]
We no longer use/recommend the dev container
