### ISSUE TITLE
Not able to launch Chromium browser using Puppeteer in Docker container due to child_process_1 operation not permitted

### ISSUE THREAD

**Issue by JohnnyRacer** [oven-sh/bun#7461]
### What version of Bun is running?

1.0.15+b3bdf22eb

### What platform is your computer?

Linux 5.15.0-88-generic x86_64

### What steps can reproduce the bug?

Create a Docker container with the `oven/bun:latest` that uses `Puppeteer`, and call `launchBrowserInstance()` to launch Chromium.  Using the latest node image the browser instance launches just fine in the container.

### What is the expected behavior?

The browser should launch without errors.

### What do you see instead?

This error message instead of the browser launching.

```js

102 |         debugLaunch(`Launching ${this.#executablePath} ${this.#args.join(' ')}`, {
103 |             detached: opts.detached,
104 |             env: opts.env,
105 |             stdio,
106 |         });
107 |         this.#browserProcess = child_process_1.default.spawn(this.#executablePath, this.#args, {
                                     ^
EPERM: Operation not permitted
 syscall: "open"
   errno: -1

      at spawn (node:child_process:610:15)
      at node:child_process:2:41
      at new Process (/code/node_modules/@puppeteer/browsers/lib/cjs/launch.js:107:32)
      at launch (/code/node_modules/@puppeteer/browsers/lib/cjs/launch.js:60:12)
      at /code/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:86:36
      at processTicksAndRejections (:61:77)
```

**Comment by RiskyMH** [comment]
I'm having a really hard time reproducing this issue, and others seem to say its fixed https://github.com/oven-sh/bun/issues/4894#issuecomment-2033557544

We've invested a ton of time into making Bun more reliable over the last year. If you're still running into this issue, please let me know and I'll re-open this
