### ISSUE TITLE
@google-cloud/secret-manager works on node.js but failed on bun

### ISSUE THREAD

**Issue by Akagi201** [oven-sh/bun#7584]
### What version of Bun is running?

1.0.16

### What platform is your computer?

Darwin 23.1.0 arm64 arm and docker oven/bun:1-slim

### What steps can reproduce the bug?

```
import { SecretManagerServiceClient } from "@google-cloud/secret-manager";

process.env.GOOGLE_APPLICATION_CREDENTIALS = "";
process.env.PROJECT_ID="";
process.env.GCP_SECRET_NAME="";

async function getOperatorPrivateKey() {
	const client = new SecretManagerServiceClient();
	const projectId = process.env.PROJECT_ID || "";
	const secretName = process.env.GCP_SECRET_NAME || "";
	const secretKey = `projects/${projectId}/secrets/${secretName}`;
	console.info(`secretKey: ${secretKey}`);
	try {
		const [accessResponse] = await client.accessSecretVersion({
			name: `${secretKey}/versions/latest`,
		});// this line of code will block on bun
		console.info(`accessResponse: ${accessResponse}`);
		const secret = accessResponse?.payload?.data?.toString();
		console.info(`secret: ${secret}`);
		return secret ?? "";
	} catch (err) {
		console.error(`error: ${err}`);
		return "";
	}
}

await getOperatorPrivateKey();
```

### What is the expected behavior?

run success and print the secret

### What do you see instead?

The program got stuck and finally panics
```sh
29 | const CALL_INVOCATION_TRANSFORMER_SYMBOL = Symbol();
30 | function isFunction(arg) {
31 |     return typeof arg === 'function';
32 | }
33 | function getErrorStackString(error) {
34 |     return error.stack.split('\n').slice(1).join('\n');
                ^
TypeError: undefined is not an object (evaluating 'error.stack.split')
      at getErrorStackString (/Users/akagi201/tmp/test_bun/node_modules/@grpc/grpc-js/build/src/client.js:34:12)
      at onReceiveStatus (/Users/akagi201/tmp/test_bun/node_modules/@grpc/grpc-js/build/src/client.js:191:41)
      at onReceiveStatus (/Users/akagi201/tmp/test_bun/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:138)
      at onReceiveStatus (/Users/akagi201/tmp/test_bun/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:178)
      at /Users/akagi201/tmp/test_bun/node_modules/@grpc/grpc-js/build/src/resolving-call.js:99:75
      at processTicksAndRejections (:61:77)
```

**Comment by Hanaasagi** [comment]
Related to https://github.com/oven-sh/bun/issues/4746

**Comment by seo-rii** [comment]
Related to https://github.com/oven-sh/bun/issues/7630

**Comment by cirospaciari** [comment]
Cant reproduce this anymore in the latest canary please reopen if is still happening
