### ISSUE TITLE
Bun i freezes and/or is much slower than npm i, and errors on `re2`

### ISSUE THREAD

**Issue by brianmhunt** [oven-sh/bun#7597]
### What version of Bun is running?

1.0.17

### What platform is your computer?

Codespace (Linux 6.2.0-1016-azure x86_64 unknown)

### What steps can reproduce the bug?

Running `bun i` with package.json like this (and probably some subset of this) on Linux / Github Codespace.

```json
{
  "name": "bun-test",
  "devDependencies": {
    "@firebase/testing": "^0.20.11",
    "@sentry/browser": "^7.64.0",
    "@types/big.js": "^6.1.6",
    "@types/docusign-esign": "^5.19.0",
    "@types/file-saver": "^2.0.5",
    "@types/jest": "^29.5.1",
    "@types/jss": "^10.0.0",
    "@types/knockout": "^3.4.72",
    "@types/webappsec-credential-management": "^0.6.4",
    "@typescript-eslint/eslint-plugin": "^5.59.6",
    "@typescript-eslint/parser": "^5.59.6",
    "currency-symbol-map": "^5.1.0",
    "esbuild": "^0.17.19",
    "eslint": "^8.40.0",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-react": "^7.32.2",
    "firebase-tools": "^12.6",
    "full-icu": "^1.5.0",
    "jest": "^29.5.0",
    "klaw-sync": "^6.0.0",
    "sinon": "^15.0.4",
    "typescript": "^5.0.4",
    "xunit-viewer": "^10.3.0"
  },
  "dependencies": {
    "@sentry/integrations": "^7.64.0",
    "@stripe/stripe-js": "^1.53.0",
    "@tko/build.reference": "^4.0.0-beta1.5",
    "@types/lodash": "^4.14.194",
    "@types/wicg-file-system-access": "^2020.9.6",
    "big-integer": "^1.6.51",
    "big.js": "^6.2.1",
    "bignumber.js": "^9.1.1",
    "cbor-x": "^1.5.3",
    "chart.js": "^4.3.0",
    "cors": "^2.8.5",
    "dagre": "^0.8.5",
    "date-fns": "^2.30",
    "eslint-plugin-promise": "^6.1.1",
    "express": "^4.18.2",
    "fast-json-patch": "^3.1.1",
    "fast-json-stable-stringify": "^2.1.0",
    "fflate": "^0.7.4",
    "file-saver": "^2.0.5",
    "firebase": "^10.5.0",
    "firebase-admin": "^11.11.0",
    "firebase-functions": "^4.4.1",
    "html-to-image": "^1.11.11",
    "idb": "^7.1.1",
    "jest-environment-jsdom": "^29.5.0",
    "jest-esbuild": "^0.2.9",
    "jest-extended": "^3.2.4",
    "jss": "^10.10.0",
    "jss-preset-default": "^10.10.0",
    "launchdarkly-js-client-sdk": "^3.1.3",
    "lodash": "^4.17.21",
    "openai": "^4.17.4",
    "pspdfkit": "^2023.4.5",
    "turndown": "^7.1.2"
  },
}
```

### What is the expected behavior?

To be as fast as or faster than `npm`.  Output is:

```
$ rm -rf node_modules; time npm i 
...
real    0m22.088s
user    0m25.887s
sys     0m21.331s
```

### What do you see instead?

Output from `bun` is 3x slower and errors:

```
$ rm -rf node_modules; time bun i 
...
bun install v1.0.17 (5e60861c)
  ⚙️  protobufjs [14/15] No github repository was identified.
Building locally ...

> re2@1.17.7 rebuild
> node-gyp rebuild
...
gyp ERR! System Linux 6.2.0-1016-azure
gyp ERR! command "/usr/local/share/nvm/versions/node/v20.10.0/bin/node" "/workspaces/MinuteBox/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /workspaces/MinuteBox/node_modules/re2
gyp ERR! node -v v20.10.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok 
error: script "rebuild" exited with code 1 (SIGHUP)

error: install script from "re2" exited with code 1 (SIGHUP)

real    1m2.479s
user    0m3.370s
sys     0m13.258s
```

### Additional information

1. Unclear if node-gyp was already compiled by `npm`, which would significantly affect the performance.
1. subsequent runs of `bun i` are very fast (0.16s)
1. Install fails in any case b/c of #7594

**Comment by Jarred-Sumner** [comment]
What does the perf look like without postinstall scripts run? I wonder if this is due to synchronous I/O on a networked filesystem

**Comment by brianmhunt** [comment]
@Jarred-Sumner How do I run it without the postintall scripts?

It _feels_ like concurrency I/O contention.

**Comment by brianmhunt** [comment]
Dropping the concurrency to `2` yields a significantly better time:

```
$ rm -rf node_modules/; time bun i --concurrent-scripts 2
...
gyp ERR! not ok 
error: script "rebuild" exited with code 1 (SIGHUP)

error: install script from "re2" exited with code 1 (SIGHUP)

real    0m13.811s
user    0m3.206s
sys     0m11.396s
```

which is consistent with the sense that it's contention.

Slightly slower with concurrency of 4 / 7

```
$ rm -rf node_modules/; time bun i --concurrent-scripts 7
...
real    0m14.489s
user    0m3.646s
sys     0m11.733s

$ rm -rf node_modules/; time bun i --concurrent-scripts 4
...
real    0m14.157s
user    0m3.341s
sys     0m11.857s
```

Just for completeness:

```
$ cat /proc/cpuinfo | tail -n 28
processor       : 7
vendor_id       : AuthenticAMD
cpu family      : 25
model           : 1
model name      : AMD EPYC 7763 64-Core Processor
stepping        : 1
microcode       : 0xffffffff
cpu MHz         : 2445.427
cache size      : 512 KB
physical id     : 0
siblings        : 8
core id         : 3
cpu cores       : 4
apicid          : 7
initial apicid  : 7
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext invpcid_single vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr rdpru arat npt nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload umip vaes vpclmulqdq rdpid fsrm
bugs            : sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass srso
bogomips        : 4890.85
TLB size        : 2560 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management:
```

**Comment by brianmhunt** [comment]
Well good and bad news.  The bad news is that the concurrency was a red-herring, since re-running `bun i` is now roughly the same speed as with the concurrency:

```sh
$ rm -rf node_modules/; time bun i
bun install v1.0.17 (5e60861c)
  ⚙️  protobufjs [9/15] No github repository was identified.
Building locally ...

> re2@1.17.7 rebuild
> node-gyp rebuild
...
error: script "rebuild" exited with code 1 (SIGHUP)

error: install script from "re2" exited with code 1 (SIGHUP)

real    0m14.062s
user    0m3.350s
sys     0m11.726s
```

And clearing `~/.bun/` doesn't seem to have much impact.

```sh
$ rm -rf ~/.bun/; rm -rf node_modules/; time bun i --concurrent-scripts 3
...
error: install script from "re2" exited with code 1 (SIGHUP)

real    0m15.802s
user    0m6.203s
sys     0m18.198s

$ rm -rf ~/.bun/; rm -rf node_modules/; time bun i 
...
real    0m15.658s
user    0m6.410s
sys     0m17.762s
```

... leaving me wondering how to reproduce this now.

**Comment by brianmhunt** [comment]
I can reproduce in a brand new Codespace, it hangs here:

<img width="607" alt="CleanShot 2023-12-12 at 09 04 23@2x" src="https://github.com/oven-sh/bun/assets/135528/ada8b7f8-c164-4567-ac68-9cbbc348bb51">

Unclear what it's doing, but it appears to be bun itself, looking at `htop`:

<img width="1074" alt="CleanShot 2023-12-12 at 09 05 41@2x" src="https://github.com/oven-sh/bun/assets/135528/65ec3d9f-7bbd-4eb0-a967-0d6f9b384430">

... and there's not a lot running, per `ps ax`

<img width="1065" alt="CleanShot 2023-12-12 at 09 06 59@2x" src="https://github.com/oven-sh/bun/assets/135528/6d784359-7247-44c9-9270-52a8b2f99c1a">

Here's what iostat shows (loop3 is the home):

<img width="899" alt="CleanShot 2023-12-12 at 09 09 54@2x" src="https://github.com/oven-sh/bun/assets/135528/3a49b2f4-59a8-472c-b8d6-b6ed1cde60a4">

<img width="914" alt="CleanShot 2023-12-12 at 09 10 34@2x" src="https://github.com/oven-sh/bun/assets/135528/dff93673-0736-450a-8a37-542f953e5e5c">

Looking at `top` bun is:

<img width="770" alt="CleanShot 2023-12-12 at 09 11 28@2x" src="https://github.com/oven-sh/bun/assets/135528/c3ceb315-eb11-48bc-8274-84bdddc38719">

The outcome here is considerably worse than being slow -- it's entirely hung here for 10 min:

<img width="685" alt="CleanShot 2023-12-12 at 09 13 55@2x" src="https://github.com/oven-sh/bun/assets/135528/25e9cd10-84b0-423c-81c0-1dca074ff405">

... then re-running it:

```
@brianmhunt ➜ /workspaces/MinuteBox (main) $ time bun i

real    0m0.063s
user    0m0.010s
sys     0m0.044s
```

So something's amiss here. In a local context would could interrupt and re-run (presuming postinstalls ran).  This would be a problem in CI workflows.

**Comment by anthonykrivonos** [comment]
Seconding this issue. Changed nothing in my `Dockerfile` since our last deploy:
```
FROM --platform=linux/amd64 node:20-bullseye-slim AS base
WORKDIR /app

COPY package.json bun.lockb*

RUN npm install -g bun
RUN bun install

...

CMD bun start
```
and getting the following error during deployment:
```
#9 4.451 gyp ERR! find Python **********************************************************

#9 4.451 gyp ERR! find Python

#9 4.451 gyp ERR! configure error

#9 4.451 gyp ERR! stack Error: Could not find any Python installation to use

#9 4.451 gyp ERR! stack at PythonFinder.fail (/app/node_modules/node-gyp/lib/find-python.js:306:11)

#9 4.451 gyp ERR! stack at PythonFinder.findPython (/app/node_modules/node-gyp/lib/find-python.js:164:17)

#9 4.451 gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

#9 4.451 gyp ERR! stack at async configure (/app/node_modules/node-gyp/lib/configure.js:23:18)

#9 4.451 gyp ERR! stack at async run (/app/node_modules/node-gyp/bin/node-gyp.js:81:18)

#9 4.451 gyp ERR! System Linux 5.10.0-25-cloud-amd64

#9 4.451 gyp ERR! command "/usr/local/bin/node" "/app/node_modules/.bin/node-gyp" "rebuild"

#9 4.451 gyp ERR! cwd /app/node_modules/re2

#9 4.451 gyp ERR! node -v v20.10.0

#9 4.451 gyp ERR! node-gyp -v v10.0.1

#9 4.451 gyp ERR! not ok

#9 4.451 error: script "rebuild" exited with code 1 (SIGHUP)

#9 4.451

#9 4.451 error: install script from "re2" exited with code 1 (SIGHUP)
```

Changing the Bun installation line to `RUN npm install -g bun@1.0.16` has been my team's quick fix. Would appreciate some assistance from the Bun team.

**Comment by dylan-conway** [comment]
The slow down is happening because environment variables `npm_package_name/version/github` are not set for bun run, so the `re2` script is rebuilding the entire package rather than grabbing a prebuilt from github. We will have a fix for this soon

**Comment by brianmhunt** [comment]
Thanks for the update @dylan-conway and all your hard work on this.

Noting that the prebuild wouldn't _explain_ the lockup, though it may certainly be related.

**Comment by Jarred-Sumner** [comment]
This branch should fix the IO slowness, but not the re2 issue specifically #7628

**Comment by brianmhunt** [comment]
@dylan-conway @Jarred-Sumner Just a heads up that re2 still erroring on 1.0.18 in vanilla Codespaces.

Seeing some consistent improvement in I/O perf.

Using re2 pre-build may solve this error, and you may already know about this issue, but flagging just in case you expected #7628 to solve this.

```
@brianmhunt ➜ /workspaces/MinuteBox (main) $ bun -v 
1.0.18

@brianmhunt ➜ /workspaces/MinuteBox (main) $ time bun i 
bun install v1.0.18 (36c316a2)
[12.38ms] migrated lockfile from package-lock.json
  ⚙️  full-icu [12/12] No github repository was identified.
Building locally ...

> re2@1.17.7 rebuild
> node-gyp rebuild

make: Entering directory '/workspaces/MinuteBox/node_modules/re2/build'
  CXX(target) Release/obj.target/re2/lib/addon.o
make: Leaving directory '/workspaces/MinuteBox/node_modules/re2/build'
make: Entering directory '/workspaces/MinuteBox/node_modules/re2/build'
  CXX(target) Release/obj.target/re2/lib/addon.o
make: Leaving directory '/workspaces/MinuteBox/node_modules/re2/build'

gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@20.10.0 | linux | x64
gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/workspaces/MinuteBox/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/workspaces/MinuteBox/node_modules/re2/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/workspaces/MinuteBox/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/vscode/.cache/node-gyp/20.10.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/vscode/.cache/node-gyp/20.10.0',
gyp info spawn args   '-Dnode_gyp_dir=/workspaces/MinuteBox/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/vscode/.cache/node-gyp/20.10.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/workspaces/MinuteBox/node_modules/re2',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
In file included from ../../nan/nan.h:180,
                 from ../lib/./wrapped_re2.h:4,
                 from ../lib/addon.cc:1:
../../nan/nan_callbacks.h:55:23: error: ‘AccessorSignature’ is not a member of ‘v8’
   55 | typedef v8::Local<v8::AccessorSignature> Sig;
      |                       ^~~~~~~~~~~~~~~~~
../../nan/nan_callbacks.h:55:40: error: template argument 1 is invalid
   55 | typedef v8::Local<v8::AccessorSignature> Sig;
      |                                        ^
In file included from ../lib/./wrapped_re2.h:4,
                 from ../lib/addon.cc:1:
../../nan/nan.h: In function ‘bool Nan::IdleNotification(int)’:
../../nan/nan.h:687:32: warning: ‘bool v8::Isolate::IdleNotificationDeadline(double)’ is deprecated: Use MemoryPressureNotification() to influence the GC schedule. [-Wdeprecated-declarations]
  687 |         idle_time_in_ms * 0.001);
      |                                ^
In file included from /home/vscode/.cache/node-gyp/20.10.0/include/node/v8-initialization.h:13,
                 from /home/vscode/.cache/node-gyp/20.10.0/include/node/v8.h:34,
                 from /home/vscode/.cache/node-gyp/20.10.0/include/node/node.h:73,
                 from ../../nan/nan.h:60,
                 from ../lib/./wrapped_re2.h:4,
                 from ../lib/addon.cc:1:
/home/vscode/.cache/node-gyp/20.10.0/include/node/v8-isolate.h:1293:8: note: declared here
 1293 |   bool IdleNotificationDeadline(double deadline_in_seconds);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~
make: *** [re2.target.mk:172: Release/obj.target/re2/lib/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/workspaces/MinuteBox/node_modules/node-gyp/lib/build.js:201:23)
gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Linux 6.2.0-1018-azure
gyp ERR! command "/usr/local/share/nvm/versions/node/v20.10.0/bin/node" "/workspaces/MinuteBox/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /workspaces/MinuteBox/node_modules/re2
gyp ERR! node -v v20.10.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok 
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "1".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v20.10.0
$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@20.10.0 | linux | x64
gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/workspaces/MinuteBox/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/workspaces/MinuteBox/node_modules/re2/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/workspaces/MinuteBox/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/vscode/.cache/node-gyp/20.10.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/vscode/.cache/node-gyp/20.10.0',
gyp info spawn args   '-Dnode_gyp_dir=/workspaces/MinuteBox/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/vscode/.cache/node-gyp/20.10.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/workspaces/MinuteBox/node_modules/re2',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
In file included from ../../nan/nan.h:180,
                 from ../lib/./wrapped_re2.h:4,
                 from ../lib/addon.cc:1:
../../nan/nan_callbacks.h:55:23: error: ‘AccessorSignature’ is not a member of ‘v8’
   55 | typedef v8::Local<v8::AccessorSignature> Sig;
      |                       ^~~~~~~~~~~~~~~~~
../../nan/nan_callbacks.h:55:40: error: template argument 1 is invalid
   55 | typedef v8::Local<v8::AccessorSignature> Sig;
      |                                        ^
In file included from ../lib/./wrapped_re2.h:4,
                 from ../lib/addon.cc:1:
../../nan/nan.h: In function ‘bool Nan::IdleNotification(int)’:
../../nan/nan.h:687:32: warning: ‘bool v8::Isolate::IdleNotificationDeadline(double)’ is deprecated: Use MemoryPressureNotification() to influence the GC schedule. [-Wdeprecated-declarations]
  687 |         idle_time_in_ms * 0.001);
      |                                ^
In file included from /home/vscode/.cache/node-gyp/20.10.0/include/node/v8-initialization.h:13,
                 from /home/vscode/.cache/node-gyp/20.10.0/include/node/v8.h:34,
                 from /home/vscode/.cache/node-gyp/20.10.0/include/node/node.h:73,
                 from ../../nan/nan.h:60,
                 from ../lib/./wrapped_re2.h:4,
                 from ../lib/addon.cc:1:
/home/vscode/.cache/node-gyp/20.10.0/include/node/v8-isolate.h:1293:8: note: declared here
 1293 |   bool IdleNotificationDeadline(double deadline_in_seconds);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~
make: *** [re2.target.mk:172: Release/obj.target/re2/lib/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/workspaces/MinuteBox/node_modules/node-gyp/lib/build.js:201:23)
gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Linux 6.2.0-1018-azure
gyp ERR! command "/usr/local/share/nvm/versions/node/v20.10.0/bin/node" "/workspaces/MinuteBox/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /workspaces/MinuteBox/node_modules/re2
gyp ERR! node -v v20.10.0
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok 

error: install script from "re2" exited with code 1 (SIGHUP)

real    0m13.069s
user    0m5.925s
sys     0m12.754s
```

**Comment by brianmhunt** [comment]
This is probably a dupe with #7683 and the `re2` issue is known, so it'd be ok if this were closed (i.e. I don't think any info would be lost).

**Comment by brianmhunt** [comment]
Noting that the `re2` error still occurs on bun 1.0.19.

Install seems faster now, though.  Down to 11s.

(Related: Using bun still blocked b/c of the trusted dependencies. #7594)

**Comment by brianmhunt** [comment]
## Transitive Dependencies

I believe there's some opportunity to improve the trusted dependency system, by making the trust transitive / inherited by packages.

For example:

1. I trust package "A",
2. "A" trusts "B" and "C" (with `A/package.json` having `trustedDependencies: ["B", "C"]`)
3. therefore I trust "B" and "C"

There are some obvious (and possibly non-obvious) benefits here:

1. it gives package maintainers the ability to specify trust relationships without package consumers having to know/understand the trust (i.e. change of responsibility from consumer to producer)
1. it would avoid a trusted-dependency change being necessary anytime a package relies on another with a script install (less burden on consumer)
1. bun would no longer need to hard-code the top 500 (delegation of responsibility / authority)

Arguably on the first point consumers _should_ be aware of the trust relationship, but this'll create a friction to use, so it's a policy/principle question for oven/bun.

The latter is particularly important because:

1. trusting packages by popularity may not align with the security surface a consumer of bun is concerned with (i.e. they may wish to DIY it / not assume bun as an authority on trust)
2. bun can offload the trusted dependency to another, who would need only an otherwise empty package with a "trustedDependencies: [a, b, c]"
3. others could create their own set of trusted dependencies
4. oven/bun would no longer need to maintain this list as part of the repo i.e. it could be broken out into a new, simple repo (alleviating the responsibility on oven/bun and lowering the barrier to contribution)

**Comment by notramo** [comment]
In this case, I would name it `transitiveTrustedDependencies`, and it should be an array separate to `trustedDependencies`.

**Comment by brianmhunt** [comment]
I think it's fair to say this issue no longer exists in a meaningful way, so closing.
