### ISSUE TITLE
Cannot find module node:child_process

### ISSUE THREAD

**Issue by mindplay-dk** [oven-sh/bun#7600]
### What version of Bun is running?

1.0.17

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```
bun init
bun install sharp
```

### What is the expected behavior?

Package should be installed

### What do you see instead?

```
$ bun install sharp
bun add v1.0.17 (5e60861c)
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:child_process'
Require stack:
- /home/mindplay/workspace/try-bun/node_modules/sharp/lib/libvips.js
- /home/mindplay/workspace/try-bun/node_modules/sharp/install/check.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/mindplay/workspace/try-bun/node_modules/sharp/lib/libvips.js:6:23)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/mindplay/workspace/try-bun/node_modules/sharp/lib/libvips.js',
    '/home/mindplay/workspace/try-bun/node_modules/sharp/install/check.js'
  ]
}

error: install script from "sharp" exited with code 1 (SIGHUP)
```

### Additional information

It looks like support for `node:child_process` was added [earlier](https://github.com/oven-sh/bun/issues/595#issuecomment-1341543945), but for some reason not working anymore?

**Comment by Jarred-Sumner** [comment]
It's running in Node.js, and probably a very old version of Node.js which predates support for the `node:` prefix (note the stacktrace referencing `"internal/"`, Bun's stacktraces do not look like that)

**Comment by mindplay-dk** [comment]
how is it running in Node.js?? as you can see, I wrote `bun install sharp`. 🤔

**Comment by Electroid** [comment]
This is because `sharp` has post-install scripts that are specifically calling out to Node.js. We're thinking of ways to make this better/avoid this, but haven't landed on a solution yet.

**Comment by mindplay-dk** [comment]
> This is because `sharp` has post-install scripts that are specifically calling out to Node.js.

ah, I see, you mean [this](https://github.com/lovell/sharp/blob/cd5cf7ce2d7294faeacd0f9536e874bbea950ee7/package.json#L94), which runs [this](https://github.com/lovell/sharp/blob/main/install/check.js) at install, yes?

> We're thinking of ways to make this better/avoid this, but haven't landed on a solution yet.

so like, a `node` compatible "proxy" or "shim" of some sort?

I'm sure that's a lot of work.

I'm not sure how much of `node` commands you'd need to support though - looks like just a basic launcher would do it here?

Presumably you'd run into similar problems with scripts that run aggregate `npm` scripts?

This is the price of forking the ecosystem, I suppose... sort of off-topic, but did it ever occur to you to just keep the command names and CLI syntax as close to compatible with existing tools as possible? I mean, if you want to leverage the existing package ecosystem, that would be the most direct way to do it, wouldn't it?
