### ISSUE TITLE
Bun process exits silently when downloading GCS files with @google-cloud/storage

### ISSUE THREAD

**Issue by Scalahansolo** [oven-sh/bun#7747]
### What version of Bun is running?

1.0.18

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

As pointed out in this thread. (https://github.com/oven-sh/bun/issues/6200#issuecomment-1857250127)

This can reproed with a setup similar to the code in https://github.com/oven-sh/bun/issues/6200#issuecomment-1858461497. 

Bun will list files in GCS just fine. Downloading files however does not work at all. Whenever I've attempted to download files in various ways using this npm library, the process just exits with code 0. I've also tried to use bun inspect with no success. In ever setup I've tried the process just exits with 0.

### What is the expected behavior?

I'd expect to be able to use Bun along with @google-cloud/storage to download files from GCS

### Additional information

If it were possible to setup a shareable repro, I would, but I think since this involves using a GCP json key it's not easy to provide a super simple repro. I could maybe put together a repo with steps for setting up a GCS account that shows this issue?

**Comment by Scalahansolo** [comment]
To just provide some proof of what I am seeing, here some screenshots of my code and how it executes. This bun command ultimately calls the code block seen here.

![CleanShot 2023-12-19 at 14 24 06@2x](https://github.com/oven-sh/bun/assets/4317253/6f0dd678-19dc-41ce-90ea-23f6d6fbf7e7)

![CleanShot 2023-12-19 at 14 20 59@2x](https://github.com/oven-sh/bun/assets/4317253/b651d963-aa81-46b8-85ef-9c4d2d19fa39)

**Comment by gusfune** [comment]
I have a similar issue with `@google-cloud/storage`, but in my case is saving a file to a bucket.
I've managed to track down the issue to a dependency:

```
TypeError: null is not an object
      at node:1:8827
      at parseKeys (node:1:8847)
      at sign (node:1:8983)
      at node:1:9127
      at sign (/usr/src/app/node_modules/jwa/index.js:152:45)
      at jwsSign (/usr/src/app/node_modules/jws/lib/sign-stream.js:32:24)
      at /usr/src/app/node_modules/gtoken/build/src/index.js:224:31
      at requestToken (/usr/src/app/node_modules/gtoken/build/src/index.js:212:26)
      at getTokenAsyncInner (/usr/src/app/node_modules/gtoken/build/src/index.js:143:30)
      at /usr/src/app/node_modules/gtoken/build/src/index.js:137:55
```

**Comment by kugesh-Rajasekaran** [comment]
Same here. Another thread which has some info: https://github.com/oven-sh/bun/issues/6200.

**Comment by deepso7** [comment]
```
⋊> ~/d/h/upload_test bun run index.ts                                                                                                                                                             15:42:06
147 |     checkIsPrivateKey(privateKey);
148 |     thing = normalizeInput(thing);
149 |     // Even though we are specifying "RSA" here, this works with ECDSA
150 |     // keys as well.
151 |     var signer = crypto.createSign('RSA-SHA' + bits);
152 |     var sig = (signer.update(thing), signer.sign(privateKey, 'base64'));
                                                  ^
TypeError: null is not an object
      at node:crypto:8695:30
      at parseKeys (node:crypto:8715:23)
      at sign (node:crypto:8851:18)
      at node:crypto:8995:38
      at sign (/Users/deepso/dev/h/upload_test/node_modules/jwa/index.js:152:45)
      at jwsSign (/Users/deepso/dev/h/upload_test/node_modules/jws/lib/sign-stream.js:4:5)
      at /Users/deepso/dev/h/upload_test/node_modules/gtoken/build/src/index.js:235:27
      at _GoogleToken_requestToken (/Users/deepso/dev/h/upload_test/node_modules/gtoken/build/src/index.js:223:44)
      at /Users/deepso/dev/h/upload_test/node_modules/gtoken/build/src/index.js:226:35
      at _GoogleToken_getTokenAsyncInner (/Users/deepso/dev/h/upload_test/node_modules/gtoken/build/src/index.js:203:28)

Bun v1.1.24 (macOS arm64)
```

Getting similar error, trying to `const [buckets] = await client.getBuckets();`
