### ISSUE TITLE
Add class names to stack traces

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#7780]
We are missing class names in stack traces. How do we get them from the `JSC::CodeBlock`?

Bun (note the lack of `MyClass`):

```js
❯ bun much.js
      at method (/Users/jarred/Build/bcrypty/much.js:3:5)
      at /Users/jarred/Build/bcrypty/much.js:8:1
```

Node:

```js
❯ node much.js
    at MyClass.method (file:///Users/jarred/Build/bcrypty/much.js:3:13)
    at file:///Users/jarred/Build/bcrypty/much.js:8:5
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)
```

```js
   1   │ class MyClass {
   2   │   method() {
   3   │     console.trace("here");
   4   │   }
   5   │ }
   6   │
   7   │ const hey = new MyClass();
   8   │ hey.method();
```

**Comment by robobun** [comment]
Same issue as #4323: stack frames for class methods are printed as the bare function name (`at method`) instead of Node's `ReceiverClass.method` form (`at MyClass.method`), because Bun's stack trace formatting has no receiver/class name for the frame. Both repros (`new Error().stack` and `console.trace()` inside a class method) still behave identically on Bun 1.4.0, and the open PR #35694 lists #4323 and #7780 as the same underlying problem, so one fix closes both.

Duplicate of #4323

Please add a 👍 or any extra details over there so it all stays in one place. If this is actually a different problem, say so here and we'll reopen.
