### ISSUE TITLE
@apollo/client subscription connection error

### ISSUE THREAD

**Issue by tavindev** [oven-sh/bun#7802]
### What version of Bun is running?

1.0.19 / 1.0.20

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

Install dependencies: `bun install graphql-ws @apollo/client ws`

Create file:
```typescript 
import { ApolloClient, DocumentNode, InMemoryCache } from '@apollo/client/core';
import { GraphQLWsLink } from '@apollo/client/link/subscriptions';
import { createClient } from 'graphql-ws';
import WebSocket from 'ws';

export const OnCreateTradeDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"subscription","name":{"kind":"Name","value":"OnCreateTrade"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"userId"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"createTrade"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"userId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"userId"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"trade"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"totalValue"}},{"kind":"Field","name":{"kind":"Name","value":"markupPercent"}},{"kind":"Field","name":{"kind":"Name","value":"avgPaintWear"}},{"kind":"Field","name":{"kind":"Name","value":"tradeItems"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"itemVariant"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"externalId"}}]}},{"kind":"Field","name":{"kind":"Name","value":"steamExternalAssetId"}}]}}]}}]}}]}}]} as unknown as DocumentNode;

const wsLink = new GraphQLWsLink(
    createClient({
        url: 'wss://api.csgoroll.com/graphql',
        webSocketImpl: class extends WebSocket {
            constructor(address: any, protocols: any) {
                super(address, protocols, {
                    headers: {
                        'user-agent':
                            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)',
                    },
                });
            }
        },
        keepAlive: 30_000,
        retryAttempts: Infinity,
        shouldRetry: () => true,
    }),
);

const client = new ApolloClient({
    link: wsLink,
    defaultOptions: {
        watchQuery: {
            fetchPolicy: 'no-cache',
            errorPolicy: 'ignore',
        },
        query: {
            fetchPolicy: 'no-cache',
            errorPolicy: 'all',
        },
        mutate: {
            fetchPolicy: 'no-cache',
            errorPolicy: 'all',
        },
    },
    queryDeduplication: false,
    cache: new InMemoryCache(),
});

const sub = client
    .subscribe({
        query: OnCreateTradeDocument,
        variables: {},
    })
    .subscribe(async ({ data }) => {
        // ...
    });

```

Run with: `bun run ./path/to/file.ts`

### What is the expected behavior?

It should subscribe and start receiving events

### What do you see instead?

```bash
32 |                     if (err instanceof Error) {
33 |                         return observer.error(err);
34 |                     }
35 |                     var likeClose = isLikeCloseEvent(err);
36 |                     if (likeClose || isLikeErrorEvent(err)) {
37 |                         return observer.error(new Error("Socket closed".concat(likeClose ? " with event ".concat(err.code) : "").concat(likeClose ? " ".concat(err.reason) : "")));
                                                   ^
error: Socket closed with event 1002 Expected 101 status code
      at error (/node_modules/.pnpm/@apollo+client@3.7.15_graphql-ws@5.14.3_graphql@16.8.1/node_modules/@apollo/client/link/subscriptions/subscriptions.cjs:37:47)
      at /node_modules/.pnpm/graphql-ws@5.14.3_graphql@16.8.1/node_modules/graphql-ws/lib/client.js:441:13
      at processTicksAndRejections (:61:77)
```

### Additional information

Works fine on NodeJS `pnpm tsnd --transpile-only ./path/to/file.ts` and using bun when we don't create the subscription.

**Comment by nik-webdevelop** [comment]
+1, got the same issue today
