### ISSUE TITLE
Bun cannot open a .node file

### ISSUE THREAD

**Issue by Polygons1** [oven-sh/bun#7860]
### What version of Bun is running?

1.0.20+09d51486e

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

bun run build on an vite + electron project (with electron-builder)

### What is the expected behavior?

packaging the app

### What do you see instead?

⨯ require is not a function. (In 'require("./native.node")', 'require' is an instance of Object)  failedTask=build stackTrace=TypeError: require is not a function. (In 'require("./native.node")', 'require' is an instance of Object)

**Comment by Electroid** [comment]
Thanks for reporting. Would you be able to provide the template or repository you used, as well as the full command output?

**Comment by Polygons1** [comment]
bunx create-electron-vite with the React template

```
$ tsc && vite build && electron-builder
vite v4.5.1 building for production...
✓ 31 modules transformed.
dist/index.html                  0.39 kB │ gzip:  0.27 kB
dist/assets/index-5d96450e.js  328.45 kB │ gzip: 99.99 kB
✓ built in 2.30s
vite v4.5.1 building for production...
✓ 1 modules transformed.
dist-electron/main.js  0.81 kB │ gzip: 0.46 kB
✓ built in 27ms
vite v4.5.1 building for production...
✓ 1 modules transformed.
dist-electron/preload.js  1.86 kB │ gzip: 0.91 kB
✓ built in 32ms
  • electron-builder  version=24.9.1 os=23.1.0
  • loaded configuration  file=/Users/User/code/browser-electron/electron-builder.json5
  • description is missed in the package.json  appPackageFile=/Users/User/code/browser-electron/package.json
  • author is missed in the package.json  appPackageFile=/Users/User/code/browser-electron/package.json
  • writing effective config  file=release/0.0.0/builder-effective-config.yaml
  ⨯ require is not a function. (In 'require("./native.node")', 'require' is an instance of Object)  failedTask=build stackTrace=TypeError: require is not a function. (In 'require("./native.node")', 'require' is an instance of Object)
    at /Users/User/code/browser-electron/node_modules/iconv-corefoundation/lib/native.js:5:19
    at global code (/Users/User/code/browser-electron/node_modules/iconv-corefoundation/lib/native.js:18:8)
    at anonymous (native)
    at overridableRequire (:1:21)
    at /Users/User/code/browser-electron/node_modules/iconv-corefoundation/lib/index.js:6
    at global code (/Users/User/code/browser-electron/node_modules/iconv-corefoundation/lib/index.js:23:8)
    at anonymous (native)
    at overridableRequire (:1:21)
    at /Users/User/code/browser-electron/node_modules/dmg-license/lib/Labels.js:3:6
    at global code (/Users/User/code/browser-electron/node_modules/dmg-license/lib/Labels.js:134:8)
    at anonymous (native)
    at overridableRequire (:1:21)
    at /Users/User/code/browser-electron/node_modules/dmg-license/lib/assembleLicenses.js:6:6
    at global code (/Users/User/code/browser-electron/node_modules/dmg-license/lib/assembleLicenses.js:121:8)
    at anonymous (native)
    at overridableRequire (:1:21)
    at /Users/User/code/browser-electron/node_modules/dmg-license/lib/index.js:4:6
    at global code (/Users/User/code/browser-electron/node_modules/dmg-license/lib/index.js:43:8)
    at anonymous (native)
    at overridableRequire (:1:21)
    at /Users/User/code/browser-electron/node_modules/dmg-builder/src/dmgLicense.ts:64:2
    at global code (/Users/User/code/browser-electron/node_modules/dmg-builder/out/dmgLicense.js:39:8)
    at anonymous (native)
    at overridableRequire (:1:21)
    at /Users/User/code/browser-electron/node_modules/dmg-builder/src/dmg.ts:13:1
    at global code (/Users/User/code/browser-electron/node_modules/dmg-builder/src/dmg.ts:256:3)
    at anonymous (native)
    at overridableRequire (:1:21)
    at /Users/User/code/browser-electron/node_modules/dmg-builder/src/dmgUtil.ts:6:1
    at global code (/Users/User/code/browser-electron/node_modules/dmg-builder/src/dmgUtil.ts:53:2)
    at anonymous (native)
    at overridableRequire (:1:21)
    at createTargets (/Users/User/code/browser-electron/node_modules/app-builder-lib/src/macPackager.ts:76:19)
    at createTargets (/Users/User/code/browser-electron/node_modules/app-builder-lib/src/targets/targetFactory.ts:63:3)
    at /Users/User/code/browser-electron/node_modules/app-builder-lib/src/packager.ts:441:61
    at processTicksAndRejections (:61:77)
error: script "build" exited with code 1
```

(the result was an empty object, not a function)

**Comment by nektro** [comment]
Hi! if this is still affecting you in the latest version of Bun (you may need to run `bun upgrade`) please leave a comment and let us know. for now we're going to mark this as closed.
