### ISSUE TITLE
Remix running with node, not bun

### ISSUE THREAD

**Issue by danthegoodman1** [oven-sh/bun#7918]
### What version of Bun is running?

1.0.15

### What platform is your computer?

linux x86

### What steps can reproduce the bug?

```
bun create remix .
```

```dockerfile
# syntax = docker/dockerfile:1

# Adjust BUN_VERSION as desired
ARG BUN_VERSION=1.0.15
FROM oven/bun:${BUN_VERSION}-slim as base

LABEL fly_launch_runtime="Remix"

# Remix app lives here
WORKDIR /app

# Set production environment
ENV NODE_ENV="production"


# Throw-away build stage to reduce size of final image
FROM base as build

# Install packages needed to build node modules
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential node-gyp pkg-config python-is-python3

# Install node modules
COPY --link bun.lockb package-lock.json package.json ./
RUN bun install

# Copy application code
COPY --link . .

# Build application
RUN bun run build

# Remove development dependencies
RUN rm -rf node_modules && \
    bun install --ci


# Final stage for app image
FROM base

# Copy built application
COPY --from=build /app /app

# Start the server by default, this can be overwritten at runtime
EXPOSE 3000
CMD [ "bun", "run", "start" ]
```

This is the remix template being deployed to fly.io (you can just build this locally)
```
docker build . -t ahhhhhhhhhhhh
```

### What is the expected behavior?

It builds. I can run `bun run build` fine on macOS using the same bun version, but once in this docker build it fails.

### What do you see instead?

```[+] Building 1.0s (13/15)                                                                    docker:desktop-linux
 => [internal] load .dockerignore                                                                            0.0s
 => => transferring context: 89B                                                                             0.0s
 => [internal] load build definition from Dockerfile                                                         0.0s
 => => transferring dockerfile: 1.01kB                                                                       0.0s
 => resolve image config for docker.io/docker/dockerfile:1                                                   0.3s
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:ac85f380a63b13dfcefa89046420e1781752bab20212  0.0s
 => [internal] load metadata for docker.io/oven/bun:1.0.15-slim                                              0.1s
 => [base 1/2] FROM docker.io/oven/bun:1.0.15-slim@sha256:385d4b709117988373c914e64b1e99b703f9a637cbb8abd02  0.0s
 => [internal] load build context                                                                            0.1s
 => => transferring context: 42.89kB                                                                         0.1s
 => CACHED [base 2/2] WORKDIR /app                                                                           0.0s
 => CACHED [build 1/6] RUN apt-get update -qq &&     apt-get install --no-install-recommends -y build-essen  0.0s
 => CACHED [build 2/6] COPY --link bun.lockb package-lock.json package.json ./                               0.0s
 => CACHED [build 3/6] RUN bun install                                                                       0.0s
 => CACHED [build 4/6] COPY --link . .                                                                       0.0s
 => ERROR [build 5/6] RUN bun run build                                                                      0.3s
------
 > [build 5/6] RUN bun run build:
0.185 $ remix build
0.252 /app/node_modules/@remix-run/dev/dist/cli/run.js:158
0.252   flags.interactive = flags.interactive ?? require.main === module;
0.252                                          ^
0.252
0.252 SyntaxError: Unexpected token '?'
0.252     at wrapSafe (internal/modules/cjs/loader.js:915:16)
0.252     at Module._compile (internal/modules/cjs/loader.js:963:27)
0.252     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
0.252     at Module.load (internal/modules/cjs/loader.js:863:32)
0.252     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
0.252     at Module.require (internal/modules/cjs/loader.js:887:19)
0.252     at require (internal/modules/cjs/helpers.js:74:18)
0.252     at Object.<anonymous> (/app/node_modules/@remix-run/dev/dist/cli/index.js:15:11)
0.252     at Module._compile (internal/modules/cjs/loader.js:999:30)
0.252     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
0.258 error: script "build" exited with code 1 (SIGHUP)
------
Dockerfile:31
--------------------
  29 |
  30 |     # Build application
  31 | >>> RUN bun run build
  32 |
  33 |     # Remove development dependencies
--------------------
ERROR: failed to solve: process "/bin/sh -c bun run build" did not complete successfully: exit code: 1```

### Additional information

_No response_

**Comment by danthegoodman1** [comment]
nice job fly
```
#10 [build 2/7] RUN node --version
#10 0.208 v12.22.12
#10 DONE 0.2s
```

**Comment by danthegoodman1** [comment]
Although I kind of expected bun to run this, not node...

**Comment by danthegoodman1** [comment]
Reopening as it seems that the issue is that it's all running with node, not bun

**Comment by danthegoodman1** [comment]
Related https://github.com/remix-run/remix/discussions/7413

**Comment by Electroid** [comment]
If `node` is not installed, Bun will detect this and use `bun` instead. However, we currently don't handle the case where the version of `node` is so old, that it should probably use `bun` instead.

**Comment by danthegoodman1** [comment]
Why is node installed? Is it default on the OS?

**Comment by danthegoodman1** [comment]
@Electroid is there a way to force bun? Seems expected that if I run `bun run {script}`, it would run with bun.

**Comment by danthegoodman1** [comment]
https://bun.sh/docs/cli/run#bun perhaps with this

**Comment by kubahasek** [comment]
Hi @danthegoodman1 have you managed to resolved this?

**Comment by danthegoodman1** [comment]
No I just switched back to node

**Comment by sjerratsch** [comment]
I believe the bun create remix template has vitejs in it and bun is only there as a package manager. Vite uses nodejs again.

Try looking at:
https://github.com/sergiodxa/remix-on-bun
https://sergiodxa.com/tutorials/build-an-app-with-remix-and-bun

worked for me with fly launch
