### ISSUE TITLE
@elastic/elasticsearch@8.11.0 not working due to missing undici.Pool.request

### ISSUE THREAD

**Issue by brabeji** [oven-sh/bun#7920]
### What version of Bun is running?

1.0.20

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

Simple usage of ElasticSearch client throws `Not implemented in bun` error:

```
import { Client as ElasticClient } from '@elastic/elasticsearch'; // 8.11.0

const elasticClient = new ElasticClient({
	node: 'http://127.0.0.1:9200',
});
await elasticClient.indices.create({ index: 'foo' });
```

### What is the expected behavior?

Client working or different error is thrown.

### What do you see instead?

"Not implemented in bun" error is thrown

### Additional information

After some tracing, the dismissed task of #1987 seems to be an issue, although I can't find the error message in bun codebase which is weird to me.

**Comment by kaioduarte** [comment]
The error comes from here:
https://github.com/oven-sh/bun/blob/837cbd60d5ffc5d1faf2131bbd8d968217bab2ff/src/js/thirdparty/undici.js#L268-L272

A workaround is to use the `HttpConnection` transporter:
```diff
-import { Client as ElasticClient } from '@elastic/elasticsearch'; // 8.11.0
+import { Client as ElasticClient, HttpConnection } from '@elastic/elasticsearch'; // 8.11.0

const elasticClient = new ElasticClient({
	node: 'http://127.0.0.1:9200',
+	Connection: HttpConnection,
});
await elasticClient.indices.create({ index: 'foo' });

```

**Comment by Kabeer10** [comment]
```
// Wrap the error to get a clean stack trace
539 |                         const wrappedError = error.name === 'TimeoutError'
540 |                             ? new errors_1.TimeoutError(error.message, result, errorOptions)
541 |                             : new errors_1.ConnectionError(error.message, result, errorOptions);
542 |                         this[symbols_1.kDiagnostic].emit('response', wrappedError, result);
543 |                         throw wrappedError;
                         ^
ConnectionError: Not implemented in bun
      at /home/[userName]/Desktop/project/node_modules/.pnpm/@elastic+transport@8.4.0/node_modules/@elastic/transport/lib/Transport.js:543:20
      at asyncFunctionResume (native:1:1)
      at promiseReactionJobWithoutPromiseUnwrapAsyncContext (native:1:1)
      at promiseReactionJob (native:1:1)
      at processTicksAndRejections (native:1:1)
```

**Comment by verheyenkoen** [comment]
Similar issue when using the [solr-client](https://www.npmjs.com/package/solr-client) package.

```sh
177 | class Client extends Dispatcher {
178 |   constructor() {
179 |     super(...arguments);
180 |   }
181 |   request() {
                        ^
error: Not implemented in bun
      at request (undici:181:19)
      at /Users/<redacted>/node_modules/solr-client/dist/lib/solr.js:154:32
      at doRequest (/Users/<redacted>/node_modules/solr-client/dist/lib/solr.js:129:21)
      at doQuery (/Users/<redacted>/node_modules/solr-client/dist/lib/solr.js:407:19)
```

Which correlates to this source code: https://github.com/lbdremy/solr-node-client/blob/c1a2f2a3ec233a19f84b061eb01ff4ae718d14ef/lib/solr.ts#L200

If anyone knows of another Solr client package that is bun-compatible already, please let me know.

**Comment by wnz99** [comment]
Similar issue when using https://github.com/pinojs/pino-elasticsearch package.

This will work:

```
import { HttpConnection } from '@elastic/elasticsearch'
import pino from 'pino'
import pinoElastic from 'pino-elasticsearch'

const streamToElastic = pinoElastic({
  index: 'logs',
  node: 'http://localhost:9200',
  //   esVersion: 8,
  flushBytes: 1,
  auth: {
    username: 'elastic',
    password: 'xxxxxx',
  },
  Connection: HttpConnection,
})

streamToElastic.on('unknown', (event) => console.log(event))

streamToElastic.on('error', (error) => {
  console.error('Elasticsearch client error:', error)
})

// Capture errors returned from Elasticsearch, "it will be called every time a document can't be indexed".
streamToElastic.on('insertError', (error) => {
  console.error('Elasticsearch server error:', error)
})

const pinoOptions = {}

const streams = [{ stream: process.stdout }, { stream: streamToElastic }]

const logger = pino(pinoOptions, pino.multistream(streams))

logger.info('hello world')
```

**Comment by salahudd33n** [comment]
Experiencing the same as @wnz99

**Comment by chetank628** [comment]
All the famous Logging library like winston-elastic pino-elastic are not working because of missing implementation undici.pool.request

**Comment by progys** [comment]
Faced this issue suddenly when migrated to Elastic 8. Sadly, have to go back to using Nodejs.

**Comment by Vinayak-Soni** [comment]
> The error comes from here:
> 
> [bun/src/js/thirdparty/undici.js](https://github.com/oven-sh/bun/blob/837cbd60d5ffc5d1faf2131bbd8d968217bab2ff/src/js/thirdparty/undici.js#L268-L272)
> 
> Lines 268 to 272 in [837cbd6](/oven-sh/bun/commit/837cbd60d5ffc5d1faf2131bbd8d968217bab2ff)
> 
>  class Pool extends Dispatcher { 
>    request() { 
>      throw new Error("Not implemented in bun"); 
>    } 
>  } 
> A workaround is to use the `HttpConnection` transporter:
> 
> -import { Client as ElasticClient } from '@elastic/elasticsearch'; // 8.11.0
> +import { Client as ElasticClient, HttpConnection } from '@elastic/elasticsearch'; // 8.11.0
> 
> const elasticClient = new ElasticClient({
> 	node: 'http://127.0.0.1:9200',
> +	Connection: HttpConnection,
> });
> await elasticClient.indices.create({ index: 'foo' });

is worked for me. i used elastic search with docker, client is using bun js latest version. in node js environment we dont have to do this but in bun we have to do this to make the connection work.
