### ISSUE TITLE
ReferenceError: expect is not defined

### ISSUE THREAD

**Issue by andyjessop** [oven-sh/bun#7940]
### What version of Bun is running?

1.0.20

### What platform is your computer?

Darwin 23.0.0 x86_64 i386

### What steps can reproduce the bug?

puppeteer.ts
```ts
import puppeteer, { Browser, Page } from 'puppeteer';

export let page: Page;
export let browser: Browser;

export async function init() {
  browser = await puppeteer.launch({ headless: 'new' });
  page = await browser.newPage();

  await page.goto('http://localhost:4321');
}
```

setup.ts
```ts
import { afterAll, beforeAll } from 'bun:test';

import { browser, init } from './puppeteer';

beforeAll(async () => {
  await init();
});

afterAll(async () => {
  browser?.close();
});
```

test1.test.ts
```ts
import { describe, expect, test } from 'bun:test';

import { page } from './puppeteer';

describe('test', () => {
  test('test', () => {
    page.evaluate(() => {
      expect(document).not.toBeNull();
    });
  });
});
```

test2.test.ts
```ts
import { describe, expect, test } from 'bun:test';

import { page } from './puppeteer';

describe('test2', () => {
  test('test2', () => {
    page.evaluate(() => {
      expect(document).not.toBeNull();
    });
  });
});

```

Run with:
```bash
bun test test.test.ts test2.test.ts --preload ./src/setup.ts
```

### What is the expected behavior?

The tests should run and pass

### What do you see instead?

```
> bun test test.test.ts test2.test.ts --preload ./src/setup.ts
bun test v1.0.20 (09d51486)

src/test.test.ts:
✓ test > test [1.29ms]

src/test2.test.ts:
250 |          */
251 |         async $(selector) {
252 |             return await this.mainFrame().$(selector);
253 |         }
254 |         /**
255 |          * The method runs `document.querySelectorAll` within the page. If no elements
                              ^
ReferenceError: expect is not defined
      at evaluate (evaluate at evaluate (/Users/andy/dev/ol/cortex/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:255:25)
      at /Users/andy/dev/ol/cortex/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ExecutionContext.js:228:19
      at processTicksAndRejections (:61:39)
✓ test2 > test2 [1.51ms]
 2 pass
 0 fail
Ran 2 tests across 2 files. [1299.00ms]
```

**Comment by ghost** [comment]
It looks like this is because `document` is not imported in `test1.test.ts` and `test2.test.ts`, so this isn't an issue with Bun.
