### ISSUE TITLE
[win][fs] Crash on reading (`fs.readFile`) 2 GB file+ (`reached unreachable code`)

### ISSUE THREAD

**Issue by AlttiRi** [oven-sh/bun#8255]
### What version of Bun is running?

1.0.23

### What platform is your computer?

Window 10

### What steps can reproduce the bug?

```js
import fs from "node:fs/promises";

try {
    const largeFilePath = "...";
    const file = await fs.readFile(largeFilePath);
    console.log(file.length);
} catch (e) {
    console.error(e);
    console.log("Okay, I will use stream approach");
}
```

### What is the expected behavior?

Node.js:
```
RangeError [ERR_FS_FILE_TOO_LARGE]: File size (4545459987) is greater than 2 GiB
    at new NodeError (node:internal/errors:405:5)
    at readFileHandle (node:internal/fs/promises:497:11)
    at async file:///C:/Downloads/bun-windows-x64/x.mjs:4:18 {
  code: 'ERR_FS_FILE_TOO_LARGE'
}
Okay, I will use stream approach
```

### What do you see instead?

Bun:
```
uh-oh: reached unreachable code
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.0.23-canary.14 (52894121) Windows x64
AutoCommand:
Elapsed: 679ms | User: 500ms | Sys: 859ms
RSS: 4.64GB | Peak: 4.64GB | Commit: 4.71GB | Faults: 1134829
----- bun meta -----

0   00007FF6C47351E8
1   ???
2   ???
3   ???
4   ???
5   ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 7368 panic: reached unreachable code
???:?:?: 0x7ff6c3ba4677 in ??? (???)
???:?:?: 0x7ff6c3802443 in ??? (???)
???:?:?: 0x7ff8940a7343 in ??? (KERNEL32.DLL)
???:?:?: 0x7ff895f626b0 in ??? (ntdll.dll)
```

### Additional information

It should just throw `RangeError`, instead of an application's crash.
Rel: https://github.com/oven-sh/bun/issues/8254

**Comment by AlttiRi** [comment]
BTW, also, for `Blob` there  is 4 GB limitation in Node.js:
```js
try {
    new Blob([new ArrayBuffer(2_000_000_000), new ArrayBuffer(2_000_000_000), new ArrayBuffer(2_000_000_000)])
} catch (e) {
    console.error(e);
}
```

```
RangeError [ERR_BUFFER_TOO_LARGE]: Cannot create a Buffer larger than 4294967295 bytes
    at new NodeError (node:internal/errors:405:5)                                     
    at new Blob (node:internal/blob:165:13)                                           
    at file:///C:/Downloads/bun-windows-x64/x.mjs:3:5                                 
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {                  
  code: 'ERR_BUFFER_TOO_LARGE'                                                        
}  
```

Although, in any browser it works OK. 
**Bun also works with it without errors.**

**Comment by Jarred-Sumner** [comment]
The bug is due to using signed 32 bit integers I believe

**Comment by AlttiRi** [comment]
Node.js fails instantly with the error:

```
RangeError [ERR_FS_FILE_TOO_LARGE]: File size (2275677138) is greater than 2 GiB
    at new NodeError (node:internal/errors:405:5)
    at readFileHandle (node:internal/fs/promises:497:11)
    at async file:///C:/Dev/test/x.mjs:5:18 {
  code: 'ERR_FS_FILE_TOO_LARGE'
}
```

Bun spends seconds to read the file from HDD then crashes:

```
----- bun meta -----
Bun v1.0.26-canary.70 (82a07430) Windows x64
AutoCommand:
Elapsed: 25580ms | User: 78ms | Sys: 1625ms
RSS: 2.35GB | Peak: 2.38GB | Commit: 2.40GB | Faults: 581681
----- bun meta -----

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 2200 panic: attempt to cast negative value to unsigned integer
???:?:?: 0x7ff7dae82052 in ??? (bun.exe)
???:?:?: 0x7ff7db4da316 in ??? (bun.exe)
???:?:?: 0x7ff7db0bb313 in ??? (bun.exe)
???:?:?: 0x7ffcab487343 in ??? (KERNEL32.DLL)
???:?:?: 0x7ffcaca426b0 in ??? (ntdll.dll)
```
