### ISSUE TITLE
`bun install --global react-devtools`: Electron failed to install correctly

### ISSUE THREAD

**Issue by fregante** [oven-sh/bun#8347]
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

Darwin 23.2.0 x86_64 i386

### What steps can reproduce the bug?

```sh
bun install --global react-devtools
react-devtools
```

### What is the expected behavior?

`react-devtools` should run when installed globally

### What do you see instead?

```
~/.bun/install/global/node_modules/electron/index.js:17
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again');
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (~/.bun/install/global/node_modules/electron/index.js:17:11)
    at Object.<anonymous> (~/.bun/install/global/node_modules/electron/index.js:21:18)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (~/.bun/install/global/node_modules/react-devtools/bin.js:12:18)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)

Node.js v20.5.1
```

### Additional information

This works:

```sh
bun rm -g react-devtools
npm install --global react-devtools # npm 10.2.5
react-devtools
```

**Comment by marioparaschiv** [comment]
I can reproduce this too.

**Comment by PalmDevs** [comment]
You have to run the postinstall script of Electron:

```
bun install --global react-devtools
bun pm trust -g electron
react-devtools
```

![Image](https://github.com/user-attachments/assets/7fb29b06-a103-4fe2-91a0-cee92ae43326)

**Comment by fregante** [comment]
The second command fails:

```
$ bun pm trust -g electron
bun pm trust v1.1.32 (fe8d0079)

error: 0 scripts ran. The following packages are already trusted, don't have scripts to run, or don't exist:

 - electron
```

I removed `react-devtools` from both bun global and npm global, and re-installed it with your command
