### ISSUE TITLE
[windows] Glob leak tests are failing

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#8348]
TODOs:
- These tests should not fail
- `path` should not be garbled. We must copy the file path. Garbled text indicates memory corruption.

```js
bun test v1.0.25-canary.7 (b3b5835b)


 2 |       let prev: number | undefined = undefined;
3 |       for (let i = 0; i < 100; i++) {
4 |         Bun.gc(true);
5 |         (function () {
6 |           const glob = new Bun.Glob("**/*");
7 |           Array.from(glob.scanSync({ cwd: 'D:\a\bun\bun\test\js\bun\glob' }));
                        ^
error: UV_ENOENT
   errno: -4058
 syscall: "open"
   path: "D�:�a���u�n���u�n�	�e�s�t�j�s���u�n�g�l�o�b���"

      at scanSync (:1:21)
      at D:\a\bun\bun\[eval]:7:22
      at D:\a\bun\bun\[eval]:9:16



29 |       }
30 |     `;
31 | 
32 |     const { stdout, stderr, exitCode } = Bun.spawnSync([bun, "--smol", "-e", code]);
33 |     console.log(stdout.toString(), stderr.toString());
34 |     expect(exitCode).toBe(0);
         ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at D:/a/bun/bun/test/js/bun/glob/leak.test.ts:34:5
✗ leaks > scanSync [49.09ms]
 error: UV_ENOENT
   errno: -4058
 syscall: "open"
   path: "D�:�a���u�n���u�n�	�e�s�t�j�s���u�n�g�l�o�b���"




55 |       }
56 |     `;
57 | 
58 |     const { stdout, stderr, exitCode } = Bun.spawnSync([bun, "--smol", "-e", code]);
59 |     console.log(stdout.toString(), stderr.toString());
60 |     expect(exitCode).toBe(0);
         ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at D:/a/bun/bun/test/js/bun/glob/leak.test.ts:60:5
      at D:/a/bun/bun/test/js/bun/glob/leak.test.ts:37:16
✗ leaks > scan [63.88ms]



 0 pass
 2 fail
 2 expect() calls
Ran 2 tests across 1 files. [147.00ms]
```

**Comment by zackradisic** [comment]
Closed by #8382
