### ISSUE TITLE
[windows] Fix module resolution bugs involving package paths and/or tsconfig.json paths

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#8356]
To reproduce:
```sh
bun-debug test test\js\bun\resolve\resolve-ts.test.ts
bun-debug test test\js\bun\resolve\resolve.test.ts
bun-debug test test\js\third_party\postgres\postgres.test.ts
bun-debug test test\js\third_party\grpc-js\test-retry.test.ts
bun-debug test test\js\third_party\grpc-js\test-idle-timer.test.ts
bun-debug test test\js\third_party\grpc-js\test-client.test.ts
bun-debug test test\js\third_party\grpc-js\test-channel-credentials.test.ts
bun-debug test test\js\third_party\socket.io\socket.io-messaging-many.test.ts
bun-debug test test\js\third_party\socket.io\socket.io-middleware.test.ts
bun-debug test test\js\third_party\svelte\svelte.test.ts
```

Log:

```js
bun test v1.0.25-canary.7 (b3b5835b)


error: Cannot find package "abc" from "C:/Users/runneradmin/AppData/Local/Temp/resolved63_nmbBra/index.js"


147 |     stderr: "inherit",
148 |     stdout: "inherit",
149 |     stdin: "inherit",
150 |   });
151 | 
152 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at runTest (D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:152:3)
      at D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:166:19
✗ with package.json > as dir > resolve with package.json exports type:module with .js file [137.90ms]
error: Cannot find package "abc" from "C:/Users/runneradmin/AppData/Local/Temp/resolve22b9_dMsfWi/index.js"


147 |     stderr: "inherit",
148 |     stdout: "inherit",
149 |     stdin: "inherit",
150 |   });
151 | 
152 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at runTest (D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:152:3)
      at D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:166:19
✗ with package.json > as dir > resolve with package.json exports type:module without .js file [81.64ms]
error: Cannot find package "abc" from "C:/Users/runneradmin/AppData/Local/Temp/resolve13e6_bZXPnE/index.js"


147 |     stderr: "inherit",
148 |     stdout: "inherit",
149 |     stdin: "inherit",
150 |   });
151 | 
152 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at runTest (D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:152:3)
      at D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:166:19
✗ with package.json > as dir > resolve with package.json exports type:commonjs with .js file [87.72ms]
error: Cannot find package "abc" from "C:/Users/runneradmin/AppData/Local/Temp/resolve11a7_V5LKS3/index.js"


147 |     stderr: "inherit",
148 |     stdout: "inherit",
149 |     stdin: "inherit",
150 |   });
151 | 
152 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at runTest (D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:152:3)
      at D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:166:19
✗ with package.json > as dir > resolve with package.json exports type:commonjs without .js file [78.51ms]
error: Cannot find package "abc" from "C:/Users/runneradmin/AppData/Local/Temp/resolve961_NBvuKw/index.js"


147 |     stderr: "inherit",
148 |     stdout: "inherit",
149 |     stdin: "inherit",
150 |   });
151 | 
152 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at runTest (D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:152:3)
      at D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:166:19
✗ with package.json > as dir > resolve with package.json exports  with .js file [89.10ms]
error: Cannot find package "abc" from "C:/Users/runneradmin/AppData/Local/Temp/resolve1752_9utv6u/index.js"


147 |     stderr: "inherit",
148 |     stdout: "inherit",
149 |     stdin: "inherit",
150 |   });
151 | 
152 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at runTest (D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:152:3)
      at D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:166:19
✗ with package.json > as dir > resolve with package.json exports  without .js file [81.00ms]
4 |         if (pkg.foo !== 1) {
5 |             throw new Error("Unexpected value\n" + JSON.stringify(pkg, null, 2));
6 |         }
7 | 
8 |         if (pkg.sibling !== 1) {
9 |           throw new Error("Unexpected value\n" + JSON.stringify(pkg, null, 2));
                    ^
error: Unexpected value
{
  "foo": 1,
  "sibling": 2
}
      at C:/Users/runneradmin/AppData/Local/Temp/resolved2b_lFWicD/index.js:9:17


147 |     stderr: "inherit",
148 |     stdout: "inherit",
149 |     stdin: "inherit",
150 |   });
151 | 
152 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at runTest (D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:152:3)
      at D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:166:19
✗ with package.json > as dir > resolve without package.json exports type:module with .js file [90.13ms]
✓ with package.json > as dir > resolve without package.json exports type:module without .js file [82.49ms]
4 |         if (pkg.foo !== 1) {
5 |             throw new Error("Unexpected value\n" + JSON.stringify(pkg, null, 2));
6 |         }
7 | 
8 |         if (pkg.sibling !== 1) {
9 |           throw new Error("Unexpected value\n" + JSON.stringify(pkg, null, 2));
                    ^
error: Unexpected value
{
  "foo": 1,
  "sibling": 2
}
      at C:/Users/runneradmin/AppData/Local/Temp/resolve1570_U5R2Ym/index.js:9:17


147 |     stderr: "inherit",
148 |     stdout: "inherit",
149 |     stdin: "inherit",
150 |   });
151 | 
152 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at runTest (D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:152:3)
      at D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:166:19
✗ with package.json > as dir > resolve without package.json exports type:commonjs with .js file [89.19ms]
✓ with package.json > as dir > resolve without package.json exports type:commonjs without .js file [77.44ms]
4 |         if (pkg.foo !== 1) {
5 |             throw new Error("Unexpected value\n" + JSON.stringify(pkg, null, 2));
6 |         }
7 | 
8 |         if (pkg.sibling !== 1) {
9 |           throw new Error("Unexpected value\n" + JSON.stringify(pkg, null, 2));
                    ^
error: Unexpected value
{
  "foo": 1,
  "sibling": 2
}
      at C:/Users/runneradmin/AppData/Local/Temp/resolve1eaa_nASUVE/index.js:9:17


147 |     stderr: "inherit",
148 |     stdout: "inherit",
149 |     stdin: "inherit",
150 |   });
151 | 
152 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at runTest (D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:152:3)
      at D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:166:19
✗ with package.json > as dir > resolve without package.json exports  with .js file [90.19ms]
✓ with package.json > as dir > resolve without package.json exports  without .js file [77.87ms]
error: Cannot find package "abc" from "C:/Users/runneradmin/AppData/Local/Temp/resolve1688_5joRdc/index.js"


147 |     stderr: "inherit",
148 |     stdout: "inherit",
149 |     stdin: "inherit",
150 |   });
151 | 
152 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at runTest (D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:152:3)
      at D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:166:19
✗ with package.json > resolve with package.json exports type:module with .js file [76.49ms]
error: Cannot find package "abc" from "C:/Users/runneradmin/AppData/Local/Temp/resolve1911_O4sT08/index.js"


147 |     stderr: "inherit",
148 |     stdout: "inherit",
149 |     stdin: "inherit",
150 |   });
151 | 
152 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at runTest (D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:152:3)
      at D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:166:19
✗ with package.json > resolve with package.json exports type:module without .js file [79.23ms]
error: Cannot find package "abc" from "C:/Users/runneradmin/AppData/Local/Temp/resolve1fd4_iBBVLC/index.js"


147 |     stderr: "inherit",
148 |     stdout: "inherit",
149 |     stdin: "inherit",
150 |   });
151 | 
152 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at runTest (D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:152:3)
      at D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:166:19
✗ with package.json > resolve with package.json exports type:commonjs with .js file [78.52ms]
error: Cannot find package "abc" from "C:/Users/runneradmin/AppData/Local/Temp/resolve22e6_RHSKia/index.js"


147 |     stderr: "inherit",
148 |     stdout: "inherit",
149 |     stdin: "inherit",
150 |   });
151 | 
152 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at runTest (D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:152:3)
      at D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:166:19
✗ with package.json > resolve with package.json exports type:commonjs without .js file [68.13ms]
error: Cannot find package "abc" from "C:/Users/runneradmin/AppData/Local/Temp/resolve2344_NWRAZp/index.js"


147 |     stderr: "inherit",
148 |     stdout: "inherit",
149 |     stdin: "inherit",
150 |   });
151 | 
152 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at runTest (D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:152:3)
      at D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:166:19
✗ with package.json > resolve with package.json exports  with .js file [110.80ms]
error: Cannot find package "abc" from "C:/Users/runneradmin/AppData/Local/Temp/resolveca2_GFUNHr/index.js"


147 |     stderr: "inherit",
148 |     stdout: "inherit",
149 |     stdin: "inherit",
150 |   });
151 | 
152 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at runTest (D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:152:3)
      at D:/a/bun/bun/test/js/bun/resolve/resolve-ts.test.ts:166:19
✗ with package.json > resolve with package.json exports  without .js file [82.36ms]
✓ with package.json > resolve without package.json exports type:module with .js file [80.56ms]
✓ with package.json > resolve without package.json exports type:module without .js file [78.16ms]
✓ with package.json > resolve without package.json exports type:commonjs with .js file [79.33ms]
✓ with package.json > resolve without package.json exports type:commonjs without .js file [79.81ms]
✓ with package.json > resolve without package.json exports  with .js file [79.68ms]
✓ with package.json > resolve without package.json exports  without .js file [69.72ms]
✓ .ts file is chosen over .js file locally [0.18ms]
✓ resolve without package.json and with .js file [79.55ms]
✓ resolve without package.json and without .js file [67.55ms]



 12 pass
 15 fail
 27 expect() calls
Ran 27 tests across 1 files. [2.20s]
```

```ts
bun test v1.0.25-canary.7 (b3b5835b)


bun test v1.0.25-canary.7 (b3b5835b)

resolve-test.js:
error: Cannot find module "package-json-imports/baz" from "D:\a\bun\bun\test\js\bun\resolve\resolve-test.js"
(fail) #imports [1.33ms]
error: Cannot find module "#foo/wildcard.js" from "D:\a\bun\bun\test\js\bun\resolve\node_modules\package-json-imports\package.json"
(fail) #imports with wildcard [2.30ms]
49 |   expect(run("#foo/wildcard.js")).toBe(wildcard);
50 |   expect(run("#foo/extensionless/wildcard")).toBe(wildcard);
51 | });
52 | 
53 | it("import.meta.resolve", async () => {
54 |   expect(await import.meta.resolve("./resolve-test.js")).toBe(import.meta.path);
       ^
error: expect(received).toBe(expected)

Expected: "D:\\a\\bun\\bun\\test\\js\\bun\\resolve\\resolve-test.js"
Received: "D:/a/bun/bun/test/js/bun/resolve/resolve-test.js"

      at D:/a/bun/bun/test/js/bun/resolve/resolve-test.js:54:3
(fail) import.meta.resolve [5.04ms]
107 | });
108 | 
109 | // the slightly lower level API, which doesn't prefill the second param
110 | // and expects a directory instead of a filepath
111 | it("Bun.resolve", async () => {
112 |   expect(await Bun.resolve("./resolve-test.js", import.meta.dir)).toBe(import.meta.path);
        ^
error: expect(received).toBe(expected)

Expected: "D:\\a\\bun\\bun\\test\\js\\bun\\resolve\\resolve-test.js"
Received: "D:/a/bun/bun/test/js/bun/resolve/resolve-test.js"

      at D:/a/bun/bun/test/js/bun/resolve/resolve-test.js:112:3
(fail) Bun.resolve [5.55ms]
112 |   expect(await Bun.resolve("./resolve-test.js", import.meta.dir)).toBe(import.meta.path);
113 | });
114 | 
115 | // synchronous
116 | it("Bun.resolveSync", () => {
117 |   expect(Bun.resolveSync("./resolve-test.js", import.meta.dir)).toBe(import.meta.path);
        ^
error: expect(received).toBe(expected)

Expected: "D:\\a\\bun\\bun\\test\\js\\bun\\resolve\\resolve-test.js"
Received: "D:/a/bun/bun/test/js/bun/resolve/resolve-test.js"

      at D:/a/bun/bun/test/js/bun/resolve/resolve-test.js:117:3
(fail) Bun.resolveSync [5.13ms]
error: Cannot find module "package-json-exports/baz" from "D:\a\bun\bun\test\js\bun\resolve\resolve-test.js"
(fail) self-referencing imports works [2.10ms]

 0 pass
 6 fail
 3 expect() calls
Ran 6 tests across 1 files. [62.00ms]


13 |     env: bunEnv,
14 |     cwd: import.meta.dir,
15 |     stdio: ["inherit", "inherit", "inherit"],
16 |   });
17 | 
18 |   expect(exitCode).toBe(0);
       ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at D:/a/bun/bun/test/js/bun/resolve/resolve.test.ts:18:3
✗ spawn test file [86.07ms]


94 |   const { exitCode, stdout } = Bun.spawnSync({
95 |     cmd: [bunExe(), `${dir}/test.js`],
96 |     env: bunEnv,
97 |     cwd: import.meta.dir,
98 |   });
99 |   expect(exitCode).toBe(0);
       ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at D:/a/bun/bun/test/js/bun/resolve/resolve.test.ts:99:3
      at D:/a/bun/bun/test/js/bun/resolve/resolve.test.ts:88:35
✗ file url in import resolves [72.29ms]
✓ invalid file url in import throws error [65.23ms]


122 |   const { exitCode, stdout } = Bun.spawnSync({
123 |     cmd: [bunExe(), `${dir}/test.js`],
124 |     env: bunEnv,
125 |     cwd: import.meta.dir,
126 |   });
127 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at D:/a/bun/bun/test/js/bun/resolve/resolve.test.ts:127:3
      at D:/a/bun/bun/test/js/bun/resolve/resolve.test.ts:116:41
✗ file url in await import resolves [65.11ms]


143 |   const { exitCode, stdout } = Bun.spawnSync({
144 |     cmd: [bunExe(), `${dir}/test.js`],
145 |     env: bunEnv,
146 |     cwd: import.meta.dir,
147 |   });
148 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at D:/a/bun/bun/test/js/bun/resolve/resolve.test.ts:148:3
      at D:/a/bun/bun/test/js/bun/resolve/resolve.test.ts:131:65
✗ file url with special characters in await import resolves [72.70ms]


159 |   const { exitCode, stdout } = Bun.spawnSync({
160 |     cmd: [bunExe(), `${dir}/test.js`],
161 |     env: bunEnv,
162 |     cwd: import.meta.dir,
163 |   });
164 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at D:/a/bun/bun/test/js/bun/resolve/resolve.test.ts:164:3
      at D:/a/bun/bun/test/js/bun/resolve/resolve.test.ts:152:77
✗ file url with special characters not encoded in await import resolves [73.78ms]


178 |   const { exitCode, stdout } = Bun.spawnSync({
179 |     cmd: [bunExe(), `${dir}/test.js`],
180 |     env: bunEnv,
181 |     cwd: import.meta.dir,
182 |   });
183 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at D:/a/bun/bun/test/js/bun/resolve/resolve.test.ts:183:3
      at D:/a/bun/bun/test/js/bun/resolve/resolve.test.ts:168:69
✗ file url with special characters in import statement resolves [73.06ms]


194 |   const { exitCode, stdout } = Bun.spawnSync({
195 |     cmd: [bunExe(), `${dir}/test.js`],
196 |     env: bunEnv,
197 |     cwd: import.meta.dir,
198 |   });
199 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at D:/a/bun/bun/test/js/bun/resolve/resolve.test.ts:199:3
      at D:/a/bun/bun/test/js/bun/resolve/resolve.test.ts:187:81
✗ file url with special characters not encoded in import statement resolves [64.81ms]


209 |   const { exitCode, stdout } = Bun.spawnSync({
210 |     cmd: [bunExe(), `${dir}/test.js`],
211 |     env: bunEnv,
212 |     cwd: import.meta.dir,
213 |   });
214 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at D:/a/bun/bun/test/js/bun/resolve/resolve.test.ts:214:3
      at D:/a/bun/bun/test/js/bun/resolve/resolve.test.ts:203:36
✗ file url in require resolves [71.37ms]


228 |   const { exitCode, stdout } = Bun.spawnSync({
229 |     cmd: [bunExe(), `${dir}/test.js`],
230 |     env: bunEnv,
231 |     cwd: import.meta.dir,
232 |   });
233 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at D:/a/bun/bun/test/js/bun/resolve/resolve.test.ts:233:3
      at D:/a/bun/bun/test/js/bun/resolve/resolve.test.ts:218:60
✗ file url with special characters in require resolves [68.46ms]


243 |   const { exitCode, stdout } = Bun.spawnSync({
244 |     cmd: [bunExe(), `${dir}/test.js`],
245 |     env: bunEnv,
246 |     cwd: import.meta.dir,
247 |   });
248 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at D:/a/bun/bun/test/js/bun/resolve/resolve.test.ts:248:3
      at D:/a/bun/bun/test/js/bun/resolve/resolve.test.ts:237:44
✗ file url in require.resolve resolves [67.11ms]


264 |   const { exitCode, stdout } = Bun.spawnSync({
265 |     cmd: [bunExe(), `${dir}/test.js`],
266 |     env: bunEnv,
267 |     cwd: import.meta.dir,
268 |   });
269 |   expect(exitCode).toBe(0);
        ^
error: expect(received).toBe(expected)

Expected: 0
Received: 1

      at D:/a/bun/bun/test/js/bun/resolve/resolve.test.ts:269:3
      at D:/a/bun/bun/test/js/bun/resolve/resolve.test.ts:252:60
✗ file url with special characters in require resolves [60.51ms]
✓ import long string should not segfault [3.74ms]
✓ import long string should not segfault [2.45ms]
✓ import long string should not segfault [2.32ms]
✓ import long string should not segfault [3.86ms]
✓ import override to node builtin [1.90ms]
✓ import override to bun [1.68ms]
✎ import override to bun:test



 7 pass
 1 todo
 11 fail
 15 expect() calls
Ran 19 tests across 1 files. [905.00ms]
```

**Comment by nektro** [comment]
all files except `bun-debug test test/js/third_party/svelte/svelte.test.ts` pass now
