### ISSUE TITLE
LightMyRequest: undefined is not an object (evaluating 'response._header.match')

### ISSUE THREAD

**Issue by psteinroe** [oven-sh/bun#8358]
### What version of Bun is running?

latest

### What platform is your computer?

I am running the ci on macOS and ubuntu.

### What steps can reproduce the bug?

bun is still not supporting light my request. check out [this pr](https://github.com/psteinroe/fastify-supabase/pull/11) for a reproduction. 

its related to #7485 I think. 

 ```
 172 |   response._lightMyRequest.headers = Object.assign({}, response.getHeaders())
  173 | 
  174 |   // Add raw headers
  175 |   ;['Date', 'Connection', 'Transfer-Encoding'].forEach((name) => {
  176 |     const regex = new RegExp('\\r\\n' + name + ': ([^\\r]*)\\r\\n')
  177 |     const field = response._header.match(regex)
                          ^
  TypeError: undefined is not an object (evaluating 'response._header.match')
        at /home/runner/work/fastify-supabase/fastify-supabase/node_modules/light-my-request/lib/response.js:177:19
        at forEach (:1:21)
        at copyHeaders (/home/runner/work/fastify-supabase/fastify-supabase/node_modules/light-my-request/lib/response.js:175:4)
        at /home/runner/work/fastify-supabase/fastify-supabase/node_modules/light-my-request/lib/response.js:65:3
        at /home/runner/work/fastify-supabase/fastify-supabase/node_modules/fastify/lib/error-handler.js:42:9
        at fallbackErrorHandler (/home/runner/work/fastify-supabase/fastify-supabase/node_modules/fastify/lib/error-handler.js:127:3)
        at handleError (/home/runner/work/fastify-supabase/fastify-supabase/node_modules/fastify/lib/error-handler.js:34:5)
        at onErrorHook (/home/runner/work/fastify-supabase/fastify-supabase/node_modules/fastify/lib/reply.js:777:5)
        at /home/runner/work/fastify-supabase/fastify-supabase/node_modules/fastify/lib/reply.js:145:5
        at preValidationCallback (/home/runner/work/fastify-supabase/fastify-supabase/node_modules/fastify/lib/handleRequest.js:87:5)
```

**Comment by jdalton** [comment]
PR https://github.com/oven-sh/bun/pull/7659

**Comment by isnifer** [comment]
@jdalton any chance to push forward this issue via "native code" as Jarred said? Almost a year of waiting for a chance to try bun in production 🥹

**Comment by fdaciuk** [comment]
This issue is fixed in Bun 1.1.34 🥰

**Comment by isnifer** [comment]
@fdaciuk sadly, but it's not true.

```
# Unhandled error between tests
-------------------------------
177 |   response._lightMyRequest.headers = Object.assign({}, response.getHeaders())
178 |
179 |   // Add raw headers
180 |   ;['Date', 'Connection', 'Transfer-Encoding'].forEach((name) => {
181 |     const regex = new RegExp('\\r\\n' + name + ': ([^\\r]*)\\r\\n')
182 |     const field = response._header.match(regex)
                                 ^
TypeError: undefined is not an object (evaluating 'response._header.match')
      at /PATH/TO/PROJECT/node_modules/light-my-request/lib/response.js:182:28
      at forEach (1:11)
      at copyHeaders (/PATH/TO/PROJECT/node_modules/light-my-request/lib/response.js:180:48)
      at /PATH/TO/PROJECT/node_modules/light-my-request/lib/response.js:65:3
      at /PATH/TO/PROJECT/node_modules/fastify/lib/error-handler.js:45:19
      at fallbackErrorHandler (/PATH/TO/PROJECT/node_modules/fastify/lib/error-handler.js:140:3)
      at handleError (/PATH/TO/PROJECT/node_modules/fastify/lib/error-handler.js:35:5)
      at onErrorHook (/PATH/TO/PROJECT/node_modules/fastify/lib/reply.js:803:5)
      at /PATH/TO/PROJECT/node_modules/fastify/lib/reply.js:137:5
      at /PATH/TO/PROJECT/node_modules/fastify/lib/wrapThenable.js:65:13
      at /PATH/TO/PROJECT/src/routes/v1/auth/refreshToken.test.ts:8:1
```

**Comment by fdaciuk** [comment]
@isnifer are you trying to use `app.inject()` from Fastify? In my tests everything is working fine. Can you share your code?

**Comment by psteinroe** [comment]
@fdaciuk you can check the [failing ci](https://github.com/psteinroe/fastify-supabase/actions/runs/11664692985/job/32475749518) on [this branch](https://github.com/psteinroe/fastify-supabase/pull/11).

**Comment by isnifer** [comment]
@fdaciuk nothing especial:

```ts
const authRequest = await app.inject({
  method: 'POST',
  url: 'v1/auth/login',
  body: JSON.stringify({
    email: process.env.TEST_USERNAME,
    password: process.env.TEST_PASSWORD,
  }),
})

const authToken = JSON.parse(authRequest.body).token
```

**Comment by fdaciuk** [comment]
I ran locally and the tests passed 🤔 

![Image](https://github.com/user-attachments/assets/ab69108b-28ad-459c-9de4-d7b88175c5ff)

Maybe the error could be because of cache?

![Image](https://github.com/user-attachments/assets/7a03203f-52f9-47c3-b6f2-e9219de27e6f)

**Comment by fdaciuk** [comment]
Ah, sorry. I remove the `.skip` in tests and looks like the issue is still there :(

**Comment by liu-ronny** [comment]
Can confirm, it still doesn't work for me either.

```
177 |   response._lightMyRequest.headers = Object.assign({}, response.getHeaders())
178 | 
179 |   // Add raw headers
180 |   ;['Date', 'Connection', 'Transfer-Encoding'].forEach((name) => {
181 |     const regex = new RegExp('\\r\\n' + name + ': ([^\\r]*)\\r\\n')
182 |     const field = response._header.match(regex)
                                 ^
TypeError: undefined is not an object (evaluating 'response._header.match')
      at /test/node_modules/light-my-request/lib/response.js:182:28
      at forEach (1:11)
      at copyHeaders (/test/node_modules/light-my-request/lib/response.js:180:48)
      at /test/node_modules/light-my-request/lib/response.js:65:3
      at /test/node_modules/fastify/lib/error-handler.js:45:19
      at fallbackErrorHandler (/test/node_modules/fastify/lib/error-handler.js:140:3)
      at handleError (/test/node_modules/fastify/lib/error-handler.js:35:5)
      at onErrorHook (/test/node_modules/fastify/lib/reply.js:803:5)
      at /test/node_modules/fastify/lib/reply.js:137:5
      at preValidationCallback (/test/node_modules/fastify/lib/handleRequest.js:85:11)

Bun v1.1.34 (macOS x64)
```

**Comment by RajaShanmugamJM** [comment]
I'm on mac using hapi framework and I'm running into same issue

<img width="857" alt="Image" src="https://github.com/user-attachments/assets/98173cb8-4c30-4cfe-9235-77320813eb65" />

<img width="853" alt="Image" src="https://github.com/user-attachments/assets/fb1c0c93-e958-4f63-853d-58653f463031" />

**Comment by igorls** [comment]
https://github.com/oven-sh/bun/pull/27338
