### ISSUE TITLE
`serve` http server crashing with expected sink instead of continuing to run

### ISSUE THREAD

**Issue by simylein** [oven-sh/bun#8404]
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

```ts
import EventEmitter from 'events';
import { debug, info } from '../logger/logger';

export const emitter = new EventEmitter();
emitter.setMaxListeners(2048);

export const subscribe = (req: Request, channel: string): Response => {
	info(`subscribing to channel '${channel}'`);
	return new Response(
		new ReadableStream({
			type: 'direct',
			pull(controller: ReadableStreamDirectController) {
				let id = +(req.headers.get('last-event-id') ?? 1);
				const handler = async (data: unknown): Promise<void> => {
					await controller.write(`id:${id}\ndata:${data !== undefined ? JSON.stringify(data) : ''}\n\n`);
					await controller.flush();
					id++;
				};
				emitter.on(channel, handler);
				req.signal.onabort = () => {
					info(`unsubscribing from channel '${channel}'`);
					emitter.off(channel, handler);
					controller.close();
				};
				return new Promise(() => void 0);
			},
		}),
		{
			status: 200,
			headers: { 'content-type': 'text/event-stream;charset=utf-8' },
		},
	);
};

export const emit = (channel: string, data?: unknown): void => {
	debug(`emitting to channel '${channel}'`);
	emitter.emit(channel, data);
};
```

### What is the expected behavior?

The server should log errors but not crash

```log
[simylein] (prod) 12:55:39 info: subscribing to channel 'metrics'
[simylein] (prod) 12:55:41 info: unsubscribing from channel 'metrics'
11 |                    type: 'direct',
12 |                    pull(controller: ReadableStreamDirectController) {
13 |                            let id = +(req.headers.get('last-event-id') ?? 1);
14 |                            const handler = async (data: unknown): Promise<void> => {
15 |                                    await controller.write(`id:${id}\ndata:${data !== undefined ? JSON.stringify(data) : ''}\n\n`);
16 |                                    await controller.flush();
                ^
TypeError: Expected Sink
 code: "ERR_INVALID_THIS"

      at /lib/event/event.ts:16:12
```

### What do you see instead?

The server crashes

```log
[simylein] (prod) 12:49:57 info: subscribing to channel 'metrics'
[simylein] (prod) 12:49:59 info: unsubscribing from channel 'metrics'
12 |                    pull(controller: ReadableStreamDirectController) {
13 |                            let id = +(req.headers.get('last-event-id') ?? 1);
14 |                            const handler = async (data: unknown): Promise<void> => {
15 |                                    console.log('handle');
16 |                                    await controller.write(`id:${id}\ndata:${data !== undefined ? JSON.stringify(data) : ''}\n\n`);
17 |                                    await controller.flush();
                ^
TypeError: Expected Sink
 code: "ERR_INVALID_THIS"

      at /lib/event/event.ts:17:12
error: script "start:prod" exited with code 1
```

### Additional information

This is really an issue on production since it brings down the http server. This bug appears since bun versions 1.0.23. Version 1.0.22 and before do not have this issue

**Comment by simylein** [comment]
Also if I remove the `controller.close();` in the abort signal, the underlying problem gets fixed. 
However I would like to know if this produces a memory leak or if bun is closing aborted readable streams by default. 
Since we still have no official docs for doing server sent events (#2663), I would need some advice for how to do that.

**Comment by Jarred-Sumner** [comment]
Bun is detaching the direct ReadableStream when the request is cancelled. This is a bug though, it should just return 0 written every time instead of throwing ERR_INVALID_THIS.

**Comment by paperdave** [comment]
The error message in this will change in #15234. i cannot reproduce this on linux and macOS.
