### ISSUE TITLE
[windows] More module resolution errors

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#8410]
```ts
bun test v1.0.25-canary.20 (40aff0d4)


✓ bundler > ts/DeclareConst [68.96ms]
✓ bundler > ts/DeclareLet [39.89ms]
✓ bundler > ts/DeclareVar [41.43ms]
✓ bundler > ts/DeclareClass [32.81ms]
✓ bundler > ts/DeclareClassFields [129.14ms]
✓ bundler > ts/DeclareFunction [32.44ms]
✓ bundler > ts/DeclareNamespace [40.63ms]
✓ bundler > ts/DeclareEnum [39.92ms]
✓ bundler > ts/DeclareConstEnum [38.61ms]
✎ bundler > ts/ConstEnumComments
✓ bundler > ts/ImportEmptyNamespace [95.79ms]


756 |                 errorsLeft.splice(i, 1);
757 |               }
758 |             }
759 | 
760 |             if (unexpectedErrors.length) {
761 |               throw new Error(
                          ^
error: Unexpected errors reported while bundling:
undefined: No matching export in "foo.js" for import "default"
undefined: No matching export in "foo.js" for import "y"

Expected errors:
/entry.ts: No matching export in "foo.js" for import "default"
/entry.ts: No matching export in "foo.js" for import "y"
      at D:\a\bun\bun\test\bundler\expectBundled.ts:761:21
      at D:\a\bun\bun\test\bundler\expectBundled.ts:443:11
✗ bundler > ts/ImportMissingES6 [30.69ms]
✓ bundler > ts/ImportMissingUnusedES6 [1868.47ms]
✎ bundler > ts/ExportMissingES6


756 |                 errorsLeft.splice(i, 1);
757 |               }
758 |             }
759 | 
760 |             if (unexpectedErrors.length) {
761 |               throw new Error(
                          ^
error: Unexpected errors reported while bundling:
undefined: Could not resolve: "./doesNotExist.ts"

Expected errors:
/entry.ts: Could not resolve: "./doesNotExist.ts"
      at D:\a\bun\bun\test\bundler\expectBundled.ts:761:21
      at D:\a\bun\bun\test\bundler\expectBundled.ts:443:11
✗ bundler > ts/ImportMissingFile [35.41ms]
✓ bundler > ts/ImportTypeOnlyFile [87.54ms]
✓ bundler > ts/ExportEquals [93.27ms]
✓ bundler > ts/ExportNamespace [88.15ms]
✎ bundler > ts/MinifyEnum
✎ bundler > ts/MinifyEnumExported
✓ bundler > ts/MinifyNestedEnum [52.35ms]
✓ bundler > ts/MinifyNamespace [50.02ms]
✓ bundler > ts/MinifyDerivedClass [106.65ms]
✓ bundler > ts/ImportVsLocalCollisionAllTypes [86.10ms]
✓ bundler > ts/ImportVsLocalCollisionMixed [89.81ms]
✎ bundler > ts/ImportEqualsEliminationTest
✓ bundler > ts/ImportEqualsTreeShakingFalse [33.77ms]
✎ bundler > ts/ImportEqualsTreeShakingTrue
✎ bundler > ts/ImportEqualsBundle
✓ bundler > ts/MinifiedBundleES6 [90.47ms]
✓ bundler > ts/MinifiedBundleCommonJS [97.29ms]
✓ bundler > ts/TypeScriptDecoratorsSimpleCase [96.76ms]
✎ bundler > ts/TypeScriptDecorators
✓ bundler > ts/TypeScriptDecoratorScopeESBuildIssue2147 [33.70ms]


483 | 
484 |     // Prepare source folder
485 |     if (existsSync(root)) {
486 |       rmSync(root, { recursive: true });
487 |     }
488 |     mkdirSync(root, { recursive: true });
          ^
ENOENT: No such file or directory
   errno: -2
 syscall: "mkdir"
   path: "C:\Users\RUNNER~1\AppData\Local\Temp\bun-build-tests\bun-u8jHbm\ts\ExportType*"

      at D:\a\bun\bun\test\bundler\expectBundled.ts:488:5
      at D:\a\bun\bun\test\bundler\expectBundled.ts:443:11
✗ bundler > ts/ExportType* [1.70ms]
✓ bundler > ts/ExportDefaultTypeESBuildIssue316 [141.06ms]
✓ bundler > ts/ImplicitExtensions [113.55ms]


756 |                 errorsLeft.splice(i, 1);
757 |               }
758 |             }
759 | 
760 |             if (unexpectedErrors.length) {
761 |               throw new Error(
                          ^
error: Unexpected errors reported while bundling:
undefined: Could not resolve: "./mjs.mjs"
undefined: Could not resolve: "./cjs.cjs"
undefined: Could not resolve: "./js.js"
undefined: Could not resolve: "./jsx.jsx"

Expected errors:
/entry.ts: Could not resolve: "./mjs.mjs"
/entry.ts: Could not resolve: "./cjs.cjs"
/entry.ts: Could not resolve: "./js.js"
/entry.ts: Could not resolve: "./jsx.jsx"
      at D:\a\bun\bun\test\bundler\expectBundled.ts:761:21
      at D:\a\bun\bun\test\bundler\expectBundled.ts:443:11
✗ bundler > ts/ImplicitExtensionsMissing [48.93ms]
✓ bundler > ts/ExportTypeESBuildIssue379 [111.84ms]
✓ bundler > ts/ThisInsideFunctionTS [113.93ms]
✓ bundler > ts/ThisInsideFunctionTSUseDefineForClassFields [110.00ms]
✓ bundler > ts/ThisInsideFunctionTSNoBundle [109.01ms]
✓ bundler > ts/ThisInsideFunctionTSNoBundleUseDefineForClassFields [152.58ms]
✎ bundler > ts/ComputedClassFieldUseDefineFalse
✎ bundler > ts/ComputedClassFieldUseDefineTrue
✎ bundler > ts/AbstractClassFieldUseAssign
✓ bundler > ts/AbstractClassFieldUseDefine [31.74ms]
✎ bundler > ts/ImportMTS
✓ bundler > ts/ImportCTS [90.29ms]
✓ bundler > ts/SideEffectsFalseWarningTypeDeclarations [93.79ms]
✎ bundler > ts/SiblingNamespaceLet
✎ bundler > ts/SiblingNamespaceFunction
✎ bundler > ts/SiblingNamespaceClass
✎ bundler > ts/SiblingNamespaceNamespace
✎ bundler > ts/SiblingNamespaceEnum
✎ bundler > ts/SiblingEnum
✎ bundler > ts/EnumTreeShaking
✎ bundler > ts/EnumJSX
✎ bundler > ts/EnumDefine
✎ bundler > ts/EnumSameModuleInliningAccess
✎ bundler > ts/EnumCrossModuleInliningAccess
✎ bundler > ts/EnumCrossModuleInliningDefinitions
✎ bundler > ts/EnumCrossModuleInliningReExport
✎ bundler > ts/EnumCrossModuleTreeShaking
✎ bundler > ts/EnumExportClause
✓ bundler > ts/EnumRulesFrom_TypeScript_5_0 [156.92ms]
✎ bundler > ts/EnumUseBeforeDeclare



28 tests todo:
✎ bundler > ts/ConstEnumComments
✎ bundler > ts/ExportMissingES6
✎ bundler > ts/MinifyEnum
✎ bundler > ts/MinifyEnumExported
✎ bundler > ts/ImportEqualsEliminationTest
✎ bundler > ts/ImportEqualsTreeShakingTrue
✎ bundler > ts/ImportEqualsBundle
✎ bundler > ts/TypeScriptDecorators
✎ bundler > ts/ComputedClassFieldUseDefineFalse
✎ bundler > ts/ComputedClassFieldUseDefineTrue
✎ bundler > ts/AbstractClassFieldUseAssign
✎ bundler > ts/ImportMTS
✎ bundler > ts/SiblingNamespaceLet
✎ bundler > ts/SiblingNamespaceFunction
✎ bundler > ts/SiblingNamespaceClass
✎ bundler > ts/SiblingNamespaceNamespace
✎ bundler > ts/SiblingNamespaceEnum
✎ bundler > ts/SiblingEnum
✎ bundler > ts/EnumTreeShaking
✎ bundler > ts/EnumJSX
✎ bundler > ts/EnumDefine
✎ bundler > ts/EnumSameModuleInliningAccess
✎ bundler > ts/EnumCrossModuleInliningAccess
✎ bundler > ts/EnumCrossModuleInliningDefinitions
✎ bundler > ts/EnumCrossModuleInliningReExport
✎ bundler > ts/EnumCrossModuleTreeShaking
✎ bundler > ts/EnumExportClause
✎ bundler > ts/EnumUseBeforeDeclare


4 tests failed:
✗ bundler > ts/ImportMissingES6 [30.69ms]
✗ bundler > ts/ImportMissingFile [35.41ms]
✗ bundler > ts/ExportType* [1.70ms]
✗ bundler > ts/ImplicitExtensionsMissing [48.93ms]

 35 pass
 28 todo
 4 fail
 18 expect() calls
Ran 67 tests across 1 files. [4.86s]
```

```ts
bun test v1.0.25-canary.20 (40aff0d4)


✎ bundler > tsconfig/Paths
✎ bundler > tsconfig/PathsNoBaseURL
✎ bundler > tsconfig/BadPathsNoBaseURL
✓ bundler > tsconfig/PathsOverriddenBaseURL [130.60ms]
✓ bundler > tsconfig/PathsOverriddenBaseURLDifferentDir [114.81ms]


756 |                 errorsLeft.splice(i, 1);
757 |               }
758 |             }
759 | 
760 |             if (unexpectedErrors.length) {
761 |               throw new Error(
                          ^
error: Unexpected errors reported while bundling:
undefined: Could not resolve: "#/test". Maybe you need to "bun install"?

Expected errors:
/Users/user/project/src/entry.ts: Could not resolve: "#/test". Maybe you need to "bun install"?
      at D:\a\bun\bun\test\bundler\expectBundled.ts:761:21
      at D:\a\bun\bun\test\bundler\expectBundled.ts:443:11
✗ bundler > tsconfig/PathsMissingBaseURL [58.32ms]
✓ bundler > tsconfig/JSX [51.73ms]
✓ bundler > tsconfig/ReactJSXNotReact [57.38ms]
✓ bundler > tsconfig/ReactJSXNotReactScoped [59.22ms]
✓ bundler > tsconfig/ReactJSXDevNotReact [53.12ms]
✓ bundler > tsconfig/ReactJSXDev [60.57ms]
✓ bundler > tsconfig/ReactJSXDevTSConfigProduction [53.36ms]
✓ bundler > tsconfig/ReactJSX [49.62ms]
✓ bundler > tsconfig/ReactJSXClassic [59.99ms]
✓ bundler > tsconfig/ReactJSXClassicWithNODE_ENV=Production [49.63ms]
✓ bundler > tsconfig/ReactJSXClassicWithNODE_ENV=Development [60.60ms]



 12 pass
 3 todo
 1 fail
 15 expect() calls
Ran 16 tests across 1 files. [948.00ms]
```

**Comment by paperclover** [comment]
these tests pass now
