### ISSUE TITLE
[windows] why isn't BigInt a constructor?

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#8414]
Please don't let yourself get stuck on this one for long and instead move on to the next one if it's not immediately obvious

```ts
bun-debug test test\js\bun\test\expect.test.js
```

```ts
bun test v1.0.25-canary.20 (40aff0d4)


✓ expect() > BigInt > compares correctly (literal) [1.52ms]
✓ expect() > BigInt > compares correctly (object) [4.89ms]
✓ expect() > deepEquals with asymmetric matchers > should accept any string [8.46ms]
✓ expect() > deepEquals with asymmetric matchers > should accept any number [9.84ms]
✓ expect() > deepEquals with asymmetric matchers > should accept any boolean [6.07ms]


605 | 
606 |       function g() {
607 |         return 32;
608 |       }
609 |       Object.defineProperty(g, "name", { value: "BigInt" });
610 |       expect({ a: 123n }).toEqual({ a: expect.any(BigInt) });
                                             ^
error: expect.any(constructor)

Expected a constructor

      at D:\a\bun\bun\test\js\bun\test\expect.test.js:610:40
✗ expect() > deepEquals with asymmetric matchers > should not match the wrong constructors [10.53ms]
✓ expect() > toMatchObject > with Bun.deepMatch [1.46ms]


2992 |               string1: expect.anything(),
2993 |               string2: expect.stringContaining("ll"),
2994 |               string3: expect.stringMatching(/ll/),
2995 |               d: {
2996 |                 e: {
2997 |                   bigint: expect.any(BigInt),
                                 ^
error: expect.any(constructor)

Expected a constructor

      at D:\a\bun\bun\test\js\bun\test\expect.test.js:2997:27
✗ expect() > toMatchObject > with expect matcher [204.07ms]
✓ expect() > toMatch() > reguler expression [1.34ms]
✓ expect() > toMatch() > reguler expression object [1.44ms]
✓ expect() > toMatch() > substring [0.89ms]
✓ expect() > toMatch() > substring emojis [0.03ms]
✓ expect() > toMatch() > substring UTF-16 [0.02ms]
✓ expect() > toBeEmpty() > "" [0.13ms]
✓ expect() > toBeEmpty() > [] [0.04ms]
✓ expect() > toBeEmpty() > {} [0.05ms]
✓ expect() > toBeEmpty() > new Set() [0.04ms]
✓ expect() > toBeEmpty() > new Map() [0.04ms]
✓ expect() > toBeEmpty() > new String() [0.03ms]
✓ expect() > toBeEmpty() > new Array() [0.04ms]
✓ expect() > toBeEmpty() > new Uint8Array() [0.04ms]
✓ expect() > toBeEmpty() > new Object() [0.04ms]
✓ expect() > toBeEmpty() > Buffer.from("") [0.04ms]
✓ expect() > toBeEmpty() > new Headers() [0.04ms]
✓ expect() > toBeEmpty() > new URLSearchParams() [0.05ms]
✓ expect() > toBeEmpty() > new FormData() [0.06ms]
✓ expect() > toBeEmpty() > (function* () {})() [1.85ms]
✓ expect() > toBeEmpty() > Bun.file() [11.48ms]
✓ expect() > not.toBeEmpty() > " " [0.09ms]
✓ expect() > not.toBeEmpty() > [""] [0.05ms]
✓ expect() > not.toBeEmpty() > [undefined] [0.04ms]
✓ expect() > not.toBeEmpty() > { "": "" } [1.25ms]
✓ expect() > not.toBeEmpty() > new Set([""]) [0.92ms]
✓ expect() > not.toBeEmpty() > new Map([["", ""]]) [0.03ms]
✓ expect() > not.toBeEmpty() > new String(" ") [0.04ms]
✓ expect() > not.toBeEmpty() > new Array(1) [0.04ms]
✓ expect() > not.toBeEmpty() > new Uint8Array(1) [0.05ms]
✓ expect() > not.toBeEmpty() > Buffer.from(" ") [0.05ms]
✓ expect() > not.toBeEmpty() > new Headers({...}) [0.05ms]
✓ expect() > not.toBeEmpty() > URL.searchParams [0.05ms]
✓ expect() > not.toBeEmpty() > FormData [0.05ms]
✓ expect() > not.toBeEmpty() > generator function [1.03ms]
✓ expect() > not.toBeEmpty() > Bun.file() [0.94ms]
✓ expect() > asymmetric matchers > closeTo > 0 closeTo 0 return true [2.38ms]
✓ expect() > asymmetric matchers > closeTo > 0 notCloseTo 0 return false [1.66ms]
✓ expect() > asymmetric matchers > closeTo > 0 closeTo 0.001 return true [1.83ms]
✓ expect() > asymmetric matchers > closeTo > 0 notCloseTo 0.001 return false [2.04ms]
✓ expect() > asymmetric matchers > closeTo > 1.23 closeTo 1.229 return true [2.31ms]
✓ expect() > asymmetric matchers > closeTo > 1.23 notCloseTo 1.229 return false [2.28ms]
✓ expect() > asymmetric matchers > closeTo > 1.23 closeTo 1.226 return true [2.29ms]
✓ expect() > asymmetric matchers > closeTo > 1.23 notCloseTo 1.226 return false [2.15ms]
✓ expect() > asymmetric matchers > closeTo > 1.23 closeTo 1.225 return true [2.26ms]
✓ expect() > asymmetric matchers > closeTo > 1.23 notCloseTo 1.225 return false [1.57ms]
✓ expect() > asymmetric matchers > closeTo > 1.23 closeTo 1.234 return true [2.51ms]
✓ expect() > asymmetric matchers > closeTo > 1.23 notCloseTo 1.234 return false [2.34ms]
✓ expect() > asymmetric matchers > closeTo > Infinity closeTo Infinity return true [1.81ms]
✓ expect() > asymmetric matchers > closeTo > Infinity notCloseTo Infinity return false [1.64ms]
✓ expect() > asymmetric matchers > closeTo > -Infinity closeTo -Infinity return true [2.21ms]
✓ expect() > asymmetric matchers > closeTo > -Infinity notCloseTo -Infinity return false [1.76ms]
✓ expect() > asymmetric matchers > closeTo > 0 closeTo 0.01 return false [2.01ms]
✓ expect() > asymmetric matchers > closeTo > 0 notCloseTo 0.01 return true [2.19ms]
✓ expect() > asymmetric matchers > closeTo > 1 closeTo 1.23 return false [2.02ms]
✓ expect() > asymmetric matchers > closeTo > 1 notCloseTo 1.23 return true [2.07ms]
✓ expect() > asymmetric matchers > closeTo > 1.23 closeTo 1.2249999 return false [1.98ms]
✓ expect() > asymmetric matchers > closeTo > 1.23 notCloseTo 1.2249999 return true [2.03ms]
✓ expect() > asymmetric matchers > closeTo > Infinity closeTo -Infinity return false [2.48ms]
✓ expect() > asymmetric matchers > closeTo > Infinity notCloseTo -Infinity return true [1.63ms]
✓ expect() > asymmetric matchers > closeTo > Infinity closeTo 1.23 return false [1.90ms]
✓ expect() > asymmetric matchers > closeTo > Infinity notCloseTo 1.23 return true [2.09ms]
✓ expect() > asymmetric matchers > closeTo > -Infinity closeTo -1.23 return false [2.27ms]
✓ expect() > asymmetric matchers > closeTo > -Infinity notCloseTo -1.23 return true [2.60ms]
✓ expect() > asymmetric matchers > closeTo > 0 closeTo 0.1 with precision 0 return true [1.62ms]
✓ expect() > asymmetric matchers > closeTo > 0 notCloseTo 0.1 with precision 0 return false [2.10ms]
✓ expect() > asymmetric matchers > closeTo > 0 closeTo 0.0001 with precision 3 return true [2.18ms]
✓ expect() > asymmetric matchers > closeTo > 0 notCloseTo 0.0001 with precision 3 return false [2.39ms]
✓ expect() > asymmetric matchers > closeTo > 0 closeTo 0.000004 with precision 5 return true [2.25ms]
✓ expect() > asymmetric matchers > closeTo > 0 notCloseTo 0.000004 with precision 5 return false [2.15ms]
✓ expect() > asymmetric matchers > closeTo > 2.0000002 closeTo 2 with precision 5 return true [1.94ms]
✓ expect() > asymmetric matchers > closeTo > 2.0000002 notCloseTo 2 with precision 5 return false [2.00ms]
✓ expect() > asymmetric matchers > closeTo > 3.141592e-7 closeTo 3e-7 with precision 8 return false [1.64ms]
✓ expect() > asymmetric matchers > closeTo > 3.141592e-7 notCloseTo 3e-7 with precision 8 return true [1.76ms]
✓ expect() > asymmetric matchers > closeTo > 56789 closeTo 51234 with precision -4 return false [2.03ms]
✓ expect() > asymmetric matchers > closeTo > 56789 notCloseTo 51234 with precision -4 return true [2.50ms]
✓ expect() > asymmetric matchers > closeTo > closeTo throw if expected is not number [1.70ms]
✓ expect() > asymmetric matchers > closeTo > notCloseTo throw if expected is not number [0.98ms]
✓ expect() > asymmetric matchers > closeTo > closeTo throw if precision is not number [0.11ms]
✓ expect() > asymmetric matchers > closeTo > notCloseTo throw if precision is not number [0.13ms]
✓ expect() > asymmetric matchers > closeTo > closeTo return false if received is not number [2.03ms]
✓ expect() > asymmetric matchers > closeTo > notCloseTo return false if received is not number [1.98ms]


3513 | 
3514 |       expect(expect.any(String)).toEqual("jest");
3515 |       expect(expect.any(Number)).toEqual(1);
3516 |       expect(expect.any(Function)).toEqual(() => {});
3517 |       expect(expect.any(Boolean)).toEqual(true);
3518 |       expect(expect.any(BigInt)).toEqual(1n);
                    ^
error: expect.any(constructor)

Expected a constructor

      at D:\a\bun\bun\test\js\bun\test\expect.test.js:3518:14
✗ expect() > asymmetric matchers > expect.any [10.83ms]


3526 |     test("expect.any on primitive wrapper classes", () => {
3527 |       expect(expect.any(String)).toEqual(new String("jest"));
3528 |       expect(expect.any(Number)).toEqual(new Number(1));
3529 |       expect(expect.any(Function)).toEqual(new Function("() => {}"));
3530 |       expect(expect.any(Boolean)).toEqual(new Boolean(true));
3531 |       expect(expect.any(BigInt)).toEqual(Object(1n));
                    ^
error: expect.any(constructor)

Expected a constructor

      at D:\a\bun\bun\test\js\bun\test\expect.test.js:3531:14
✗ expect() > asymmetric matchers > expect.any on primitive wrapper classes [13.88ms]
✓ expect() > asymmetric matchers > Any throws when called with empty constructor [2.54ms]
✓ expect() > asymmetric matchers > Anything matches any type [13.58ms]
✓ expect() > asymmetric matchers > Anything does not match null and undefined [4.75ms]
✓ expect() > asymmetric matchers > ArrayContaining matches [10.02ms]
✓ expect() > asymmetric matchers > ArrayContaining does not match [14.11ms]
✓ expect() > asymmetric matchers > ArrayContaining throws for non-arrays [2.14ms]
✓ expect() > asymmetric matchers > ArrayNotContaining matches [13.61ms]
✓ expect() > asymmetric matchers > ArrayNotContaining does not match [7.84ms]
✓ expect() > asymmetric matchers > ArrayNotContaining throws for non-arrays [1.75ms]
✓ expect() > asymmetric matchers > ObjectContaining matches [15.98ms]
✓ expect() > asymmetric matchers > ObjectContaining does not match [40.10ms]
✓ expect() > asymmetric matchers > ObjectContaining matches defined properties [3.89ms]
✓ expect() > asymmetric matchers > ObjectContaining matches prototype properties [4.08ms]
✓ expect() > asymmetric matchers > ObjectContaining throws for non-objects [1.69ms]
✓ expect() > asymmetric matchers > ObjectContaining does not mutate the sample [4.05ms]
✓ expect() > asymmetric matchers > ObjectNotContaining matches [33.05ms]
✓ expect() > asymmetric matchers > ObjectNotContaining does not match [15.21ms]
✓ expect() > asymmetric matchers > ObjectNotContaining inverts ObjectContaining [74.99ms]
✓ expect() > asymmetric matchers > ObjectNotContaining throws for non-objects [2.25ms]
✓ expect() > asymmetric matchers > StringContaining matches string against string [3.76ms]
✓ expect() > asymmetric matchers > StringContaining throws if expected value is not string [2.80ms]
✓ expect() > asymmetric matchers > StringContaining returns false if received value is not string [2.10ms]
✓ expect() > asymmetric matchers > StringNotContaining matches string against string [3.72ms]
✓ expect() > asymmetric matchers > StringNotContaining throws if expected value is not string [2.02ms]
✓ expect() > asymmetric matchers > StringNotContaining returns true if received value is not string [2.10ms]
✓ expect() > asymmetric matchers > StringMatching matches string against regexp [3.37ms]
✓ expect() > asymmetric matchers > StringMatching matches string against string [4.05ms]
✓ expect() > asymmetric matchers > StringMatching throws if expected value is neither string nor regexp [2.68ms]
✓ expect() > asymmetric matchers > StringMatching returns false if received value is not string [1.58ms]
✓ expect() > asymmetric matchers > StringMatching returns false even if coerced non-string received value matches pattern [2.08ms]
✓ expect() > asymmetric matchers > StringNotMatching matches string against regexp [4.38ms]
✓ expect() > asymmetric matchers > StringNotMatching matches string against string [4.42ms]
✓ expect() > asymmetric matchers > StringNotMatching throws if expected value is neither string nor regexp [2.95ms]
✓ expect() > asymmetric matchers > StringNotMatching returns true if received value is not string [1.62ms]
✓ expect() > async asymmetric matching > expect.rejectsTo [20.94ms]
✓ expect() > async asymmetric matching > expect.resolvesTo [21.41ms]
✓ expect() > object matching > objectContaining, with nested object, containing full props/values [4.54ms]
✓ expect() > object matching > objectContaining, with nested object, containing partial props/values [4.59ms]
✓ expect() > object matching > objectContaining, with nested object, also declared with objectContaining, containing partial props/values [5.57ms]
✓ expect() > object matching > toMatchObject, with nested object, containing full props/values [3.62ms]
✓ expect() > object matching > toMatchObject, with nested object, containing partial props/values [2.73ms]
✓ expect() > object matching > Array of dates [1.39ms]
✓ expect() > () [4.77ms]
✓ expect() > rejects [16.80ms]
✓ expect() > resolves [15.18ms]
✓ expect() > can call without an argument [0.09ms]
✓ expect() > toStrictEqual() vs toEqual() [81.98ms]
✓ expect() > deepEquals regex [2.81ms]
✓ expect() > deepEquals works with accessors [6.28ms]
✓ expect() > deepEquals works with proxies [20.24ms]
✓ expect() > deepEquals works with sets/maps/dates/strings [30.31ms]
✓ expect() > toThrow [75.98ms]
✓ expect() > deepEquals derived strings and strings [2.55ms]
✓ expect() > deepEquals and typed arrays [8.54ms]
✓ expect() > deepEquals throw getters [16.07ms]
✓ expect() > deepEquals large object [28.34ms]
✓ expect() > deepEquals - Date [6.36ms]
✓ expect() > deepEquals toString and functions [1.02ms]
✓ expect() > deepEquals set and map [13.60ms]
✓ expect() > deepEquals - symbols [2.46ms]
✓ expect() > deepEquals should not segfault [6.74ms]
✓ expect() > deepEquals URLs [4.36ms]
✓ expect() > toEqual objects and arrays [99.87ms]
✓ expect() > symbol based keys in arrays are processed correctly [1.08ms]
✓ expect() > non-enumerable members should be skipped during equal [1.41ms]
✓ expect() > non-enumerable symbolic members should be skipped during equal [1.11ms]
✓ expect() > properties with the same circularity are equal [8.60ms]
✓ expect() > toEqual() - arrays [1.38ms]
✓ expect() > toEqual() - private class fields [1.93ms]
✓ expect() > properties with different circularity are not equal [9.46ms]
✓ expect() > are not equal if circularity is not on the same property [1.01ms]
✓ expect() > random isEqual tests [65.26ms]
✓ expect() > toHaveProperty() - emojis [4.27ms]
✓ expect() > toHaveProperty() - dot and bracket notation edge cases [61.36ms]
✓ expect() > toHaveProperty() - with string or array [87.93ms]
✓ expect() > toHaveProperty() - all [233.00ms]
✎ expect() > toHaveProperty() - null or undefined
✓ expect() > toBe() [2.55ms]
✓ expect() > toHaveLength() [9.96ms]
✓ expect() > toHaveLength() extended [24.41ms]
✓ expect() > expect("hello").toContain("h") [0.10ms]
✓ expect() > expect("hello").toContain("") [0.07ms]
✓ expect() > expect("hello").toContain("hello") [0.06ms]
✓ expect() > expect("hello").toContain("h") [1.11ms]
✓ expect() > expect("emoji: 😃").toContain("😃") [0.96ms]
✓ expect() > expect("😄").toContain("😄") [0.05ms]
✓ expect() > expect("").toContain("") [0.06ms]
✓ expect() > expect([ 1, 2, 3 ]).toContain(1) [0.06ms]
✓ expect() > expect([ "a", "b", "c" ]).toContain("c") [0.06ms]
✓ expect() > expect([ null, undefined ]).toContain(undefined) [0.06ms]
✓ expect() > expect([ 1n, "abc", null, -1n, undefined ]).toContain(-1n) [0.06ms]
✓ expect() > expect([ Symbol(a) ]).toContain(Symbol(a)) [0.05ms]
✓ expect() > expect(Set(3) {
  1,
  2,
  3,
}).toContain(1) [0.91ms]
✓ expect() > expect(Set(3) {
  "a",
  "b",
  "c",
}).toContain("c") [2.41ms]
✓ expect() > expect(Uint8Array(3) [ 1, 2, 3 ]).toContain(1) [1.00ms]
✓ expect() > expect(BigInt64Array(3) [ 1n, 2n, 3n ]).toContain(2n) [1.20ms]
✓ expect() > expect({
  [Symbol(Symbol.iterator)]: [Function: GeneratorFunction],
}).toContain(3) [2.80ms]
✓ expect() > expect("hello").not.toContain("a") [1.12ms]
✓ expect() > expect("hello").not.toContain("hello?") [0.07ms]
✓ expect() > expect("hello").not.toContain("a") [1.73ms]
✓ expect() > expect("hello").not.toContain("hello?") [2.32ms]
✓ expect() > expect("hello").not.toContain("hello") [2.22ms]
✓ expect() > expect("hello").not.toContain("llo") [2.17ms]
✓ expect() > expect("hello").not.toContain("") [2.10ms]
✓ expect() > expect("emoji: 😃").not.toContain("😄") [0.94ms]
✓ expect() > expect([ 1, 2, 3 ]).not.toContain(-1) [0.05ms]
✓ expect() > expect([ 1, 2, 3 ]).not.toContain(1n) [0.06ms]
✓ expect() > expect([ "a", "b", "c" ]).not.toContain("d") [0.06ms]
✓ expect() > expect([ Symbol(a) ]).not.toContain(Symbol(a)) [0.06ms]
✓ expect() > expect(Set(3) {
  1,
  2,
  3,
}).not.toContain(6) [0.90ms]
✓ expect() > expect(Set(3) {
  "a",
  "b",
  "c",
}).not.toContain("f") [2.11ms]
✓ expect() > expect(Uint8Array(3) [ 1, 2, 3 ]).not.toContain(0) [0.93ms]
✓ expect() > expect(BigInt64Array(3) [ 1n, 2n, 3n ]).not.toContain(1) [0.86ms]
✓ expect() > expect({
  [Symbol(Symbol.iterator)]: [Function: GeneratorFunction],
}).not.toContain(6) [2.59ms]
✓ expect() > expect("hello").toContainEqual("h") [1.73ms]
✓ expect() > expect("hello").toContainEqual("h") [0.05ms]
✓ expect() > expect("emoji: 😃").toContainEqual("😃") [0.06ms]
✓ expect() > expect("😄").toContainEqual("😄") [0.05ms]
✓ expect() > expect("😄").toContainEqual("😄") [0.06ms]
✓ expect() > expect([ 1, 2, 3 ]).toContainEqual(1) [0.05ms]
✓ expect() > expect([
  {
    a: 1,
  }, {
    b: 2,
  }, {
    c: 3,
  }
]).toContainEqual({
  c: 3,
}) [1.18ms]
✓ expect() > expect([
  {}
]).toContainEqual({}) [1.09ms]
✓ expect() > expect([ "a", "b", "c" ]).toContainEqual("c") [0.04ms]
✓ expect() > expect([
  [ 1, 2, 3 ], [ 4, 5, 6 ], [ 7, 8, 9 ]
]).toContainEqual([ 7, 8, 9 ]) [0.05ms]
✓ expect() > expect([ null, undefined ]).toContainEqual(undefined) [0.06ms]
✓ expect() > expect([ 1n, "abc", null, -1n, undefined ]).toContainEqual(-1n) [0.06ms]
✓ expect() > expect([ Symbol(a) ]).toContainEqual(Symbol(a)) [0.06ms]
✓ expect() > expect(Set(3) {
  1,
  2,
  3,
}).toContainEqual(1) [1.82ms]
✓ expect() > expect(Set(3) {
  [],
  {
    a: 1,
  },
  Headers {},
}).toContainEqual(Headers {}) [2.46ms]
✓ expect() > expect(Set(3) {
  "a",
  "b",
  "c",
}).toContainEqual("c") [1.87ms]
✓ expect() > expect(Set(1) {
  Map(1) {
    1: 2,
  },
}).toContainEqual(Map(1) {
  1: 2,
}) [1.97ms]
✓ expect() > expect(Uint8Array(3) [ 1, 2, 3 ]).toContainEqual(1) [1.98ms]
✓ expect() > expect(BigInt64Array(3) [ 1n, 2n, 3n ]).toContainEqual(2n) [0.94ms]
✓ expect() > expect({
  [Symbol(Symbol.iterator)]: [Function: GeneratorFunction],
}).toContainEqual({
  a: 1,
  b: Map {},
}) [2.70ms]
✓ expect() > expect("hello").not.toContainEqual("a") [1.32ms]
✓ expect() > expect("hello").not.toContainEqual("hello?") [0.04ms]
✓ expect() > expect("hello").not.toContainEqual("hello") [0.05ms]
✓ expect() > expect("hello").not.toContainEqual("llo") [0.06ms]
✓ expect() > expect("hello").not.toContainEqual("") [0.06ms]
✓ expect() > expect("").not.toContainEqual("") [0.06ms]
✓ expect() > expect("").not.toContainEqual("") [0.06ms]
✓ expect() > expect("hello").not.toContainEqual("a") [0.06ms]
✓ expect() > expect("hello").not.toContainEqual("hello?") [0.06ms]
✓ expect() > expect("hello").not.toContainEqual("hello") [0.06ms]
✓ expect() > expect("hello").not.toContainEqual("llo") [0.06ms]
✓ expect() > expect("hello").not.toContainEqual("") [0.06ms]
✓ expect() > expect("😄").not.toContainEqual("😄") [0.06ms]
✓ expect() > expect("1").not.toContainEqual("1") [0.06ms]
✓ expect() > expect("emoji: 😃").not.toContainEqual("😄") [0.06ms]
✓ expect() > expect([ 1, 2, 3 ]).not.toContainEqual(-1) [0.06ms]
✓ expect() > expect([
  {
    a: 1,
  }, {
    b: 2,
  }, {
    c: 3,
  }
]).not.toContainEqual({
  c: 1,
}) [1.05ms]
✓ expect() > expect([]).not.toContainEqual({}) [0.97ms]
✓ expect() > expect([
  {}, {
    a: 1,
  }
]).not.toContainEqual({
  d: 4,
}) [0.94ms]
✓ expect() > expect([ 1, 2, 3 ]).not.toContainEqual(1n) [1.05ms]
✓ expect() > expect([ "a", "b", "c" ]).not.toContainEqual("d") [0.04ms]
✓ expect() > expect([ Symbol(a) ]).not.toContainEqual(Symbol(a)) [0.05ms]
✓ expect() > expect(Set(3) {
  1,
  2,
  3,
}).not.toContainEqual(6) [1.36ms]
✓ expect() > expect(Set(3) {
  {
    a: 1,
  },
  {
    b: 2,
  },
  {
    c: 3,
  },
}).not.toContainEqual({
  d: 4,
}) [2.78ms]
✓ expect() > expect(Set {}).not.toContainEqual({}) [2.54ms]
✓ expect() > expect(Set(3) {
  "a",
  "b",
  "c",
}).not.toContainEqual("f") [2.54ms]
✓ expect() > expect(Uint8Array(3) [ 1, 2, 3 ]).not.toContainEqual(0) [0.89ms]
✓ expect() > expect(BigInt64Array(3) [ 1n, 2n, 3n ]).not.toContainEqual(1) [0.94ms]
✓ expect() > expect({
  [Symbol(Symbol.iterator)]: [Function: GeneratorFunction],
}).not.toContainEqual(6) [3.08ms]
✓ expect() > expect({
  [Symbol(Symbol.iterator)]: [Function: GeneratorFunction],
}).not.toContainEqual([ 1, 2, 4 ]) [2.77ms]
✓ expect() > expect({
  [Symbol(Symbol.iterator)]: [Function: GeneratorFunction],
}).not.toContainEqual({}) [2.99ms]
✓ expect() > toContainKey [2.04ms]
✓ expect() > toContainAnyKeys [14.76ms]
✓ expect() > toContainKeys [10.93ms]
✓ expect() > toBeTruthy() [5.99ms]
✓ expect() > toBeUndefined() [3.39ms]
✓ expect() > toBeNull() [0.21ms]
✓ expect() > toBeDefined() [0.17ms]
✓ expect() > toBeFalsy() [38.40ms]
✓ expect() > toBeGreaterThan() [36.75ms]
✓ expect() > toBeGreaterThanOrEqual() [23.87ms]
✓ expect() > toBeLessThan() [37.18ms]
✓ expect() > toBeLessThanOrEqual() [38.34ms]
✓ expect() > toBeNaN() [5.49ms]
✓ expect() > toBeEmptyObject() [16.74ms]
✓ expect() > toBeNil() [2.01ms]
✓ expect() > toBeTypeOf() [16.56ms]
✓ expect() > toBeBoolean() [1.59ms]
✓ expect() > toBeTrue() [0.25ms]
✓ expect() > toBeFalse() [0.23ms]
✓ expect() > toBeNumber() [0.29ms]
✓ expect() > toBeInteger() [0.29ms]
✓ expect() > toBeObject() [7.01ms]
✓ expect() > toBeFinite() [1.62ms]
✓ expect() > toBePositive() [0.28ms]
✓ expect() > toBeNegative() [0.25ms]
✓ expect() > toBeWithin() [0.32ms]
✓ expect() > toEqualIgnoringWhitespace() [4.29ms]
✓ expect() > toBeSymbol() [3.58ms]
✓ expect() > toBeFunction() [2.53ms]
✓ expect() > toBeDate() [2.37ms]
✓ expect() > toBeValidDate() [2.03ms]
✓ expect() > toBeString() [2.30ms]
✓ expect() > toInclude() [0.22ms]
✓ expect() > toStartWith() [0.24ms]
✓ expect() > toEndWith() [0.23ms]
✓ expect() > fail to return undefined [0.14ms]
✓ expect() > pass to return undefined [0.13ms]
✓ expect() > rejects to return undefined [1.29ms]
✓ expect() > resolves to return undefined [0.92ms]
✓ expect() > toBe to return undefined [0.14ms]
✓ expect() > toBeArray to return undefined [1.03ms]
✓ expect() > toBeArrayOfSize to return undefined [0.14ms]
✓ expect() > toBeBoolean to return undefined [0.13ms]
✓ expect() > toBeCloseTo to return undefined [0.13ms]
✓ expect() > toBeDate to return undefined [0.95ms]
✓ expect() > toBeDefined to return undefined [0.14ms]
✓ expect() > toBeEmpty to return undefined [0.13ms]
✓ expect() > toBeEven to return undefined [0.12ms]
✓ expect() > toBeFalse to return undefined [0.11ms]
✓ expect() > toBeFalsy to return undefined [0.10ms]
✓ expect() > toBeFinite to return undefined [0.09ms]
✓ expect() > toBeFunction to return undefined [1.42ms]
✓ expect() > toBeGreaterThan to return undefined [0.12ms]
✓ expect() > toBeGreaterThanOrEqual to return undefined [0.13ms]
✓ expect() > toBeInstanceOf to return undefined [3.51ms]
✓ expect() > toBeInteger to return undefined [0.14ms]
✓ expect() > toBeLessThan to return undefined [0.13ms]
✓ expect() > toBeLessThanOrEqual to return undefined [0.12ms]
✓ expect() > toBeNaN to return undefined [0.12ms]
✓ expect() > toBeNegative to return undefined [0.13ms]
✓ expect() > toBeNil to return undefined [0.12ms]
✓ expect() > toBeNull to return undefined [0.12ms]
✓ expect() > toBeNumber to return undefined [0.12ms]
✓ expect() > toBeOdd to return undefined [0.12ms]
✓ expect() > toBePositive to return undefined [0.12ms]
✓ expect() > toBeString to return undefined [0.12ms]
✓ expect() > toBeSymbol to return undefined [1.39ms]
✓ expect() > toBeTrue to return undefined [0.14ms]
✓ expect() > toBeTruthy to return undefined [0.13ms]
✓ expect() > toBeTypeOf to return undefined [0.13ms]
✓ expect() > toBeUndefined to return undefined [0.12ms]
✓ expect() > toBeWithin to return undefined [0.12ms]
✓ expect() > toContain to return undefined [1.00ms]
✎ expect() > toContainEqual to return undefined
✓ expect() > toEndWith to return undefined [0.13ms]
✓ expect() > toEqual to return undefined [0.12ms]
✓ expect() > toEqualIgnoringWhitespace to return undefined [0.12ms]
✓ expect() > toHaveBeenCalled to return undefined [0.15ms]
✓ expect() > toHaveBeenCalledTimes to return undefined [0.14ms]
✓ expect() > toHaveBeenCalledWith to return undefined [0.13ms]
✓ expect() > toHaveBeenLastCalledWith to return undefined [0.14ms]
✎ expect() > toHaveBeenNthCalledWith to return undefined
✎ expect() > toHaveLastReturnedWith to return undefined
✓ expect() > toHaveLength to return undefined [0.14ms]
✎ expect() > toHaveNthReturnedWith to return undefined
✎ expect() > toHaveProperty to return undefined
✎ expect() > toHaveReturnedTimes to return undefined
✎ expect() > toHaveReturnedWith to return undefined
✓ expect() > toInclude to return undefined [0.15ms]
✎ expect() > toIncludeRepeated to return undefined
✓ expect() > toMatch to return undefined [0.13ms]
✎ expect() > toMatchInlineSnapshot to return undefined
✓ expect() > toMatchObject to return undefined [1.03ms]
✓ expect() > toMatchSnapshot to return undefined [0.48ms]
✓ expect() > toSatisfy to return undefined [2.34ms]
✓ expect() > toStartWith to return undefined [0.14ms]
✓ expect() > toStrictEqual to return undefined [0.10ms]
✓ expect() > toThrow to return undefined [4.47ms]
✎ expect() > toThrowErrorMatchingInlineSnapshot to return undefined
✎ expect() > toThrowErrorMatchingSnapshot to return undefined
✓ expect() >  " " to contain "" [0.09ms]



12 tests todo:
✎ expect() > toHaveProperty() - null or undefined
✎ expect() > toContainEqual to return undefined
✎ expect() > toHaveBeenNthCalledWith to return undefined
✎ expect() > toHaveLastReturnedWith to return undefined
✎ expect() > toHaveNthReturnedWith to return undefined
✎ expect() > toHaveProperty to return undefined
✎ expect() > toHaveReturnedTimes to return undefined
✎ expect() > toHaveReturnedWith to return undefined
✎ expect() > toIncludeRepeated to return undefined
✎ expect() > toMatchInlineSnapshot to return undefined
✎ expect() > toThrowErrorMatchingInlineSnapshot to return undefined
✎ expect() > toThrowErrorMatchingSnapshot to return undefined


4 tests failed:
✗ expect() > deepEquals with asymmetric matchers > should not match the wrong constructors [10.53ms]
✗ expect() > toMatchObject > with expect matcher [204.07ms]
✗ expect() > asymmetric matchers > expect.any [10.83ms]
✗ expect() > asymmetric matchers > expect.any on primitive wrapper classes [13.88ms]

 341 pass
 12 todo
 4 fail
 1 snapshots, 1934 expect() calls
Ran 357 tests across 1 files. [2.16s]
```

**Comment by dylan-conway** [comment]
Happens only in release builds

**Comment by Jarred-Sumner** [comment]
This was fixed
