### ISSUE TITLE
bun run with error: 'ECDH' not found in module 'crypto'

### ISSUE THREAD

**Issue by XuJiandong** [oven-sh/bun#8470]
### What version of Bun is running?

1.0.25

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

```
❯ cat src/ts_crypto.ts
import { createHmac } from "node:crypto";
import { createECDH, ECDH } from "node:crypto";

function main() {
    const hasher = createHmac("sha256", "");
    hasher.update("0xFF00");
    hasher.update(new Uint8Array([0xff, 0]));
    console.log("0x%s", hasher.digest("hex"));

    const ecdh = createECDH("secp256k1");
    ecdh.generateKeys();
    const compressedKey = ecdh.getPublicKey("hex", "compressed");
    const uncompressedKey = ECDH.convertKey(compressedKey, "secp256k1", "hex", "hex", "uncompressed");
    console.log(ecdh.getPublicKey("hex") == uncompressedKey);
}

main();
❯ bun run src/ts_crypto.ts
1 | (function (entry, fetcher)
    ^
SyntaxError: Export named 'ECDH' not found in module 'crypto'.
❯ ts-node src/ts_crypto.ts
0xb0fc0173e2e6c27404a29397e9b56b1cd7757c5574f75a84ed7dc414bbeaac3e
true

```

### What is the expected behavior?

Can run successfully as ts-node

### What do you see instead?

Error reported: 
```
1 | (function (entry, fetcher)
    ^
SyntaxError: Export named 'ECDH' not found in module 'crypto'.
```

### Additional information

great work

**Comment by jlucaso1** [comment]
New error message in the canary:

```
0xb0fc0173e2e6c27404a29397e9b56b1cd7757c5574f75a84ed7dc414bbeaac3e
 5 |     const hasher = createHmac("sha256", "");
 6 |     hasher.update("0xFF00");
 7 |     hasher.update(new Uint8Array([0xff, 0]));
 8 |     console.log("0x%s", hasher.digest("hex"));
 9 |
10 |     const ecdh = createECDH("secp256k1");
                      ^
error: Failed to create key using named curve
 code: "ERR_CRYPTO_OPERATION_FAILED"

      at createECDH (node:crypto:2418:10)
      at main (/home/jlucaso/projects/temp/bun.ts:10:18)
      at /home/jlucaso/projects/temp/bun.ts:17:1

Bun v1.2.6-canary.57+26f08fabd (Linux x64)
```

**Comment by dylan-conway** [comment]
`ECDH` missing from `node:crypto` was fixed in Bun v1.1.45. Closing as complete.

Currently secp256k1 is unsupported in Bun. This issue can be followed here #17184
