### ISSUE TITLE
$`tsc`

### ISSUE THREAD

**Issue by JacobWeisenburger** [oven-sh/bun#8562]
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

```ts
import { $ } from 'bun'
$`tsc`
```
or
```ts
import { $ } from 'bun'
$`tsc --version`
```

### What is the expected behavior?

tsc to run normally

### What do you see instead?

```
/home/.../node_modules/typescript/lib/tsc.js:93
  for (let i = startIndex ?? 0; i < array.length; i++) {
                           ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/.../node_modules/typescript/bin/tsc:2:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by paperclover** [comment]
not technically a bug in shell, but that the `tsc` is running in node (as per shebang `#!/usr/bin/env`)

**Comment by JacobWeisenburger** [comment]
I was able to solve this using:
https://github.com/wobsoriano/bun-plugin-dts
