### ISSUE TITLE
Bun Compatibility with Protobot

### ISSUE THREAD

**Issue by jackHedaya** [oven-sh/bun#8614]
### What version of Bun is running?

1.0.25

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

Attempt to make a Probot and use the `$` command in a TypeScript file. Run bun start

### What is the expected behavior?

Probot successfully runs

### What do you see instead?

```
jackhedaya@Jacks-MacBook-Pro deploy-bot % bun start
$ probot run ./index.js
(node:25315) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/.../deploy-bot/node_modules/resolve/lib/sync.js:111
    var err = new Error("Cannot find module '" + x + "' from '" + parent + "'");
              ^

Error: Cannot find module './index.js' from '/.../Desktop/deploy-bot'
    at resolveSync (/.../Desktop/deploy-bot/node_modules/resolve/lib/sync.js:111:15)
    at resolveAppFunction (/.../Desktop/deploy-bot/node_modules/probot/lib/helpers/resolve-app-function.js:34:23)
    at combinedApps (/.../Desktop/deploy-bot/node_modules/probot/lib/run.js:101:79)
    at async Server.load (/.../Desktop/deploy-bot/node_modules/probot/lib/server/server.js:60:9)
    at async run (/.../Desktop/deploy-bot/node_modules/probot/lib/run.js:105:9) {
  code: 'MODULE_NOT_FOUND'
}
```

**Comment by jackHedaya** [comment]
I can source the error to [this file](https://github.com/probot/probot/blob/1eb03896e9772312c84f0be3da7bf3c0910797b6/src/helpers/resolve-app-function.ts#L5). Unsure if I have the time to look deeper over the next few days but thought it might help.

**Comment by jackHedaya** [comment]
I have found that you can import the server directly from Probot as opposed to running the command. I think running the command should be supported by `bun` but you can do the following:
```typescript
import { run, type Probot } from 'probot'

run(server)

function server(app: Probot) {
   ...
}
```
