### ISSUE TITLE
Invalid argument in copyFileSync while running vite build with bun

### ISSUE THREAD

**Issue by starsep** [oven-sh/bun#8625]
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

Linux 5.15.0-57-generic x86_64 x86_64

### What steps can reproduce the bug?

```
gh repo clone openstreetmap-polska/openaedmap-frontend
cd openaedmap-frontend
bun install
VITE_DEFAULT_LANG=en bunx --bun vite build
```

### What is the expected behavior?

I expect vite build not to fail.
Running `VITE_DEFAULT_LANG=en bunx vite build` which uses NodeJS is successful

### What do you see instead?

```
vite v5.0.12 building for production...
✓ 602 modules transformed.
Invalid argument
✓ built in 3.91s
error during build:
EINVAL: Invalid argument
    at copyFileSync (native)
    at copyDir (/home/starsep/openaedmap-frontend/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:4593:24)
    at copyDir (/home/starsep/openaedmap-frontend/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:4591:14)
    at copyDir (/home/starsep/openaedmap-frontend/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:4591:14)
    at prepareOutDir (/home/starsep/openaedmap-frontend/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:23463:14)
    at <anonymous> (/home/starsep/openaedmap-frontend/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:23428:20)
    at processTicksAndRejections (:12:39)
```

**Comment by 0-don** [comment]
same issue currently I am using copyFileSync

**Comment by starsep** [comment]
I no longer can reproduce with `bun 1.1.29` and `vite 5.4.8`
