### ISSUE TITLE
Allow `bunx` to run bin's from current package

### ISSUE THREAD

**Issue by icanvardar** [oven-sh/bun#8664]
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

Linux 6.5.0-15-generic x86_64 x86_64

### What steps can reproduce the bug?

I wanted to create bunx package executable by using Package Runner. I've created bin file in /dist directory as index.js and I've also referenced it to package.json. Additionally, /dist/index.js file is simple js file that consists `console.log` also Shebang line.

After these configurations I tried to run `bunx my-cli` which is the package name, and than I'd got the error. 

Here's the package.json file:

```json
{
  "name": "my-cli",
  "module": "index.ts",
  "type": "module",
  "bin": {
    "my-cli": "dist/index.js"
  },
  "devDependencies": {
    "@types/bun": "latest"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  }
}
```

Here's the /dist/index.js file:

```js
#!/usr/bin/env bun

console.log("Hello world!");
```

### What is the expected behavior?

```sh
Hello world!
```

### What do you see instead?

```sh
fs.js:43
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:43:5
    at req_ (/tmp/pesto@latest--bunx/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/tmp/pesto@latest--bunx/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/tmp/pesto@latest--bunx/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
```

**Comment by paperclover** [comment]
what happens here is bunx tries to download the npm package `my-cli` and run that, when you desire it to lookup the current package's `bin`. I think this would be neat to have.

I should note that `npx` does not do this, it always installs

<img width="406" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/8506d2a5-855f-45c3-8b5a-4873b5017269">

As a workaround, I recommend putting a `scripts` entry with `my-cli`, then you can use bun run my-cli as if it was the CLI.

```diff
  "type": "module",
  "bin": {
    "my-cli": "dist/index.js"
  },
+ "scripts": {
+   "my-cli": "bun dist/index.ts"
+ },
  "devDependencies": {
    "@types/bun": "latest"
```

**Comment by icanvardar** [comment]
This seems kind of a solution, but I am not quite sure this is a proper way to solve it. As I know npx looks node_modules/.bin folder which is marked as bin field in package.json. If there is no package named as `my-cli`, and then It downloads remotely.

So, running the built file in scripts, does not bring me any solution in my opinion. Thanks anyway. 🙏🏼
