### ISSUE TITLE
`spawnSync` throws error instead of defining property

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#8729]
### What version of Bun is running?

1.0.26+972a7b708

### What platform is your computer?

Darwin 22.2.0 arm64 arm

### What steps can reproduce the bug?

```js
const { spawnSync } = require("child_process");

console.log(spawnSync("doesnotexist"));
```

### What is the expected behavior?

In Node:

```
❯ node spawnSync.cjs 
{
  error: Error: spawnSync doesnotexist ENOENT
      at Object.spawnSync (node:internal/child_process:1124:20)
      at spawnSync (node:child_process:876:24)
      at Object.<anonymous> (/spawnSync.cjs:3:13)
      at Module._compile (node:internal/modules/cjs/loader:1375:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
      at Module.load (node:internal/modules/cjs/loader:1206:32)
      at Module._load (node:internal/modules/cjs/loader:1022:12)
      at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
      at node:internal/main/run_main_module:28:49 {
    errno: -2,
    code: 'ENOENT',
    syscall: 'spawnSync doesnotexist',
    path: 'doesnotexist',
    spawnargs: []
  },
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}
```

### What do you see instead?

In Bun:

```
❯ bun spawnSync.cjs 
1 | const { spawnSync } = require("child_process");
2 | 
3 | console.log(spawnSync("doesnotexist"));
                ^
TypeError: Executable not found in $PATH: "doesnotexist"
 code: "ERR_INVALID_ARG_TYPE"

      at node:child_process:173:47
      at /spawnSync.cjs:3:13
```

**Comment by nektro** [comment]
fixed by https://github.com/oven-sh/bun/pull/15561
