### ISSUE TITLE
Bun imports the wrong file from linked package for macros

### ISSUE THREAD

**Issue by NeoVance** [oven-sh/bun#8779]
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Linux 5.15.0-91-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Create a workspace with a normal library entry point, as well as a macro-specific entry point.
2. Set add the macro entry point to exports in `package.json` and build
3. Link the workspace to a second workspace, and import using `with|assert { type: 'macro' }`
4. Use a macro function expected to exist in the macro entry point, and attempt to build

### What is the expected behavior?

The macros should be loaded from the file indicated to be the entry point for the macro type by the package and work as expected.

### What do you see instead?

```
❯ bun build --root ./ --outdir dist index.ts
 8 | }
 9 | if (!('ALPHA_NUMERIC_STR' in Macros)) {
10 |   throw new Error("Macro 'ALPHA_NUMERIC_STR' not found in '/libs/useful-constants/dist/index.js'");
11 | }
12 | 
13 | Bun.registerMacro(1699583824, Macros['ALPHA_NUMERIC_STR']);
     ^
error: Macro must be a function
      at macro://d0ee1cc50d444272.js:13:1
120 |   const string = function string(length: number, source: string | string[] = ALPHA_NUMERIC_STR()) {
                                                                                   ^
error: "MacroLoadError" error in macro
    at /libs/prng/src/prng.ts:120:78
```
The error output indicates that Bun is loading the module from the regular `import` export type from the `package.json` file rather than the export intended to be used for macros which is defined as indicated by the documentation. In my case, this should be `./dist/index.macro.js`.,

**Comment by aralroca** [comment]
I had the same issue, in my case, it crashed the second time with the same error. The first time it uses the macro from my library it works, the second time it crashes... Have you found any workaround to solve it? @NeoVance
