### ISSUE TITLE
nock does't work in bun

### ISSUE THREAD

**Issue by panva** [oven-sh/bun#8781]
### What version of Bun is running?

1.0.26+c75e768a6

### What steps can reproduce the bug?

```
gh repo clone nock/nock
cd nock
bun install
bun run ./node_modules/.bin/mocha --recursive tests
```

### What is the expected behavior?

The nock test suite passes, indicating that nock can be used in project test suites to check if they work in bun or not.

### What do you see instead?

- incomplete test output
- failures almost everywhere

### Additional information

It is impossible for modules that have existing test suite for the Node.js runtime to test and assert their module works in Bun if the test suite doesn't even run in Bun. `nock` is a very common library for mocking http responses for the `node:http` and `node:https` modules.

**Comment by JulianKingman** [comment]
In version 1.0.4, I got this error: https://github.com/oven-sh/bun/issues/5006

Now in version 1.1.0, I get this error:
```
96 |     req.path = options.path
         ^
TypeError: Attempted to assign to readonly property.
      at attachToReq (/Users/Julian/Projects//node_modules/nock/lib/intercepted_request_router.js:96:5)
      at new InterceptedRequestRouter (/Users/Julian/Projects//node_modules/nock/lib/intercepted_request_router.js:73:5)
      at new OverriddenClientRequest (/Users/Julian/Projects//node_modules/nock/lib/intercept.js:290:25)
      at /Users/Julian/Projects//node_modules/nock/lib/intercept.js:426:14
      at /Users/Julian/Projects//node_modules/nock/lib/common.js:91:14
      at /Users/Julian/Projects//node_modules/@smithy/node-http-handler/dist-cjs/index.js:294:19
      at new Promise (:1:21)
      at /Users/Julian/Projects//node_modules/@smithy/node-http-handler/dist-cjs/index.js:245:12
```
Probably related: https://github.com/oven-sh/bun/pull/8368

**Comment by dougludlow** [comment]
I'm seeing the exact same error as above in v1.1.2.

**Comment by rafaell-lycan** [comment]
I just got the same error as well on v1.1.26 😬

**Comment by hems** [comment]
this is super important, nock is such an important library. this is such a deal breaker on bun : (

**Comment by hems** [comment]
Actually i ended up in this other problem with nockBack / recording.

It seems it's not useable with bun :(

https://github.com/nock/nock/issues/2803

**Comment by PfisterFactor** [comment]
I believe this is because nock trys to [assign to properties](https://github.com/nock/nock/blob/ac7a1b200e34bba4882216d75ba13528164a4f2e/lib/intercepted_request_router.js#L77) that are public fields on node, but only have [getters](https://github.com/oven-sh/bun/blob/b4f34b03d68286cb399878bc719b7f3a5f9d65fd/src/js/node/http.ts#L1465) on bun.

I think if we just add setters on the ClientRequest class in Bun - we should be able to resolve these errors

**Comment by rafaell-lycan** [comment]
@Jarred-Sumner any changes to fix it or bring a better solution for it in the future?

**Comment by isnifer** [comment]
I immediately switched to `msw` and it "just works!"
