### ISSUE TITLE
Postgres.js connection error with bun >0.6.14

### ISSUE THREAD

**Issue by akhar** [oven-sh/bun#8789]
### What version of Bun is running?

1.0.26

### What platform is your computer?

Darwin 23.2.0 arm64

### What steps can reproduce the bug?

1. bun init
2. bun add postgres
3. configure a connection
4. try to connect and select data

### What is the expected behavior?

return data

### What do you see instead?

```
165 |   if (originCache.has(xs))
166 |     return originCache.get(xs)
167 |
168 |   const x = Error.stackTraceLimit
169 |   Error.stackTraceLimit = 4
170 |   originCache.set(xs, new Error())
                               ^
ECONNREFUSED: Failed to connect
 syscall: "connect"

      at cachedError (/Users/akha/WebstormProjects/BunPostgresError/node_modules/postgres/src/query.js:170:26)
      at new Query (/Users/akha/WebstormProjects/BunPostgresError/node_modules/postgres/src/query.js:36:24)
      at sql (/Users/akha/WebstormProjects/BunPostgresError/node_modules/postgres/src/index.js:112:15)
      at readLogs (/Users/akha/WebstormProjects/BunPostgresError/index.ts:31:31)
```

### Additional information

It works using bun 0.6.x
Doesn't work using bun 0.7.x, 0.8.x, 1.0.x.

**Comment by Jarred-Sumner** [comment]
We run Postgres.js in Bun's test suite and in an internal production service - so there must be something more specific going on. Can you share if this is using TLS? What is the postgres provider?

**Comment by akhar** [comment]
I use Docker container `FROM postgres:13.10`, without TLS, everything pretty default.
Btw, pg.js not working with same conditions as well.
I will be glad to share any information you need, just ask.

**Comment by Serpentarius13** [comment]
Im getting the same thing. My docker-compose:

```
 db:
    image: postgres:15.2
    container_name: elysia-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: elysia
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
```

Im just opening a pool with pg library:

```
const pool = new Pool({
      host: "localhost",
      port: 5432,
      user: "root",
      password: "root",
      database: "elysia",
    });
    

```

The error is:

```
rej = reject
backend-1  | 42 |   }).catch((err) => {
backend-1  | 43 |     // replace the stack trace that leads to `TCP.onStreamRead` with one that leads back to the
backend-1  | 44 |     // application that created the query
backend-1  | 45 |     Error.captureStackTrace(err)
backend-1  | 46 |     throw err
backend-1  |        ^
backend-1  | ECONNREFUSED: Failed to connect
backend-1  |  syscall: "connect"
backend-1  | 
backend-1  |       at /usr/src/app/node_modules/pg-pool/index.js:46:3
backend-1  |       at processTicksAndRejections (native:1:1)
```

Just to note, this happens only in docker. Everything works when Bun is run normally

**Comment by markoftw** [comment]
Is there a workaround for this yet or a planned solution?

Having the same issue, but only in GitHub actions, locally it works fine.

```40 |     res = resolve
41 |     rej = reject
42 |   }).catch((err) => {
43 |     // replace the stack trace that leads to `TCP.onStreamRead` with one that leads back to the
44 |     // application that created the query
45 |     Error.captureStackTrace(err)
               ^
ECONNREFUSED: Failed to connect
   errno: 24
 syscall: "connect"

      at /home/runner/work/org/repo/node_modules/.pnpm/pg-pool@3.6.2_pg@8.12.0/node_modules/pg-pool/index.js:45:11
      at processTicksAndRejections (native:1:1)
```
