### ISSUE TITLE
req.headers.raw function

### ISSUE THREAD

**Issue by ComputMagnac** [oven-sh/bun#8793]
### What is the problem this feature would solve?

the function req.headers.raw() needs to be implemented.
TypeError: req.headers.raw is not a function. (In 'req.headers.raw()', 'req.headers.raw' is undefined)

### What is the feature you are proposing to solve the problem?

Implementing it

### What alternatives have you considered?

None

**Comment by Electroid** [comment]
We do support `headers.raw()` if you're importing from `node-fetch`. Could you share a small snippet of how you're using it?

**Comment by ComputMagnac** [comment]
> We do support `headers.raw()` if you're importing from `node-fetch`. Could you share a small snippet of how you're using it?

```javascript
fetch: async (req, server) => {
    req = await this.#buildCustomReq(req);
    [...]
};

async #buildCustomReq(req)
{
    let finalReq = {
      isGET: req.method === "GET",
      isPOST: req.method === "POST",

      headers: req.headers.raw()
    }
    return finalReq;
}
```

**Comment by nektro** [comment]
```js
import http from "node:http";

const server = http.createServer(req => {
  console.log(req.headers);
  console.log(req.headers.raw());
});
server.listen(3000);
server.on("listening", () => {
  console.log("listenin on http://localhost:3000");
});
```

```
❯ node test.js 
listenin on http://localhost:3000
{
.....
}
file:///Users/meghan/src/bun/test.js:5
  console.log(req.headers.raw());
                          ^
TypeError: req.headers.raw is not a function
    at Server.<anonymous> (file:///Users/meghandenny/src/bun/test.js:5:27)
    at Server.emit (node:events:519:28)
    at parserOnIncoming (node:_http_server:1150:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:118:17)

Node.js v22.9.0
````

```
❯ ./build/debug/bun-debug test.js
listenin on http://localhost:3000
{
....
}
1 | import http from "node:http";
2 | 
3 | const server = http.createServer(req => {
4 |   console.log(req.headers);
5 |   console.log(req.headers.raw());
                              ^
TypeError: req.headers.raw is not a function. (In 'req.headers.raw()', 'req.headers.raw' is undefined)
      at /Users/meghandenny/src/bun/test.js:5:27
      at emit (node:events:254:48)
      at fetch (node:http:786:14)
GET - / failed
```

**Comment by nektro** [comment]
if this is still affecting you in the latest version of Bun (you may need to run `bun upgrade`) please leave a comment and let us know. for now we're going to mark this as closed.

**Comment by Electroid** [comment]
@nektro I think the report here is about using `node-fetch`, and not `node:http`

**Comment by nektro** [comment]
i also closed it because of `needs repro` and `stale`
