### ISSUE TITLE
IPC support for windows

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#8917]
### What is the problem this feature would solve?

Using NextJS on Windows

Error:
```
PS D:\GitHub\MYPROJECT> bun --bun run dev  
$ next dev
228 |                 NODE_OPTIONS = `${NODE_OPTIONS} --max-old-space-size=${Math.floor(totalMemInMB * 0.5)}`;
229 |             }
230 |             if (nodeDebugType) {
231 |                 NODE_OPTIONS = `${NODE_OPTIONS} --${nodeDebugType}=${(0, _utils.getDebugPort)() + 1}`;
232 |             }
233 |             child = (0, _child_process.fork)(startServerPath, {
                              ^
TODOError: TODO: IPC is not yet supported on Windows
      at spawn (node:child_process:641:15)
      at node:child_process:2:41
      at D:\GitHub\MYPROJECT\node_modules\next\dist\cli\next-dev.js:233:25
      at new Promise (:1:21)
      at D:\GitHub\MYPROJECT\node_modules\next\dist\cli\next-dev.js:219:16
      at startServer (D:\GitHub\MYPROJECT\node_modules\next\dist\cli\next-dev.js:218:32)
      at D:\GitHub\MYPROJECT\node_modules\next\dist\cli\next-dev.js:300:23
      at D:\GitHub\MYPROJECT\node_modules\next\dist\cli\next-dev.js:278:33
      at D:\GitHub\MYPROJECT\node_modules\next\dist\cli\next-dev.js:305:27
```

### What is the feature you are proposing to solve the problem?

Support for IPC on Windows

**Comment by paperclover** [comment]
Work in #8497. Blocked by #8456
