### ISSUE TITLE
ShellJS support broken starting with version 1.0.22

### ISSUE THREAD

**Issue by zArubaru** [oven-sh/bun#9013]
### What version of Bun is running?

bun@1.0.28

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

```js
import shell from 'shelljs';

shell.set('-e');

shell.exec('echo "Hello 1!"');
shell.exec('echo "Hello 2!"');
shell.exec('echo "Hello 3!"');
```

$ `bun src/test.ts`

### What is the expected behavior?

```bash
$ bun src/test.ts
Hello 1!
Hello 2!
Hello 3!
```

### What do you see instead?

```sh
$ bun src/test.ts
Hello 1!
105 |   var logEntry = convertErrorOutput(options.prefix + msg);
106 |   state.error = state.error ? state.error + '\n' : '';
107 |   state.error += logEntry;
108 |
109 |   // Throw an error, or log the entry
110 |   if (config.fatal) throw new Error(logEntry);
                                ^
error: exec:
      at error (/Users/MY_USER/MY_PROJECT/node_modules/shelljs/src/common.js:110:27)
      at execSync (/Users/MY_USER/MY_PROJECT/node_modules/shelljs/src/exec.js:120:5)
      at _exec (/Users/MY_USER/MY_PROJECT/node_modules/shelljs/src/exec.js:223:12)
      at /Users/MY_USER/MY_PROJECT/node_modules/shelljs/src/common.js:335:20
      at /Users/MY_USER/MY_PROJECT/src/test.ts:6:1
```

### Additional information

Using bun@1.0.21 this problem does **not** appear. Issue seems to start on version 1.0.22 and tested multiple ones between 1.0.22-1.0.28 and the issue persisted.

**Comment by akirarika** [comment]
This may not be the answer you want, but I think you may need it:

https://bun.sh/docs/runtime/shell

bun has launched a very useful shell, perhaps before this issue is fixed, you can replace the shell in the code with the built-in shell function of bun

```ts
$`echo "hello world"`;
```

**Comment by zArubaru** [comment]
Thank you @akirarika, but for now the current bun.sh implementation of shell isn't robust (and feature-rich) enough for my use case. The above example was just intended as a simple case, where we can get an error :)

**Comment by ludicast** [comment]
I'm getting a shelljs issue with bun watch (v1.1.23 of bun) when cd is used

    import { pwd, cd } from "shelljs"

    cd("node_modules")
    console.log(pwd())

running `bun --watch ./index.ts` gives me the correct result initially but after changing the index file the watcher errors with `error: Module not found "index.ts"`
