### ISSUE TITLE
EBADF: Bad file descriptor.  errno: -9

### ISSUE THREAD

**Issue by sergey-arkhipov** [oven-sh/bun#9024]
### What version of Bun is running?

1.0.28

### What platform is your computer?

Darwin 23.2.0 x86_64 i386 | Linux 5.15.0-94-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Create bun.config.js

```js
import path from 'path'
import fs from 'fs'

const config = {
  sourcemap: 'external',
  entrypoints: ['app/javascript/application.js'],
  outdir: path.join(process.cwd(), 'app/assets/builds'),
  plugins: [
    {
      name: 'tinyMCE',
      async setup(build) {
        console.log('Start copying files')
        try {
          await fs.promises.rmdir('./public/assets', {
            recursive: true,
            force: true,
          })
          await fs.promises.mkdir('./public/assets/tinymce', {
            recursive: true,
          })
          await fs.promises.cp(
            './node_modules/tinymce',
            './public/assets/tinymce',
            { recursive: true },
          )
          console.log(`Number of plugins: ${build.config.plugins.length}`)
        } catch (err) {
          console.error(err)
        }
      },
    },
  ],
}

const build = async (config) => {
  const result = await Bun.build(config)

  if (!result.success) {
    if (process.argv.includes('--watch')) {
      console.error('Build failed')
      for (const message of result.logs) {
        console.error(message)
      }
      return
    } else {
      throw new AggregateError(result.logs, 'Build failed')
    }
  }
}

const main = async () => {
  await build(config)

  if (process.argv.includes('--watch')) {
    fs.watch(
      path.join(process.cwd(), 'app/javascript'),
      { recursive: true },
      (eventType, filename) => {
        console.log(`File changed: ${filename}. Rebuilding...`)
        build(config)
      },
    )
  } else {
    process.exit(0)
  }
}

main()

```
2. Create package.json

```json
{
  "name": "app",
  "private": "true",
  "scripts": {
    "build": "bun bun.config.js",
    "build:css:compile": "sass ./app/assets/stylesheets/application.sass.scss:./app/assets/builds/application.css --no-source-map --load-path=node_modules",
    "build:css:prefix": "postcss ./app/assets/builds/application.css --use=autoprefixer --output=./app/assets/builds/application.css",
    "build:css": "bun run build:css:compile && bun run build:css:prefix",
    "watch:css": "nodemon --watch ./app/assets/stylesheets/ --ext scss --exec \"bun run build:css\""
  },
  "dependencies": {
    "@hotwired/stimulus": "^3.2.2",
    "@hotwired/turbo-rails": "^7.3.0",
    "@popperjs/core": "^2.11.8",
    "@rails/request.js": "^0.0.9",
    "autoprefixer": "^10.4.16",
    "bootstrap": "^5.3.2",
    "bootstrap-icons": "^1.11.1",
    "flat-tree-builder": "1.5.17",
    "flatpickr": "^4.6.13",
    "nodemon": "^3.0.1",
    "postcss": "^8.4.31",
    "postcss-cli": "^10.1.0",
    "sass": "^1.69.3",
    "shortcut-buttons-flatpickr": "^0.4.0",
    "sortablejs": "^1.15.0",
    "tinymce": "^6.7.0",
    "tinymce-langs": "^1.0.0",
    "tom-select": "^2.2.2"
  }
}
```

3. bun run build

```bash
$ bun bun.config.js
Start copying files
31 |     },
32 |   ],
33 | }
34 |
35 | const build = async (config) => {
36 |   const result = await Bun.build(config)
                            ^
EBADF: Bad file descriptor
   errno: -9
 syscall: "open"
   path: "./node_modules/tinymce"

      at /Users/as/Documents/work/souz/bun.config.js:36:24
      at build (/Users/as/Documents/work/souz/bun.config.js:35:22)
      at /Users/as/Documents/work/souz/bun.config.js:52:9
      at main (/Users/as/Documents/work/souz/bun.config.js:51:14)
      at /Users/as/Documents/work/souz/bun.config.js:68:1
```

### What is the expected behavior?

Build without errors, for example, bun v.1.0.26

```bash 
#  bun --version
1.0.26

 # bun run build
$ bun bun.config.js
Start copying files
Number of plugins: 1
```

### Additional information

This error started from version 1.0.27

**Comment by argosphil** [comment]
@gvilums can you check whether https://github.com/oven-sh/bun/commit/1a695f13bf776c1be2241fd2538104f72a78d632#comments might be the problem? Thanks!

**Comment by sergey-arkhipov** [comment]
> @gvilums can you check

What exactly do you want me to check?

Oh, I'm sorry, it's not for me

**Comment by lgarron** [comment]
I'm also running into a mysterious "Bad file descriptor" error after upgrading to `bun` v1.0.29:

Repro:

```shell
cd /tmp
git clone https://github.com/cubing/cubing.js && cd cubing.js
git switch --detach 97d6f47e388eeac3f3a17380a968c1e0d4ff61ec
make setup
make build-site-twizzle
```

Output:

```
Cloning into 'cubing.js'...
remote: Enumerating objects: 46678, done.
remote: Counting objects: 100% (5142/5142), done.
remote: Compressing objects: 100% (1856/1856), done.
remote: Total 46678 (delta 3247), reused 4855 (delta 3045), pack-reused 41536
Receiving objects: 100% (46678/46678), 36.92 MiB | 34.31 MiB/s, done.
Resolving deltas: 100% (32120/32120), done.
HEAD is now at 97d6f47e Update VS Code settings to organize imports on save.
bun install # TODO: was `npm ci`
bun install v1.0.29 (a146856d)

 + @biomejs/biome@1.5.2
 …
 + three@0.160.0

 505 packages installed [597.00ms]
bun run ./script/build/sites/build-site-twizzle.ts
EBADF: Bad file descriptor
   errno: -9
 syscall: "open"
   path: "src/sites/alpha.twizzle.net"

make: *** [build-site-twizzle] Error 1
```

**Comment by lgarron** [comment]
This works for me with:

```
brew install oven-sh/bun/bun@1.0.26
```

It fails with:

```
brew install oven-sh/bun/bun@1.0.27
```

So it's a regression from one of these commits: https://github.com/oven-sh/bun/compare/bun-v1.0.26...bun-v1.0.27
