### ISSUE TITLE
TransformStream leaking errors even when handled

### ISSUE THREAD

**Issue by jchitel** [oven-sh/bun#9058]
### What version of Bun is running?

1.0.28+705638470

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

I am working with a `TransformStream` that may throw errors during the transformation process. Using it with `ReadableStream.pipeThrough()`, I am unable to handle these errors in a way that doesn't end the process with a non-zero exit code, or fail a unit test.

Here is a simple example that fails:
```ts
const input = new ReadableStream({
    start(controller) {
        controller.enqueue(1);
        controller.close();
    },
});
const stream = new TransformStream({
    transform() {
        throw new Error("transform error");
    },
});
const reader = input.pipeThrough(stream).getReader();
reader.read().catch((err) => {
    console.error("read error", err.message);
});
```

### What is the expected behavior?

I would expect to see only this, with a successful exit code:
```
> bun index.ts
read error transform error
```

This works as expected with Node, as well as in the Safari console.

### What do you see instead?

```
> bun index.ts
read error transform error
4 |         controller.close();
5 |     },
6 | });
7 | const stream = new TransformStream({
8 |     transform() {
9 |         throw new Error("transform error");
                   ^
error: transform error
      at transform (/Users/jchitel/development/new-lang/index.ts:9:15)
      at promiseInvokeOrNoopMethodNoCatch (:1:21)
      at promiseInvokeOrNoopMethod (:1:21)
      at transformStreamDefaultControllerPerformTransform (:1:21)
      at writableStreamDefaultControllerProcessWrite (:1:21)
      at writableStreamDefaultControllerAdvanceQueueIfNeeded (:1:21)
      at writableStreamDefaultControllerWrite (:1:21)
      at writableStreamDefaultWriterWrite (:1:21)
```

### Additional information

If I instead use the `TransformStream`'s `readable` and `writable` directly and attach a `catch` handler to the `write()` call, everything works as expected:
```ts
const stream = new TransformStream({
    transform() {
        throw new Error("transform error");
    },
});
const writer = stream.writable.getWriter();
const reader = stream.readable.getReader();
reader.read().catch((err) => {
    console.error("read error", err.message);
});
writer.write(1).catch((err) => {
    console.error("write error", err.message);
});
```

However, the internal mechanics of `pipeThrough` do not allow public access to the writer, so there is no way to make this work.

**Comment by truongan07** [comment]
try code :

```js
const input = new ReadableStream({
    start(controller) {
        controller.enqueue(1);
        controller.enqueue(2);
        controller.enqueue(3);
        controller.enqueue(4);
        controller.enqueue(5);
        controller.close();
    },
});
const stream = new TransformStream({
    transform(chunk, controller) {
        // do something
        console.log('transform: ', chunk);

        // stop by error
        if(3 === chunk) controller.error("transform error");
    },
});

const reader = input.pipeThrough(stream).getReader();

reader.read().catch(() => {
    // do something with error
});

```

**Comment by Milly** [comment]
I think this is a problem with `ReadableStream`.

```ts#test.ts
const readable = new ReadableStream({
  start(controller) {
    controller.error(new Error("foo"));
  }
});
readable.pipeTo(new WritableStream()).catch(() => {
  console.log("catched");
});
```

### Expected output

```
catched
```

### Actual output

```
catched
1 | const readable = new ReadableStream({
2 |   start(controller) {
3 |     controller.error(new Error("foo"));
                         ^
error: foo
      at start (C:\work\test.ts:3:22)
      at promiseInvokeOrNoopMethodNoCatch (:1:21)
      at readableStreamDefaultControllerStart (:1:21)
      at setupReadableStreamDefaultController (:1:21)
      at createReadableStreamController (:1:21)
      at initializeReadableStream (:1:21)
      at C:\work\test.ts:1:18

Bun v1.1.10 (Windows x64)
```
