### ISSUE TITLE
npm i -g bun gives an error in docker using the image node:alpine

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#9098]
### What version of Bun is running?

1.0.29

### What platform is your computer?

Docker node alpine

### What steps can reproduce the bug?

```dockerfile
FROM node:alpine

WORKDIR /app

RUN npm i -g bun
```

### What is the expected behavior?

download it successfully

### What do you see instead?
```
 > [backend  3/10] RUN npm i -g bun:
79.62 npm notice
79.62 npm notice New minor version of npm available! 10.2.4 -> 10.4.0
79.62 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.4.0>
79.62 npm notice Run `npm install -g npm@10.4.0` to update!
79.62 npm notice
79.62 npm ERR! code 1
79.62 npm ERR! path /usr/local/lib/node_modules/bun
79.62 npm ERR! command failed
79.62 npm ERR! command sh -c node install.js
79.62 npm ERR! Failed to find package "@oven/bun-linux-x64". You may have used the "--no-optional" flag when running "npm install".
79.62 npm ERR! Failed to find package "@oven/bun-linux-x64-baseline". You may have used the "--no-optional" flag when running "npm install".
79.62 npm ERR! Error: Failed to install package "bun"
79.62 npm ERR!     at /usr/local/lib/node_modules/bun/install.js:311:11
79.62 npm ERR!     at Generator.throw (<anonymous>)
79.62 npm ERR!     at rejected (/usr/local/lib/node_modules/bun/install.js:35:27)
79.62 npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
79.63
79.63 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-02-25T08_40_46_038Z-debug-0.log

failed to solve: process "/bin/sh -c npm i -g bun" did not complete successfully: exit code: 1
```

**Comment by ChillerDragon** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/5545

**Comment by ghost** [comment]
@ChillerDragon I didn't knew, sorry
