### ISSUE TITLE
mssql/tedious connect ConnectionError "_nodeUrl.default.domainToASCII is not a function."

### ISSUE THREAD

**Issue by nxht** [oven-sh/bun#9235]
### What version of Bun is running?

1.0.29+a146856d1

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

`package.json`: 
```json
{
  "dependencies": { "mssql": "^10.0.2" },
  "devDependencies": {
    "@types/bun": "^1.0.8",
    "@types/mssql": "^9.1.5"
  }
}
```

`mssql` case:
```typescript
import sql from 'mssql';

await sql.connect({ server: 'localhost' });
```

`tedious` case:
```typescript
import { Connection } from 'tedious';

const connection = new Connection({ server: 'localhost' });
connection.connect((err) => {
  if (err) throw err;
});
```

### What is the expected behavior?

Connect normally

### What do you see instead?

`mssql` case:
```
80 |         rejectOnce(err)
81 |         return
82 |       }
83 |       tedious.connect(err => {
84 |         if (err) {
85 |           err = new ConnectionError(err)
                                   ^
ConnectionError: Failed to connect to localhost:1433 - _nodeUrl.default.domainToASCII is not a function. (In '_nodeUrl.default.domainToASCII(host)', '_nodeUrl.default.domainToASCII' is undefined)
 code: "ESOCKET"

      at /home/wsladmin/typescript/test-bun/node_modules/mssql/lib/tedious/connection-pool.js:85:31
      at onConnect (/home/wsladmin/typescript/test-bun/node_modules/tedious/lib/connection.js:1443:12)
      at native:1:1
      at emit (native:1:1)
      at socketError (/home/wsladmin/typescript/test-bun/node_modules/tedious/lib/connection.js:2309:14)
      at /home/wsladmin/typescript/test-bun/node_modules/tedious/lib/connection.js:2030:9
      at processTicksAndRejections (native:1:1)

Exit code: 1
```

`tedious` case:
```
4 |   value: true
5 | });
6 | exports.RequestError = exports.ConnectionError = void 0;
7 | class ConnectionError extends Error {
8 |   constructor(message, code) {
9 |     super(message);
        ^
error: Failed to connect to localhost:1433 - _nodeUrl.default.domainToASCII is not a function. (In '_nodeUrl.default.domainToASCII(host)', '_nodeUrl.default.domainToASCII' is undefined)
 code: "ESOCKET"

      at new ConnectionError (/home/wsladmin/typescript/test-bun/node_modules/tedious/lib/errors.js:9:5)
      at socketError (/home/wsladmin/typescript/test-bun/node_modules/tedious/lib/connection.js:1340:28)
      at /home/wsladmin/typescript/test-bun/node_modules/tedious/lib/connection.js:1133:9

Exit code: 1
```

### Additional information

It's due to changes on tedious v16.7.1, tediousjs/tedious/pull/1597 which changes `punycode` to `url.domainToASCII`
which is mentioned as missing in Bun NodeJS compatiblity document (https://bun.sh/docs/runtime/nodejs-apis#node-url)

**Comment by Electroid** [comment]
We need to implement [`domainToASCII`](https://nodejs.org/api/url.html#urldomaintoasciidomain)
