### ISSUE TITLE
Auto-install doesn't work for sqlite3 library

### ISSUE THREAD

**Issue by mayfer** [oven-sh/bun#9292]
### What version of Bun is running?

1.30

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

Create a test.ts file that imports sqlite3

```
import sqlite3 from 'sqlite3';
const db = new sqlite3.Database('db.sqlite');
```

Make sure there's no node_modules dir

$ `bun test.ts`

### What is the expected behavior?

Auto-install sqlite3 and run

### What do you see instead?

```
$ bun server/index.ts 
121 |         throw e;
122 |       }
123 |     }
124 |   }
125 | 
126 |   err = new Error(
              ^
error: Could not locate the bindings file. Tried:
 → /Users/murat/.bun/install/cache/sqlite3@5.1.7/build/node_sqlite3.node
 → /Users/murat/.bun/install/cache/sqlite3@5.1.7/build/Debug/node_sqlite3.node
 → /Users/murat/.bun/install/cache/sqlite3@5.1.7/build/Release/node_sqlite3.node
 → /Users/murat/.bun/install/cache/sqlite3@5.1.7/out/Debug/node_sqlite3.node
 → /Users/murat/.bun/install/cache/sqlite3@5.1.7/Debug/node_sqlite3.node
 → /Users/murat/.bun/install/cache/sqlite3@5.1.7/out/Release/node_sqlite3.node
 → /Users/murat/.bun/install/cache/sqlite3@5.1.7/Release/node_sqlite3.node
 → /Users/murat/.bun/install/cache/sqlite3@5.1.7/build/default/node_sqlite3.node
 → /Users/murat/.bun/install/cache/sqlite3@5.1.7/compiled/21.6.0/darwin/arm64/node_sqlite3.node
 → /Users/murat/.bun/install/cache/sqlite3@5.1.7/addon-build/release/install-root/node_sqlite3.node
 → /Users/murat/.bun/install/cache/sqlite3@5.1.7/addon-build/debug/install-root/node_sqlite3.node
 → /Users/murat/.bun/install/cache/sqlite3@5.1.7/addon-build/default/install-root/node_sqlite3.node
 → /Users/murat/.bun/install/cache/sqlite3@5.1.7/lib/binding/node-v115-darwin-arm64/node_sqlite3.node
      at bindings (/Users/murat/.bun/install/cache/bindings@1.5.0/bindings.js:126:9)
      at /Users/murat/.bun/install/cache/sqlite3@5.1.7/lib/sqlite3-binding.js:1:8
      at /Users/murat/.bun/install/cache/sqlite3@5.1.7/lib/sqlite3.js:2:7
```

### Additional information

If I remove sqlite3 code, other libraries work fine. It can auto-install them (example: "uuid" package)

**Comment by Jarred-Sumner** [comment]
not sure what to do about this yet. auto-install reuses the shared global cache which makes mutable packages difficult

maybe we do something special for packages with install scripts

**Comment by mayfer** [comment]
how about a `--install=local` flag to auto-install into node_modules locally when missing?

auto-install being restricted to NOT having a node_modules dir is quite limiting IMO.

another option is to have a separate script for auto-installing all missing packages given an entry point

**Comment by maciej-trebacz** [comment]
Bumping this issue, as I've ran into it while using the [srcbook](https://github.com/srcbookdev/srcbook) package. Reproduction is easy:

```
bunx srcbook start
```

**Comment by buzzy** [comment]
I am getting the same issue. Seems like any library that depends on the "standard" node sqlite3 library fails, because Bun tries to load it from the **.bun/install/cache** dir instead of **node_modules**. The cache dir version does not contain the **build/Release/node_sqlite3.node** binary, so it fails.

**Comment by buzzy** [comment]
And if I copy the sqlite3 binary from node_modules to cache, I get this error:

![image](https://github.com/user-attachments/assets/fb010384-b23e-45a5-91ca-2fd6b32c0bfe)

**Comment by buzzy** [comment]
Btw, this is not only a problem with auto-install. Even if I manually do "bun add sqlite3" and having it installed in the node_modules dir, Bun still uses the cache-version and ignores node_modules.
