### ISSUE TITLE
Bun cannot start with nextjs

### ISSUE THREAD

**Issue by dongchenxie** [oven-sh/bun#9329]
### What version of Bun is running?

1.0.30+1424a196f

### What platform is your computer?

zsh: no matches found: [Environment]::OSVersion zsh: command not found: ForEach-Object zsh: no matches found: [Environment]::Is64BitOperatingSystem zsh: command not found: x86 zsh: command not found:

### What steps can reproduce the bug?

bun create next-app .

### What is the expected behavior?

It should create a base nextjs app

### What do you see instead?

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'stream/promises'
Require stack:
- /tmp/bunx-1000-create-next-app@latest/node_modules/create-next-app/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Module.8776 (/tmp/bunx-1000-create-next-app@latest/node_modules/create-next-app/dist/index.js:74:30476)
    at __nccwpck_require__ (/tmp/bunx-1000-create-next-app@latest/node_modules/create-next-app/dist/index.js:74:59273)
    at /tmp/bunx-1000-create-next-app@latest/node_modules/create-next-app/dist/index.js:74:60137
    at Object.<anonymous> (/tmp/bunx-1000-create-next-app@latest/node_modules/create-next-app/dist/index.js:74:60181)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/bunx-1000-create-next-app@latest/node_modules/create-next-app/dist/index.js'
  ]

**Comment by matthewcm** [comment]
Same issue here.

**Comment by RiskyMH** [comment]
We've invested a ton of time into making Bun more reliable over the last year. I'm having a really hard time reproducing this. If you're still running into this issue, please let me know and I'll re-open this

**Comment by dongchenxie** [comment]
Problem is resolved with newer version of bun, thanks @RiskyMH
