### ISSUE TITLE
Error when use Bun build and @google-cloud libraries

### ISSUE THREAD

**Issue by ftognetto** [oven-sh/bun#9367]
### What version of Bun is running?

1.0.30+1424a196f

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

In my project I'm currently using @google-cloud/pubsub and @google-cloud/logging
When I run the project with bun run index.ts I have no problem.
When I build the project (bun build index.ts --target node (or bun, is the same) and run the index.js output I get

```
Error: undefined undefined: undefined
    at callErrorFromStatus (file:///Users/fabriziotognetto/quantosprojects/bigartwall/bigartwall-backend/bun/services/album-service/dist/index.js:73779:19)
    at Object.onReceiveStatus (file:///Users/fabriziotognetto/quantosprojects/bigartwall/bigartwall-backend/bun/services/album-service/dist/index.js:74458:68)
    at Object.onReceiveStatus (file:///Users/fabriziotognetto/quantosprojects/bigartwall/bigartwall-backend/bun/services/album-service/dist/index.js:74292:139)
    at Object.onReceiveStatus (file:///Users/fabriziotognetto/quantosprojects/bigartwall/bigartwall-backend/bun/services/album-service/dist/index.js:74259:174)
    at file:///Users/fabriziotognetto/quantosprojects/bigartwall/bigartwall-backend/bun/services/album-service/dist/index.js:77548:67
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (file:///Users/fabriziotognetto/quantosprojects/bigartwall/bigartwall-backend/bun/services/album-service/dist/index.js:74429:30)
    at ServiceClientImpl.<anonymous> (file:///Users/fabriziotognetto/quantosprojects/bigartwall/bigartwall-backend/bun/services/album-service/dist/index.js:74721:17)
    at file:///Users/fabriziotognetto/quantosprojects/bigartwall/bigartwall-backend/bun/services/album-service/dist/index.js:116309:23
    at file:///Users/fabriziotognetto/quantosprojects/bigartwall/bigartwall-backend/bun/services/album-service/dist/index.js:106773:14
    at repeat (file:///Users/fabriziotognetto/quantosprojects/bigartwall/bigartwall-backend/bun/services/album-service/dist/index.js:106816:21)
    at Task._apiCall (file:///Users/fabriziotognetto/quantosprojects/bigartwall/bigartwall-backend/bun/services/album-service/dist/index.js:106849:9)
    at Task.run (file:///Users/fabriziotognetto/quantosprojects/bigartwall/bigartwall-backend/bun/services/album-service/dist/index.js:105558:33)
    at BundleExecutor._runNow (file:///Users/fabriziotognetto/quantosprojects/bigartwall/bigartwall-backend/bun/services/album-service/dist/index.js:105750:12)
    at Timeout._onTimeout (file:///Users/fabriziotognetto/quantosprojects/bigartwall/bigartwall-backend/bun/services/album-service/dist/index.js:105715:16)
    at listOnTimeout (node:internal/timers:573:17)
Emitted 'error' event on DerivedLogger instance at:
    at DerivedLogger.transportEvent (file:///Users/fabriziotognetto/quantosprojects/bigartwall/bigartwall-backend/bun/services/album-service/dist/index.js:155313:14)
    at LoggingWinston.emit (node:events:526:35)
    at errorOrDestroy (file:///Users/fabriziotognetto/quantosprojects/bigartwall/bigartwall-backend/bun/services/album-service/dist/index.js:26865:14)
    at onwriteError (file:///Users/fabriziotognetto/quantosprojects/bigartwall/bigartwall-backend/bun/services/album-service/dist/index.js:28421:7)
    at onwrite (file:///Users/fabriziotognetto/quantosprojects/bigartwall/bigartwall-backend/bun/services/album-service/dist/index.js:28439:7)
    at WritableState.onwrite (file:///Users/fabriziotognetto/quantosprojects/bigartwall/bigartwall-backend/bun/services/album-service/dist/index.js:28306:7)
    at newCallback (file:///Users/fabriziotognetto/quantosprojects/bigartwall/bigartwall-backend/bun/services/album-service/dist/index.js:143776:13)
    at file:///Users/fabriziotognetto/quantosprojects/bigartwall/bigartwall-backend/bun/services/album-service/dist/index.js:64731:19 {
  code: undefined,
  details: undefined,
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  note: 'Exception occurred in retry method that was not classified as transient'
}

Node.js v20.10.0
```

The same error when I try to send a message with @google-cloud/pubsub

### What is the expected behavior?

Something I don't understand is happening during the transpiling done by Bun.build. I expect to make @google-cloud libraries work after Bun.build

### Additional information

I'm currently using bun workspace.

The tsconfig I'm using is (taken from bun best practices)

```
{
	"compilerOptions": {
		// Enable latest features
		"lib": ["ESNext"],
		"target": "ESNext",
		"module": "ESNext",
		"moduleDetection": "force",
		"jsx": "preserve", //"jsx": "react-jsx",
		"allowJs": true,

		// Bundler mode
		"moduleResolution": "Bundler",
		"allowImportingTsExtensions": true,
		"verbatimModuleSyntax": true,
		"noEmit": true,
		"esModuleInterop": true,

		"allowSyntheticDefaultImports": true,

		// Best practices
		"strict": true,
		"skipLibCheck": true,
		"noFallthroughCasesInSwitch": true,

		// Some stricter flags
		"noUnusedLocals": true,
		"noUnusedParameters": false,
		"noPropertyAccessFromIndexSignature": false,

		"types": [
			"bun-types" // add Bun global
		]
	}
}
```

**Comment by Electroid** [comment]
Is it possible to share a minimal reproduction in code?

**Comment by ftognetto** [comment]
HI @Electroid yes ofc.

I create a repo here https://github.com/ftognetto/-oven-sh-bun-issues-9367

To use this repo you should have a gcp project with pubsub enabled.
There are two env variables to setup
- env "GOOGLE_APPLICATION_CREDENTIALS" pointing to a Google service account json (https://cloud.google.com/docs/authentication/provide-credentials-adc#local-key) 
- TOPIC  a pub sub topic where to publish.

I created some scripts in package.json that already load those env so you have everything in one place

- start - start the application with bun, everything work fine here - you must change the env passing to bun here
- build - build the app
- run-build - run the build with node, here we have the problem - you must change the env passing to bun here

Notes:
- I tried with node 16, 18 and 20
- I tried changing various tsconfig options

**Comment by ftognetto** [comment]
Hi @Electroid forgive the insistence are there any update on this? We are currently waiting for migrating an old lerna monorepo to bun workspaces and we have scheduled work on it.
If you need I can send you in private a service account so you can test the repo I sent without additional operation from your side. Let me know, thank you

**Comment by coupez** [comment]
I can confirm this issue is still present in the latest version of bun. When running the program directly `bun run main.ts` it works fine, but after `bun build ... --target bun`, the error above is still there.

**Comment by darekaze** [comment]
Confirm this issue is still existing using Bun 1.2.15, no matter bundling to bun or node.

For my current workaround is to run my backend application directly without using bun build (bundling it), which is common for most backend projects.

Or another workaround I think of is to use @vercel/ncc to bundle it.

But anyway I hope this issue can get fixed so we can just use bun for everything...

**Comment by bombnp** [comment]
can confirm this exact issue still persists (im using @google-cloud/pubsub). Is there any updates on this issue?

**Comment by charles-salmon** [comment]
I can confirm that I have reproduced this issue using Bun v1.2.17 and the current canary build.

I was able to workaround this issue by compiling my bundle using `--format cjs`.

@cirospaciari Based on past contributions, it looks like you're fairly well versed in this area. Do you potentially have any insight into what could be going wrong here?

**Comment by dylantientcheu** [comment]
The issue persists with pubsub.

Everything works perfectly in development, but once you build you have 

```
Error: undefined undefined: undefined
```

**Comment by maxmil** [comment]
Also affected by this issue. In our case we went with the fallback, which also supports `rest` explicitly, shame that it's not in the types. 

```typescript
new PubSub({ fallback: 'rest' } as any)
```

**Comment by macecchi** [comment]
Still happening. For anyone searching, just importing `@google-cloud/monitoring` also causes the issue. I don't see an error logged in this case, requests just hang, and setting `{ fallback: 'rest' }` doesn't have any effect. The issue happens even before initializing it.

**Comment by robobun** [comment]
The `Error: undefined undefined: undefined` that the gRPC-based @google-cloud clients throw after `bun build` comes from `@protobufjs/inquire`'s eval'd `require` returning nothing in Bun's bundled output, so protobufjs loses Node `Buffer` support and its serializers return `Uint8Array`, which grpc-js cannot send; that missing `require` for eval'd code in bundles is exactly the bug tracked in #14891 (and is why `--format cjs` or externalizing protobufjs works around it). The pending bundler fix for #14891 (#35581) covers this report as well, so it is being consolidated there.

Duplicate of #14891

Please add a 👍 or any extra details over there so it all stays in one place. If this is actually a different problem, say so here and we'll reopen.
