### ISSUE TITLE
`wiptest` exits with code 0 if an error occurs outside a test

### ISSUE THREAD

**Issue by DetachHead** [oven-sh/bun#948]
### Version

0.1.5

### Platform

Microsoft Windows NT 10.0.19044.0 x64

### What steps will reproduce the bug?

```ts
import {test} from 'bun:test'
import {ok} from 'assert'

throw new Error("fail")

test('asdf', () => {
    ok(false)
})
```
```bash
bun wiptest
```

### What is the expected behavior?

exit code 1 (or any code other than 0)

### What do you see instead?

```
$ bun wiptest

asdf.spec.ts:
1 | import {test} from 'bun:test'
2 | import {ok} from 'assert'
3 |
4 | throw new Error("fail")
          ^
Error: fail
      at /project/asdf.spec.ts:4:6


 0 pass
 0 fail
 Ran 0 tests across 1 files [64.00ms]
```
```
$ echo $?
0
```

**Comment by Electroid** [comment]
This has been fixed as of Bun 0.5.8.

```zsh
bun test v0.5.8 (5d296f62)

index.test.ts:
1 | import {test} from 'bun:test'
2 | import {ok} from 'assert'
3 | 
4 | throw new Error("fail")
          ^
error: fail
      at /Users/ashcon/Desktop/code/testing/index.test.ts:4:6

 0 pass
 1 fail
Ran 1 tests across 1 files [38.00ms]
```
```zsh
❯ echo $status
1

```
