### ISSUE TITLE
Turborepo possible regression on 1.0.33

### ISSUE THREAD

**Issue by kaminskypavel** [oven-sh/bun#9531]
### What version of Bun is running?

1.0.33-canary.10+931e04b01

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

`bunx create-turbo@latest`

### What do you see instead?

```
>>> TURBOREPO

>>> Welcome to Turborepo! Let's get you set up with a new codebase.

? Where would you like to create your turborepo? ./my-turborepo
? Which package manager do you want to use? bun workspaces (beta)

Downloading files. This might take a moment.

>>> Created a new Turborepo with the following:

apps
 - apps\docs
 - apps\web
packages
 - packages\eslint-config
 - packages\typescript-config
 - packages\ui

Installing packages. This might take a couple of minutes.

>   Installing dependencies...
>>> Unexpected error. Please report it as a bug:
Error: Command failed with exit code 3: bun install
bun install v1.0.33-canary.10 (931e04b0)

Panic: reached unreachable code

bun has crashed :'(

----- bun meta -----
Bun v1.0.33-canary.10 (931e04b0) Windows x64
InstallCommand:
Elapsed: 47ms | User: 0ms | Sys: 0ms
RSS: 45.25MB | Peak: 45.25MB | Commit: 90.95MB | Faults: 11232
----- bun meta -----

0   00007FF7F46B8258
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???
10  ???
11  ???
12  ???
13  ???
14  ???
15  ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 12564 panic: reached unreachable code
???:?:?: 0x7ff7f3367467 in ??? (bun.exe)
???:?:?: 0x7ff7f32ed034 in ??? (bun.exe)
???:?:?: 0x7ff7f31fe477 in ??? (bun.exe)
???:?:?: 0x7ff7f31f81c7 in ??? (bun.exe)
???:?:?: 0x7ff7f31f66dc in ??? (bun.exe)
???:?:?: 0x7ff7f3203736 in ??? (bun.exe)
???:?:?: 0x7ff7f3236e0a in ??? (bun.exe)
???:?:?: 0x7ff7f3254b29 in ??? (bun.exe)
???:?:?: 0x7ff7f326be25 in ??? (bun.exe)
???:?:?: 0x7ff7f331aeea in ??? (bun.exe)
???:?:?: 0x7ff7f30516f4 in ??? (bun.exe)
???:?:?: 0x7ff7f5b6e923 in ??? (bun.exe)
???:?:?: 0x7ffb8217257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ffb8408aa57 in ??? (ntdll.dll)
    at ML (C:\Users\kamin\AppData\Local\Temp\bunx-3530938197-create-turbo@latest\node_modules\create-turbo\dist\cli.js:12:57)
    at C:\Users\kamin\AppData\Local\Temp\bunx-3530938197-create-turbo@latest\node_modules\create-turbo\dist\cli.js:12:8077
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fc (C:\Users\kamin\AppData\Local\Temp\bunx-3530938197-create-turbo@latest\node_modules\create-turbo\dist\cli.js:60:2093)
    at async Command.Lm (C:\Users\kamin\AppData\Local\Temp\bunx-3530938197-create-turbo@latest\node_modules\create-turbo\dist\cli.js:87:2075)
    at async Command.parseAsync (C:\Users\kamin\AppData\Local\Temp\bunx-3530938197-create-turbo@latest\node_modules\commander\lib\command.js:935:5) {
  shortMessage: 'Command failed with exit code 3: bun install',
  command: 'bun install',
  escapedCommand: 'bun install',
  exitCode: 3,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'bun install v1.0.33-canary.10 (931e04b0)\n' +
    '\n' +
    'Panic: reached unreachable code\n' +
    '\n' +
    "bun has crashed :'(\n" +
    '\n' +
    '----- bun meta -----\n' +
    'Bun v1.0.33-canary.10 (931e04b0) Windows x64 \n' +
    'InstallCommand: \n' +
    'Elapsed: 47ms | User: 0ms | Sys: 0ms\n' +
    'RSS: 45.25MB | Peak: 45.25MB | Commit: 90.95MB | Faults: 11232\n' +
    '----- bun meta -----\n' +
    '\n' +
    '0   00007FF7F46B8258\n' +
    '1   ???\n' +
    '2   ???\n' +
    '3   ???\n' +
    '4   ???\n' +
    '5   ???\n' +
    '6   ???\n' +
    '7   ???\n' +
    '8   ???\n' +
    '9   ???\n' +
    '10  ???\n' +
    '11  ???\n' +
    '12  ???\n' +
    '13  ???\n' +
    '14  ???\n' +
    '15  ???\n' +
    '\n' +
    'Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord\n' +
    '\n' +
    'thread 12564 panic: reached unreachable code\n' +
    '???:?:?: 0x7ff7f3367467 in ??? (bun.exe)\n' +
    '???:?:?: 0x7ff7f32ed034 in ??? (bun.exe)\n' +
    '???:?:?: 0x7ff7f31fe477 in ??? (bun.exe)\n' +
    '???:?:?: 0x7ff7f31f81c7 in ??? (bun.exe)\n' +
    '???:?:?: 0x7ff7f31f66dc in ??? (bun.exe)\n' +
    '???:?:?: 0x7ff7f3203736 in ??? (bun.exe)\n' +
    '???:?:?: 0x7ff7f3236e0a in ??? (bun.exe)\n' +
    '???:?:?: 0x7ff7f3254b29 in ??? (bun.exe)\n' +
    '???:?:?: 0x7ff7f326be25 in ??? (bun.exe)\n' +
    '???:?:?: 0x7ff7f331aeea in ??? (bun.exe)\n' +
    '???:?:?: 0x7ff7f30516f4 in ??? (bun.exe)\n' +
    '???:?:?: 0x7ff7f5b6e923 in ??? (bun.exe)\n' +
    '???:?:?: 0x7ffb8217257c in ??? (KERNEL32.DLL)\n' +
    '???:?:?: 0x7ffb8408aa57 in ??? (ntdll.dll)',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by kaminskypavel** [comment]
tried again, does not reproduce. closing
