### ISSUE TITLE
Bun fails to compile project in cloudflare pages, pnpm works

### ISSUE THREAD

**Issue by nikivdev** [oven-sh/bun#9624]
### What version of Bun is running?

1.0.33+931e04b01

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

1. fork https://github.com/nikitavoloboev/nikiv.dev
2. add git project to cloudflare pages
3. `rm pnpm-lock.yaml && bun i` , then commit
4. it will break the build with 

<img width="1058" alt="image" src="https://github.com/oven-sh/bun/assets/6391776/a2970a28-7e87-4217-809f-f95677ea85df">

```
00:07:16.402	The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
00:07:16.670	[error] require() of ES Module /opt/buildhome/repo/node_modules/strip-ansi/index.js from /opt/buildhome/repo/node_modules/wide-align/node_modules/string-width/index.js not supported.
00:07:16.670	Instead change the require of /opt/buildhome/repo/node_modules/strip-ansi/index.js in /opt/buildhome/repo/node_modules/wide-align/node_modules/string-width/index.js to a dynamic import() which is available in all CommonJS modules.
00:07:16.671	  Instead change the require of node_modules/strip-ansi/index.js in /opt/buildhome/repo/node_modules/wide-align/node_modules/string-width/index.js to a dynamic import() which is available in all CommonJS modules.
00:07:16.671	  at Object.<anonymous> (node_modules/wide-align/node_modules/string-width/index.js:2:19)
00:07:16.671	  at Object.<anonymous> (node_modules/wide-align/align.js:2:19)
00:07:16.671	  at Object.<anonymous> (node_modules/gauge/render-template.js:2:13)
00:07:16.671	  at Object.<anonymous> (node_modules/gauge/plumbing.js:3:22)
00:07:16.672	  at Object.<anonymous> (node_modules/gauge/index.js:2:16)
00:07:16.672	  at Object.<anonymous> (node_modules/npmlog/log.js:3:13)
00:07:16.672	  at Object.<anonymous> (node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js:23:13)
00:07:16.672	  at Object.<anonymous> (node_modules/@vercel/nft/out/analyze.js:22:40)
00:07:16.672	  at Object.<anonymous> (node_modules/@vercel/nft/out/node-file-trace.js:31:35)
00:07:16.672	  at Object.<anonymous> (node_modules/@vercel/nft/out/index.js:22:25) 
```

However with `pnpm i` instead, it works.

It's due to bun using old stale lockfile for some reason.

### What is the expected behavior?

It deploys with bun. Like with pnpm:

<img width="1119" alt="image" src="https://github.com/oven-sh/bun/assets/6391776/dabada08-ba4c-4fb1-a803-dbf25d3d4cff">

**Comment by Jarred-Sumner** [comment]
looks like a peer dependency hoisting bug @dylan-conway

**Comment by Electroid** [comment]
Could you add a `bun --revision` statement to your build script to see which version of Bun is running in CI?
