### ISSUE TITLE
Crash when loading `"esm"` npm package

### ISSUE THREAD

**Issue by AriesAlex** [oven-sh/bun#9778]
### What version of Bun is running?

1.1.0

### What platform is your computer?

Microsoft Windows NT 10.0.22635.0 x64

### What steps can reproduce the bug?

`mkdir esm-test; cd esm-test; echo "require('esm')(module)" > main.js; npm init -y; bun i esm; bun main.js`

```
error: process.binding("fs") is not implemented in Bun. Track the status & thumbs up the issue: https://github.com/oven-sh/bun/issues/3546
      at C:\Users\cawa1\Desktop\esm-test\esm-test\esm-test\esm-test\esm-test\esm-test\node_modules\esm\esm.js:1:68254
      at C:\Users\cawa1\Desktop\esm-test\esm-test\esm-test\esm-test\esm-test\esm-test\node_modules\esm\esm.js:1:76017
      at C:\Users\cawa1\Desktop\esm-test\esm-test\esm-test\esm-test\esm-test\esm-test\node_modules\esm\esm.js:1:56312
      at C:\Users\cawa1\Desktop\esm-test\esm-test\esm-test\esm-test\esm-test\esm-test\node_modules\esm\esm.js:1:346540
      at C:\Users\cawa1\Desktop\esm-test\esm-test\esm-test\esm-test\esm-test\esm-test\node_modules\esm\esm.js:1:346649
      at C:\Users\cawa1\Desktop\esm-test\esm-test\esm-test\esm-test\esm-test\esm-test\node_modules\esm\esm.js:1:517868
      at C:\Users\cawa1\Desktop\esm-test\esm-test\esm-test\esm-test\esm-test\esm-test\node_modules\esm\esm.js:1:523113
      at e (C:\Users\cawa1\Desktop\esm-test\esm-test\esm-test\esm-test\esm-test\esm-test\node_modules\esm\esm.js:1:523995)
      at get (C:\Users\cawa1\Desktop\esm-test\esm-test\esm-test\esm-test\esm-test\esm-test\node_modules\esm\esm.js:1:523911)

uh-oh: attempt to use null value
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.1.0-canary.58 (83a99bf1) Windows x64
AutoCommand: Bun.stdin(2)
Builtins: "bun:main" "node:buffer" "node:console" "node:crypto" "node:fs" "node:module" "node:path" "node:string_decoder" "node:timers" "node:url" "node:util" "node:util/types" "node:vm" "node:punycode" "node:repl" "node:inspector"
Elapsed: 141ms | User: 62ms | Sys: 15ms
RSS: 0.14GB | Peak: 0.14GB | Commit: 0.18GB | Faults: 33369
----- bun meta -----

0   00007FF6BE889B78
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???
10  ???
11  ???
12  ???
13  ???
14  ???
15  ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 13336 panic: attempt to use null value
???:?:?: 0x7ff6bd51ca67 in ??? (bun.exe)
???:?:?: 0x7ff6bd644530 in ??? (bun.exe)
???:?:?: 0x7ff6bfa73245 in ??? (bun.exe)
???:?:?: 0x7ff6bf8bb08b in ??? (bun.exe)
???:?:?: 0x7ff6bd826a3a in ??? (bun.exe)
???:?:?: 0x7ff6bd556b94 in ??? (bun.exe)
???:?:?: 0x7ff6bf99c1aa in ??? (bun.exe)
???:?:?: 0x7ff6bd4cea82 in ??? (bun.exe)
???:?:?: 0x7ff6bd4f7e4a in ??? (bun.exe)
???:?:?: 0x7ff6bd4e6234 in ??? (bun.exe)
???:?:?: 0x7ff6bd211603 in ??? (bun.exe)
???:?:?: 0x7ff6bfd474f3 in ??? (bun.exe)
???:?:?: 0x7ff9eff8257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ff9f15aaa47 in ??? (ntdll.dll)
```

also without `(module)`:

```
uh-oh: attempt to use null value
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.1.0-canary.58 (83a99bf1) Windows x64
AutoCommand: Bun.stdin(2)
Builtins: "bun:main" "node:buffer" "node:console" "node:crypto" "node:fs" "node:module" "node:path" "node:string_decoder" "node:timers" "node:url" "node:util" "node:util/types" "node:vm" "node:punycode" "node:repl" "node:inspector"
Elapsed: 115ms | User: 46ms | Sys: 0ms
RSS: 130.58MB | Peak: 130.58MB | Commit: 0.18GB | Faults: 32289
----- bun meta -----

0   00007FF6BE889B78
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???
10  ???
11  ???
12  ???
13  ???
14  ???
15  ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 19888 panic: attempt to use null value
???:?:?: 0x7ff6bd51ca67 in ??? (bun.exe)
???:?:?: 0x7ff6bd644530 in ??? (bun.exe)
???:?:?: 0x7ff6bfa73245 in ??? (bun.exe)
???:?:?: 0x7ff6bf8bb08b in ??? (bun.exe)
???:?:?: 0x7ff6bd826a3a in ??? (bun.exe)
???:?:?: 0x7ff6bd55705a in ??? (bun.exe)
???:?:?: 0x7ff6bf99c1aa in ??? (bun.exe)
???:?:?: 0x7ff6bd4cea82 in ??? (bun.exe)
???:?:?: 0x7ff6bd4f7e4a in ??? (bun.exe)
???:?:?: 0x7ff6bd4e6234 in ??? (bun.exe)
???:?:?: 0x7ff6bd211603 in ??? (bun.exe)
???:?:?: 0x7ff6bfd474f3 in ??? (bun.exe)
???:?:?: 0x7ff9eff8257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ff9f15aaa47 in ??? (ntdll.dll)
```

also in production project instead of those errors Im getting:

`TypeError: undefined is not an object (evaluating 'se.fs.internalModuleStat')`

but can't repro this.
but esm uses internalModuleStat: https://github.com/standard-things/esm/tree/master
seems like it's not implemented in bun?

I use esm in prod legacy project so I can't even start it

**Comment by Jarred-Sumner** [comment]
We'll fix this crash, but note that In Bun, you don't need to use the `esm` module to load ESM. You can use import and require in the same file. You can import CommonJS modules and CommonJS modules can require ES modules. All of that just works.

**Comment by Jarred-Sumner** [comment]
It would probably be worthwhile for us to make `require("esm")` a no-op since its a very popular package in legacy projects

**Comment by jdalton** [comment]
👋 Author of the [`esm`](https://github.com/standard-things/esm) package here. The `esm` repo has been archived and no further development has been done on it for years. The last tested version was Node 10 or so (5 years ago).

I don't think Bun should be in the business of no-oping old packages though it might be worthwhile to compare how Node and Bun fail differently.

**Comment by jdalton** [comment]
The `esm` package did rely on a few `bindings` and fell back where possible. Some bindings may have been critical at the time. That kind of project required a considerable amount of babysitting to keep in sync with Node's updated internals and bindings (as they change frequently-ish).
