### ISSUE TITLE
Implement subshell support in Bun Shell

### ISSUE THREAD

**Issue by louisescher** [oven-sh/bun#9781]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

1. Use `bunx create astro@latest` to create a new Astro project
2. cd into the project & run `bun install`

### What is the expected behavior?

`bun install` should install all modules, then finish

### What do you see instead?

The installation will fail with the following error: 
```sh
C:\Users\louis\Documents\source\projects\personal\websites\louisescher.dev\helpless-hubble>bun install
bun install v1.1.0 (5903a614)
  ⚙️  esbuild [1/3] error: Failed to run script C:\Users\louis\Documents\source\projects\personal\websites\louisescher.dev\helpless-hubble\node_modules\sharp\[eval] due to errror Unexpected `(`, subshells are currently not supported right now. Escape the `(` or open a GitHub issue.
```

**Comment by torn4dom4n** [comment]
I have a repo using Bun. When the first time I run `bun install`, I get this error:

```
bun install v1.1.0 (5903a614)
  📦 Installing [621/654] error: Failed to run script C:\Users\Windows\Documents\GitHub\MedPocket\18-months\node_modules\astro\node_modules\sharp\[eval] due to error Unexpected `(`, subshells are currently not supported right now. Escape the `(` or open a GitHub issue.

error: install script from "sharp" exited with 1
```

After that, I ran `bun install` again and it worked.

I'm using bun v1.1.0 and Windows 11.

**Comment by aczw** [comment]
For me, `bun install` worked as well after a few tries, but attempting to start the local dev server throws me an `AstroError` about not being able to find `sharp`. See:

![image](https://github.com/oven-sh/bun/assets/79176651/0f3a3c8d-bbb1-48e3-80c6-773b5cac74f4)

**Comment by Jarred-Sumner** [comment]
We need to implement subshell support in the Bun Shell. We will do this soon

**Comment by torn4dom4n** [comment]
@Jarred-Sumner I still have a few errors with Bun v1.1.1. With sharp

```
bun install v1.1.1 (ca1dbb4e)
node:internal/modules/cjs/loader:1143
  throw err;
  ^

Error: Cannot find module 'streamx'
Require stack:
- /home/runner/work/torn4dom4n.github.io/torn4dom4n.github.io/node_modules/tar-stream/extract.js
- /home/runner/work/torn4dom4n.github.io/torn4dom4n.github.io/node_modules/tar-stream/index.js
- /home/runner/work/torn4dom4n.github.io/torn4dom4n.github.io/node_modules/tar-fs/index.js
- /home/runner/work/torn4dom4n.github.io/torn4dom4n.github.io/node_modules/astro/node_modules/sharp/install/libvips.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:1[5](https://github.com/torn4dom4n/torn4dom4n.github.io/actions/runs/8564347797/job/23470749947#step:4:6))
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/runner/work/torn4dom4n.github.io/torn4dom4n.github.io/node_modules/tar-stream/extract.js:1:48)
    at Module._compile (node:internal/modules/cjs/loader:13[6](https://github.com/torn4dom4n/torn4dom4n.github.io/actions/runs/8564347797/job/23470749947#step:4:7)4:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/torn4dom4n.github.io/torn4dom4n.github.io/node_modules/tar-stream/extract.js',
    '/home/runner/work/torn4dom4n.github.io/torn4dom4n.github.io/node_modules/tar-stream/index.js',
    '/home/runner/work/torn4dom4n.github.io/torn4dom4n.github.io/node_modules/tar-fs/index.js',
    '/home/runner/work/torn4dom4n.github.io/torn4dom4n.github.io/node_modules/astro/node_modules/sharp/install/libvips.js'
  ]
}

Node.js v1[8](https://github.com/torn4dom4n/torn4dom4n.github.io/actions/runs/8564347797/job/23470749947#step:4:9).20.0

error: install script from "sharp" exited with 1
Error: Process completed with exit code 1.
```
You can see the first log at [here](https://github.com/torn4dom4n/torn4dom4n.github.io/actions/runs/8564347797/job/23470749947).

I also have another issue with the same repo happening on Vercel:

```
[09:58:16.481] Running build in Washington, D.C., USA (East) – iad1
[09:58:17.316] Cloning github.com/torn4dom4n/torn4dom4n.github.io (Branch: main, Commit: c42d7a2)
[09:58:18.494] Cloning completed: 1.174s
[09:58:21.239] Restored build cache
[09:58:21.380] Running "vercel build"
[09:58:22.828] Vercel CLI 33.6.3
[09:58:23.920] Running "install" command: `bun install`...
[09:58:24.003] bun install v1.0.36 (40f61ebb)
[09:58:25.704] /vercel/path0/node_modules/vite/node_modules/esbuild/install.js:133
[09:58:25.705]     throw new Error(`Expected ${JSON.stringify(versionFromPackageJSON)} but got ${JSON.stringify(stdout)}`);
[09:58:25.705]           ^
[09:58:25.705] 
[09:58:25.705] Error: Expected "0.20.2" but got "0.19.12"
[09:58:25.705]     at validateBinaryVersion (/vercel/path0/node_modules/vite/node_modules/esbuild/install.js:133:11)
[09:58:25.705]     at /vercel/path0/node_modules/vite/node_modules/esbuild/install.js:286:5
[09:58:25.705] 
[09:58:25.705] Node.js v18.19.1
[09:58:25.705] 
[09:58:25.705] error: postinstall script from "esbuild" exited with 1
[09:58:25.718] Error: Command "bun install" exited with 1
[09:58:26.615] 
```

I just want to know How could I get the latest Bun on Vercel.

**Comment by louisescher** [comment]
Can you try to add `streamx` to the dependencies? That might help with the GitHub deployment. 
I suspect the Vercel build fails because of some version mismatch between packages, but I would need to see the repo to validate that.

**Comment by torn4dom4n** [comment]
> Can you try to add `streamx` to the dependencies? That might help with the GitHub deployment. I suspect the Vercel build fails because of some version mismatch between packages, but I would need to see the repo to validate that.

I tried a few times to re-run GitHub actions and sometimes it works.
