### ISSUE TITLE
Projects use Refine (refine.dev) is not working on Windows

### ISSUE THREAD

**Issue by vinhphm** [oven-sh/bun#9821]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

1. Use [refine.dev](https://refine.dev/) in the web to make a project that uses Vite.
2. Download and run `bun install`
3. Run `bun run dev`

### What is the expected behavior?

Dev server should run.

### What do you see instead?

```
$ refine dev
node:internal/modules/cjs/loader:1143
  const err = new Error(message);
              ^

Error: Cannot find module '.bin/vite'
Require stack:
- C:\Users\vinh\Development\refine-project\node_modules\@refinedev\cli\dist\cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Function.resolve (node:internal/modules/helpers:190:19)
    at Object.getBin (C:\Users\pvinh002\Development\refine-project\node_modules\@refinedev\cli\dist\cli.js:4:1020)
    at Command.Bo (C:\Users\pvinh002\Development\refine-project\node_modules\@refinedev\cli\dist\cli.js:17:1400)
    at Command.listener [as _actionHandler] (C:\Users\pvinh002\Development\refine-project\node_modules\commander\lib\command.js:482:17)
    at C:\Users\vinh\Development\refine-project\node_modules\commander\lib\command.js:1264:65
    at C:\Users\vinh\Development\refine-project\node_modules\commander\lib\command.js:1155:33
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\vinh\\Development\\refine-project\\node_modules\\@refinedev\\cli\\dist\\cli.js'
  ]
}
```

**Comment by EmbiiFox** [comment]
I face the same issues 🐞
