### ISSUE TITLE
turborepo next not working with bun

### ISSUE THREAD

**Issue by darklight9811** [oven-sh/bun#9869]
### What version of Bun is running?

1.1.0-canary.58+83a99bf19

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Use the repo:
```
https://github.com/darklight9811/reencontre-me/tree/bun
```

Run bun install and them `bun --bun run dev --scope=app`

### What is the expected behavior?

For the code to run the server and start it

### What do you see instead?

A bunch of errors are thrown in the terminal (its trying to log something), but finally throws a:
```
app:dev: error: Attempt to export a nullable value for "TextDecoderStream"
app:dev: 
app:dev:       at defineProperties (C:\projects\javascript\yamiassu\company\reencontre-me\node_modules\next\dist\compiled\edge-runtime\index.js:1:711758)
app:dev:       at addPrimitives (C:\projects\javascript\yamiassu\company\reencontre-me\node_modules\next\dist\compiled\edge-runtime\index.js:1:710442)
app:dev:       at extend (C:\projects\javascript\yamiassu\company\reencontre-me\node_modules\next\dist\compiled\edge-runtime\index.js:1:705225)
app:dev:       at new VM (C:\projects\javascript\yamiassu\company\reencontre-me\node_modules\next\dist\compiled\edge-runtime\index.js:1:712552)
app:dev:       at new EdgeVM (C:\projects\javascript\yamiassu\company\reencontre-me\node_modules\next\dist\compiled\edge-runtime\index.js:1:705155)
app:dev:       at C:\projects\javascript\yamiassu\company\reencontre-me\node_modules\next\dist\server\web\sandbox\context.js:208:38
```

### Additional information

This is a opensource project for an app that helps find missing people and pets

**Comment by wesleycoder** [comment]
I've run in the same issue when trying go use Next.js with Bun in a Docker container for deploy with fly.io in a monorepo setup.

I'll try to isolate a reproduction repository with my use-case w/ Docker.

**Comment by darklight9811** [comment]
@wesleycoder I don't know if its the same case as you, but bun 1.1.17 fixed it for me. It was an issue with bun install, if I installed everything with node, it would work when running bun.

I will close it for now since the bug I reported was fixed

**Comment by darklight9811** [comment]
Actually the error just reappeared out of nowhere, but a solution for me is to install using yarn and just run dev with bun

**Comment by darklight9811** [comment]
related
- #12178 
- #5648

**Comment by wesleycoder** [comment]
I managed to fix my issue with the help of turborepo, running the prune command with the --docker flag was enough to mitigate most of the problems for me.
Maybe you can try prune and see if it helps you:
https://turbo.build/repo/docs/reference/prune

**Comment by dylan-conway** [comment]
`TextEncoderStream` and `TextDecoderStream` support was added in Bun v1.1.23. Closing as complete.

If you continue to have issues with turborepo or `TextDecoderStream` please open a new issue or comment here and I will reopen this issue.
