### ISSUE TITLE
ResolveMessage message property read-only status breaks ESLint error feedback

### ISSUE THREAD

**Issue by adamaveray** [oven-sh/bun#9919]
### What version of Bun is running?

1.0.35

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

Here are the minimum steps to reproduce:

```sh
bun install eslint
echo '{ "plugins": ["unknown-plugin"] }' > .eslintrc.json

bun --bun x eslint . # Shows unclear error
npx eslint . # Shows understandable error
```

### What is the expected behavior?

This is the correct error output when running with Node:

<details>
    Oops! Something went wrong! :(

    ESLint: 8.57.0

    ESLint couldn't find the plugin "eslint-plugin-unknown-plugin".

    (The package "eslint-plugin-unknown-plugin" was not found when loaded as a Node module from the directory "…".)

    It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

        npm install eslint-plugin-unknown-plugin@latest --save-dev

    The plugin "eslint-plugin-unknown-plugin" was referenced from the config file in ".eslintrc.json".

    If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

</details>

### What do you see instead?

This is the unclear error output when running with Bun:

<details>
    Oops! Something went wrong! :(

    ESLint: 8.57.0

    TypeError: Attempted to assign to readonly property.
        at _loadPlugin (…/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3452:12)
        at <anonymous> (…/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:815:40)
        at reduce (:1:11)
        at _normalizeObjectConfigDataBody (…/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:701:112)
        at _normalizeObjectConfigData (…/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:676:26)
        at loadInDirectory (…/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:622:111)
        at _loadConfigInAncestors (…/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:1070:57)
        at getConfigArrayForFile (…/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:1036:119)
        at _iterateFilesRecursive (…/node_modules/eslint/lib/cli-engine/file-enumerator.js:131:62)
        at iterateFiles (…/node_modules/eslint/lib/cli-engine/file-enumerator.js:73:47)
</details>

### Additional information

The issue occurs when ESLint overwrites the `error.message` value [on this line in `config-array-factory.js`](https://github.com/eslint/eslintrc/blob/fb8d7ffbb27214686318a07e16ac8878aaafc805/lib/config-array-factory.js#L1105) after failing to resolve a referenced plugin. Since the error object is a Bun ResolveMessage instance, the `message` property of which is read-only, this causes a different error, obfuscating what the issue actually is. For compatibility with NodeJS, that property should be writeable.

There is also [an open issue in ESLint](https://github.com/oven-sh/bun/issues/6730).

**Comment by adamaveray** [comment]
I had too many tabs open and thought the linked relevant issue was on the ESLint project, but it's actually a Bun issue. I will close this one and move the discussion there.
