### ISSUE TITLE
Error packaging elysia server "Right side of assignment cannot be destructured"

### ISSUE THREAD

**Issue by aishuaikang** [oven-sh/bun#9994]
### What version of Bun is running?

1.1.1+ca1dbb4eb

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

`bun build ./src/index.ts --compile --minify --outfile ./build/index`
Execute after packaging and request a response
![image](https://github.com/oven-sh/bun/assets/68257609/2108ef9f-5663-4ee8-aa0c-e6347f56d979)
If `--minify` is removed, then it is normal
bun build ./src/index.ts --compile --outfile ./build/index
![image](https://github.com/oven-sh/bun/assets/68257609/44589102-0801-47a3-8290-dd63c4dc6451)

**Comment by Electroid** [comment]
Is it possible to share the code? If you are also about to make a minimal reproduction that would be great.

**Comment by aishuaikang** [comment]
> Is it possible to share the code? If you are also about to make a minimal reproduction that would be great.可以共享代码吗？如果你也想做一个最小的复制，那就太好了。

https://github.com/aishuaikang/xablog

**Comment by aishuaikang** [comment]
1、`bun install`
2、Configure the database connection in .env
3、exec`bun run mysql:push`
3、`bun run build` or `bun run build:exec`
4. Run index.js or index executable file
5. Request `/auth`

**Comment by aishuaikang** [comment]
#10065 
Of course, after solving the problem of `--minify`, there is another problem.

**Comment by YDrogen** [comment]
Having the same issue
Bun revision: Bun 1.1.3+2615dc742
Platform: Darwin 23.4.0 arm64 arm
Using Elysia with cookies. Error comes up when getting a cookie value.
```ts
new Elysia().post('', ({ cookie }) => {
  // so far so good...

  const value = cookie.example;
  // ^ error here
})
```

Building with: `NODE_ENV=production bun build --entrypoints src/index.ts --outfile exe/app --compile --minify --sourcemap --target bun`
Removing `--minify` solves this issue.

Thanks @aishuaikang ! I couldn't have found it by myself!

**Comment by esciullo** [comment]
I have the same issue using Elysia. Removing `--minify` solves this issue.

**Comment by Snafuh** [comment]
I'm having the issue with Elysia as well, but unfortunately it also happens with non-minfied code.

**Comment by paperdave** [comment]
is this bug https://github.com/elysiajs/elysia/issues/724 or the re-opened https://github.com/elysiajs/elysia/issues/844?

**Comment by wintercounter** [comment]
I have the same issue but just by simply using bun with `satori`.

```
bun scripts/myScript.js
```

```
TypeError: Right side of assignment cannot be destructured
      at /home/..../node_modules/satori/dist/index.js:5:51424
      at /home/..../node_modules/satori/dist/index.js:5:52230
1 | var Tl=Object.create;var Pr=Object.defineProperty;var Al=Object.getOwnPropertyDescriptor;var Ol=Object.getOwnPropertyNames;var Pl=Object.getPrototypeOf,Bl=Object.prototype.hasOwnProperty;var yn=(e,t)=>()=>
(e&&(t=e(e=0)),t);var k=(e,t)=>()=>(t||e((t={exports:{}}).exports,t),t.exports),xn=(e,t)=>{for(var n in t)Pr(e,n,{get:t[n],enumerable:!0})},Go=(e,t,n,r)=>{if(t&&typeof t=="object"||typeof t=="function")for(let
 i of Ol(t))!Bl.call(e,i)&&i!==n&&Pr(e,i,{get:()=>t[i],enumerable:!(r=Al(t,i))||r.enumerable});return e};var Il=(e,t,n)=>(n=e!=null?Tl(Pl(e)):{},Go(t||!e||!e.__esModule?Pr(n,"default",{value:e,enumerable:!0}):
n,e)),Br=e=>Go(Pr({},"__esModule",{value:!0}),e);var jo={};xn(jo,{getYogaModule:()=>Rl});async function Rl(){let{default:e}=await import("yoga-wasm-web/asm");return e()}var Ho=yn(()=>{});var Xn=k(Yn=>{"use strict";Object.defineProperty(Yn,"__esModule",{value:!0});Object.defineProperty(Yn,"default",{enumerable:!0,get:()=>Vf});function Vf(e){if(e=`${e}`,e==="0")return"0";if(/^[+-]?(\d+|\d*\.\d+)(e[+- | ... truncated 
2 | In order to be iterable, non-array objects must have a [Symbol.iterator]() method.`)}return n=e[Symbol.iterator](),n.next.bind(n)}function Ic(e,t){if(e){if(typeof e=="string")return ls(e,t);var n=Object.pr
ototype.toString.call(e).slice(8,-1);if(n==="Object"&&e.constructor&&(n=e.constructor.name),n==="Map"||n==="Set")return Array.from(e);if(n==="Arguments"||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n))retu
rn ls(e,t)}}function ls(e,t){(t==null||t>e.length)&&(t=e.length);for(var n=0,r=new Array(t);n<t;n++)r[n]=e[n];return r}function fs(e,t){for(var n=0;n<t.length;n++){var r=t[n];r.enumerable=r.enumerable||!1,r.co
nfigurable=!0,"value"in r&&(r.writable=!0),Object.defineProperty(e,r.key,r)}}function Rc(e,t,n){return t&&fs(e.prototype,t),n&&fs(e,n),e}function Lc(e,t){e.prototype=Object.create(t.prototype),e.prototype.constructor=e,si(e,t)}function si(e,t){return si=Object.setPrototypeOf||function(r,i){return r.__proto__=i,r},si(e,t)}var Mc=function(e){Lc(t,e);function t(r){var i;return i=e.call(this,r)||this,i | ... truncated 
3 | `),m=x.length-1,m>0?(S=u+m,v=g-x[m].length):(S=u,v=o),y=w.comment,u=S,p=S,c=g-v):l===w.slash?(g=s,y=l,p=u,c=s-o,a=g+1):(g=Gp(n,s),y=w.word,p=u,c=g-o),a=g+1;break}t.push([y,u,s-o,p,c,s,a]),v&&(o=v,v=null),s
=a}return t}});var Ys=k((ar,Vs)=>{"use strict";ar.__esModule=!0;ar.default=void 0;var Yp=ve(li()),$i=ve(ci()),Xp=ve(hi()),qs=ve(Di()),Qp=ve(bi()),Kp=ve(xi()),qi=ve(wi()),Jp=ve(Si()),zs=fn(Oi()),Zp=ve(Bi()),zi=
ve(Ri()),e0=ve(Mi()),t0=ve(Ls()),F=fn($s()),C=fn(Ni()),r0=fn(ne()),Y=Ut(),nt,Ui;function Hs(){if(typeof WeakMap!="function")return null;var e=new WeakMap;return Hs=function(){return e},e}function fn(e){if(e&&e
.__esModule)return e;if(e===null||typeof e!="object"&&typeof e!="function")return{default:e};var t=Hs();if(t&&t.has(e))return t.get(e);var n={},r=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var i in e)if(Object.prototype.hasOwnProperty.call(e,i)){var o=r?Object.getOwnPropertyDescriptor(e,i):null;o&&(o.get||o.set)?Object.defineProperty(n,i,o):n[i]=e[i]}return n.default=e,t&&t.set(e,n) | ... truncated 
4 |   `+mu(u):`
5 |   in CSS rule \`${u}: ${s}\`.${mu(u)}`))}}}if(n.backgroundImage){let{backgrounds:i}=ff(n);n.backgroundImage=i}(n.maskImage||n.WebkitMaskImage)&&(n.maskImage=hu(n));let r=gf(n.fontSize,t.fontSize);typeof n.
fontSize<"u"&&(n.fontSize=r),n.transformOrigin&&(n.transformOrigin=Bn(n.transformOrigin,r));for(let i in n){let o=n[i];if(i==="lineHeight")typeof o=="string"&&o!=="normal"&&(o=n[i]=O(o,r,r,t,!0)/r);else{if(typ
eof o=="string"){let u=O(o,r,r,t);typeof u<"u"&&(n[i]=u),o=n[i]}if(typeof o=="string"||typeof o=="object"){let u=bu(o);u&&(n[i]=u),o=n[i]}}if(i==="opacity"&&typeof o=="number"&&(n.opacity=o*t.opacity),i==="tra
nsform"){let u=o;for(let s of u){let a=Object.keys(s)[0],l=s[a],f=typeof l=="string"?O(l,r,r,t)??l:l;s[a]=f}}if(i==="textShadowRadius"){let u=o;n.textShadowRadius=u.map(s=>O(s,r,0,t,!1))}if(i==="textShadowOffset"){let u=o;n.textShadowOffset=u.map(({height:s,width:a})=>({height:O(s,r,0,t,!1),width:O(a,r,0,t,!1)}))}}return n}function gf(e,t){if(typeof e=="number")return e;try{let n=new Le(e);switch(n | ... truncated 

TypeError: Right side of assignment cannot be destructured
      at /home/..../node_modules/satori/dist/index.js:5:51424
      at /home/..../node_modules/satori/dist/index.js:5:52230
```

**Comment by albasyir** [comment]
i have problem also in nestjs

```
[Nest] 7  - 12/02/2024, 9:29:10 AM VERBOSE [019386b3-cb64-7042-b3be-66e9bc360b30][RPC][NotificationService.sendEmail] sending using email dev@bsianakyatim.id
76 |       currentToken += StringPrototypeSubstring.@call(altNames, offset, nextSep), ArrayPrototypePush.@call(result, currentToken), currentToken = "", offset = nextSep + 2;
77 |     else
78 |       currentToken += StringPrototypeSubstring.@call(altNames, offset), offset = altNames.length;
79 |   }
80 |   return ArrayPrototypePush.@call(result, currentToken), result;
81 | function checkServerIdentity(hostname, cert) {
                                 ^
TypeError: Right side of assignment cannot be destructured
 code: "ESOCKET"
      at checkServerIdentity (node:tls:81:29)
      at handshake (node:net:90:14)
Error: {
 "code": "ESOCKET",
 "command": "CONN"
}
[Nest] 7  - 12/02/2024, 9:29:10 AM   ERROR [019386b3-cb64-7042-b3be-66e9bc360b30][RPC][NotificationClientController.sendEmail] Error: {
[019386b3-cb64-7042-b3be-66e9bc360b30] "code": "ESOCKET",
[019386b3-cb64-7042-b3be-66e9bc360b30] "command": "CONN"

```
